### ISSUE TITLE
More documentation on transactions and isolation levels

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#1140]
We have quite extended internal documentation, but rather limited public one. The public one we have is basically this: https://github.com/Starcounter/Starcounter/wiki/More-on-Transactions.

I think we need to extend the documentation and describe things like the effect using long-running transactions can have, and that the snapshot isolation you get when using scopes can turn into read committed if there is a yield.

This issue should be be assigned to @k-rus or @Starcounter-Jack.

**Comment by dan31** [comment]
Will be covered in https://github.com/Starcounter/Starcounter/issues/1140.
