### ISSUE TITLE
Add ability for developers to force snapshot isolation or fail

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#1143]
We currently support transactions with snapshot isolation via the following managed construct:

``` c#
Db.Transaction(() => { ... });
```

However, under certain circumstances (if the transaction should take a long time for example), the isolation level will change and instead become more like "read committed".

We are disucssion ways to add support for more isolation levels, and to allow the developer to specify that only snapshot should be accepted and to have Starcounter retry until it succeeds. But since we are not there yet (and it's a somewhat bigger job), we will introduce the following in the meantime:

``` c#
static void Transaction(Action a, bool forceSnapshot = false);
```

In this case, if the developer specify:

``` c#
Db.Transaction(() => { ... }, true);
```

and the transaction comes to a state where Starcounter have to switch to "read committed" (i.e. doing a new snapshot), the transaction instead will be aborted and an exception will be raised.

This will make the managed transaction API more predictable and still operate on nearly the same principle as now.

**Comment by dan31** [comment]
In 2.3 ```Db.Transact`` is always snapshot isolation.
