### ISSUE TITLE
Host Starcounter in Mono

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#122]
For Posix environments, Mono will be used instead of the CLR to run managed Starcounter code.

### Bluestar
* Migrate REST codegen
* Migrate SQL
* Migrate hypermedia

### User code
* Migrate the Weaver
* Make sure that typed Json works with xbuild

**Comment by dan31** [comment]
.NET Core is for the resque. Obsoleting 😺
