### ISSUE TITLE
New SQL parser should fail the queries with escape strings

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1237]
The following query is an example to fail:

``` sql
SELECT E'\\xDEADBEEF
```

**Comment by dan31** [comment]
Related to https://github.com/Starcounter/Starcounter/issues/1238.

**Comment by k-rus** [comment]
> Related to #1238.

It is already referenced from the issue, which is kind of umbrella.

**Comment by andan342** [comment]
This query currently fails, as unterminated string.

Variants with no single quote, space before `\\` and no `E` also fail as a syntax error at the first `\`.

**Comment by andan342** [comment]
The variant present in **sqlparser_unittest** is `SELECT E'\xDEADBEEF'`, which is a correct SQL query (at least according to PostgreSQL). The SELECT target is represented by the list of `A_Const` (string) and `TypeName` (`E`) nodes, together representing a typed literal, i.e. a string with attached type.

Do we want to remove the use of escapes in strings altogether?

**Comment by k-rus** [comment]
Let's discuss, which approach we should go.

**Comment by k-rus** [comment]
We discussed this and decided to keep the syntax and current interpretation for now.
Archiving.
