### ISSUE TITLE
Investigate issues with some unacceptable queries in new parser

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1238]
I found several queries, which the parser should fail, but they succeed. They are marked in the source code of a regression test. I need to go through them and create separate issue for each of them. One issue #1237 is already created.

**Comment by andan342** [comment]
In the following comments, I will refer to the problematic queries in order of their appearance in **src/tests/sqlparser_unittest/queries.hpp** file.

**Comment by andan342** [comment]
**1.** 
```
select * from tbl1 union select * from tbl option index (tbl indx1)
```

The problem was with a missing rule action, when an index hint option clause is the only one used among the optional clauses to SELECT queries. (Other optional clauses are for sorting, locking, limit/offset and WITH / WITH RECURSIVE).

Also, it turned out that some fields of `Node` subclasses were added without proper reflection in `::copy()` and `::out()` methods. This included the field to store these index hint options, and also the 'generic' properties of `FunCall` and `TypeName` nodes.

**Comment by andan342** [comment]
**(6)** unclear:
the query is specified as a string `"select \u0066"`, which corresponds to an SQL query
```
select u0066
```
which is OK, since it selects a valid identifier. If my guess is right, and there's a typo, the query 
```
select \u0066
```
is invalid, since SQL does not support selecting characters, and also using escapes `\` outside a string. The correct query would be 
```
select '\u0066'
```
which selects a string literal. Unicode escapes are not processed by the parser, and are put 'as is' into the AST.

Is the idea behind this testcase is to process Unicode escapes in string literals?

**Comment by andan342** [comment]
(2): unclear:
```
select cast(col as typ<typ2>) from tble
```
appears to be a valid query. Generics can be part of type names.

Maybe, the idea is to disable casting to generic types?

**Comment by andan342** [comment]
**(3-5)** suggestion:
```
select nm.typ<typ2>.fn()

select a < b > c

select a < b , c >
```
In all these cases, the generics in `<>` are assigned to the function call, with function name being `typ` or `a`.

Our current SQL grammar allows calling functions with empty argument lists, while specifying no parentheses. However, I could not find this option mentioned in any official docs:

-  **PostgreSQL** [Calling Functions](https://www.postgresql.org/docs/9.1/static/sql-syntax-calling-funcs.html), and [Value Expressions](https://www.postgresql.org/docs/9.6/static/sql-expressions.html).
- **MS SQL Server** [Expressions ](https://msdn.microsoft.com/en-us/library/ms190286.aspx) docs. 
- **MySQL [Expression Syntax](https://dev.mysql.com/doc/refman/5.5/en/expressions.html) and **Oracle** [SQL Expressions](https://docs.oracle.com/cd/B19306_01/server.102/b14195/sqlqr03.htm) do not elaborate on function calls at all.

I would suggest to always require parentheses in function calls - this would render the queries (3-5) invalid, and make such syntactic cases less ambiguous to the user.

**Comment by andan342** [comment]
**(7-8)** fixed:
```
select B'010A010'

select X'FID13A'
```

As I understand, the idea was to validate if the *bit string* and *hex string* literals are correct. 

This check is now in place, and errors are returned for these queries, referring to the whole `B'010A010'` or `X'FID13A'` token.

**Comment by andan342** [comment]
**(9)** unclear:
```
select u1 from user u1 join user u2 on u1 != u2 and u1.useridnr = u2.useridn2 + ?
```

I can see nothing wrong with this query, from the perspective of Starcouter SQL.

In a standard SQL it would be strange to compare table aliases `u1` and `u2` for non-equality. However, in our object-oriented setting this should be perfectly fine.

It is also quite strange that the query is commented out. It should have been problematic before the #1361 fix, since `user` was a keyword. So the parser was returning a syntax error. Now it is parsed without problems.

**Comment by k-rus** [comment]
> Also, it turned out that some fields of Node subclasses were added without proper reflection in ::copy() and ::out() methods. This included the field to store these index hint options, and also the generic properties of FunCall and TypeName nodes.

These methods were not maintained. Now they are, but we have tech debts in their design, so it is easy to miss fixing them according to changes.


> If my guess is right, and there's a typo, the query
> 
> select \u0066
> is invalid, since SQL does not support selecting characters, and also using escapes \ outside a string.

The query originates from C# code, where C# translates it into single letter identifier (see line 176 in SqlProcessorTest.cs of Level1). Here the test was disabled during migration to C++. The actual call to native parser was `select f`. Thus the test should be removed from Queries.hpp.



> (2) unclear:
> 
> select cast(col as typ<typ2>) from tble
> appears to be a valid query. Generics can be part of type names.
> 
> Maybe, the idea is to disable casting to generic types?

I believe it was due to some limitation in C#. I double checked and such casting can be done with C++ templates. So I follow your suggestion that we allow such queries.


> I would suggest to always require parentheses in function calls - this would render the queries (3-5) invalid, and make such syntactic cases less ambiguous to the user.

Yes, it is necessary as everyone expects this requirement. Fix it.

> select u1 from user u1 join user u2 on u1 != u2 and u1.useridnr = u2.useridn2 + ?
> I can see nothing wrong with this query, from the perspective of Starcouter SQL.
> 
> In a standard SQL it would be strange to compare table aliases u1 and u2 for non-equality. However, in our object-oriented setting this should be perfectly fine.
> 
> It is also surprising that the query is commented out. It should have been problematic before the #1361 fix, since user was a keyword - so the parser should have been returning a syntax error. Now it is parsed without problems.

I don't see any syntactical problem either. Since it was not working, it might be was wrong expected result. I suggest to accept this query as with correct syntax.

**Comment by andan342** [comment]
**(3-5)** fixed:

Even though `TypeName` node was generated for `typ<typ2>`, and `a<b>` / `a<b,c>`, the rule was among the rules for function calls. This rule is now removed, which made some other queris in the unit test (**queries.hpp**) invalid:

```
select I.J<A>.f<A>(g)

select A.D.B<C>.F.G<A>(d,A<d>.D<s>())

select A+ D<A,F>.<B>F()
```

These queries are not tested for "incorrect syntax" exception. The changes are in **1238** branch

@k-rus : please confirm that there was no intent for putting these queries as correct ones into the test! The comment above those rules was saying *Member accesses similar to C#*

**Comment by andan342** [comment]
**(2), (6), (9)** test updated:

Queries (2) and (9) are re-enabled in the test. Query (6) is removed.

**Comment by k-rus** [comment]
> These queries are now tested for "incorrect syntax" exception. The changes are in 1238 branch
> 
> @k-rus : please confirm that there was no intent for putting these queries as correct ones into the test! The comment above those rules was saying Member accesses similar to C#

To make final decision it is necessary to check the specification of C++ standard and C# standard. @andan342 Can you look at them?

**Comment by andan342** [comment]
**C# Reference** is available for download here: https://www.microsoft.com/en-us/download/confirmation.aspx?id=7029

Sections 3.8 and  7.6.4 define that constructs like `a.b<c>` are allowed, but the interpretation is limited to the following:
- if `a` is a namespace, and `b<c>` is a generic class defined there, the expression is type-valued. 
- if `a` is a variable bound to a class instance, and that class contains a generic method `b<c>`, the expression is *delegate* (method) valued, or if that class contains a nested class `b<c>, the expression is type-valued.

As I understand, in our SQL we are not interested in type- or method-valued expressions.

**Comment by andan342** [comment]
**C++ Standard** working draft is available here:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf

Section 5.2.5 defines class member access of the form `E1.E2` or `E1->E2`, where `E2` is an *id-expression*, which can be a *template-id*, for example, `b<c>`.

If `E2` is a data member, the result is *lvalue*, otherwise, if `E2` is a function member the expression `E1.E2` is method-valued.

**Comment by andan342** [comment]
A simple check with VS2015 shows that it is impossible to declare a C++ class with a data member named like `b<c>`, only a function member.

**Comment by k-rus** [comment]
> A simple check with VS2015 shows that it is impossible to declare a C++ class with a data member named like b<c>, only a function member.

However, we have properties, which are more like functions, but without arguments and parentheses. So it feels like we should continue support generics in the path for both functions and non-functions, so that we don't close the door for future implementations.

Is it feasible?

**Comment by andan342** [comment]
It is.

This would revert the fix for (3-5), and make those queries valid again.

However, I'm curious what might be the semantics of supplying generics with a property dereference?
One cannot use it to provide the desired value type, since the property types are defined at compile time, thus calling `cheese.expires<Date>`  or `cheese.expires<String>` is not the right use.

**Comment by k-rus** [comment]
> However, I'm curious what might be the semantics of supplying generics with a property dereference?
> One cannot use it to provide the desired value type, since the property types are defined at compile time, thus calling cheese.expires<Date> or cheese.expires<String> is not the right use.

It is the same semantics as method with generics without arguments. It is not supported in C# now, but I don't know if it will be or not relevant in future. So I prefer keep the syntax and not use it, instead facing of reintroducing the syntax in future.

Post if you see already issues in syntax support for properties with generics.

**Comment by andan342** [comment]
The problem with queries (2) and (9) is that the error "Error: memory state is different" is thrown during the **sqlparser_unittest**

@k-rus : what was the purpose of this check?

**Comment by k-rus** [comment]
> The problem with queries (2) and (9) is that the error "Error: memory state is different" is thrown during the sqlparser_unittest
> 
> @k-rus : what was the purpose of this check?

This means that your code is leaking. Can you give a link to the commit? I hope it is not merged to develop.

**Comment by andan342** [comment]
It's in the branch **1238**. I just re-enabled these queries in the test.

I guess the leak was discovered long time ago - can't think of any other reason why these two queries were commented out.

**Comment by andan342** [comment]
regarding (3-5)
> Post if you see already issues in syntax support for properties with generics.

No issues, except that in any expression like `a.b<c>`, `b<c>` needs to be stored as a `TypeName` node, since we do not know at parse time whether `a` is a variable or a namespace.

However, we can rename `TypeName` to something like `TypeNameOrGenericProperty`, or something shorter...

How confident we are about the generic properties? @dan31 ?

**Comment by andan342** [comment]
regarding (3-5)
>  something like TypeNameOrGenericProperty
If we do not have any type-valued expressions, then expressions and types might be syntactically separated. 

If you think it's worth the effort, I can check and see if that's the case, and we can tell a *type name* from a *generic property* by their place in a query.

**Comment by k-rus** [comment]
> regarding (2) and (9)
> 
> It's in the branch 1238. I just re-enabled these queries in the test.
> 
> I guess the leak was discovered long time ago - can't think of any other reason why these two queries were commented out.

Can you create a separate issue about it in our repo?



> regarding (3-5)
> 
> something like TypeNameOrGenericProperty
> If we do not have any type-valued expressions, then expressions and types might be syntactically separated.
> 
> If you think it's worth the effort, I can check and see if that's the case, and we can tell a type name from a generic property by their place in a query.

The only place for types in expression that I can think of is casting.

Of course, it will be nice to fix that the node is meaningful, i.e., it is not a `TypeName` if it is not a type name. On the other side, I understand that grammar is complex and is not very flexible. We don't want to hack the current design of the grammar. So if it is possible to do it directly in the grammar without running in troubles or without using some other layer then it is nice, otherwise we will deal with during the first phase of the query planner.

**Comment by andan342** [comment]
regarding (2) and (9)

> Can you create a separate issue about it in our repo?

Just did - issue [#194](https://git.starcounter.org/BlueStar/level0/issues/194). It turned out that no memory leak is detected - just a misleading error message when the syntax test fails.

(the queries were expected to be wrong, where as they are valid)

**Comment by andan342** [comment]
regarding (3-5)

I have re-enabled the syntax of these queries, so now they are valid. 

An expression `a.b<c>`, is now represented as a list (see [#188](https://git.starcounter.org/BlueStar/level0/issues/188)) of an `Ident` node for `a` and an `IdentWithGenerics` node for `b<c>`, so the `TypeName` is not used in this case.

In contrast, an expression `CAST(a AS b.c<d>)` is parsed to a `TypeCast` node, where `b.c<d>` is represented by a `TypeName` node, containing the list `("b" "c") in `.names` and another `TypeName` node for `d` in `.generics`.

**Comment by andan342** [comment]
All the changes described above are merged to **develop**. 

Tests in **queries.hpp** are updated. This issue is ready to be closed.
