### ISSUE TITLE
Building HttpParser sometimes failes on build server

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1246]
I had two cases during last week when a daily build failed due to failure of building HttpParser. [One of the builds](https://scbuildserver/viewLog.html?tab=buildLog&buildTypeId=bt23&buildId=18999)

**Comment by parherman** [comment]
@alemoi I have not seen this, do you believe we can close this?

**Comment by alemoi** [comment]
I think this can be closed now. Never seen the error again after we started to build the project explicitly before Level1.
