### ISSUE TITLE
Replace def files with DLL export from compiler.h in native SQL Processor

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1249]
Depends on an example in the kernel.

**Comment by k-rus** [comment]
@alexanderstc was it already done?

**Comment by alexanderstc** [comment]
Yes,  I believe so.



On Wed, Jan 13, 2016 at 5:35 AM -0800, "Ruslan Fomkin" <notifications@github.com<mailto:notifications@github.com>> wrote:


@alexanderstc<https://github.com/alexanderstc> was it already done?

-
