### ISSUE TITLE
Finalizer/Destructor?

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#1259]
Seems like Starcounter doesn't support finalizer/destructor?
Is there any other way to clean up "child" objects on delete?

**Comment by Starcounter-Jack** [comment]
@per-samuelsson 
Bump

**Comment by dan31** [comment]
@per-samuelsson just bumped on that one, looking at the ```IEntity``` API and don't find any mental reference. Is that commit hooks which we encourage to use today to implement cascaded deletes? No IEntity today, correct?

**Comment by per-samuelsson** [comment]
> No IEntity today, correct?

Nope. Not correct. `IEntity` is still there as an optional thing to use, and still work like I describe it [here](https://github.com/Starcounter/Starcounter/issues/1259#issuecomment-27756686). It's just not in our docs (which is why this issue is still open, labeled "document").

If we should keep it that way, promote hooks instead, or whatever else, is a another question.

**Comment by dan31** [comment]
@per-samuelsson thanks for the info! I think that we can reconsider this taking other APIs review during August. The question of subscribing to object events is quite generic, and both facilities such as ```IEntity``` and commit hooks might be still reasonable. And might be not. We will see.

**Comment by miyconst** [comment]
I would like to be a part of that discussion.

**Comment by per-samuelsson** [comment]
> I would like to be a part of that discussion.

The more the merrier! :+1:

**Comment by dan31** [comment]
@miyconst surely do. We really plan to undertake this in August.

**Comment by Mackiovello** [comment]
This is now documented [here](https://starcounter.io/guides/database/referential-integrity/)

**Comment by per-samuelsson** [comment]
@Mackiovello 

> This is now documented here

Any reason we quote MSDN? I'm not sure it's the best thing to do, considering bias, etc. I'm certainly not an expert, but I think it's better to quite something more standard, like Wikipedia, if we need to include explanations of general concepts.

https://en.wikipedia.org/wiki/Referential_integrity

**Comment by Mackiovello** [comment]
> Any reason we quote MSDN? I'm not sure it's the best thing to do, considering bias, etc. I'm certainly not an expert, but I think it's better to quite something more standard, like Wikipedia, if we need to include explanations of general concepts.

MSDN had, in my opinion, the best concise explanation. The Wiki article is good, it's not as clear on the basic concept, though. 

What kind of bias issue? 

I've now included a link to the Wikipedia article for more in-depth information.

**Comment by mtornwall** [comment]
>> Any reason we quote MSDN? I'm not sure it's the best thing to do, considering bias, etc. I'm certainly not an expert, but I think it's better to quite something more standard, like Wikipedia, if we need to include explanations of general concepts.

> MSDN had, in my opinion, the best concise explanation. The Wiki article is good, it's not as clear on the basic concept, though.

Can't we try to reword it so that it's not copied verbatim from MSDN, but retains the clarity of their explanation? I too am worried about mentioning MSDN directly as it reinforces the perception that Starcounter is a .NET product.

**Comment by Mackiovello** [comment]
Got it.

I've updated it to not contain any reference to MSDN.

**Comment by dan31** [comment]
Good job @Mackiovello!
