### ISSUE TITLE
Implement limited support for HTTP2 

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#128]
Before known as SPDY. The networking overhead of HTTP1.1 is to big for high traffic scenarios.
HTTP2 allows for connection multiplexing and request/response pipelining.

The first step is to make use of the smaller request/response size and what we need for aggregation.

**Comment by alemoi** [comment]
It will be a duty of our future Go gateway or 3rd party server like NGinx/haproxy.
