### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#1297]
Was trying to do unit tests for my code.
The application code in one dll/project  that include starcounter parts and one separate dll/project with my unit tests.

I'm using visual studios own built in test methods for unit tests ([TestClass] attribute.

I actually tried this quite long ago but noticed that the tests was not runned but still didn't see any errors so I skipped it for the moment and went on to other things. However, I stumbled on the information that running tests in visual studio didn't show all errors and that I should run it in command prompt instead.

So I did and I got this result:
```
Warning: Test Run deployment issue: The assembly or module 'FasterThanJson' dire
ctly or indirectly referenced by the test container 'C:\Projects\GitHub\Tunity-2
.0\Tunity.QueryBuilder.Tests\bin\Debug\tunity.querybuilder.tests.dll' was not found
```  

Have you tried doing unit tests? How do you do it?

**Comment by per-samuelsson** [comment]
Unit test support coming up: #3831. Closing this one in favor of that. Please redirect any further questions / comments to that issue.
