### ISSUE TITLE
Resizing column in event log in Administrator causes visual weirdness

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#132]
![Screenshot of Parallels Desktop](https://f.cloud.github.com/assets/1219049/356396/98dea1c0-a105-11e2-9dc4-a4e64ac6f3f4.png)

When resizing the host column, the row height goes haywire.

![Screenshot of Parallels Desktop](https://f.cloud.github.com/assets/1219049/356401/ba93511c-a105-11e2-9d94-059f527384d9.png)

**Comment by warpech** [comment]
Not reproducible anymore in the SQL browser. Also, the columns in the log are no longer resizable.
