### ISSUE TITLE
Comments on Executable -> stop and restart pop-up

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#1322]
Comments on Executable -> stop and restart pop-up:

Pushing the stop button I get this pop-up:

>Stop executable
>
>Do you want to stop the executable C:\Temp\StarcounterApplication2\StarcounterApplication2\bin\Debug\StarcounterApplication2.exe

First: No question mark! Also, as a security check this a bit cumbersome since you have to really work to decipher the name of the actual executable.

Maybe something like:

>Stop executable
>
>Do you want to stop the executable StarcounterApplication2.exe?
>
>(C:\Temp\StarcounterApplication2\StarcounterApplication2\bin\Debug\StarcounterApplication2.exe)

(Or maybe a pulldown of something even to get the path. How often will I be interested in the path?).

**Comment by miyconst** [comment]
In the current version there is no popup at all, closing the issue.

**Comment by warpech** [comment]
Thanks @miyconst for issue gardeninig :smile:
