### ISSUE TITLE
Make keyword USER unreserved

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1361]
Currently, the bison-based parser does not accept identifier USER in many places. For example, the following statement fails:

``` sql
create index nicknameindx on User(NickName)
```

This has to be investigated and fixed as soon as possible.

Then the query preparation should be changed to assume that bison-based parser accepts all queries accepted by prolog-based parser.

**Comment by andan342** [comment]
Yes, currently the keyword `USER` is only used in 
```
ALTER TABLE ... ENABLE|DISABLE TRIGGER ALL|USER|trigger_name
```

So the `USER` is restricted for some (but not all) kinds of identifiers, falling into the `type_func_name_keyword` category. For example, if we had a trigger named `User`, the above statement would become ambiguous.

As explained in [PostgreSQL documentation](https://www.postgresql.org/docs/9.2/static/sql-altertable.html), the purpose of `DISABLE TRIGGER USER` is to disable all *user-defined* triggers defined on the table.

PostgreSQL implements constraints like *foreign key*, *uniqueness*, and *exclusion* also with triggers, so those are *system-defined*, and can be disabled with `DISABLE TRIGGER ALL` (with certain privileges).

I see two good ways to fix this:

1. Changing the syntax for corresponding operations to `DISABLE ALL|USER TRIGGERS` and `DISABLE TRIGGER trigger_name`.

2. Removing the concept of *user-defined* vs *system-defined* triggers. then we can just remove this option.

Here is some research on what other guys are doing:

- [MS SQL Server](https://msdn.microsoft.com/en-us/library/ms182706.aspx) uses `ENABLE|DISABLE TRIGGER ALL`,
- [Oracle](https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_4001.htm) uses `ENABLE|DISABLE ALL TRIGGERS`, and there as same planned feature in [MySQL](https://dev.mysql.com/worklog/task/?id=2825).
- none of them has a concept of *user-defined* triggers, this appears to be a distinctive feature of PostgreSQL, owing to its history of being a research prototype.

**Comment by k-rus** [comment]
We are not sure if we will use trigger syntax. Thus we decided to go for Oracle syntax, which will allow to relax `USER`. So the syntax will be:

```
ALTER TABLE ...
DISABLE/ENABLE USER/ALL TRIGGER
```

**Comment by andan342** [comment]
@k-rus : I guess you mean 

```
ALTER TABLE ...
DISABLE/ENABLE USER/ALL TRIGGERS
```
which is the Oracle way. I am about to add a new keyword `TRIGGERS`.

**Comment by andan342** [comment]
Fixed in branch **grammar2**, testcase added to **sqlparser_unittest**.

The new unreserved keyword `TRIGGERS` is added. The keyword `USER` is now unreserved too.

**Comment by andan342** [comment]
Pushed to **develop**.

**Comment by k-rus** [comment]
Am I correct that it is two reserved keywords now: `TRIGGER` and `TRIGGERS`? If so, then let's keep only one of them reserved.

**Comment by andan342** [comment]
Both of them are unreserved.

**Comment by k-rus** [comment]
Thank you for clarification. The issue is resolved.
