### ISSUE TITLE
Test SQL parser for insert statements constructed from database objects

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1397]
The goal is:

1. To create insert statement strings filled with literals from possible values read from a database 
2. Write them to file
3. Read them from file 
4. Submit them to SQL parser and see if all literals are recognized. 

The outcome will be:

1. Specification how insert strings should be created, written to and read from files.
2. Issues to fix SQL parser.

This issue can be done already know and does not requires any specific or complex knowledge.

**Comment by k-rus** [comment]
The query processing test runs unload and reload of its database, which can be seen as partial test targeted here. I think it can be enough for now.

**Comment by alemoi** [comment]
:+1:
