### ISSUE TITLE
Migrate our solutions to use NuGet 2.7 Automatic Package Restore

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#1457]
This is a step to simplify our builds further, no longer relying on excplicit "Enable NuGet package restore" to build.

With this (if possible), we should also try to figure out a way to check that VS is using NuGet 2.7 when building, and warn / instruct developers if not.

**Comment by alemoi** [comment]
I guess this one is now can be closed since @chrhol added automatic restore supported by VS2015: #2981
