### ISSUE TITLE
Wrong build dependencies treatmeant by MsBuild or problem with AfterBuild

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#1495]
Quite often there is an error like this when building Level1 (native code projects): `c:\scbuildsystem\teamcity6\buildagent\work\build-daily-2.0.6162.2\level1\src\chunks\bmx\chunk_helper.h(11): fatal error C1083: Cannot open include file: '../../Starcounter.ErrorCodes/scerrres/scerrres.h': No such file or directory (OurSources\apps_http_request_parser.cpp) [C:\ScBuildSystem\TeamCity6\buildAgent\work\build-daily-2.0.6162.2\Level1\src\HTTP\HttpParser\HttpParser32.vcxproj]`

The project dependencies in solution are correct. Either MsBuild is treating them wrong or AfterBuild in `scerrres` can not be treated properly for dependencies.

**Comment by dan31** [comment]
@parherman, chat with @alemoi upon the issue.

**Comment by parherman** [comment]
@alemoi do you still see this?

**Comment by alemoi** [comment]
Not anymore, after we made a step to build error codes separately before Level1! Closing the issue.
