### ISSUE TITLE
comments in Interactive SQL

### ISSUE THREAD

**Issue by JingkunLi** [Starcounter/Starcounter#159]
In StarCounter Administrator,  Interactive SQL Failed to process querys SQL including comments: 

![image](https://f.cloud.github.com/assets/3672331/372382/983a4ccc-a35a-11e2-9d0a-7f9c4a086831.png)
example: 
Select * from Person  -- some comments text.

error msg: 
Failed to process query: Select * from Person --  some comments text: Incorrect syntax.

![image](https://f.cloud.github.com/assets/3672331/372385/b86b3aba-a35a-11e2-8d92-3e82f56f71ba.png)

**Comment by dan31** [comment]
Proposed resolution:
Support for comments in interactive SQL: won't fix.
Support for ```delete``` in interactive SQL and single quotes: due to #161.
Close by now.
