### ISSUE TITLE
Horizontal scrolling works badly for many columns in SQL result

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1635]
If the result of executing SQL query is wide, then horizontal scrolling moves by half char only if I press arrows and pressing empty space on the scroll bar left or right from the current place does not work as expected. I see this problem in Firefox.
If I do the same in Chrome then the scroll bar is not shown correctly:
![horizontalscrollbarissuechrome](https://f.cloud.github.com/assets/1726044/2205057/8c9ad85c-9948-11e3-95f4-da4ef837d3ea.png)

It can be reproduced by installing Starcounter from my branch `NewSqlProcessor`, starting the following application and executing interactive query `select * from clrview c, tablecolumn where basetable = c`.

```
using Starcounter;

class Hello {
    static void Main() {
        Db.Transaction(() => {
            var albert = new Person() { FirstName = "Albert", LastName = "Einstein" };
            new Quote() { Person = albert, Text = "Make things as simple as possible, but not simpler" };
        });
        Handle.GET("/hello/{?}", (string name) => {
            return "<!DOCTYPE html><title>Hello</title>Hello " + name;
        });
    }
}

[Database]
public class Person {
    public string FirstName;
    public string LastName;
    public string FullName { get { return FirstName + " " + LastName; } }
}

[Database]
public class Quote {
    public Person Person;
    public string Text;
}
```

I guess the problem is in Handsone table.
I will create a Starcounter installer for my branch.

**Comment by warpech** [comment]
@budnix After fixing https://github.com/Starcounter/Starcounter/issues/2990, could you please check if the issues described here (including comments) are still reproducible?

**Comment by warpech** [comment]
@budnix wrote in email:

> Related with #2987, should be fixed automatically.

After https://github.com/budnix/Starcounter/commit/e258f21c0a9490be9fc3f72dd5d32a2d5c6c6e59 I can see that there is a horizontal scrollbar in the DIV container (see the screenshot below). 

I would prefer to only use window scrollbars for horizontal and vertical scrolling of the table, as previously. @budnix could you please change this?

![screen shot 2016-01-13 at 10 33 30](https://cloud.githubusercontent.com/assets/566463/12290314/61667df6-b9e1-11e5-8cfc-0fd665b9ed62.png)

**Comment by warpech** [comment]
I have pasted this request as a separate issue: https://github.com/Starcounter/Starcounter/issues/3244
