### ISSUE TITLE
Administrator web [user] unterface

### ISSUE THREAD

**Issue by andan342** [Starcounter/Starcounter#1738]
1. On page
https://github.com/Starcounter/Starcounter/wiki/Creating-a-Hello-World-application
there are no instructions how to run SUBJ

2. Clicking "Adminstrator" in Pop-Up menu on Starcounter server notification icon doesn't do anything on Windows 8 with Firefox chosen as the default web browser.

**Comment by miyconst** [comment]
@andwah this is fixed, right? Could you close it?
