### ISSUE TITLE
Create new web for www.starcounter.com

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#1773]
Our web page should be more directed towards the product and developers with direct gists of example code. The image below is not the actual design but an indication on the direction. The site will be a Polyjuice launcher and the sample code/apps will be live running Starcounter apps. 

Comments are very welcome.

![starcounterweb2 001](http://www.rebelslounge.com/res/starcounter/new-web-full2.png)

**Comment by warpech** [comment]
Archiving
