### ISSUE TITLE
Fix location info for not supported clauses

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1777]
It might be good idea to provide location of the keyword, which clause is not supported. This requires changes in `List` structure and might affect `Node` related code.

**Comment by andan342** [comment]
It is not the parser who decides if a clause is supported or not. If the error is thrown at a next step, it can always include the `position` information.

However, the current problem is that `int position` is not stored for every subclass of `Node` - just for some descendants of it. A fix would be to have provide `position` for all nodes or at least of all *clauses*. The latter might be defined as syntactic nodes defined with an certain keyword.

**Comment by k-rus** [comment]
Yes, this issue is to provide this position numbers after parsing. May be it first should be checked from the code which creates the error. I think I already found that it is missing. Now I can image the position of `SELECT`.

**Comment by alexanderstc** [comment]
@andan342 

> However, the current problem is that int position is not stored for every subclass of Node - just for some descendants of it. A fix would be to have provide position for all nodes

Let me know if you need help with moving position info to the Node class.

**Comment by andan342** [comment]
Every `Node` descendant now has a `location` property, which can be used for error reporting.

The new locations are described in this document:
https://github.com/Starcounter/RebelsLounge/blob/master/query_processor/Locations_in_AST.md

It's still an issue to report an error for not supported clauses, see e.g. [BlueStar #158](https://git.starcounter.org/BlueStar/level0/issues/158).

**Comment by k-rus** [comment]
Closing, since it is done.

**Comment by k-rus** [comment]
Or was I too early? What is left?

**Comment by andan342** [comment]
@k-rus, @Thanh-Truong : I guess, when we know how to identify *not supported* clauses in a general way - we can report it here. I am referring to that issue above.

**Comment by Thanh-Truong** [comment]
The issue should be opened. 
Currently, we manually check "not supported" clauses and the reported error should include the position of not supporte clauses. I'll cover this as well as I am reviewing all error reports, case by case, from QP

**Comment by k-rus** [comment]
> Currently, we manually check "not supported" clauses and the reported error should include the position of not supporte clauses. I'll cover this as well as I am reviewing all error reports, case by case, from QP

Correct.

**Comment by Thanh-Truong** [comment]
fixed in c5b154b58ba66cb8d6990a3f2ab87019a85c7df8
