### ISSUE TITLE
Use of Debug build configuration for daily build

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1779]
Daily build has configuration environment variable, which is set to Release by default. What is the purpose of it? I tested to run it as Debug, but all projects are compiled as release, while tests are run from Debug folder and of course fail, see [this build](https://scbuildserver/viewLog.html?buildId=21078&buildTypeId=bt23&tab=buildLog&state=&expand=none#_focus=5429&state=5429).

**Comment by alemoi** [comment]
This was completely changed when I created a all-in-one batch script. So this should already work for a while.
