### ISSUE TITLE
Investigate changing SQL error message from char to ucs2_char

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1784]
Errors from type checker contains names of database objects, which are in `wchar_t`. Currently, error messages cannot include the names, since it is of `char`. Changing to wide char might require to do changes in the parser.

**Comment by k-rus** [comment]
@alexanderstc 
Can you look to this issue when you will fix error reporting of the parser (issue #1214)?

**Comment by alexanderstc** [comment]
Shouldn't this be "to ucs2_char" instead of "to wchar_t"?

**Comment by k-rus** [comment]
> Shouldn't this be "to ucs2_char" instead of "to wchar_t"?

Yes, of course. Renamed.

**Comment by alexanderstc** [comment]
Currently in branch alexander-ucs2-sql-errs I made sqlparser_unittest to print seemingly correct ucs2 error messages.

However, sqlregression_test now fails because some parts of error messages are chewed up, like:
expected: "Incorrect SQL syntax. Query string must contain a valid statement. The error near or at position 0."
     actual: "Incorrect SQL syntax. Q The error near or at position 0."

Will investigate.

**Comment by k-rus** [comment]
> However, sqlregression_test now fails because some parts of error messages are chewed up, like:
> expected: "Incorrect SQL syntax. Query string must contain a valid statement. The error near or at position 0."
> actual: "Incorrect SQL syntax. Q The error near or at position 0."

Have you fixed the type expected by managed code? It expects sequence of `sbyte`, i.e., `char`, not `wchar`.

**Comment by alexanderstc** [comment]
I thought it was something like that.
Have to find where it is coded.

**Comment by k-rus** [comment]
> I thought it was something like that.
> Have to find where it is coded.

I can look at it. It is in *SqlProcessor.cs*.

**Comment by alexanderstc** [comment]
Please do.

**Comment by alexanderstc** [comment]
Implemented, in l0 & l1 pnext.
