### ISSUE TITLE
Static resource and multiple apps

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#1804]
Hey!

I'm not sure how to reproduce this, but I've been playing around with PMail, TodoDemo, PolymerBoilerplate and my own app where I try to use these parts.

From time to time I get the wrong resources loaded. It seems that the AppsBootstrapper.Bootstrap is global? 
Reproducing goes something like this:
1. Start TodoDemo, will run on port 8080
2. Start PolymerBoilerplate, will also run on port 8080. 
3. Stop TodoDemo in the web ui
4. Restart PolymerBoilerplate, i still get the resources of TodoDemo.

**Comment by alemoi** [comment]
I have changed the architecture behind the static file handler. Now each codehost owns its static file handler (which sits on user port for that codehost). This architecture automatically solves the above and some other problems. Done via cedf011b66a3b737c6de621c76f3ea8e3dd60427
