### ISSUE TITLE
Boilerplate, FocusedPage

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#1808]
Hi!
Another question about the bouilerplate application. I'm trying to add another menu item to the first page. The url seems right when I hover over the link, but I always get the same content no matter which menu item I click. It seems to be that the patching of FocusedPage isn't updating the html?

Could someone please download the git patch attached to this issue and please tell me what I'm doing wrong. Or is it a bug in puppet?

(I named the file png just to be able to upload, it's a 7z containing a git patch)
![0001-adapted-to-be-used-with-heads-administrator 7z](https://cloud.githubusercontent.com/assets/4263597/2576769/241a5454-b975-11e3-9027-b7d9f7d497ba.png)

**Comment by tomalec** [comment]
Now we have full set of https://github.com/Starcounter/ in place of PolymerBoilerplate
