### ISSUE TITLE
Modification capability in Administrator GUI

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1813]
Should it be possible to do insert into statements from our Administrator?

**Comment by warpech** [comment]
It is desired to do all CRUD operations in the Administrator (INSERT, SELECT, DELETE, UPDATE) if possible. Currently only SELECT is supported.

The development is tracked in: https://github.com/Starcounter/Starcounter/issues/166

**Comment by miyconst** [comment]
We have several issues about this feature, could we close this one to don't duplicate?

**Comment by k-rus** [comment]
closing
