### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#1821]
Not certain what parts of the application, but I've attached a zip. I didn't include default.00000000**.log.bak because I had quite a few at 256mb each.

"Access violation (C0000005) detected at ....\src\sccoredb\sccoredb.cpp:483 (Thread 15064).
    00007FF8819B16CE TurboText_en-GB_3!
    0000006352F1D7C4 sccoredb!_attr_ext_read_column_name_into_buf : schemaapi.cpp (599)
    0000006352F1D50A sccoredb!_get_column_info : schemaapi.cpp (737)
    0000006352F3F218 sccoredb!sccoredb_get_column_info : sccoredb.cpp (474)
    00007FF82A4DF486 <unknown>!
    00007FF82A54000F <unknown>!
    0000005B66810000 <unknown>!
    000000654943F160 <unknown>!
    0000006352F1D5E9 sccoredb!__get_table_info : schemaapi.cpp (675)
    000000654943F070 <unknown>!
    00007FF82A4DF486 <unknown>!
    000000654943F090 <unknown>!
    000000654943F160 <unknown>!
    00007FF8000F0000 <unknown>!
    0000005B5660D620 <unknown>!

"
![personal 7z](https://cloud.githubusercontent.com/assets/4263597/2595877/06557a58-baa0-11e3-86d4-39a74b2b8023.png)

**Comment by dan31** [comment]
Old, archived.
