### ISSUE TITLE
Access violation (C0000005) 

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#1831]
Not sure how to reproduce, server crashed with an exception. Next start yields this result.

![personal 7z](https://cloud.githubusercontent.com/assets/4263597/2614512/885be944-bbe8-11e3-924c-bd087c581d4d.png)
7z-Zip attached as png, download and rename to 7z-extension

Access violation (C0000005) detected at ..\..\src\sccoredb\sccoredb.cpp:2198 (Thread 3488). 000000A86BED48EE sccoredb!storage_allocator_page_list::add : storage_allocator_page_list.hpp (58) 000000A86BEC1B54 sccoredb!__free_fss_table_slot<0,0,&__free_standard_slot_and_update_page_header,_storage_memory,storage_allocator> : freeslot.hpp (78) 000000A86BEE1677 sccoredb!free_fragmented_record : c_freeobjv.cpp (78) 000000A86BEC9DCD sccoredb!_replace_target_record_with_deleted_record : c_writedal.cpp (122) 000000A86BEE2CFE sccoredb!_commit_write_delete : c_writedel.cpp (22) 000000A86BEE2C26 sccoredb!_commit_write : c_write.cpp (93) 000000A86BEEFB8C sccoredb!_commit_task_execute : serialized.cpp (644) 000000A86BF21943 sccorelib!pluto_enqueue_and_execute : enqnexec.c (42) 000000A86BEED8D3 sccoredb!__do_commit : sccoredb.cpp (2173) 000000A86BEEDA6B sccoredb!__commit : sccoredb.cpp (2055) 000000A86BEED614 sccoredb!sccoredb_complete_commit : sccoredb.cpp (2355) 00007FF82A4FF5C0 <unknown>! 0000009DA3B59090 <unknown>! 00007FF82A594208 <unknown>! 0000000100000000 <unknown>! 00007FF82A594320 <unknown>! 00003FE10A23ACCE <unknown>! 00007FF88A1E9000 clr! 000000AA643EF0A0 <unknown>! 00007FF82A564540 <unknown>! 000000A06F46F670 <unknown>! 000000AA643EE300 <unknown>! 00007FF82A4FF5C0 <unknown>! 000000AA643EE320 <unknown>!

**Comment by alemoi** [comment]
@dan31 should we get back to this? :)

**Comment by dan31** [comment]
Such an archeologist @alemoi! I all following starting-up projects I've never seen that repeated since maybe July 2014. @careri, do you confirm not having it repeated?
