### ISSUE TITLE
System.IO.IOException: Remote host closed the connection. at Starcounter.NodeTask.PerformSyncRequest()

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#1887]
I get this now and then when accessing our application (on full reload).
When it happens it often comes twice or three times (2-3 reloads) in a row and then everything works again. I have not found any triggers for it. It happens maybe 1-4 times every day. (I might have 60-100 reloads a day)

**Comment by alemoi** [comment]
Closing this issue. It was probably fixed recently.
