### ISSUE TITLE
Correct user groups and users on the forum

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#189]
1. Study permissions on the forum and different forum levels and implications
2. Obtain specification for user groups, forums and users.
3. Check if the specification is followed.

**Comment by Starcounter-Jack** [comment]
This issue pertains to vBulletin. It is no longer used.

**Comment by k-rus** [comment]
If our forum is not used it would be great that my email address is removed from there. Currently, all messages send on behalf of the forum are sent from my email address. The only receivers nowadays are spammers. So my Starcounter email is provided to all spammers.

**Comment by dan31** [comment]
@k-rus, the forum will be achieved, the activity is in a deep backlog though.

**Comment by k-rus** [comment]
I don't like that my work email is sent to all spammers. Not really a great idea. So far it wasn't big problem.

**Comment by dan31** [comment]
An outsourced task to archive old forum is created: https://github.com/Starcounter/AdminTrack/issues/107.
