### ISSUE TITLE
Fix location and token for Invalid statement error

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1915]
It requires some changes to be able to report correct location and token in the invalid statement error.

**Comment by andan342** [comment]
Every `Node` descendant now has a `location` property, which can be used for error reporting.

The new locations are described in this document:
https://github.com/Starcounter/RebelsLounge/blob/master/query_processor/Locations_in_AST.md

All invalid syntax is reported, specifying the location and offending/invalid token.

**Comment by k-rus** [comment]
I believe we can close the issue. By default Level1 should utilise the provided token information. If it will be noticed otherwise, then it will be reported and fixed separately.

**Comment by Thanh-Truong** [comment]
> By default Level1 should utilise the provided token information

It is not the case as Level0 does not provide location/token in case of invalid error statement. Thus, I reopen this since work is in progress.

**Comment by Thanh-Truong** [comment]
pushed onto [develop](https://git.starcounter.org/BlueStar/level0/commit/21d1303e78c6fb317fcc8340dedf2f653afa44c4)

> All invalid syntax is reported, specifying the location and offending/invalid token.

Yes

> By default Level1 should utilise the provided token information. If it will be noticed otherwise, then it will be reported and fixed separately.

Yes and therefore, I am closing this issue.
