### ISSUE TITLE
Fix line numbers in SQL syntax error messages

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1916]

**Comment by andan342** [comment]
Do you have a testcase where line numbers are wrong?

**Comment by k-rus** [comment]
> Do you have a testcase where line numbers are wrong?

I think there is no cases when line numbers are presented. Currently it is only position in a string. If a string takes multiple lines, then I don't know what will be the correct approach. It is more interesting if query comes from a file (e.g., modify query). But I have zero experience with such case. If you have suggestions it will be great.

**Comment by andan342** [comment]
Every `Node` descendant now has a `location` property, which can be used for error reporting.

The new locations feature line and column numbers, and are described in detail in this document:
https://github.com/Starcounter/RebelsLounge/blob/master/query_processor/Locations_in_AST.md

All invalid syntax is reported, specifying the location and offending/invalid token.

**Comment by Thanh-Truong** [comment]
fixed in https://git.starcounter.org/BlueStar/level0/commit/c5b154b58ba66cb8d6990a3f2ab87019a85c7df8
