### ISSUE TITLE
Starting database hangs if not enough disk space

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1952]
I downloaded and installed latest nightly build (Starcounter-2.0.1832.3-Setup.exe). Then I started application `DatabasePopulation` from [ScSqlTestFramework](https://github.com/Starcounter/ScSqlTestFramework) from command line and it hangs on starting database:
>C:\GitRepositories\Starcounter\ScSqlTestFramework\DatabasePopulation\bin\Debug>DatabasePopulation.exe
DatabasePopulation -> default (starting database ...)

At the same time windows gives me warning that low disk space.

I attached debugger and see the stack trace if I pause:
```
 	ntdll.dll!000000007791186a()	Unknown
 	KernelBase.dll!000007fefd9e1430()	Unknown
 	kernel32.dll!00000000777b06e0()	Unknown
>	sccoredb.dll!_SendRecv(int killIfTargetTerminates, int waitPings) Line 59	C++
 	sccoredb.dll!_SynchronousCheckpoint(_SC_PROCESS * pProcess, int waitPings, int backup) Line 29	C++
 	sccoredb.dll!_DurabilityCompleteDatabaseInit(int waitPings, int backup) Line 168	C++
 	sccoredb.dll!sccoredb_connect(unsigned int flags, unsigned int scheduler_count, unsigned __int64 hmenv, unsigned __int64 hlogs, void * hperf) Line 3059	C++
 	[Managed to Native Transition]	
 	Starcounter.Bootstrap.dll!StarcounterInternal.Bootstrap.Control.ConnectDatabase(uint schedulerCount, ulong hmenv, ulong hlogs) Line 528	C#
 	Starcounter.Bootstrap.dll!StarcounterInternal.Bootstrap.Control.Setup(string[] args) Line 183	C#
 	Starcounter.Bootstrap.dll!StarcounterInternal.Bootstrap.Control.Main(string[] args) Line 42	C#
 	sccode.exe!sccode.Program.Main(string[] args) Line 17	C#
 	[Native to Managed Transition]	
 	mscoreei.dll!000007fef82277ad()	Unknown
 	mscoree.dll!000007fef82d5b21()	Unknown
 	kernel32.dll!00000000777b59ed()	Unknown
 	ntdll.dll!00000000778ec541()	Unknown
```

To reproduce:
1. Make sure that there is no much space on disk. 500MB is already good for the reproduction.
2. Make sure that the database does not exist or even better the server is not started, however I am not sure if required.
3. Start any Starcounter application from command line (see example above)

**Comment by eriohl** [comment]
Will be working in next version. Will not be addressed in current version.
