### ISSUE TITLE
Building Starcounter code requires manual 32-bit reinstall

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#1957]
Similar to #1956, after building a new version of any assemblies we support as 32-bit components (in the %StarcounterBin%\32BitComponents folder) requires the developer to run a manual bat-file to guarantee accurate results. If you don't do this, any 32-bit process loading Starcounter (most notably, the VS extension) will produce unpredictable results (like evident in #1926).

Part of #1955.

**Comment by alemoi** [comment]
Building 32-bit components and building of public assemblies are now integrated into Level1 build so does not require any extra steps. Closing the issue.
