### ISSUE TITLE
Incorrect arithmetic in the installer presentation

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#197]
One slide in the presentation states that RDBMS were developed 41 years ago with a reference to a paper from 1970. Now, it is 2013. 2013 - 1970 is not 41.
It is stated 41, because the presentation was designed 2 years ago in 2011. At that time 41 years ago was true.

**Comment by k-rus** [comment]
Temporal fix was done, which is already invalid, since we are in 2015.

**Comment by dan31** [comment]
The video is discontinued, so the issue is.
