### ISSUE TITLE
Administrator does not inform if stopping database failed

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1978]
When I stop an application and experience the problem in issue #1977, the administrator shows starting message forever, while the database was actually down. This is very confusing. The screenshot:
![stoppingapplicationadministrator](https://cloud.githubusercontent.com/assets/1726044/2973012/97ce14e6-db79-11e3-8576-faabb9afa689.png)

**Comment by k-rus** [comment]
@andwah is it still an issue?

**Comment by andwah** [comment]
No, it has been resolved, closing issue.
