### ISSUE TITLE
Null reference during stopping database

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1979]
I have two running applications `DatabasePopulation` and then `UnloadDatabase` from Starcounter/ScSqlTestFramework. Then I successfully started `PokerDemoApp`. Then I tried to start `DatabasePopulation`, which requires to stop code host and I've got the following error:
```
DatabasePopulation -> default (restarting default (and 2 other executable(s)))

Stopping F1E483A429DA3C83FA807D9D27B245C9C30D41B3 failed due to an unexpected pr
oblem. ("Object reference not set to an instance of an object.").
```

In the log:
> "ScErrUnexpectedCommandException (SCERR10016): Stopping F1E483A429DA3C83FA807D9D27B245C9C30D41B3 failed due to an unexpected problem.
Version: 2.0.1844.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Server.Commands.StopExecutableCommandProcessor.<>c__DisplayClass8.<Execute>b__3(CommandTask task)
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func)
   at Starcounter.Server.Commands.StopExecutableCommandProcessor.Execute()
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback)
HResult=-2147467261
"

**Comment by k-rus** [comment]
Can this issue be closed?

**Comment by per-samuelsson** [comment]
> Can this issue be closed?

I think this issue is one of those that are hard to evaluate, and its not deterministic. On top of that, if it still applies, fixing it most likely need quite a largish redesign.

Thats the input I can give. If you want to close it or leave it open, its for you to decide. :)

**Comment by k-rus** [comment]
Since it is not deterministic and old, I close it.
