### ISSUE TITLE
Unnecessary scroll bar in Administrator

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1980]
I stopped a database in Administrator and removed the message. The result window contains scroll bar, while everything is already visible:
![unnecessaryscrollbaradministrator](https://cloud.githubusercontent.com/assets/1726044/2981228/fa475712-dc01-11e3-935c-7e5e9e1182a0.png)

**Comment by warpech** [comment]
Not reproducible anymore. Probably fixed with other fixes or with the redesign of Administrator.
