### ISSUE TITLE
Ctrl-Enter for SQL execution does not always work in Administrator Firefox

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1993]
I often experience that when I press Ctrl-Enter to execute interactive query, nothing happens. I guess something is broken. It happens often, but not always, so I cannot say what triggers it.

**Comment by warpech** [comment]
Fixed in https://github.com/Starcounter/Starcounter/commit/38b7402b041fa5ca05dbd18f84b4b84c04b046c3.
