### ISSUE TITLE
Widestring operator names: propagating the change

### ISSUE THREAD

**Issue by andan342** [Starcounter/Starcounter#2014]
I see that makeSimpleA_Expr() function (as defined in `Nodes\makefuncs.c`) takes `wchar_t*` as a second argument, and stores the name of the operator as widestring.

However, in `gram.y`, simple strings are passed as arguments to makeSimpleA_Expr() calls. Doing it this way makes multi-character operator names invisible (`0x00` byte follows the first character), unless explicitly cast to `(char*)` on a later stage of processing.

I suggest prefixing all arguments to makeSimpleA_Expr() with `L`, e.g. `L"!~~"` instead of `"!~~"`in `NOT LIKE` rule action.

However, I do not know if the reverse typecasting to `(char*)` really takes place at a later stage.

**Comment by k-rus** [comment]
@andan342 Can you check if it is fixed already?

**Comment by andan342** [comment]
Yes, it has been fixed, and I just tested it. The operations are stored as UTF-16 strings in the `name` field of AEXPR.

Since there were no reported problems with subsequent QP, I assume that these values in the AST are treated correctly as well.
