### ISSUE TITLE
Improve delete database files message

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2020]
When I install the same version of Starcounter as it was before, i.e., the database files exist already for the version to install, I get a question if I want to delete the folder with database files. Every time when I read the message I don't know how serious consequences will be if I don't delete the database. However, I tested and no problems appear. 

Thus I suggest to improve the message and make clear that the user can allow the installer to delete the database files, if the user does not need them, or don't need to delete them and keep the database files for use them to run applications with the installed version of Starcounter.

**Comment by alemoi** [comment]
I think this is no longer relevant since we started to always install into existing server directory meaning that there is no such message box anymore. Thanks for the input anyways!
