### ISSUE TITLE
Missing .NET meta-data for private fields

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2061]
If a database class in an application contains private field, a column is created for it, but no property is created and thus the field cannot be used if no other public property or method is defined in terms of it. Such code exists in SO, e.g.:

```c#
namespace Concepts.Ring2
{
    public class DocumentElement : Something
    {
        private DocumentElement Parent;
        private int Position;
        public string Text;
    }
}
```

For such private fields .NET metadata are created to describe the future column, i.e., `ColumnDef` in `TableDef`, which lacks information about the actual type, while no meta-data are created to describe property, i.e., `PropertyDef` of `TypeDef`, which contains such information called TargetedType. I don't know yet if the weaver does not provide this information or it is during creation of the meta-data from the weaver input. I would believe that the weaver provides the information.

This issue is the source for the bug #2056.

It is necessary to discuss and decide how to deal with private fields in Meta-data and SQL.

**Comment by per-samuelsson** [comment]
This seem to work good and I'm therefore closing this.
