### ISSUE TITLE
Unclear error message for JSON property "Input"

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2065]
I am working on a Starcounter demo with a following JSON-by-example:

```json
{
  Html: "",
  Input$: 1.0,
  Output: 1.0
}
```

The project does not build, with a following error message:

```
'Input': member names cannot be the same as their enclosing type	
C:\Starcounter Projects\Squared\Squared\Squared\obj\x64\Debug\Master.json.g.cs	
131	22
```

As it turns out, `Input` or `Input$` are not accepted JSON property names.

It was not easy to fix the problem (rename `Input$` to something else), because the error points to a line in generated code, not directly to the JSON line.

I suggest allowing a property name `Input` because I can imagine other people trying to use it as well.

**Comment by chrhol** [comment]
Similar/same issue as #3143 and also brought up by Mopedo, that certain names cannot be used. I will keep the other issue open since it has some more comments and close this one so we keep it all in one place.
