### ISSUE TITLE
JSON-by-example data types not documented

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2066]
This wiki page introduces JSON-by-example: https://github.com/Starcounter/Starcounter/wiki/Responding-with-JSON

Looks that what is missing there is a list of data types implied by certain values.

For example, it may not be obvious to everyone that `{ Num: 1 }` creates `long` and `{ Num: 1.0 }` creates `decimal`.

**Comment by chrhol** [comment]
List available on the first page for TypedJSON on starcounter.io: http://starcounter.io/guides/json/
