### ISSUE TITLE
Behaviour of schema change is unclear

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#2122]
Steps to reproduce.

1/ Get a clean database, run the code and get `Some` in the output:

```
using System;
using Starcounter;

[Database]
public class MyClass
{
    public string Field;
}

class Program
{
    static void Main()
    {
        Db.Transaction(delegate{
            var p = new MyClass();
            p.Field = "Some";
        });

        Console.WriteLine(Db.SQL("SELECT Field FROM MyClass").First);
        Console.WriteLine("Hello!");
    }
}
```

2/ Make a change in a scheme and run the code:

```
using System;
using Starcounter;

[Database]
public class MyClass
{
    public string _Field;
}

class Program
{
    static void Main()
    {
        Console.WriteLine(Db.SQL("SELECT _Field FROM MyClass").First);
        Console.WriteLine("Hello!");
    }
}
```

Works as expected.
3/ Now run the example from 1/ (just replace the code in the app, don't drop the database). The output is different, no `Some` now.

Let's try to understand what happens here? What happens with schema, is it correct behavior?

**Comment by k-rus** [comment]
> I suggest to close this bug as duplicate for #1766. Any other opinion?

Closing as duplicate
