### ISSUE TITLE
Handler is called twice when client asks for both html and json.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2124]
An issue that pops up again and again (#2111, #1811 for example)  is when using the following pattern for an app:

A handler is registered, for example for the root, that creates a typedjson object, a new session and overrides the AsMimeType()-function to return html.
1. Client sends a request for root asking for html.
2. The handler is called which creates json and session (and other resources) and return the jsonobject, but since the client asks for html AsMimeType will be called and used in the response.
3. Client receives the html and sends another request using the same uri, but asks for json instead.
4. Handler is called again, and a new jsonobject and session is created, but this time the json is returned. 

``` csharp
partial class MyJson : Json {
    static void Main() {
        Handle.GET("/", () => {
            var myJson = new MyJson();
            myJson.Html = "/master.html";
            myJson.Session = new Session();
            return myJson;
        });
    }

    // Browsers will ask for "text/html" and we will give it to them
    // by loading the contents of the URI in our Html property
    public override string AsMimeType(MimeType type) {
        if (type == MimeType.Text_Html) {
            return X.GET<string>(Html);
        }
        return base.AsMimeType(type);
    }
}
```

After this we have two sessions and two stateobjects which leads to confusing bugs in later requests.

The workaround that have been used for now is to manually check if an session exists and if so return the stateobject directly.

``` csharp
...
Handle.GET("/", () => {
    if (Session.Current != null)
        return Session.Current.Data;
    var myJson = new MyJson();
    myJson.Html = "/master.html";
    myJson.Session = new Session();
    return myJson;
});
...
```

This is not a good way to solve this since it is so easy to miss do this, and everybody do including myself.

We need to find a proper solution for this problem.

**Comment by chrhol** [comment]
We're no longer using this pattern. The viewmodel is retrieved using a location that is specified in the response. Closing.

**Comment by warpech** [comment]
Agreed!
