### ISSUE TITLE
Make a high level (managed) Faster-than-JSON tree creator/reader/writer

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2135]
Let's assume we're creating the following JSON tree:

``` json
{
  "FirstName":"Joachim",
  "LastName":"Wester",
  "Phone":{"Home":"08-54137731"},{"Mobile":"0702424472"}},
  "City":"Stockholm"
}
```

The schema is always known by the writer/reader. Either it is known in the template structure (on the server) or it is sent as meta data to the client (when using the format as a JSON alternative). This means that the instance data representation contains no information about the schema. Below is a sample creating the instance representation of the above tree:

We have a schema that looks like this

```
TObject SchemaId=1
    TString Name="FirstName" Index=0
    TString Name="LastName" Index=1
    TObject Name="Phone" SchemaId=2 Index=2
        TString Name="Home" Index=0
        TString Name="Mobile" Index=1
   TString Name="City" Index=3
```

The instance tree can be written like this:

``` c#
var t  = new FasterThanJsonStream();
        // Memory should be hosted by BlueStar in shared memory (scdata)

t.BeginObject();
t.Append(1); // Points to the Person schema { FirstName:string, LastName:string, Phone:phone, City:string }
t.Append("Joachim");
t.Append("Wester");
t.BeginObject();
t.Append(2); // Points to the Phone schema { Home:string, Mobile:string }
t.Append("0854137731");
t.Append("0702424472");
t.EndObject();
t.Append("Stockholm");
t.EndObject();
```

![tupleformat](https://cloud.githubusercontent.com/assets/1219049/3439439/5ff0b772-00e5-11e4-9e3a-30adce1a56d2.png)
NOTE! The above illustration is missing the numeric template identifier property that is the first value of tuple.
## Each object knows its schema (i.e. Template)

Each object Each template has a unique index number that can be used to reference the template.
## Random Access Reads

The Template objects (TObject, TString, TBoolean etc.) contains their tuple position (i.e. index). The proxy Json objects (short lived) contains a cache with their offset in the tree blob. When the Json object is created, the offset is retrieved from the parent offset and its tuple index using the FTJ format.

In order to read the value of a property in a JSON tree you would step down level by level from the root level until you can read the leaf value in the tree.

``` c#
struct TupleAddress {
   IntPtr Buffer;
   int Offset;
}

public class Json {
   private TupleAddress TupleAddressCache; // I may know where I am hosted within the blob

    // Returns 
    public string Get( TString property ) {
        return FasterThanJson.ReadStringAt( TupleAddress, property.Index );
    };

    public TupleAddress TupleAddress { get { 
            if (TupleAddressCache != -1 )
               return TupleAddressCache;
            int offset = 0;
            IntPtr buffer;
            if (Parent !=null) {
                offset = Parent.TupleAddress.Offset;             
                buffer = Parent.TupleAddress.Buffer;
            }
            offset = offset + FasterThanJson.ReadOffsetAt( buffer, Template.Index );
            TupleOffsetCache.Buffer = buffer;
            TupleOffsetCache.Offset = offset;
            return TupleOffsetCache;
         }
    }
}
```
## Random Access Writes

TODO!
### Schema tuple

```
{
    $$Schema:[
         { Name:"Person", SchemaId:1, Properties:[ 
                     { Name:"FirstName",Type:"String"},
                     { Name:"LastName",Type:"String"},
                     { Name:"Phone", Type:"Object", SchemaId:2},
                     { Name:"City", Type:"String"}
         },
         { Name:"Phone", SchemaId:2, Properties:[ 
                     { Name:"Home",Type:"String"},
                     { Name:"Mobile",Type:"String"}
         }
    ],
   $:{S:1},
   FirstName:"Joachim",
   LastName:"Wester",
   Phone: { $:{S:2}, Home:"0854137731,Mobile:"0702424472" }, 
   City:"Stockholm"
}
```

**Comment by chrhol** [comment]
I don't think this is high prio, or if it should even be implemented at all. At least not until we can investigate possible alternatives that already exists instead of creating our own solution.
