### ISSUE TITLE
Create new kind when a kind class triggers the creation of a table

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2142]
Part of #2129.

The `Starcounter.Kinds` extension must assure that every time a [kind class](https://github.com/Starcounter/Starcounter/wiki/Kinds#terminology) triggers the creation of a new table (i.e. its added to the model/database), a corresponding kind shall be created.

As described in #2137, we have defined a base model such as this (simplified):

``` c#
class Concept {
  protected Kind kind;
  class Kind : Concept {
    Kind DerivedFrom {
      get { return kind; }
    }
  }
}
```

When used, the `Starcounter.Kinds` extension should react to the above model when it is first bound to the database (i.e. generating tables) and create the kind represented by the kind class.

In the core, the above model will generate the following (pseudo-) schema:

```
Table: Concept
Column[0]: ObjectId
Column[1]: kind

Table: Concept.Kind
Column[0]: ObjectId
Column[1]: kind
```

When `Starcounter.Kinds` have had a chance to react to this, the database should look like:

```
Concent table: 
[no rows]

Concept.Kind table:
[1 row]
ObjectId: 123, kind: <null>
```

Note the **null** value in the kind column for the created kind. It denotes that the given kind is created with no parent kind - this is the root kind of the entire kind system, the only kind allowed to have **null** as it's kind-value.

**Comment by dan31** [comment]
Archived.
