### ISSUE TITLE
Implement Kind.New()

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2143]
Part of #2129.

In #2137, the root [kind class](https://github.com/Starcounter/Starcounter/wiki/Kinds#terminology) define the `New()` method to support the creation of new concept objects from a given kind. This method must be implemented in a virtual manner (see [1] below).

When invoked, `New()` should be able to 
1. resolve what [concept class](https://github.com/Starcounter/Starcounter/wiki/Kinds#terminology) the current kind is to create a proxy of
2. instantiate a new database core object in the corresponding table and bind it to said proxy
3. set the `kind` field of said object to "this"

Since this is performance critical, the implementation should probably be code generated, either at runtime or with the support of some extension we need to do in the weaver.

**Comment by dan31** [comment]
Archived.
