### ISSUE TITLE
Implement Kind.Of<T>()

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2144]
Part of #2129.

The top-level [kind class](https://github.com/Starcounter/Starcounter/wiki/Kinds#terminology), `Concept.Kind`, expose a method `Of<T>() where T : Concept`. This method should return the system-generated kind created as a reaction to the binding of the kind class for the concept provided by `T`.

Example:

``` c#
class Foo : Concept {
  new class Kind : Concept.Kind {
  }

  void Bar() {
    var kind = Kind.Of<Foo>();
    var foo = kind.New() as Foo;
  }
}
```

**Comment by dan31** [comment]
Archived.
