### ISSUE TITLE
Implement Kind.Derive()

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2145]
Part of #2129. Close resemblance to #2143.

In #2137, the root [kind class](https://github.com/Starcounter/Starcounter/wiki/Kinds#terminology) define the `Derive()` method to support runtime specialization of kinds. This method must be implemented in a virtual manner (see [1] below).

When invoked, `Derive()` should be able to 
1. resolve what [kind class](https://github.com/Starcounter/Starcounter/wiki/Kinds#terminology) the current kind belongs to, and create a proxy instance of that class
2. instantiate a new database core object in the corresponding table and bind it to said proxy
3. set the `kind` field of said object to "this"

Since this is performance-critical, the implementation should probably be code-generated, either at runtime or with the support of some extension we need to do in the weaver.

**Comment by dan31** [comment]
Archived.
