### ISSUE TITLE
Support querying for objects with kinds, and kinds

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2146]
Part of #2129.

To successfully support the full concept of kinds, it must be possible to make a set of queries where the kind is used as a type (while it is actually just a normal object). Hence, the query langague must support the input of kind instances and understand they have a certain meaning.

To fullfill the above, I guess some kind of specialized indexing might be needed.

The most concrete example of a query feature we have in Kinds 1.0 (and hence Starcounter 1.x), but we are lacking now (I think), is the possibility to do a query that filter on a types kind, specifying if the **kind is equal to, or derived from, another kind**. This functionality is used to support method `Kind.IsDerivedFrom` and property `Kind.DerivedKinds`.

An example query (inspired from old `Kind.DerivedKinds`) look like:

``` SQL
SELECT kind FROM Foo.Kind kind WHERE kind.EqualsOrIsDerivedFrom(VARIABLE({0}, kind))=TRUE AND NOT kind=VAR({0}, thiskind)"
```

**Comment by dan31** [comment]
Archived.
