### ISSUE TITLE
Fix separate constant for decimal

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2163]
Lexer already recognizes decimals and floats, however both are returned as `FCONST` token. The fix will require to update the grammar and INSERT INTO statement.

**Comment by henriksjostrom** [comment]
So basically we need some kind of function that maps the string representation received from the query into the int64_t representation used by the CRUD api as that is what we are to use in the background.

**Comment by k-rus** [comment]
I think I need to reconsider this issue. Actually syntactical analysis cannot know if value will be interpreted as decimal or float. Thus we cannot do much about it at this phase. 

@andan342 @henriksjostrom Do I think right?

**Comment by henriksjostrom** [comment]
@k-rus I believe you are right. 

This also plays into the larger question of how our operators should behave. For example is ulong > -2.5 is a valid behavior or not when -2.5 is a query parameter. But that discussion is to large for this issue

**Comment by andan342** [comment]
@henriksjostrom : I see no problem comparing unsigned and signed numbers - IMHO it should always work.

**Comment by andan342** [comment]
@k-rus : The syntactical analysis can identify the minimal containing type for an object. Widening the type at a later stage can be done automatically
(e.g. inserting an integer value into a Double column)

**Comment by andan342** [comment]
BTW, yesterday @henriksjostrom  and I were discussing this in relation to the CRUD API, as it is specified here:
https://git.starcounter.org/BlueStar/level0/blob/pnext/src/include/sccrud.h

A this issue suggests creating `FCONST` tokens for floating-point and `DCONST` for decimal integers, shall we stick to either *Double* or *64-bit signed Integers* at the parser level? Meaning: no *Float*, no *unsigned Integer*?

Then, when involving CRUD API, we can narrow-down the value types with necessary checks and exceptions. I see this as the easiest approach.

**Comment by k-rus** [comment]
> A this issue suggests creating FCONST tokens for floating-point and DCONST for decimal integers, shall we stick to either Double or 64-bit signed Integers at the parser level? Meaning: no Float, no unsigned Integer?

Can you clarify in which case what you propose to use?

If a number is converted into double and then needs to be converted into decimal, then the actual value can become different from original. I believe we need to preserve original value until there is enough semantics to convert into correct representation.

Signed integer cannot fit unsigned integer values.



> The syntactical analysis can identify the minimal containing type for a token. Widening the type at a later stage can be done automatically.

We will still have cases when numbers cannot fit any type. Problem with decimal is that there is no standard type `Decimal` in C++. One way is to keep the values as strings until semantics step as now. May be renaming `FCONST` and `Float` into `DCONST` and `Decimal` as any number literal with dot is a decimal. Or is there syntax to specify floating point number close to machine format?

**Comment by k-rus** [comment]
> Problem with decimal is that there is no standard type Decimal in C++. One way is to keep the values as strings until semantics step as now.

Another approach is to store the values as integers and number of decimal points. @andan342 Is it what you meant?

**Comment by andan342** [comment]
> Another approach is to store the values as integers and number of decimal points.
No, I think storing numbers as strings would solve the same problem. However...

> Can you clarify in which case what you propose to use?

I propose to use either **Double** or **64-bit signed Integers** at the parser stage.

Do we support numeric values which are not supported in C? Like, for example, unlimited-length integers?

If not - then the approach I propose would work just fine. 
If we do support such values - I would suggest to also store the numbers as strings. Then, if it is possible that such a value is stored correctly, it will be converted at that point.

@k-rus , @henriksjostrom WDYT?

**Comment by henriksjostrom** [comment]
@andan342 While it is possible to fit the max value of a uint64_t into a int64_t that is an encoding scheme we really don't want to do. Additionally encoding things as Double leads to loss of precision which is highly undesierable unless the original input is double.

We support decimal which is not part of c++

**Comment by andan342** [comment]
I totally agree - we should not encode integers as **Double** - that's why I propose these two reasonably wide types.

> We support decimal which is not part of c++

Any examples / links to specifications?

**Comment by andan342** [comment]
@henriksjostrom : or, do you mean a specific type which is called *decimal*? 

To me, 'decimal' is the representations of integers, like `format("%d", ...)`. So a parser can recognize a decimal integer number (as opposed to e.g. hexadecimal).

Are we on the same page?

**Comment by henriksjostrom** [comment]
@andan342 I mean a specific type which is called decimal. Even if it is used as int64_t in the crud.

As for the reasonably wide types, if we use say int64_t in the output to represent a uint64_t and someone writes a query with the value UINT64_MAX then out representation will fail to show it accurately as UINT64_MAX>INT64_MAX.

**Comment by andan342** [comment]
> Even if it is used as int64_t in the crud.

So this *decimal* thing is not yet implemented, but planned? Are there any specs to read about it?

**Comment by andan342** [comment]
> someone writes a query with the value UINT64_MAX then out representation will fail

Well, one way to solve this problem is to only support *signed 64-bit integers*. 

If the political decision (of supporting `uint64_t`) is already taken - no problem, the tokenizer actually never emits negative numbers (instead, a unary `-` operator and then a positive number. And so the syntactic parser can emit an expression subtree instead.  In this case `uint64_t` will be our reasonably-wide type for integers.

**Comment by mtornwall** [comment]
In that case, consider emitting integers as `intmax_t`.

As for decimal, you can find the current implementation of the encoder/decoder [here](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.Internal/X6Decimal.cs).

**Comment by andan342** [comment]
@mtornwall : Thanks, martin, but the specs link

http://www.starcounter.com/internal/wiki/Slots#Decimal

is broken.

**Comment by mtornwall** [comment]
I know. Sorry to say, but I think you'll have to read the source. :laugh:

**Comment by andan342** [comment]
So, there used to be docs, but we lost them? Are there any backups?

**Comment by andan342** [comment]
> In that case, consider emitting integers as intmax_t.

As I can see from this discussion, `intmax_t` can be a `long long int` with VS, and `int128_t` with GNU C:

http://stackoverflow.com/questions/20459513/is-intmax-t-the-same-as-long-long-int

So, what if someone dumps a database on Linux and then tries to load it on Windows? Should we report 'integer overflow'?

And, since `intmax_t` is signed, it does not solve the [problem](https://github.com/Starcounter/Starcounter/issues/2163#issuecomment-262994025) pointed out by @henriksjostrom.

**Comment by mtornwall** [comment]
> So, what if someone dumps a database on Linux and then tries to load it on Windows? Should we report 'integer overflow'?

Starcounter itself doesn't store 128-bit integers, so it wouldn't be possible to dump it.

However:

> And, since intmax_t is signed, it does not solve the problem pointed out by @henriksjostrom.

This is an excellent point, so in that case I suppose that `uint64_t` and `uintmax_t` are the remaining candidates.

**Comment by k-rus** [comment]
SQL must support all the types, which our database, i.e., kernel, supports. The types are: `ulong` (unsigned 64 bit int), `long` (signed 64 bit int), `string` (UTF16 strings), `binary` (byte array), `decimal` (our X6 decimal), `float` (23 bit floating point number), and `double` (64 bit floating point number). Correct me if I missed any types. `float` might be deprecated in future. Implementation of `decimal` might be changed in future to be sync with C# decimal, which is 128 bits, but no discussions are going on. Currtenly we use 64 bits for non-variable types as it is the most efficient way to use CPU.

For the rest SQL should return meaningful errors.

It is not acceptable to lose precisions for any of the types except `float` and `double`.

Values should be casted to correct datatypes as soon as possible. So I don't like idea to store unsigned int as signed int. This should be solved in good engineering way.

**Comment by k-rus** [comment]
We discussed the issue. All non-integer number values need to be stored as string to be able to return meaning full errors with users, where tokens represent input value. Integer values (signed and unsigned) can be converted into string back and having the same representation.

So no work is required (may be only renaming), so I close the issue.

**Comment by andan342** [comment]
The summary of the changes is posted at:

https://github.com/Starcounter/RebelsLounge/blob/master/query_processor/numeric_values_in_AST.md
