### ISSUE TITLE
Create float and decimal values in lexer

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2164]
Since Lexer already parses the number strings, it can create the decimal or float instead of a substracting the string.
The values will be assigned to `ival` field and correct token be returned, either FCONST or DCONST. Since the use of the value is unknown it might be not good idea to conver decimal value to X6Decimal.

**Comment by andan342** [comment]
As a result of discussion with @k-rus, we keep storing float and decimal values in the `val.str` union field of 'Value` nodes. The corresponding node type is always 'T_Float' for all numeric values which are either not integers, or fall out of 64-bt integer range (unsigned or signed).

The summary of the recent changes is posted at:

https://github.com/Starcounter/RebelsLounge/blob/master/query_processor/numeric_values_in_AST.md

**Comment by k-rus** [comment]
I close the issue as it is necessary to keep float/decimal values in strings.
