### ISSUE TITLE
Filter application outputs in Polyjuice

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2172]
For Polyjuice, we have set up a principle that each request is delivered to all applications running in the system.

Polyjuice Launcher delegates the request (e.g. `/dashboard`) to the applications, receiving mergable responses known as Polypages:

```
X.GET("/dashboard", out resp);
launcher.results = resp;
```

Now, as I user, sometimes I would like to see only output of application A and hide outputs of applications B, C, D. It still means that all applications should be running but only application A should be sent to the client.

So, there should be a server side layer for Polyjuice that returns a list of boolean options to the client to choose the filtered applications. Then it includes in the JSON output only for the visible applications.

**Comment by alemoi** [comment]
I think this should work now, since I changed the whole levels system and some merging problems. Please report again if you experience the problem.
