### ISSUE TITLE
Ugrade server with web visit app

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2177]
The main reason for this issue is to see that Unload/Reload is working.

Here is instruction how to unload and then reload the database
## Unload

0. Backup the database or server.
1. Download Starcounter build 2.0.7619.2 either from [the build server](https://scbuildserver/viewLog.html?buildId=22748&tab=artifacts&buildTypeId=bt23), or file *Starcounter-2.0.7619.2-Setup.Unload.exe* from Marcin exchange dropbox, or ask @k-rus.
2. Download [UnloadDatabase.cs](https://gist.github.com/k-rus/867bb7bae2ceb1ed41f7).
3. Uninstall the current version of Starcounter
4. Install Starcounter build 2.0.7619.2. During installation set the database path to the actual path, e.g., *C:\Users\starcounter\Documents\Starcounter\2.0.1438.3\Personal*, and **reply NO to the question to replace the database**.
5. If the database path was not set during installation, fix *Personal.xml* in *C:\Program Files\Starcounter\2.0.7619.2\Configuration* to have the path to the database with the data. This step requires to stop Starcounter processes by calling `staradmin killall`
6. Start the application either according to the application instruction or just with `star` and the name of the executable.
7. Do unload with help of `UnloadDatabase.cs` by `star UnloadDatabase.cs`.
8. Write down the reported number of objects unloaded.
9. Find file `ReloadData.sql` in `C:\Users\Public\Documents`. It contains the unloaded objects for reload.
10. Report any met problem or ask questions about the instructions in this issue.

## Reload

1. Download latest version of Starcounter, at least from the 22th of July or daily build 2.0.7627.2 and up.
2. Uninstall Starcounter, i.e., version 2.0.7619.2.
3. Install the new version of Starcounter. The database path should not be modified or should be set to an empty location.
4. Generate binary of the application where MATERIALIZED_INDEX is replaced with MATERIALIZEDINDEX or MaterializedIndex (SQL is case-insensitive).
5. Start the application binary by `star`, e.g., `star theApp.exe`
6. Reload the database by calling `staradmin`, e.g., `staradmin reload`. It assumes the file with data to reload is called `ReloadData.sql` and placed in `C:\Users\Public\Documents`, i.e., where it was unloaded.
7. Note that the same number of objects is reloaded as unloaded.
8. Test the database and the application.
9. Return the application back to the operation.
10. Do what you want with the old database.
11. Report any problems or ask questions here.

**Comment by k-rus** [comment]
Is this issue still relevant?

**Comment by k-rus** [comment]
@warpech 
Is this issue still relevant?

**Comment by warpech** [comment]
No, that was a one time thing. Closing.
