### ISSUE TITLE
Implement new Attributes

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2184]
This issue is about adding the attributes and populating the metadata tables and not about the functionality provided by the attributes.
### Type

See #2183 
### TypeID

See #2160 
### Inherits

See #2183 
### TypeName

See #2183 
### WhatIs, WhoIs, Property, Subject

These attributes all mean the same thing. The reason there are multiple options is the paradigm that you like (edges as subject/predicate/object or edges as normal objects or edge as properties). See https://github.com/Starcounter/Starcounter/wiki/Graphs
### ToWhat, ToWhom, Object

These attributes all mean the same thing. The reason there are multiple options is the paradigm that you like (edges as subject/predicate/object or edges as normal objects or edge as properties). See https://github.com/Starcounter/Starcounter/wiki/Graphs
### ObjectID

Maps to the string answered by `DbHelper.GetObjectID()`
### ObjectNo

Maps to the ulong answered by `DbHelper.GetObjectNo()`
### Synonym

Replaces `SynonymousTo`

**Comment by Starcounter-Jack** [comment]
@per-samuelsson I believe that the pending next branch is a good milestone to do all the renames.

**Comment by per-samuelsson** [comment]
> I believe that the pending next branch is a good milestone to do all the renames.

I agree. I have a few other reviews I'd like to discuss and settle. I'm just about to add them to a seperate issue of their own.

**Comment by per-samuelsson** [comment]
No longer apply.
