### ISSUE TITLE
Better error message required

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2196]
When performing the following API call:
```c#
X.GET<string>("nonexistent.html");
```

We get the following error:
```c#
System.Net.Sockets.SocketException (0x80004005): No such host is known at
System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port) at
Starcounter.NodeTask.PerformSyncRequest()
```

1. We should generate a better error message.
2. How do we determine if nonexistent.html is a host name or a local resource?

Example:
```c#
Cannot locate host "nonexistent.html". Did you mean to locate a local file?
If so, use an initial slash (i.e. "/nonexistent.html" ).
```

**Comment by alemoi** [comment]
This problem should be automatically fixed during recent major changes. X is gone and replaced with Self and Http.

**Comment by warpech** [comment]
I just checked  the current behaviour out of curiosity.

Currently `X.GET<string>("nonexistent.html");` returns null without an error message. 

Fine for me.
