### ISSUE TITLE
Fix error message for unknown type

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2201]
As it can be seen in [here](https://github.com/Starcounter/Starcounter/wiki/Reloading-database-between-Starcounter-versions#example-of-failed-reload-exception) the error message contains type name in wrong word order:
>System.Exception: ScErrSqlUnknownType (SCERR7037): The type is unknown. The name of the table or database class specified in the query is unknown and cannot be matched to a database type. The error near or at position 6, near or at token: Department.EmployeeDb.RegressionTestApplication.

**Comment by atifsheikh** [comment]
Is this bug fixed in SC Version 2.0.3226.3?

**Comment by k-rus** [comment]
> Is this bug fixed in SC Version 2.0.3226.3?

The bug is open and was never fixed. You can see the name of the table/class in correct order in the query reported in the error message.

**Comment by atifsheikh** [comment]
So how do I load the data in my DB?

**Comment by k-rus** [comment]
> So how do I load the data in my DB?

This bug has to do just with the error message. The error message specifies, which class you are missed to load. So if you want to load data you need to have the class be loaded. Otherwise, you need to write your own logic for unload to disregard the data.
Then if you want to migrate data from one class to another class you need to make apps, which will do it for you in several steps of upgrading. We don't provide tools for that.

**Comment by k-rus** [comment]
> So how do I load the data in my DB?

If you have more questions about how to unload data, create a separate issue. This issue is not about how to load.

**Comment by k-rus** [comment]
This issue will not be fixed for develop. pnext contains new implementation for INSERT INTO.
