### ISSUE TITLE
Handsontable listens to keyevents even if it do not have keyboard focus

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#2211]
How to reproduce:
*in the Administrator SQL page.*

* Enter a query and exeucte it
* Click in a cell handsontable
* Click in the Textarea where you entered the query
* Press the left/right arror keys to move the cursor in the textarea.

Now you will see that the focus border in handsontable also moves around.

Maybe issue #1993 is also related to this.

**Comment by warpech** [comment]
Fixed by https://github.com/Starcounter/Starcounter/commit/38b7402b041fa5ca05dbd18f84b4b84c04b046c3. Handsontable now defocuses correctly when focusing the SQL textarea. Dobule scrollbars are not there anymore.
