### ISSUE TITLE
JSON highlighting in VS 2013

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#2214]
Now VS 2013 can highlight JSON, and it hints JSON definitions with syntax warning like that:
![untitled2323](https://cloud.githubusercontent.com/assets/7162535/3867114/90edf4dc-1ff0-11e4-9db2-2f4b67a9f4be.png)
What should be change in order to make JSON definitions display without syntax warning?
I'm not sure whom to address the question to, @chrhol or @per-samuelsson?

**Comment by chrhol** [comment]
Closing this issue as the question is answered.

**Comment by warpech** [comment]
On a side note, I think that in our samples we should only use "strict" JSON, because that is the only JSON. Defining keys without quotation marks drives all JSON-aware tools crazy.
