### ISSUE TITLE
Patch versioning for asynchronous communication

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2244]
There are scenarios in which client can send a patch based on outdated information about the current view-model state at the server.

This has already been reported by @malx122 (multiple times, last time in: https://github.com/Starcounter/Starcounter/issues/1717)

Today a meeting was held between @Starcounter-Jack, @chrhol, @alemoi and me. Below are short notes from the meeting.

Observations:
- client needs to understand the version of the data at server
- client should can calculate the patch only if there is no pending response from the server
- client should queue up any user actions if it is waiting for a response from the server and only then calculate the patch or invalidate the action. Examples:
  - if I have 2 buttons clicked and click on 1 button removes the other button --> the resulting patch is empty
  - if I want to write “hello” to server… after I press “h” and send it to server, the “e” should only be sent of “h” was not rejected

Currently, server acknowledges the patch by responding with the same patch (see https://github.com/Starcounter/Starcounter/issues/1345). In future, it can be optimised  - if the server returns nothing, it will also mean it acknowledged the change. Only if the server responds with a patch that violates the client's speculation about the current view-model, it means that the patch was rejected.

Solution to the asynchronous communication problem: **optional** `__version` metadata on the view-model root. `__version` is a number that is increased by server (and is read-only by the client)
If the `__version` is specified in the view-model, client sends it with every request so the server knows the version this patch applies to.

Version assertion can be done using JSON-Patch `test` operation: http://tools.ietf.org/html/rfc6902#page-7

The client can send a patch to an outdated version and server will try to apply it. Server should keep the log of the view-model changes so it actually know what change does the client mean, even if the array indexes has changes since the version the client knows (as in Git)

Rationale:
Multiplayer drawing app. We have 4 clients connected to same server who are drawing on a single canvas at the same time. So many people drawing at once will produce a constant stream of patches. No client ever knows the current state of the view-model. Server needs to accept patch for an outdated version of the view-model and propagate the drawing to the other users.

On a side note: document version should actually be part of the JSON-Patch protocol but it is not, so we need to make up for it.

@Starcounter-Jack, @chrhol, @alemoi - please review the above notes and the title of this issue and feel free to edit it if I have put something wrong.

**Comment by chrhol** [comment]
I just pushed the implementation of transformation and some unittests for the server. Next step would be to try it out in a real app instead of just unittests.

**Comment by warpech** [comment]
I pushed the VersioningTest here: https://github.com/starcounter/versioningtest

Right now it only reproduces the first problem (Contact Remove). I will add the second problem (Who Wants to be a Millionaire) today.

@tomalec, @chrhol can you add the parts that turn the version control on?

**Comment by chrhol** [comment]
I've added the needed changes to enable versioning and OT on the server, but left them commented out. To enable change `page.Session = new Session()` to `page.Session(SessionOptions.PatchVersioning)` on rows 19 and 55

**Comment by warpech** [comment]
I added "Who Wants to be a Millionaire" test to https://github.com/Starcounter/VersioningTest. It is quite a fun to write games with Starcounter :)

**Comment by tomalec** [comment]
One note: both examples tests transformations being made on server-side, it would be nice to have an example for OT on browser as well.

As in out case browser sends only `replace` operation objects we need to have conflict between `replace` and `replace` like, when we are trying to replace something in child node of something that was already replaced.

Like, auto-complete of edited input, or more complicated example:
Browser updates the street field of mailing address 
```js
{op: "replace", path: "/client/mailingAddress/street", value: "Main Street 123"}
``` 
then sets entire address to null as billing one will be used 
```js
{op: "replace", path: "/client/mailingAddress", value: null}
``` 
then comes server response to the first request with zip-code for given address 
```js
{op: 'replace', path: "/client/mailingAddress/zipCode", value: "12345"}
```
which should be ignored, as new version of `"/client/mailingAddress"` was already send from browser to server to handle, and there is not place to put `"12345"`.

**Comment by warpech** [comment]
@chrhol - I think this can be closed now, do you agree?

**Comment by warpech** [comment]
Closing as done
