### ISSUE TITLE
Investigate a potential problem with process shut-down

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#2246]
@malx122 experiences random hangs/shut-offs, Starcounter might be a source of it. The type of problem we haven't experience yet. @malx122, at first point, can you describe the pattern here? At least, time in between SC processes start-up and shut-down, what processes are missing after the shut-down, how do you resurrect from the case.

**Comment by alemoi** [comment]
I think this issue was fixed during the last month. Closing.

**Comment by dan31** [comment]
@alemoi, what was the related issue number?

**Comment by alemoi** [comment]
I'm not sure if @chrhol created an issue related to some problem in JSON serialization because that was the cause of the issue, as I understood. @chrhol what do you think?
