### ISSUE TITLE
How to get cookies from request header when a Handle is called

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#2262]
```
void Handle(Input.ButtonClicked action) {

   <<get cookies from request header>>

}
```

**Comment by miyconst** [comment]
As @alemoi said there is no way to get/set cookies/haeders in Handle method. Instead an HTTP REST call should be used for that.

There are two new methods to set cookies/headers:

```csharp
Handle.AddOutgoingCookie()
Handle.AddOutgoingHeader()
```

`GoogleSignIn` and `SignIn` apps work in that way to set auth cookie.

@andwah this issue should be closed, should not it?

**Comment by andwah** [comment]
@miyconst Yes. ill close it.

**Comment by andwah** [comment]
The answer is that you can not get the cookies.
