### ISSUE TITLE
Force cache invalidation when static resources are changed (question)

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#2299]
Our website www.starcounter.com runs on Starcounter. After Anders changed pictures and pages there, you need to reload the website skipping the cache (Ctrl+R, Ctrl+Shift+R) in all popular browsers to see those changes. If you just load the site, changes remain invisible. This behaviour is misleading in many cases (too many people can miss those changes for quite a long time).

Is there some way to force cache invalidation with Starcounter? I believe there should be some header attached to response. @andwah, maybe you too have a suggestion?

**Comment by ivarbergman** [comment]
Hi! Is this a ticket/question that could be addressed again? Could the Starcounter web server use some kind of header based invalidation mechanism for static content. Ie use Etag/Last-Modified headers instead of 

    Cache-Control:public,max-age=31536000

for static files.

Thanks / Ivar

**Comment by alemoi** [comment]
Thank you for the question! I will check the latest behavior and get back you.

**Comment by ivarbergman** [comment]
Would:

    Cache-Control: max-age=0, must-revalidate
    Last-Modified: [file modification time]

be appropriate response HTTP headers. And HTTP status `304` if request header `If-Modified-Since` match file modification time.

**Comment by warpech** [comment]
@alemoi would it be possible to add some response filter API so that anyone would have a chance to adjust cache and other headers at their will?

**Comment by alemoi** [comment]
Yes, there is such API already. That modifies the outgoing responses. I will write about it.

**Comment by ivarbergman** [comment]
Hi! Are you referring to ´Handle.AddResponseFilter´ ? (Looks like it might do the trick.)

Is there some method to get the absolute file path to the requested static resource?

I have looked at the ´StaticWebServer´ but I'm not really sure how to get the StaticWebServer-instance connected to the current Request. Or is there a better way?

**Comment by alemoi** [comment]
Yes, that was the thing. Regarding resource path you can probably get this from resource Response object after static resource resolution, not Request. There is a property `FilePath` that is now internal, but I will make it public.

**Comment by ivarbergman** [comment]
Access to the `FilePath`  property would be great!
Thx

**Comment by ivarbergman** [comment]
Or maybe all getters for the file related properties could be public? 
`FileExists `, `FileModified `, etc

**Comment by alemoi** [comment]
Yes, I will make them public.

**Comment by ivarbergman** [comment]
Hi @alemoi  

Short follow up question:

I can see that commit 63421dec9591281f12763e5593aa1ab57a04c662 made these properties public.

But in my Starcounter version, 2.0.33, these properties are still not available. Is this commit only available in SC 2.1?

/Ivar

**Comment by alemoi** [comment]
Thank you for the question! Yes, this is correct. You can get the latest version here: http://starcounter.io/download/

**Comment by dan31** [comment]
Closing this one as a duplicate of #3427 as reported by @warpech.
