### ISSUE TITLE
Memory manager is dead once in 1731

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2311]
When I run build server on 1731 I’ve got once ScErrMemoryManagerIsDead. The build is https://scbuildserver/viewLog.html?buildId=23617&buildTypeId=Starcounter_DevelopDaily&tab=buildLog

Another build did not get this problem.

According to @eriohl the reason might be because sccode.exe tries to connect before scdata.exe is properly initialised. Another build did not get it, since it had time to initialise. More specific error messages should enable determining the exact nature of the problem. So we will monitor to get it.

**Comment by eriohl** [comment]
Seems to not be a problem any more. Should get a better error message if and when it happens again.
