### ISSUE TITLE
No query after semicolon should be allowed

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2319]
`;` is used to separate multiple queries in a single string. The following statement parses fine:

``` sql
SELECT a[MyNamespace.Father].Name FROM Person a WHERE a.Name = 'Alice';
SELECT a[MyNamespace.Father].Name FROM Person a WHERE a.Name = 'Alice'
```

Notice that the last statement does not contain `;` at the end. It is common to present `;` at the end, but it does not work currently. So the following two queries will fail to parse:

``` sql
SELECT a[MyNamespace.Father].Name FROM Person a WHERE a.Name = 'Alice';
SELECT a[MyNamespace.Father].Name FROM Person a WHERE a.Name = 'Alice';
```

and

``` sql
SELECT a[MyNamespace.Father].Name FROM Person a WHERE a.Name = 'Alice';
```

**Comment by k-rus** [comment]
The goal of the issue to fix the parser that it works correctly with semicolon at the end of the last statement.

**Comment by k-rus** [comment]
Part of an [internal issue](https://git.starcounter.org/BlueStar/level0/issues/55)

**Comment by andan342** [comment]
A prototype fix in branch **position** is the most liberal one: it allows semicolon after the last query, i.e. 

*a list of queries separated by `;` with or without `;` in the end*. 

It also allows consequent series of ';' with no queries between them, as long as there is at least one valid query present.

I would suggest to use this approach as the least problem prone. It would allow query generators to generate series of queries interleaved with `;`, and also dropping some of the queries, like:

```
CREATE TABLE ... ;
CREATE INDEX ;
;
INSERT INTO TABLE ... VALUES ... ;
```

However, it does not satisfy the request in the header: it allows queries after semicolon!

@k-rus : Please confirm it's a good idea, and then we can merge!

**Comment by andan342** [comment]
Changes pushed to **develop**. I also found a way to keep the old error message *"Query string must contain a valid statement."*, which I believe is more informative than just a syntax error at a certain position. 

In the end of the day, this fix does not involve any changes to the grammar - only the point where an error is thrown.

**Comment by andan342** [comment]
However, if we decide not to allow 'empty queries' in between semicolons, this would be easy to do by actually adding `NULL` statements into the AST, and checking for them at the next stage of analysis. 

This would involve no change to the grammar either.

**Comment by k-rus** [comment]
The implementation of rules is not simple/natural enough. Separate issue created: https://git.starcounter.org/BlueStar/level0/issues/164

The result will be published here.

**Comment by k-rus** [comment]
Implemented

**Comment by warpech** [comment]
Should this be closed, too? https://github.com/Starcounter/Starcounter/issues/3767
