### ISSUE TITLE
Build agent is down and memory exceeded error

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2343]
One build agent is down. No nightly build was running last night. The build server reports:
>TeamCity server memory usage for PS Old Gen pool exceeded 100% of 341 MB maximum available. 335 MB used of 455 MB total heap available. See the TeamCity documentation for possible solutions.

**Comment by alemoi** [comment]
I am not sure if this issue is still relevant, but will assign @parherman if its ok for you.

**Comment by parherman** [comment]
I believe this happened because of a hardware error that was corrected in February and I have not seen this since, closing this issue now
