### ISSUE TITLE
Reregistering / handler causes 404 NotFound

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2371]
In my app ("Warehouse2" in my Exchange folder) I have a very simple GET `/` handler. 

When I have my application running, then stop it, make a change in my code, rebuild the application and start it again, the `/` handler does not work anymore. Instead, it returns `404 NotFound` error. Moreover, the static files return `400 BadRequest` error.

The only solution right now is to kill the server and start it again.

**Comment by dan31** [comment]
@warpech, is that still an issue?

**Comment by warpech** [comment]
Nope, works fine now

**Comment by alemoi** [comment]
That time there was probably some temporary problem causing this wrong behaviour. Closing the issue.
