### ISSUE TITLE
Build server hangs on exception during nightly builds

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2390]
I've noticed that if exception happens in builds other than Daily-Develop, the build agent hangs. See [the last one](https://scbuildserver/viewLog.html?buildId=24181&buildTypeId=Starcounter_DevelopNightly&tab=buildLog).

**Comment by alemoi** [comment]
Most probably this is no longer relevant. And the build log is not available anymore. Closing the issue.
