### ISSUE TITLE
Built 32bit components sets environment variable for nightly build

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2392]
*Build32bitcomponents.bat*, which has to be run manually in Starcounter development environment, contains the line:
> set SC_RUNNING_ON_BUILD_SERVER=True

What is the reason to have it? The batch script is executed not only on build server (where it is already set), but also locally. In the case of local execution it is not expected the variable to be set.
Can it be removed or reset after execution to original value?

**Comment by alemoi** [comment]
I have completely removed the need to build 32 bit components and public assemblies explicitly. So now, whenever you build Level1 - those would be built automatically! Pushed to `develop` only for now. Thank you very much for noting this! Please do it for everything you think is uncomfortable.
