### ISSUE TITLE
Administrator SQL is unresponsive to keyboard

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2400]
I have problem sometimes that when I type an SQL statement in Administrator it does not get the characters, i.e., keystrokes do not appear on the screen.

**Comment by dan31** [comment]
This repeats sometimes, remains an issue.

**Comment by warpech** [comment]
Fixed in https://github.com/Starcounter/Starcounter/commit/38b7402b041fa5ca05dbd18f84b4b84c04b046c3. Thanks @k-rus for reporting, sorry that it took so long!
