### ISSUE TITLE
Help converting obsolete Index logic

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2404]
Hi!

I'm trying to upgrade my code from April, 2.0.1722.3:

    var toDelete = Db.SQL("SELECT i FROM materialized_index i WHERE i.Name <> ?", "auto").ToList();
    foreach (Starcounter.Metadata.materialized_index userIndex in toDelete)
    {
        Db.SQL(string.Format(
          "DROP INDEX {0} ON {1}",
          userIndex.name, userIndex.table.name));
    }
 

materialized_index table no longer exists.

**Comment by k-rus** [comment]
I guess the issue can be closed. If not, welcome to reopen.
