### ISSUE TITLE
Call SocietyObjects handlers all the way up in the ontology tree

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2408]
We discussed with @Starcounter-Jack that the handlers for concepts in an upper ontology should respond to lower ontology requests.

For example, Skyper app currently explicitly defines request handlers:

```c#
Handle.GET("/societyobjects/ring1/person/{?}", (String objectId) => { /* ..... */ }));
Handle.GET("/societyobjects/ring2/organisation/{?}", (String objectId) => { /* ..... */ }));
```

Since both `Person` and `Organisation` extend `LegalEntity`, Skyper should be able to register just a single handler:

```c#
Handle.GET("/societyobjects/ring1/legalentity/{?}", (String objectId) => { /* ..... */ }));
```

And have this handler called each time someone calls one of the following:

```c#
X.GET("/societyobjects/ring1/person/" + objectId);
X.GET("/societyobjects/ring2/organisation/" + objectId);
```

**Comment by alemoi** [comment]
I think this one is already fixed long time ago using `Polyjuice.OntologyMap` functionality. Closing the issue.
