### ISSUE TITLE
Misleading error about transaction due to implicit write transaction

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2412]
I have the following code:
```c#
	static void Main() {
		Db.SQL("create index NikcNameIndx on \"User\" (NickName)");
		new User { FirstName = "Alex", LastName = "Ivanov", NickName = "Lion" };
	}
```

It fails with:
> Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entry
point method raised an exception. ScErrCantExecuteDDLTransactLocked (SCERR4266):
 Failed to execute DDL statement, since a transaction cannot be created for the
execution. This can happen if the statement was called in a user-specified trans
action scope. Cannot execute CREATE INDEX statement.

However, the code does not contain any transaction. Actually it should fail on new database instance creation. This misleading error happens due to implicit write transaction. See #2218

**Comment by chrhol** [comment]
This issue is resolved now. You get a more correct exception when the User is created.

> Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entry
point method raised an exception. ScErrReadOnlyTransaction (SCERR4093): The tran
saction is readonly and cannot be changed to write-mode.
