### ISSUE TITLE
Administrator queries different database then chosen

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2414]
In SQL tab of Administrator I chose database `default`, however the submitted queries are issued against another running database. To solve the problem I have to switch to another database, issue a query and then switch back to `default`.

I don't know how it is difficult to reproduce. I guess it depends on some combination of restarting databases, switching between tabs, executing queries.

It's not an expected problem, thus takes enormous time to understand why data are not as expected.

**Comment by andwah** [comment]
Solved, How databases is selected and used when executing queries has changed.
