### ISSUE TITLE
External login to Starcounter for access via iframe

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2427]
I want to log in a user to my Starcounter app from an external site using a simple javascript request and then have that user being able to access the app in an iframe where he should be logged in. 

The problem is that the Starcounter session that is used to log in the user isn't stored by the browser and consequently the user isn't logged in to the app in the iframe. 

I have this bit of html code to log in the user (and I can verify by querying the database that the session is logged in): 

		<head>
		<script type='text/javascript' src='http://adfenix.wpengine.com/wp-includes/js/jquery/jquery.js?ver=1.11.1'></script>
		<style>
		iframe[seamless]{
			background-color: transparent;
			border: 0px none transparent;
			padding-left: -10px;
			margin-left:-10px;
			overflow: hidden;
		}
		</style>
		<script>
		function login(){
				jQuery.getJSON('http://localhost:8080/adfenix/signintest/testusername/testpassword', function(data) {
				});
		}
		</script>
		</head>
		<body>
		<button onclick="login();">Click to login</button>
		<iframe frameborder="0" allowtransparency="true" scrolling="no" height="100%" width="100%"src="http://localhost:8080/launcher/workspace/adfenix/segmentationrules"></iframe>
		</body>

And this code in my app where I use the SignInApp for user authentication. 

            Handle.GET("/adfenix/signintest/{?}/{?}", (string username, string password) =>
            {
                Response response = new Response();
                string origin = "";
                if (response.HeadersDictionary.ContainsKey("Origin"))
                {
                    origin = response.HeadersDictionary["Origin"];
                }
                else {
                    origin = "null";
                }
                response.StatusCode = 200;
                response.ContentType = "text/html";
                response.HeadersDictionary = new Dictionary<string, string>() {
                        { "Access-Control-Allow-Origin", origin},
                        { "Access-Control-Allow-Credentials", "true"}
                    };
                if (Session.Current == null) {
                    var s = new Session();
                    string reply = "";
                    string sessionId = s.SessionIdString;
                    SignInApp.Server.SignInOut.SignInSystemUser(username, password, "", sessionId, out reply);
                    response.Body = sessionId;
                    response.Cookies.Add("Location=%2F__default%2F"+ sessionId +"; path=/");
                    response.StatusCode = 200;
                    return response;
                }
                response.Body = "Already logged in";
                return response;
            }, opt);
        }

**Comment by dan31** [comment]
@Ripipip, @warpech, any new thoughts there?

**Comment by Ripipip** [comment]
Yes, this is not a problem anymore. I believe it was fixed somewhere along the way.
