### ISSUE TITLE
SqlParser and SqlProcessorManager must be built using /EHa

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2434]
Reported by @linkdata in another issue tracker.

The SQL parser/processor DLL's declares the following functions as external (implied "C") linkage and then throws a C++ exception from them:

```
extern void ThrowException(char *msg);
extern void ThrowExceptionCode(int scerrcode, char *msg);
extern void ThrowExceptionReport(int scerrorcode, int position, wchar_t *token, char *message);
```

From the MSVC docs (http://msdn.microsoft.com/en-us/library/1deeycx5.aspx):

```If used with s (/EHsc), catches C++ exceptions only and tells the compiler to assume that functions declared as extern "C" never throw a C++ exception.```

**This invokes undefined behaviour.** I've fixed this in the CMake build files, but it needs to be fixed in the MSVC solution/project files as well. `/EHsc` is the default for projects. Technically, setting either `/EHs` or `/EHa` will resolve this.

**Comment by k-rus** [comment]
@alexanderstc 
What do you think about this issue?

**Comment by alexanderstc** [comment]
The parser and sqlprocessor are fine both makefiles and projects.
Fixed the metalayer makefile too, now it's OK.
Succeeded on the buildserver on my pvt build, pushed to pnext, waiting for the buildserver to be fixed.

**Comment by alexanderstc** [comment]
Fixed, in pnext.
