### ISSUE TITLE
Browser "Back" or "Duplicate tab" brings up JSON instead of HTML

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2442]
With PuppetJs, we load HTML and JSON representation of a page using HTTP `GET` from the same location.

Despite having the `Cache-Control: no-cache` header, browsers such as Chrome cache the last response for a URL. In result, using <kbd>Duplicate</kbd> or <kbd>Back</kbd> button (after manual change of the URL) brings up JSON instead of HTML.

![duplicate-json-page](https://cloud.githubusercontent.com/assets/566463/5362215/83a6f8a0-7fd1-11e4-8003-a6928bfed87e.gif)

Proposed solution: change `Cache-Control: no-cache` to `Cache-Control: no-store` wherever it is used. 

That should be enough in some case, despite the fact that the problem is more sophisticated (see http://stackoverflow.com/questions/49547/making-sure-a-web-page-is-not-cached-across-all-browsers)

**Comment by warpech** [comment]
@alemoi I believe you fixed that on 18.12.2014. Can this be closed?

**Comment by alemoi** [comment]
Yes, that's correct, closing this.
