### ISSUE TITLE
Keep artifacts on build server or reference from build server

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2443]
To be able to investigate customer issues we need to keep all artifacts.
For example, to investigate #2439 I need installer for 2907, but it is removed from the server.

**Comment by k-rus** [comment]
This is almost a showstopper. There are two bug reports, which require a version from December 22, but no artifacts exist on build server.

**Comment by alemoi** [comment]
For now I have extended the clean up policy to "Artifacts older than the 50th successful build". Let's see if that works out better. The best way would be to upload every nightly to somewhere with a big storage. This needs @dan31 involvement.

**Comment by alemoi** [comment]
Reassigning this issue to @parherman 
Let me know if you want to discuss this.

**Comment by dan31** [comment]
@k-rus question answered today positively.
