### ISSUE TITLE
Application.ToString() no longer reveals the name of the application

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2446]
I noticed that if you create a new application (```staradmin +```), the template code

```C#
using Starcounter;
using System;

class Program {
    static void Main() {
        Console.WriteLine("{0} starting...", Application.Current);
    }
}
```

no longer print the name of the application when you run the application. 

If I run this application from a file ```app.cs``` (like ```star app.cs```), it should print "app starting...". It now prints "Starcounter.Application starting...".

**Comment by per-samuelsson** [comment]
From #2982 

> I think #2446 was caused by @alemoi moving the application class some time, from Starcounter to Starcounter.Internal or something like that. Thats when it was broken at least. I can assign it to me to try to figure out what broke it though.

@alemoi, what was the reason you did this move, do your remember? I saw now you didn't only move that, but moved `ApplicationBase` into there too.

It kind of messed up much of the thought I had with these classes, and the experience they would have inside the code host to application developers, and I think I will have to now make some redesign to get this to work back like it used to, and was inteded too. That will be easier to do if I understand the reason you did this move, so I can try to figure out some other way supporting whatever it was you found lacking.

**Comment by per-samuelsson** [comment]
Hmm, its pretty clear why the original issue stopped working too, since both properties `Application.DisplayName` and `Application.FullName`, and the overridden, `Application.ToString()` method was just deleted in 52311370cf8c72529199046f53062ea22dd525d5.

**Comment by alemoi** [comment]
I guess the reason was a need to use application name in low levels, far below what it was placed initially. Since we started to use application name in many different areas, that was a quick fix I made, Im not sure if I discussed it with you.

**Comment by per-samuelsson** [comment]
> I guess the reason was a need to use application name in low levels,

OK, thanks. 

But I find only one single place where it is used, in `\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ConsoleOuputRestHandler.cs`, in class `CircularStream`, I find method `GetAppName()`, implemented like this:

```C#
private string GetAppName() {

            try {
                if (Application.Current == null) return null;
                return Application.Current.Name;
            }
            catch (Exception) {
                return null;
            }
        }
```

And if the current name is all you need, its already there, without moving these classes, since if you look at the implementation of `Application.Current`, it just fetch `StarcounterEnvironment.AppName` to get the name. Why not just use that?

**Comment by alemoi** [comment]
Thanks for the clarification! In this case, I guess you can revert the change, if you can of course. As long as all tests pass, this is not an issue at all. Let me know if I should revert/check it.

**Comment by per-samuelsson** [comment]
> Thanks for the clarification! In this case, I guess you can revert the change, if you can of course.

OK, great! That will both solve this issue, and also I can do the stuff I planned to do in the code host, and what was the idea of those classes in the first place. Thanks for the feedback. I'll do it. Just wanted to check with you first. :+1:

**Comment by alemoi** [comment]
Sounds awesome! Thank you for your work!

**Comment by per-samuelsson** [comment]
Done. Merged and pushed in https://github.com/Starcounter/Starcounter/commit/2a6bc915338ab39889dacd4ace82ccbc17a25797.
