### ISSUE TITLE
Default project structure

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2459]
The default project folder structure should be simplified for our project templates.

For the ```hello-world``` Starcounter project

```
/webroot/index.html
/index.json
   + index.cs
````   

For the ```hello-world``` Polyjuice project
```
/webroot/hello-world/index.html
/index.json
   + index.cs
````

**Comment by alemoi** [comment]
Currently we use auto-detecting `wwwroot` folder as described above. Applications then have sub-folders named as applications, and also `sys` folder sometimes. Closing until changes required.
