### ISSUE TITLE
White screen error

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2469]
Since I've explained the error a few times to different people I thought I could just explain it here instead. 

I'm experiencing some issues in the frontend where sometimes the screen goes white/blanc - no interface is returned. 

This can only be reproduced when the application is under load from live traffic on our server. 

It is reproduced by just clicking on a random link in the application multiple times. 

For as long as you get this response it is fine: 
[{"op":"replace","path":"/workspaces/0/master","value":{"AdFenix":{"Html":"/client/partials/admin/start.html","ObId":"","RedirectUrl":"","EmailReport$":false,"EmailNotification$":false,"UserGroup$":"admin","Domain$":"","Save$":null,"Undo$":null,"Delete$":null},"Html":"/polyjuice-merger?AdFenix=/client/partials/admin/start.html"}}]

But when your JSON response lack the app name it returns the correct "interface" but the request after that will fail. 

[{"op":"replace","path":"/workspaces/0/master","value":{"Html":"/client/partials/admin/start.html","ObId":"","RedirectUrl":"","EmailReport$":false,"EmailNotification$":false,"UserGroup$":"admin","Domain$":"","Save$":null,"Undo$":null,"Delete$":null}}]

The failed request returns the html file which cannot be processed and the screen is blanc. 
** HTML FILE AS RESPONSE **

**Comment by Starcounter-Jack** [comment]
@Ripipip 
Which issues do you want to mark as your current ```showstopper```s (if any). Could you list them here and I'll label them as such.

**Comment by Ripipip** [comment]
I haven't been able to reproduce this since I updated Starcounter to 2999 so on my end I would consider this closed.
