### ISSUE TITLE
Puppetjs interfers with local objects 

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2471]
We are trying to create a regular polymer component for just changing tabs that shouldn't be shared with the server. 

However, with the implementation below we can't change tabs without getting an error from puppetjs. 

Trying to add ignore (according to this documentation: https://github.com/PuppetJs/PuppetJs#ignoring-local-changes-ignoreadd) doesn't work because puppetjs in the Launcher points to the root template and the content of our app isn't in the root template. 

So we either want to know why the component below is shared with the server - and how we can avoid it - or how we can make the ignoreadd feature in puppetjs work in our app. 

Implementation:

    <adfenix-tabs selected="{{_selected}}">
        <adfenix-tab>Test</adfenix-tab>
        <adfenix-tab>Test2</adfenix-tab>
    </adfenix-tabs>
    <span>selected: {{selected}} {{ item }}</span>

Component: 
    <link rel="import" href="/sys/core-selector/core-selector.html">

    <polymer-element
        name="adfenix-tabs"
        extends="core-selector"
        role="tablist"
        flex horizontal layout>
    <template id="tabs">
        <shadow></shadow>
    </template>
    <style>
        adfenix-tabs  {
            background: beige;
        }
    </style>
    <script>
        Polymer('adfenix-tabs', {
            ready: function () {
                this.super();
                this.selectedIndex = 1;
            }
        });
    </script>
    </polymer-element>
    <polymer-element name="adfenix-tab">
    <template>
        <div class="tab" flex auto center-center horizontal layout>
            <content></content>
        </div>
    </template>
    <style>
        adfenix-tab {
            cursor: pointer;
            user-select: none;
            padding: 5px;
            border: 1px solid #E2E2E2;
        }
        adfenix-tab.selected {
            color: red;
        }
    </style>
    <script>
        Polymer({});
    </script>
    </polymer-element>

**Comment by andwah** [comment]
What kind of error do you get from puppetjs?

**Comment by Ripipip** [comment]
PuppetJSON Response Error

Server responed with error 400 bad request. 

Unsupported patch operation in patch.

**Comment by Ripipip** [comment]
On another component we added the "hack" below to be able to move on but I don't think it is a good solution. 

 elem = document.querySelector('puppet-js');
                if(elem) {
                    elem.outerHTML = "";
                    delete elem;
                }

**Comment by warpech** [comment]
> Trying to add ignore (according to this documentation: https://github.com/PuppetJs/PuppetJs#ignoring-local-changes-ignoreadd) doesn't work because puppetjs in the Launcher points to the root template and the content of our app isn't in the root template.

This actually should not be true. The aim of `ignoreAdd` is to match property name at any level in the tree. Maybe your regexp makes it match only root-level properties? Could you paste the content of your `ignoreAdd` property here?

**Comment by Starcounter-Jack** [comment]
Maybe the solution is the same as in this issue #2470. I.e. that Puppet-Js only sends correct patches.

1. If the patch value is of the wrong type, Puppet-Js will try to convert it.
2. If the patch is for a non existing property, Puppet-Js will ignore it.

It might solve both this issue and #2470?

**Comment by tomalec** [comment]
The issue occurred to be wrong property name (one without which didn't start with `_`) in JSON view-model.

Duplicated HTML code was not an issue as it was original template content + stamped instance.

**Comment by warpech** [comment]
@Starcounter-Jack Yes, this issue would not exist if Puppet-Js would ignore all adds. I think it would be nice to just turn `ignoreAdd` on for all properties created on client (with an option to turn it off).

**Comment by tomalec** [comment]
So maybe we could provide:
1. `ignoreAdd=true` - ignores all add operations
2. `ignoreMatch=/_.*/` - ignores all operations (add, replace, remove..) for matching paths
So it could solve also  PuppetJs/PuppetJs/issues/35, #2468.5
