### ISSUE TITLE
Document impact of new dynamic type related custom attributes

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2473]
In #2264, #2266 and #2269, parts of #2184 - to introduce custom attributes to support declaring and using **dynamic types** - started its implementation.

Since these attributes have quite an impact on how Starcounter operate, we must make sure to document their functionality and how they affect applications and databases thoughly. This should be done on the [wiki](https://github.com/Starcounter/Starcounter/wiki) eventually.

I will begin by adding some "raw" content from internal discussions to this issue, and try to keep it up-to-date with future changes/additions in parallell to these features are actually implemented.

(One idea is to use this initial content as the base of test-driven development when doing the implementation).

**Comment by per-samuelsson** [comment]
**Listing 1**
```C#
[Database] public class Car {}
class Program {
  static void Main() {
    Console.WriteLine(Db.SQL<Car>("SELECT * FROM Car").First);
  }
}
/* Output: null */
```
Comment: When not using the dynamic type custom attributes, Starcounter will operate as now.

**Comment by per-samuelsson** [comment]
**Listing 2**
```C#
[Database] public class Car {
  public CarModel Model;
}
[Database] public class CarModel {
  public string ModelName;
}

class Program {
  static void Main() {
    Console.WriteLine(Db.SQL<Car>("SELECT * FROM Car").First);
    Console.WriteLine(Db.SQL<CarModel>("SELECT * FROM CarModel").First);
  }
}
/* Output: 
      null
      null
*/
```
Comment: Still not using the dynamic type custom attributes, hence similar experience to **Listing 1**.

**Comment by per-samuelsson** [comment]
**Listing 3**
```C#
[Database] public class Car {
  [Type]
  public CarModel Model;
}
[Database] public class CarModel {
  public string ModelName;
}

class Program {
  static void Main() {
    Console.WriteLine(Db.SQL<Car>("SELECT * FROM Car").First);
    Console.WriteLine(Db.SQL<CarModel>("SELECT * FROM CarModel").First);
    Console.WriteLine(new Car().Model);
  }
}

/* Output: 
      null
      [model]
      [model]
*/
```
Comment: Here, *[model]* is the implementation of ```CarModel.ToString()```. With the introduction of the ```Type``` attribute, Starcounter will react by creating an instance of class ```CarModel``` to hold the metadata of cars, and it will also connect any new ```Car``` instance to this auto-created ```CarModel``` instance.

**Comment by per-samuelsson** [comment]
**Listing 4**
```C#
[Database] public class Car {
  [Type]
  public CarModel Model;
}
[Database] public class CarModel {
  [TypeName]
  public string ModelName;
}

class Program {
  static void Main() {
    Console.WriteLine(Db.SQL<CarModel>("SELECT * FROM CarModel").First.ModelName);
  }
}

/* Output: 
      Car
*/
```
Comment: We now introduced the ```TypeName``` custom attribute, and Starcounter will react to that by establishing the relationship that ```CarModel``` is the model of the ```Car``` class and that the default ```ModelName``` hence will be ```Car```. This can obviously be modified afterwards.

**Comment by per-samuelsson** [comment]
**Listing 5**
```C#
[Database] public class Car {
  [Type]
  public CarModel Model;
}
[Database] public class Car2 {
  [Type]
  public CarModel Model;
}
[Database] public class CarModel {
  [TypeName]
  public string ModelName;
}

class Program {
  static void Main() {
    Console.WriteLine(Db.SQL("SELECT COUNT(*) FROM CarModel"));
  }
}

/* Output: 
      2
*/
```
Comment: A new Car class was introduced ("```Car2```") and hence a specific corresponding model was instantiated. See comments from previous listings why. There is now one with the ```ModelName``` "Car", the other with "Car2".

**Comment by per-samuelsson** [comment]
**Listing 6**

Focus: Introducing the ```[Inherits]``` attribute.

```C#
[Database] public class Car {
  [Type]
  public CarModel Model;
}

[Database] public class CarModel {
  [TypeName]
  public string ModelName;

  [Inherits]
  public CarModel BasedOn;
}

class Program {
  static void Main() {
    Console.WriteLine(Db.SQL<CarModel>("SELECT * FROM CarModel").First.BasedOn);
  }
}

/* Output: 
      null
*/
```
Comment: As explained earlier, there will be a single instance of ```CarModel``` present (due to the fact that ```Car``` has declared it as it's type). However, this model has no base type, and hence **null** is displayed.

**Comment by per-samuelsson** [comment]
**Listing 7**

Focus: Studying the workings of the ```[Inherits]``` attribute.

```C#
[Database] public class Car {
  [Type]
  public CarModel Model;
}

[Database] public class EnglishCar : Car {}

[Database] public class CarModel {
  [TypeName]
  public string ModelName;

  [Inherits]
  public CarModel BasedOn;
}

class Program {
  static void Main() {
    Console.WriteLine(Db.SQL<CarModel>(
      "SELECT * FROM CarModel WHERE ModelName == 'EnglishCar'").First.BasedOn.ModelName
    );
  }
}

/* Output: 
      Car
*/
```
Comment: When the ```Car``` class is specialized (```EnglishCar```), there will now exist 2 ```CarModel``` instances in the database; one for ```Car``` and one for ```EnglishCar```. The later will have it's ```BasedOn``` field assigned to ```Car```.

**Comment by k-rus** [comment]
> Listing 1
> 
> Focus: plain use of Starcounter, simple single class.
> 
> [Database] public class Car {}
> 
> class Program {
>   static void Main() {
>     Console.WriteLine(Db.SQL<Car>("SELECT * FROM Car").First);
>   }
> }
> /* Output: null */
> Comment: When not using the dynamic type custom attributes, Starcounter will operate as now.

Am I correct that intention was to write the following query:
```c#
Console.WriteLine(Db.SQL<Car>("SELECT c FROM Car c").First);
```

**Comment by k-rus** [comment]
> Am I correct that intention was to write the following query:
> 
> Console.WriteLine(Db.SQL<Car>("SELECT c FROM Car c").First);

I noticed the same problem with queries in all listings. I guess the intention is to retrieve object, not a projection of all columns. @per-samuelsson: can you clarify?

**Comment by per-samuelsson** [comment]
> @per-samuelsson: can you clarify?

I considered a disclaimer in the original post, stating that everything that was not directly usage of custom attributes for dynamic types was to be considered **pseudo code**. The exact syntax of SQL, to me, was not at all the focus here. I choose not to omit the disclaimer, but appearantly that was a bad idea.

If you want perfect correctness, you are of course free to update all the samples!

**Comment by per-samuelsson** [comment]
No longer apply.
