### ISSUE TITLE
Remove automatic cache for internal REST calls

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2474]
[EDITED:Correct example below]

**Comment by alemoi** [comment]
Great! I will do that!

**Comment by warpech** [comment]
Can this also work in Polyjuice merged apps? Last time I checked, `Session.Current.Data` returned null if session was implicit (created by the Launcher, tried to retrieve the session object in an app)

**Comment by Starcounter-Jack** [comment]
Alexey and I worked out how to write code without the implicit cache. This is the pattern that we recommend:

```c#

Handle.GET("/email/{?}", (long no, Request r) => {
  var s = GET<MasterPage>("/master").SubPage;
  if ( s != null && s.Uri == r.Uri ) {
    // We already have the correct email up, just return the reference to it.
    return s;
  }
  return new EmailJson() { Uri = r.Uri };
};
```

We will add a public string called ```Uri``` on the Json class. This property can be use to make a note on the location of the existing resource in the view model tree. In this way, you can manually avoid recreating a JSON object that is already there. The cache can then be obsoleted and make Starcounter perform less magic.

**Comment by alemoi** [comment]
Forgot to mention that these changes are in place, except that property name in Json dedicated for cache is called `CacheUri` (this name is temporary to avoid collisions with existing projects that already have a property named `Uri`).
