### ISSUE TITLE
Implicit write transactions

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2476]
I have to admit defeat on this one. Because we cannot roll back state changes in .NET, it will be to easy to introduce side effects when implicit transactions are restarted due to optimistic concurrency control. I think, until we can guarantee side-effect restarts, we need to disable implicit write transactions. When you do explicit transactions, however, you need to stay clear of performing side-effects inside the transaction scope (doing state changes in databases is, of course, fine).

**Comment by chrhol** [comment]
:thumbsup: I will merge this one with the other implicit transaction issue (#2218) and assign to me. I will remove it ASAP.
