### ISSUE TITLE
Reimplement IS operator to use implicit columns

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2478]
In branch **next**, every object now support a set of implicit columns that hold data about the given objects state relating to "dynamic types". As an example, all objects have columns to reference a (dynamic) type object and to indicate if they are a type themselves.

Currently, the SQL **IS** operator is based on metadata stated used custom attrbiutes. This metadata is consumed by the weaver, and later stored as part of internal runtime structures (i.e. ```TypeDef```, ```TypeBinding```, etc). The design was made before implcit columns became available.

I think we should change the implementation to instead consult implicit columns. I think a query such as ```SELECT f FROM Foo f WHERE f IS {FooType}``` (where "FooType" is any instance of a database class) should be treated semantically as "consider all [f] whose [implicit column 'type'] reference either reference [FooType object ID], or whose [implicit column 'inherits'] reference a base type that reference [FooType object ID] recursively.

(I'm not considering TypeID here, since in the final implementation, that should be used as an optimizer I guess).

@k-rus, @dan31, any thoughts on this?

**Comment by per-samuelsson** [comment]
> @k-rus, @dan31, any thoughts on this?

I'm actually hesitating about this suggestion myself. I'm currently trying to review everything we did to code host runtime metadata structures before implicit columns and sew it together, at the same time resolving #2385. Let's see where that ends up before we bring up any discussion.

**Comment by k-rus** [comment]
If the methods will be removed or behavior changed then it is important to update IS implementation to use the columns. Otherwise, I suggest to wait and change the implementation to use TypeID directly, since implementation using TypeID should be done in any case.

**Comment by per-samuelsson** [comment]
> Otherwise, I suggest to wait and change the implementation to use TypeID directly, since implementation using TypeID should be done in any case.

After more reviewing and some work to fix #2385, I agree on the above. I'll close this issue.
