### ISSUE TITLE
Merge latest kernel changes, i.e., 2279 and 2279_noRecordFlag, into next

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2481]
Before the merge can be done, number of issues has to be completed. Example of issues to do:

1. Fix installation Id.
2. Implement TypeId generation and population for each new type, both hard and soft.
3. Refactor meta-data part

Doing the merge is important, since there are limitations, which will be resolved. For example, currently *next* allows up 14 indexes per table, which limits the length of an inheritance.

The merge will bring some limitations. There is a separate issue with their description.

Doing the merge is quite big project, which requires to fix new meta-data population and the old query processor. For example, neither systables and SqlProcessor is disabled in #2279.

This issue needs to be completed with more tasks and links to existing related issues.

**Comment by eriohl** [comment]
#2605

**Comment by k-rus** [comment]
@eriohl 
I am wonder why does layout need both layout_id and name? What is the purpose of having layout name?

**Comment by eriohl** [comment]
You need a user generated id (or something) to find the layout id. Layout id is allocated on commit so it is not known until after layout is great. Also, you need to be able to lookup the layout for a specific class on load.

This of course can be done some other way (like checking the layout columns). It does not have to have a name really. I suspect locating the appropiate layout will be an issue on type binding.

**Comment by eriohl** [comment]
The layout id should actually be layout handle.

**Comment by k-rus** [comment]
Thank you for the explanation! Now it is clear the need in both of them. I agree it is good idea to rename `layout_id` to `layout_handle`. 
I wonder if layouts have names. As I understood they don't match one-to-one to tables/classes/types/sets. Can the same layout be used for representing different tables, which have the same schema? What happens if the schema is changed, i.e., there are objects of the same type with different layouts? Should the layout name (or name token) be different in such case?
What other requirements on name token, which is used for naming layouts and columns?
For example, I don't understand if a separate table is needed to store mapping between string names and name tokens and how to deal with case (in-)sensitivity.

**Comment by eriohl** [comment]
> Can the same layout be used for representing different tables, which have the same schema?

Yes.

> What happens if the schema is changed, i.e., there are objects of the same type with different layouts?

This is this expected layout stuff I had a big presentation on a while back. Essentially the values of any record can be accessed as it has any layout. If in fact the actual layout differs from the expected layout then the kernel reads the value on token.

For example: Lets say you have 2 record layouts: Person1 and Person2. Both have the column Name:String but in Person1 the column has index 2 while in Person1 the column has index 4.

Then the client can assume that all Person-s have layout Person2 so when reading Name (which would be a token, not a string) is reads the string column with index 2 and the expected layout Person2.

If then the underlying record actually has the layout Person2 then it simply reads index 2 and every is nice and fast. If it has not however, but instead has layout Person1, it:

1. Reads the token from Person2 index 2. Which would be Name.
2. Checks which index the column Name has in Person1. Which would be 4 (in not found it returns default).
3. Checks that this column has the type expected (Person2 index 2). Which you be a string and in this case it does (if it did not it returns default).
4. Returns value of column 4 instead.

This is all done by the kernel so it not something the client has to worry about. All the client needs to do it figure out which layout it expects records of a specific type has and use this.

Then when a record is written with a new layout the layout of the record is changed on commit. That is: If we write to a record with Person1 layout as it had Person2 layout it will be stored with Person2 layout on commit.

> Should the layout name (or name token) be different in such case?

No. Then is would be a different layout (?)

> What other requirements on name token, which is used for naming layouts and columns?

Only one layout in can have a specific name. Only one column within a specific layout can have a specific name (that is: There can only be one column with token 5 in a specific layout).

Kernel do not care what the string value of a token. This is up to the client. But if you want to be able to read a column value from a record which has a different layout then the column indicating needs to have the same name token in both layouts.

**Comment by k-rus** [comment]
I remember the presentation. Wha I really was missing the implementation details and what is assumed by the kernel.



> Should the layout name (or name token) be different in such case?
> No. Then is would be a different layout (?)

The layout structure is different in my example, but name is the same. Is it possible? For example, a type `Person` was created with one layout, then there was change in the layout, e.g., added a column or removed a column, or switched column places or several such changes. The new layout has still the same name, but it is different. Your example seems to be similar but the two layouts are given two different names `Person1` and `Person2`. So I am still confused.
If in my case the layouts have to have different names, then the names are not really names, but ids. Can you clarify this?
There are cases when types/sets don't have names. So calling layout name is confusing in any case.

**Comment by eriohl** [comment]
No. They can't have the same name. The name has to be unique. But why they could not have a name for this reason I don't really get.

What about this then:

What is not layout_name we can call layout_id (this is a user generated 64-bit id).
What is not called layout_id we call layout_handle (this is generated by database engine and is 16-bits).

Ok?

**Comment by k-rus** [comment]
> What is not layout_name we can call layout_id (this is a user generated 64-bit id).
> What is not called layout_id we call layout_handle (this is generated by database engine and is 16-bits).
> 
> Ok?

Yes. I think it will be less confusion. The source for names are user identifiers, which are not one-to-one mapped to kernel represenetation.



> But why they could not have a name for this reason I don't really get.

Dynamic type object does not require to have name, thus types can be without name. I don't know if Starcounter will provide an interface to add properties to a type object, i.e., create a layout without name. I guess this functionality will be necessary for graph part of unified database paradigm. I don't know if such situation can happened in javascript (never worked with it yet).

**Comment by eriohl** [comment]
Been a lot of sickness and such so haven't gotten around to addressing this. But considering this some more I feel reluctant to call what is now name id instead. The reason for this is record id, which is auto generated. So I think it more consistent if the user generated keys in the interface is called name while the auto generated keys are called id.

As for anonymous types I would argue that they do have a name although it is a generated name that is invisible to the user code. This might be a construct of the runtime of course but in a way so it this. So I don't really see the conflict. Also this should then apply to columns (fields) and indexes as well since they could also be anonymous. So then we should for consistency not have names on anything that now have names.

What we could do it rename name to token everywhere in the kernel interface. If the token then correlates to a name or not is up to the (kernel) client.

Then (in kernel interface):
handle=Indirect address of kernel object: Index handle, Layout handle and Record handle (record handle is a weak 16-bit handle).
token=Non-kernel generated unique identifier.
id=Auto generated unique identifier: Record id.

Then we could use a bit in the token to indicate it is correlates to a name or not or something like this.

What do you think?

**Comment by k-rus** [comment]
I agree with the suggested names. Just clarification questions:
1. Is `token` unique identifier per database or per database object type, i.e., per table, per index and per column?
2. Was Record id earlier called `ObjectId`?

**Comment by eriohl** [comment]
> 1. Is token unique identifier per database or per database object type, i.e., per table, per index and per column?

There are no tables in the kernel generally it is unique per object type (there can only one layout with a specific token but an index can have the same token). Column tokens are unique per layout and is also used as a column identifier when converting between layouts.

> 2. Was Record id earlier called ObjectId?

It is the same as ObjectNo in client. It was called object id in kernel interface previously although this was a long time ago. So yes I suppose.

**Comment by eriohl** [comment]
Discussed changes to naming done (in the interface at least).

**Comment by dan31** [comment]
What about that one @k-rus, closing?

**Comment by k-rus** [comment]
The task 2 is important to do. The task 3 is ongoing. Only the task 1 is not needed, since new code host will be implemented.
Since there is no separate issue for task 2 I suggest to keep this issue open.

**Comment by k-rus** [comment]
obsolete issue
