### ISSUE TITLE
Starcounter always runs as a service on my machine

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2490]
I am doing development and I installed Starcounter together with VS extensions from local build into Starconter's bin folder. When I start any application with `star`, `sccode` is started in elevated mode, so I cannot do any development tasks without putting all programs in elevated mode too. This is not how it should work.

I noticed the issue first time last December. I discussed the problem with @per-samuelsson and he has changed anything related to this. The most likely the problem was introduced with @alemoi changes.

**Comment by alemoi** [comment]
Starcounter always runs as a service when installed on a custom machine. To change this behavior you have to disable the Starcounter service in Windows Services.

**Comment by k-rus** [comment]
> Starcounter always runs as a service when installed on a custom machine. To change this behavior you have to disable the Starcounter service in Windows Services.

When and why was the behavior changed? According to @per-samuelsson the prerequisite for service is no VS extension installed. If VS extension is installed then it is a development machine and Starcounter should run as non-elevated process.

**Comment by k-rus** [comment]
@alemoi confirmed that he introduced the bug.

**Comment by k-rus** [comment]
As I understood the bug is fixed now.
