### ISSUE TITLE
Rename Db.Transaction to Db.Transact

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2491]
With the changes for the longrunning transaction (#2403), @Starcounter-Jack suggested that `Db.Transaction(...)` should be renamed to `Db.Transact(...)`. Part of this is to make it a little bit clearer  since the longrunning transaction is called `Transaction` and it is a bit confusing when the method and class are called the same. Also the definition of Transact fits the operation being done (http://www.merriam-webster.com/dictionary/transact)

**Comment by eriohl** [comment]
Db.Atomic(...)?

**Comment by Starcounter-Jack** [comment]
We should probably have a verb.

![screenshot of screenfloat 20-01-15 11 11 56](https://cloud.githubusercontent.com/assets/1219049/5815334/2a54dbca-a095-11e4-9e70-5f2646a909a8.png)

**Comment by chrhol** [comment]
Pushed to develop, but yet to next.

**Comment by chrhol** [comment]
Pushed to next.
