### ISSUE TITLE
Add constraint to [Type] target - must be based on base type

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2497]
Consider the following model:

``` C#
public class Car : Entity {
  [Type] public CarModel Model;
}
[Database] public class CarModel {
  [TypeName] public string Name;
}
```

Here, `Car` is based on `Entity` while `CarModel` is not. Hence, the following code will raise a runtime exception (due to an invalid cast):

`````` C#
var e = new Car() as Entity;
var t = e.Type;  // CarModel is not an ```Entity```
``````

This constraint relates to our .NET binding and I guess the best place to implement it is in the weaver.

**Comment by Starcounter-Jack** [comment]
Why does CarModel have to be based on Entity?

**Comment by per-samuelsson** [comment]
> Why does CarModel have to be based on Entity? It only needs to be based on the same type as the type object for Entity.

Second sentence answer the question in the first. :smile:

> So your statement should only be true if entity is defined as:
>
>```c#
>public class Entity {
>   [Type] public Entity Type;
>}
>```

Exactly. That is how it **IS** implemented. And hence ```Car.Type``` can only be used if the type assigned can be casted to an ```Entity```, something ```CarModel``` in this case can not.

**Comment by per-samuelsson** [comment]
Just want to make 2 things clear:

* ```var t = Car.Model;``` would still work fine.
* This is no big showstopper or something we should prioritize right now. Just added an issue to make sure I don't forget it later on.

**Comment by Starcounter-Jack** [comment]
Then everything is as expected.

**Comment by per-samuelsson** [comment]
No longer apply.
