### ISSUE TITLE
Implement Entity.Create()

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2500]
Part of #2159. Should be briefly documented in #2499, and later in the wiki.

This issue is about implementing ```Entity.Create()``` in the most basic way. That is, with this feature implemented, we can create instances from known types (represented as entities).

This will be done in **next**.

We also need to support creating new **types** on the fly. This should be done by a "pseudo type" (i.e. the type-of-a-type). This will be done in a separate issue however.

**Comment by per-samuelsson** [comment]
Consider the following model:

```C#
public class Foo : Entity {}
```

After binding/initialization, Starcounter will have auto-created two instances - both types. In the current implementation, both these are instances of .NET type ```Entity```. One is named "Entity"; the other is named "Foo";

Now consider this:

```C#
var f = new Foo();
f = (Foo) f.Type.Create();
```

A new ```Foo``` instance is created (```new Foo```). Then we retreive its type, which would be the ```Entity``` auto-created from binding, named "Foo". When we call ```Create``` on it, we'll get back an ```Entity```, not a ```Foo```. Hence, the second line will fail with an invalid cast.

**Comment by per-samuelsson** [comment]
To solve the problem in the previous post, we have a few alternatives:

1) We keep it as it is, and treat it as "by design". After all, the ```Foo``` class has not declared any particular custom type representation, so then creating new ```Foo``` instances this way will not be doable.

2) We make sure the auto-created type (which is now in the ```Entity``` table) keeps a reference to the (high-level) type it is assumed to instantiate when ```Create()``` is called. Hence, the runtime will know that it must instantiate a ```Foo``` in the case above. Exactly how the underlying reference will look we'll work out later (I guess we can start just using the name).

3) We make the auto-created type a ```Foo```, not an ```Entity```, already from the start.

**Comment by per-samuelsson** [comment]
I'm starting with this implementation:

> 2) We make sure the auto-created type (which is now in the Entity table) keeps a reference to the (high-level) type it is assumed to instantiate when Create() is called. Hence, the runtime will know that it must instantiate a Foo in the case above. Exactly how the underlying reference will look we'll work out later (I guess we can start just using the name).

I'll have the reference to the high-level type to instantiate be the name of it (since it's already present). This is not the long term-solution, but should be revised together with the introduction of type ids.

Since the implementation will be somewhat temporary, I'm not gonna spend any time on proper error checking and introducing new error codes. This has to be done later on.

**Comment by k-rus** [comment]
According to the concept, the instance representing a type does not belong to the type. I.e., `(new Foo()).Type` does not belong to `Foo` and `(new Entity()).Type` does not belong to `Entity`. I.e., `select e from Entity e` will not contain them. Therefore, it might be necessary to have implicit type `EntityType`, which might not have a meaningful name.

When an instance is created from a type instance, it should belong to the correct type. I.e., `(new Foo()).Type.Create` will result in the instance belonging to `Foo` as suggested in 2).

**Comment by per-samuelsson** [comment]
> I.e., (new Foo()).Type.Create will result in the instance belonging to Foo as suggested in 2).

Yes, this is clear.

> According to the concept, the instance representing a type does not belong to the type. I.e., (new Foo()).Type does not belong to Foo and (new Entity()).Type does not belong to Entity. I.e., select e from Entity e will not contain them.

OK, this is not how it is implemented now. And then we must change things to get it to work. Either we have to change the datatype of ```Entity.Type```. This is somewhat related to #2480. Or we have to return something that is an ```Entity```, like we have discussed before. I guess then the best way is to implement #2502, because I guess then what we return from ```Entity.Type``` is an instance of one of the metadata classes, like ```Starcounter.Metadata.Type```.

**Comment by per-samuelsson** [comment]
> I.e., select e from Entity e will not contain them

Regarding the above, are you sure of this? Because this is not what @Starcounter-Jack told me, if I remember correctly. And I don't understand why it shouldn't either.

Also, if we do #2502, I thought the idea was that any metadata instance would be returned in this query as well. Basically, anything that derives ```Entity```.

**Comment by k-rus** [comment]
> Regarding the above, are you sure of this? Because this is not what @Starcounter-Jack told me, if I remember correctly. And I don't understand why it shouldn't either.

I confirm that @Starcounter-Jack said to @per-samuelsson that the instances belong to `Entity`. On the other side @Starcounter-Jack was very explicit and clear to me that `(new Entity).Type` instance does not belong to `Entity` during concept discussions. This is very confusing that contradiction statements are said to different people at different time.

I see that the approach described by @per-samuelsson does not follow concept. However, the implementation needs to do some optimization from the concept. I am not sure if the suggested approach is acceptable or not.

**Comment by per-samuelsson** [comment]
Thanks for the input, @k-rus. Its clear that there is some confussion on this. I'll try straighten it out with @Starcounter-Jack eventually.

I want this issue to be about ```Entity.Create```. I will create another one where we can continue the discussion on querying on ```Entity``` and what it should return.

**Comment by per-samuelsson** [comment]
> I want this issue to be about Entity.Create. I will create another one where we can continue the discussion on querying on Entity and what it should return.

#2510

**Comment by per-samuelsson** [comment]
First (rather unpolished) implemention merged and pushed in https://github.com/Starcounter/Starcounter/commit/187278dc11d137f7be6a7bdeb5de0fda2f0b7d26.
