### ISSUE TITLE
About adding path to static web server

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2501]
I think from yesterday I noticed that *QueryProcessingTest* prints the following line when *sccode* is started:

>Adding path to static web server "C:\GitRepositories\Starcounter\Level1\bin\Debug\s\QueryProcessingTest\.starcounter"

What does it mean? Why does it appear now?

Note that Starcounter is not installed (it was uninstalled) and the test uses low level executables.

I pay attention to this, because the test fails locally. While the test does not fail on build server and **this message is not printed on the build server**.
Was something not uninstalled correctly?

**Comment by alemoi** [comment]
All applications are adding static path to Administrator when they start. Static path is used to serve static files. If its not like this, then its a bug I guess.

**Comment by k-rus** [comment]
> All applications are adding static path to Administrator when they start. Static path is used to serve static files. If its not like this, then its a bug I guess.

As I wrote Starcounter is not installed. There is no Administator. Comments?

**Comment by k-rus** [comment]
Actually it is not related to my problems. Still I am curious how it works in the case of not installed Starcounter.
If I run just the test on build server, it behaves the same as locally, i.e., prints the message.

**Comment by alemoi** [comment]
I was not totally correct. The static path message is displayed when the static files directory is registered on code host, regardless if there is an Administrator or not. So its registered inside the code host and in Administrator.
