### ISSUE TITLE
Merge SystemEntity and Entity

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2502]
Currently, in **next**, we distinguish between "system entities" and "normal enteties" with two distinct base classes: `SystemEntity` and `Entity`. The metadata classes derive the former.

We have decided that eventually, we want to merge the two, effectively removing the `SystemEntity` class. This issue represent that work to be done, and will be used to discuss this and document its implications.

**Comment by per-samuelsson** [comment]
As part of this issue, we should also change the binding so that we don't create any explicit ```Entity``` for every type being bound that derive ```Entity```. Instead, ```Db.TypeOf<Entity>``` should return the best-fit metadata object (probably the ```Starcounter.Metadata.Type``` instance) that is already created.

With that being said, I'm not sure if the above is doable with the current design, considering that metadata is dropped and recreated on every code host restart. That would make it impossible to default assign any user objects to a type using it's object ID as it is implemented now.

**Comment by k-rus** [comment]
> With that being said, I'm not sure if the above is doable with the current design, considering that metadata is dropped and recreated on every code host restart

Only meta-data describing code host environment are dropped on database restart. The meta-data, which describes the schema state of the database, are kept together with the database, since the types are persistent and independent from code host.

**Comment by per-samuelsson** [comment]
> Only meta-data describing code host environment are dropped on database restart.

OK, great.

>  The meta-data, which describes the schema state of the database, are kept together with the database, since the types are persistent and independent from code host.

I suggest we provide some API to detect what types are "volatile" (i.e. recreated on restarts) and what are not.

I suggest we do this issue (#2502) first, and them make a hierarchy similar to this:

```C#
public abstract class SystemEntity : Entity {
  public virtual bool IsRuntimeInstanceDroppedOnRestart {
    get { return false; }
  }
}

public class Type : SystemEntity {
  public override bool IsRuntimeInstanceDroppedOnRestart {
    get { return false; }
  }
}

public class ClrView : SystemEntity {
  public override bool IsRuntimeInstanceDroppedOnRestart {
    get { return true; }
  }
}
```

(Never mind the naming/API, and/or exactly the types. The point is the middlelayer ```SystemEntity``` itself).

Maybe this also can allow queries that can select from Entity (#2510) and exclude/filter all the system types.

**Comment by per-samuelsson** [comment]
This was quite a bit more timeconsuming than I first thought. As usual when I'm asked to change something that involves working with the metadata.

If I understand correctly, I must do quite major changes in how metadata is populated and defined in Level0, not only the relevant changes in Level1. This includes defining the Entity class and all its columns already in Level0, and set up the other metadata tables to extend it.

**Comment by k-rus** [comment]
> I suggest we provide some API to detect what types are "volatile" (i.e. recreated on restarts) and what are not.

Why do you suggest to mark them as *volatile*? Why is it necessary?
Actually the instances life time will be while the application is loaded. There might be changes to this in future.
Note that the instances describes classes, not types. Name of `Starcounter.Metadata.Type` might be confusing, since it means a possible column type, including primitive type, it does not mean Starcounter type. May be `Starcounter.Metadata.Type` should be renamed into `Starcounter.Metadata.ValueType`

**Comment by k-rus** [comment]
> If I understand correctly, I must do quite major changes in how metadata is populated and defined in Level0, not only the relevant changes in Level1. This includes defining the Entity class and all its columns already in Level0, and set up the other metadata tables to extend it.

I don't know. My guess was that it requires just adjust implementation of CLR classes for meta-data, e.g., changing from `SystemEntity` to `Entity`. I didn't expect any changes outside the classes definitions.

**Comment by per-samuelsson** [comment]
> I don't know. My guess was that it requires just adjust implementation of CLR classes for meta-data, e.g., changing from SystemEntity to Entity. I didn't expect any changes outside the classes definitions

This really supprise me, since you have written quite a lot of assertions that will immediately fail once you change the base class. Try it yourself. With Entity, there is suddenly a new set of columns and properties in play for every metadata class, and then the manual binding doesn't work very well at all. 

One example is that it's required for every metadata class to have exactly the same number of columns as there are properties in the class (minus object id). This fails pretty badly (3 != 14 as an example).

**Comment by per-samuelsson** [comment]
> Note that the instances describes classes, not types. Name of Starcounter.Metadata.Type might be confusing, since it means a possible column type, including primitive type, it does not mean Starcounter type. May be Starcounter.Metadata.Type should be renamed into Starcounter.Metadata.ValueType.

Sorry to say, but I totally agree: I think the naming is quite confusing overall. And also, I REALLY miss at least one or two lines of comments on every class that gives an overview for what it represent. Like the one you provided now. I will actually copy it "as is" and add it to the Type class :smile:

**Comment by per-samuelsson** [comment]
We have decided to postpone this, since its too complex to do right now, considering the above discussions. Basically, @k-rus will first need to adapt the defintion of the Level0 datamodel (defined in "metadata population") to include the model we want reflected in Level1.

When we are to do this, the idea is to have two new types defined in Level0: Entity and SystemEntity. The former introduce all the implicit columns defined in the Entity class, roughly as it is defined today in **next**. The later is initially just a "middle-layer" type (with no additional columns) that sits between Entity and all metadata tables. Then the corresponding change is to be done in .NET: SystemEntity remains, but should extend Entity (like the first commits in [this branch](https://github.com/Starcounter/Starcounter/tree/issue/2502) already achieve).

The drawback of postpoing this is that we either have to change the datatype of ```Entity.Type``` from ```Entity``` to ```object``` - to be able to return metadata instances as types - or to keep the temporary solution where auto-created types are still created explicitly by the binding, and those are returned. I will take a decision on what path to go shortly.

**Comment by per-samuelsson** [comment]
No longer apply.
