### ISSUE TITLE
Create simple sample application for server push for view models

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2503]
Progress bar demo

```html
<div>{{ProgressBar}}</div>
```

```json
{
    ProgressBar: 0
}
```

```c#
static void Main() {
   Handle.GET("/importing-in-progress", () => {      
       Session.Current.Run( async () => {
            while (true) {
                 X.GET<MasterPage>("/Master").ProgressBar++;
                 await Session.Current.Yield(); // will push and process incoming requests
            }
       }
     }
   }
}
```

**Comment by alemoi** [comment]
I guess now such a sample is a Chatter application made by @warpech 
I really like it as example. What do you think?

**Comment by warpech** [comment]
Chatter is available here: https://github.com/polyjuice/chatter

It would be good to have a simpler working snippet, that shows both broadcasting to all clients and current session. Such snippet should be documented on starcounter.io
