### ISSUE TITLE
Installer starts Starcounter with as administrator 

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2504]
When installing, the installer of course need administrator access. But the installer also autostarts som starcounter processes that also automatically get administrator access, not good. You can as an example not start any user SC application (if not giving them administrator access)

Workaround is of course killing SC and restart it with normal access. But as long as the above is not solved, I think the installer should NOT autostart any SC processes.

**Comment by k-rus** [comment]
This bug was introduced by @alemoi recently. See #2490. This is very annoying.

**Comment by alemoi** [comment]
The problem was that I thought that it should always start :)
Anyways, fixed via d5930de5d333eaac3b2822eac6f0008209ee847b
Thanks for reporting.

**Comment by dan31** [comment]
@parherman, not sure if that assumption can be included into acceptance test. Keep an eye on it, would be nice to have that assumption tested.

**Comment by parherman** [comment]
@dan31 When we run the installer during the acceptance test we have to launch it as admin, otherwise the ui automation won't work, but we might be able to add a separate test
