### ISSUE TITLE
Better error message with missing property/class in unload

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2509]
If unload fails due to missing property description in internal .NET meta-data, the error message does not give any information, which property caused this. This problem currently appears when a property is not public. See #2485 for example. The error message should be more informative and contain the name of the property and the class.

**Comment by per-samuelsson** [comment]
This is now resolved. It is merged and pushed, along with #2508, in commit https://github.com/Starcounter/Starcounter/commit/00eccd1419c1e5f3d4f8a0ca35923983ce121c66.
