### ISSUE TITLE
About selecting everything from Entity

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2510]
In #2500, we have a discussion about what should be returned from the query `SELECT e FROM Entity e` in various cases. Let's try getting them answered in this issue.

The discussion is about branch **next** (and branches based on that).

 Running every below application in a completely new, empty database, what should be the output?

**Application 1**
Focus: no database class defined.

``` C#
using System;
using System.Linq;
using Starcounter;

class Program {
  static void Main() {
    Console.Write(Db.SQL<Entity>("SELECT e FROM Entity e").Count());
  }
}
```

**Application 2**
Focus: one database class defined, based on `Entity`.

``` C#
using System;
using System.Linq;
using Starcounter;

public class Foo : Entity { }

class Program {
  static void Main() {
    Console.Write(Db.SQL<Entity>("SELECT e FROM Entity e").Count());
  }
}
```

**Application 3**
Focus: one database class defined, using the `[Database]` custom attribute.

``` C#
using System;
using System.Linq;
using Starcounter;

[Database] public class Foo {}

class Program {
  static void Main() {
    Console.Write(Db.SQL<Entity>("SELECT e FROM Entity e").Count());
  }
}
```

**Comment by per-samuelsson** [comment]
In the current, work-in-progress implementation, the facit is **1, 2, 1**.

**Comment by per-samuelsson** [comment]
A related question: the implementation of dynamic types is based on a shared, implicit underlying datamodel. Hence, both ```class Foo : Entity {}``` and ```[Database] class Bar {}``` will share a set of properties (implicitly there in the case of ```Bar```). Examples include ```ObjectNo```, ```Name```, ```IsType```, and a few more.

Should we support a way to jointly select these? Like a view that select "everything"?

**Comment by per-samuelsson** [comment]
> In the current, work-in-progress implementation, the facit is 1, 2, 1.

I've now had a discussion with @Starcounter-Jack, and the facit given the current implementation is correct. 

The bottom-line is this: ```Entity``` is defined by us, and if you select from it, you will get hits, even if you have created no user-level objects whatsoever. Hence, in the above cases, you will get the corresponding type objects (all of type ```Entity```, since nothing else was defined).

An important distinction is that you wouldn't get any hits on ```Foo```, in either of applications 2 or 3.

With that being established, the facit will change with the #2502 implementation; with that in place, you will also get a hit for every possible metadata table. Semantically, we are treating ```Entity``` as the table/extent for "all our objects, and all yours extending the ```Entity``` class".

**Comment by k-rus** [comment]
> In the current, work-in-progress implementation, the facit is 1, 2, 1.
> I've now had a discussion with @Starcounter-Jack, and the facit given the current implementation is correct.

This does not correspond to the concept, which I was requested to make sure to be in place. I guess I don't understand the concept and the concept is not written anywhere, i.e., it does not exist.

**Comment by k-rus** [comment]
I have an idea for this confusion. In the new dynamic type Starcounter there is the big tables, which contains all objects. Selecting from the big table will return all instances exesting in the database. May be `Entity` means the big table in the above context. However, I don't think it is good idea to extend the big table. So it looks like it is naming collision between `Entity` as the big table and `Entity` as the most common concept extended by other types. This needs to be discussed and confirmed.

**Comment by per-samuelsson** [comment]
I actually don't think it is any big confusion, I think its quite simple. If you select from Entity, you will get back all objects that extend the Entity class. This will be all user defined types extending that class, and all our metadata, since we are about to migrate all metadata tables to Entity, in #2502. Its not more complex than that.

The objecs you don't get is those defined as user objects using the ```[Database]``` attribute. The only (not really important) question for me is if we should have a way for users to select on all objects, i.e. one that includes both the former and the later.

**Comment by k-rus** [comment]
According to the concept, which was presented to us by @Starcounter-Jack and is still on the white board in the small conference room, type instances and instances never have common ancestors. Therefore `Car` and `CarModel` should never extend the same type. However, I guess that in SO `Car` and `CarModel` will extend a concept type, e.g., called `Entity`, which introduces a contradiction. In simple model it will look like:
```c#
public class Car : Entity {
  [Type]
  public CarModel Model;
}

public class CarModel : Entity {
}
```
If I understand correctly, it will mean that the following statements are correct:
```c#
Assert((new Car()).Type.BasedOn.Name == "Entity");
Assert((new Car().Type.BasedOn == Db.TypeOf<Entity>());
Assert((new Entity().Type == Db.TypeOf<Entity>());
Asser((new Car()).Type.Name == "CarModel");
```

This also means the following definition of `Entity`:
```c#
public class Entity {
  [Type]
  public Entity Type;
}
```

This means that instance of `Entity` has a type instance, which is an instance of `Entity`, which also has a type instance, which is an instance of `Entity`, and so on. This infinite references can be stopped by looking into the current types, however the implementation becomes complicated. This make impossible to store auto-created type instance in meta-data.
The following two queries should return different result sets:
```c#
Db.SQL("SELECT e FROM Entity e WHERE e IS ?", (new Entity()).Type);
Db.SQL("SELECT e FROM Entity e WHERE e IS ?", (new Entity()).Type.Type);
```
The second query has sense if the above schema with `Car` and `CarModel` is defined.

**Comment by per-samuelsson** [comment]
> According to the concept, which was presented to us by @Starcounter-Jack and is still on the white board in the small conference room, type instances and instances never have common ancestors.

This doesn't sound right to me. It's up to the developer, IMO. Given this model:

```C#
public class Car : Entity {
  [Type] public CarModel Model;
}
public class CarModel : Entity {}
```

the code host binding will create an instance of ```CarModel``` as the "auto-type" of ```Car```.

If you'd change it to

```C#
public class Car : Entity {}
```

it would instead create a type as an ```Entity```. based on that ```Entity.Type``` is defined as ```[Type] Entity Type```, which in turn is an indicator that every class that extend ```Entity``` will have its ```Type``` defined. After we have finalized #2502, the **implementation** of this type will probably be ```Starcounter.Metadata.Type```, but then again, that is not important for the discussion - it's an implementation detail (black boxed).

Finally, if you would change the above to

```C#
[Database] public class Car {}
```

there would **still** be an auto-created type, i.e the same one as in the previous example. But it's not accessible directly from the ```Car``` type. You will still be able to get ahold of it though, but you'll need to use an helper API, i.e. ```Db.TypeOf<Car>``` (which we will change to return **object** as the default, with a generic overload allowing an explicit type to be given, e.g. ```CarModel```).

**Comment by k-rus** [comment]
> public class Car : Entity {
>   [Type] public CarModel Model;
> }
> public class CarModel : Entity {}
> the code host binding will create an instance of CarModel as the "auto-type" of Car.

1. Should this instance of `CarModel` inherit from an auto-generated instance of `Entity`?
2. Should the code host binding create an instance as the "auto-type" of `CarModel` to be prepared for a call `new CarModel()`?

**Comment by per-samuelsson** [comment]
> Should this instance of CarModel inherit from an auto-generated instance of Entity?

No. In this example - when an explicit user-defined type is defined - it's an instance of ```CarModel```.

> Should the code host binding create an instance as the "auto-type" of CarModel to be prepared for a call new CarModel()

Yes and no. :smile: We have decided that we currently start with only "two levels", i.e. we don't create "types of types" in the first implementation. But in the future, yes. In the above model, the instance returned from ```new Car().Model.Type``` will be one of the metadata classes (when it derives ```Entity```, as we are fixing in #2502). Right now it return **null**.

**Comment by Starcounter-Jack** [comment]
We provide a type of any declared type in a equivalent way that can be studied from Smalltalk-80.

This means that the class will be represented by a type object that will have a type that is not null. This means that declaring the type ```Car``` will also declare the type ```CarType``` as is the case in Smalltalk-80 (http://en.wikipedia.org/wiki/Metaclass).

**Comment by per-samuelsson** [comment]
> as is the case in Smalltalk-80 (http://en.wikipedia.org/wiki/Metaclass).

Here is the [direct link](http://en.wikipedia.org/wiki/Metaclass#In_Smalltalk-80) to the Smalltalk portion of the referenced wiki page. Its important, since for example Python (described above) treat types much more like .NET (as meta objects, not real objects).

Our implementation is becoming be very much like the Smalltalk one (plus extra goodies).

**Comment by Starcounter-Jack** [comment]
The runtime type system in Smalltalk has a rather strong foundation in treating types full citizen objects allowing for proper metalevel abstractions. Ours is even stronger IMHO.

**Comment by Starcounter-Jack** [comment]
>> @per-samuelsson: We have decided that we currently start with only "two levels", 

Terminating meta levels is good practice. You can do this with a terminator type or with null. I believe either one will mean the same. Smalltalk goes one level up as otherwise you would have no type representing the ***universal set*** of stuff the user might want to use (in selects, creation and inheritance). I.e. the user must be able to go up one level to find instances

**Comment by per-samuelsson** [comment]
> Terminating meta levels is good practice. You can do this with a terminator type or with null. I believe either one will mean the same.

Yep, I know/agree. And I fully understand what we are aiming to achieve. I think I either was not clear enough in my previous comment, or you took it out from its context. What I meant was that **right now**, we started just to "auto-assure" for two levels. Right after that first step is finished, I'll implement the full monty, with (probably) system-level terminating types as the boundary.

**Comment by Starcounter-Jack** [comment]
@per-samuelsson 
I was actually agreeing with your post and just tried to repeat/reinforce your standpoint :-)

**Comment by Starcounter-Jack** [comment]
In this way, we don't add complexity for devs that don't want to learn metatypes. It is simply a product table in their minds.

**Comment by per-samuelsson** [comment]
@Starcounter-Jack 
Thanks for the input.

I don't see anything in your writing that I don't agree with, and actually nothing either that we have already decided (as far as I have understood). I think we are on a rather straight path into this model with the ongoing work in **next**. If we find particular problems/flaws when working, we have to deal with them at that point.

**Comment by per-samuelsson** [comment]
No longer apply.
