### ISSUE TITLE
The created index is not utilized

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2522]
Inside RetailDemo project (https://github.com/Starcounter/RetailDemo) master branch, we utilize several indexes: https://github.com/Starcounter/RetailDemo/blob/master/Starcounter/Program.cs

Since we did run this demo for testing purposes the code has not been changed, but now by some reason it does select on `CustomerId` using `FullTableScan` instead of `IndexScan`.

To reproduce (I use latest Starcounter develop debug configuration):
1. Build ScRetailDemo solution.
2. `star ScRetailDemo.exe`
3. Run client to create indexes and insert objects in db: `RetailClient.exe -Inserting=True -UseAggregation=True -NumCustomers=10000 -NumTransferMoneyBetweenTwoAccounts=0 -NumGetCustomerAndAccounts=0 -NumGetCustomerById=0 -NumGetCustomerByFullName=0`
4. Check the query plan in Administrator (it should be IndexScan): `SELECT * FROM Customer p WHERE CustomerId = 16334`
5. Do REST call (which underneath does the above select but does it through FullTableScan->MoveNext()): `http://127.0.0.1:8080/dashboard/16334`

You can verify that FullTableScan is used by putting breakpoint in `RetailDemo\Starcounter\Program.cs` line 93 and then `Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs` line 475.

**Comment by k-rus** [comment]
I cannot confirm the problem. I guess the code creating indexes was never called in you case.
What I did:

0. Installed Starcounter from local build in Develop configuration on the latest source code
1. Obtained the Retail Demo.
2. Built it by F6
3. Started it by F5
4. Called the initialization handler from browser, i.e., `http://127.0.0.1:8080/init`
5. Called the query `SELECT * FROM Customer p WHERE CustomerId = 16334` from the Administrator
6. Inspected the query plan to use the index:

>Tables(
 0 = ScRetailDemo.Customer
)
Projection(
 0 = 
  IntegerProperty(0, CustomerId)
 1 = 
  StringProperty(0, FullName)
 2 = 
  ObjectNoProperty(0, ObjectNo)
 3 = 
  ObjectIDProperty(0, ObjectID)
)
IndexScan(
 CustomerIdIndex ON ScRetailDemo.Customer
 0
 CustomerId
 IntegerDynamicRange(
  NumericalRangePoint(
   GreaterThanOrEqual
   IntegerLiteral(16334)
  )
  NumericalRangePoint(
   LessThanOrEqual
   IntegerLiteral(16334)
  )
 )
 LogicalValue(TRUE)
 Ascending
)

**Comment by k-rus** [comment]
By the way when you execute your query from Administrator you can also query for existing indexes, e.g.:
````sql
SELECT * FROM Starcounter.Metadata."Index"
```

Another comment the application must use 'Index' instead of `MaterializedIndex`, since the second one is deprecated and will be removed. An example of usage:
```c#
if (Db.SQL("SELECT i FROM Starcounter.Metadata.\"Index\" i WHERE Name = ?", "CustomerIdIndex").First == null)
  Db.SQL("CREATE UNIQUE INDEX CustomerIdIndex ON Customer (CustomerId asc)");
```

**Comment by alemoi** [comment]
After further investigation we found that JSON was performing a database query during `Data` assignment. Its located in RetailDemo `Program.cs`:
`json.Data = Db.SQL("SELECT p FROM Customer p WHERE CustomerId = ?", customerId).First;`

with the actual SQL query: `SELECT a FROM Account a WHERE a.Customer=?`

from `Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs` call to `CheckBoundArray` (line 294). And there is no index explicitly created on `Account.Customer` that's why its using `FullTableScan`.

During init the server side code has `Json.DirtyCheckEnabled = false;`

@chrhol can you advice on this?

**Comment by k-rus** [comment]
I would like to note that calling auto-created query, which is probably the case here, can be serious performance issue.

**Comment by chrhol** [comment]
What exactly is RetailDemo? I didn't even know we had a repo for that, I thought the retaildemo was the polyjuiceapps procurement, product and images?

> I would like to note that calling auto-created query, which is probably the case here, can be serious performance issue.

There are no autocreated queries in json. What `CheckBoundArray` does is calling a property in the dataobject that the jsonproperty is bound to and matches the results with the existing items.

If the query is incorrect it should be changed in the application, and/or the jsonproperty bound to another dataproperty (or not at all).

This particular query comes from the datamodel, `ScRetailDemo.Customer.Accounts`. If it is not correct it should be changed.

```csharp
...
public IEnumerable<Account> Accounts { get { return Db.SQL<Account>("SELECT a FROM Account a WHERE a.Customer=?", this); } }
...
```

**Comment by dan31** [comment]
@chrhol, RetailDemo is a slightly changed PokerDemo. The change has been done because PokerDemo had nothing to do with Poker :)

**Comment by alemoi** [comment]
That's true, the query is there! I wonder how the code worked before, since we didn't have the performance problems and we didn't change the code since then. In any case thank you for response. Maybe I didn't use this specific type of sub-test previously. RetailDemo is now added to tests: SC_RUN_RETAILDEMO_TEST parameter.

**Comment by k-rus** [comment]
> That's true, the query is there! I wonder how the code worked before, since we didn't have the performance problems and we didn't change the code since then. In any case thank you for response. Maybe I didn't use this specific type of sub-test previously. RetailDemo is now added to tests: SC_RUN_RETAILDEMO_TEST parameter.

Do you confirm that it is expected at data binding that the query without index is called?

**Comment by dan31** [comment]
@alemoi, check @k-rus question (reopened).

**Comment by dan31** [comment]
@alemoi confirms that issue remains. I met similar behaviour sometime ago at Ripipip apps: index is presented but eventually not utilised. After dropping index from Administrator, it started to be utilized. @alemoi, follow up with @k-rus.

**Comment by k-rus** [comment]
> @alemoi confirms that issue remains. I met similar behaviour sometime ago at Ripipip apps: index is presented but eventually not utilised. After dropping index from Administrator, it started to be utilized. @alemoi, follow up with @k-rus.

This is different issue. In this issue data binding was calling a query, which uses no indexes. My question is if it is expected that the query is called. I don't if it is according to the current specification and if the specification needs to be improved. Or how to tackle such performance problems in future.

**Comment by alemoi** [comment]
> Do you confirm that it is expected at data binding that the query without index is called?

The data binding has a Db.SQL query inside "get" statement, that user has created explicitely. Before we simply didn't use that specific query I think.

The other problem (however with other index `"SELECT a FROM Account a WHERE AccountId`) was related to the situation that RetailDemo was ran after PokerDemo (that shares some of the data structures names and correspondingly indexes), without database being deleted. That created a situation that index was not used properly.
