### ISSUE TITLE
Question: Index on property

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2523]
I have the following objects. 

    public class KeyWord
    {
            public string Text;
    }

    public class Site
    {
         public string Domain;
    }
    public class Title
    {
            public KeyWord KeyWord;
            public Site Site;
    }

And then the following query is done: 

var result = Db.SQL<Ttile>("SELECT W FROM Title W WHERE KeyWord.Text=? AND Site=?", word, site).First;

To improve performance I have tried to make an index for this query but without success. 

This Index throws an error: 

Starcounter.Db.SQL("CREATE INDEX TitleIndex ON Title (Keyword.Text, Site)"); 

And this doesn't help 

Starcounter.Db.SQL("CREATE INDEX KeyWordIndex ON KeyWord (Text)");
Starcounter.Db.SQL("CREATE INDEX TitleIndex ON Title (Keyword, Site)");

**Comment by k-rus** [comment]
Thank you for your question!


> This Index throws an error:
> 
> Starcounter.Db.SQL("CREATE INDEX TitleIndex ON Title (Keyword.Text, Site)");

Indexes are allowed only on columns of the table. There is no column `Keyword.Text` in table `Title`. So it 's correct that you get an error.


> And this doesn't help
> 
> Starcounter.Db.SQL("CREATE INDEX KeyWordIndex ON KeyWord (Text)");
> Starcounter.Db.SQL("CREATE INDEX TitleIndex ON Title (Keyword, Site)");

What do you mean that it does not help? Do you mean that you get an error or the performance is not improved?

What is more selective `Keyword` or `Site`? I can guess that the number of keywords per site is limited. If so, it should be better if you define index on `Site` of `Title`:
```c#
Starcounter.Db.SQL("CREAT INDEX TitleSite ON Title (Site)");
```

**Comment by Ripipip** [comment]
Yes, that actually made a huge difference :) Thank you!

**Comment by k-rus** [comment]
Then I close the issue. You might want to remove the first two indexes if there are no queries, which might utilize them.
