### ISSUE TITLE
Index requested not found after update.

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2528]
Updated to Starcounter 3005.3 and while the apps build correctly I can't run the apps due to this error. 

ScErrIndexNotFound: Index requested not found.

https://gist.github.com/mbarinov/235d4776e0c31ca8c069

**Comment by k-rus** [comment]
There were incompatible changes in Starcounter. To be able to keep your data, you need to migrate them as described [here](https://github.com/Starcounter/Starcounter/wiki/Reloading-database-between-Starcounter-versions).

Basically the steps are:

1. Install back the old version of Starcounter
2. Start your application
2. Unload the database
3. Backup the server folder with the database image
4. Install new Starcounter with new server folder (either remove the old one, which you already backed up, or point into an empty or non-existing)
5. Start your application with no data
6. Reload the database dump

The tracking issue is #2495

**Comment by dan31** [comment]
@Ripipip, closing that one?
