### ISSUE TITLE
Confusions with parameters in project Develop-Nightly-Debug

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2534]
When I look to the parameters of the project Develop-Nightly-Debug, I am confused that the configuration parameter is set to `Release`, while I expect to see `Debug`. I also see parameter SC_RUN_DEBUG_BUILD, which sounds to have the same role as Configuration.
Can it be clarified?
What is the role of parameter Configuration for all the project in general? Does it have any meaning?

**Comment by alemoi** [comment]
For Debug build the idea was that it runs inside Release project, which was abandoned. For debug build the actual configuration is overriden in TeamCityDebug.bat. I just didn't want to maintain a lot of different project properties. The same for the parameter that you mentioned. I will remove this parameter and set Configuration to Debug. Thanks for noticing.

**Comment by alemoi** [comment]
I have removed the parameter and changed Configuration to Debug.
