### ISSUE TITLE
Client static files should be available in Starcounter edition installer

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2538]
Client static files in `/sys/` path should be available in Starcounter edition installer (currently only in Polyjuice edition).

There are no additional files for the Polyjuice edition installer at this moment. Starcounter and Polyjuice editions should come with the same set of client static files.

**Comment by dan31** [comment]
It's important to simplify demos. Also it is logical, since we allow to build web-apps with Starcounter.

**Comment by alemoi** [comment]
Should already be working. Please verify.

**Comment by warpech** [comment]
I confirm, it works great

**Comment by dan31** [comment]
I noticed that ```c:\Program Files\Starcounter\2.0.3037.3\EditionLibraries\``` are now included in Starcounter edition. I suggest that's incorrect, only static client files should have appeared at Starcounter edition. Also check #2564.

**Comment by k-rus** [comment]
> I noticed that c:\Program Files\Starcounter\2.0.3037.3\EditionLibraries\ are now included in Starcounter edition. I suggest that's incorrect, only static client files should have appeared at Starcounter edition. Also check #2564.

I believe this issue is incorrect place for reporting another issue. I suggest to create a separate issue.

**Comment by dan31** [comment]
@k-rus, we figured out that SocietyObjects are there on purpose for developers' usability. The plan is to rename SO into something else, so this won't be an issue with custom versions of SO.

**Comment by k-rus** [comment]
> @k-rus, we figured out that SocietyObjects are there on purpose for developers' usability. The plan is to rename SO into something else, so this won't be an issue with custom versions of SO.

This purpose made problems to the users as in #2564, since the change was introduced without notifying users. 
What is the difference now between Starcounter and Polyjuice editions? Can it be clarified to our customers too?
