### ISSUE TITLE
Unfriendly error message when session expires

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2541]
In any of the following cases:
1) user loses Wi-Fi range
2) user puts his laptop to sleep/hibernation
3) server restarted
4) server stopped

Client gets an ugly error when he tries to perform an action with Puppet: 

![screen shot 2015-02-04 at 14 56 45-](https://cloud.githubusercontent.com/assets/566463/6051226/850f923e-acc6-11e4-92c7-cc2fe5d9ecd8.png)

Any idea why this happens? How long is the session lifetime on server?

This appears with WebSocket turned **OFF**. With WebSocket turned on, the disconnection also results in a client error, but that's a different issue: https://github.com/PuppetJs/PuppetJs/issues/37

**Comment by alemoi** [comment]
> Any idea why this happens? 
Maybe the client keeps the old session and server creates a new one causing client to treat sitation as errornous?

> How long is the session lifetime on server?
Defined in `scnetworkgateway.xml` in your server directory. The default value is 20 minutes.

**Comment by warpech** [comment]
I think 20 minutes is way too short. Your desktop programs (Firefox, Visual Studio, etc) remember their state for weeks.

I think we should do not one but 3 things:

1. change 20 minutes to 7 days
2. if there is no session, server should return `410 Gone` or `404 Not Found` instead of creating a new session
3. if server returns the error mentioned in 2., the client should display a message "Session expired. Press OK to reload the page"

**Comment by alemoi** [comment]
Since we made a lot of work regarding the session timeout and heartbeat (https://github.com/Starcounter/Starcounter/issues/3084) - I guess I can close this issue as well.
