### ISSUE TITLE
input.Cancel() doesnt work anymore

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2548]
Lets say I have a Json handler for a boolean:
```
 void Handle(Input.Remove input)
        {
            input.Cancel();
        }
```
Then I expect input.Cancel() to prevent any changes to the Remove property but thats not the current case, remove is set :(.

**Comment by chrhol** [comment]
When you call input.Cancel() it will not set the value sent from the client (in input.Value) and if the input value is different from existing value the old value will be sent back (or rather the property will be marked as dirty).  However it does not block any other code on the server to set the property.

Do you have a sample of the code that misbehaves? I can see nothing directly that can cause this.

**Comment by malx122** [comment]
Everywhere.... (Not sure if it is set or not but the handlers does not get
called a second time with the same change)
Den 9 feb 2015 11:35 skrev "Christian" <notifications@github.com>:

**Comment by chrhol** [comment]
You are correct, although with a little change in title. This have never worked. The server have never sent back the original value when an input is cancelled. I'm really suprised, I was sure this was working.

The fix is quite easy, I will just add an unittest as well before pushing to develop.

**Comment by chrhol** [comment]
Fix was pushed in the last referenced commit. Closing this issue.
