### ISSUE TITLE
Allow arbitary URLs in Polyjuice.Map

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2553]
Currently `Polyjuice.Map` requires the mapped URL to match the scheme defined in `PopulateSoTree`.

As a device to enable content mapping for a launcher, it should be possible to specify arbitrary url maps, like: `Polyjuice.Map("/launcher/region/menu", "/menu")`

**Comment by alemoi** [comment]
This feature has been added as `Polyjuice.Map`.
