### ISSUE TITLE
X.GET should allow to provide own response

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2555]
Today @Starcounter-Jack, @andwah, @tomalec and I were discussing a simpler approach to create Launcher "workspaces" concept based entirely on PolyPages concept.

Launcher needs to route the current request to other apps using `X.GET`. The response from other apps can be merged as PolyPages, given that Launcher will add its own response into the tree. 

There are 3 possible solutions that we see but only the last one is robust:
1) Naive solution: hardcode all existing URL handlers in Launcher
2) Unperformant solution: create a wildcard URL handler in Launcher
3) **Robust solution:** Launcher should be able to provide its own empty response to any `X.GET` request by providing a delegate to `X.GET`, such as:

```c#
X.GET("/SuperCRM/person/123", () => {
 return new Page();
})
```

The above code can be explained as: 

> request the URL `/SuperCRM/person/123` and if I don't have my own handler for it, use an empty Page as the response

**Comment by alemoi** [comment]
Implemented, can be seen, for example, in Launcher application.
