### ISSUE TITLE
How to make master -> details concept in SC?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2560]
I have three html templates:

1. master.html -> common for all urls
2. customers.html -> /customers
3. orders.html -> /orders

How to dynamically load the html?

This manual does not work any more:
https://github.com/Starcounter/Starcounter/wiki/Multiple-pages-in-single-page-applications-(SPAs)

1. It has a typo, missing ")" in the end of Json attribute.
[ Json("{ Mails:[{Title:'Hi Alexey!'}], Focused:{}" ]
2. There is no more Json attribute in Starcounter namespace.
3. There is no more Json<T> class in Starcounter, only Json and IBound<T>.
4. There is no more View property nor in Starcounter.Json, nor in Starcounter.Page.

**Comment by warpech** [comment]
Sorry, I will work on updating the article.

**Comment by warpech** [comment]
I pushed a new commit (https://github.com/Starcounter/InvoiceDemo/commit/625fb766e18fed81ab48d1963a18663c92a9180d) that presents how to implement HTML "partials" for view-models.

Now, you can create separate Customers page (`Customers.json` with `Customers.json.cs`) and assign in to `Master.FocusedPage`.

I will leave this issue opened until wikis are updated

**Comment by miyconst** [comment]
@warpech, thanks for the demo.

I have followed your example and implemented Master -> Details views in my sample project. Could you please take a look?

The source code of my project is available here:
http://www.miyconst.com/Blog/Download/1052/33/DemoShop.zip

**Comment by warpech** [comment]
1 . We set up `Content` as the working directory in Visual Studio, so that it will become the domain root. Thanks to that, you get better control over which files are exposed in HTTP. Unfortunately, InvoiceDemo does not show it, but we got it covered in wiki: https://github.com/Starcounter/Starcounter/wiki/Using-the-internal-web-server (and also duplicated on page https://github.com/Starcounter/Starcounter/wiki/Serving-static-content)

2 . You don't have to create a `ID` column in the database. You can use `GetObjectID()` on any database object (e.g. `customer.GetObjectID()`) to retrieve the unique id of the object.

3 . The relation in database does not have to be based on foreign keys but on direct object references. This is what makes Starcounter fast. Remove the `ID` column in `Order` and then replace:

```c#
this.Orders = SQL("SELECT o FROM \"Order\" o WHERE o.Customer.ID = ?", ((Model.Customer)this.CustomerView.Data).ID);
``` 

with 

```c#
this.Orders = SQL("SELECT o FROM \"Order\" o WHERE o.Customer= ?", (Model.Customer)this.CustomerView.Data);
```

4 . The above makes `GetByPk` redundant. Alternatively it can be changed to: 

```c#
        public Customer GetByPk(string ObjectID)
        {
            return Db.SQL<Customer>("SELECT c FROM Customer c WHERE ObjectID = ?", ObjectID).First;
        }
```

5 . Replacing:

```c#
return Db.SQL<decimal>("SELECT SUM(oi.Quantity * oi.Price) FROM OrderItem oi WHERE oi.\"Order\" = ?", this).First;
```

with:

```c#
return Db.SQL<decimal>("SELECT SUM(oi.Total) FROM OrderItem oi WHERE oi.\"Order\" = ?", this).First;
```

Is better because of raw performance and mainainability (`ot.Total` is the single source of truth about how the OrderItem total is calculated).

**Comment by miyconst** [comment]
All the points except the first one are fixed. I have read the wiki page, but do not understand what should I do.

Have some questions though:

1. Can I assign a customer to an order if I have customer's ObjectID only?
For example in Entity Framework Order would have two properties:
Order.Customer and Order.CustomerID.

2. How to determine whether object is new or saved? GetObjectID method always return some value, even for new objects.

3. I have added ID property to every Database class:
```csharp
public string ID
{
    get
    {
        return this.GetObjectID();
    }
}
```
Is this okay?

**Comment by warpech** [comment]
> All the points except the first one are fixed. I have read the wiki page, but do not understand what should I do.

I added clarification to https://github.com/Starcounter/Starcounter/wiki/Using-the-internal-web-server (point 1)

1. I would propose to do a `SELECT c FROM Customer c WHERE ObjectID = ?` for this ID, and then you can assign the Customer to an Order using the reference to the Customer object

2. If it only matters for the application logic, then I think it is the easiest to create a property in the view-model that keeps track of such information. If it matters for the data model, then you should create a property in the database class (`Published` or `PublishedDate`, etc)

3. Looks good to me. I guess it may be useful in auto-binding ObjectID to a view-model

**Comment by k-rus** [comment]
> 2 . You don't have to create a ID column in the database. You can use GetObjectID() on any database object (e.g. customer.GetObjectID()) to retrieve the unique id of the object.

Note that `GetObjectID` returns web friendly identifier. If it is intended to be used only within code host without transferring over the net, then it might be a good idea to use `GetObjectNo`, which return 64-bit numeric value of the object id without any conversion. See [this wiki page](https://github.com/Starcounter/Starcounter/wiki/Object-identity-and-object-references) for more info.



> I would propose to do a SELECT c FROM Customer c WHERE ObjectID = ? for this ID, and then you can assign the Customer to an Order using the reference to the Customer object

There is C# API method to avoid expensive SQL query: `Starcoutner.DbHelper.FromID(ulong objno)`. Thus the query can be replaced with:
```c#
Customer c = (Customer)Starcounter.DbHelper.FromID(myObjectNo);
```
If it is necessary to go from `ObjectID`, which is a string, then it should be converted from `String` to `UInt64` by `Starcounter.DbHelper.Base64DecodeObjectID`.

**Comment by warpech** [comment]
Great! Could `DbHelper` get described in the wiki? It is not mentioned there at all

**Comment by k-rus** [comment]
> Great! Could DbHelper get described in the wiki? It is not mentioned there at all

I don't know what is the plan with this help class. If I don't mistake there was some plans to do some refactoring about help methods. May be @per-samuelsson did something already in *next*. In general I agree it should be described.

**Comment by miyconst** [comment]
@warpech,

1. Extracting object by its id In Entity Framework requires a call to the database, this is expensive and that is why ParentTableID properties are made. I may assume that such calls are not expensive in SC and I should extract full object whenever I have to set a relation.

2. Are there any db events, such as ObjectCreated, ObjectSaved, ObjectUpdated, so I can automatically fill CreateDate, ChangeDate fields?

As @k-rus said I replaced my GetByPk method to:

```csharp
public Order GetByPk(string ObjectID)
{
    return DbHelper.FromID(DbHelper.Base64DecodeObjectID(ObjectID)) as Order;
}
```

**Comment by k-rus** [comment]
> Extracting object by its id In Entity Framework requires a call to the database, this is expensive and that is why ParentTableID properties are made. I may assume that such calls are not expensive in SC and I should extract full object whenever I have to set a relation.

Starcounter is based on different paradigm than any ORM. It is based on VMDBMS that the application code is run within the database process, thus accessing data is very cheap if SQL is not used. It is not recommended to copy data from database properties into non-database properties, since transaction properties cannot be guaranteed. Let me know if you have more questions or more clarification is needed.

**Comment by Starcounter-Jack** [comment]
1. Getting full object by its id is free. Nothing is ever copied between the database and the POCO. The object is aldready in your RAM, so any "transfer" would be uneccessary.

2. If not, I think we should add this capability.

**Comment by miyconst** [comment]
@k-rus, @Starcounter-Jack, thank you for the explanation. It is clear now.
