### ISSUE TITLE
Strange exception when passing View.Data.Property as out parameter to a function

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2562]
I tried to validate a date field inside a json view model:

```csharp
if (!DateTime.TryParse(this.Date, out this.Data.Date)) //This leads to a strange exception.
```

And got this exception:

> At least one error has been detected during weaving of the application code. Process exit code: 4062 (ScErrWeavingError (SCERR2030))

What is wrong in the code?

**Comment by miyconst** [comment]
``` csharp
[Database]
    public class Order
    {
        public string ID
        {
            get
            {
                return this.GetObjectID();
            }
        }

        public Customer Customer;
        public DateTime Date;
        public string Description;
        public string Address;

        public string DateString
        {
            get
            {
                return this.Date.ToShortDateString() + " " + this.Date.ToShortTimeString();
            }
        }

        public QueryResultRows<OrderItem> Items
        {
            get
            {
                return Db.SQL<OrderItem>("SELECT oi FROM OrderItem oi WHERE oi.\"Order\" = ?", this);
            }
        }

        public decimal Total
        {
            get
            {
                return Db.SQL<decimal>("SELECT SUM(oi.Total) FROM OrderItem oi WHERE oi.\"Order\" = ?", this).First;
            }
        }
    }
```

**Comment by chrhol** [comment]
Quite confusing errormessage yes. The actual error is hidden in earlier messages in the starcounter log.

First, the part that does not work in your code:

> ScErrFieldRefMethod (SCERR4062): Starcounter can't handle the reference parameters in a certain method.

Starcounter cannot properly handle using `this.Data.Date` directly as an out parameter. The solution is to use a local variable and then assign order.Date

```c#
DateTime localDate;
if (!DateTime.TryParse(this.Date, out localDate))
    this.Data.Date = localDate;
```

Second, the errorreporting. It looks like there is some other exception being thrown that makes the actual exception not showing.

> System.FormatException: ScErrWrongErrorMessageFormat (SCERR1033): Parsing an error message string failed due to an incorrect message format. Message: SCPFV21 - ScErrFieldRefMethod (SCERR4062): Starcounter can't handle the reference parameters in a certain method. 

In any way either this other exception needs to be fixed or the errorreporting improved.

**Comment by per-samuelsson** [comment]
> Starcounter cannot properly handle using this.Data.Date directly as an out parameter. The solution is to use a local variable and then assign order.Date

Yes, this is the real, underlying error. It's a limitation of the coding experience thats been there since years back, that fields that are database fields can not be used directly as ```ref``` or ```out``` parameters, since the switch going from fields to property accessors is not designed to handle it. So the described workaround is the way to go right now.

> In any way either this other exception needs to be fixed or the errorreporting improved.

Agree. I'm assigning it to me to do it eventually.

**Comment by per-samuelsson** [comment]
I have now redesigned the error propagation a bit, assuring (hopefully) a more informative user experience.

I have also updated the relevant help wiki page, and included source code that examplifies the limiation and shows a suggested resolution:

https://github.com/Starcounter/Starcounter/wiki/SCERR4062

All commits are pushed and merged within https://github.com/Starcounter/Starcounter/commit/172a1feb7048623aa7039472813aa620cc6d14ee.

@miyconst, if you find the time, please test this eventually and let us know if it works for you. And don't hesitate to let us know what you think! The simplest way to test it is to copy the example code from the [referenced wiki page](https://github.com/Starcounter/Starcounter/wiki/SCERR4062) and paste it into an empty ```.cs``` file, e.g. ```app.cs```, and run it in a command prompt using ```star app.cs```.

I'm closing this until further notice.

**Comment by miyconst** [comment]
The approach which is described in the wiki worked before and still works.

**Comment by per-samuelsson** [comment]
> The approach which is described in the wiki worked before and still works.

Yes, it is the recommended way too. What I fixed was merely a better user experience in the form of a more descriptive error message, both in Visual Studio and in the CLI, and updated the wiki. Thanks for all the feedback.
