### ISSUE TITLE
Reviewing [Inherits] attribute

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2563]
Just as we have done with the more complex `[Type]` attribute, it might be good to have a discussion thread for the implementation of the `[Inherits]` attribute.

According to my understanding, `[Inherits]` is pretty basic. It basically allows a developer to expose the explicit column with the same name.

It defines a constraint that the current type must be _assignable from_ the referenced one. Hence, a declaration such as

``` C#
class CarModel {}
class SUV : CarModel {
  [Inherits] CarModel Parent;
}
```

will pass, while the following will fail:

``` C#
class Foo {}
class CarModel {}
class SUV : CarModel {
  [Inherits] Foo Parent;
}
```

@k-rus? @Starcounter-Jack?

**Comment by k-rus** [comment]
Since the type system does not support multiple inheritance, it is OK or even correct to fail extension from two different classes at the same time. Thus I agree with @per-samuelsson on the above examples.

There is another example, which is more complex:
```c#
class ProductModel { };
class CarModel : ProductModel { };
class SUV : ProductModel { 
  [Inerits] CarModel Parent;
};
```
and
```c#
class ProductModel { };
class CarModel : ProductModel { };
class SUV : CarModel { 
  [Inerits] ProductModel Parent;
};
```

I believe that the first one can be accepted (or can be failed for simplicity), but the second one will definitely fail.

**Comment by per-samuelsson** [comment]
> I believe that the first one can be accepted (or can be failed for simplicity), but the second one will definitely fail.

Now I'm probably just tired, but I would say the opposite. :smile:

**Comment by per-samuelsson** [comment]
> Now I'm probably just tired, but I would say the opposite.

I was thinking we could use ```Type.IsAssignableFrom(Type t)``` to solve the equation, and define legacy as

```C#
var legal = typeof(referencedType).IsAssignableFrom(current) && referencedType != current;
```

**Comment by k-rus** [comment]
> I believe that the first one can be accepted (or can be failed for simplicity), but the second one will definitely fail.
> Now I'm probably just tired, but I would say the opposite.

I agree. The best way to understand is to define properties in each inherited type and then see if the properties will be accessible or not. In the first example `CarModel` specific properties will not be accessible in C#, since `ProductModel` does not include them.

**Comment by per-samuelsson** [comment]
No longer apply.
