### ISSUE TITLE
Disable SocietyObjects?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2564]
Hi!

My application stopped working with version: 2.0.3026.3
It seems like SocietyObjects is now embedded? I have class name clashes. My class HSM.Concepts.ComputerSystem collides with Concepts.Ring3.ComputerSystem.

If I make a query agains Starcounter.Metadata.Tables I retrieve both my table and "your" table for ComputerSystems. How ever making a query agains my ComputerSystem fails:
Failed to process query: select cs.Name from "HSM"."Concepts"."ComputerSystem" cs: Unknown class HSM.Concepts.ComputerSystem. Unknown property Name of class HSM.Concepts.ComputerSystem.

Can I disable SocietyObjects? If not why doesnt't queries on namespace+class work?

**Comment by careri** [comment]
Yes, I guessed that they shouldn't have been included. Renaming my class solved the problem. But still why doesn't query on fullname work?

**Comment by k-rus** [comment]
Thank you for reporting the issue. The query should works, since there is no ambiguity. I will need to reproduce this case and I might need a help.

**Comment by dan31** [comment]
@alemoi, is it okay if the developer simply deletes SO dll's from the installation folder so that those DLL's don't interfere with custom SO?

**Comment by alemoi** [comment]
> @alemoi, is it okay if the developer simply deletes SO dll's from the installation folder so that those DLL's don't interfere with custom SO?

Yes, that works. In this case I would also delete them from `Public Assemblies` folder.

**Comment by per-samuelsson** [comment]
> Yes, that works. In this case I would also delete them from Public Assemblies folder.

I think it actually is sufficient to rename the EditionLibraries folder in the installation path. At least thats how this was implemented initially - the weaver / binder inroduce certain inclusions of everything in this folder. If it does not exist, things are back to "normal".

Be aware though that any update of Starcounter version will probably require the same producedure again.

**Comment by dan31** [comment]
And, to clarify. SO will be renamed in future versions of SC.

**Comment by k-rus** [comment]
> And, to clarify. SO will be renamed in future versions of SC.

The classes are in different namespaces, thus it is already renamed.

The problem happened due to a bug and I think I have an idea about. I will try to reproduce on a simple example.

**Comment by k-rus** [comment]
> The problem happened due to a bug and I think I have an idea about. I will try to reproduce on a simple example.

No, I have no idea why it does not work.

@careri:
We need help to reproduce the issue.

**Comment by dan31** [comment]
Since the issue title stands for "Disable SO", the issue is @careri-specific and the resolution is to remove SO dll's, if you have custom SO, following @alemoi advice. The #2566 is about the querying issue. That's why we close that one.
