### ISSUE TITLE
ScErrInputQueueFull

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2565]
I recieved a quite large JSON message over HTTP. I than used anonymous callbacks to transfer the values into a DbSession:
````
    var dbSession = new DbSession();
    dbSession.RunAsync(() => WebServiceManager.LogRequest(Service, req, args));
    var response = Service.OnRequest(req, args);
    dbSession.RunAsync(() => WebServiceManager.LogResponse(Service, response, req)); <-- Exception here!
````

**Comment by dan31** [comment]
The current RunAsync capacity is limited by 256. Can you check the moment of exception, isn't it 256-th?

**Comment by careri** [comment]
What value is it that I'm supposed to check?

**Comment by dan31** [comment]
> What value is it that I'm supposed to check?

I assume that you have ```RunAsync``` called multiple times. You can count how many times it is exposed (ex., create a counter variable in DB), and my expectation is that the exception will occur at the counter equals to 256.

> The solution might be to split the batches in to smaller batches.

I think that queue reduction let ```RunAsync``` be exposed without reaching the 256 limit.

**Comment by careri** [comment]
Nope, no recursive calls. Only the 2 calls in the code above. But the request held a large JSON, don't know if that matters?

Any way, I realized that the DbSession wasn't needed any longer, I had some old code that interacted with the database. So I just went ahead and removed the DbSession here. 

So I wan't be getting the exception any longer. But you should try to reproduce it, sending a request with a large JSON.

**Comment by dan31** [comment]
@careri, it definitely matters. ```ScErrInputQueueFull``` happens when the queue for async tasks is full, upper limit is 256 tasks. One can invoke that having a huge task in ```RunAsync```argument, and ```RunAsync``` call is wrapped into a handler, say, ```Foo```. If you call more that 256 ```Foo```-s instantly, the huge tasks won't finish, so the queue will be full and exception will be thrown. That's the only known way to get that exception now. @careri, do you have the same case with the code entailing ```RunAsync``` call?

**Comment by careri** [comment]
Is queue shared between DbSession instances? The code above was the code executed in a Http-handler.
Might have been a lot of incomming requests, and if the queue is shared that would yield that result. I didn't make any more calls to RunAsync in my code, but I did call properties on the Starcounter.Response and Starcounter.Request. Maybe the create nested RunAsync calls in your code?

**Comment by alemoi** [comment]
Tasks are scheduled to a specific scheduler. The queue is per scheduler. I guess your are using DbSession.RunAsync without specifying the scheduler so everything goes to scheduler 0 by default. Thank you.

**Comment by careri** [comment]
You're right, I didn't specify the scheduler

**Comment by careri** [comment]
How many schedulers are there?

**Comment by alemoi** [comment]
Up to number of logical processors in the system, unless its overwritten with `SchedulerCount` in .db.config

**Comment by careri** [comment]
Aha, thanks

**Comment by careri** [comment]
Can one access the SchedulerCount from a running instance of scdb?

**Comment by careri** [comment]
Found it:
Db.Environment.SchedulerCount

**Comment by alemoi** [comment]
Exactly! Please ask if any other questions.
