### ISSUE TITLE
Make a query on a fully specified name

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#2566]
Application stopped working with version: 2.0.3026.3
It seems like SocietyObjects is now embedded? I have class name clashes. My class HSM.Concepts.ComputerSystem collides with Concepts.Ring3.ComputerSystem.
If I make a query against Starcounter.Metadata.Tables I retrieve both my table and "your" table for ComputerSystems. However making a query against my ComputerSystem fails:
Failed to process query: select cs.Name from "HSM"."Concepts"."ComputerSystem" cs: Unknown class HSM.Concepts.ComputerSystem. Unknown property Name of class HSM.Concepts.ComputerSystem.

**Comment by dan31** [comment]
@parherman, please try to reproduce on Friday. You need an installed Starcounter and a Starcounter DLL with "HSM.Concepts.ComputerSystem" loaded into an app. @k-rus, correct me if I'm wrong.

**Comment by dan31** [comment]
@k-rus, I think I miss a detail here. Can you outline steps to reproduce?

**Comment by parherman** [comment]
FYI I do not have access to the SocietyObjects repo, if that is needed for this

**Comment by k-rus** [comment]
This is duplicate to #2564.

**Comment by k-rus** [comment]
To reproduce the issue #2564 it is necessary:

1. Install Starcounter locally from local Debug build for the repository state compatible with the application.
2. Copy SO binaries into Edition Library folder.
3. Obtain the database (the server folder) and the application binary compatible with the local Starcounter installation.
4. Provide a way to start application, attach debugger in Level1 and break at the point when the failed query is called.

**Comment by k-rus** [comment]
BUMP

**Comment by parherman** [comment]
@k-rus, @dan31 Do we have access to the to the database and the application?

**Comment by k-rus** [comment]
> @k-rus, @dan31 Do we have access to the to the database and the application?

This is goal of this issue to get the database and reproduce the issue.

**Comment by dan31** [comment]
@careri, can you help us reproduce the issue?
We do the following. Having the code:
```
using System;
using Starcounter;

namespace HSM {
    namespace Concepts {
        [Database]
        public class ComputerSystem {
            public string Name;
        }
    }
}

namespace StarcounterApplication1 {
    public class SomeSystem : Concepts.Ring3.ComputerSystem { }
    class Program {
        static void Main() {
            Db.Transact(() => {
                var a = new SomeSystem();
            });
        }
    }
}
```
We get 0 rows for ```select cs.Name from HSM.Concepts.ComputerSystem cs``` and 1 row for ```select cs.Name from Concepts.Ring3.ComputerSystem cs```.
How does your case differ?

**Comment by careri** [comment]
Sorry, didn't notice your question. I'll get back to you if I can reproduce. Have to reset my git-repo to before I renamed. I'll see if I have time to do that today.

**Comment by careri** [comment]
I think it's related to renaming classes. In this case I hade image files that only knew of my class called Computer. Then when upgradring I got the SO-assemblies and the renamte/new class logic messed up some indexes?

I had a similar error now when I renamed a class and removed a property at the same name

**Comment by careri** [comment]
Never mind that last input, I forgot to update the SQL query with the new name. Sorry

**Comment by dan31** [comment]
To conclude, in current version one has to do schema changing and data morphing one simple step at a time. A combination of them might mess things, so that you have to roll back those actions back (doing one simple backwards step at a time) to restore access to your previously available data. The algebra of schema changing will be improved in future versions of SC.
