### ISSUE TITLE
What client side libraries are used in SC applications?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2585]
I am trying to make some client side logic in SC.

What js libraries do you use for client side effects, such as date picker, time picker, range control.

Do you validate data on client side before sending it to the server?

**Comment by tomalec** [comment]
For data communication on client-side we usually use [PuppetJS](https://github.com/PuppetJs/PuppetJs) (packed into [`<puppet-client>`](https://github.com/PuppetJs/Puppet-client) Web Component), you can find some examples at https://github.com/Polyjuice

PuppetJs in general is framework agnostic, so we give complete freedom for front-end devs to use whatever they want. Bootstrap, jQuery, Angular, everything should work without a problem. However, we are big fans of Web Components :)

So I believe, easiest way to go is to grab something from http://customelements.io/
