### ISSUE TITLE
What is the complete list of available components under /sys/?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2588]
What is the complete list of available components under /sys/?

**Comment by tomalec** [comment]
In Starcounter source it's in [/src/BuildSystem/Polyjuice/StaticFiles/sys](https://github.com/Starcounter/Starcounter/tree/develop/src/BuildSystem/Polyjuice/StaticFiles/sys), bower config at [/src/BuildSystem/Polyjuice/bower.json](https://github.com/Starcounter/Starcounter/blob/develop/src/BuildSystem/Polyjuice/bower.json)

In your installation folder it's at `Polyjuice/` folder (for example `C:\Program Files\Starcounter\2.0.3045.3\Polyjuice`)
