### ISSUE TITLE
NullReferenceException is suppressed by something

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2592]
NullReferenceException is suppressed by something in Handle method.

```csharp
[CustomersView_json.Customers]
partial class CustomersViewCustomer : Json
{
	void Handle(Input.Delete Action)
	{
		CustomerProvider provider = new CustomerProvider();

		this.Transaction.Scope(() =>
		{
			Customer customer = this.Data as Customer;
			provider.DeleteCustomer(customer);
		});


		this.Transaction.Commit();
		this.ParentView.RefreshCustomers(); //Here ParentView is NULL, but no exception fired.
	}

	public CustomersView ParentView
	{
		get
		{
			return this.Parent as CustomersView;
		}
	}
}
```
Actual Parent value is an instance of CustomersViewCustomer class, and its parent is CustomersView.
This is why ParentView is NULL, but when I run the code exception is not firing, same happens in debug mode, VS just stops processing following lines of code and exits the method as if I would wrote return in there.

**Comment by chrhol** [comment]
I noticed similar behaviour when trying to find another problem reported by @alemoi in #2618 and what I found was that the error is actually returned from the server (and logged) but not shown to the user in the browser. 

If you are using websocket, I don't see any way to find out about the error in the browser and if not you can only see it in the network-tab. It's not directly shown to the user.

**Comment by miyconst** [comment]
When debugging, VS usually stops on the line of code which fires an exception, but not in this case. This has nothing to do with client side.

It acts like the exception was caught by some internal `try catch` and not thrown again.

**Comment by k-rus** [comment]
Just a note that Query processor fires exceptions and catches them, but they are not general exceptions. I guess it is not related to the above behaviour, but I wanted to note for a case.

**Comment by miyconst** [comment]
>Query processor fires exceptions and catches them

@k-rus, actually this is also very annoying. I would like VS to hit the line of code which tries to execute a wrong sql query, instead of silently return null or die.

**Comment by k-rus** [comment]
> Query processor fires exceptions and catches them
> @k-rus, actually this is also very annoying. I would like VS to hit the line of code which tries to execute a wrong sql query, instead of silently return null or die.

This is current temporal architecture. It is not possible to know if the query is wrong at the point, when the legacy code throws the exception. New Starcounter version will not have this annoying feature.

**Comment by miyconst** [comment]
Closing this issue as answered and outdated.
