### ISSUE TITLE
Calling something like Init() when loading libraries from EditionLibraries directory

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2593]
Can we add functionality to call an initialization function when loading those libraries (it should search e.g. for Init() function and if its presented - call it)? This is quite crucial functionality to make current Launcher like any other app and some other problems it solves. I will initially assign to @per-samuelsson.

**Comment by per-samuelsson** [comment]
@alemoi 

Should we close this one do you think, as there is no immediate need for it right now, correct?

**Comment by alemoi** [comment]
Yes,  I am closing it.
