### ISSUE TITLE
Visual Studio extension screen is corrupt in installer

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2595]
The Visual Studio extension step in Starcounter installer is corrupt in version 2.0.3052.3.

The checkbox and the name for Visual Studio 2012 does not render. The extension **is** actually installed.

Compare the following screenshots:

2.0.3052.3:
![installer-52](https://cloud.githubusercontent.com/assets/566463/6439583/5635e608-c0d4-11e4-8744-07b436993fdc.png)

2.0.3045.3:
![installer-45](https://cloud.githubusercontent.com/assets/566463/6439355/43b23146-c0d2-11e4-808c-67e46e9ca4c4.png)

**Comment by k-rus** [comment]
I confirm the same problem in the installer. It is still there.

**Comment by alemoi** [comment]
I just experienced this: visually the extension checkbox and area is inactive, but extension is installed anyways. So its some rendering problem I guess.

**Comment by andwah** [comment]
I will fix this tomorrow. thanks for all reports

**Comment by parherman** [comment]
I believe this is solved in commit 7add398693a01ad7176325a02560ac92d6188ddc
![installer](https://cloud.githubusercontent.com/assets/231535/6797280/3f8e0894-d200-11e4-83c5-5233bc93bc4b.png)

**Comment by warpech** [comment]
I confirm it is fixed now
