### ISSUE TITLE
Using Ports in InvoiceDemo

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2598]
Hi!

I'm having incosistent behaviour when using ports in the handlers for the InvoiceDemo. When running on my computer it works. But when running on another machine I end up calling the wrong handler.

I added port 18080 in the handlers for the invoice demo, but I'm not sure I'm doing it right:
````
Handle.GET(18080, "/master", () => {
// ...
});
Handle.GET(18080, "/", () => {
            Master master = Master.GET("/master"); <-- `How to provide the port?
````
I've tried adding the Request instance to the Handler and used requestInstance.Host.
How can I resolve the schema used for the request? E.g. if it's HTTP or HTTPS?

**Comment by alemoi** [comment]
Thank you for reporting. This one is on me. I have to extend the existing API to support that. For now, you can have a new static Node instance, that has your port number18080 and use that instance for GETs, POSTs, etc.

**Comment by careri** [comment]
Could you please provide an Example so I get things right without to much trial and error.
Thanks

**Comment by alemoi** [comment]
Sure! To create a Node instance with a port number: 
```c#
Node localNode2 = new Node("127.0.0.1", 8080);
Node localNode3 = new Node("buildserver", 8080);
```
and the use the instance for GETs, POSTs, etc.

**Comment by alemoi** [comment]
Thank you for patience! I have added a new API for X.GET specifically (later will add for other methods). Here is the usage example:
```c#
Handle.GET(123, "/test123", () => {
    return "test123";
});

Handle.GET("/test8080", () => {
    return "test8080";
});

String s = null;
s = X.GET<String>("/test8080");
Assert.IsTrue(s == "test8080");

s = X.GET<String>(123, "/test123");
Assert.IsTrue(s == "test123");
```

**Comment by careri** [comment]
Seems to be working

**Comment by alemoi** [comment]
Thanks for the response. Closing the issue so far.
