### ISSUE TITLE
Public Web Folders

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2602]
I have two applications running on different ports. The table of Public Web Folders looks really wierd. 
The app running on port 38080 can't find it's files
Do you autoadd subfolders?

This folder is added through code on port 38080 but it's also added on 18080 why is that?
d:\source\Scdb2Apps\HeadsAdmin\BootApp\bin\Debug\Client

![capture](https://cloud.githubusercontent.com/assets/4263597/6484324/3db25fc8-c27b-11e4-9e78-596401eddcd5.PNG)

**Comment by careri** [comment]
Another strange thing with running multiple apps on different ports is that the seem to share the Session.Current instance?

The app on port 18080 retrieves the Session.Current from the app on 38080, I know this because Session.Current.Data holds an instance that is unknown to the app on 18080.

**Comment by alemoi** [comment]
Thanks for reporting! Regarding the first problem - I will take a look tomorrow. Regarding the second issue with session we will have ro discuss and get back to you.

**Comment by alemoi** [comment]
I looked briefly at the code and made so that duplicate (different case sensitivity) directories on same port are not added.
