### ISSUE TITLE
Restart of an app stops other running apps

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2608]
I have two VisualStudio instances.

Launcher solution in the first instance. It started without debugging (Ctrl + F5).
People solution in another instance.

When I start People solution for the first time, everything works as expected.
But when I restart People solution with (F5) or without (Ctrl + F5) debugging then Launcher solution gets stopped and I have to launch it again.

**Comment by warpech** [comment]
This may be similar to case which I had. One Visual Studio solution with multiple projects. Starting a project stops all Starcounter applications in that case.

In case of a single Visual Studio with a single solution + single project, works as expected (stopping/starting a project does not stop other apps running in Starcounter).

**Comment by per-samuelsson** [comment]
@miyconst 

Thanks for reporting this. I'm currently trying to understand the case here, to see if it is "by design" or a flaw we can improve on.

Assigning this to me right now.

**Comment by per-samuelsson** [comment]
> This may be similar to case which I had. One Visual Studio solution with multiple projects. Starting a project stops all Starcounter applications in that case.

They don't relate 1-1. Your case was different, and fixed.

**Comment by per-samuelsson** [comment]
I have found the problem now, and I have an idea how to solve it.

**Comment by alemoi** [comment]
:+1:

**Comment by per-samuelsson** [comment]
> I have found the problem now, and I have an idea how to solve it.

I think I will be able to push this today. I can't see any real problems with the new design.

**Comment by per-samuelsson** [comment]
I think I now have solved this. Its merged and pushed to develop in https://github.com/Starcounter/Starcounter/commit/45002fc1d814d9f33115e16f798de691cd6b3550.

Let me know if there is something that does not work still, @miyconst.

**Comment by miyconst** [comment]
@per-samuelsson, it looks like the issue is solved.
Thank you.
