### ISSUE TITLE
Could not run a Starcounter app under Polyjuice edition

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2610]
Starcounter applications fail to start under Polyjuice edition:

>Error registering handler: POST /init-demo-data. Polyjuice applications can only register handlers starting with application name prefix, for example, /myapp/foo

I could force it start by modifying url handlers, but standalone application should work without it, should not it?

**Comment by alemoi** [comment]
Thanks you for reporting this! The problem is known, now its time to address it. Currently, the Polyjuice flag is too broad - ita per installation. We should replace it with a flag per database or even per application: when creating either, it should inherit global flag from installation with possibility to change it.

**Comment by per-samuelsson** [comment]
> Currently, the Polyjuice flag is too broad - ita per installation. We should replace it with a flag per database or even per application: when creating either, it should inherit global flag from installation with possibility to change it.

I agree with this. I looked some in the code on how it works, and it seems to be a few different spots we need to redesign. The ```PolyjuiceAppsFlag``` and its effects is one.

Another thing we need to think about when doing this if we really want all applications that are built on a Starcounter polyjuice edition installation to include the edition libraries. I guess not? And if not, we need a way to configure if edition libraries should be included or not, and this have to be passed to the weaver too.

**Comment by per-samuelsson** [comment]
> Another thing we need to think about when doing this if we really want all applications that are built on a Starcounter polyjuice edition installation to include the edition libraries. I guess not? And if not, we need a way to configure if edition libraries should be included or not, and this have to be passed to the weaver too.

I created a new issue to implement the above, #2619, and self-assigned it to implement.

**Comment by per-samuelsson** [comment]
> I created a new issue to implement the above, #2619, and self-assigned it to implement.

This is now implemented and pushed to **develop**.

**Comment by Starcounter-Jack** [comment]
There is no Polyjuice edition of Starcounter. The installer should install the same exact bits. The only difference should be that the installer will ask you to register your App Store and account at Polyjuice.com. It will also point you to a Polyjuice app centric wiki and getting started tutorial.


## Polyjuice installer

1. Agree to licence agreement and choose directories and options for Starcounter
2. Create account and organisation (ala GitHub)
3. Slideshow during installation is Polyjuice centric
* 4. The installed state contains the Starcounter and Polyjuice bits (exact same as the other installer) *
5. Installer ends at Polyjuice wiki.

## Starcounter installer

1. Agree to licence agreement and choose directories and options for Starcounter
2. Slideshow during installation is more generic about the Starcounter platform.
* 4. The installed state contains the Starcounter and Polyjuice bits (exact same as the other installer) *
3. Installer ends at Starcounter wiki.

**Comment by alemoi** [comment]
Here is the info about database Polyjuice flag: http://starcounter.io/nightly-changes/polyjuice-database-flag/

**Comment by miyconst** [comment]
@alemoi thanks, this is an old issue, created long before we the flag was added, I close it.
