### ISSUE TITLE
By some reason the Json Html property is not set even when setting

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2615]
When I run Cartographer app, for example, with People application (and trying to edit a specific contact) and Launcher, I can see that LocationInfo->Html property for Cartographer property takes the default value, however I set it explicitly (line 49). Cartographer application is located here: https://github.com/Polyjuice/Cartographer

To reproduce, start all three apps, add a new contact and try to edit it. When getting to editing page, the Json sub-tree for Cartographer will have default Html value (empty string).

**Comment by chrhol** [comment]
This issue is solved. We fixed some parts of the handler that was not correct.
