### ISSUE TITLE
Deleting Json element from the list and deleting object from database

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2618]
Trying to delete an item from database and as well an element in the list.
The following works fine (Parent here is used just as example):

```c#
        void Handle(Input.Delete input) {
            this.Data.Delete();
            this.Data = null;
            Transaction.Commit();

            ((LocationsPage)this.Parent.Parent).LocationsList.Remove(this);
        }
```
and this does not work:
```c#
        void Handle(Input.Delete input) {
            this.Data.Delete();
            this.Data = null;
            ((LocationsPage)this.Parent.Parent).LocationsList.Remove(this);

            Transaction.Commit();
        }
```

As you can see the order matter in this example. Is there explanation why it is so?

**Comment by chrhol** [comment]
It shouldn't matter in which order you do it so this is a bug I think.

My guess (without any investigation) is that the transaction that is attached to `this` is unregistered on the session and removed from the item when you call LocationList.Remove so when Transaction.Commit is called there is no longer a valid transaction. 

There is no exception thrown when running the code that does not work?

**Comment by alemoi** [comment]
Yes, there is no exception.

**Comment by chrhol** [comment]
Actually there is an exception, but the server default behaviour is that the patches are rejected silently and no error is sent back to client. I will change this so default behaviour is that it's not silently rejected with an option to turn it on.

In your case the second example fails because the transaction is attached higher up in the tree, so when you remove the child first and then call `this.Transaction` it will return null.

**Comment by chrhol** [comment]
My previous comment was not correct. The exception is actually sent back to the client. You can see it if you have the network-tab open, but you get no other notification. It will also be logged in the serverlog

So this was not due to the session rejecting the patch.

**Comment by chrhol** [comment]
(and if websockets are not used...)
