### ISSUE TITLE
Compiletime error for invalid bindings in typed json.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#262]
There need to be some way to get an earlier notification/exception for an invalid binding in a jsonobject, one of the problems with the current solution can be found in issue #216.

If we have a typed jsonobject it should be possible to add code in the generated file that access the property in the dataobject to get a error during compilation and be able to pinpoint the actual property that cannot be bound.

**Comment by chrhol** [comment]
So, it's finally time to implement this.

To keep backwards compability, we will implement a new interface, `IExplicitBound<T>`, where all properties are considered always bound. If any exceptions should be made to a property, it needs to be manually set.

Code to test these bindings will be added to the generated code. One drawback is that there doesn't seem to be a way to redirect the compilation error to point to the original json file. Which means that invalid bindings will point to the generated code. 

Each property that is bound will be tagged with a `BoundAttribute` and using the `nameof` parameter to test the binding. This will mean that when a binding is not valid, for example a property in a database class have been renamed, an error is shown when compiling and if you are in VS, clicking on that item, will end up on the attribute where it can be seen which property and what binding failed.

```csharp
// Auto generated code \\
public partial class PersonPage {
    [Bound(nameof(Person.Name))]
    public string Name { get; set; }

    [Bound(nameof(Person.Surname))]
    public string Surname { get; set; }
}
```

This will not work for bindings that use a path expression, so either we have to treat bindings with a path as before, meaning they will not generate a compiletime error, but a runtime error, or we add another test for those.

For example adding a dummy-method, that will never be called.

```csharp
// Auto generated code \\
public partial class PersonPage {
    [Bound(nameof(Person.Name))]
    public string Name { get; set; }

    [Bound(nameof(Person.Surname))]
    public string Surname { get; set; }

    // Will never be called, only used to generate compilation errors and to keep track.
    private void CompileTimeTestBindings() {
        Person p = null;
        var x = p.Adress.Street; // Bound to PersonsPage.Street
    }
}
```

Another advantage of having these compiletime checks, is that you can use built-in mechanisms to get for example the call-graph of a property in a database class and see that it's bound in a viewmodel.

**Comment by miyconst** [comment]
>For example adding a dummy-method, that will never be called.

I am not sure about it, but it just does not seem to be right for me.

What "path expression" bindings are you talking about in this case?

**Data base classes**

```cs
public class Address {
	public string Country { get; set; }
	public string City { get; set; }
	public string Street { get; set; }
}

public class Person {
	public string Name { get; set; }
	public string Surname { get; set; }
	public Address HomeAddress { get; set; }
}
```

**JSON view-model declaration**

```json
{
	"Person": {
		"Name": "",
		"Surname": "",
		"HomeAddress": {
			"Country": "",
			"City": "",
			"Street": ""
		}
	}
}
```

**Code behind for the view-model**

```cs
public class PersonPage : Json, IExplicitBound<Person> {
}
```

Will the `Person.HomeAddress.*` properties in the view model be marked with the `[Bound]` attribute in this case? Or I have to add another partial class and implement `IExplicitBound<Address>` for the `HomeAddress` class?

**Comment by chrhol** [comment]
> What "path expression" bindings are you talking about in this case?

In this case, there will be no path-expressions. You have to manually add the string yourself for that. I just wanted it brought up so we are aware of it.

Based on your example above (with a few changes):

```json
{
	"Person": {
		"Name": "",
		"Country": ""
	}
}
```

**Code behind for the view-model**

```cs
public class PersonPage : Json, IExplicitBound<Person> {
    static PersonsPage {
        DefaultTemplate.Person.Country.Bind = "HomeAddress.Country";
    } 
}
```

Of course in this case, you can manually add the test yourself so you are probably correct that we shouldn't add any check for this in the generated code.

`DefaultTemplate.Person.Country.Bind = nameof(Person.HomeAddress) + "." + nameof(Address.Country);`

**Comment by chrhol** [comment]
> Will the `Person.HomeAddress.*` properties in the view model be marked with the `[Bound]` attribute in this case? Or I have to add another partial class and implement `IExplicitBound<Address>` for the `HomeAddress` class?

That's a good question. I'm not sure what would be the most obvious way here.

**Comment by miyconst** [comment]
For me this is a manual binding:

```cs
DefaultTemplate.Person.Country.Bind = "HomeAddress.Country";
```

The manual bindings should not be checked by the `IExplicitBound` interface, as they might point to something else rather than a data object property.

In this particular case I believe, that we should use the `nameof` operator to construct the binding string, and the issue will be solved.

**Comment by miyconst** [comment]
>That's a good question. I'm not sure what would be the most obvious way here.

If that is not difficult/much of work, I would like to get the `[Bound]` attribute for the `Person.HomeAddress.*` properties as well, otherwise it is fine to manually declare `IExplicitBound<Address>` for every JSON object in view-model.

**Comment by chrhol** [comment]
NOTE: I will push this to both 2.2 (develop) and 2.3 (pnext)

**Comment by chrhol** [comment]
> > Will the `Person.HomeAddress.*` properties in the view model be marked with the `[Bound]` attribute in this case? Or I have to add another partial class and implement `IExplicitBound<Address>` for the `HomeAddress` class?

> That's a good question. I'm not sure what would be the most obvious way here. 

I looked at this and cannot find any way currently to get the information I need during compilation that will work. So for now I go with the assumption that you have to specify `IExplicitBound<T>` for every JSON object in the viewmodel (that should be explicit). 

I will finish the first version and then go back and see if there are any way to solve it.

**Comment by miyconst** [comment]
Sure. For the first version it should be enough.

**Comment by chrhol** [comment]
Another speedbump:
The following example, when a property in json has the same name as the datatype as it's bound to, doesn't work since the name will be ambiguous in the generated code (remember: we don't have access to any type information so we cannot verify or find out the full name):

**Database**
```csharp
public class Person {
    public Address Address { get; set; }
}
```

**PersonPage.json**
```javascript
{
  "Address": {
    "Country": "",
    }
}
```

**PersonPage.json.cs**
```csharp
public class PersonPage : Json, IExplicitBound<Person> {
    [PersonPage_json.Address]
    partial class AddressPage : Json, IExplicitBound<Address> {
    }
}
```

The reason is that the compiler dont know if we mean the property `Address` or the type `Address` in this case.

The generated code will look (roughly) like this:
```csharp
partial class PersonPage {
    [Bound(nameof(Person.Address))] // Works fine
    public AdressPage Address { get; set } 

    partial class AddressPage {
       [Bound(nameof(Address.Country))] // Will raise compilation error: ambiguous between property above and datatype
       public string Country { get; set; }
    }
}
```

The only way in this implementation I can think of is to, in the cases where property and datatype is the same, force the typeparameter to be fully qualified.

I added an exception while generating code (by simply comparing the name of the datatype with existing properties) so that an compiler error with a (hopefully) descriptive error is raised:

`ScErrJsonAmbiguousDatatypeIExplicitBound (SCERR12034): A datatype specified as a generic parameter for IExplicitBound interface is ambiguous. Please use fully qualifed name. Name: Address`

**Solution**
Change typeparameter in code-behind like this:
**PersonPage.json.cs**
```csharp
public class PersonPage : Json, IExplicitBound<Person> {
    [PersonPage_json.Address]
    partial class AddressPage : Json, IExplicitBound<StarcounterApplication9.Address> {
    }
}
```

Of course, the property could be renamed as well, to not have the same name as it's type.

**Comment by miyconst** [comment]
@chrhol I don't see why it should fail.

>The reason is that the compiler dont know if we mean the property Address or the type Address in this case.

I think, this is not the case. Compiler will take the `Address` property, not the type. Here is an example:

```cs
using System.IO;
using System;

class Item
{
    public string Name { get; set; }
}

class Child
{
    public string Number { get; set; }
}

class Parent
{
    public Child Item { get; set; }
    
    public void Test()
    {
        //Console.WriteLine(nameof(Item.Number)); // Type `Child' does not contain a definition for `Name' and no extension method `Name' of type `Child' could be found. Are you missing an assembly reference?
        Console.WriteLine(nameof(Item.Number)); // No errors
    }
}

class Program
{
    static void Main()
    {
        Parent p = new Parent();
        p.Test();
    }
}
```

**Comment by miyconst** [comment]
Anyway, the proposed solution is fine. I would only adjust the error message a little bit:

>Please use fully qualifed name **including namespace**.

**Comment by chrhol** [comment]
> I think, this is not the case. Compiler will take the Address property, not the type. Here is an example:

Ahh yes, was a bit unclear in the comment. You are right, it will take the property instead of the type and complain that you need an object reference to be able to use `nameof` for the property. And we want to point it to the type.

> Anyway, the proposed solution is fine. I would only adjust the error message a little bit:

Will change to that.

**Comment by chrhol** [comment]
I'm getting close to have something to push soon. Will not do it yet though. I want to test it a bit more. I've tried to not change anything in existing code, so if `IExplicitBound<T>` is not specified, everything should work as before. Which means that if there are some bugs or something that doesn't work when testing, it should be possible to go back to using `IBound<T>`

Everything so far is pushed to branch `issue/262`.

**Comment by chrhol** [comment]
I have pushed the implementation to both develop and pnext now. 

Need to update/add some documentation before closing this issue.

**Comment by chrhol** [comment]
@miyconst found a bug where properties that should not be bound sometimes still got added in the generated code, resulting in a compile error.

The bug is found and fixed, will be pushed soon.

**Comment by chrhol** [comment]
Pushed to both develop and pnext now.

**Comment by miyconst** [comment]
Now it works. Thanks @chrhol. I would consider this issue as done. Please close it if you don't have anything else to do.

**Comment by dan31** [comment]
@chrhol this is one of the best closed "opened windows" I have ever seen! Cool!
