### ISSUE TITLE
What is the purpose of Session.InitialRequest value

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2620]
What is the purpose of Session.InitialRequest value and why it is available only inside first Handle.GET block?

Here are some images showing what I mean:

![initial-request-1](https://cloud.githubusercontent.com/assets/6435556/6688711/a1901e0e-ccc6-11e4-90b9-5936bd0caba4.PNG)
![initial-request-2](https://cloud.githubusercontent.com/assets/6435556/6688709/a18d561a-ccc6-11e4-9f5c-013a709a2c89.PNG)
![initial-request-3](https://cloud.githubusercontent.com/assets/6435556/6688710/a18fc0c6-ccc6-11e4-994c-ca21515322be.PNG)

**Comment by alemoi** [comment]
Thank you for the question! Probably it is not used anymore. We will check!

**Comment by alemoi** [comment]
`Session.InitialRequest` was removed.
