### ISSUE TITLE
Unable to unload database: An Application, where the class is declared, needs to be loaded...

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2622]
I try to unload a database, but it fails with the following exception:
An Application, where the class is declared, needs to be loaded before unload is called. Table Simplified.Ring3.Supplier cannot be unloaded.

![sc-db-dump-error](https://cloud.githubusercontent.com/assets/6435556/6718978/b1b1e63e-cdc8-11e4-87a3-2b6d82514603.png)

The Supplier class is inside Simplified project which is included into People app, so the table must be created. Anyway, I have never ran the application which uses Supplier class, why should it try to unload  the table?

How could I avoid this?

**Comment by k-rus** [comment]
Thank you for your question.
Unload in `staradmin` is limited to unload every table found in the database and the tables were created for each declared database class. 
It is possible during unload to ignore tables, which classes are not loaded for. For this, it is necessary to write [unload app](https://gist.github.com/k-rus/867bb7bae2ceb1ed41f7), which calls `Starcounter.Db.Unload(string fileName, ulong shiftId = 0, Boolean unloadAll = true)`, where `unloadAll` means if to fail tables without loaded classes or ignore. So if you set it to `false`, the unload will succeed and it will log, which tables were ignored.

Let it me know if it helps.

**Comment by per-samuelsson** [comment]
> Unload in staradmin is limited to unload every table found in the database and the tables were created for each declared database class.

Maybe we should extend staradmin to support this with a parameter, just as we support a file to be given?

**Comment by k-rus** [comment]
> Unload in staradmin is limited to unload every table found in the database and the tables were created for each declared database class.
> Maybe we should extend staradmin to support this with a parameter, just as we support a file to be given?

I think it is good idea. Our users quite often ask for the additional functionality such as shift id and ignoring tables.

**Comment by per-samuelsson** [comment]
> Our users quite often ask for the additional functionality such as shift id and ignoring tables.

OK. I'll assign it to me to fix eventually. Can you reveal some about the shifting? Any documentation on that? Is it to shift series of keys (i.e. object ids)?

**Comment by k-rus** [comment]
> OK. I'll assign it to me to fix eventually. Can you reveal some about the shifting? Any documentation on that? Is it to shift series of keys (i.e. object ids)?

Some information is available on [the wiki](https://github.com/Starcounter/Starcounter/wiki/Reloading-database-between-Starcounter-versions#unload-stable-or-develop-version-for-reloading-into-branch-1731). Basically, `schiftId` adds the given number to the object ids read from the database. This allows to avoid collusion on reload if some data has to be populated before reload.

**Comment by miyconst** [comment]
For now I have created a temporary method to unload db.

**Comment by per-samuelsson** [comment]
With the implementation of #2623, I consider this issue fixed.
