### ISSUE TITLE
Next daily is not run on available agent

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2625]
I see that 1 of 3 agents is available. I added build of Next-Daily, but the build is queued and is not run on the available agent.
Why is it so?

**Comment by parherman** [comment]
scbuildserver3 Is a Linux build machine and is only able to run Linux builds, so only to agents are available for Windows - could that be it?

**Comment by k-rus** [comment]
Thanks for the clarification. So it is again lack of the information and misleading interface. Now I know.

**Comment by parherman** [comment]
Oki, so this was the issue. I'm sorry you have not received information about this, right now it is not used by everyone so I have not informed about it

I will bring it up on a morning meeting so that everyone gets the information!

**Comment by k-rus** [comment]
> I will bring it up on a morning meeting so that everyone gets the information!

There are no morning meetings where everyone participate. You might need to discuss with @dan31 the notification model.
