### ISSUE TITLE
Failed builds: why and how

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2627]
I merged my changes into main branch after I tested on personal branch. However, [the auto started build](https://scbuildserver/viewLog.html?tab=buildLog&buildTypeId=Starcounter_NextDaily&buildId=26735) failed. When I look into the log on the build server I can see only that the build failed during compilation, but I cannot figure out easilty what really happened. Then I started the build again and it succeeded, so it was some probabilistic problem.
So I just repeat the known two issues:

1. It is difficult to understand what failed with the current build server log.
2. Builds fail without any bug in the submitted code.

My questions are:

1. Are the issues going to be addressed?
2. When are they going to be addressed?

**Comment by alemoi** [comment]
Thanks for reporting. Searching for " error " in the build log usually reveals the problem. In this case it was a well-known error with error codes project (scerrres.h generated file), that essentially is a MsBuild bug when project dependencies are resolved incorrectly. We will move the build of this errorcodes generator project outside Level1 in the build script, so its always pre-built before Level1.

**Comment by k-rus** [comment]
> Searching for " error " in the build log usually reveals the problem.

This tip unfortunately does not really help. I did it in this case and it didn't help me. And, imho, it is not a solution to the issue 1.

**Comment by alemoi** [comment]
Yes, its definitely far from being good. I was searching for explicit step labeling in TeamCity using console log, but could not find this functionality. We need to research more on how to improve this.

**Comment by parherman** [comment]
@k-rus I have set up a test instans with TeamCity where I'm have among other things tried to enable better reporting during builds, would you like me to create an account for you so that you can see if you like it better?

There is also the Nightly Next CTest job on regular TeamCity where I have tried to enable better reporting for tests

**Comment by k-rus** [comment]
I think my questions are answered now. The work on the issues is on-going and there are some ideas how to tackle them. The timeframe is not defined, but somewhere in future.
I suggest to keep the issue open until they are  resolved.
