### ISSUE TITLE
Build server cannot start builds

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2633]
There is some problem with build server or some other server. No builds can be started.

**Comment by parherman** [comment]
TeamCity cannot access github.com for some reason, investigating

**Comment by k-rus** [comment]
According to [the status at GitHub](https://status.github.com) it is under DDoS attach.

**Comment by parherman** [comment]
It looks like the connection to github is unstable at the moment, and most of the time we get timeouts. It might take some time for them to recover to full capacity from the DDoS attack earlier this morning.

Will continue to monitor this

**Comment by per-samuelsson** [comment]
https://status.github.com/

**Comment by parherman** [comment]
I have temporally increased the global changes check interval to 30 min, so jobs will not start directly for the time being

**Comment by k-rus** [comment]
I think the problem is with our client software used on the build server. Accessing GitHub from git works perfectly.

**Comment by parherman** [comment]
I actually get timeouts on git clone https://github.com/Starcounter/Starcounter.git from time to time

**Comment by parherman** [comment]
GitHub: 8:31 UTCAt this time we're fully operational but we're still mitigating the ongoing DDoS attack and there may be intermittent connectivity issues as we continue working on the problem

**Comment by k-rus** [comment]
I think we need to change our build strategy with cloning. Now the build server does many clones for one single build. This will be always bottleneck.
Note that daily builds should be very smooth and optimised to safe our time. It is necessary to investigate strategies to decrease time to build a daily build, e.g., by pulling instead of cloning.

**Comment by parherman** [comment]
That is a good point and there is ongoing work on a setup where we reuse build artifacts and don't pull the repos again unless there is a change for example

We should also investigate having internal/local mirrors of our repos and use web hooks in github to trigger builds instead of pulling for changes

**Comment by k-rus** [comment]
> don't pull the repos again unless there is a change for example
> 
> We should also investigate having internal/local mirrors of our repos and use web hooks in github to trigger builds instead of pulling for changes

The problem is not in pulling changes, but cloning entire repos. I can pull, fetch or push changes to GitHub without big problems even during DDoS, since the changes are small, but cloning entire repository is expensive and still does not work.
Of course, using pulling instead of cloning will complicate things, but I don't see other way to make our work smooth.

**Comment by per-samuelsson** [comment]
> I think we need to change our build strategy with cloning. Now the build server does many clones for one single build. This will be always bottleneck.

I agree. Nightly builds are fine using clone, but daily builds should optimally not.

>  I can pull, fetch or push changes to GitHub without big problems even during DDoS

I can not. :cry:. I'm trygin to push recent development in on of my branches, and just don't work. So hard to do personal tests at the moment.

**Comment by k-rus** [comment]
> I can pull, fetch or push changes to GitHub without big problems even during DDoS
> I can not. . I'm trygin to push recent development in on of my branches, and just don't work. So hard to do personal tests at the moment.

I was able to pull and push, but personal tests cannot be done. I am trying (in background) to run it without success for long time now. Once I was lucky that a test started but it failed during cloning Launcher. Why launcher is in daily tests I don't know.

**Comment by parherman** [comment]
@k-rus the way the jobs are set up right now we do basically the same thing for all the jobs, then run a different set of tests on the builds - if you want to I can give you access to the TC test instants where the jobs are more split up and you can define what tests you want to run in a separate job

**Comment by k-rus** [comment]
> @k-rus the way the jobs are set up right now we do basically the same thing for all the jobs, then run a different set of tests on the builds - if you want to I can give you access to the TC test instants where the jobs are more split up and you can define what tests you want to run in a separate job

I understand that the tests in TC are not set to work as I described and this is not a small task to fix. However, this should be planned and fixed, since we need to have more reliable and better performing environment.

I am still curious: why launcher is a part of daily builds? It was decided to have minimal amount of tests in daily builds and cloning, building and running launcher does not seem to qualify such.

**Comment by parherman** [comment]
> I am still curious: why launcher is a part of daily builds?
There is a test project available in the buildsystem repo for the Luncher but I dont think it runs, it could be left in there by mistake

Except for some test projects repos the same things are pulled for most jobs right now

**Comment by k-rus** [comment]
> I am still curious: why launcher is a part of daily builds?
> There is a test project available in the buildsystem repo for the Luncher but I dont think it runs, it could be left in there by mistake
> 
> Except for some test projects repos the same things are pulled for most jobs right now

Will it be investigated? It would be great if Launcher is not pulled for daily builds.

**Comment by parherman** [comment]
@alemoi The Luncher repos is pulled in the build script, but from the looks of it, it is not used for anything. As far as I can tell it is possible to build and run test whiteout it - do you know why it was added or if it can be removed safely?

**Comment by parherman** [comment]
According to status.github.com things are calming down a bit and I have disabled the cloneing of the launcher repo during daily builds

Jobs seem to pass more frequently now

**Comment by alemoi** [comment]
Yes, we thought to have Launcher as a preinstalled application for Polyjuice addition. So we might come back to this later. Let's have a discussion first.

**Comment by k-rus** [comment]
> Yes, we thought to have Launcher as a preinstalled application for Polyjuice addition. So we might come back to this later. Let's have a discussion first.

In my comment I mean daily build of develop, which should not have relationship to Polyjuice edition. It would be nice that the separation is kept on the build server.

**Comment by alemoi** [comment]
Unfortunately, would not be possible I think. The thing is that Starcounter and Polyjuice editions are different only in the installer, other binaries and features are the same, meaning that Polyjuice apps should be runnable on both editions and vice versa. That's why currently, develop and next daily and nightly are suppose to produce both editions.
