### ISSUE TITLE
Add the possibility to access the initial external request

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2637]
Inside the nested call hierarchy user code should still be able to access the initial external HTTP request and possibly the requests on each intermediate level.

**Comment by alemoi** [comment]
For now added a possibility to call handlers using the initial request, as its now working in Launcher with middleware filters. Here is the commit: 26ddd56d690b40cd333600af506085d448b03fbc

**Comment by alemoi** [comment]
Access to initial external request is in `Handle.IncomingRequest` where you can read incoming cookies and HTTP headers. For setting outgoing cookies use `Handle.AddOutgoingCookie`.

**Comment by andwah** [comment]
```Starcounter.Handle.IncomingRequest``` is null if you have enable WebSocket's.
