### ISSUE TITLE
Next daily does not run automatically

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2641]
It seems that pushes to next branch does not trigger automatically daily build. Is it by design? Can it be run automatically on commits as develop daily?

**Comment by parherman** [comment]
It looks like the last build was triggered by git, or am I missing something? 

https://scbuildserver/viewLog.html?buildId=26976&tab=buildResultsDiv&buildTypeId=Starcounter_NextDaily

It triggered on my push now, but I will keep an eye out for this

**Comment by k-rus** [comment]
> k-rus It looks like the last build was triggered by git, or am I missing something?
> 
> http://192.168.200.21:7990/projects/BLUESTAR/repos/level0/commits?until=refs%2Fheads%2Fnext
> 
> https://scbuildserver/viewLog.html?buildId=26976&tab=buildResultsDiv&buildTypeId=Starcounter_NextDaily
> 
> It triggered on my push now, but I will keep an eye out for this

Yes, you are correct. I was surprised that the triggered build contained more than just mine changes. I should reformulate my question?
Why are the builds not started sometimes? Why was there no build for changes from @alemoi and @chrhol ?

**Comment by parherman** [comment]
In the history it looks like the previous build was canceled

**Comment by k-rus** [comment]
> @k-rus In the history it looks like the previous build was canceled

Thank you for clarification. I was confused by this. No more questions from me. I am closing the issue.
