### ISSUE TITLE
Corrupt json-patch value

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2642]
Same issue with double comma `,,` in json-patch again.
This time in another place:
https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet.js#L381

Here is the link to the patch data:
https://jsfiddle.net/qokxbgk9/

How to reproduce the bug:

1. Start Launcher, UserAdminApp, GoogleSignIn, SignInApp all together.
2. Navigate to http://localhost:8080/signinapp/signinuser

Note: the cookie-rework branch of SignInApp should be used.
https://github.com/Polyjuice/SignInApp/tree/cookie-rework

With a hack-fix inside puppet.js
```javascript
var json = JSON.parse(responseText.replace(/,,/gi, ","));
```

Everything works fine.

**Comment by miyconst** [comment]
Same happens when I run only Launcher ans SignIn app together.
New patch here:
https://jsfiddle.net/tcz4upd1/

The problem is on the server side, not the client.

Note: You have to use cookie-rework branch of SignIn application.

**Comment by warpech** [comment]
@chrhol could you take a look? It happens in initial `application/json` response when running just two apps: Launcher (master branch) and SignIn (cookie-rework branch)

**Comment by chrhol** [comment]
I have reproduced it, looking into it now. I thought I fixed the double commas but apparently not in all places.

**Comment by miyconst** [comment]
@chrhol will this update be available in today's nighty build?

**Comment by chrhol** [comment]
@miyconst, yes I just pushed it to develop (and next). It should be available in the next nightly build. Or I could upload a daily build if you like.

**Comment by miyconst** [comment]
@chrhol no need for daily build, thank you.

I will test it tomorrow and close the issue if it works.

**Comment by miyconst** [comment]
The bug is fixed. Closing the issue.
