### ISSUE TITLE
Cookie.cs class

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2643]
GoogleSignIn app and SignInApp share the same class `Cookie.cs`.
https://github.com/Polyjuice/GoogleSignIn/blob/master/Server/Cookie.cs

Lots applications might use cookies and all of them will implement some wrapper to get/set cookies.
That is why I think the class should be included in Starcounter.

Other way is to create a custom `.dll` and use it in GoogleSginIn and SignInApp, but it is never a good idea to copy paste entire class/file.

**Comment by alemoi** [comment]
Agree, we need something like this and it should probably be integrated into Request/Response classes.
