### ISSUE TITLE
Commit hooks

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2644]
There is such line of code inside SignInApp:
```csharp
CommitHooks.LocalAppUrl = "/GoogleSignIn/__db/__" + StarcounterEnvironment.DatabaseNameLower + "/societyobjects/systemusersession";
```
https://github.com/Polyjuice/SignInApp/blob/master/src/Database/CommitHooks.cs#L18

Does this url has some meaning or there may be used anything?

**Comment by dan31** [comment]
@miyconst, would you review the question in a light of 2.0 commit hooks?

**Comment by miyconst** [comment]
Yes, there is no such code anymore. The commit hooks has replaced it.
