### ISSUE TITLE
ScErrInputQueueFull (SCERR1026)

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#2646]
After a while "pushing" data on the socket i sometimes get this error

```
20150401T171559 Error sc://abc/personal Starcounter.Server.Commands 1026 System.Exception: ScErrInputQueueFull (SCERR1026): Operation failed because the target input queue was full.
Version: 2.0.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1026.
   at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId) in c:\\github\\Level1\\src\\Hosting\\Starcounter.Hosting\\TaskSchedulerImpl.cs:line 39
   at Starcounter.Internal.TaskScheduler.Run(ITask task, Byte schedId) in c:\\github\\Level1\\src\\Starcounter\\DbSession.cs:line 40
   at Starcounter.DbSession.RunAsync(Action action, Byte schedId) in c:\\github\\Level1\\src\\Starcounter\\DbSession.cs:line 104
   at Starcounter.Session.ForEach(UInt64 cargoId, Action`1 action) in c:\\github\\Level1\\src\\Starcounter.XSON\\Sessions\\Session.cs:line 172
   at Administrator.Server.Managers.ServerManager.PushchangesToListeners() in c:\\github\\Level1\\src\\Starcounter.Administrator\\Server\\Managers\\ServerManager.cs:line 156
   HResult=-2146233088
   HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1026
```

**Comment by alemoi** [comment]
Yes, its a known problem with limited queue size. Websocket.ForEach, since it needs to send on all sockets, it does schedule a job for other schedulers (to which those sockets belong). I will however take a look and make sure that sockets job is not per each socket but for all selected sockets per scheduler.

**Comment by andwah** [comment]
thanks, and maybe i can switch from ```Session.ForEach``` to ```WebSocket.ForEach``` or does both use the RunAsync method?

**Comment by alemoi** [comment]
I have checked the code and `RunAsync` is running for each scheduler with a "thick" delegate, and not for each WebSocket as I first assumed. Then it means that `WebSocket.ForEach` is called very frequently, since each scheduler has a queue size of 1024, which exceeds.

**Comment by alemoi** [comment]
`Session.ForEach` also runs a "thick" delegate up to number of schedulers, so the story there is the same as for `WebSocket.ForEach`. On what events is ForEach executed?

**Comment by andwah** [comment]
When the server data model changes (if a database/app is started/stopped etc..),  when a database starts there can be many events (the operation has many micro jobs to execute). 

I get the feeling that the queue is never emptied?. can that be so?,  it takes a while before i get the error.

**Comment by alemoi** [comment]
> I get the feeling that the queue is never emptied?. can that be so?, it takes a while before i get the error.

Should not be the case. It can be just a big burst of tasks causing the error.

**Comment by alemoi** [comment]
Since WebSocket API is completely changed and there is no `WebSocket.ForEach` anymore - I am closing this issue. However, the case still could be possible for the `Session.ForAll`, but that would be a separate issue.
