### ISSUE TITLE
Response data for REST API

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2647]
There should be a way to return clean JSON result for third side applications.

Applications with own GUI would like to see clean API response. Lets take SignIn method for example.

Expected:
```javascript
{
    "IsSignedIn": true,
    "Message": "",
    "FullName": "Konstantin Mi",
    "ImageUrl": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
}
```

Actual:
```javascript
{
    "_ver#c$": 0,
    "_ver#s": 0,
    "Html": "/Launcher/LauncherTemplate.html",
    "homeThumbnail": {
    },
    "homeUrl": "",
    "editingMode$": false,
    "searchBar": {
        "query$": "",
        "searchEngineResultPageUrl$": "",
        "feedback": [
        ]
    },
    "results": {
    },
    "user": {
        "Launcher": {
            "Html": ""
        },
        "SignIn": {
            "Uri": "",
            "Html": "/SignIn/html/SignInPage.html",
            "Username$": "",
            "Password$": "",
            "IsSignedIn": true,
            "Message": "",
            "FullName": "Konstantin Mi",
            "ImageUrl": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg",
            "SignInForm": {
                "SignIn": {
                },
                "Launcher": {
                    "Html": ""
                },
                "Html": ""
            }
        },
        "Html": "/polyjuice/htmlmerger?SignIn=/SignIn/html/SignInPage.html"
    },
    "menu": {
        "Launcher": {
            "Html": "/Launcher/LauncherMenu.html"
        },
        "Html": "/polyjuice/htmlmerger?Launcher=/Launcher/LauncherMenu.html"
    },
    "launchpad": {
        "icons": {
            "Launcher": {
                "Html": ""
            },
            "Html": ""
        },
        "names": {
            "Launcher": {
                "Html": ""
            },
            "Html": ""
        }
    },
    "dashboard": {
    },
    "appFilter": [
    ],
    "uri": "",
    "workspaces": [
    {
        "appName": "signin",
        "master": {
            "Launcher": {
                "Html": ""
            },
            "SignIn": {
            },
            "Html": ""
        },
        "Html": "/Launcher/LauncherTemplate.html"
    }
    ]
}
```

**Comment by alemoi** [comment]
I assume you don't want to modify the user code and still be able to respond with plain JSON?

**Comment by alemoi** [comment]
One way could be to send a special accepted MIME type from client, like e.g. application/plain-json.

**Comment by miyconst** [comment]
@alemoi yes, that is what I thought about.

I think it is okay to modify server side code to make it work in both `plain-json` and `json-patch` ways, but the goal is to make same method work for both requests.

**Comment by alemoi** [comment]
Another would be to uncheck Polyjuice flag on database where you are running. Then your app will automatically return exactly what you are sending in response. So do you want to simulataneously run both modes or one at a time?

**Comment by miyconst** [comment]
@alemoi it should work simultaneously, should not it?

For example, we have an ordinary polyjuice web application and another application which somehow related to our data, they both should run at the same time.

**Comment by warpech** [comment]
This is important for the project that we discussed today on the meeting. 

The requirement is to have a JSON REST API as well as an admin web interface for the same information (wrapped in Launcher).

I can think of 2 solutions:

1. Provide a special mime-type: `application/json-root+json`. Only with this mime-type client would receive the view-model wrapped in Launcher. This is something that we already discussed and what could be used here.
2. Only `Json` responses that have a session are wrapped in Launcher. If it does not have a session attached, it is a stateless response which goes unwrapped to the client.

I like solution 2 much more. @miyconst WDYT? Could you check, maybe it already works like that?

**Comment by miyconst** [comment]
Launcher creates its own session and wraps every page, no matter this page is attached to the session or not.

**Comment by warpech** [comment]
@alemoi, @Starcounter-Jack, @chrhol what do you think of solution proposed in point 2 above?

The implication would be that stateless responses will not get wrapped in Launcher. I think this is a good thing, because previously we had problems with stateless responses with apps anyway.

**Comment by chrhol** [comment]
> The implication would be that stateless responses will not get wrapped in Launcher. I think this is a good thing, because previously we had problems with stateless responses with apps anyway.

I thought this was the way it worked today. If you don't attach the json to a session and return it you will get the json you returned. Unless it's called from a `Self.GET` I guess and it's merged...but then I saw the earlier comment from @miyconst:

> Launcher creates its own session and wraps every page, no matter this page is attached to the session or not.

Is it treated as a workspace perhaps and the function in launcher adds an empty workspace-page to wrap it in. So the thing we need to change is in how the launcher listens and responds to all requests?

**Comment by warpech** [comment]
Yeah, Launcher does that explicitly here: https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/api/LauncherHelper.cs#L24

So Launcher should only wrap the responses if they are attached to a session. Currently Launcher doesn't know that, because:

1. apps are isolated, so Launcher cannot check response from another app
2. AddFilterToMiddleware runs before the request, not after it (@alemoi is this true?)

**Comment by alemoi** [comment]
Yes, middle-ware filters, once added are running before the external requests: http://starcounter.io/nightly-changes/addingskipping-middleware-filters/

**Comment by warpech** [comment]
So, `AddFilterToMiddleware` can only judge if a request is wrappable based on the request properties (such as URL, headers, ...), not based on the response properties.

How could we make judgement based only on request properties? Currently, Launcher wraps all requests [that are not system handlers](https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/api/LauncherHelper.cs#L29), ignoring the mime-type. 

`application/json-root+json` (proposed earlier in this thread) is only a solution for wrapping JSONs, but not for HTML and other mime-types. So we have to dismiss it as a solution to this problem.

Conditional mapping for any request mime-type can be achieved if Launcher takes some URI argument into consideration (URI contains `/rest/` or `?rest` etc) or `User-Agent` header (all browser UA strings contain the word `Mozilla`). 

Both above suggestion seem to be ugly workarounds, but I cannot think of a better solution if Launcher  can only consider request properties for wrapping.

**Comment by warpech** [comment]
As @alemoi explained in the Hangout, the problem expressed in first message of this thread is solved with using `skipMiddlewareFilters` flag in the request handler. Explained here: http://starcounter.io/nightly-changes/addingskipping-middleware-filters/

I think this is better than all the proposed solutions in this thread :+1:

@alemoi, @miyconst if you're fine with this, we can close this issue

**Comment by miyconst** [comment]
Does this mean, that all *Pure REST API* handler should be with `SkipMiddlewareFilters = true` flag?

I am okay with this, but what if I want to use a filter to check authentication in my api application, but not wrap it with Launcher?

**Comment by alemoi** [comment]
Hmm, if the same handler should be wrapped in some cases and pure on other, I guess the only way to tell this to server is to send some indication from the client.

**Comment by miyconst** [comment]
Then the client will be able to bypass an authentication filter.

Let's say I am a developer of a single app. I have some auth logic, and for that purpose created a filter. Then someone runs my app inside a Launcher. The app still should call only mine own filters, not Launcher's.

**Comment by miyconst** [comment]
In asp.net we **enable** filters, not disable. I don't know how that could help since Launcher has no idea of the handler from other apps.

**Comment by warpech** [comment]
> Let's say I am a developer of a single app. I have some auth logic, and for that purpose created a filter. Then someone runs my app inside a Launcher. The app still should call only mine own filters, not Launcher's.

Shouldn't both filters be applied in such case? I agree that we may need to refine the filters (or maybe let them be fine-controllable in mappers), but that is not the purpose of current issue.

To discuss filters, please create a new issue when needed. It would be good to illustrate it with links to reference material in other platforms. I expect that in JS world, [Koa](https://github.com/koajs/koa) (a successor to ExpressJS) has state-of-the-art filters, which can be used to compare.

@miyconst can you check if wrapping `SkipMiddlewareFilters = true` handlers in `SkipMiddlewareFilters = false` handlers works as expected (that is: the response is passed to the filter).

**Comment by miyconst** [comment]
Yes, it works as expected:

```cs
Handle.GET("/images/nosession", () => {
    return new IllustrationPage() { Html = "A page without session." };
}, new HandlerOptions() { SkipMiddlewareFilters = true });
```

This returns pure json of the `IllustrationPage`.
