### ISSUE TITLE
What means $ in front of variable name in json model?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2649]
Here is an example:
https://github.com/Polyjuice/Images/blob/master/JSON/IllustrationJson.json#L4

```javascript
{ 
	Html: "/Images/images.html",
	Name$: "",
	$Name$: {Bind:"Concept.Name"},
	DbIDString : "",
	ImageURL$: "",
	$ImageURL$: {Bind:"Content.URL"},
	Delete$: 0
}
```

What does `$Name$` means and what is it made for?

**Comment by chrhol** [comment]
It's used on the server when generating code from Json-By-Example for TypedJson. It's a way to add metadata information directly in the json-file.

In the example above, `$Name$`, a path is specified that the property should be bound to in the dataobject. 

It doesn't look like this is documented anywhere though (as usual). it should probably be reviewed first if it the best way to handle this kind of functionality.

**Comment by chrhol** [comment]
I've added a new issue for reviewing and documenting this feature, #2650

**Comment by miyconst** [comment]
@chrhol thank you for the explanation.
