### ISSUE TITLE
Review and document how we specify metadata in json for TypedJson.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2650]
Today we use the `$` char in the beginning of a propertyname in json to specify metadata for the property (or object), like paths for binding, reuse of existing typedjson classes and namespaces.

This should be reviewed to make sure that it's a solution we want and properly documented.

**Comment by miyconst** [comment]
Personally I would like to keep JSON files without any logic.

I prefer this:
```json
{
    "Username": "",
    "Someone": { "FullName": "" }
}
```

Rather than this:
```json
{
    "Username": "",
    "FullName": "",
    "$FullName": { "Bind": "Someone.FullName" }
}
```

**Comment by per-samuelsson** [comment]
> Personally I would like to keep JSON files without any logic.

+1.

I'm just trying to learn all this JSON-stuff. I'll gladly try to help out whereever I can.

**Comment by chrhol** [comment]
> > Personally I would like to keep JSON files without any logic.

> +1

I have no opinion on the sample, if you rather create another object that is automatically bound, it is perfectly fine to do that, but sometimes it might not be possible to change the structure of the viewmodel but you still want it to be bound. And you dont always want to keep the viewmodel looking exactly as the database objects.

> I'm just trying to learn all this JSON-stuff. I'll gladly try to help out whereever I can.

I think that is a good thing. Both you and @miyconst come with good feedback. Maybe we can take a little time and do some brainstorming on what we want and how we want it to look.

**Comment by per-samuelsson** [comment]
> Maybe we can take a little time and do some brainstorming on what we want and how we want it to look.

Sure, I'm all for it. But I need to allocate even more time to read/test/consider before doing this though, because I'm still such a novice compared to you guys. Basically, all thoughts I have so far, I've turned into issues.

**Comment by chrhol** [comment]
Parts of this is already covered, and with the change of jsonparser to newtonsoft (#3811) these parts will be documented by that issue. Closing this one.
