### ISSUE TITLE
Add Handle.SetOutgoingStatusCode method

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2653]
Method `Handle.AddOutgoingHeader` is handy for setting outgoing headers, but there is no way to set response status code by it.

There should be a way to change response status code. 

By this piece of code I assume that in the past it was working somehow:
https://github.com/Polyjuice/Images/blob/master/ImageUpload.cs#L50
```csharp
return new Response() {
    StatusCode = (ushort)System.Net.HttpStatusCode.UnsupportedMediaType,
    StatusDescription = "Unfortunately, we don't support " + mime + " file type.  Try again with a PNG, GIF, or JPG."
};
```

**Comment by alemoi** [comment]
Added methods for setting outgoing HTTP status code and description: `Handle.SetOutgoingStatusCode` and `Handle.SetOutgoingStatusDescription`

**Comment by miyconst** [comment]
@alemoi thank you.

Both of the methods work, I close the issue.

**Comment by miyconst** [comment]
Found a bug.

Once I set status code and description:
```csharp
Handle.SetOutgoingStatusCode((ushort)500);
Handle.SetOutgoingStatusDescription("Internal server error");
```
It applies for all handlers till I change it manually again.

Steps to reproduce:
- Create an app with three handlers, I used People app (`/people/persons`, `/people/persons/@w`, `/people/organizations`).
- To handler 1 add code:
```csharp
Handle.SetOutgoingStatusCode((ushort)200);
Handle.SetOutgoingStatusDescription("OK");
```
- To handler 2 add code:
```csharp
Handle.SetOutgoingStatusCode((ushort)500);
Handle.SetOutgoingStatusDescription("Internal server error");
```
- Open handler 1 - it works.
- Open handler 2 - it returns error.
- Open handler 3 - **it also returns error, but should not**.
- Open handler 1 again - it works.

**Comment by alemoi** [comment]
Thanks for reporting. I think I might know the reason and was expecting something like that.

**Comment by alemoi** [comment]
Just one comment: I haven't implemented outgoing status code and description initially because of conflicting applications. In comparison, cookies and headers are always just adding with possible replacement. And status code always replaces with last value. I don't know yet the consequences for this, but just noting this here.

**Comment by miyconst** [comment]
@alemoi I just figured out that the headers have same wrong behaviour. Method `Handle.AddOutgoingHeader` adds a header to all future responses, which is not correct.

**Comment by miyconst** [comment]
Same happens with cookies, if I set a cookie on the server side and then change it on the client side, it will be restored to its original value with the next response.

**Comment by alemoi** [comment]
Yes, I just forgot to write that I am aware of this and going to fix soon!

**Comment by alemoi** [comment]
Should be fixed now! Thank you for reporting!

**Comment by miyconst** [comment]
I confirm, the headers, cookies and status code applies for only one response.
