### ISSUE TITLE
Could we remove /StarcounterJs and /third_party folders in the GIT repo

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2654]
@parherman 

They are not used by Starcounter.

**Comment by parherman** [comment]
Done!

Ref: 55482f093e051eee7000bcee1afb6e29472c68e5 (develop) and 55482f093e051eee7000bcee1afb6e29472c68e5 (next)

**Comment by Starcounter-Jack** [comment]
@parherman Wow, that was quick.
