### ISSUE TITLE
Make gitter chat room public

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2655]
Currently, you cannot joint the Starcounter gitter chat room unless you are a Starcounter organisation member. 

I think we should change the chat room to be ```gitter/Starcounter/Starcounter``` rather than ```gitter/Starcounter``` and allow anyone in.

**Comment by dan31** [comment]
I made a public room: ```https://gitter.im/Starcounter/Starcounter```. @mtornwall, do you get invitation from gitter?
We've been using gitter in private chat mode for some weeks with @parherman, @warpech and @k-rus. It has native mac and windows clients, stores full chat history, supports markdown. We are quite satisfied with it now.

**Comment by k-rus** [comment]
The main problem for me is that it does not work well with not native clients. Installing and running native client is not so great option as it explodes number clients on machines.
(I have not tested native client, so I cannot give feedback on its quality).

**Comment by mtornwall** [comment]
@dan31 I did. Thanks.

**Comment by dan31** [comment]
We now have public and private ones.
