### ISSUE TITLE
Add possibility to delete data from administrator panel

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2658]
Sometimes I need to delete some rows from database, and I can't do that from administrator panel by executing an sql statement. This is really annoying.

**Comment by dan31** [comment]
Good suggestion.

**Comment by warpech** [comment]
This is tracked in https://github.com/Starcounter/Starcounter/issues/166

**Comment by miyconst** [comment]
Administrator now supports `DELETE` statements, not multiline though: https://github.com/Starcounter/Starcounter/issues/3034. Closing this issue.
