### ISSUE TITLE
Unable to execute any sql when stopped on a break point in VS

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2659]
I could not execute an sql query from administrator panel when VS stops execution on a break point.
The sql query hangs till VS finishes execution. This makes impossible to check database values while debugging.

**Comment by dan31** [comment]
That's a good point, @miyconst. @per-samuelsson, I guess that isn't solvable, because ```sccode``` is stopped by debugger, so that no query can be executed against any app running in the database?

**Comment by per-samuelsson** [comment]
>  @per-samuelsson, I guess that isn't solvable, because sccode is stopped by debugger, so that no query can be executed against any app running in the database?

While the code host is being debugged, and a breakpoint is hit, yes, the threads are suspended. I guess it works pretty much like in a normal GUI application, or any kind of server really. If you suspend the threads, the user interface becomes not responsive.

Not sure if its "solvable" or not, i.e. if there is some way we can design thread management as it is used by the SQL admin UI differently. I don't know about any such efforts being made anyway. :cry:

**Comment by miyconst** [comment]
@per-samuelsson thanks for the answer, I should probably stop trying make SC work like MS-SQL.

**Comment by dan31** [comment]
To be addressed in the new version (dnx). According to current vision: data would be shared among multiple codehosts, so the query, in general, would be codehost-agnostic and thus independent of codehost threads.
