### ISSUE TITLE
Too big request

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2662]
Request with content length more than allowed fails to execute.
![request-too-big-error](https://cloud.githubusercontent.com/assets/6435556/7084935/cdd94a0a-df7a-11e4-9c42-ed1d6a36d5cf.PNG)
There should be some informative status code and message.

**Comment by warpech** [comment]
This is configurable in `scnetworkgateway.xml` in the Starcounter installation directory:

```
<MaximumReceiveContentLength>4194304</MaximumReceiveContentLength>
```

I suggest we:
1) Provide a meaningful error message for such error
2) Create a wiki page that describes common configuration options. The wiki page will be moved to starcounter.io eventually

**Comment by alemoi** [comment]
Sure. I think I will return 400 Bad Request with the reason.

**Comment by warpech** [comment]
Or perhaps 413 Request Entity Too Large?

**Comment by alemoi** [comment]
> Or perhaps 413 Request Entity Too Large?

I looked at the code I wrote and it was already 413 there :) But the browser does not display this message.

The problem is more general here. It occurs because server rejects (drops the connection) the request before its being uploaded completely (request is too long, so it obviously can't be uploaded/processed). Here is the same issue people have with nginx (probably because of the same reasons I explained above): http://serverfault.com/questions/401729/uploading-files-greater-than-1mb-connection-resets

**Comment by alemoi** [comment]
I will check with @linkdata or @dan31 tomorrow how nginx behaves on too big file upload.

**Comment by alemoi** [comment]
Here is another discussion regarding this issue: http://stackoverflow.com/questions/4947107/nginx-upload-client-max-body-size-issue

If the client behaves, it will send the `Expect: 100-Continue` header in request, but this is not always the case, of course. Our server should already behave well with `Expect: 100-Continue`, but, as I said, its just a single case.

Some people do hacks like this: http://richardarosenthal.com/?m=201308

But in general, I guess there is no ultimate solution to this case.

**Comment by alemoi** [comment]
Wrote a bit about network gateway configuration: https://github.com/Starcounter/Starcounter/wiki/Network-gateway

**Comment by dan31** [comment]
There should be some standard pattern described when user needs to upload large files with "Continue". E.g., some documents in PDF's might be uploaded to server in certain apps. I'd say there are some issues on tracker from @careri, when he did such thing, but I couldn't find them rapidly.

**Comment by miyconst** [comment]
This is how it looks in asp.net under iis: http://dotnetcodebytes.blogspot.ru/2010/10/error-maximum-request-length-exceeded.html

So, there should be some way to display a user friendly message of what has happened.

**Comment by alemoi** [comment]
Hmm, are you sure its really happening? :)
Because when I google, I see the following: https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=asp.net+upload+Connection+was+reset

**Comment by miyconst** [comment]
As you can see from the search result, the most recent one is for year 2013. Maybe the old versions of iis did act like this, but the current does not.

I have created an empty asp.net website with simple upload form, limited request length to 500 bytes. The source code is available for download here: http://www.miyconst.com/BlogImages/UploadError.zip

Here is the result when I try to upload a file:
![request-length-exceed-asp-net](https://cloud.githubusercontent.com/assets/6435556/8177633/52948b10-140f-11e5-9873-4c23352a2189.png)

Also IIS has two modes of error reporting, something like *debug* and *release*. The *release* mode will not show error messages to the end user, but only status code and a basic message, that an error has occurred.

**Comment by miyconst** [comment]
Closing this issue as outdated.
