### ISSUE TITLE
Session ended event?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2664]
Hi!

Is there any way of getting informed of a Session ending? I would need to clean up some event handlers bound to the Session Data (JSon).

**Comment by alemoi** [comment]
Thanks for the question! You can set a destroy delegate using `Session.SetSessionDestroyCallback`. Let us know about the result!

**Comment by careri** [comment]
Thanks I´ll try that

**Comment by careri** [comment]
Seems to be working. Thanks. What is the default timeout on a session?

**Comment by alemoi** [comment]
The default value is 20 min and its set in `DefaultSessionTimeoutMinutes` in your database configuration. Let us know if that works fine for you!

**Comment by alemoi** [comment]
The session destroy event has changed its API: https://github.com/Starcounter/Starcounter/issues/2722
