### ISSUE TITLE
Patch replaces the whole JSON tree fragment instead of 2 properties

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2669]
There is a case where the whole JSON tree of a mapped app gets replaced in a patch response when only some properties were changed.

Steps to reproduce:

1. Run the current versions of Launcher, SignIn and People (or Products or any other app)
2. Visit the URL [http://localhost:8080/signin/signinuser](http://localhost:8080/signin/signinuser) to create the JSON tree. SignIn is present in 2 places in the JSON tree:
 - /user/SignIn (for the icon and dropdown in top right corner) f
 - /workspaces/0/master/SignIn (for the big form) f
3. Click on the "Persons" link in the left menu to change workspace to another app (this step is not neccessary to reproduce the problem but makes it more apparent)
4. Click on the user icon in top right corner. Provide some fake user name and password and press "Sign In".
5. You will see the SignIn app workspace output about People app workspace. This is because the reponse from the server replaces `/workspaces/0/master/SignIn` when it should just replace few primitive properties.

Screenshot:
![signin](https://cloud.githubusercontent.com/assets/566463/7135536/ffe2361c-e2a7-11e4-9a31-a4f8b6fe06c9.png)

Request:
```
GET http://localhost:8080/signin/signin/a/a
Accept:application/json-patch+json
X-Referer:/__default/215F434D0575069690000000
```

Response:
```
200 OK
Cache-Control:no-store
Content-Length:934
Content-Type:application/json-patch+json
Date:Tue, 14 Apr 2015 11:15:32 GMT
Server:SC
Set-Cookie:soauthtoken=; path=/

[  
   {  
      "op":"replace",
      "path":"/_ver#s",
      "value":5
   },
   {  
      "op":"test",
      "path":"/_ver#c$",
      "value":3
   },
   {  
      "op":"replace",
      "path":"/user/SignIn/IsSignedIn",
      "value":false
   },
   {  
      "op":"replace",
      "path":"/user/SignIn/Message",
      "value":"Invalid username or password"
   },
   {  
      "op":"replace",
      "path":"/user/SignIn/FullName",
      "value":""
   },
   {  
      "op":"replace",
      "path":"/workspaces/0/master/SignIn/IsSignedIn",
      "value":false
   },
   {  
      "op":"replace",
      "path":"/workspaces/0/master/SignIn/Message",
      "value":"Invalid username or password"
   },
   {  
      "op":"replace",
      "path":"/workspaces/0/master",
      "value":{  
         "Launcher":{  
            "Html":""
         },
         "Launcher":{  
            "Html":""
         },
         "SignIn":{  
            "Uri":"",
            "Html":"/SignIn/viewmodels/SignInFormPage.html",
            "Username$":"",
            "Password$":"",
            "IsSignedIn":false,
            "Message":"Invalid username or password",
            "OriginUrl":"",
            "RedirectUrl":""
         },
         "Html":"/polyjuice/htmlmerger?SignIn=/SignIn/viewmodels/SignInFormPage.html"
      }
   },
   {  
      "op":"replace",
      "path":"/workspaces/0/Html",
      "value":"/Launcher/LauncherTemplate.html"
   }
]
```

cc @miyconst

**Comment by chrhol** [comment]
Thanks for reporting it here. I will take a look.

**Comment by warpech** [comment]
Another (less painful but unelegant) symptom of this is:

1. Run Launcher and Products
2. Go to http://localhost:8080/
3. Click on "Products" in the left menu
4. Click on "Products" again. No information changes on the screen but the Products app output flickers because the whole object at `/workspaces/0/master` is replaced.

Patch output:

```json
[
  {
    "op":"replace",
    "path":"/_ver#s",
    "value":1
  },
  {
    "op":"test",
    "path":"/_ver#c$",
    "value":0
  },
  {
    "op":"replace",
    "path":"/workspaces/0/master",
    "value":{
      "Launcher":{
        "Html":""
      },
      "Launcher":{
        "Html":""
      },
      "Launcher":{
        "Html":""
      },
      "Products":{
        "Html":"/Products/viewmodels/LauncherWrapperPage.html",
        "CurrentPage":{
          "Html":"/Products/viewmodels/ProductListPage.html",
          "Products":[
            {
              "Key":"EN",
              "Name":"Coke",
              "Delete$":0
            },
            {
              "Key":"Eu",
              "Name":"Fanta",
              "Delete$":0
            },
            {
              "Key":"Ew",
              "Name":"Sprite",
              "Delete$":0
            },
            {
              "Key":"FA",
              "Name":"Pepsi",
              "Delete$":0
            }
          ],
          "Confirm":{
            "Message":"",
            "Ok$":"",
            "Reject$":""
          }
        }
      },
      "Html":"/polyjuice/htmlmerger?Products=/Products/viewmodels/LauncherWrapperPage.html"
    }
  },
  {
    "op":"replace",
    "path":"/workspaces/0/Html",
    "value":"/Launcher/LauncherTemplate.html"
  }
]
```

**Comment by chrhol** [comment]
As far as I can see these responses are actually correct. The `master` property is set with a new json which is then sent to the client, even if parts of the responses returns an existing viewmodel.

The problem lies in `Polyjuice.LauncherHelper.WrapInLauncher(...)` I think.

The following code will always create and set a new json even if some of the siblings are reused, since the returning response will be the launcher response. I guess we need some way to allow reusing the same instance of the viewmodel and check before setting master to avoid this.

```c#
...
Response resp = X.CallUsingExternalRequestEfficiently(req, () => {
    var p = new Page();
    return p;
});

foundWorkspace.master = resp.Resource as Json;
...
``` 

In the first comment in this issue there are two patches that should not be sent though

```
 {  
      "op":"replace",
      "path":"/workspaces/0/master/SignIn/IsSignedIn",
      "value":false
   },
   {  
      "op":"replace",
      "path":"/workspaces/0/master/SignIn/Message",
      "value":"Invalid username or password"
   },
```

These two are included in the big response for master and should not be sent separately.

**Comment by warpech** [comment]
@alemoi what was the purpose of using `CallUsingExternalRequestEfficiently`?

**Comment by alemoi** [comment]
> @alemoi what was the purpose of using CallUsingExternalRequestEfficiently?

It uses all information like Cookies, Headers, etc + HandlerId from the external Request object, so its a very efficient REST call (no URI matching, no Request object creation, etc). Do you have any problems with it?

**Comment by warpech** [comment]
It looks that after refactor by @tomalec it is fixed. This was Launcher app problem in the end. Thanks!

**Comment by warpech** [comment]
@miyconst can you please verify that your problem (SignInApp form unexpectedly showing in workspace of another app) is fixed?

**Comment by miyconst** [comment]
@warpech, looks like it is fixed.
