### ISSUE TITLE
Too verbose about static server

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2672]
When I start application by `star`, I always get a message about adding directory to static web server in the command prompt window. IMHO, this detail is a debug information and user should not be disturbed by such message in default. This is similar to printing information that new tables are created and added to meta-data whenever an application is started (and we don't print this).
I recommend to print messages related to static web server (if not error) only at verbose mode.

**Comment by k-rus** [comment]
BUMP
Any comments?

**Comment by alemoi** [comment]
I actually agree with your statement and will remove these debug messages. Thank you for the input!

**Comment by alemoi** [comment]
Fixed via 19b4c4587f87db53d5c3fc47d3323fd57942bf2b
Thank you for reporting!
