### ISSUE TITLE
Unspecified error in sccoredb!_AcquireNxLock_NA

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2673]
Me and @chrhol got an off-tracker question about an error that have been spotted twice in two different environments, running Starcounter 1.x:

> Unspecified error (E0000101) detected at c:\users\eriohl\projects\perforce\starcounter\dev\blue\mark1\sccoredb\sccoredb.cpp:347 (Thread 3820, Version 0.0.0).
    000007FEFCE9940D KERNELBASE!
    000000018009C364 sccoredb!_AcquireNxLock_NA : acqnxlock.cpp (13)
    00000001800B96F4 sccoredb!Mdb_DefinitionIndexToStringIndexHandle : sccoredb.cpp (334)
    000007FEF856C0E2 mscorwks!
    000007FF01B86F2D <unknown>!
    000000073F216318 <unknown>!
 
> Unspecified error (E0000101) detected at c:\users\eriohl\projects\perforce\starcounter\dev\blue\mark1\sccoredb\sccoredb.cpp:1069 (Thread 5700, Version 0.0.0).
   000007FEFDBF940D KERNELBASE!
    000000018009C364 sccoredb!_AcquireNxLock_NA : acqnxlock.cpp (13)
    00000001800BAC48 sccoredb!Mdb_ObjectReadObjRef : sccoredb.cpp (1056)
    000007FEFA48C0E2 mscorwks!
    000007FF01D26387 <unknown>!
    00000004C1E9D401 <unknown>!

I really dont have more info than that, but I thought it was best posting it here anyway.

Anyone recognize this? @eriohl?

**Comment by eriohl** [comment]
It is a debug timeout that is triggered is spin lock can not be acquired in a reasonable amount of time.

Could be that the lock is broken (not working on current hardware perhaps), that the lock is held for unreasonable amount of time or that the thread holding the lock has crashed (in which case some other error should be logged as well).

(I should note that the referenced version is no longer supported.)

**Comment by mottagare** [comment]
Thanks, I think that is enough info for us. I do think there could be a large clean-up transaction associated with this error, meaning that the transaction is open a long time which might cause the lock to time out.

**Comment by per-samuelsson** [comment]
> Thanks, I think that is enough info for us.

Nice. I'll close this issue then. Thanks for reporting.
