### ISSUE TITLE
Build server does not stop after error

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2674]
After an error happens during running a test the build continues running instead of stopping. See [this build](https://scbuildserver/viewLog.html?buildId=27255&tab=buildLog&buildTypeId=Starcounter_NextDaily&logTab=tail) for example.

**Comment by parherman** [comment]
It looks like CycleTime.exe dose not detect the exception properly

**Comment by parherman** [comment]
The job now stops on error from CycleTime test as seen in [this build](https://scbuildserver/viewLog.html?buildId=27685&tab=buildLog&buildTypeId=Starcounter_NextDaily&logTab=tail)

Closing this now
