### ISSUE TITLE
No information on the specific test running in the build log

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2675]
The build logs do not contain information on which exactly test/script is running, making difficult to investigate problems. See [this build](https://scbuildserver/viewLog.html?buildId=27255&tab=buildLog&buildTypeId=Starcounter_NextDaily&logTab=tail) for example.

**Comment by parherman** [comment]
@k-rus This is a good point and will be addressed once we move to using ctest as test runner

**Comment by k-rus** [comment]
Running tests in develop was redesigned and improved.
