### ISSUE TITLE
CycleTime test is not part of build configuration

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2676]
Almost all tests can be disabled/enabled for a build run by setting corresponding parameters. However, there is no parameter for CycleTime. Moreover, CycleTime test seems to be built every daily build. Is it by purpose? What does the test actually do?
Can it be configured to be enabled/disabled?

**Comment by k-rus** [comment]
How can I run the test locally? It is failed on the build server and I need to reproduce locally.

**Comment by alemoi** [comment]
The parameter for CycleTime test is `SC_RUN_CYCLE_TIME_TEST`, which was not exposed in Next Daily, for example (now I exposed it and set to True by default). The build scripts are located here: `http://sccode.innowait.se:7990/projects/BLUESTAR/repos/buildsystem/browse/src/Scripts` In this thread I described what the test does: https://github.com/Starcounter/Starcounter/issues/2677

**Comment by k-rus** [comment]
> The parameter for CycleTime test is SC_RUN_CYCLE_TIME_TEST, which was not exposed in Next Daily, for example (now I exposed it and set to True by default).

Thank you for fixing this.
However, performance tests should not be part of daily builds. I suggest to make it by default only in night builds.

> The build scripts are located here: http://sccode.innowait.se:7990/projects/BLUESTAR/repos/buildsystem/browse/src/Scripts In this thread I described what the test does: #2677
> To run it just execute s/CycleTime/CycleTime.exe

It would be great to have a way to get such information without obtaining build server repository and looking into the script or communicating with you. I.e., we need to have some very simple way to document tests, which I guess a separate issue.

**Comment by alemoi** [comment]
CycleTime test is now a configurable part of all build configurations. But in all cases its set to false because of a different issue (which occurs also in star loop test): https://github.com/Starcounter/Starcounter/issues/2677

So closing this one.
