### ISSUE TITLE
Next daily build often fails with missing transaction log during cycle time test

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2677]
In general, CycleTime test is the problem, see e.g. #2676.
I noticed that [this build](https://scbuildserver/viewLog.html?tab=buildLog&buildTypeId=Starcounter_NextDaily&buildId=27110) is failed due to:

> [Step 1/1] CycleTime test.
> [18:39:47][Step 1/1] 
> [18:39:47][Step 1/1] [18:39:46, Critical, Starcounter (default)]
> [18:39:47][Step 1/1] Starcounter.DbException: ScErrTransLogWriterNotAvailable (SCERR4256): Transaction log writer is not available.
> [18:39:47][Step 1/1] Version: 2.0.610.7.
> [18:39:47][Step 1/1] Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4256.
> [18:39:47][Step 1/1]    at StarcounterInternal.Bootstrap.Control.ConnectDatabase(UInt32 schedulerCount, UInt64 hmenv, UInt64 hlogs) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.610.7\Level1\src\Starcounter.Bootstrap\Control.cs:line 547
> [18:39:47][Step 1/1]    at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.610.7\Level1\src\Starcounter.Bootstrap\Control.cs:line 208
> [18:39:47][Step 1/1]    at StarcounterInternal.Bootstrap.Control.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.610.7\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
> [18:39:47][Step 1/1] ErrorCode=4256
> [18:39:47][Step 1/1] HResult=-2146233088
> [18:39:47][Step 1/1] HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4256

I also noticed that @alemoi cancelled number of builds with the same error, but no input in the issue tracker.

It would be nice to understand the issue and fix it.

**Comment by alemoi** [comment]
Thanks for the report! We noticed this problem with @parherman, a problem that occurred occasionally. Cycle time is a super simple test that measures how fast the `star.exe` with application start is. The code is here: https://github.com/Starcounter/Starcounter/blob/develop/src/Samples/CycleTime/CycleTime.cs
It just starts `star.exe s\NetworkIoTest\NetworkIoTest.exe` like the `star_loop_test.bat` but from .NET.
I don't understand the issue yet.

**Comment by eriohl** [comment]
This error occurs on failure to establish a connection to the log writer or if an existing connection is terminated. If no additional error is logged then it is probably because the log writer is yet to initialize when host is started (which should not occur is you start by way of the server or it is a bug).

**Comment by parherman** [comment]
When CycleTime test fails it will properly fail the build now that issue #2674 is fixed. Since it fails every now and then have been doing so for some time I will disable it until we can determine if its a problem with the test or a legitimate issue.

**Comment by parherman** [comment]
ScErrTransLogWriterNotAvailable happens outside of CycleTime also:

[During 3LevelSchemaChange test](https://scbuildserver/viewLog.html?buildId=27703&buildTypeId=Starcounter_DevelopNightly&tab=buildLog#_focus=5397)

[During Star.exe loop test](https://scbuildserver/viewLog.html?buildId=27669&buildTypeId=Starcounter_DevelopNightly&tab=buildLog#_focus=2559)

**Comment by parherman** [comment]
@eriohl Star.exe loop test is a bat file that runs this in a loop:

```
star.exe s\NetworkIoTest\NetworkIoTest.exe DbNumber=1 PortNumber=8080 TestType=MODE_NODE_TESTS
```
[link to src](https://github.com/Starcounter/Starcounter/blob/develop/src/Server/sccli/star_loop_test.bat)

Do we need to run staradmin kill all before we run star.exe again to kill scdblog?

**Comment by k-rus** [comment]
@dan31 or @eriohl 
Is it reasonable to postpone investigation of the issue until pnext is merged to next?

**Comment by k-rus** [comment]
> @dan31 or @eriohl 
> Is it reasonable to postpone investigation of the issue until pnext is merged to next?

No. The problem is also in develop. See [this build](https://scbuildserver/viewLog.html?tab=buildLog&buildTypeId=Starcounter_DevelopNightly&buildId=27703).
It looks like that someone did changes that affected Level1 to not work correctly with the kernel.

**Comment by dan31** [comment]
@per-samuelsson, WDYT? Something with signaling between parties on a startup sequence?

**Comment by per-samuelsson** [comment]
> @per-samuelsson, WDYT? Something with signaling between parties on a startup sequence?

Not sure, since I haven't even seen this issue. But maybe. I have noticed that quite often, signaling between the admin server and the data process (```scdata.exe```) doesn't work in a predictable, expected way, so maybe it's something there. I have tried to the best of my ability to figure out how it is possible to monitor/wait related processes (i.e. ```scdata.exe``` and, later added, ```sclogwriter.exe```, but it havent been very straight-forward).

If you want me to switch to investigate this, just let me know.

**Comment by parherman** [comment]
Just a note that DevelopNightly failed whit ScErrTransLogWriterNotAvailable during TestClassSchemaChange test, [log](https://scbuildserver/viewLog.html?buildId=28333&buildTypeId=Starcounter_DevelopNightly&tab=buildLog#_focus=5447)

**Comment by k-rus** [comment]
Is it still valid?

**Comment by alemoi** [comment]
I will check the build history to make a verdict.

**Comment by per-samuelsson** [comment]
I'm guessing this one no longer apply. Closing.
