### ISSUE TITLE
Access violation in NEXT when starting application

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2679]
This was reported in this https://github.com/Starcounter/Starcounter/issues/2671#issuecomment-93947135, but we were not able to reproduce it.

> [16:12:13, Critical, Starcounter (default)]
Access violation (C0000005) detected at C:\BuildAgent\work\sc-2.0.637.7\Level0\src\sccoredb\export\sccoredb.cpp:3649 (Thread 5016).

Now I have found the pattern to repoduce:

> star -d=foo heads.exe
> staradmin kill all
> star -d=foo heads.exe

After I do a first, rude "kill all", the problem persist until I delete the database. If I instead stop the db gracefully (or restart it), the AV does not show.

I will investigate more exactly where it occurs.

**Comment by per-samuelsson** [comment]
> I will investigate more exactly where it occurs.

I'm really not getting anywhere with this unfortunally. I can constantly reproduce it if I download a nightly version - I've tried both debug- and release build distributions - but I can not get it to reproduce while I'm building a version locally.

I have reached as far as that I now know it occurs somewhere in the scope of ```sccoredb.sccoredb_connect```, but I still don't know the reason (and neither if its bad input or a flaw in the Level0-implementation).

I'll pause this for now, but we need to eventually solve it of course.

**Comment by per-samuelsson** [comment]
Just found #2634, looks like they two are pretty much the same.

**Comment by eriohl** [comment]
Why no stack trace? Are you just not publishing it or are you using a distribution without PDB files or something and not getting one?

**Comment by per-samuelsson** [comment]
Closing this since NEXT is discontinued.
