### ISSUE TITLE
Turn OntologyMap on/off

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2680]
Can there be an API to disable ontology maps?

I would like to be able to turn maps defined by `Polyjuice.OntologyMap` on and off in the runtime (throught a JSON handler).

This is useful for demos and debugging.

**Comment by warpech** [comment]
I reviewed the changes and it works great! I can use it as it is for my planned demo.

Just three minor issues for future consideration:

1. The REST interface works on app port (8080), but not on admin port (8181). Therefore it is not possible to control it from Administrator if the database is not running. Also, given that the setting is per system, not per database, shouldn't it only listen on port 8181?

2. `/Polyjuice/MappingTrigger ` and `/Polyjuice/OntologyMappingTrigger` work as expected. `/Polyjuice/MiddlewareFiltersTrigger ` though, seems to disable three things: filters, maps and ontology maps. Shouldn't it only disable filters?

3. For correct REST interface, GET verb should not change the flag. GET should return the current setting and POST should change the flag.

**Comment by alemoi** [comment]
Thanks for review!

1. Yes, I was thinking to make it 8181, but needed more opinions. So now will probably change that!

2. Should only do the middleware filters. I think the behavior you get is because there is no Launcher wrapping HTML that collects and shows all partials. Let's discuss that!

3. Agree and thought about that :) For now just made it so its easier to execute from browser. Will change it to POST.

**Comment by warpech** [comment]
I created some scripts to control the mapping: https://github.com/Polyjuice/Tools/blob/master/scripts

I used `curl` to make the HTTP requests. Is there some way to change it to use `star` or `staradmin` for those who don't have `curl` installed?

**Comment by alemoi** [comment]
Ok, I refactored the handlers, here is the new list:
```
GET	/__default/mappingflag
POST	/__default/mappingflag/@b
GET	/__default/middlewarefiltersflag
POST	/__default/middlewarefiltersflag/@b
GET	/__default/polyjuice/ontologymappingflag
POST	/__default/polyjuice/ontologymappingflag/@b
```
As you can see the flags are set per-codehost. Ontology mapping is for Polyjuice only, that's why its perefixed.

> I used curl to make the HTTP requests. Is there some way to change it to use star or staradmin for those who don't have curl installed?

I usually use Chrome REST plugin, but curl seems fine!

**Comment by warpech** [comment]
Using nightly 3132 and database "default", it seems to not work for me:

```
c:\PolyjuiceProjects\Polyjuice\Tools\scripts>curl -X GET http://localhost:8080/__d
efault/mappingflag
Error 404: File /__default/mappingflag. not found

c:\PolyjuiceProjects\Polyjuice\Tools\scripts>curl -X POST http://localhost:8080/__
default/mappingflag/true
URI not found: POST /__default/mappingflag/true

c:\PolyjuiceProjects\Polyjuice\Tools\scripts>curl -X POST http://localhost:8080/__
default/polyjuice/ontologymappingflag/false
URI not found: POST /__default/polyjuice/ontologymappingflag/false
c:\PolyjuiceProjects\Polyjuice\Tools\scripts>
```

Ideas?

**Comment by alemoi** [comment]
> Ideas?

Yes :) You are using port 8080, it should be 8181.

**Comment by warpech** [comment]
Works perfect, thanks!

**Comment by warpech** [comment]
The flags are now reset whenever an application is started (or restarted). To make this feature usable, it needs to persist during server restarts. Can this value be stored in config?

**Comment by alemoi** [comment]
Yes, I'm thinking to store it inside database config, like the Polyjuice flag that will be there. I will make it work after a short vacation!

**Comment by dan31** [comment]
Isn't that something solved already?

**Comment by warpech** [comment]
Yes it is solved. Remaining part is to describe it: https://github.com/Starcounter/Starcounter/issues/2743
