### ISSUE TITLE
DbSession add return value

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2681]
Hi!

Might I suggest adding the same signature for RunSync as Transaction.Scope. So that you don't have to use temp variables to store return values from Transactions.

It would then be possible to skip temp variables like the example below.

Temp variable needed today:
````
public bool MyBool()
        {
            bool b = false;
            new DbSession().RunSync(() =>
            {
                using (var t = new Transaction(false))
                    b = t.Scope(() => true);
            }
            return b;
        }

````

With improved signature:
````
public bool MyBool()
        {
            return new DbSession().RunSync(() =>
            {
                using (var t = new Transaction(false))
                    return t.Scope(() => true);
            }
        }

````

**Comment by careri** [comment]
No input on this?

**Comment by dan31** [comment]
Hi @careri! There is a similar issue https://github.com/Starcounter/Starcounter/issues/2822, but you know it already, as I see your comment there :) Yes, we see a consistent way to improve that part and we are going to do it in future releases. Can't tell you more precisely, just show that we hear the inquiry.

**Comment by careri** [comment]
Sorry, though this issue looked familiar :)
You can close this one then

**Comment by careri** [comment]
Looking forward to the improvements.

**Comment by dan31** [comment]
@chrhol, we found that we don't have a means to do it for ```RunAsync```. Do you think we can offer it for ```RunSync```, similar to what we intend for #2822?

**Comment by chrhol** [comment]
The current API does not use DbSession anymore so there is no good way currently to add this kind of behaviour, and since we cannot fully support it it feels better not to implement anything extra. 

In later versions of Starcounter we will implement scheduling in a more task-like manner, and add support for async/await pattern.
