### ISSUE TITLE
Request hangs forever on type mismatch between properties in Json and Data

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2682]
If I define a JSON message Foo.json as follows (with or without code-behind):

    {
        "Bar": 4711
    }

And set up a simple GET handler like so:

    Handle.GET("/FooApplication/Foo", () =>
    {
        return new Foo() { Data = new { Bar = "4711" } };
    });

A GET request to /FooApplication/Foo seems to hang forever, without any error message. Notice that according to the JSON example, "Bar" has type integer, but in the object passed to Data it has type string. Fixing either to match the other resolves the problem.

Tested with Starcounter v2.0.3127.3.

**Comment by chrhol** [comment]
I totally missed this one, sorry about that.

There is an exception thrown and logged, but it looks like it's not correctly handled (or handled too late on the server) so no response is sent back to the client.

I will put it on me to fix.

Logged exception: 
```
System.Exception: ScErrCreateDataBindingForJson (SCERR14006): Cannot create binding between typed json and dataobject. Incompatible types for binding. Json property 'Foo.Bar' (System.Int64), data property '<>f__AnonymousType0`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Bar' (System.String).
...
```
