### ISSUE TITLE
Cannot recreate database by the same name

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2684]
I had a db called `default`. I stopped it, deleted it and wanted to start a new one by the same name.

I get an error:

```
ScErrUnexpectedCommandException (SCERR10016): Creating database default failed due to an unexpected problem.
Version: 2.0.3131.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Starcounter.Server.DatabaseSetup.CreateFiles() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3131.3\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 124
   at Starcounter.Server.DatabaseSetup.CreateDatabase() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3131.3\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 134
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3131.3\Level1\src\Server\Starcounter.Server\Commands\Processors\CreateDatabaseCommandProcessor.cs:line 31
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3131.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2147024713
```

Is this by design? I tried this many times before and it worked.

Killing the server and restarting it does not help.

**Comment by per-samuelsson** [comment]
> Is this by design?

Absolutely not. :cry:

Questions:

1. What version is this - **next** or **develop**?
2. How did you proceed when you deleted the database? ```staradmin delete db```?
3. Can you run ```staradmin list db``` to see what databases Starcounter consider exist?

Thanks.

**Comment by warpech** [comment]
1. develop, build 2.0.3131.3 (current nightly)
2. I deleted it using the Administrator GUI
3. `staradmin list db` produces output `No databases found`

Deleting the files from my database folder fixes the problem. Should I keep the state for further investigation?

**Comment by per-samuelsson** [comment]
> Deleting the files from my database folder fixes the problem.

What files did you delete to solve it? The image/transaction logs in the under the **Data** hive (assuming you are using default settings)?

> Should I keep the state for further investigation?

Well, I guess no. Lets try to just keep an eye on this to see if we can get it to appear again, so I can take a look at it while it actually happens. I'm gonna do some quick tests to see if I can provoke it too.

**Comment by warpech** [comment]
On my disk there are still both folders:

```
C:\db\Personal\Data\Default
C:\db\Personal\Databases\default
```

Deleting `Data\Default` manually did not help. Deleting `Databases\default` helped.

======

Please note that not only it was impossible to create a database from the Administrator, but also when starting an app:

```
c:\PolyjuiceProjects\Polyjuice\Launcher>run.bat
Launcher -> default (creating database)

[15:01:47, Starcounter.Server.Commands (scadminserver)]
ScErrServerCommandFailed (SCERR10011): The operation "Creating database default" f
ailed.
Version: 2.0.3131.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.

[15:01:47, Starcounter.Server.Commands (scadminserver)]
ScErrUnexpectedCommandException (SCERR10016): Creating database default failed due
 to an unexpected problem.
Version: 2.0.3131.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, B
oolean checkHost)
   at Starcounter.Server.DatabaseSetup.CreateFiles() in c:\TeamCity\TeamCity8\buil
dAgent\work\sc-2.0.3131.3\Level1\src\Server\Starcounter.Server\CoreServices\Databa
seSetup.cs:line 124
   at Starcounter.Server.DatabaseSetup.CreateDatabase() in c:\TeamCity\TeamCity8\b
uildAgent\work\sc-2.0.3131.3\Level1\src\Server\Starcounter.Server\CoreServices\Dat
abaseSetup.cs:line 134
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in c:\T
eamCity\TeamCity8\buildAgent\work\sc-2.0.3131.3\Level1\src\Server\Starcounter.Serv
er\Commands\Processors\CreateDatabaseCommandProcessor.cs:line 31
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandSta
tusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgen
t\work\sc-2.0.3131.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcesso
r.cs:line 300
HResult=-2147024713
```

**Comment by warpech** [comment]
This just happened again.

Database was deleted in Adminstrator and then tried creating it again from VS.

Starcounter 2.0.3233.3

Should I provide more details? I fill freeze development for few minutes

Screenshot:

![image](https://cloud.githubusercontent.com/assets/566463/8376461/d9683538-1c07-11e5-8274-a992a073aad2.png)

**Comment by per-samuelsson** [comment]
> This just happened again.

Argh. Lets try solving it together. I'll contact you to get some environment.

**Comment by per-samuelsson** [comment]
I'm quite confident now that I've found the reason for this. It seems to be caused by recent playlist-functionality added to the administrator, and that files remain in the database specific server repo even after it being deleted.

WTBS, I'm not 100% on how to deal with it. The question is basically if app-related stuff should stick around for a database when it's deleted or not. I think I can solve it quite easily if we decide it should - I'll just watch for all database-specific files to be properly deleted, and treat that as a successfull delete if they are all gone.

I will revise this again tomorrow and consider it some more. I think we can have a final solution after some short discussion where we need to decide the semantics, and then adapt o that. Its probably not more than like half a day to fix once decided.

**Comment by per-samuelsson** [comment]
Pausing this until we have taken decisions as formulated in #2786.

**Comment by warpech** [comment]
What is the status of this? It still happens

**Comment by per-samuelsson** [comment]
> What is the status of this? It still happens

AFAIK, nothing has been done to resolve it. It's still caused by how playlists where implemented. In #2786, I see there are different voices with different opinions. We can't solve it until there is a final decision on the desired semantics.

**Comment by dan31** [comment]
Okay, they key thing there to balance is that we cannot give a lot of technical debt to 2.0 in order to focus on new version development. In the nearest future @k-rus won't allocate time to investigate old SQL layer, since we are working intensively on delivering a new one. Basing on this, we can simply assume now: there is no easy way to have a feature to clean the database in 2.0 without deleting it. What options are we left with to improve the current feature? Remove apps with the database? Change how playlists are done? @andwah, maybe you can give a coin?

**Comment by per-samuelsson** [comment]
> Okay, they key thing there to balance is that we cannot give a lot of technical debt to 2.0 in order to focus on new version development. In the nearest future @k-rus won't allocate time to investigate old SQL layer, since we are working intensively on delivering a new one. Basing on this, we can simply assume now: there is no easy way to have a feature to clean the database in 2.0 without deleting it.

This is a good decision. I fully support it.

>  What options are we left with to improve the current feature? Remove apps with the database? Change how playlists are done? @andwah, maybe you can give a coin?

Lets see what @andwah says. For me, I can do either, in a couple of hours I think, maybe half a day. That is, either a) make sure all apps are deleted when the database is deleted, or b), preserve apps installed in the database (and they will thereby be avaibable again if/when a database with the same name is recreated).

Personally, I vote for going with (a) in 2.x, and then we can reconsider in future versions if this makes a problem.

Both (a) and (b) solutions would solve @warpech problem in the OP.

**Comment by andwah** [comment]
> a) make sure all apps are deleted when the database is deleted, or b), preserve apps installed in the database (and they will thereby be avaibable again if/when a database with the same name is recreated).

Ill also vote for option (a).   

Apps is like your personal installed programs in windows, if you reinstall windows yours programs will be gone.

**Comment by warpech** [comment]
:+1: Totally agree with @andwah

**Comment by per-samuelsson** [comment]
> Totally agree with @andwah

Good. Then the 3 of us agree, and I think @dan31 does too. Let's go this way. 

Can you adapt the playlist/AppStore implementation to this, @andwah? Or will you need my help? Or do you even want me to do it?

**Comment by andwah** [comment]
> Can you adapt the playlist/AppStore implementation to this.

Sure i can, no problem.  I will make sure that when a database is deleted (via REST) it will also delete the (installed) Applications and the configuration file that is associated with the applications.

**Comment by andwah** [comment]
Resolved.
See 3c97cad21aad06cfd14644ddaabc4801c2ede2fc

**Comment by warpech** [comment]
I confirm that fix works :)
