### ISSUE TITLE
Local build fails on metadata population

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2686]
Since like 2 days, I can not run a standard, "development setup" local build of Starcounter.

I'm using the **develop** branch. I'm starting completly fresh (or at least try to do so):

1. I delete ```Level1\bin``` directory.
2. I delete the server repo completely (i.e. ```Starcounter``` under documents)
2. I build Level1 (with ```LEVEL0_CONFIGURATIOn=Release``` set).
3. I install using ```Starcounter-Setup.exe```, specifying that it should install using the path to ```Level1\bin```. 

Then, with the simplest application possible, I do

> star app.cs

and I get this every time

![image](https://cloud.githubusercontent.com/assets/2902045/7251614/4b8c10b2-e82d-11e4-815f-b471e53f8e4d.png)

If I step into the code, this assert fails:

```C#
Starcounter.Metadata.Column rawCol =
Db.SQL<Starcounter.Metadata.Column>(
  "select c from column c where c.table = ? and name = ?",
  theView.Mapper,
  propDef.ColumnName).First;
Debug.Assert(rawCol != null);
```

The name of the mapper is "materialized_table" and the column name is "base_table". I just can't understand what it is causing this...? Any help highly appreciated!

**Comment by k-rus** [comment]
The problem looks like mismatch between meta-data implementation versions. May be cleaning and re-building all three solutions (in develop) will help.
When I switch between develop and next, I always clean the solution files and re-build the projects. I don't have any build automation such as building Level1 builds Level0. I use solution files of Level0, SqlProcessor and Level1 in develop, and cmake for Level0, which includes SqlProcessor, and solution file for Level1.

**Comment by per-samuelsson** [comment]
> The problem looks like mismatch between meta-data implementation versions.

Yeah, that was my initial suspicion. That automating builds from Level1 especially works really poorly when you switch between develop and next branches. And even more so when we have introduced cmake that builds some parts (I think).

Anyway, after our discussions, I now followed the following procedure:

```
Open Blue.sln
Assure you have the corresponding Configuration (e.g. Debug, Release)
Build | Clean
Build | Build
Close Blue.sln

Open SqlProcessor.sln
Assure you have the corresponding Configuration (e.g. Debug, Release)
Build | Clean
Build | Build
Close SqlProcessor.sln

Open Level1.sln
Assure LEVEL0_CONFIGURATION=[Configuration] is set to your preference
Build | Clean
Build | Build
Then build AGAIN (the first time will fail)
```

This did still **not** solve the problem (the same assertion still applies), so I guess the procedure have to be further extended. I will keep experimenting.

Thanks for all the input, @k-rus. Now I at least know about this, and that I must be careful. The problem is o/c its very time consuming, since my workweek normally will contain several switches between the two branches (including running applications on both).

**Comment by per-samuelsson** [comment]
After I retried the above, and added a few more manual deletions of directories, now I finally was able to successfully load an application.

For future reference, here's what was needed to switch from **next** to **develop** (and, I assume, the opposite):

```
Delete Level0\msbuild\x64
Delete Level0\msbuild\SqlProcessor\x64
Delete Level1\bin\[Level1_Configuration]

Open Blue.sln
Assure you have the corresponding Configuration (e.g. Debug, Release)
Build | Clean
Build | Build
Close Blue.sln

Open SqlProcessor.sln
Assure you have the corresponding Configuration (e.g. Debug, Release)
Build | Clean
Build | Build
Close SqlProcessor.sln

Open Level1.sln
Assure LEVEL0_CONFIGURATION=[Configuration] is set to your preference
Build | Clean
Build | Build
Then build AGAIN (the first time will fail)

Open Level1\bin\[Level1_Configuration]\Configuration\Personal.xml and
adjust <server-dir> to the correct server repository folder
(normally c:\Users\[User]\Documents\Starcounter\Personal\)
```

**Comment by alemoi** [comment]
Honestly I would go crazy if I would have to do such procedure :) Maybe its better to keep totally separated folders for `next` and `develop` Starcounter and just switch the `StarcounterBin` env var using SETX script when needed?

**Comment by per-samuelsson** [comment]
> Honestly I would go crazy if I would have to do such procedure :)

Believe me, I do too! :camel: 

> Maybe its better to keep totally separated folders for next and develop Starcounter and just switch the StarcounterBin env var using SETX script when needed?

Yeah, like you suggested yesterday. I'm actually gonna try that. It will require a little time to set it up I guess, but if it works, it will be a lot less hazzle in the long run.

**Comment by per-samuelsson** [comment]
> ... just switch the StarcounterBin env var using SETX script when needed?

This particular thing works, but with a flaw: it doesn't update the PATH (so that star.exe, staradmin.exe, etc are correctly resolved). I'm testing a procedure where I will instead always do an uninstall/install everytime I switch from one branch to the other (with a *dummy.sci* in each installation folder, so that binaries are not deleted).

**Comment by per-samuelsson** [comment]
> I'm testing a procedure where I will instead always do an uninstall/install everytime I switch from one branch to the other (with a dummy.sci in each installation folder, so that binaries are not deleted).

This seem to work. I know have two isolated hives with a clone of all repos in each, and hence a duplicate set of binaries/installation directories. So far, I haven't found any problem.

Now, when I'm switching between a branch based on next to a branch based on develop, the procedure I need to take is:

```
Delete all databases (or specify branch-specific names always)
Run "staradmin kill all"
Close any prompt
Close an VS instance
Uninstall Starcounter
Install Starcounter (using custom, development-machine input)
```

Still not perfect, but at least more predictable than the older procedure.
