### ISSUE TITLE
Query on RawView.AutoTypeInstance with filter yield no hits

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2689]
I'm doing a query such as this:

``` C#
var views = Db.SQL<RawView>("SELECT rw FROM RawView rw WHERE rw.AutoTypeInstance > ?", 0);
foreach (var item in views) {
  Console.Write("Hello");
}
```

The Hello never prints.

On the same data, I then do this:

``` C#
var views = Db.SQL<RawView>("SELECT rw FROM RawView rw");
foreach (var item in views) {
  if (item.AutoTypeInstance > 0) {
      Console.Write("Hello");
  }
}
```

and I now get the expected number of hits.

I've shown this to @k-rus and I can reproduce it every time. I have only tested it in **next**.

**Comment by per-samuelsson** [comment]
If it can be of any help, equality operations **do** work. On the same data set as I use in the original post I can do:

```C#
Db.SQL<RawView>("SELECT rw FROM RawView rw WHERE rw.AutoTypeInstance = ?", oid);
```

where ```oid``` is a key in the top of the ulong-range, and I get a hit.

**Comment by k-rus** [comment]
Thank for reporting! I will look into it, which is basically by stepping into execution of the failed query.

**Comment by k-rus** [comment]
By the way it has nothing to do with new query processor (NewSQL), since it is not in place yet.

**Comment by k-rus** [comment]
@per-samuelsson Can you provide code to create initial data with auto created types? Some simple example.

**Comment by k-rus** [comment]
Meta-schema is different now and the column under issue does not exist. Closing
