### ISSUE TITLE
DEF files as part of VS solution files

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2692]
cmake generates VS solution files for Level0 in branch next. However, it does not include `.def` files, which contain public shared API. Thus it is inconvenient to update these files, when corresponding changes done in C files through VS. I think it is good idea to include such files solution with appropriate properties.
Is it a good suggestion? Can it be done?

**Comment by eriohl** [comment]
DEF files has been replaced with pragmas in header files kernel shared libraries. Only works with MSVC.

**Comment by parherman** [comment]
Its looks like the generator is filtering .def files from vs projects for some reason: Will investigate best solution, possibly removing def files entirely

**Comment by parherman** [comment]
Replacing def files I mean

**Comment by k-rus** [comment]
DEF files are not used any more.
