### ISSUE TITLE
Are there any Starcounter.Json/Page life events?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2697]
Are there any life circle events in `Starcounter.Json` or `Starcounter.Page`, or any other way to execute some code when ViewModel unloaded.

The feature I want to implement:

1. User opens New image page.
2. User drags an image and uploads it.
3. User closes the page without saving the image, or navigates to another page without saving the image.
4. **Uploaded file deleted**.

How to do this?

**Comment by warpech** [comment]
In that case, the transaction is aborted, so wouldn't it be possible to use Illustration object `OnDelete` method?

@dan31, what is the way to go in your opinion?

I sense a problem to do that since Illustration is defined in Simplified.dll, but that problem should be gone when we have mapping.

**Comment by dan31** [comment]
Good question! We'll take tomorrow with @per-samuelsson.

**Comment by miyconst** [comment]
@dan31, @per-samuelsson, is there any solution for the issue?

**Comment by dan31** [comment]
BUMP me :) @per-samuelsson, @chrhol, WDYT?

**Comment by chrhol** [comment]
There is nothing implemented for this today. At least not in TypedJson.

A similar problem that we have briefly mentioned is that we need to solve save/cancel behaviour for several apps. Maybe this is the same thing. We need to have some way to let all partials get a callback/event when certain things are happening, like save or cancel/close.

Then the image-app should expose a Close for itself where the image can be deleted.

The only thing I can find about it is in [this comment](https://github.com/Polyjuice/Polyjuice/issues/13#issuecomment-83436739), first point, from @andwah.

**Comment by miyconst** [comment]
@chrhol, will there be any solution soon or just leave Images app as is?

**Comment by warpech** [comment]
I think this could be solved not with Json lifecycle but with Database commit hooks. @per-samuelsson is there any commit hook that is executed when a transaction is aborted (due to cancellation or timeout)?

PS. Commit hooks are available in `next` branch of Starcounter at the moment.

**Comment by per-samuelsson** [comment]
>  @per-samuelsson is there any commit hook that is executed when a transaction is aborted (due to cancellation or timeout)?

Nope. And as opposed to commit hooks, this feature we've never supported (where commit hooks have been supported in previous versions).

**Comment by warpech** [comment]
I guess [`OnDelete`](https://github.com/Starcounter/Starcounter/blob/c9e45aaf07b091786f1aa8376ff9c41899f60339/src/Starcounter/IEntity.cs) method is not called in such case either? Any other ideas?

**Comment by per-samuelsson** [comment]
> Commit hooks are available in next branch of Starcounter at the moment.

With #2754 pushed, its also available in 2.0.

**Comment by miyconst** [comment]
Closing this issue as no longer relevant.
