### ISSUE TITLE
Parallel, hangs

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#270]
Hey!

I wrote a question at stackoverflow, since I thought did had something to do with detached threads to do. But now I'm not so sure, maybe it's a bug?

Do I need to run a detached thread to use the PTL?
Using it has rendered some strange results, first as mentioned in the question it newer completes. Another strange behaviour was not completing the loop and continueing. So I didn't get all my items itterated.

Switching to plain foreach itterations without PTL works just fine.

Here's the post:
http://stackoverflow.com/questions/16215738/starcounter-parallel

/Carl

**Comment by dan31** [comment]
Currently in 2.x we interleave the use of .NET tasks and SC tasks with ```ScheduleTask``` API (http://starcounter.io/guides/transactions/running-background-jobs/). Basically you nest one from another. In 3.x there are no more Starcounter tasks, all Starcounter jobs are done on regular .NET tasks.
