### ISSUE TITLE
Polyjuice installation and Starcounter installation must be equal

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2703]
InvoiceDemo and Polyjuice demo apps should be runnable in Starcounter installer.

This includes usage of `Polyjuice.Map`, `Polyjuice.OntologyMap` as well as making use of data models defined in Polyjuice.dll and Simplified.dll.

Polyjuice installer will include additional *user* features over the Starcounter installer, but the developer tools and libraries should be the same.

@dan31, @Starcounter-Jack can you confirm?

**Comment by dan31** [comment]
My strong belief that we must make Polyjuice be non-intrusive. Starcounter is a "2x2=4" thing, while Polyjuice, Ontology, SocietyObjects and other things with rapidly changing definitions and use cases are "commutative algebra, grade 4". InvoiceDemo and all other demos should show "2x2": plain html-s in Client and no mapping and ontologies. Dev people get that story in one click. We cannot loose that beautiful simplicity by excusing us to first explain commutative algebra and then moving to 2x2. That is a hassle.

Polyjuice runs on Starcounter. It means that those who aren't using Polyjuice-specific features, shouldn't be disturbed by them. Now it isn't the case, and we continue to mess things for those who migrate to newer versions of Starcounter. We stop simple things working for them because we change our mind about Polyjuice. Unfortunately, we don't run all demos got from repos as acceptance tests, I believe it is a good time to do that.

So, tell me if it is wrong about keeping Polyjuice non-intruding into Starcounter, otherwise let's follow that guideline. Then, we must take care that:
1) There is a single installer,
2) Which has Polyjuice bits and all APIs needed,
3) But having Polyjuice there doesn't disrupt pure Starcounter experience.

About InvoiceDemo, as I understand InvoiceDemo3 will actually appify InvoiceDemo2, and there we will see all the Polyjuice way, adding needed mappers etc. Mapping will essentially become a part of Starcounter, because it is a beautiful way to develop independent and well-mixable applications.

**Comment by per-samuelsson** [comment]
> My strong belief that we must make Polyjuice be non-intrusive. Starcounter is a "2x2=4" thing, while Polyjuice, Ontology, SocietyObjects and other things with rapidly changing definitions and use cases are "commutative algebra, grade 4". InvoiceDemo and all other demos should show "2x2": plain html-s in Client and no mapping and ontologies. Dev people get that story in one click. We cannot loose that beautiful simplicity by excusing us to first explain commutative algebra and then moving to 2x2. That is a hassle.

For what it's worth, this is one of those few things I feel kind of strong for. I couldn't agree more.

**Comment by warpech** [comment]
I agree as well. But the developer that learns how to mix apps must have a smooth learning experience from 2x2=4 to "commutative algebra, grade 4".

The new InvoiceDemo tutorial is divided into 3 parts:

- **InvoiceDemo1** - show a single invoice with rows, computed totals and buttons: Add Row, Save and Cancel
- **InvoiceDemo2** - add a list of invoices, Delete button, partial templates and URL morphing
- **InvoiceDemo3** - integrate your app with another apps running in the database

Theoretically, I could invite the developer to run InvoiceDemo1 and 2 in the "Starcounter edition", and then install "Polyjuice editon" to run InvoiceDemo3, but where's logic in that? Starcounter is the application platform so it must support app mixing with zero config in the normal installation.

If I have to choose one installer to be available on the new starcounter.io, it will be "Polyjuice edition", which is the only one that can run InvoiceDemo and Polyjuice sample apps.

---

To go into detail of the particular problem with InvoiceDemo, I tried to be able to mix it with another apps as well as respond to `/` URL. This is only possible in the "Polyjuice edition" with the use of `Polyjuice.Map`. 

**As an immediate fix, I will change the InvoiceDemo to use `/invoicedemo` URLs, which work in both editions.**

On a similar note, running [Hello World](https://github.com/Starcounter/Starcounter/wiki/Responding-to-a-request) example in "Polyjuice edition" throws an error if the app is not called `hello.exe`:

> Polyjuice applications can only register handlers starting with application name prefix, for example, /myapp/foo

I have a strong preference to use `/` url in the demos, because I have rarely seen a "Hello World" for a web framework that would not use that URL. Compare:
- frameworks that use `/` in Hello World: [Sinatra](http://www.sinatrarb.com/intro.html), [ExpressJS](http://expressjs.com/starter/hello-world.html)
- framework that uses `/HelloWorld/Welcome/Scott/3` in Hello World: [ASP.NET](http://www.asp.net/mvc/overview/getting-started/introduction/adding-a-controller)

---

A possible solution could be to dynamically switch to Polyjuice mode when a first app tries to use a Polyjuice feature. If some other apps that are already running are violate Polyjuice rules, this would show an exception "Cannot start 'People' because another app ('Hello World') is violating Polyjuice rules". @alemoi WDYT?

**Comment by dan31** [comment]
> I agree as well. But the developer that learns how to mix apps must have a smooth learning experience from 2x2=4 to "commutative algebra, grade 4".

Exactly! That's one of major prios for us all, to make it more like 2*2 :)

> Starcounter is the application platform so it must support app mixing with zero config in the normal installation.

Absolutely agree. I believe it should be easily configurable. As a developer, I want to build my stuff the Polyjuice way as well: like an ISV who builds stuff in-house. It should be a switch: if I want to do that way, I just do that without reinstallations, on the platform. If I want to run my hardcore UDP streamer and nice Polyjuice mashup together – I shouldn't install 2 SC for that (today it's not likely possible). So it should be either per-database config, or even simpler.

> A possible solution could be to dynamically switch to Polyjuice mode when a first app tries to use a Polyjuice feature. If some other apps that are already running are violate Polyjuice rules, this would show an exception "Cannot start 'People' because another app ('Hello World') is violating Polyjuice rules".

Very good thinking. I believe it shouldn't be either/or from installer prospective. Perhaps per-database config is a good choice (and you can click that in installer as well)? If so, the same will apply to "poorman's mapper", we discussed that with @per-samuelsson already. That mapper won't be needed in non-app scenarios, and can be turned on/off by a DB config.

**Comment by alemoi** [comment]
Here is the info about database Polyjuice flag: http://starcounter.io/nightly-changes/polyjuice-database-flag/
Since now installations are equal and flag is added on per-database level which seem to work fine, should we close the issue?

**Comment by careri** [comment]
So what are you saying, to fix the my project that's suffering from (Starcounter Edition):
Polyjuice applications can only register handlers starting with application name prefix, for example, /myapp/foo

I'm not using Polyjuice, so I would really like to keep using my simple urls. Do I need to prefix them with  the name of the application?

**Comment by alemoi** [comment]
> I'm not using Polyjuice, so I would really like to keep using my simple urls. Do I need to prefix them with the name of the application?

Only if you are using a Polyjuice database in any edition (`PolyjuiceDatabaseFlag` equals to `true`) you will have to prefix your handlers. If you have `PolyjuiceDatabaseFlag` equals to `false` URLs can stay arbitrary.

**Comment by careri** [comment]
I'm running Starcounter Edition: 2.0.3183.3
I get the error, where is this flag stored?

**Comment by careri** [comment]
If I look in the Default.Db.Config the flag is set correctly:

    <PolyjuiceDatabaseFlag>false</PolyjuiceDatabaseFlag>

But I'm launching the debugger with a custom database name:

    --d=HAD --name=HAD

And that config sets the flag to true, even though I'm running Starcounter Edition:

    <PolyjuiceDatabaseFlag>true</PolyjuiceDatabaseFlag>

For now I can just revert to the default database

**Comment by careri** [comment]
I can confirm that using the default database works as expected

**Comment by alemoi** [comment]
> I can confirm that using the default database works as expected

Good! Please let us know if you still experience any issues with this.

**Comment by k-rus** [comment]
> But I'm launching the debugger with a custom database name:
> 
> --d=HAD --name=HAD
> And that config sets the flag to true, even though I'm running Starcounter Edition:
> 
> <PolyjuiceDatabaseFlag>true</PolyjuiceDatabaseFlag>
> For now I can just revert to the default database

I guess the issue is not resolved. @alemoi  can you look if flag works correctly in the case of non-default database?

**Comment by per-samuelsson** [comment]
> I guess the issue is not resolved. @alemoi can you look if flag works correctly in the case of non-default database?

From @careri's reply, it seems that by default, a newly created database, created "on the fly", gets the polyjuice-flag set to **true**. This must be wrong in any non-Polyjuice edition.

Also, note that there was a bug in the implementation of the polyjuice flag, that I tracked down and fixed yesterday: #2729. When testing, make sure to test on a version built *after* this bug was resolved.

**Comment by per-samuelsson** [comment]
> From @careri's reply, it seems that by default, a newly created database, created "on the fly", gets the polyjuice-flag set to true. This must be wrong in any non-Polyjuice edition.

I did a simple test, like ```star -d=Test empty.cs``` on a version I built from sources yesterday afternoon, and it set the polyjuice flag to **false**, i.e. the correct behaviour. So either I did something different from @careri, or my environment is not the correct. Or #2729 fixed the problem.

@careri, can you grab the latest version (built tonight) and try just using an empty app like this:

```C#
using Starcounter;
using System;

class Program {
    static void Main() {
        Console.WriteLine("{0} starting...", Application.Current);
    }
}
```

Put it some Foo.cs file and run it like ```star -d=DbThatDoesNotExist foo```, and then check the config flag of the DbThatDoesNotExist database. Thanks!

**Comment by careri** [comment]
That seems to be working without installing the latest version. I probably forgot to recreate the HAD database. Sorry

**Comment by per-samuelsson** [comment]
> That seems to be working without installing the latest version. I probably forgot to recreate the HAD database. Sorry

No worries! Thanks for helping us tracking down these things. And let us know if there are anything else that seems weird or doesn't work like you expect regarding this!

Should we close this issue for now? I couldn't find any more work that needed to be done while reading it through...

**Comment by warpech** [comment]
Before closing, I would like to get a confirmation that Polyjuice Edition installer is sufficient as the only installer linked on for http://starcounter.io/download/

Polyjuice Edition is the only one that has the correct default settings to run the sample apps.

**Comment by warpech** [comment]
cc @dan31

**Comment by dan31** [comment]
The main problem now is following: if I install Polyjuice edition, I cannot run simple demos because of URI restrictions. @alemoi, would it be possible to activate the polyjuice db flag dynamically just once polyjuice features are observed in one of the apps running in the database?

**Comment by alemoi** [comment]
Probably its possible but we have to detect this before the application `Main()` is called.

**Comment by alemoi** [comment]
But I don't really see it as a big problem as long as its 1 button click in Administrator.

**Comment by warpech** [comment]
It doesn't seem like much, but it makes a significant difference. Because of the flag, the developer needs to learn that Administrator exists. It would be good to have no reason for asking developers to go to the Administrator - it should be used as a fine-tuning tool only.

**Comment by dan31** [comment]
@alemoi, completely forgot about administrator, I just ~~used Ildasm.exe and patched MSIL~~ changed configs :) @warpech is absolutely right, makes big difference. We should let developers feel as comfortable as possible, if we don't sacrifice reliability and consistency. Would be really cool to have polyjuice be nonintrusive and easy to activate (and scheduling adaptive, crashed apps self-recoverable etc, you know).

**Comment by warpech** [comment]
This issue resulted of isolating "Polyjuice" features behind "Polyjuice" flag set per database. 

The remaining problem was separated into a new issue: https://github.com/Starcounter/Starcounter/issues/2783
