### ISSUE TITLE
Allow treating enums as strings in JSON

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2706]
Presently, if I have a database object that contains an enum like so:

    enum Color { Red, Green, Blue }

    [Database]
    public class Thing
    {
        public Color Color;
    }

The `Color` property will be stored as an integer in the database. This is fine. However, suppose I create the following JSON message:

    {
        "Color": "Red"
    }

Attempting to set the data of this JSON message to be an instance of `Thing` in an HTTP handler will cause it to hang forever (see #2682) as there is a type mismatch between the JSON type (string) and the type of `Thing.Color` (int, sort of). Instead of hanging or throwing an exception in this situation, **I would like for the JSON layer to transparently convert between the enum names and their integer representations if the JSON type is string.**

**Comment by miyconst** [comment]
+1

**Comment by chrhol** [comment]
Good suggestion! Since we generate the code for bindings runtime it shouldn't be too difficult to add conversion to and from enum to strings.

I will put it on me to be implemented.

**Comment by warpech** [comment]
I remember I tried to use enum in the first app I was working on. +1 from me

**Comment by chrhol** [comment]
I have added automatic conversion for enums to and from strings now when bound in typedjson. Pushed to develop and next.
