### ISSUE TITLE
Add DbHelper.FromID(string ObjectId) method

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2708]
Currently we have only `DbHelper.FromID(long ObjectId)` method, but in web we use encoded id, which is string.

So, every time I select an object by id, I have to do like this:

```csharp
DbHelper.FromID(DbHelper.Base64DecodeObjectID(objectId));
```

**Comment by k-rus** [comment]
Thank you for your request. The issue for this enhancement was already created and is #2567. Thus I will close this one as duplicate.
You are welcome to make comment there.
