### ISSUE TITLE
VisualStudio watch window - The name 'DbHelper' does not exist in the current context

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2709]
I try to debug some code, and added an expression to Watch windows:

``` csharp
DbHelper.FromID(DbHelper.Base64DecodeObjectID(objectId))
```

This rises an error in VisualStudio:

```
The name 'DbHelper' does not exist in the current context
```

![dbhelper-watch-bug](https://cloud.githubusercontent.com/assets/6435556/7582314/feb99ef8-f894-11e4-9c3e-4372eec59c3d.png)

**Comment by miyconst** [comment]
@alemoi could you please teake a look? It is really annoying when trying to debug an app.

**Comment by dan31** [comment]
@miyconst, does IntelliSense work for you for Starcounter classes in that project?

**Comment by miyconst** [comment]
@dan31, it works, but not in the Watch window.

**Comment by per-samuelsson** [comment]
> it works, but not in the Watch window.

Thats kind of weird. Can you try/confirm just a few things here:

1. Are you building ```Debug``` configuration of your project/solution? Just thinking that otherwise, it might be something going on with inlining stuff.
2. Can you try creating a dummy static class and wrap the call to DbHelper, and add a watch to that, to see if that works? Like

```C#
static class Dummy {
  public static ulong FromID(string id) {
    return DbHelper.FromID(DbHelper.Base64DecodeObjectID(objectId));
  }
}
```

Add watch to ```Dummy.FromID(string)```

Not sure what (2) really tells us if it works, but just curious to see anyway. :smiley:

**Comment by per-samuelsson** [comment]
Oh, and also,

3, can you try to fully qualify ```DbHelper```, to see if that helps?

**Comment by per-samuelsson** [comment]
> can you try to fully qualify DbHelper, to see if that helps?

And as for this, I think VS tries resolving based on the scope of the current instruction, and if I'm not wrong, ```DbHelper``` is some subnamespace, right? Not sure if that namespace is in the scope of where the instruction execute.

**Comment by miyconst** [comment]
1. Yes, it is a debug build.
2. Yes, a `DbHelperWrapper` class works as expected.
3. `Starcounter.DbHelper` is visible in the Watch window, `DbHelper` is not. The `using Starcounter;` is included on top of the file.

![vs-debugging-error](https://cloud.githubusercontent.com/assets/6435556/7747450/2a7f4d96-ffc3-11e4-8e9d-002bba6b6f24.png)

**Comment by miyconst** [comment]
Is this going to be fixed somehow? 

If not, then it would be nice to add some documentation, because it is very frustrating when you copy a piece of your code which works to the Watch window and it does not work in there.

**Comment by alemoi** [comment]
I have the same problem trying to debug inside Starcounter, I have to specify full namespaced names in some cases. I guess when its outside the current namespace, or in different assembly, not sure about that.

**Comment by dan31** [comment]
@alemoi, @miyconst, does it happen _when you update versions of Starcounter_? My theory now is that, first time you install SC and create a project from template – it is all fine; then you upgrade Starcounter and the references in your project creep. Isn't it the case?

**Comment by miyconst** [comment]
Looks like so. I have created a new Solution and Watch expressions work as expected in there, but not in the old apps.

**Comment by alemoi** [comment]
Ok, then its weird. I meant that in Level1 I have to specify namespaces always in watch window for the cases outside the current namespace.

**Comment by miyconst** [comment]
Archiving the issue.
