### ISSUE TITLE
Installer needs to check that all chosen network ports are available

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2711]
I guess its quite easy to do without me writing any special API. @andwah assigning to you, but let's discuss together!

**Comment by andwah** [comment]
This is now done.

Port 135 is occupied on my system.
![image](https://cloud.githubusercontent.com/assets/2656996/7729427/fb6e23b4-ff14-11e4-9b4a-e18c9c0e1eb3.png)

**Comment by alemoi** [comment]
:+1:
