### ISSUE TITLE
Expose aggregation port as configurable in installer GUI

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2712]
Right now port 9191 is not exposed in GUI installer but used underneath for aggregation protocol. I will make some initial work on this and then assign to @andwah

**Comment by alemoi** [comment]
Internal engine part and configuration fixed via 89cb47ceaf5a23cba33dd0626c4c903bf907ec5c
The remaining part is to expose the aggregation port and check ports availability in GUI installer. Therefore assigning now to @andwah

**Comment by alemoi** [comment]
https://github.com/Starcounter/Starcounter/issues/2711

**Comment by andwah** [comment]
This is now done.

![image](https://cloud.githubusercontent.com/assets/2656996/7729376/c3df7894-ff14-11e4-86ac-9d0ac444c028.png)
