### ISSUE TITLE
Negative exit codes are not detected during batch file tests 

### ISSUE THREAD

**Issue by parherman** [Starcounter/Starcounter#2716]
Currently failed tests can go undetected and hang on the build server because some exceptions use negative exit codes. We use IF ERRORLEVEL 1 to check for errors, but that only checks for exit codes that are grater then 0.

We should try to change to "IF %ERRORLEVEL% NEQ 0 ()" so that we cover also negative exit codes, or "IF %ERRORLEVEL% EQU %KNOW_EXIT_CODE% ()" when we want to check for known exit codes. (Not tested yet!)

**Comment by k-rus** [comment]
`errorlevel` is not a real environment variable and using it as another environment variable can bring unexpected results, see #2462 for such example. I suggest to find a solution through documentation. Experiments might not cover some complex but real cases.

**Comment by k-rus** [comment]
> some exceptions use negative exit codes

Can you provide more information about it? 
I am wonder if it is possible to fix the application to guarantee positive codes only.



> "IF %ERRORLEVEL% NEQ 0 ()"

From our experience this way does not always work.

**Comment by parherman** [comment]
In C#, when I do this:

```C#
System.IO.File.OpenRead(@"This\will\throw");
```

The exit code will be -532462766

This is from IF /?:

> IF [NOT] ERRORLEVEL number /.../ Specifies a true condition if the last program run returned an exit code equal to or greater than the number specified.

So I think its safe to say that "IF ERRORLEVEL 1" will not catch exit codes lower then 1.

Also from IF /?:

> %ERRORLEVEL% will expand into a string representation of the current value of ERRORLEVEL, provided that there is not already an environment variable with the name ERRORLEVEL, in which case you will get its value instead.  After running a program, the following illustrates ERRORLEVEL use

So what if we clear %ERRORLEVEL% before we run the tests, [like the highest voted answer](http://stackoverflow.com/a/334890) in the Stackoverflow question you link to in #2462 suggests:

```

C:\Users\herman\Projects\tests>TestErrorlevel.bat
ECHO is on.

C:\Users\herman\Projects\tests>set ERRORLEVEL=2000

C:\Users\herman\Projects\tests>set ERRORLEVEL=

C:\Users\herman\Projects\tests>ThisWillThrow.exe

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\herman\Projects\tests\This\will\throw'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at ConsoleApplication2.Program.Main(String[] args)

C:\Users\herman\Projects\tests>echo -532462766
-532462766

C:\Users\herman\Projects\tests>IF -532462766 NEQ 0 (ECHO The test failed )
The test failed
```

@k-rus, @alemoi when I read #2462 it looks like there was a problem with IF %ERRORLEVEL% NEQ 0 in one place, but you ended up changing all the checks or am I missing somthing? Do you think we could clear the %ERRORLEVEL% as an alternative approach to solving #2462?

In any case, I believe that we sometimes get negative exit codes and that "IF ERRORLEVEL 1" dose not catch them.

**Comment by parherman** [comment]
The actual hanging could be the result of the "The application has stopped working" dialog that Windows uses, where the user needs to click Debug/Close to continue. I was able to suppress this dialog when running star.exe in CycleTime.exe with processInfo.CreateNoWindow = true;

**Comment by k-rus** [comment]
> @k-rus, @alemoi when I read #2462 it looks like there was a problem with IF %ERRORLEVEL% NEQ 0 in one place, but you ended up changing all the checks or am I missing somthing? Do you think we could clear the %ERRORLEVEL% as an alternative approach to solving #2462?

If I don't mistake `%ERRORLEVEL%` was not set. Thus clearing it will not help. Unfortunately, `%ERRORLEVEL%` is not always set to correct value. For example, we experienced that `%ERRORLEVEL% NEQ 0` was false, while `ERRORLEVEL 1` was true.

Having both conditions might server our need.

> In any case, I believe that we sometimes get negative exit codes and that "IF ERRORLEVEL 1" dose not catch them.

We know this and discussed that it might be a problem. And it is a problem now.

**Comment by parherman** [comment]
@k-rus one option to implement your suggestion to "guarantee positive codes only" and suppress the "The application has stopped working" dialog could be to write a small wrapper exe that we run star.exe and other applications with that "catches" exceptions

Or we could convert the test *.bats used to start individual tests to C# so that we can use CreateNoWindow, something like [CycleTime.cs](https://github.com/Starcounter/Starcounter/blob/develop/src/Samples/CycleTime/CycleTime.cs)

**Comment by k-rus** [comment]
Now the existing broken tests need a temporal solution.

Long term there should be strategy how tests should be designed and written without brining much overhead to developers.



> In C#, when I do this:
> 
> System.IO.File.OpenRead(@"This\will\throw");

Such code should be wrapped in try-catch block, I think. Again we need to have good practice in writing tests and everyone should follow such.

**Comment by parherman** [comment]
> Such code should be wrapped in try-catch block, I think. Again we need to have good practice in writing tests and everyone should follow such.

True, but sometimes star.exe will throw unhandled exceptions like this that we need to catch on the buildserver/bat files

**Comment by k-rus** [comment]
> True, but sometimes star.exe will throw unhandled exceptions like this that we need to catch on the buildserver/bat files

Why will it do?

If it is a common case, then yes, it should be handled.
If it is a strange way of writing tests, then it might not worth to cover this.
If users can write code that produce such problem, then there should be a general solution in `star`.

**Comment by parherman** [comment]
> Why will it do?

The problem I see now is that start.exe can crash with a negative exit code but some tests will still report passed result and problems can go undetected on the build server, like in #2674 or #2701

**Comment by k-rus** [comment]
The first issue is a C# wrapping calls to `star`. The second might be also due to the same reason. Then it is not problem with `star` and build server, but with the actual tests wrapping the calls. Correct me, if I am wrong.

**Comment by parherman** [comment]
I guess its in the eye of the beholder, before I made changes to CycleTime.exe it would exit with negative exit code that went on undetected by IF ERRORLEVEL 1. Maybe its an error that CycleTime.exe did not use positive exit code, but I think it would have been easier to detect if the test/build had failed

**Comment by parherman** [comment]
We continue to use IF ERRORLEVEL 1 like before so that we avoid problems with %ERRORLEVEL% not containing the last ERRORLEVEL
