### ISSUE TITLE
Assigning a new object to a property, does not trigger OnData behavior 

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#2717]
Hi!

(Starcounter edition 2.0.3139.3)

I have a Json bound to a database class. This database class has a public property. When I re-assign this property to another object the OnData method for the Property is not called. Neither is the new Property values sent to the client json.

As an example: The our database class Blog has a ProductionGroup property. When I change Data.ProductionGroup I would expect the OnData method in TestPageProductionGroup class to get called. 

    [TestPage_json]
    partial class TestPage : Page, IBound<Blog>
    {        
        void Handle(Input.Change input)
        {       
            if (Data != null)
            {
                    Data.ProductionGroup = MyHelper.GetNextProductionGroup();
            }
        }

        [TestPage_json.ProductionGroup]
        partial class TestPageProductionGroup : Json, IBound<ProductionGroup>
        {
            protected override void OnData()
            {
                // This is called when Blog is bound to this Json. 
                // But not when Blog.ProductionGroup property is changed to another instance.
                base.OnData();
            }
        }
    }

Is this a known error? Can I provide you with more information, or show you a real example from our Tunity solution?

/Ivar

**Comment by dan31** [comment]
Hi @ivarbergman, thanks for question! @chrhol, WDYT?

**Comment by chrhol** [comment]
Sorry, I should have answered earlier. Clearly a bug, either the Data object on the json is not updated properly in this case, or the OnData() is not triggered.

I will take a look.

**Comment by chrhol** [comment]
I tried to reproduce it but in my sample based on the code above, it works fine. I have access to your code so If you could point me to where it is I can test it in your application instead.

**Comment by ivarbergman** [comment]
I think it would be easiest if I could show you over a screen share. (There are a number of steps to recreate the issue). Do you have time tomorrow?

**Comment by chrhol** [comment]
I can reproduce it in Tunity app after Ivar showed me. Will investigate

**Comment by chrhol** [comment]
Found the problem after some digging. In one place there was an incorrect `!` in an expression, which in turn made it so that the dirtycheck was skipped.

I've pushed a fix to develop, so next nightly should include it.
