### ISSUE TITLE
Review the API to get and set typedjson that contains single value.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2720]
After the implementation to support typedjson that contains of one single value and arrays with primitive values (#237) the public API should be reviewed to make sure it's a solution we are satisfied with.

I will add examples here on how the API looks today (currently no docs written yet).

**Comment by chrhol** [comment]
Old issue that haven't been touched for over 1½ years. Lets just finish this. The current implementation of single value json can be improved.

Based on [this comment](https://github.com/Starcounter/Starcounter/issues/237#issuecomment-117844981), my proposal is to move all functions for manipulation values for single value json to an extension class since they are not commonly used. This will allow the standard API to be less bloated while still allowing a better experience than how it's currently implemented.

The extension class will contain methods for adding items to an array for a specific value, setting and getting a value from a single value json and checking what type a json is.

```csharp
using Starcounter.XSON.Extensions

...
Json newItem = strArrJson.Add("stringValue");
if (!newItem.IsString()) 
     throw new Exception();
newItem.SetStringValue("differentValue");
string s = newItem.GetStringValue();
...
```

The same pattern as above will be implemented for all primitive types (`string`, `long`, `double`, `decimal`, `bool`). 

@warpech, @miyconst WDYT?

**Comment by warpech** [comment]
My opinion is that extension class obscures availability of this API. People who use IntelliSense as the primary tool to learn about the API will have hard time finding it.

But I leave the final word to you and @miyconst.

**Comment by chrhol** [comment]
> My opinion is that extension class obscures availability of this API. People who use IntelliSense as the primary tool to learn about the API will have hard time finding it.

Right, thanks for the input. Do you think the API is good enough and we should leave it as is for the moment? This is not something critical to change, just me wanted to finish some old issues :smile:

**Comment by per-samuelsson** [comment]
@chrhol 

Just for the sake of it, could you include some content that show what single value json look like in it's native form (i.e. JSON)?

**Comment by per-samuelsson** [comment]
> Just for the sake of it, could you include some content that show what single value json look like in it's native form (i.e. JSON)?

[Nevermind](https://docs.starcounter.io/guides/typed-json/primitive-arrays-and-single-value-types.html). 😄

**Comment by chrhol** [comment]
Was just looking for that page.

Currently the following properties are implemented directly in the `Json` class, meaning that they will show up for all instances of a `Json`, and that you cannot use these names as a name of a property in your viewmodel. 

There are also no overloads for adding items to an array for a specific value. You have to call `Add()` to get a new item, and then set the value.

```
public bool BoolValue
public decimal DecimalValue
public double DoubleValue
public long IntegerValue
public string StringValue
public bool IsBool
public bool IsDecimal
public bool IsDouble
public bool IsInteger
public bool IsString
public bool IsObject
public bool IsArray
```

**Comment by per-samuelsson** [comment]
I know you will hate me for this (and I might very well be wrong): for me, it would be more convenient that single value JSON content produced not a Json at all, but a more specific type, dealing particularly with that type of content.

No idea how that should work technically though 😎 

Rationale: single content JSON seem really exotic (correct?) and the price we pay to support it is quite high (i.e. it's harder to understand the API as a whole + we reserve a lot of names + there is maintenance costs for it, tests, etc).

**Comment by per-samuelsson** [comment]
I guess something like:

```
Json
  JsonObject
  SingleValueJson
```

And we would have to force SingleValueJson as the baseclass for code-behind that had a desire to define content as such (or allow Json, but you wouldn't be able to work with the data using such a reference).

**Comment by per-samuelsson** [comment]
> I guess something like:

Or even simpler actually:

```
Json
  SingleValueJson
```

**Comment by chrhol** [comment]
> it would be more convenient that single value JSON content produced not a Json at all, but a more specific type, dealing particularly with that type of content.

Yes, I somewhat agree. We took the decision quite early on though, to do the opposite. We should not have more than one `Json` class, no specific classes for single values and arrays. So all proposals have been done with that in mind, that we are stuck with one single class that needs to contain all functionality.

Maybe we should reconsider this, but then we probably need to do a more thorough proposal/specification and really look on how it will work both for those using XSON and internally.

**Comment by chrhol** [comment]
Well actually, we kind of have specialied classes of `Json`. The generated code is more or less like this...so maybe it wouldn't be a major shift to have it like that. If we structure it correctly, we can still keep functionality so that internally we only have have to care about the baseclass, while the user gets a nicer experince

**Comment by warpech** [comment]
My only strong opinion is that the API for this is needed, but I don't care much about the form of it. It is rarely used but must be there when it's needed.

Maybe @miyconst has strong opinion?

**Comment by per-samuelsson** [comment]
> My only strong opinion is that the API for this is needed, but I don't care much about the form of it. It is rarely used but must be there when it's needed.

Then I fully support the idea @chrhol had:

>Based on this comment, my proposal is to move all functions for manipulation values for single value json to an extension class since they are not commonly used.

Since single value data is quite exotic, I think that proposal sounds really good. Because it can keep those advanced methods/properties out of the way in all normal cases, and allow them to be brought in only when needed (by the few).

**Comment by warpech** [comment]
Ok, fair enough!

**Comment by chrhol** [comment]
Changes are pushed to develop branch. All properties for single values are obsoleted and the new ones are added to the extension (in `Starcounter.Advanced.XSON` namespace).

Documentation have been updated for the develop branch on docs.starcounter.io (https://docs.starcounter.io/v/Develop/guides/typed-json/primitive-arrays-and-single-value-types/)

Considering this issue solved and will close it.
