### ISSUE TITLE
ScErrThreadNotDetached when starting codehost in a certain way

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2721]
Using `develop` Level1 and Level0. When making round robin scheduling from gateway point of view on system port (8181) I get `ScErrThreadNotDetached (SCERR1007): The operation failed because the current thread was attached to the scheduler and detached thread was expected.` when starting codehost in a certain way.

If scheduler on which gateway sends is the same, the problem does not occur. So I guess its related to 
parallel execution on different schedulers, when gateway distributes the load in round robin manner. 

Not every codehost is able to reproduce the problem, but RetailDemo and PokerDemo do.

The steps are the following:

1. Build RetailDemo project: https://github.com/Starcounter/RetailDemo
2. Change line `Level1\src\scnetworkgateway\OurSources\worker_db_interface.cpp` line 488: `sched_id = 0;` to `sched_id = GenerateSchedulerId();`
3. Start/stop database in the following manner:

```
star.exe -database=default ScRetailDemo.exe
staradmin --database=default stop db
staradmin --database=default delete --force db
star.exe -database=default ScRetailDemo.exe
```

The console where star.exe called with get the red error message: `ScErrThreadNotDetached (SCERR1007): The operation failed because the current thread was attached to the scheduler and detached thread was expected.`

Trying to locate the error I set `DebugBreak();` in sccoredb.cpp `star_attach` on `if (ptc != NULL)` I get the following stack trace:

```
Unspecified error (80000003) detected at ..\..\src\sccoredb\sccoredb\sccoredb.cpp:3376 (Thread 13560).
    000007FC35978B12 KERNELBASE!
    0000003101842266 sccoredb!star_attach : sccoredb.cpp (3355)
    000007FC2CBC117C sccoredbh!sccoredbh_thread_enter : sccoredbh.cpp (44)
    000007FC290FE297 coalmine!_on_enter : threadev.c (9)
    000007FC290E9F13 coalmine!_edetach : detach.c (62)
    000007FC290E6F56 coalmine!cm3_set_yblk : coalmine.c (424)
    000007FBBC4192F2 <unknown>!
```

**Comment by eriohl** [comment]
Used PokerDemo instead of RetailDemo (RetailDemo only supports VS2013, which I do not have). But says it should work with PokerDemo as well so.. Otherwise followed instructions exactly. Running latest release build built locally. 2 hardware threads. Failed to reproduce. Any ideas?

**Comment by eriohl** [comment]
Managed to reproduce it on a machine with more threads. Investigating...

**Comment by eriohl** [comment]
Resolved. Problem was an on schema updated callback on attaching thread which in turn tried to attach the thread again. Changed so that the thread is tagged at attached in scheduler before before call to attach to database kernel.

**Comment by alemoi** [comment]
Wow! Super fast resolution, thank you!

**Comment by alemoi** [comment]
Sorry for the late response.

**Comment by dan31** [comment]
:+1:
