### ISSUE TITLE
Session gets regenerated for no reason

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2731]
Repeatable in 50% of page loads. Repeatable when running only Launcher, as well as Launcher combined with more apps.

There comes some session id with the initial `text/html` response, which is then replaced in the consecutive `application/json` response:

Initially comes `Set-Cookie:Location=%2F__default%2F389B5B6B05A82A2300000020; path=/`:

![session](https://cloud.githubusercontent.com/assets/566463/7813269/c2ae86e6-03b9-11e5-8c43-777f81088318.png)

Which is then replaced with: `Set-Cookie:Location=%2F__default%2FF99D299F722102C110000030; path=/`

![session2](https://cloud.githubusercontent.com/assets/566463/7813272/c5667e70-03b9-11e5-83ea-bfb7007bcb89.png)

That causes an exception in PuppetJS:

> Uncaught Error: Session lost. Server replied with a different session ID that was already set. 
Possibly a server restart happened while you were working. 
Please reload the page.
Previous session ID: /__default/389B5B6B05A82A2300000020
New session ID: /__default/F99D299F722102C110000030

**Comment by miyconst** [comment]
This also happens with any other app + launcher.

**Comment by warpech** [comment]
This seems to be a server issue, to be clear.

**Comment by alemoi** [comment]
Cool! I will take a look!

**Comment by alemoi** [comment]
Can you please provide with some simplest reproduction cycle with only the Launcher app? Thank you!

**Comment by warpech** [comment]
Start Launcher with current Starcounter (I use yesterdays daily), go to http://localhost:8080/ and press F5 few times.

**Comment by alemoi** [comment]
Hmmm, I would say I can not reproduce the issue. Need to look on your computer tomorrow! I hit F5 again and again and see no errors in browser debug window and no `Set-Cookie` in second localhost request `Accept:application/json`.

**Comment by warpech** [comment]
Still reproducible as of Starcounter 2.0.3183.3. You may try pressing Ctrl+F5. I can show you in person as well

**Comment by alemoi** [comment]
Should be fixed via f6f182b7c97cfaf590e8866527f2bbabd3516487
Thank you for testing!

**Comment by warpech** [comment]
Seems to be fixed in current build. Thx!
