### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2732]
I'm trying to do a query on a class in my database and loop through the results. When going through the second result I do get the exception "index was outside the bounds of the array". I don't get the exception if I remove the parameter _Removed=false from the query. 

                    QueryResultRows<ClassifiedHomeAd> availableProperties = null;
                    if (broker != "") {
                        availableProperties = Db.SQL<ClassifiedHomeAd>("SELECT c FROM ClassifiedHomeAd c WHERE BrokerOrganization=? AND Seller=? AND _Removed=?", organization, broker, false);
                    }
                    else
                    {
                        availableProperties = Db.SQL<ClassifiedHomeAd>("SELECT c FROM ClassifiedHomeAd c WHERE BrokerOrganization=? AND _Removed=?", organization, false);
                    }
                    string titles = "";
                    foreach (ClassifiedHomeAd ad in availableProperties)
                    {
                        if (!titles.Contains(ad.Name))
                        {
                            titles += ad.Name;
                            string adress = MatchRegex.Group1(ad.Name, "(.*?) -");
                            string propertyId = MatchRegex.Group1("", "");
                            var item = viewModel.AvailableAds.Add();
                            item.Url = ad.Url;
                            item.Title = adress;
                        }
                    }

If I try to do the query in the admin gui I get the exception even if I only try to fetch 1 result.

**Comment by k-rus** [comment]
Thank you for the question.
What is the schema of `ClassifiedHomeAd`? How is it and its properties defined?

**Comment by Ripipip** [comment]
This is the part related to _Removed (that causes the error).

        public bool _Removed;
        public bool Removed
        {
            get
            {
                return _Removed;
            }
            set
            {
                if (_Removed == false)
                {
                  // Check if removed
                }
            }
        }

**Comment by k-rus** [comment]
Thank you for the clarification. It should work.

Can you provide the full stack trace? How can we reproduce the issue?

 Sorry, that I didn't ask about the stack trace from the beginning, and it is always good to report complete stack trace from the log (or all related errors) in issue.

**Comment by k-rus** [comment]
I made a test application based on the information above and I was not able to reproduce the issue. 
@Ripipip 
Can you provide the application and steps to reproduce the issue?

**Comment by Ripipip** [comment]
Okay, so I cleaned the database and weren't able to reproduce it again. So it is some bug somewhere but for now it is solved. Thank you anyway!

**Comment by k-rus** [comment]
Can it be that you changed some database class and tried to run in existing database? Such changes can make mismatch between the database schema and class definitions.
