### ISSUE TITLE
Cannot retrieve session through GET

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2736]
When making a request like `GET /__default/483D3E341CAC89F710000030`

I get an error message `404 Session does not contain any state (session.Data).`

This is wrong because the session actually exisists and sending a PATCH to it works.

Error might be caused because `Handle.GET` checks `session.Data`, while `Handle.PATCH` checks `root = session.PublicViewModel`.

@chrhol could you take a look?

**Comment by chrhol** [comment]
Yes, looks like we missed this handler when we changed the behaviour when multiple apps share session. I will change it.
