### ISSUE TITLE
Huge number of dead branches in Level1

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2741]
I have noticed that there are again huge number of branches of form issue/number. This really complicates working with remote branches. It would be great if not needed once are removed ASAP.

From past experience I can guess that they were created by @per-samuelsson, thus I assign the task to him. Correct me if I am wrong, since I haven't checked.

**Comment by per-samuelsson** [comment]
You have already created an issue like this: #2578. And its assigned to @parherman.

I can briefly repeat what I have said before: its the duty of the infrastructure to clean up abandoned remote branches. I'm just not changing the way I work, b/c its the **right** way to work.

**Comment by k-rus** [comment]
> You have already created an issue like this: #2578. And its assigned to @parherman.
> 
> I can briefly repeat what I have said before: its the duty of the infrastructure to clean up abandoned remote branches. I'm just not changing the way I work, b/c its the right way to work.

To my knowledge there is official decision that there are will be no changes in the build infrastructure for current version of Starcounter. So the dead branches have to be cleaned up manually.

I will close this issue and will repeat my request to manually delete unused branches in #2578.

**Comment by k-rus** [comment]
> I'm just not changing the way I work, b/c its the right way to work.

Do you mean that it is the right way to keep all non-used branches open? I do agree that it is good practice to open separate branches for different issues, but I disagree that it is right way to keep them open forever.

**Comment by parherman** [comment]
@k-rus like @per-samuelsson suggests here and like I suggested yesterday, we can auto delete branches one they are merge

**Comment by k-rus** [comment]
> @k-rus like @per-samuelsson suggests here and like I suggested yesterday, we can auto delete branches one they are merge

There are two cases: a final merge or an intermediate merge. I have not investigated how removing branch at intermediate merge will affect continuation of the work with the branch. The scenarios for investigation include different commonly used GUIs and development on several machines with the same branch.

By the way it is closed issue.
