### ISSUE TITLE
Can Handle.GET use methods instead of Actions?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2746]
In VS we can 
1. Navigate between methods with the top right drop down.
2. Collapse/expand methods' body.

This is not available for actions like: `() => { ... }`.

Could we replace:
```csharp
Handle.GET("/signin/signin/{?}/{?}", (string Username, string Password) => {
    //Some code here
});

Handle.GET("/signin/signout", () => {
    //Some code here
});
```

With:
```csharp
class SignIn {
    [HttpGet]
    public Json SignIn(string Username, string Password) {
        //Some code here
    }

    [HttpGet]
    public Json SignOut() {
        //Some code here
    }
}
```

**Comment by dan31** [comment]
It would be nice to navigate in between handlers. However, the Starcounter's way feels for us of minimal verbosity and corresponds to other actual frameworks as well. Going in class-style handlers means for me polluting namespace too much, stealing focus. What I believe in is, since Roslyn, we can provide very customized tools for new VS. E.g., not only there should be a way to provide collapsing and navigation for handlers, but also refactoring for class names inside SC SQL queries.

**Comment by miyconst** [comment]
Sometimes it is difficult to find a handler in a big app.

I tried to use:

```csharp
protected void HandleSignIn(string Username, string Password) {
    //Some code here
}

Handle.GET("/signin/signin/{?}/{?}", HandleSignIn);
```

But it is not allowed, this works for functions without parameters only. All I want is to somehow efficiently organize the Handlers, methods or actions, does not really matter.

**Comment by dan31** [comment]
Good point @miyconst. I couldn't find a reason why this doesn't work. E.g., I tried also as such:
```
		public delegate Starcounter.Response Del (string Username, string Password);
		public Del del = (u, a) => { return ""; };

		public static void Main () {
			Handle.GET ("/signin/signin/{?}/{?}", del);
		}
```
@alemoi, maybe you can tell how to cook it properly?

**Comment by alemoi** [comment]
> @alemoi, maybe you can tell how to cook it properly?

Sure, no need for anything extra, here is how you can organize your particular example:

```c#
static Response HandleSignIn(string Username, string Password) {
    return "My response string " + Username;
}
...

Handle.GET<String, String>("/signin/signin/{?}/{?}", HandleSignIn);

```

**Comment by alemoi** [comment]
Did it work out for you guys?

**Comment by miyconst** [comment]
@alemoi thanks, it does work!

I can even go for some polymorphism like this:

```csharp
Handle.GET<string>("/signin/signinuser?{?}", HandleSignIn);
Handle.GET<string, string>("/signin/signin/{?}/{?}", HandleSignIn);
```

**Comment by alemoi** [comment]
Hmm, I wonder why the example with one parameter works.. I thought it should be very strict.

**Comment by miyconst** [comment]
I can use it with up to five parameters:

```csharp
Handle.GET<T1>
Handle.GET<T1, T2>
Handle.GET<T1, T2, T3>
Handle.GET<T1, T2, T3, T4>
Handle.GET<T1, T2, T3, T4, T5>
```

**Comment by alemoi** [comment]
So unused parameters are taking the default values? Or some strange values, like for integer, boolean and other primitive types?

**Comment by miyconst** [comment]
I don't have access to the internal code, but `Handle` class has some definition for those `GET` methods:

```csharp
namespace Starcounter {
    public class Handle {
public static void GET(string uriTemplate, Func<Response> code, HandlerOptions ho = null);
        public static void GET<T>(string uriTemplate, Func<T, Response> code, HandlerOptions ho = null);
        public static void GET<T1, T2>(string uriTemplate, Func<T1, T2, Response> code, HandlerOptions ho = null);
        public static void GET<T1, T2, T3>(string uriTemplate, Func<T1, T2, T3, Response> code, HandlerOptions ho = null);
        public static void GET<T1, T2, T3, T4>(string uriTemplate, Func<T1, T2, T3, T4, Response> code, HandlerOptions ho = null);
        public static void GET<T1, T2, T3, T4, T5>(string uriTemplate, Func<T1, T2, T3, T4, T5, Response> code, HandlerOptions ho = null);
    }
}
```

That is why it works.

**Comment by warpech** [comment]
I think you have access to the source code: https://github.com/Starcounter/Starcounter/blob/6faab03b67711436f4fad4eb35335d153c929485/src/Starcounter.Internal/Handle.GET.cs

**Comment by alemoi** [comment]
No problems, I will check myself and add unit tests probably. My question was related to the situation that you use 1 parameter template but 2 parameters function. So I wondered what values got the undeclared parameters.

**Comment by miyconst** [comment]
@warpech, yes, looks like so.

@alemoi, I have two functions with the same name. One accepts single parameters, the other one accepts two parameters. That is why it works.

**Comment by alemoi** [comment]
> @alemoi, I have two functions with the same name. One accepts single parameters, the other one accepts two parameters. That is why it works. 

Ok, then everything is like it suppose to be! I thought its the same function :)

**Comment by dan31** [comment]
@alemoi, @miyconst, C# gods! :100:
