### ISSUE TITLE
Public web folders are not updated after an app stops

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2752]
App's public folders should be removed from `Public web folders` list when the app stops. Currently server restart required to remove web folder from stopped apps.

**Comment by alemoi** [comment]
Thanks for reporting! There are several issues regarding this. I will fix as soon as finished with current tasks!

**Comment by miyconst** [comment]
@alemoi, any success on this?

**Comment by alemoi** [comment]
I have changed the architecture behind the static file handler. Now each codehost owns its static file handler (which sits on user port for that codehost). This architecture automatically solves the above and some other problems. Done via cedf011b66a3b737c6de621c76f3ea8e3dd60427
Feel free to open this issue if you have any problems.

**Comment by miyconst** [comment]
This issue is fixed, but another one appeared:

Launcher has some content which replaces `/sys/` content. After restarting launcher Starcounter server always returns file from `/sys/` folder in spite of Launcher has same file.

The file: `http://localhost:8080/sys/polyjuice-include/polyjuice-include.html`

Without Launcher should look like this: https://github.com/Polyjuice/polyjuice-include/blob/gh-pages/polyjuice-include.html

With Launcher should look like this: https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/wwwroot/sys/polyjuice-include/polyjuice-include.html

**Comment by alemoi** [comment]
Thanks for reporting! Ok and look up is done on the same port. That's probably a different issue, I guess related to the order in which folders for files are looked up. Just prpbably by luck we didn't have that before. I will check this tonight!

**Comment by alemoi** [comment]
Big time thanks for reporting and concrete reproduction steps! Should be fixed via f2a8c11586254f9b1196b88dac15991aa0494734
Let us know if anything.

**Comment by miyconst** [comment]
Thank you for quick fixing, it works now.
