### ISSUE TITLE
Change to OntologyMap

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2753]
By @alemoi on 4 Jun 2015 01:29:16 AM

>Hi guys! I just pushed to my personal branch the initial version of arbitrary classes mapping. I tested it a bit and it seem to work fine!
However, I guess the common Polyjuice applications (Launcher, People, Products, ..) are broken now regardless: tried People, Products, Launcher and the partials were not displayed correctly (with or without my changes).
That's why I didn't push the changes to develop and kept them in my local branch.

>Marcin, when the issues with apps get resolved, can you please download and install my personal build with changes: 
http://downloads.starcounter.com/download/Polyjuice/DevelopDailyBuilds/2.0.9764.2

>I kept the "/so/.../..." and added "/db/.../..." handler!

>I need to test the changes more and add a build system test!

>Let's see tomorrow how it goes!

By @warpech on Jun 5, 2015 at 12:58 PM

>As discussed on today's meeting, /db/ should only accept full table names. /so/ should accept short names but solve them in the Society Objects scope.

>Alexey, will you include that explanation in .io pages?
http://starcounter.io/guides/apps/uri-mapping/
http://starcounter.io/guides/apps/data-mapping/

**Comment by alemoi** [comment]
Thank you for creating the issue. Here is the related one: https://github.com/Starcounter/Starcounter/issues/2745

**Comment by alemoi** [comment]
I have just pushed the discussed changes via 3154c4ade9ed1398659e9aea87ddeee3b7c38b00
Big thanks to @miyconst for testing!
Waiting for your next week response @warpech :)

**Comment by miyconst** [comment]
Closing this issue as we are satisfied with the current implementation of OntologyMapping.
