### ISSUE TITLE
Commit hooks in 2.0

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#2754]

**Comment by warpech** [comment]
:+1:

**Comment by eriohl** [comment]
Support available in kernel.

Works pretty much the same was as in NEXT with some difference in the interface.

To configure commit hooks use: star_set_commit_hooks(transaction_flags, table_id, commit_hook_mask). Note that id is used instead of token and the function creates its own transaction, same approach as with the other schema update functions. Also, the mask constants if different. As before: Bit mask has to be recalculated on each update.

Function test commit_hook_test is available in DEVELOP now also to check usage.

No internal structures had to be changed so I saw no need to update image version. Keep in mind however that downgrading after use may cause the recovery to fail.

**Comment by per-samuelsson** [comment]
OK, commit hooks are now usable in 2.0. The relevant API and sample can be found in **Listing 1** in [this old comment](https://github.com/Starcounter/Starcounter/issues/2235#issuecomment-55898680), which in turn use the defined database model from [this comment](https://github.com/Starcounter/Starcounter/issues/2235#issuecomment-53554124).

Its pretty straightforward I think. Let me know if something doesn't work or you have questions and/or any improval suggestions. Meanwhile, I'm closing this.
