### ISSUE TITLE
ScErrIteratorNotOwned (SCERR4035)

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2755]
Starcounter.DbException: ScErrIteratorNotOwned (SCERR4035): A cursor operation failed because the cursor wasn't owned by the current thread and transaction.

Following code will fail during iteration:
```
foreach (MyDbObject mdo in Db.SQL<MyDbObject>("SELECT a FROM MyDbObject a WHERE a.MyStringProperty = ?", "a"))
{
      MyDbObject copy = (pseducode) mdo.Copy();
     copy.MyStringProperty = "c"; //Should not affect iterator
     Transaction.Current.Commit();
}
```

Is this by design?

**Comment by chrhol** [comment]
Yes, as far as I understand it, when the transaction is committed it's actually recreated in the kernel so you cannot continue to use iterators.
