### ISSUE TITLE
Fix char bugs in SQL parser

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2756]
The source code of the parser was fixed from `char` to `wchar_t` some time ago. It was found during conversion of `wchar_t` into `ucs2_char` that there are still number of places where `char` presented, i.e., bugs which need to be fixed.

The found rules are:
- [x] `CharacterWithLength` and `CharacterWithoutLength` defined on lines 4669 and 4688 respectively. Both rules analyse input from rule `opt_charset`, which is defined through `IDENT` and thus produces 2 byte character.
- [x] Rules using function `SystemTypeName`, which include the above rules. The string literals, which are inputs to the function, can be moved into separate definition or kept at the same place, and be initialized as arrays.

**Comment by k-rus** [comment]
I just want to mention about next: 
I also noticed buggy use of functions `makeString` and `makeSimpleA_Expr`, which takes `wchat_t` as arguments, but used with `char`. It might be already fixed in the conversion branch.

**Comment by alexanderstc** [comment]
Fixed the mentioned problems and similar ones which were found by converting the parser from C to C++.
