### ISSUE TITLE
Starcounter polyjuice edition only loads static files on port 8080

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2758]
Have a server with several databases with different ports. Now installed the SC polyjuice edition to start using polymer and other static files from the sys directory. Only the db using port 8080 is finding the files.

**Comment by alemoi** [comment]
Thank you for the question! By default there is only one default user port in the system, on which the above handler is registered. Is each database/codehost using a different default user port? If yes, than they should register different port handlers. Let us know if they don't! If user would like to register some directory explicitly (not a working directory, and not `wwwroot`) then `AppsBootstrapper.AddStaticFileDirectory` should be used from `Starcounter.Apps.JsonPatch.dll` which should be renamed, but this is a different issue :)

**Comment by chrhol** [comment]
I can confirm that if you create a database with a different default port than 8080, the static files included in Starcounter are still registered on the default port (8080). Running for example the launcher  in that database will not work, it will not find the static files.
