### ISSUE TITLE
Invalid Session scope inside Hook<T>.OnAction

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2762]
Two applications `SignIn` and `GoogleSignIn`, each application uses `Session.Current.Data` to save ViewModel instance and update it's state when user signs in/out.

When user signs in with `SignIn` app it creates a new `SystemUserSession` and then in `GoogleSignIn`:
```csharp
Hook<SystemUserSession>.OnInsert(s => {
    //In here Session.Current.Data equals to SignIn.SessionContainer
    //And StarcounterEnvironment.AppName equals to "SignIn", but should be "GoogleSignIn"
});
```

The `SignIn.SessionContainer` class is defined and set to Session in `SignIn` app, but visible in `GoogleSignIn` app.

If I manually change 
```csharp
StarcounterEnvironment.AppName = "GoogleSignIn";
```
Then `Session.Current` has correct value, but as @alemoi said `StarcounterEnvironment.AppName` should be readonly and currently exposed only for test reasons.

The changes are not pushed yet, I can push or demonstrate on my pc if needed.

**Comment by miyconst** [comment]
https://github.com/Starcounter/Starcounter/issues/2763

**Comment by alemoi** [comment]
I would say the hooking system should save the application name whenever hook is created. I don't know how the hooks are implemented by @per-samuelsson but I just guess it should work like this:
1. Creator application name should saved with hook when hook is created.
2. When the hook is called, it should save current AppName, set hook-creator AppName before the hook is called and restore back to current AppName at the end of hook call. Like this it works for Handlers, Handles, WebSockets, etc.

**Comment by per-samuelsson** [comment]
>  I don't know how the hooks are implemented by @per-samuelsson but I just guess it should work like this:

Hooks are totally not aware of contexts at all. The are invoked in the context of the transaction being committed. If they must change, please open a change request and we can formalize some kind of specification and I can implement it eventually.

**Comment by warpech** [comment]
Before the session/appname problem is fixed, @miyconst can continue testing commit hooks by overwriting `StarcounterEnvironment.AppName` property before reading Session.Current

After the session/appname problem is fixed, @alemoi proposes to change `StarcounterEnvironment.AppName` to be readonly again so that the apps will not compile without removing the line that changes it.

**Comment by per-samuelsson** [comment]
I discussed with @alemoi yesterday, and he suggest hooks should be extended to support the same kind of mechanism / app-context awareness as the other stuff you've done with handlers, etc. Basically, what he described [here](https://github.com/Starcounter/Starcounter/issues/2762#issuecomment-110359674).

I said it's fine by me, and I can do it, but I need some more info on exactly how it should work. Once @alemoi provide me with that, I will make this happen.

**Comment by per-samuelsson** [comment]
> I said it's fine by me, and I can do it, but I need some more info on exactly how it should work. Once @alemoi provide me with that, I will make this happen.

@alemoi have given me the info I need, I just need to figure out how it should relate to hooks, but I'm changing this to in-progress now.

**Comment by per-samuelsson** [comment]
Its not perfectly clear to me how you guys want this to work. Consider the following case, for example.

```C#
Lib.dll
"lib" {
  class Base {}
  class BaseHook {
    public static void OnInsert(Base b) {
      Console.Write("{0} in {1}", b, StarcounterEnvironment.AppName);
    }
  }
}

App1.exe
"app1" {
  using lib;
  
  void Main() {
    Hook<Base>.OnInsert(BaseHook.OnInsert);
  }
}

App2.exe
"app2" {
  using lib;
  
  void Main() {
    Hook<Base>.OnInsert(BaseHook.OnInsert);
  }
}
```

What should happen on a new ```Base``` being committed? Should the callback be called twice, one for each scope? That is, is the application name to be considered to be part of the unique identity of every installed hook?

Currently, only a single call would be made. In the kernel, the ```Base``` table is pinned as one that is to be "hooked", and in the managed layer, the infrastructure will consider both registered hook callbacks to be equal, i.e. the second registration redundant, and only invoke it once.

**Comment by miyconst** [comment]
There are two hooks (yes, they are the same), so the callback should be called twice. Each app receives the callback only once and with it's name inside `StarcounterEnvironment.AppName`.

So, the result on console should be:

```
b in App1
b in App2
```

This is how I see it.

**Comment by per-samuelsson** [comment]
> [...] so the callback should be called twice.

Thanks for the input.

What about this then? Invalid (b/c duplicate)? Call once? Call twice?

```C#
class Program {
  static void OnInsert() {}

  public static void Main() {
    Hook<Foo>.OnInsert(Program.OnInsert);
    Hook<Foo>.OnInsert(Program.OnInsert);
  }
}
```

**Comment by miyconst** [comment]
Also twice. Maybe the `OnInsert` method counts number of calls and does different logic depending on that ))

**Comment by per-samuelsson** [comment]
> Also twice. Maybe the OnInsert method counts number of calls and does different logic depending on that ))

OK. Good point. And both consistent with how it works when registering from separate apps, and probably also the simplest implementation (i.e. never check for duplicates, just treating every registered callback as a unique entity).

The only problem I can see with it is how we then should treat future deregistering of hooks, but maybe its as simple as just removing the last identical hook installed.

**Comment by miyconst** [comment]
We should follow native c# behaviour.

```csharp
using System.IO;
using System;

class Test {
    public event EventHandler Event;
    
    public void OnEvent() {
        if (this.Event != null) {
            this.Event(this, EventArgs.Empty);
        }
    }
}

class Program {
    static int count = 0;
    
    static void Output(object sender, EventArgs e) {
        count++;
        Console.WriteLine("This is call #{0}", count);
    }
    
    static void Main() {
        var test = new Test();
        
        test.Event += Output;
        test.Event += Output;
        test.OnEvent();
    }
}
```

And the result:

```
This is call #1
This is call #2 
```

**Comment by miyconst** [comment]
I have updated my example. If you have several same hooks then detaching a hook with the same type should remove one of them and does not really matter which one, as they are the same.

**Comment by per-samuelsson** [comment]
> If you have several same hooks then detaching a hook with the same type should remove one of them and does not really matter which one, as they are the same.

Yep, that seem logical. We'll adopt this once we get to detaching of hooks. My prio is to first solve this thing with application context (original post), probably sticking to the current API. And then revise everything we've discussed here and translate it to work items.

**Comment by miyconst** [comment]
Sure. The context problem is the most important one.

**Comment by per-samuelsson** [comment]
> The context problem is the most important one.

I'm on it, and I now have an idea on how it should be implemented. If all goes well, I can push it today. 

I will also change the implementation so that there is no matching of equality when hooks are installed, so that the semantics of hook registration change to what you outlined in this https://github.com/Starcounter/Starcounter/issues/2762#issuecomment-110734978. Hence, installing the same hook twice will invoke it twice (as opposed to once, as it is in the current solution).

**Comment by miyconst** [comment]
Cool. Thank you.

**Comment by per-samuelsson** [comment]
This is now resolved and merged/pushed in https://github.com/Starcounter/Starcounter/commit/5f07a3f0f1c25dab66adfe46a7587611e312863f. Commit hooks are now aware of the application context, and assured to run in the context of the registered application. And every registration of a hook will always execute (duplicates are no longer considered redundant).

Simple regression tests has been added to the regression test TestApps suite.

@miyconst, I'll let you close it once you have verified it works. Let me know if any problem.

**Comment by miyconst** [comment]
Will this be available in today's nighty build?

**Comment by miyconst** [comment]
`Session.Current` works as desired! Thanks!
