### ISSUE TITLE
Improve error message for unnamespaced app handlers

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2764]
I have an app called "HelloWorld" in which I tried to create a handler `/hello` (Polyjuice flag turned on)

The error message that I receive is:

> Polyjuice applications can only register handlers starting with application name prefix, for example, /myapp/foo

A better error message would be:

> Polyjuice applications can only register handlers starting with application name prefix, for example, /helloworld/foo

![image](https://cloud.githubusercontent.com/assets/566463/8059617/46b1458e-0ec1-11e5-9931-42531a5f7a68.png)

**Comment by alemoi** [comment]
Thanks for reporting! Done via ac4619787a0e5ced00ec14dc9a40db2a6793780f
