### ISSUE TITLE
Using Polyjuice.Map in non-Polyjuice database

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2765]
Currently, if the Polyjuice flag is disabled for a database, executing the following code:

```c#
PolyjuiceNamespace.Polyjuice.Map("/invoicedemo", "/");
```

results with a startup exception:

> Polyjuice is not initialized!

In issue https://github.com/Starcounter/InvoiceDemo/issues/20 it was suggested to enable URI mapping feature generally by renaming this to `Handle.Map` or something similar.

**Comment by alemoi** [comment]
Polyjuice.Map is working in a way specific to Launcher so far. We discussed and we are not sure if generic Polyjuice.Map is needed at all. So let's monitor this one.

**Comment by alemoi** [comment]
Since big changes pushed now, Im closing this issue.

**Comment by warpech** [comment]
List of above mentioned changes: http://starcounter.io/nightly-changes/list-breaking-changes-starting-build-2-1-1-3/
