### ISSUE TITLE
Server does not respond on WS patch

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2768]
The server does not response on WS in this scenario, but should.

Request
```http
GET: http://localhost:8080/images
Accept: text/html
```

Response
```http
200 OK
Cookie: Location = /__default/D11C498A1A5F64ABD0000010
```

Request
```http
GET: http://localhost:8080/__default/D11C498A1A5F64ABD0000010
Accept: application/json
```

Response
```http
200 OK
Content: { some json content }
```

WebSocket connected to `/__default/wsupgrade/D11C498A1A5F64ABD0000010`
```http
STATE -> {"state":1,"url":"ws://localhost:8080/__default/wsupgrade/D11C498A1A5F64ABD0000010"}
WS -> [{"op":"replace","path":"/_ver#c$","value":1},{"op":"test","path":"/_ver#s","value":0},{"op":"replace","path":"/workspaces/0/Images/CurrentPage/Images/Add$","value":1}]
```

No answer from the server and none of the breakpoints in Images app hit.

Works as expected if the second request sent to `http://localhost:8080/images` instead of `http://localhost:8080/__default/D11C498A1A5F64ABD0000010`.

@chrhol take a look, please.

**Comment by miyconst** [comment]
This issue is related to: https://github.com/PuppetJs/PuppetJs/issues/58

**Comment by chrhol** [comment]
I found a problem that the changelog of the viewmodel was not refreshed when the initial state of the viewmodel was returned. This in turn led to a mismatch in versioning. I will push a fix as soon as my build on the buildserver succeeds.

**Comment by chrhol** [comment]
Fix pushed!

**Comment by miyconst** [comment]
@chrhol will there be a daily build or wait till tomorrow and test with the nighty build?

**Comment by chrhol** [comment]
Sorry, missed your last comment. I didn't start a daily build but I can do that if you want a new version directly.

**Comment by miyconst** [comment]
Yes, do it please.

**Comment by chrhol** [comment]
I've started a build, will post the link here once it's done and uploaded.

**Comment by chrhol** [comment]
http://downloads.starcounter.com/download/Polyjuice/DevelopDailyBuilds/2.0.9950.2

**Comment by miyconst** [comment]
Thank you, it works.
