### ISSUE TITLE
Review and redesign hook API

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2770]
Part of #2760.

Preparing discussions can be found in #2760 (originally triggered by OP-section `[5]`) and in #2767.

Goals:

1. Make **hook** the general term, and support ```IEntity.OnDelete``` this way too, either as a complement to it, or a replacement (preferably the later).
2. Use notion of events as the principal entry.
3. Use generics as primary mechanism, but support runtime types / type names for more complex/custom scenarios, using a secondary API (to support future dynamic types too).
4. Prepare API to support detaching (but implement it as a separate issue).
5. Consider possible future implementation of *inherited hooks*, as suggested in #2760 OP-section `[2]`.

CC @miyconst.

**Comment by miyconst** [comment]
Sounds solid. The item 4 is not necessary, I guess. c# events support native detaching, no more work required here.

**Comment by per-samuelsson** [comment]
> The item 4 is not necessary, I guess. c# events support native detaching, no more work required here.

Well, I wish it was that easy. :sunglasses: I will need to write custom event add/remove sequences, since there is a synchronization thingy going on with how to configure the kernel in correspondance. Hence, I will prepare the API for detaching, but not implement it as part of this issue (I'm thinking you will recieve an ```NotImplementedException``` if detaching before we fully support it).

**Comment by miyconst** [comment]
Fair enough. Currently we don't need detaching in our apps.

**Comment by per-samuelsson** [comment]
I've worked out a first draft proposal of the new API. I have considered 3-5 from the OP especially, trying to craft an complete API that covers all cases, even though we won't support all the functionality as part of this issue.

There are two facets to the proposal: one simpler, "everyday" API, that will cover most cases, and that we'll use in the basic samples. And then an extended one to support more exotic usage such as hooks supporting runtime cherrypicking of types, future dynamic types, and hooks that diverge between the database type being hooked, and the signature of the callback (e.g supporting cherrypicking, and interface signatures).

I'll sum them up in separate comments below in a moment.

**Comment by per-samuelsson** [comment]
### Basic API

Based on generics; you hook the type (or hierarchy) you specify as the generic argument. The delegate signature must therefore compile-time match the given argument.

```C#
class Foo {}
class Bar : Foo { }

// Hook single class Foo. The BeforeDelete substitute/complement
// IEntity.OnDelete.
Hook<Foo>.BeforeDelete += (s, foo) => {
  Console.WriteLine(foo);
};
Hook<Foo>.DeleteCommitted += (s, objectKey) => {
  Console.WriteLine(objectKey);
};

// Hook not only a a single class, but its entire hierarhcy
HookHierarchy<Foo>.BeforeDelete += (s, foo) => {
  Console.WriteLine(foo);
};
HookHierarchy<Foo>.DeleteCommitted += (s, objectKey) => {
  Console.WriteLine(objectKey);
};
```

Pretty much what we discussed I think. I want "hierarcial hooks" separated from the single-type ones, since we should advocate care when they are used. The can be quite expensive performance wise if used carelessly.

Just showing the two delete-related hooks, where ```BeforeDelete``` will be the new kid on the block. Each class expose two separate events for `InsertCommitted` and `UpdateCommitted`.

**Comment by miyconst** [comment]
Looks good to me.

Only one small note: To follow c#'s rules in here `(s, foo)` the `foo` should be `HookEventArgs : EventArgs`, not the instance of class `Foo` which is being Deleted/Updated/Inserted.

**Comment by per-samuelsson** [comment]
> I'll sum them up in separate comments below in a moment.

Continuing with the extended API. Basics in previous post.

### Extended API

Code first; comments below.

```C#

class Foo : IFoo {}
class Bar : Foo { }

// 1. The runtime callback allows cherrypicking of types to hook,
// and register them either by type or name at runtime.
var types = new[] { typeof(Foo), typeof(Bar) };

foreach (var type in types) {
  RuntimeCallback<Foo>.TriggeredBy(type).BeforeDelete += (s, foo) => {
    Console.WriteLine(foo);
  };
}

// 2. Registering a signature that can't be hooked itself, i.e IPerson
// in this case.
var persons = Db.Types.AllWithInterface<IPerson>();
foreach (var p in persons) {
  RuntimeCallback<IPerson>.TriggeredBy(p).BeforeDelete += (...) {...};
}

// 3. Registering on arbitrary type, with name
RuntimeCallback<Clown>.TriggeredBy("PerSamuelsson").BeforeDelete += (...) {...};

// 4. Using optional parameter to specify hierachial registration
RuntimeCallback<IFoo>.TriggeredBy(typeof(Foo), true).BeforeDelete += (...) {...};
```

The rationale not to use Hook in the name of the class is because it would be confusing since here, the generic argument is **not** the type being hooked (we can use generics for that, since we hook dynamically, runtime). The generic type instead specifies the signature of the callback.

Also note that doing `RuntimeCallback<Foo>.TriggeredBy(typeof(Foo)).BeforeDelete += (...) {...};` will perform the same thing as basic `Hook<Foo>.BeforeDelete += ...`.

Finally note [4], and the extra optional parameter to ```TriggeredBy```, specifying to register a hierarchial hook. It defaults to **false** in all registering methods.

**Comment by per-samuelsson** [comment]
> Only one small note: To follow c#'s rules in here (s, foo) the foo should be HookEventArgs : EventArgs, not the instance of class Foo which is being Deleted/Updated/Inserted.

Yeah, but how much of puritans do we want to be? Personally, I'd slightly favor the propsed solution meaning a few less characters to type (and objects instantiated). The custom EventArgs wouldnt really add anything...?

**Comment by miyconst** [comment]
Custom `EventArgs` could add something if we like. Lets say we want to read some value from a hook, the value may be stored inside the agrs.

If don't use `EventArgs`, then also don't use `sender` as it does not have any practical usage, does it?

**Comment by dan31** [comment]
@per-samuelsson @miyconst Maybe provide version with EventArgs and overload without EventArgs? Depending on what the caller code wishes. The latter will be used most of the time. I opt for less verbosity and indirection. Making object be part of EventArgs hides logic, and we shouldn't violate "Less code for more" principle.

**Comment by per-samuelsson** [comment]
>  I opt for less verbosity and indirection.

Yeah, this is one of the core principles of Starcounter, and the reason I suggested the design without ```EventArgs```. I too vote for this.

With that being said, it's also important to adhere to patterns "standard" .NET developers are used to, so @miyconst has a point to. This is somewhat of a hard call IMO. Each approach has benefits.

> If don't use EventArgs, then also don't use sender as it does not have any practical usage, does it?

Thats a valid point too. If we expose hooks as events, we should probably either support the "full" pattern (i.e use ```EventArgs```), or scrap the signature as a whole, i.e. not use ```sender``` either.

**Comment by per-samuelsson** [comment]
Just a little thing I noticed: in the [older API doc of EventHandler{T}](https://msdn.microsoft.com/en-us/library/db0etb8x(v=vs.100).aspx), the generic argument is constrained to be a derivate of ```EventArgs```, while [in the never](https://msdn.microsoft.com/en-us/library/db0etb8x(v=vs.110).aspx) (>= 4.5) it is not. This might indicate the community/MS is going in the direction of less verbosity too. They keep the sender argument though.

Maybe this is what we need to take this decision? We'll go with a signature that is the middle way - keeping the sender argument, but base our API on a direct database class (as suggested by my earlier https://github.com/Starcounter/Starcounter/issues/2770#issuecomment-111494526), and not an ```EventArgs``` type.

**Comment by miyconst** [comment]
Okay, lets go this way.

**Comment by dan31** [comment]
Let's decide as a rule and follow: we follow the most recent MS changes to align in our API's (coreclr5.0 and its libraries, and sometimes 4.6) and catch ourselves not falling back to existing/old APIs. @miyconst, @per-samuelsson, I see your agreement!

**Comment by miyconst** [comment]
The only reason why I like `EventArgs` is because it lets different hooks share information about an object, but I could not come with a good example where it could be needed.

**Comment by per-samuelsson** [comment]
With https://github.com/Starcounter/Starcounter/commit/14a6ab452df774e9bcb8134c464f2fe619f2cb24, this is now implemented and merged/pushed into develop/2.0.

To see the basics in action, [CommitHooksTest.cs](https://github.com/Starcounter/Starcounter/blob/develop/src/Samples/TestApps/CommitHooksTest/CommitHooksTest.cs) implement a simple regression test, run as part of nighly builds by default. Eventually, we should add extended tests that include the more advanced features, but I don't have time for this right now.

**Comment by per-samuelsson** [comment]
And oh, a small detail: I pass **null** as the sender argument to all delegates at this point. I guess this is not ultimate, but I'm unsure what to actually pass. I'm up for suggestions.

**Comment by miyconst** [comment]
@per-samuelsson could you please start a daily build for me? So I modify apps according to the new hooks api.

I also thought that current transaction should be passed as `sender`,

**Comment by miyconst** [comment]
In here https://github.com/Starcounter/Starcounter/blob/14a6ab452df774e9bcb8134c464f2fe619f2cb24/src/Starcounter/Hooks/Hook.cs
I see that you have written the meta comments for each hook, but for whatever reason they are not visible in VisualStudio intellisense, could you please take a look?

**Comment by miyconst** [comment]
Fixed all of the apps according to the new commit hooks.

**Comment by per-samuelsson** [comment]
> I see that you have written the meta comments for each hook, but for whatever reason they are not visible in VisualStudio intellisense, could you please take a look?

Writing XML doc is not enough for the comments to be visible in the Intellisense, they must be generated too. And we currently don't do that I think. :disappointed:

**Comment by miyconst** [comment]
For us it is obvious what each hook mean and when it is called, but someone new might now know, the comments would be really useful.

I can create a new issue, if you think this is an important task.

**Comment by per-samuelsson** [comment]
> I can create a new issue, if you think this is an important task.

I honestly don't know the state of our API docs, if they are supposed to be generated or not, and how to get them to turn up properly in the Intellisense. I guess its a task for @parherman? Or maybe @dan31 can provide some insight? I noticed [this comment by @dan31](https://github.com/Starcounter/Starcounter/issues/2757#issuecomment-110272609) some week ago. Maybe they somehow relate?

@miyconst, what about other standard APIs, like ```Db.Transact``` or ```Handle.GET```, intellisense show up for these in the same version?

**Comment by miyconst** [comment]
No, I don't see any comments for `Db.Transact` and `Handle.GET`.

**Comment by per-samuelsson** [comment]
> No, I don't see any comments for Db.Transact and Handle.GET.

OK, then this is part of a bigger problem though, probably caused by the expired license. Lets give @dan31 a chance to reply his thoughts, either here or in #2757.

**Comment by parherman** [comment]
Since this [commit](https://github.com/Starcounter/Starcounter/commit/9f49bbd7cd9f99e30117c4cdd31a1f864e18250d) we also copy Starcounter.XML, Starcounter.Bootstrap.XML, Starcounter.Apps.JsonPatch.XML, Starcounter.Internal.XML, Starcounter.Logging.XML, Starcounter.Hypermedia.XML, Starcounter.Node.XML, Starcounter.XSON.XML to Public Assemblies during build, so now there should be intellisense documentation using the latest installers.

@miyconst you can try this [installer](http://downloads.starcounter.com/download/Polyjuice/DevelopNightlyBuilds/2.0.3231.3) to verify!

**Comment by miyconst** [comment]
Yes, it works! Thank you.

**Comment by per-samuelsson** [comment]
This one is done.
