### ISSUE TITLE
Installer automation?

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2771]
Is it possible to run the installer automatically, without GUI interaction? I want to use this for automatic deployment of Starcounter instances.

**Comment by alemoi** [comment]
Thank you for the question! That was made some time ago, but then we abandoned the feature. We need to recover it now.

**Comment by parherman** [comment]
@mtornwall, @alemoi This is a duplicate of #2609, I will close this and we can continue the discussion in that issue!
