### ISSUE TITLE
Switch pnext to rely on Level1 from develop

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2776]
Currently, usually **Level1** from **next** is used for building **pnext**, since it has dependencies to some bits of **Level1**.
Can we start using **Level1** from **develop** instead of **next**? I have tested on build server and both pnext build projects succeeded.
Can the build projects `pnext-daily-windows` and `pnext-daily-linux` be switched to **develop** of **Level1**?

@eriohl @parherman ?

The reason is that **next** is not maintained any more and currently the only way to get important changes from **develop** to be used in **pnext** is by using actual **develop**.

**Comment by parherman** [comment]
pnext-daily-windows switch to build with develop branch of level1.

From the looks of it pnext-daily-linux dose not currently build correctly with develop, investigating...

**Comment by k-rus** [comment]
> pnext-daily-windows switch to build with develop branch of level1.

I raised questions if it is doable or not. According to @eriohl (see [this comment](https://github.com/Starcounter/CompanyTrack/issues/78#issuecomment-111972583)), **next** of **Level1** must be used with **pnext**. Thus, can you change back to **next** in the build project? Unfortunately, we have to keep this hassle with merging certain files from **develop** to **next ** for now.

**Comment by eriohl** [comment]
No. You misunderstand. You can run PNEXT with level1 DEVELOP. Just disable the projects dependent on the IPC (which @parherman is doing). I will enabled them when needed and then build with NEXT. So as long as you do not delete NEXT branch until these projects are deleted then I'm good.

**Comment by k-rus** [comment]
> No. You misunderstand. You can run PNEXT with level1 DEVELOP. Just disable the projects dependent on the IPC (which @parherman is doing). I will enabled them when needed and then build with NEXT. So as long as you do not delete NEXT branch until these projects are deleted then I'm good.

Sorry, for misunderstanding. Is it possible to run tests which requires to create a database, create tables, load data and then read data from the database on without NEXT branch of LEVEL1, i.e., on DEVELOP branch? I need to run such tests for the meta-layer and IMHO such tests should be enabled on the build server.

**Comment by eriohl** [comment]
Yes. Kernel function tests works. DNX host will work. Anything dependent on legacy scheduler will not.

**Comment by k-rus** [comment]
> Yes. Kernel function tests works. DNX host will work.

Great! Then I am for having build project to be running on DEVELOP. It would be nice that kernel function test is also part of the build, but I don't know how much work to fix this.

Actually, I was not able to build PNEXT with DEVELOP locally. I cloned Level0 at PNEXT and Level1 at DEVELOP, generated the solution file of Blue with CMake, but building in Debug from VS failed with:

>Severity	Code	Description	Project	File	Line
Error	C1083	Cannot open include file: '../../Starcounter.ErrorCodes/scerrres/scerrres.h': No such file or directory (compiling source file C:\GitRepositories\Starcounter\Level1\src\Chunks\BMX\bmx.cpp)	bmx	c:\gitrepositories\starcounter\level1\src\chunks\bmx\chunk_helper.h	11

If I use NEXT of Level1, then compilation works fine.

@parherman What is the difference between local build and build server? Is it due to Debug/Release configuration or something else? Can the repo be fixed to work with DEVELOP locally?

**Comment by parherman** [comment]
I have now commented out all the Chunks dependencies in level0, [link to commit](https://git.starcounter.org/BlueStar/level0/commit/d339d944d14c15c17dcd7f4be479986b7d7f251a), so that pnext-daily-linux builds correctly and switched both jobs to develop branch for level1

**Comment by k-rus** [comment]
> I have now commented out all the Chunks dependencies in level0, link to commit, so that pnext-daily-linux builds correctly and switched both jobs to develop branch for level1

I confirm that building locally work now with DEVELOP after I pulled this change.

**Comment by parherman** [comment]
@k-rus what tests are you running that should run on the build server?

**Comment by k-rus** [comment]
> @k-rus what tests are you running that should run on the build server?

I don't run, but it would be great to have the test described in Starcounter/CompanyTrack#79
However, it requires to at least write a bat file, which will prepare environment for the test, and another file to clean the environment after the test. Or something like this.

**Comment by parherman** [comment]
This is done and pnext builds with develop in the build jobs now so i'm closing this issue
