### ISSUE TITLE
Starcounter uninstaller does not remove version folder

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2777]
When uninstalling Starcounter, it's version folder is not being removed, and after some updates I have huge number of `2.0.xxxx.3` folders in `C:\Program Files\Starcounter`.

Uninstaller should not only remove the version folder, but also `Starcounter` folder.

@andwah is this your responsibility?

**Comment by warpech** [comment]
Confirmed, happens to me as well.

**Comment by andwah** [comment]
It's in the Installer Engine, but i can take a look at it.

**Comment by alemoi** [comment]
There is a task that deletes the internals installation directory like a few seconds the process exit (because otherwise we have running processes and corrwsponding binaries in that directory) . I can check it.

**Comment by andwah** [comment]
@alemoi okey, thanks

**Comment by andwah** [comment]
This has been fixed, 
The version number will be added (under the hood) to the installation path that the user specifies.
When uninstalling/upgrading the version folder will be deleted and the parent path will be left along

**Comment by alemoi** [comment]
:+1: will check later how it works out!

**Comment by miyconst** [comment]
Build `2.0.3226.3` works for me. It leaves `C:\Program Files\Starcounter` folder, but removes `C:\Program Files\Starcounter\2.0.3226.3` folder.
