### ISSUE TITLE
Pass context information to kernel as argument (rather then getting in from the thread)

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#2779]
Pass context information to kernel as argument (rather then getting in from the thread).

For example:

Interface function:

```C++
extern uint32_t star_get_long(uint64_t record_id, uint64_t record_ref, uint32_t column_index, int64_t *pvalue);
```

Will be replaced with

```C++
extern uint32_t star_get_long(void *context, uint64_t record_id, uint64_t record_ref, uint32_t column_index, int64_t *pvalue);
```

(Exactly what this "context" will contain and called is currently being debated).

Note that this will not fundamentally change how anything actually works. But it will have a pretty big impact on interface and so break compatibility with all current clients implementations. The purpose of this is to make integration easier in future.

**Comment by eriohl** [comment]
Now "works" (in the sense that the code generally does what it's supposed to although generally also in a rather inefficient way).

New API is built around 3 basic types: Context, transaction and iterator.

All transaction is created within a context. An iterators is created within a transaction.

![objmod](https://cloud.githubusercontent.com/assets/3438751/8291482/3f7f1606-192a-11e5-85d6-da0811296c6f.png)

All control and responsibility over threading has been moved to the client.

Example:

```C++
uint32_t my_print_age(void *context, uint64_t record_id)
{
  static const uint32_t age_column_index = 1;
  uint32_t e;
  uint64_t t1;

  e = star_context_create_transaction(context, 0, &t1);
  if (!e)
  {
    uint64_t record_ref;
    e = star_transaction_lookup(t1, record_id, &record_ref);
    if (!e)
    {
      int64_t age;
      e = star_transaction_get_long(t1, record_id, record_ref, age_column_index, &age);
      if (!e)
        printf("my age is %ld\n", age);
    }
    e = star_transaction_commit(t1, 1);
  }
  return e;
}
```

There as still some inconsistencies in the API that is being worked out. And then we will move on to redesigned the internals to work more efficiently with the new API. But it should now be working good enough to start building on it.

**Comment by eriohl** [comment]
Done.

Not entirely happy with iterator interface, too much overhead probably, but I think we'll work on this one in the scope of new query processing so optimizing this is probably premature.

**Comment by dan31** [comment]
Yes, let's view it in complex while approaching iteration API's in new SQL proc.
