### ISSUE TITLE
Map/OntologyMap should work disregardless of "Polyjuice flag"

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2783]
The features of URL mapping, currently exposed as `Polyjuice.Map` and `Polyjuice.OntologyMap` rely on Polyjuice flag being enabled or disabled per database. 

Polyjuice installer sets the flag by default to ON. Starcounter installer sets it by default to OFF.

Because of that, that apps that use these features cannot work in the default installation of the Starcounter editition.

I propose that Map/OntologyMap should work disregardless of "Polyjuice flag".

After this is done, we can expose Starcounter edition installer instead of Polyjuice edition installer as the downloadable installer on starcounter.io.

In long term, I would like to see Map/OntologyMap merged into a single method and exposed as part of Starcounter API, not "Polyjuice API". That should be a different issue though.

cc @dan31, @alemoi

**Comment by k-rus** [comment]
I am wonder: is there definition what is the standard Starcounter and Polyjuice Starcounter? What are the  roadmaps for both editions?

**Comment by dan31** [comment]
@k-rus No editions, check that for clarification: https://github.com/Polyjuice/Polyjuice/issues/2#issuecomment-113161046 . ```Polyjuice```-named APIs will be soon renamed, entire mapping becomes a feature of Starcounter. Three kinds of core mapping has been recently identified, including data mapping, and are in process of logical alignment.

**Comment by Starcounter-Jack** [comment]
All technology will be Starcounter.

**Comment by k-rus** [comment]
If I don't mistake is that Polyjuice edition uses Society Objects, while Starcounter has empty database with only meta-tables. I believe it is good to keep these two setups. What are the plans? May be this should be presented in a separate issue?

**Comment by warpech** [comment]
This issue applies to Starcounter in general, with any data model, not only Society Objects.

> If I don't mistake is that Polyjuice edition uses Society Objects, while Starcounter has empty database with only meta-tables. I believe it is good to keep these two setups. What are the plans? May be this should be presented in a separate issue?

Currently, Starcounter edition **does contain** SO dlls. They are just not loaded to the database if the database Polyjuice flag is OFF. Any changes to this should be a separate issue.

**Comment by dan31** [comment]
@k-rus, to add to what @warpech explained: we attempt to make a data and app integration feature be intrusive and on-demand essential feature of Starcounter. Currently it is controlled by "Polyjuice" flag, which is set per-database. So today, if you install Starcounter, it is very easy to start developing Polyjuice applications with it by changing a flag. In future we think that the flag will be set automatically, once any data/app integration feature (that we used to call Polyjuice-related) is used.

**Comment by warpech** [comment]
This issue can be closed now. 

UriMapping.Map/UriMapping.OntologyMap is controlled using `UriMappingEnabled`, `OntologyMappingEnabled` flags. Docs here: http://starcounter.io/guides/database/database-configuration/
