### ISSUE TITLE
Console WriteLine ConsoleOuputRestHandler.cs should assume that there is no app running

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2784]
We have system components that are doing Console.WriteLine (e.g. static file server) and that are outside of any app scope (no Application.Current set).

ConsoleOuputRestHandler.cs GetAppName() throws exceptions because Application.Current is not set.

To reproduce run an app with static files, e.g. Launcher, attach the debugger to sccode.exe set catching all exceptions and then go to 127.0.0.1:8080/launcher in browser so static files are retrieved. And you will see the following:

![image](https://cloud.githubusercontent.com/assets/208134/8231653/4f709444-15ca-11e5-9795-e81aac06e8e6.png)

**Comment by andwah** [comment]
Thanks for reporting.. i will not be able to look into it tonight, maybe tomorrow.

**Comment by andwah** [comment]
Added a null reference check
