### ISSUE TITLE
Wrong WebSocket closing status code in case of malformed JSON-Patch

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2785]
When testing #2332 I discovered that sometimes WebSocket disconnects with wrong closing [status code](https://tools.ietf.org/html/rfc6455#section-7.4.1).

If WebSocket disconnects because of an uncaught exception in C# app code, then the status code is `1011` as could be expected.

If WebSocket disconnects because of a malformed patch, then the status code is `1000`, which is incorrect, because RFC6455 defines `1000` as "a normal closure, meaning that the purpose for which the connection was established has been fulfilled"

An easy way to reproduce such error with current version of PuppetJs is shown on the screenshot:

![image](https://cloud.githubusercontent.com/assets/566463/8357325/af220676-1b5a-11e5-9067-9b3e3632e39a.png)

**Comment by alemoi** [comment]
I looked at Json patch code and in this case an exception with message is thrown: No value found in patch. I treat all exceptions the same, that's the result. I guess this one is quite low prio?

**Comment by warpech** [comment]
Yeah, the same exception message can be seen on the screen shot. I think that the exception message is OK. Only the WebSocket closing status code is wrong: `1000`. I would expect `1008` or `1011`.

Also see: http://stackoverflow.com/questions/22587438/websocket-close-code-1002

Yes, this is low priority.

**Comment by chrhol** [comment]
I will change this. I'm doing some other stuff with patches and errorhandling on the server and this is a quite small change.

**Comment by chrhol** [comment]
I've pushed a fix for this now. A more correct errorcode is sent ot the client.
