### ISSUE TITLE
Migrate extension to Visual Studio 2015

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2787]
Making a prototype first. Then we need to decide when to migrate Level1 to 2015 (which I think will be a prerrequisite; maybe its doable by just installing VS SDK 2015 though).

**Comment by per-samuelsson** [comment]
> Then we need to decide when to migrate Level1 to 2015 (which I think will be a prerrequisite; maybe its doable by just installing VS SDK 2015 though).

It turned out that we don't need to add any build-time dependency at all, as far as I understand. It should be enough to build the extension as part of Level1 in VS 2012 still, and it even looks as if we don't need to install the 2015 SDK.

So, things have turned out good. This is now "done". I have been able to produce a deployment package for VS 2015, which I have installed, uninstalled and tested with the templates to produce applications and to run and debug them in VS 2015. It works.

Also, I have made all the installer engine work too now, so the installer is ready for it - its not just a prototype. 

The small thing I need help with is to add it to the installer GUI - basically just adding the checkbox, and have that checkbox enable/disable the new configuration option I have introduced in the installer. Can either @andwah or @alemoi help me with that maybe?

One cool thing: all tests I have done, I have done targeting Visual Studio 2015 **community edition**. Hence, we can now support the IDE-integrated development experience even to those that dont want to pay for a VS license. 

On the contrary, I have **not** tested with VS 2015 Professional or the new Enterprise edition (introduced in 2015). But I'm quite confident it will work there too, without any additional work. Its basically just to get a box set up with those versions and test it. Maybe @parherman can do so eventually?

I'll wait to merge this into ```develop``` until monday, so that we can have a reconciliation about it. If anyone want to test Starcounter in VS 2015 before that, just [pull the 2787 branch]( https://github.com/Starcounter/Starcounter/tree/issue/2787), build it and give it a go.

**Comment by per-samuelsson** [comment]
Thanks to @parherman, this is now tested, and I have merged it and pushed it to develop. Everything is in place except for making the GUI-part of the installer, i.e. exposing this as a checkbox and set the corresponding installer flag. I'll open a separate issue for that.

**Comment by per-samuelsson** [comment]
> I'll open a separate issue for that.

#2789 created. To test the extension before that, it can be installed/uninstalled manually. Just get a copy of VS 2015 (RC at this point), and doubleclick `Starcounter.VS14.vsix` (in `%StarcounterBin%`) and try it out.

**Comment by per-samuelsson** [comment]
Reopening this, since it turned out not to work properly in the installer. I will try fixing that and repush it.

**Comment by parherman** [comment]
Yes I did not test this properly yesterday! @per-samuelsson Here is a screenshot of the problem with the installer:

![acceptance_tests](https://cloud.githubusercontent.com/assets/231535/8430607/fe56c462-1f32-11e5-83d1-884c69e722b7.png)

**Comment by per-samuelsson** [comment]
> Here is a screenshot of the problem with the installer:

Thanks! I got it from @chrhol too. :) It seems the outer WPF installer and the inner installer engine is more interrelated than I knew, but with the help of @alemoi I think I have a fix for this shortly. Its just a matter of testing it again though, and then I can hopefully remerge it.

**Comment by per-samuelsson** [comment]
Me and @parherman have now got this to work again, so now it should be possible to run the installer. Closing this again.

**Comment by warpech** [comment]
I tried to install the VS 2015 extension manually, but there no `Starcounter.VS14.vsix` in `%StarcounterBin%` (using Starcounter 2.0.3268.3). Was it ever included in the installation?

**Comment by alemoi** [comment]
I have finalized the started work and VS 2015 extension is now available in installer.

**Comment by per-samuelsson** [comment]
> I have finalized the started work and VS 2015 extension is now available in installer.

:+1:
