### ISSUE TITLE
Can we remove version folder from the installation path?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2788]
The default installation path for Starcounter is: `C:\Program Files\Starcounter\2.0.XXXX.3`.

Two different Starcounter versions cannot live alongside and can not even be installed, what the `2.0.XXXX.3` folder is for then?

I often work with installed javascript files from `C:\Program Files\Starcounter\2.0.3237.3\Polyjuice\StaticFiles\sys` folder, and have some VisualStudio projects to access `PuppetJs`, `starcounter-debug-aid`, `puppet-client` etc.

Every time I update Starcounter, I have to update the `.sln` files. Could we remove the `2.0.XXXX.3` from default installation path?

**Comment by warpech** [comment]
+1

**Comment by dan31** [comment]
It is reasonable, since developers barely would ever had 2 versions of SC installed and moreover how would you make them run parallel and why. @alemoi, any principal objections to that step, what do you think?

**Comment by dan31** [comment]
This will likely also solve the path creeping issue in your projects when upgrading Starcounter.

**Comment by warpech** [comment]
In case someone wants to have multiple versions of Starcounter installed, they could still potentially install it in a custom path.

**Comment by alemoi** [comment]
I guess the reasons are only historical when we wanted several versions at a time. One more cool addition will be that we would not need to restart cmds :) How about that?? :smile_cat:

**Comment by miyconst** [comment]
Looks like everyone likes my idea ;-)

**Comment by dan31** [comment]
No objections, good to go. @alemoi?

**Comment by alemoi** [comment]
I think its all fine! However, @andwah implemented some recent changes that we should take into account in installer GUI. So we must do this changes when I and him are both available.

**Comment by malx122** [comment]
Bump! Was has happened here? Seems everyone was ok with it? Was going to start the same issue when I found this one.

**Comment by miyconst** [comment]
@malx122 what Starcounter version do you use?

The version folder is removed for quite some time.
Current default installation path is `C:\Program Files\Starcounter`.

**Comment by miyconst** [comment]
Closing this issue.

The version folder is removed, checked with Starcounter `2.1.352`.

**Comment by malx122** [comment]
Strange, it seems so for me as well. I just thought it was yet there since I needed to restart my command prompts to find "star.exe" in path after I installed a new version... Must have been something else that failed.
