### ISSUE TITLE
Expose new VS 2015 extension in the installer GUI

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2789]
Tails #2787. Its basically about adapting the installer GUI, exposing the flag `ConstantsBank.Setting_InstallVS2015Integration` as a checkbox. Everything else is prepared for.

Not sure when this should be done, and if its best done by @andwah or @alemoi or anyone else. I guess @dan31 can set a prio.

**Comment by dan31** [comment]
@alemoi, @parherman will push it to "develop", would you add a checkbox in Installer?

**Comment by alemoi** [comment]
I have finalized the started work and VS 2015 extension is now available in installer.

**Comment by per-samuelsson** [comment]
> I have finalized the started work and VS 2015 extension is now available in installer.

Then we can close this, right?
