### ISSUE TITLE
Change session WebSocket upgrade URI

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2791]
Currently, the REST URI for a session looks like `/__default/D11C498A1A5F64ABD0000010`
The WebSocket upgrade URI for the same session looks like `/__default/wsupgrade/D11C498A1A5F64ABD0000010`

The `/wsupgrade` parameter in the above URL is hardcoded in an ugly way on the client: https://github.com/PuppetJs/PuppetJs/blob/d04702dcf4377f4d13133cca10f9b7241aa0fb6a/src/puppet.js#L187

The same day a fix for this lands in `develop`, it must be fixed in PuppetJs issue: https://github.com/PuppetJs/PuppetJs/issues/60. PuppetJs needs to be upgraded in https://github.com/Starcounter/Starcounter/tree/develop/src/BuildSystem/Polyjuice/StaticFiles/sys

---

[Current spec](https://github.com/PuppetJs/PuppetJs/wiki/Server-communication) does not mention anything about WebSocket puppet connections (only REST is discussed there), but it should be assumed that the WebSocket upgrade URI is identical to the REST URI. (there is an issue to write a proper spec: https://github.com/PuppetJs/PuppetJs/issues/61)

**Comment by miyconst** [comment]
@chrhol, please notify me when there is something to test.

**Comment by chrhol** [comment]
I'm working on this now. Should I push the changes to develop and you will fix PuppetJs today, or is it better to push to a separate branch until you are finished on your side?

**Comment by miyconst** [comment]
I like the first way, push to develop, give me a link to daily build, and I fix PuppetJs.

**Comment by chrhol** [comment]
Changed pushed to develop now. A daily build can be downloaded here: http://downloads.starcounter.com/download/Polyjuice/DevelopDailyBuilds/2.0.10094.2
