### ISSUE TITLE
Using filters with unregistered handlers

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2795]
As discovered in https://github.com/Polyjuice/AppStoreClient/issues/6#issuecomment-118050724, `AddFilterToMiddleware` does not work for requests that are not matched against explicitly defined handlers.

The filtering functionality should be expanded to allow:

1. a global filter that adds a HTTP header to any response, regardless of the HTTP method. Compare with:
  -  http://enable-cors.org/server_expressjs.html
2. catching unhandled requests to respond with a nice 404 page. Compare with: 
  - https://github.com/koajs/examples/blob/master/404/app.js 
  - http://www.hacksparrow.com/express-js-custom-error-pages-404-and-500.html

**Comment by alemoi** [comment]
Thank you for the issues. This works in the way how static files serving is currently implemented. I will think how to change this.

Other thoughts: I started to dislike the name "middleware filters" :) I was thinking to also add filters for outgoing responses, so I thought to have: incoming filters and outgoing filters. What do you think?

**Comment by alemoi** [comment]
Ok, I just tested the modified way of codehost-dependent static file resources handlers and it seems working fine (I'm talking about adding custom 404 page). It also solves current big problem of removing static files paths from codehosts that died (now you need to restart the whole sc). It requires however that each codehost has a unique user port, which is a requirement nowadays anyway. Will push changes tomorrow probably.

**Comment by alemoi** [comment]
I have added some experimental code in `Handle.AddOutgoingFilter` and `Handle.SetCustomResourceNotFoundResolver` via cedf011b66a3b737c6de621c76f3ea8e3dd60427
An example of a 404 page can be found in: https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.Administrator/Server/Program.cs#L104

**Comment by warpech** [comment]
Discussed with @alemoi. The original problems can be fixed this way:

1. Not a global filter, but a wildcard handler can be used: `Handle.OPTIONS("/people{?}")`
2. 404s in current app can be solved with `Handle.GET("/people{?}")`. Global 404s can be done with `SetCustomResourceNotFoundResolver` (needs better name)

@alemoi will explain this on the .io website (I will create separate issues for that)

**Comment by alemoi** [comment]
`SetCustomResourceNotFoundResolver ` is now gone again and replaced with new schema. I described the new schema in blog post and network guide: http://starcounter.io/guides/network/handling-responses/

**Comment by miyconst** [comment]
Good guide :+1: . I have fixed a couple of typos.

**Comment by warpech** [comment]
Case closed, thanks :)
