### ISSUE TITLE
Switch Windows pnext build project to use VS 2015

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2797]
The discussion about switching building pnext/DNX to VS 2015 was [here](https://github.com/Starcounter/CompanyTrack/issues/68#issuecomment-107837432). The conclusion is that it should be possible to build .NET 4.6 and .NET Core 5 versions of Starcounter in VS 2015.
VS 2015 contains features, which are extremely important for cross-platform code of QP.

QP group needs to know if the build projects for Windows pnext branch will be moved to VS 2015 and when. This is a kind of showstopper for us.

I remember that @parherman installed VS 2015 on a build agent, however PNext-Daily-Windows uses VS 2012.

**Comment by parherman** [comment]
I understand this as QP group needs pnext to build in VS2015.

From now on PNext-Daily-Windows will build with VS2015/Boost 1.58, as a consequence it will only run on scbuildserver2

I will close this now - please open again if there are issues

**Comment by k-rus** [comment]
:thumbsup:
