### ISSUE TITLE
Application name can only contain letters, numbers and underscores

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2801]
It is a common practice to put projects of same solution into sub-namespaces. Something like:

- MainApplication;
- MainApplication.Database;
- MainApplication.SubApplication1;
- MainApplication.SubApplication2;
- MainApplication.SubApplication3;

But Polyjuice does not allow application with `.` (dot) in the namespace, such applications fail to start with the following error:

```
Application name can only contain letters, numbers and underscores. Application name that is not allowed: MainApplication.SubApplication1
```

**Comment by mtornwall** [comment]
+1

**Comment by dan31** [comment]
+1

**Comment by alemoi** [comment]
There were some reasons of not using the dot. Right now I don't remember exactly though :) Something with places where `StarcounterEnvironment.AppName` is used. Maybe @per-samuelsson remembers?

**Comment by k-rus** [comment]
> There were some reasons of not using the dot. Right now I don't remember exactly though :) Something with places where StarcounterEnvironment.AppName is used. Maybe @per-samuelsson remembers?

@alemoi Thank you for mentioning this!
It might be even several reasons why identifiers are not allowed to contain dot. One is that dot is a separator between identifier and application name is an identifier, which was important for future SQL. I think this can be changed but this requires deep planning for DNX.

**Comment by miyconst** [comment]
Can the app name be different from it's namespace? I mean, what if the app name will be constructed as `Namespace.Replace(".", String.Empty)`?

**Comment by per-samuelsson** [comment]
> Maybe @per-samuelsson remembers?

I remember we had quite a few discussions about it, and I'm quite sure there were some issue too. But I dont remember the core reason. I *think* it had to do with polyjuice/launcher and/or possibly handler registration, and I'm quite sure it was not me that finally implemented the restriction.

Maybe look in git history for the commit that implemented the relevant error messages to find some clue there?

**Comment by k-rus** [comment]
> Can the app name be different from it's namespace?

I think there is no direct relationship between app name and namespace. Namespace is defined in the source code of an app, it can be more than one, it can be omitted, and it can be different. May be there are some new limitations on apps and namespaces that I am not aware of.

**Comment by per-samuelsson** [comment]
> I think there is no direct relationship between app name and namespace.

It's not, most defintely. At least not in standard Starcounter. Maybe Polyjuice adds some restrictions on top though.

Application name -> namespace is not even 1-1. An application can obv be modularized and define a whole range of namespaces. Application names are a management feature, used to distinguish applications within a given code host.

**Comment by miyconst** [comment]
What is the `AppName` then? How do I modify it? Let's assume my .exe is `Main.Sub.exe`, my namespace is `namespace Main.Sub`, and I want the app name be `MainSub`, how to set that up?

**Comment by mtornwall** [comment]
@miyconst I've tinkered a bit with this lately and it appears that the Starcounter application name is copied verbatim from the assembly name as configured in the project properties dialog.

**Comment by k-rus** [comment]
Sorry, that we haven't replied the last question. I think @per-samuelsson will confirm @mtornwall's finding.

**Comment by per-samuelsson** [comment]
> @miyconst I've tinkered a bit with this lately and it appears that the Starcounter application name is copied verbatim from the assembly name as configured in the project properties dialog.

The application name is taken from the name of the executable, so your finding is basically correct. However, this can also be overridden with a switch, ```--name``` (query `star` without arguments for help). This works equally in VS and in the CLI.

The CLI approach:

```
c:\foo>star donkey.exe --name=kong
```

In VS you set the same thing up by specifying it in `Project | Properties | Debug | Command line arguments`. In that text box, you can specify anything you can specify to `star.exe`, including the application name. Try adding `--name=foo` to it, and your application with boot and run with the name "foo".

**Comment by miyconst** [comment]
Closing the issue, as there is actually a way to change application name.
