### ISSUE TITLE
Invalid session sent from the gateway to the codehost even though a session exists.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2803]
When session is specified as parameter in the uri, the gateway sometimes overwrites correct sessioninfo in the datablob with invalid values which leads to an IncorrectSessionException in the codehost.

As far as I understand, this happens when the referer (or x-referer) headers have a value of a specific length.

The following condition will be true even though it shouldn't (in http_proto.OnHeaderValue)

```c++
if ((MixedCodeConstants::SESSION_STRING_LEN_CHARS < length) &&
      (*(session_id_start - 1) == '/'))
```

Can be reproduced by running the Products-app only and calling [http://localhost:8080/products](http://localhost:8080/products) from a browser.

Reported originally in https://github.com/Polyjuice/Products/issues/4

I will assign it to @alemoi  even though hes on vacation. If this gets more urgent I might try to fix it but I rather not if possible :)

**Comment by alemoi** [comment]
Thanks for reporting! I will take a look at this when have time!

**Comment by alemoi** [comment]
I went through the specs in https://github.com/Starcounter/Starcounter/issues/2713
and for `Referer` and `X-Referer` I follow the formats from there (e.g. `X-Referer: 35AA181932856ED910000000`).

**Comment by alemoi** [comment]
I just added the fix via 74870bc6a2a03ed955ac75079c1aa7ef569867b0 and Products are loading fine. But when I press `Add new product` I have an exception on the client: `throw new Error("Given version was already applied.");` in `json-patch-queue.js`

**Comment by alemoi** [comment]
Ok, after I added another patch 80d6afe8422cf0e69dcc187905455571f53f95fe to read `X-Referer` and `Referer` as "ends-with", then all started to work (no more JS error above). That however means that https://github.com/Starcounter/Starcounter/issues/2713 specification is not really correct (about `X-Referer: 35AA181932856ED910000000`) :)

Still would like to get some confirmation that stuff works :) Thanks!

**Comment by miyconst** [comment]
@alemoi thanks. The build `2.0.3257.3` works good. I close the original issue and leave this one for you.

**Comment by alemoi** [comment]
Thanks for response! Closing this one as well!
