### ISSUE TITLE
Starcounter & Puppet & Handsontable

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2805]
In my Polymer 1.0 demo application (https://github.com/PuppetJs/PuppetJs/issues/65) I tried to use Handsontable (http://handsontable.com/) and met some restrictions/limitations.

Here is the list of my questions/suggestions:

- How to define and fill plain data array for Handsontable in json view model?
- I can define an array inside json view model like `"Data": [""]`, but this will be array of strings only.
- Is there a way to subscribe to view model array changes? `void Handle(Input.Array Action)` does not exists.
- If I have an array with two objects on client side, and then insert an object on position 1 it is recognized by `PuppetJs` as 
```js
var oldObj = array[1];
array[1] = newObj;
array.push(oldObj);
```
I understand why it acts like this and what it means, but this is a contradictory of what is actually happened.
- Replacing all elements inside an array on server side acts like replacing entire array. Handsontable has to be re-bound after each such manipulation (for example server side pagination or sorting).
- Operation `add` to array is accepted, but ignored by server.

The view model:
```json
{
    "Cars": [
        {
            "Number$": "",
            "Brand$": "",
            "Model$": ""
        }
    ]
}
```
The patch:
```json
[{"op":"add","path":"/Cars/3","value":{"Number$":null,"Brand$":null,"Model$":null}}]
```

The server accepts the patch and responses with correct *increment session* patch, but the new array item is not created.

- Unable to create array of arrays in view model:
```json
"DataRows": [ [ "" ] ]
```
Application fails to start with the following exception:
```
Expected "Object, string, boolean, event, number" but found a Array
  ([String ("",Starcounter.Internal.JsonTemplate.DebugInfo)],
   Starcounter.Internal.JsonTemplate.DebugInfo)
```

**Comment by chrhol** [comment]
I will try to answer your questions in order.

> How to define and fill plain data array for Handsontable in json view model?
I can define an array inside json view model like "Data": [""], but this will be array of strings only.

If you want to have an array of different items you define it as an empty array, `"Data": []`, in that one you can put all different kinds of items.

Currently it's a bit bulky to work with primitive values in arrays. See #237.

> Is there a way to subscribe to view model array changes? void Handle(Input.Array Action) does not exists.

No there is no way because the client is not allowed to add items to the array. The client is only allowed  to request a change for a single value and then it is up to the server to decide what to do.

> If I have an array with two objects on client side, and then insert an object on position 1 it is recognized by PuppetJs as

This I dont know. Is it a problem with the patches sent from the server or how it's applied on the client?

> Replacing all elements inside an array on server side acts like replacing entire array. Handsontable has to be re-bound after each such manipulation (for example server side pagination or sorting).

This is implemented like this by purpose to decrease the overhead in sending a lot of patches. Maybe we need to rethink this part if it messes up bindings on clients.

> Operation add to array is accepted, but ignored by server.

It's not accepted, but I think the error is suppressed by default. We had some discussion on how the server should work together with versioning and I think I did not implement everything according to the decisions made (see #2470). I will take a look and change the needed parts.

> Unable to create array of arrays in view model:

This should work, and I thought I fixed it when I added the support for more flexible arrays and values in JSON-by-example. I will take a look.

**Comment by chrhol** [comment]
Added a separate issue for the last comment, arrays in arrays: #2806

**Comment by miyconst** [comment]
@chrhol thank you for the answers. This issue is not something to fix, to change, to do immediately. 

These points just indicate problems with Starcounter & Handsontable integration. Starcounter might/should not fix/support all of the points.

**Comment by miyconst** [comment]
I am not sure this is a bug, if client sends a replace patch to an array item which is not exists, then server exception happens:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
```

**Comment by miyconst** [comment]
Here is the issue with details of the previous error: https://github.com/Starcounter/Starcounter/issues/2812

**Comment by miyconst** [comment]
>No there is no way because the client is not allowed to add items to the array. The client is only allowed to request a change for a single value and then it is up to the server to decide what to do.

Looks like I can't replace entire array either. The following example does not work:

The model:
```json
{
    "SortColumns$": [""]
}
```

The patch:
```js
{
    op: "replace",
    path: "/SortColumns$",
    value: { "FirstName", "LastName" }
}
```

**Comment by chrhol** [comment]
Sorry, I missed a word before. The client is only allowed to request a change for a single **primitive** value. That is a change for number, boolean or string. Replacing objects or arrays is not allowed.

**Comment by miyconst** [comment]
Do we plan to add support for adding items for array with primitive values?

**Comment by chrhol** [comment]
> Do we plan to add support for adding items for array with primitive values?

Do you mean to add it on the server or support for the client to add it? As for the client it's a good question. An array of primitive values falls somewhere in between.

The basic criteria is that the client is not allowed to change anything at all in the viewmodel. It can suggest a change for the server to decide. For convenience we have implemented this as the client sets a value in the viewmodel, but it's always the server that decides. And to keep the protocol and the handling as simple as possible we only allow single primitive values. 

I'm not sure here for an array with primitive values. I think to allow it would make things more complex and you can solve this behaviour in other ways, for example having a inputfield outside the array which when updated adds an item to the primitive array.

**Comment by miyconst** [comment]
Yes, I was asking about server side support.

>for example having a inputfield outside the array which when updated adds an item to the primitive array.

I used exactly same approach.

Though in some situations it is very frustrating, for example a custom web component which does some logic over an array. The component has "Add" function. The function should be hacked or replaced to make the component work on top of Starcounter view model object.

Instead of inserting an item to the array it should pass two values to server through two fields: 
- The value being inserted.
- The index where row being inserted.

**Comment by miyconst** [comment]
Closing this issue as handsoncode guys are working on handsoncode-invoicedemo.
https://github.com/handsoncode-apps
