### ISSUE TITLE
Test gets ignored instead of failing on the buildserver

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2813]
Created by @alexanderstc in Starcounter/CompanyTrack#83:

If, in the level0/src/tests/\metalayer_functest/CMakeLists.txt rename run_metalayer_functest.bat into whatever.bat, instead of failing on the build server the test gets ignored.

In general: it is important that build fails on everything that is not expected, instead of ignoring and succeeding build.

**Comment by parherman** [comment]
Unfortunately the test report parser that we use to parse and present the results from ctest in TeamCity, sees the result "The following tests FAILED: 22 - metalayer_functest (Not Run)" as a ignored test!

I have updated the job to fail if ctest has a non zero exit code, so the job will now fail with this example with "Tests failed" in the build log, but in the test report form TeamCity the test will show up as "ignored"

[Example log](https://scbuildserver/viewLog.html?buildId=30021&tab=buildResultsDiv&buildTypeId=Starcounter_WindowsPNextDaily)

**Comment by alexanderstc** [comment]
I confirm the resolution, shall we close this?

**Comment by parherman** [comment]
Yes, I will close it
