### ISSUE TITLE
Middleware filters interfere with internal SC REST calls

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2815]
One of my applications installs a strict middleware filter to prevent unauthenticated clients from accessing any resource outside the `/authentication` namespace. Since I will run a known set of apps in a controlled environment I thought this would be okay, if a bit unorthodox. :-)

Unfortunately it seems that middleware filters also affect internal Starcounter REST calls. Effects include:

* `star.exe` is effectively disabled; not possible to start or stop apps.
* Web-based administrator is rendered completely powerless.

It seems to me that user-installed middleware filters shouldn't affect Starcounter's internal requests.

**Comment by alemoi** [comment]
Thank you for the question! Internal calls should not be affected at all. It must be a bug or something. If you can describe simple steps to reproduce, I can take a look!

**Comment by mtornwall** [comment]
Try this:

    Handle.AddFilterToMiddleware(request =>
    {
         if (request.Uri == "/works")
                return null;
         else return 401;
    });

Version is 2.0.3231.3.

By the way, the simplest way I've found to recover from this is to force scsqlparser.exe to quit, taking the rest of Starcounter down with it.

**Comment by k-rus** [comment]
> By the way, the simplest way I've found to recover from this is to force scsqlparser.exe to quit, taking the rest of Starcounter down with it.

I would prefer that you rather use `staradmin kill all`

**Comment by mtornwall** [comment]
> I would prefer that you rather use `staradmin kill all`

Thanks for the hint, I didn't know that command.

**Comment by alemoi** [comment]
I checked the problem and the behavior is expected with the example filter that you gave. The problem is that there are system and other handlers that are getting filtered as well, which prevents their normal work. We have to refactor our system code so all handlers are starting for example with specific prefix `/sys/...` But this is not done yet! However even now its possible to exclude most of such system handlers. Here is the excerpt from Launcher application that utilizes middleware filters:
```c#
// Checking if we should process this request.
if ("/" == uri ||
    Handle.IsSystemHandlerUri(uri) ||
    uri.StartsWith("/" + StarcounterEnvironment.AppName + "/", StringComparison.InvariantCultureIgnoreCase) ||
    uri.Equals("/" + StarcounterEnvironment.AppName, StringComparison.InvariantCultureIgnoreCase)) {

    return null;
}
```
Available here: https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/Api/LauncherHelper.cs#L31
You can see a few checks there.
Let me know if that helps!

**Comment by mtornwall** [comment]
That's good enough for my needs! Thanks.

**Comment by alemoi** [comment]
I have another idea I came up tonight, to skip all system handlers automatically. Will check if it works and get back to you. So far use the above solution.

**Comment by alemoi** [comment]
Ok, I was working on the idea that system handlers should be automatically skipped from middleware filters by default. This seems to work fine! I have removed the `Handle.IsSystemHandlerUri`. So please check the latest https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/Api/LauncherHelper.cs for changes.
This means that your original filter should work now:
```c#
            Handle.AddFilterToMiddleware(request => {
                if (request.Uri == "/works")
                    return null;

                else return 401;
            });
```

Any input would be appreciated!

**Comment by warpech** [comment]
> Thanks for the hint, I didn't know that command.

We will explain `staradmin kill all` on the .io website. Thanks for mentioning this.

**Comment by mtornwall** [comment]
Will I get this if I grab the latest daily build?

**Comment by alemoi** [comment]
Latest nightly I would say :)

**Comment by alemoi** [comment]
How is the situation now? Is it working properly? Please close the issue if it is.

**Comment by mtornwall** [comment]
Apologies - I had forgotten about this while working on other things. It seems that the download page is down at this time, but I'll take it for a spin tomorrow and see if I can reimplement my original filter without breaking things.

**Comment by dan31** [comment]
> It seems that the download page is down at this time
Working on that now

**Comment by mtornwall** [comment]
The administrator now works correctly alongside my middleware filter (which still filters user requests, as intended). Case closed. Thanks @alemoi!
