### ISSUE TITLE
flex/bison are needed for sql parser on linux build servers

### ISSUE THREAD

**Issue by alexanderstc** [Starcounter/Starcounter#2816]
https://scbuildserver/viewLog.html?buildId=29482&buildTypeId=Starcounter_LinuxNextDaily&tab=buildLog

flex is missing, I'd assume bison is missing too.

**Comment by parherman** [comment]
I installed flex and bison and the build passed, [build log](https://scbuildserver/viewLog.html?buildId=29487&tab=buildResultsDiv&buildTypeId=Starcounter_LinuxNextDaily)

Please verify and close this if it works!

**Comment by alexanderstc** [comment]
Fix confirmed, closed #2816.
