### ISSUE TITLE
Public web folders should be adopted to new schema

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2817]
Since I changed that each codehost now owns its static file handler (not like it was before that Administrator owned all static file handlers), now each codehost have their handler `/staticcontentdir` on its port. Because of that, right now Administrator in Network tab `Public web folders` shows only 8181 port folders but should go through each codehost default user port number and execute on it `GET /staticcontentdir` to collect statistics for all ports.

**Comment by warpech** [comment]
+1

**Comment by warpech** [comment]
ping

**Comment by andwah** [comment]
Resolved da3abe06064bdd3529cec5fa4464a9b04d26bfcd

![image](https://cloud.githubusercontent.com/assets/2656996/11897716/48c35660-a592-11e5-827c-3c937e46085f.png)
