### ISSUE TITLE
Allow Db.Transact delegates to return values

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2822]
I want to initiate a write transaction that returns a value that depends on the object written, such as its ID. Presently it seems that this cannot be done using `Db.Transact()`, so my workaround is this:

    Db.Scope<string>(() => {
        var foo = new Foo();
        // ...
        Transaction.Current.Commit(); // :-(
        return foo.GetObjectID();
    });

If `Db.Transact()` could propagate its delegate's return value I could avoid the ugly (and easily forgotten) call to `Transaction.Current.Commit()`.

/sub @chrhol @Starcounter-Jack

**Comment by dan31** [comment]
Hi @mtornwall! At a first glance I see no obstacle to implement. @chrhol, do you? The only thing is a value returned in case of transaction not succeeded after max no of retries. Should also propagate to ```Db.Scope``` API, which is also ```void``` today.

**Comment by mtornwall** [comment]
> The only thing is a value returned in case of transaction not succeeded after max no of retries.

Ah, right! Perhaps it could return type `T?` so as to enable it to return value types as well?

**Comment by dan31** [comment]
@mtornwall I think so, also in newer C# neat checks can be made then using monadish Elvis operator ```?.```.

**Comment by careri** [comment]
Transact will throw an exception if failing after x retries right? So you really wouldn't need the Nullable<T> since it will never return if failed?

Otherwise maybe the Try-pattern is a better fit?
```
bool Db.TryTransact(Action action) { }
bool Db.TryTransact<T>(Action<T> action, T arg1) { }
bool Db.TryTransact<T>(Func<T> func, out T value) { }
bool Db.TryTransact<T,T2>(Func<T2,T> func, T2 arg, out T value) { }
```
etc

**Comment by dan31** [comment]
Decided with @chrhol to include in a future release.

**Comment by chrhol** [comment]
This is now done and merged to develop and pnext branches. 

Due to the nature of how generic typing works I opted to not add that many overloads since some code has to be duplicated. We can always add more overloads if needed later.

The following overloads will be available:

```csharp
Db.Transact(Action action, ...);
Db.Transact<T>(Action<T> action, T arg, ...);
Db.Transact<TResult>(Func<TResult> func, ...);
Db.Transact<T, TResult>(Func<T, TResult> func, T arg, ...);
```

**Comment by dan31** [comment]
@chrhol, shall you upgrade the docs on .io accordingly (maybe you have already)?

**Comment by chrhol** [comment]
Added it now on http://starcounter.io/guides/transactions/
Also added missing entry in changelog.
