### ISSUE TITLE
"No connection to Prolog Server" when debugging in Visual Studio

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2824]
By some reason if I put Debugger.Launch() before the first Db.SQL call, then almost every time I get "no connection to Prolog Server" exception. However if I put the Debugger.Launch() after the first SQL call - then everything is fine. Maybe its somehow related to debugging session that disturbs the communication with Prolog?

**Comment by careri** [comment]
I'm having trouble with "no connection to progol server". And I launch through Visual Studio, so debugger is attached from start.

**Comment by dan31** [comment]
Hi @careri! For how long do you experience such issue?

**Comment by careri** [comment]
Occurs from time to time. Maybe it's the first debug-session on a newly
started DB. I.I'll check on Monday
Den 9 okt. 2015 7:46 em skrev "Dan Skatov" <notifications@github.com>:

**Comment by careri** [comment]
No it's not the first debug session. Seems totally random and not that frequent, not even every day

**Comment by alemoi** [comment]
I have looked at this issue and found the following: the Prolog monitor (PBMonitor.cs in Level0) was shutting down Prolog  sessions that were taking too long time, however they were not actually. Prolog session is time between sending the query to Prolog engine and receiving the response back. I found an issue when Prolog session is closed only when exception occurs which is wrong (basically the sessions were opened but never closed): that's why Prolog monitor was closing those sessions considering them taking too much time. I have pushed the fix to level0 develop now. Let me know how it works for you.

**Comment by k-rus** [comment]
I experience `no connection to Prolog Server` two times today during debugging Level1. I am working with branch pnext, where latest develop is merged.

**Comment by chrhol** [comment]
> I experience no connection to Prolog Server two times today during debugging Level1. I am working with branch pnext, where latest develop is merged.

I think this fix in Level0 develop is not yet merged to pnext Level0. I can do that when I'm finished with some changes in LaL for running it in pnext.

**Comment by chrhol** [comment]
> I think this fix in Level0 develop is not yet merged to pnext Level0. I can do that when I'm finished with some changes in LaL for running it in pnext.

Merged now.

**Comment by k-rus** [comment]
> I think this fix in Level0 develop is not yet merged to pnext Level0. I can do that when I'm finished with some changes in LaL for running it in pnext.
> Merged now.

Yes, of course, the changes were not merged yet. Thank you for merging them!

**Comment by alemoi** [comment]
Thank you for testing @k-rus 
Let me know if you see it again (or if you not see :)) !
