### ISSUE TITLE
Can not build Level1

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2826]
![image](https://cloud.githubusercontent.com/assets/2902045/9034222/480a8c32-39ce-11e5-8ceb-cbadabc35345.png)

Trying Develop and have been pulling down the latest bits early this morning, after being back from vaccation. Restoring packages seem not to help. Any one with an idea?

**Comment by alemoi** [comment]
Here is the related issue: https://github.com/Starcounter/Starcounter/issues/2148
For me restoring didn't help either. Try either of two:
1. Manually install FSharp.Compiler.Tools and FSharp.Core version 4.0.0.1
2. Or copy corresponding packages from buildserver FTP: ftp://scbuildserver/SCDev/ThirdParty/packages/

**Comment by per-samuelsson** [comment]
> Or copy corresponding packages from buildserver FTP: ftp://scbuildserver/SCDev/ThirdParty/packages/

This worked out perfect. Thanks @alemoi!
