### ISSUE TITLE
Access violoation

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2827]
I am running into this error without being able to figure out exactly why. 

Access violation (C0000005) detected at ..\..\src\sccoredb\sccoredb\sccoredb.cpp:2524 (Thread 17888). 000000592A687A36 sccoredb!determine_separately_stored_value_and_calc_record_sizes : pw_calcpropins.cpp (185) 000000592A688070 sccoredb!calc_fragmented_record_size_and_header_properties_update : pw_calcpropupd.cpp (155) 000000592A68A21C sccoredb!prep_write::Rbuild_and_append_prep_write_record_update_fragmented : pw_prepupdf.cpp (48) 000000592A68A133 sccoredb!prep_write::Rbuild_and_append_prep_write_record_update : pw_prepupd.cpp (82) 000000592A688C73 sccoredb!prep_write::Rbuild_prep_write_lists : pw_prepare2.cpp (198) 000000592A6890B9 sccoredb!prep_write::Rcheck_build_final_list_and_prep_write_dict_and_lists : pw_prepare2.cpp (149) 000000592A68D2D4 sccoredb!__commit : sccoredb.cpp (2104) 000000592A68CFF4 sccoredb!sccoredb_complete_commit : sccoredb.cpp (2493) 00007FFE6D10421E <unknown>! 0000005930361330 <unknown>! 0000001000639663 <unknown>! 0000000000000001 <unknown>!

I'm using Polyjuice-DevelopNightlyBuilds-2.0.3226 (Jun 18, 2015 8:09:16 AM)

**Comment by dan31** [comment]
Thanks for reporting @Ripipip, can you give more details? How much space left on disk, swap file configuration, memory consumed?

**Comment by Ripipip** [comment]
Hundreds of GB left, not much memory consumed at all, swap file is 60GB. I can't detect anything really. No spike in CPU usage, no increase in memory consumtion.

**Comment by dan31** [comment]
I asked @Ripipip to check with the latest version. @eriohl, maybe you can advise how to make use of PDBs (they are included in the distribution) in that case to deliver more failure info info to the issue report? This is a local machine case and is well reproducible, so we have more freedom to operate.

**Comment by eriohl** [comment]
If it is reproducible then please let me know how to and I'll look into it?

**Comment by dan31** [comment]
@Ripipip, maybe you can provide access to @eriohl to your machine via RDP?

**Comment by eriohl** [comment]
> @Ripipip, maybe you can provide access to @eriohl to your machine via RDP?

No. Send me what I need to reproduce it and instructions on how. Then I can run it through a debugger and figure out what is wrong. Bug in the kernel most likely.

**Comment by eriohl** [comment]
Resolved. Resolution included in next build.

**Comment by Ripipip** [comment]
Yes, it works now. Thank you!
