### ISSUE TITLE
Broken layout for SQL results with long text values

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2828]
I have a table with long string values, selecting such values from administrator panel causes broken layout in handsontable.

![image](https://cloud.githubusercontent.com/assets/6435556/9038639/87d183ea-39fe-11e5-8c7e-4782298a4bd5.png)

![image](https://cloud.githubusercontent.com/assets/6435556/9038661/ac29e340-39fe-11e5-820c-80adfca8c25f.png)

- The table should not overflow its container, instead the scroll should appear in the container.
- Scrolling should be synchronized between header and content.

cc @andwah, @warpech

**Comment by warpech** [comment]
Will forward this to @budnix

**Comment by miyconst** [comment]
Steps to reproduce: 

1. Check out Website project, playground branch: https://github.com/Polyjuice/Website/tree/playground.
2. Run the project.
3. Navigate to `http://localhost:8080/website`.
4. Go to admin panel `http://localhost:8181/#/databases/default/sql`.
5. Execute the following SQL:

```sql
SELECT *
FROM Website.Models.WebTemplate
```

**Comment by warpech** [comment]
WIP: https://github.com/Starcounter/Starcounter/tree/hotUpgrade018

Now reproducible with https://github.com/Polyjuice/Website/tree/master (but you have to comment out the line that uses PolyjuiceNamespace)

**Comment by warpech** [comment]
Problem with max column width fixed by https://github.com/Starcounter/Starcounter/commit/38b7402b041fa5ca05dbd18f84b4b84c04b046c3. Problem with headers rendering tracked in https://github.com/Starcounter/Starcounter/issues/2987.
