### ISSUE TITLE
Add information in Administrator about supported SQL statements

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2834]
Novice users are surprised about the fact that only SELECT statements are supported and spend  minutes of investigation until they give up on using other queries. We should write it clearly in the Administrator what queries are supported, with a link to a page that describes it in more detail.

**Comment by mtornwall** [comment]
+1, this bit me in the beginning.

**Comment by warpech** [comment]
@andwah could you check what statements are supported currently (SELECT, CREATE INDEX, DELETE) and add this information? Every person that begins development with Starcounter is confused about that

**Comment by jakubklekota** [comment]
+1
SQL statements compatibility with t-sql http://www.w3schools.com/sql/

**Comment by andwah** [comment]
Here is some related information #2859

> The Administrator uses ```Db.SlowSQL(query)```, so everything that  ```Db.SlowSQL(query)``` supports can be used in the Administrator Query window.

I will add some informative text in the Query window

**Comment by k-rus** [comment]
> SQL statements compatibility with t-sql http://www.w3schools.com/sql/

Starcounter's SQL is described on [our website](http://starcounter.io/guides/sql/). Current version of our SQL is a limited subset of standard SQL with some extensions. The implemented syntax might have small differences to standard SQLs, e.g., 92, 99, and different SQL implementations, e.g., T-SQL, PL/SQL, since all of them are different.

**Comment by andwah** [comment]
What text should we write in the Administrator to make it clear what the user can do. ?

**Comment by warpech** [comment]
I propose the following:

> SQL browser currently supports SELECT, CREATE INDEX and DELETE statements. Other operations (equivalent to INSERT, UPDATE) are done in code. [Read more about Starcounter's SQL](http://starcounter.io/guides/sql/)

@k-rus want to refine it?

**Comment by k-rus** [comment]
> I propose the following:
> 
> SQL browser currently supports SELECT, CREATE INDEX and DELETE statements. Other operations (equivalent to INSERT, UPDATE) are done in code. Read more about Starcounter's SQL
> @k-rus want to refine it?

I don't know what is allowed in Administrator's SQL. If transaction scope was fixed and `SlowSQL` is used, then I guess all implemented SQL should work. However, it should be tested first, or better to add regression tests.

Neither INSERT, nor UPDATE are supported in current SQL implementation. INSERT is only supported for loading data from generated statements. INSERT is not supposed to be used by users.

**Comment by andwah** [comment]
I added some extra information that will be displayed when SCERRSQLINCORRECTSYNTAX, SCERRSQLNOTIMPLEMENTED and SCERRSQLNOTSUPPORTED, error code is returned from an query. Will that cover what we need?

![image](https://cloud.githubusercontent.com/assets/2656996/10361851/27c83e36-6dab-11e5-82b4-a0590ab856a9.png)

**Comment by warpech** [comment]
LGTM!

**Comment by andwah** [comment]
pushed b6aef07a964a990f4a26cbc496498f501f5f8e50

**Comment by warpech** [comment]
Thanks, closing!
