### ISSUE TITLE
Set MatchingHost in the reverse proxy

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2835]
Currently, reverse proxy only supports `MatchingMethodAndUri` as explained here: https://github.com/Starcounter/Starcounter/wiki/Gateway-Reverse-Proxy

I would like to have multiple databases on the same server, each database for a different customer. Databases should be exposed as a subdomain, eg. `<customername>.mysampleapp.com` and accessed on port 80.

To be able to achieve that with Starcounter's reverse proxy, it needs to allow specifying the `MatchingHost`. This config directive should look at the value of the `Host` header in the HTTP request.

Please evaluate if this is a feasible option. If not, then we need to work on a how-to about using nginx for this purpose.

/cc @dan31, @miyconst

**Comment by alemoi** [comment]
The initial solution is implemented and considered OK for the moment. I have updated the network gateway documentation: http://starcounter.io/guides/network/networkgateway/
The remaining part is to add nightly tests for this.

**Comment by warpech** [comment]
Can this be closed now?

**Comment by alemoi** [comment]
Nightly tests are still not added but otherwise can be closed.
