### ISSUE TITLE
Populate meta-data about meta-tables

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2836]
During meta-layer preparation, which is part of database initialisation, meta-tables are created and need to be populated with meta-data about themselves. The source of information for meta-tables is the json file with the description and ids/handles from the kernel.

For each created table a record is inserted into meta-table `RawView`, which has the following schema (see also the JSON file):
```
RawView : Table (
    ulong LayoutId
)
Table : Type (
    Table Inherits, 
    ulong Updatable, 
    string FullName, 
    string UniqueIdentifier, 
    string UniqueIdentifierReversed
)
Type (
    string Name
)
```
Since `RawView` inherits `Table`and `Table` inherits `Type`, it contains 7 columns, which are populated in the following way:

- Column `Name` is a short name of the table as presented in the JSON file. For example, `Name` for table *RawView* is *RawView*.
- Column `FullName` is the short name with the namespace. If the JSON file specifies `"PublicNamespace" : true`, which should be by default, then the namespace is `Starcounter.Metadata.`, if `false`, then `Starcounter.Internal.Metadata.`. The fullname is used to create token and table. For example, table *RawView* is in internal namespace, thus `FullName = "Starcounter.Internal.Metadata.RawView"`.
- Column `UniqueIdentifier` adds prefix *Starcounter.Raw.* to `FullName`. For example, `UniqueIdentifier` for table *RawView* will be *Starcounter.Raw.Starcounter.Internal.Metadata.RawView*. The unique identifier resolves ambiguity between code host names for tables and direct logical table names, which both can be used in SQL queries.
- Column `UniqueIdentifierReversed` contains the same value as `UniqueIdentifier`, but the identifiers are stored in reversed order to allow efficient index search on most specific identifiers. For example, `UniqueIdentifierReversed` for table *RawView* will be *RawView.Metadata.Internal.Starcounter.Raw.Starcounter*.
- Column `Updatable` is always set to `false` for meta-tables, since they cannot be updated by users.
- Column `Inherits` stores reference to the record describing the parent table. For example, table *RawView* extends table *Table*, then `Inherits` will contain reference to the record for *Table*.
- Column `LayoutId` is set to the layout handle/id provided by the kernel. It is obtained by calling `stari_transaction_get_layout_info_by_token`. Note that the function can be called after the transaction, where the table was created, is committed. This is current limitation in the kernel, which will be eventually relaxed.

Records in `SetSpecifier` has to be updated to set references into these records inserted into `RawView`. (see #2831)

Insertions of meta-data about columns and indexes will be in the following comments in this issue.

**Comment by k-rus** [comment]
For each column of a table a record is inserted into `RawColumn`, which has the following schema (see also the JSON file):
```
RawColumn : Column (
    ulong ColumnIndex
)
Column : Member (
    ulong Nullable,
    long AlwaysUnique
)
Member (
    Table Table,
    string Name,
    Type DataType,
    ulong Inherited
)
```
Since `RawColumn` extends `Column` and `Member`, it contains 7 columns.

It is important that inserted columns for a table describes directly specified columns, but also all inherited columns. For example, number of columns inserted for table *RawView* will be 7.

The column values for 'RawColumn` are set in the following way:

- Column `Table` contains reference into `RawView` record describing the table, to which the column belongs. For example, column `UniqueIdentifier` of table *RawView* will refer to the record of `RawView`, which describes table *RawView*.
- Column `Name`is set to the column name obtained from the JSON file.
- Column `DataType` describes the result type of the column. It either refers to a record of *RawView* or a record of `DbPrimitiveType`. Population of `DbPrimitiveType` is described in function `populate_materialized_type` in file *populate_metatable.cpp*. For example, `DataType` of column *UniqueIdentifier* will refer to the record of `DbPrimitiveType` describing type named `string`. `DataType` of column *Inherits* of table *Table*  will refer to record of `RawView`, which describes table *Table*.
- Column `Inherited` is set to `false` if the column directly belongs to the table and is set to `true` if the column is inherited from the extended table. For example, `Inherited` of a record describing column *UniqueIdentifier* and referred to a record describing table *Table* is set to `false`, and `Inherited` of a record describing column *UniqueIdentifier, but referred to a record describing table *RawView* is set to `true`.
- Column `Nullable` is set according to function `set_nullable_type` and correspond to information provided to the kernel during table creation (see functions `create_metatable` and `define_column`).
- Column `AlwayUnique` is always set to `false`, since the only always unique column is `__id`.
- Column `ColumnIndex` is set to the value calculated in function `TABLE_INFO::verify`. Basically, this number is obtained by knowing the order of columns provided during table creation, that index 0 and 1 are already allocated for the kernel columns (__id and __setspecifier) and inherited columns precede the direct columns. The index can be verified by calling `stari_transaction_get_column_info`.

**Comment by k-rus** [comment]
Important note, which I forgot to mention:
Functions `verify`calculates some values, which are then used during meta-data population. First version of meta-data population can be found in file *populate_metatable.cpp*, which is excluded form the project. The code from file can be used to clarify the population or even be reused.

**Comment by k-rus** [comment]
For each created index a record is inserted into meta-table `Index` with the following schema:
```
Index(
    string Name,
    Table Table,
    ulong Unique,
    ulong IndexHandle
)
```
Table `Index` contains 4 columns, which are set according:

- Column `Name` contains the name of the index, which is obtained from the JSON file and used during index creation. Note that index name is database unique.
- Column `Table` is a reference to a record of `RawView`, which describes the table to which the index belongs. This relationship between the index and the table is defined by the set specifier value used during index creation and is found in the JSON file.
- Column `Unique` describes if the created index is unique or not. The value is obtained from the JSON file and used during the index creation.
- Column `IndexHandle` contains the index handle value, which is obtained after index creation by calling `stari_transaction_get_index_info_by_token`. Note that the function should be called after the transaction with index creation was committed.

For each column of the index a record is inserted into meta-table `IndexedColumn`, which has the following schema:
```
IndexedColumn(
    Index Index,
    Column Column,
    ulong Position,
    ulong Ascending
```
It contains 4 columns, which are set in the following way:

- Column `Index` contains reference to a record of meta-table `Index`, which describes the index to which the column belong.
- Column `Column` contains reference to a record of meta-table `RawColumn`.
- Column `Position` is set to the position of the column in the index, which corresponds to the order in which the columns are specified during the index creation. For example, index *MemberPK* of table *Member* is constructed with two columns: *Table* having position `0` and *Name* having position 1.
- Column `Ascending` specifies if the index on the column is in ascending order, which is by default. Thus all indexes on the meta-tables are ordered in ascending order.

**Comment by k-rus** [comment]
During implementation it is important to remember that the meta-schema and population specification is not final and will be updated number of times in future.

**Comment by alexanderstc** [comment]
A working prototype on the branch CleanMetalayer-alexander. Still need to implement Insert base table's fields in the metalayer generator; make setspec creation code use letters other than a-z.

**Comment by alexanderstc** [comment]
Implemented, closed.
