### ISSUE TITLE
Nightly build failed because of LibrariesWithDatabaseClasses and QueryProcessingTest metadata

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2838]
After we started to have LibrariesWithDatabaseClasses needed for database mapping and other purposes (it includes DLLs with database classes that are loaded on each codehost startup), it interferes with the metadata for query processing test. For example, via a78733c4ed08bfcf5cddd2a7f2663fde9105449e I changed the properties of one database class, and now the test fails: https://scbuildserver/viewLog.html?buildId=29804&buildTypeId=Starcounter_Develop_Nightly_Debug&tab=buildLog
@k-rus is it possible to make it flexible for metadata test to get around this?
And in this particular case (a78733c4ed08bfcf5cddd2a7f2663fde9105449e) I guess I should change some metadata values checks, but need some advice from you @k-rus 
Thank you!

**Comment by k-rus** [comment]
I don't understand how the changes are related to metadata. I need more information to understand the changes. For example, I don't know what LibrariesWithDatabaseClasses means. Can you debug the test to see the difference between expected and actual values?

**Comment by k-rus** [comment]
If your changes generate additional tables or columns for each created table, then the correct assertions should be corrected to include them. Another approach is to avoid such generation for the test database and test application as before there was differentiation between pure empty Starcounter and Polyjuice.

**Comment by alemoi** [comment]
Its a set of DLLs that are include database class ([Database]) and loaded upon the code host start. Those libraries are needed, for example, for database mapping and other purposes in future. I guess metadata test assumes there is a certain predefined number of database classes, so if I added one more classes to LibrariesWithDatabaseClasses DLLs, then metadata test will fail again and will require correction. For example, here is how @chrhol corrected the previous case with LibrariesWithDatabaseClasses: bbab532ae564946459f3bcdf85c067ab6f17e19e
I will fix the current case, but question is more about future, how to avoid this situation again.
I actually think now to rename this folder LibrariesWithDatabaseClasses for the time of the query processing test, and then rename back. Just that you are aware of this.

**Comment by k-rus** [comment]
Thank you for the clarification! Now it is much more clear what is happening. Yes, the test assumes that only database classes and thus tables, which are defined in the application, exist. It does not follow the concept that someone can load more classes into the application without modifying the application. The Polyjuice flag was important for tests on SQL such as the query processing test.
IMHO, the best option is somehow to disable adding database classes from outside the application for the test purpose.

**Comment by alemoi** [comment]
Great! Then I will do temporary folder renaming for the time of Query Processing Test!

**Comment by dan31** [comment]
Guys, off-top comment here. Out of those 6 messages, only 2 of them I received as email notifications. Anyone else experience the same?

**Comment by alemoi** [comment]
I guess it accumulates if replies are within a minute or so.

**Comment by per-samuelsson** [comment]
> Anyone else experience the same?

I have had a few cases the last couple of days where I would have expected a mail, but didn't get one. For example, I didn't get one when @linkdata  mentioned me in that CompanyTrack thread about the Kernel API in pnext. :cry:

**Comment by alemoi** [comment]
The original problem fixed via b38e387bf7c326f6d6ad689fb526de6a16538fd9
I also reverted the fixes made by @chrhol since now for query processing test we skip the folder completely.
