### ISSUE TITLE
What is Starcounter_Internal_Unload_Utility?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2841]
I went to Applications page of administrator panel and saw this:

![image](https://cloud.githubusercontent.com/assets/6435556/9135173/5cde0146-3d13-11e5-8fe2-ff328c402dab.png)

What the `Starcounter_Internal_Unload_Utility` app is and where it came from?

**Comment by mtornwall** [comment]
I noticed this gets launched when you use `staradmin` to unload (I'd really prefer the word *dump*) the database to an SQL file.

**Comment by per-samuelsson** [comment]
> What the Starcounter_Internal_Unload_Utility app is and where it came from?

Just like @mtornwall says, it relates to the unload. When you issue either `staradmin unload` or `staradmin reload`, they get executed by means of an internal application. Which, unfortunatelly, stays resident in the code host.

Eventually, we'll make these apps more transparent, and have the act like single-purpose tools. The design to have them modelled like apps are fine, but the fact they are not unloaded should be considered a flaw.
 
There some info here if you are interested: https://github.com/Starcounter/Starcounter/issues/2506#issuecomment-71008370

**Comment by miyconst** [comment]
I would be nice to close the up after the job done, or name it nice, not like some tech name which would confuse the new users.

Closing the issue.

**Comment by per-samuelsson** [comment]
> I would be nice to close the up after the job done ...

Agree. Like I wrote: its a bug that its not like that.

> [...] or name it nice, not like some tech name which would confuse the new users.

The name was designed like it was to minimize the chance that it would clash with some user application. The whole idea was that the name would never be visible to the user. If it would terminate right after it completed, you would have never seen it.
