### ISSUE TITLE
Exposing gateway reverse proxy configuration in Administrator

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2843]
I added initial support for host-header-based reverse proxy in gateway. Its reflected in scnetworkgateway.xml (there is an example of usage there). Also reverse proxies information is contained in gateway statistics: 127.0.0.1:8181/gwstats

Ideally gateway proxies should be editable from Administrator, where the Apply button will call GET 127.0.0.1:8181/UpdateConfiguration (will rename it to /GwUpdateConf) which actually makes gateway re-read the scnetworkgateway.xml to get latest proxies info from there.

I also wrote an article on reverse proxies here: http://starcounter.io/guides/network/networkgateway/

**Comment by warpech** [comment]
What's the current name for this handler? `/gw/updateconfiguration`?

**Comment by alemoi** [comment]
Yes, I changed it to this.

**Comment by alemoi** [comment]
This change however will be available in the following nightly.

**Comment by warpech** [comment]
I confirm it works

@alemoi can you update the docs at http://starcounter.io/guides/network/networkgateway/ to explain `/gw/updateconf` and close the issue?

**Comment by alemoi** [comment]
Thanks for reminding. Updated the Wiki. Let me know if anything else, otherwise you can close the issue.
