### ISSUE TITLE
Minsk, service wrapper questions.

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2844]
Hi!

I'm writing a service wrapper for minsk.exe, and it's working nice with a couple of exceptions:
1. How do I stop minsk.exe nicely, when running interactive there is a button to push. What does this button do? Can the shutdown be invoked through sockets? I'm using Process.Kill at the moment, is this safe?
2. Does minsk only work with swedish culture? I run into this problem on an english OS:

    D:\Deploy\source\master-Debug-AnyCPU\HIA\Server\StorageStats\StorageStats_8\12\2015 12_41_06 PM.log

The file name contains DateTime.Now using english format, which contains backslash. 
If I run interactive with my user that has Swedish-culture defined the file has this format:

    D:\Deploy\source\master-Debug-AnyCPU\HIA\Server\StorageStats\StorageStats_2015-08-12 13_45_16.log

To get by this problem I can run the service with my account instead of Local service.

**Comment by per-samuelsson** [comment]
> I'm using Process.Kill at the moment, is this safe?

For durability of the database, I'm quite sure it is, yes. This is like 10 year old code we are talking about, but AFAIK, we've never had any released versions that haven't been safe in terms of durability.

For the rest, I can't really answer. Maybe @eriohl can share some, or else, maybe I can spend some time looking at the old code (but I have to get someone to get that old server up and running if so). 

And if I don't remember wrong, some (outer-ish) parts of the Minsk server were written by @niklasbjorkman, no? Might be more of scheduling/threading though, so maybe that last question is more likely we should answer.

**Comment by eriohl** [comment]
I'm not entirely sure about this but I'm pretty sure that Heads did the GUI (with the button) and most probably this file print you are referring to as well (I at least can recall seeing this file before).

You are running minsk.exe then?

**Comment by careri** [comment]
Strange didn't get a mail that you replied. Sorry for not responding.

I've decompiled your libraries. And the code being executed resides 

    Minsk.Application.Runtime.Exit()

That just seems to set an event that exits the the Idle()-loop and shutsdown.

In the Start()-method of my service I spawn minsk.exe with the correct arguments, but there will be no GUI since it's running as a service.

But I have a new idea, I just write a plugin that opens a channel that the MinskService can send a message on. Just trying to figure out how to register a channel..

**Comment by careri** [comment]
MinskDb.StorageStats is the class being written using DateTime.Now I guess.

Haven't found out where yet though, browsing the code

**Comment by careri** [comment]
MinskServer.LogEntry:

    LogName = logdir + logName + "_" + DateTime.Now.ToString().Replace(":","_");

Don't know who wrote that, but looks bad :)

**Comment by per-samuelsson** [comment]
> Don't know who wrote that, but looks bad :)

If its bad, it was me! :wine_glass: 

> Strange didn't get a mail that you replied.

Me and @dan31 has also experienced severl such cases recently. It's probably a GitHub issue. I think @dan31 is following up on it with their support.

**Comment by dan31** [comment]
> Me and @dan31 has also experienced severl such cases recently. It's probably a GitHub issue. I think @dan31 is following up on it with their support.

Or this is GH + MS (which own our mail services). Still investigating.

**Comment by careri** [comment]
We'll in this case of looking bad I'm 100% sure I'm not the culprit. Nice for once :)

Ok, I'll try to keep in mind for now to manually check for updates here... that will probably work out...

**Comment by eriohl** [comment]
Ok.

minsk.exe unloads the database properly on exiting call to Minsk.Activation.EntryPoint (calling SCCleanup). So it you want the database to be properly unloaded then ```Minsk.Application.Runtime.Exit()```. The AppDomain needs be unloaded before call to SCCleanup because this is the only way to ensure no other threads are accessing the kernel when this is done (this would be bad). If you just kill the process you should not loose any data as @per-samuelsson says but it will have to run recovery at startup.

(You own the source for minsk.exe and MinskDb, MinskServer and all the Minsk.* managed libraries as well. As for MinskServer I don't know that we have access to the source code for that any longer even.)

**Comment by careri** [comment]
Thanks. I've managed to setup a Starcounter.Channel. But any data I send just ends up in:

    IIoHandler.ChannelOpened(Channel channel);

Browsing the code suggests that I should end any data with the '\0' null char. But I just can't seem to reach:

    IIoHandler.MessageReceived(Channel channel, ByteBuffer message);


My message just gets thrown away somewhere along the path. 
I'm intending to call

    Minsk.Application.Runtime.Exit()

When I get a certain message on my channel.

Any ideas?

**Comment by eriohl** [comment]
You need to call Channel.Read for it to read a message (in ChannelOpened and after each MessageReceived). Note that Channel.Read is not synchronous, MessageReceived is always called to process message (after call to Read). Have you done this?

**Comment by careri** [comment]
No, I figured it out about the same time as you responded. Thanks

**Comment by careri** [comment]
I'll close this issue. Got the server shutting down properly when invoked on the channel.
