### ISSUE TITLE
Moving and renaming database types

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2845]
My data model is changing frequently and I often need to rename types or move them between namespaces. I expect I shall have to do this even after my product is in production. Are there any facilities in Starcounter for renaming the tables so that I don't lose data?

**Comment by dan31** [comment]
Hi @mtornwall, thanks for a good question.
A reasonable way to do schema migration is to manually adjust schema stored in a database to a suggested schema change of the code. To do this, changing metadata table records is a way to go. The metadata tables description is on pic below:
![metadatatables 1](https://cloud.githubusercontent.com/assets/7162535/9258038/6e246734-41f9-11e5-8ab7-f4b690ac7dfe.png)
It is drawn assuming to be self-explanatory. Hope it is :)
@k-rus, please correct me if there should be some other path. This seems to be okay when you only adjust schema but not data. Is it possible in 2.0 to add new fields or remove fields by manipulating metadata only, maybe it is also about weaver calling lower-level APIs (which isn't a case for administrator).

**Comment by k-rus** [comment]
> A reasonable way to do schema migration is to manually adjust schema stored in a database to a suggested schema change of the code. To do this, changing metadata table records is a way to go.

Meta-data should never be touched. They must reflect the logical state of the schema in the kernel, i.e., the actual tables.
The meta-data are available to users only for read.

Somewhere I described how to change schema with the current implementation that it works, but I cannot find the issue.

Adding a new column or table is simple and is just by adding new field/property and new class in the class definition in the application. Removing a column or a table is also working, I think. Just remove from the class definitions and double check that no information about it left in the meta-data.
Renaming is not supported. Renaming should be done manually in several steps:

1. Add new column with the new name in the class definition.
2. Run application and copy values from the old name column to new name column.
3. Remove the old column by modifying class definition.

Same with renaming classes and namespaces:

1. Add new class.
2. Manually move data from the old class to new class.
3. Remove old class. (make sure that no traces of the old class is in the meta-data)

If you try to rename a column or a table by class definition as one step: you will create new column or table without data and remove the old column or table with the result of losing data.

This is how it works now. We will investigate a better solution for refactoring in new version.

**Comment by mtornwall** [comment]
Based on @k-rus explanation it sounds a bit laborious but rather straightforward. I may invest some time into automating most of this process as I know myself well enough to know I would mess this up sooner or later. :-)

Thanks for your answers.

**Comment by dan31** [comment]
@mtornwall, what would be your strategy to pilot new versions? The question is connected to your question. Let's say, you run v1 in production and have made a new version v2 with some names changed, some fields added. Now you want to migrate data and run v2. Is it enough for you to stop v1, run v1->v2 migrator (which is "automating most of the process") and then run v2. If not, we need to think how to better do it. What's your opinion? I have some schemes in mind, but I bet you'd propose a better one :)

**Comment by dan31** [comment]
@k-rus, looks like I was dreaming about better implementation in mind. I believe renaming should be improved in future versions (NB to me and you – address that in specs as a special point), since what you do there is changing only the metadata linkage to data layout, but not data layout itself.

Yes I know that in other DB's migrating table layouts is a tough op. At least, when I dealt with MySQL, doing layouts changes was implemented there through full table copies, which could take days to perform. 

Today it is heavy with SC as well, I believe we have numerous ways to address it. I thought if I could hack onto metadata that would be a case. Perhaps it's no-goer with 2.0.

**Comment by k-rus** [comment]
> believe renaming should be improved in future versions (NB to me and you – address that in specs as a special point), since what you do there is changing only the metadata linkage to data layout, but not data layout itself.

Good point that renaming will just change meta-data. 

It is important to note that we need to provide API to specify renaming explicitly. Renaming cannot be decided implicitly by looking in changes in class definitions.

A side node about dropping a table: in addition to class definition table can be dropped by SQL query with `DROP TABLE` statement.
