### ISSUE TITLE
Implement schema change API

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2849]
Implement the following API functions, which update database schema:

- [ ] Create table
- [ ] Create index
- [ ] Drop index

---

#### Create table

Draft of public API:
```c++
// This structure is used to communicate column info from different clients, SQL, .NET host, other hosts
struct STAR_COLUMN_DEFINITION
{
	uint64_t type_oid; uint64_t type_ref; // Record id pair
	uint8_t is_nullable;
	const ucs2_char *name;
};
// This interface function does not do type checking.
// It assumes that the type checking was done by client.
// It should assure the assumptions in debug mode, i.e., do type checking but only in debug build
SYSTABLES_EXPORT uint32_t star_create_table(uint64_t context_handle,
  const ucs2_char *full_name, 
  uint64_t base_table_oid, uint64_t base_table_ref,
  const struct STAR_COLUMN_DEFINITION *column_definitions
  );
```
The input is then used to call the kernel and populate meta-data in the following way.
The input to the kernel function `stari_transaction_create_layout` and structure `STARI_COLUMN_DEFINITION`:
- `handle` is handle of transaction created in the context given through `context_handle`.
- `token` is obtained from `name` and table `Token` by assuring a token for the name
- `base_layout_handle` is `LayoutId` of base table record, which is `RawView`.
- `column_definitions` are set from `column_definitions` according:
  - `STARI_COLUMN_DEFINITION:type` - the value is obtained from type record either directly from column `PrimitiveType` if it belongs to `DbPrimitiveType`or is `STAR_TYPE_REFERENCE` if it belongs to `RawView`.
  - `STARI_COLUMN_DEFINITION:is_nullable` is directly set (strings and references are always nullable)
  - `STARI_COLUMN_DEFINITION:is_token` is obtained from `STAR_COLUMN_DEFINITION:name` and `Token` table by assuring a token for the name.

Meta-table `RawView` is populated:
- `Name` is the actual name of table without namespaces, i.e., the last identifier in `full_name`, which is placed after the last dot. It can be the same as the full name if the table is outside namespaces.
- `Inherits` is set to base table record
- `Updatable` is set to `true`
- `FullName` is the `full_name`
- `UniqueIdentifier` is `Starcounter.Raw.` + the value of `FullName`.
- `UniqueIdentifierReversed` is `UniqueIdentifier` with reverse order of identifiers (separated by dots)
- `LayoutId` is obtained from kernel after the table creation

Meta-table `RawColumn` is populated for directly defined columns and for inherited columns for all base tables down to the root in the hierarchy:
- `Table` is set table this table record in `RawView`.
- `Name` is set to `STAR_COLUMN_DEFINITION:name`.
- `DataType`is set directly to the type record.
- `Inherited` is set to `false`for directly defined columns and to `true` for columns inherited from base tables.
- `Nullable` is set directly.
- `AlwaysUnique` is set to `false`. (it is `true` only for `__id`, which is not part of meta-data so far).
- `ColumnIndex` is obtained from kernel after the table creation.

Draft of another public API function to create table, which is important for testing:
```c++
// This interface simplifies testing and prototyping, but will not be used in production, 
// since clients will cache meta-data locally.
struct STAR_COLUMN_DEFINITION_HIGH
{
	uint8_t primitive_type;
	const ucs2_char *type_full_name; // Always null if primitive type is not reference
	uint8_t is_nullable;
	const ucs2_char *name;
};
SYSTABLES_EXPORT uint32_t star_create_table_high(uint64_t context_handle,
  const ucs2_char *full_name, 
  const ucs2_char *base_table_full_name,
  const struct STAR_COLUMN_DEFINITION *column_definitions
  );
```
Implementation of this function should find base table record in `RawView` based on `base_table_name` and for each column find data type record. The data type record is either instance of `RawView`, if `primitive_type=STAR_TYPE_REFERENCE` and `type_name` is set, or instance of `DbPrimitiveType` otherwise. If a record for `base_table_full_name` is not found, then `SCERRBASETYPENOTFOUND`, if a record for `type_full_name` is not found, then `SCERRDATATYPENOTFOUND`.

---

#### Create index

Draft of public API:
```c++
SYSTABLES_EXPORT uint32_t star_create_index(uint64_t context_handle,
  uint64_t table_oid, uint64_ table_ref, 
  const ucs2_char *name, 
  uint16_t sort_mask,
  const int16_t *column_indexes, 
  uint32_t attribute_flags
  );
```
The input is then used to call kernel and populate meta-data. The kernel API:
```c++
SCCOREDB
extern uint32_t stari_transaction_create_index(
  uint64_t handle,                      // IN
  uint64_t token,                       // IN
  const ucs2_char *setspec,             // IN
  uint16_t layout_handle,               // IN
  const int16_t *column_indexes,        // IN
  uint16_t sort_mask,                   // IN
  uint32_t attribute_flags              // IN
  );
```
The arguments are prepared as following:
- `handle` is the handle of a transaction created in the give context, `context_handle`.
- `token` is the token assured for the given `name`. Note that name and token is unique among all indexes.
- `setspec` is the set specifier of the type (table), which is provided by the record pair.
- `layout_handle` is the layout id of the type.
- `column_indexes` is used directly.
- `sort_mask` is used directly.
- `attribute_flags` is used directly.

Meta-table `Index` is populated in the following way:
- `Name` is `name`, i.e., the name of the index.
- `Table` is the type / table.
- `Unique` is obtained from attribute flag by masking with `STAR_UNIQUE_CONSTRAINT`.
- `IndexHandle` is retrieved from the kernel after creating index and committing the transaction.

Meta-table `IndexedColumn` is populated for each index of the column in the following way. The number of columns is found from `column_indexes`, which is an array of column indexes terminated with invalid index `-1`:

- `Index` is the reference to the created meta-record index in table `Index`.
- `Column` is the reference to a record of table `Column`, which is found by accessing index `RawColumnPK` using the table reference and column index obtained from `column_indexes`.
- `Position` is the position of the indexed column in the array `column_indexes`.
- `Ascending` is the value of the corresponding bit in `sort_mask`.

For additional information see documentation of `stari_transaction_create_index` and disabled `createindex.cpp`. 

Draft of public API for testing:
```c++
struct STAR_INDEXED_COLUMN {
  const ucs2_char *column_name,
  uint8_t ascending
};
SYSTABLES_EXPORT uint32_t star_create_index_high(uint64_t context_handle,
  const ucs2_char *index_name, 
  const ucs2_char *table_full_name,
  STAR_INDEXED_COLUMN *columns,
  uint32_t unique_flag
  );
```
If a type for `table_full_name` is not found, returns `SCERRTYPENOTFOUND`. If a column for `column_name` of the table (including inherited) is not found, returns `SCERRBASETYPECOLUMNNOTFOUND`.

---

####  Drop index

Draft public API:
```c++
SYSTABLES_EXPORT uint32_t star_drop_index(uint64_t context_handle,
  uint64_t index_oid, uint64_t index_ref
  );
SYSTABLES_EXPORT uint32_t star_drop_index_by_name(uint64_t context_handle,
  const ucs2_char *index_name
  );
SYSTABLES_EXPORT uint32_t star_drop_index_by_table_and_name(uint64_t context_handle,
  const ucs2_char *table_full_name, const ucs2_char *index_name
  );
```
The second and the third functions return `SCERRINDEXNOTFOUND` if there is no index for the given name. The third function returns `SCERRTYPENOTFOUND` if there is no type for the given name, and `SCERRINDEXNOTFOUNDINTYPE` if the given index does not exist in the given type.

The input to the functions is used to call kernel and to update meta-data. The kernel function to call is:
```c++
SCCOREDB
extern uint32_t stari_transaction_drop_index(uint64_t handle, uint64_t token);
```
The arguments are prepared:

- `handle` is the handle of a transaction created in the given context.
- `token` is the token of the index name obtained from Token table for the name obtained from Index table (or validated in Index table).

The record of `Index` describing this index and all records of `IndexedColumn`, which refers to the index record, are removed from the database.

**Comment by k-rus** [comment]
Definition of `stari_transaction_create_layout` contains argument `attribute_flags`. The comment does not say more than the actual name. @eriohl Can you remind what this argument for and what are possible values of flags?

**Comment by k-rus** [comment]
Implementation of create index requires index on `RawColumn`, which requires that JSON to CPP conversions support inherited columns in index definitions. The index is defined in the json file in branch `FailedJsonGenerator` and building it fails.

**Comment by k-rus** [comment]
The first draft version of API and the specification of the implementation are completed. The API and details might need to be improved if so found during implementation or due to clients of the API need.

**Comment by per-samuelsson** [comment]
> Name is the actual name of table without namespaces, i.e., the last identifier in name, which is placed after the **last dot**. It can be the same as the full name if the table is outside namespaces.

Just a very minor detail: its probably wise to either isolate to a central spot the built-in assumption of a dot as a separator, or have it defined as an (internal) parameter/setting. IMO, this is one thing that can differ between qualified names in different contexts.

**Comment by k-rus** [comment]
> Just a very minor detail: its probably wise to either isolate to a central spot the built-in assumption of a dot as a separator, or have it defined as an (internal) parameter/setting. IMO, this is one thing that can differ between qualified names in different contexts.

It is necessary to use one build-in uniform separator to allow efficient search on identifiers in meta-data. The natural choice is dot, which is the separator in client APIs: C#, Javascript, C. Our SQL uses dot too.

**Comment by alexanderstc** [comment]
Implemented, closed.

**Comment by per-samuelsson** [comment]
@alexanderstc 

Looks like there is a typo in the second sample of the OP: I guess `STAR_COLUMN_DEFINITION` should be `STAR_COLUMN_DEFINITION_HIGH` in that one, no?

Also: any doc on return value of `star_create_table/high` pair? Is that a handle/ID to the table? If so, how are errors propagated? I would have expected an out parameter for the handle/ID? 

Or is the pattern more like:

```c
e = star_create_table_high("foo", "bar", ...);
if (e == SUCCESS) {
  tableHandle = star_get_table_handle("foo");
}
```

And if so, any doc on `star_get_table_handle` equivalent?

**Comment by alexanderstc** [comment]
Sorry, wasn't watching. A typo, obviously. Fixed.

**Comment by k-rus** [comment]
> Also: any doc on return value of star_create_table/high pair? Is that a handle/ID to the table? If so, how are errors propagated? I would have expected an out parameter for the handle/ID?

The return value is error code as usual for public API. There will be public API to retrieve error specific information in future if needed.



> Or is the pattern more like:
> 
> e = star_create_table_high("foo", "bar", ...);
> if (e == SUCCESS) {
>   tableHandle = star_get_table_handle("foo");
> }
> And if so, any doc on star_get_table_handle equivalent?

There is no function to get table/layout handle. Instead the meta-table `RawView` is searched to find description of table with the given name.

**Comment by per-samuelsson** [comment]
>  Instead the meta-table RawView is searched to find description of table with the given name.

OK, thats fine I guess. With that being said, would it be very bad to just return some kind of handle as an out parameter? Maybe a reference to the RawView? You would have that at the callee site already I guess?

And no, an implementation of SQL DDL "CREATE TABLE" might not need that. But for hosts, it would be neat.

**Comment by alexanderstc** [comment]
Please move this to #102.

**Comment by per-samuelsson** [comment]
> Please move this to #102.

Agree, and [done](https://github.com/Starcounter/CompanyTrack/issues/102#issuecomment-139177677). Let's let this closed issue rest.
