### ISSUE TITLE
DB Metalayer issues

### ISSUE THREAD

**Issue by alexanderstc** [Starcounter/Starcounter#2850]
- [ ] Current implementation of setspec (#2831) uses a a-z ascii character set and order, which might not necessarily work with particular DB's collation, furthermore all characters of the type id collation needs to be used. When "collation per column" feature is available from the kernel, setspecs have to be implemented correctly.
- [ ] Create key buffer with a stack-based buffer of fixed length, and a bigger dynamic buffer in case the fixed one is too small.

**Comment by alexanderstc** [comment]
Create key buffer with a stack-based buffer of fixed length, and a bigger dynamic buffer in case the fixed one is too small.

**Comment by alexanderstc** [comment]
In case an index is not unique, generate not a By...() function, but a MakeKey() functions with the same parameters to create a key which can be used together with db_iterator.

**Comment by alexanderstc** [comment]
Propagate detailed error messages to the user.

**Comment by alexanderstc** [comment]
> Propagate detailed error messages to the user.

Done, in pnext.

**Comment by dan31** [comment]
@alexanderstc shall this issue be closed?

**Comment by k-rus** [comment]
> @alexanderstc shall this issue be closed?

It is quite clear that the tasks are not done. The task, which is done, is not the same as in the original list.

**Comment by alexanderstc** [comment]
I think this issue is replaced by https://git.starcounter.org/BlueStar/level0/issues/3 and can be closed.

**Comment by alexanderstc** [comment]
... and by a number of setspec-related issues on gitlab.

**Comment by k-rus** [comment]
Agreed, closing.
