### ISSUE TITLE
Administrator doesn't work in IE11

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2852]
This is most probably to missing URL API, which can be fixed by a shim. Screenshots:

![image](https://cloud.githubusercontent.com/assets/566463/9462312/31e96844-4b15-11e5-89ee-7bdb6845a8cb.png)

![image](https://cloud.githubusercontent.com/assets/566463/9462319/406d6fdc-4b15-11e5-899a-3b3d9f104df4.png)

**Comment by warpech** [comment]
@tomalec do you think we could add an error in PuppetJs, such as: "URL API not found in your web browser. Please add a shim, for example Polymer/URL"? For a developer who doesn't read the README.md this would help to solve the problem

**Comment by tomalec** [comment]
I think we can, but I would do it only once at script load.

**Comment by warpech** [comment]
Sounds good

Btw. If you need to add a new file to Administrator, remember to add it (can be manually) to https://github.com/Starcounter/Starcounter/blob/bda4866206d53dbff897113a116e2362218b09fb/src/Starcounter.Administrator/Starcounter.Administrator.csproj or otherwise it will not be included in the installer.

**Comment by warpech** [comment]
Bump

**Comment by tomalec** [comment]
Feature support check require try/catch + some code more, as URL object is available in IE, but not standard compilant:
```js
  var hasWorkingUrl = false;
    try {
      var u = new URL('b', 'http://a');
      u.pathname = 'c%20d';
      hasWorkingUrl = u.href === 'http://a/c%20d';
    } catch(e) {}
    if(!hasWorkingUrl){
      console.warn("URL API not found in your web browser. Please add a shim, for example Polymer/URL");
    }
  }
```
