### ISSUE TITLE
Windows 10: installer freezes in default Parallels VM

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2856]
Trying to install Starcounter in default Windows 10 evaluation machine acquired from http://dev.modern.ie/tools/vms/

The installer freezes on system requirements check if the system requirements are not satisfied.

Frozen installer looks like this (the wheel is not spinning):

![image](https://cloud.githubusercontent.com/assets/566463/9493995/c50f4974-4c03-11e5-8d8e-0a73003dcb48.png)

Windows 10 Enterprise Evaluation (64-bit) in Parallels
1 GB RAM
1 CPU core (Intel)

**Comment by k-rus** [comment]
Related #2832

**Comment by warpech** [comment]
Difference from #2832 is that after increasing VM setup to 4 GB RAM & 2 CPU cores the installer succeeds.

**Comment by parherman** [comment]
Related https://github.com/Starcounter/Starcounter/issues/2759

**Comment by mtornwall** [comment]
@warpech @parherman Probably a duplicate, even. It looks like the exact same problem.

**Comment by dan31** [comment]
@alemoi @andwah Let's address the issue and #2832 next week together with other installer pimping.

**Comment by warpech** [comment]
Closing as duplicate
