### ISSUE TITLE
A few minors about the starcounter.io blog

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2858]
* Lets try not to have any blog entries be written by ["admin"](http://starcounter.io/author/admin), even if its "just" announcements. Blogs should be personal.
* A thumbnail photo next to names will make our blog portal more human. Second best is photos if you click on the name.

/cc @warpech @dan31 @tomalec

**Comment by warpech** [comment]
Good ones! I'll do it

**Comment by warpech** [comment]
> Lets try not to have any blog entries be written by "admin", even if its "just" announcements. Blogs should be personal.

Done

**Comment by dan31** [comment]
I like the idea with photo. @warpech, maybe we can ask Sabrina next time to get proper images and make nice non-JPEG-corrupted sharp thumbnail photos?

**Comment by warpech** [comment]
Closing this umbrella issue. Remaining point is covered in https://github.com/Starcounter/starcounter.io/issues/119
