### ISSUE TITLE
Create index from Web Administrator

### ISSUE THREAD

**Issue by peterbergman** [Starcounter/Starcounter#2859]
I am trying to create an index from the web based admin console with the following SQL:

```
CREATE INDEX SeatIndex ON DRTB.Database.Subscription (Seat)
```

However, this fails and gives me the following exception:

```
Starcounter.DbException: ScErrCantExecuteDDLTransactLocked (SCERR4266): Failed to execute DDL statement, since a transaction cannot be created for the execution. This can happen if the statement was called in a user-specified transaction scope. Cannot execute CREATE INDEX statement.
 Version: 2.0.3185.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4266.

at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Starcounter\Query\QueryPreparation.cs:line 67
 at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 123
 at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Starcounter\Mock\Db.cs:line 126
 at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 82
```

Am I doing it wrong or is this a bug?

**Comment by k-rus** [comment]
Thank you for your question.
Only SELECT statements are supported from Administrator. Related issue #2834.

**Comment by peterbergman** [comment]
I see, thank you for the information. But, DELETE seems to work as well?

**Comment by per-samuelsson** [comment]
> per-samuelsson changed the title from Create index from admin console to Create index from Web Administrator just now

Refined the title, not to confuse it with `staradmin` command-line (i.e. "console") admin tool.

**Comment by per-samuelsson** [comment]
> However, DELETE seem to work as well?

@k-rus, can you confirm/deny this? And then close this issue?

**Comment by k-rus** [comment]
> However, DELETE seem to work as well?
> @k-rus, can you confirm/deny this? And then close this issue?

I was told that Administrator implementation supports only SELECT statement. I guess only @andwah can confirm what actually is supported. Another problem, I don't really understand @peterbergman question.

In general, use of DELETE is not recommended, since it is not efficient and it fails on large tables.

**Comment by andwah** [comment]
The Administrator uses ```Db.SlowSQL(query)```, so everything that  ```Db.SlowSQL(query)``` supports can be used in the Administrator Query window.

**Comment by k-rus** [comment]
> The Administrator uses Db.SlowSQL(query), so everything that Db.SlowSQL(query) supports can be used in the Administrator Query window.

Actually, another important implementation detail, which affects supported queries, is used transactions. How does Administrator deal with transactions when it processes queries? Note, that `SlowSQL` executes all supported queries including CREAT INDEX and DELETE, however CREATE INDEX failed due to an error related to transactions.

**Comment by andwah** [comment]
> SlowSQL executes all supported queries

Thats excellent, then ill just need to take a look on how transactions are handled and fix that.

**Comment by peterbergman** [comment]
Ok, I just noticed that DELETE seem to work and wanted to point that out for your information.

About index creation, if it could be supported through the web administrator that would be great. In my opinion, creating and managing indexes is a typically administrative task. Having to do this from the application code is really inconvenient.

**Comment by andwah** [comment]
Resolved by re-executing the query without an Transaction
