### ISSUE TITLE
ScErrOutOfSharedStorageAbort (SCERR8012): The transaction was aborted because of a failure to allocate shared storage memory

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2860]
I get these kind of crashes. Most likely because of a bad relation between size of database and memory. 

Any help is appreciated. 

ScErrOutOfSharedStorageAbort (SCERR8012): The transaction was aborted because of a failure to allocate shared storage memory

**Comment by eriohl** [comment]
This error generally occurs when the memory on the machine is running low.

If not then is could be that either your OS for some reason doesn't allow you to allocate more memory or you created the database image for a smaller machine with less memory (could be the case if the database image file is created on a different machine).

If you could send us your event log (starcounter.??????????.log) we could look see if we could find the reason for the failure.

**Comment by Ripipip** [comment]
I got the file, but how do I send it to you in the best way? Can you call me on hangout?
