### ISSUE TITLE
InvoiceDemo1 fails because: Application can only map to handlers starting with "/polyjuice/".

### ISSUE THREAD

**Issue by parherman** [Starcounter/Starcounter#2863]
InvoiceDemo1 and acceptance tests InvoiceDemo app contains:

```c#
PoyjuiceNamespace.Polyjuice.Map("/invoicedemo", "/"); 
```
And that fails with:

> Additional information: Application can only map to handlers starting with "/polyjuice/".

since commit b088041e35d69738f4bbc48a72f627bdd262ff81

Is this change related to https://github.com/Starcounter/Starcounter/issues/2862?

@alemoi, @warpech how should InvoiceDemo1 and acceptance tests be updated?

**Comment by warpech** [comment]
@alemoi, @miyconst can you suggest solution?

**Comment by miyconst** [comment]
I think, this test should be removed, the root url mapping is no longer supported.

Optionally, we could replace it with API to configure url aliases, @alemoi should provide details of how to do that.

**Comment by parherman** [comment]
I will update the InvoiceDemo test use:

```c#
PoyjuiceNamespace.Polyjuice.Map("/invoicedemo", "/polyjuice/"); 
```

This should probably be done for https://github.com/Starcounter/InvoiceDemo also, since it fails for the same reason if you try to run it now

**Comment by alemoi** [comment]
I will disable mapping to /polyjuice/ so the test will fail again :) The solution is to use URI aliases, for aliasing /invoicedemo to root, which is done outside application.

**Comment by warpech** [comment]
I removed mapping to / from tutorial, but not from code on GitHub. Will do the changes to keep the code in GitHub in sync with the tutorial.

**Comment by warpech** [comment]
This is now fixed
