### ISSUE TITLE
Web administrator 404 when accessing it with routed URL

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2873]
Since some day(s) ago: accessing web admin using `localhost:8181` produce a 404. I talked to @andwah about it, and the workarond is to use `http://localhost:8181/index.html`.

**Comment by alemoi** [comment]
Thanks for reporting! I added URI aliasing and removed the original method. I will add back the original method.

**Comment by per-samuelsson** [comment]
> Thanks for reporting! I added URI aliasing and removed the original method. I will add back the original method.

:+1: :fire:

**Comment by andwah** [comment]
A fix has now been committed to github
