### ISSUE TITLE
pnext: Run logopt automatically to create checkpoint

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#2882]
Log writer to run logopt when appropriate.

**Comment by eriohl** [comment]
This basically works now but performance needs to be evaluated.

There is however an issue concerning how to determine checkpoint urgency on starting up. Currently it assumes that a optlog file is always created at threshold which might not be the case (and even if it was it can have been removed). Error handling is also not fully functional.

Then there is also the problem of removing replaced optlog files. This is a bit tricky since the optlog files are not necessarily created by the log writer. So how to determine which ones to remove?

**Comment by eriohl** [comment]
@bigwad: This should be incorporated into [this](https://github.com/Starcounter/CompanyTrack/issues/177) project then right?

**Comment by bigwad** [comment]
Yes, I think so

**Comment by eriohl** [comment]
Alright. I'll move this one to you then.

**Comment by bigwad** [comment]
When it's time to start logopt - it runs up to the most recent log, not up to the next one as it was before.

**Comment by eriohl** [comment]
This one is completed right?

**Comment by bigwad** [comment]
Absolutely
