### ISSUE TITLE
How to check Database Object is null or empty

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#2885]
Is there a single function to check if a database object is populated (not null and not empty).
And is it possible to use the same function to check nested database objects.

Code example to explain my question:
I want to check the GrandChild Age only, so i have to code something like  : 

if (person != null && person.Child != null && person.Child.Child != null && person.Child.Child.Age != null && person.Child.Child.Age != "")

Any help or suggestion will be really appreciated.

**Comment by miyconst** [comment]
Hello @atifsheikh!

You can select the grand child with an SQL query:

```cs
var child = Db.SQL<Person>("SELECT p FROM Person p WHERE p.Parent.Parent = ?", person).First;
``` 
And check if the `child == null`.

You also can add a property GrandChild to your Person class:

```cs
public Person GrandChild {
    get {
        return this.Child != null ? this.Child.Child : null;
    }
}
```

I don't know your model, but it seems to be wrong to reference Child from Parent, as a person could have multiply children. There should be `public Person Parent` property and `public IEnumerable<Person> Children` collection.

**Comment by dan31** [comment]
Hi @atifsheikh! Did that work out?

**Comment by atifsheikh** [comment]
Hi, Thanks for the solution and Yes your solution works fine.

But we have some cases where we do not want to add SQL queries all the
time. We are looking for some function which is something like :
if (parent.child.child.IsNullOrEmpty())
{
  return true;
}

which will further do the following checks automatically :

if (parent.IsNullOrEmpty && parent.child.IsNullOrEmpty &&
parent.child.child.IsNullOrEmpty)
{
  return true;
}


Best Regards,
Atif Waqar
Head of Development
AdFenix AB
