### ISSUE TITLE
Unhandled Exception in a UDP Handle result in a Critical db error.

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#2886]
To reproduce, try the following Handle:

    Handle.Udp(7000, (IPAddress clientIp, UInt16 clientPort, Byte[] datagram) =>
    {
        throw new Exception("My Unhandled Exception");
    });

Now, a UDP message triggers the following Critical error:

    Unspecified error (E0434352) detected at bmx_manager.cpp:119 (Thread 2624). 000007FF2AC2811C KERNELBASE!
     000007FF235EA1FF clr!
     000007FF235EACEE clr!
     000007FEC44F2CA0 <unknown>!
     000000007000468B <unknown>!
     000007FEC42626E0 <unknown>!
     0000000054A8D89A <unknown>!
     000000A8169FF968 <unknown>!
    Endless stackwalk detected. An error occured during callstack dump.

**Comment by alemoi** [comment]
Thank you for reporting! Missing catch and log in this case. I will fix it!

**Comment by dan31** [comment]
@alemoi, small fix, please don't forget taking it.

**Comment by alemoi** [comment]
Sure! Fixed via e418a96c632f5524f565464304942c434b20a642
Now the exceptions are catched and logged.
Thank you for reporting!
