### ISSUE TITLE
pnext: Fix poor log space utilization

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#2890]
We get poor utlization of log space even on high load after connection to log writer moved to DM. Leads to poor performance and storage space waste. To look into improving grouping of log entries.

There is also a lot of waste on low load since minimum log block size is 4 KiB. Maybe make is smaller to get better utilization on low load as well?

Also: Log writer spins a lot waiting for additional log entries to be posted. Better the DM waits signalling the log writer instead in order to lower CPU usage.

**Comment by eriohl** [comment]
Fixed so that DM signals log writer if to wait for additional input before flushing or not. Tested with TPC-A test and it works splendidly. Should be no reason for it to not work with with other loads as well. So space utilization on high load should be much improved.

**Comment by eriohl** [comment]
Smaller block sizes is off the table.

After investigating this we concluded that supporting smaller log block sizes then 4 KiB, to improve space utilization in case of a lot of small writes that can't be grouped with other writes, turned out to be a bad play since most new storage devices uses 4 KiB physical block size. So added complexity doesn't seem justified.

Instead the idea is to:

1. Wait for a bit longer in case immediate flush is not demanded to improve the chances that write can be grouped with other write.

2. Fill padding with zeros to make compression more efficient.

**Comment by eriohl** [comment]
Done all I can on this for now. Work is suspended pending setup of proper tests.

**Comment by bigwad** [comment]
#3283 shows that log space utilization has become worse.

**Comment by eriohl** [comment]
Since develop? This is known: Hence this issue. None of the above discussed optimizations is currently enabled (and the small wait on gather in develop is removed).

If you want to try out the optimizations then check ```gather_wait_for_more_log_entries_while_expecting_more``` and ```gather_wait_for_more_log_entries_or_write_deadline``` in log_writer_main.cpp (the later working best in my tests).

**Comment by eriohl** [comment]
I've enabled the optimization ``gather_wait_for_more_log_entries_or_write_deadline``. This works best in all scenarios I've tested.

Keeping the code for the other optimizations however. I think we may want to revisit this when tuning asynchronous commits waiting for log to complete.
