### ISSUE TITLE
Starcounter should be layout-aware

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2893]
Just discussed with @Starcounter-Jack and @alemoi:

Problem: Currently, the sample app layouts are stored in a table called `JuicyTilesSetup`, which belongs half (data model) to Starcounter, half (REST API, renderer) to Launcher. This breaks the paradigm of apps not knowing about each other's existence. 

Solution: The notion of what elements are present in templates (what's their desired size, priority, etc) is a relevant information for Starcounter. Launcher is just presenting the desired layout using a renderer called "juicy-tile-grid", but that is just an implementation. Neither Starcounter nor other apps should know if "juicy-tile-grid" or some other renderer is used.

The solution is:

1. Table `JuicyTiles.JuicyTilesSetup` should be distributed with Starcounter as `Starcounter.Layout` (@alemoi will do it)
2. The REST API should be moved from https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/Api/JuicyTilesSetupHandlers.cs to Starcounter (@alemoi will do it)
3. The layout JSON format should be described as renderer agnostic. If there are any juicy-tile-grid specific properties in JSON, they should be prefixed with `-juicy-`. (@warpech will create a separate issue about that. It is not high priority)
4. Apps should be upgraded to insert their default layouts to `Starcounter.Layout` (@alemoi will do it for few apps)

@tomalec, @miyconst comments?

**Comment by tomalec** [comment]
What about the idea of LayoutApp that would dress regular partials into
grid (on custom element level), and its setup (on data fetchin level)?
16 wrz 2015 17:46 "Marcin Warpechowski" <notifications@github.com>
napisał(a):

**Comment by miyconst** [comment]
Suggestion from @warpech sounds good to me. The Launcher is basically a LayoutApp, with some more features, we could split it into even smaller apps, but I would not like to do so.

Right now, Launcher acts like a Parent to all other apps, and that is why it may know about children and do any manipulations with them. On other hand the LayoutApp would be a sibling, which would go against mediator pattern.

**Comment by warpech** [comment]
Splitting layout app out of Launcher does not go in conflict with this change. 

But if we ever split it, then I recommend to call it "Juicy Layout", not the "Layout". Then we will have a clear understanding that this app only renders the layouts and does not define them (though the editor part of it acts as a helper in defining it).

This is something for future though.

PS. I need to see [Thinking in Polymer](https://www.youtube.com/watch?v=ZDjiUmx51y8&index=2&list=PLNYkxOF6rcICdISJclfQhj2S8QZGjXV8J) to grasp what is meant by mediator pattern, since this seems to be the word of the week :)

**Comment by warpech** [comment]
I propose to change the names of the properties as well:

Current definition:

```c#
    [Database]
    public class JuicyTilesSetup {
        public string Key;
        public string Value;

        public static void CreateIndex() {
//            Db.Transaction(() => {
                if (Db.SQL("SELECT i FROM MaterializedIndex i WHERE i.Name = ?", "JuicyTilesSetupKeyIndex").First == null)
                    Starcounter.Db.SQL("CREATE UNIQUE INDEX JuicyTilesSetupKeyIndex ON JuicyTilesSetup (Key ASC)");
//            });
        }

        public static JuicyTilesSetup GetSetup(string key) {
            return Db.SQL<JuicyTilesSetup>("SELECT c FROM JuicyTilesSetup c WHERE c.Key = ?", key).First;
        }
    }
```

I propose to rename `Key` to `TemplateURI`:
And `Value` to `Setup`

It was agreed with @Starcounter-Jack that the static method `GetSetup` should be removed in favor of using SELECT directly in the apps. (database is the API, we don't need another API on top of that)

@tomalec & @myiconst - any ideas for better names?

**Comment by miyconst** [comment]
Actually, I like the `Key`, `Value` names. We may have multiply setups for same partial, so `TemplateURI` name is not good.

What about `Name` and `Setup`?

**Comment by miyconst** [comment]
The `Key` property is used for `ObjectId` in `Simplified`, so I agree, it should be renamed.

**Comment by warpech** [comment]
`Name` is used in SO, and I guess `TemplateURI` would be synonymous to it. Let's go with `Name` and `Setup` then.

**Comment by tomalec** [comment]
:+1: for Juicy Layout setup
:+1: for renaming properties

**Comment by warpech** [comment]
Btw. the property `juicyTilesSetup` of the merged partial needs to be renamed to `layout` as well. Affected code:

- https://github.com/Starcounter/Starcounter/blob/50018807796625f0c8cd134b0d5816dc1f40bae7/src/Starcounter.XSON/Serializer/Json/StandardJsonSerializer.cs
- https://github.com/Polyjuice/Launcher/search?utf8=%E2%9C%93&q=JuicyTilesSetup

**Comment by alemoi** [comment]
In my branches I have made desired layout refactoring with help of @miyconst
We tested and layout work as expected.
Will be pushed soon!

**Comment by alemoi** [comment]
Is it decided about Key->Name and Value->Setup ?
I guess its the remaining thing here.

**Comment by warpech** [comment]
Yes :+1:

**Comment by warpech** [comment]
This was implemented long ago. Can be closed now
