### ISSUE TITLE
Starting app.exe directly does not work

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2895]
As pointed out by @bigwad in an email (6.06.2015):

> http://starcounter.io/tutorials/hello-world/ 
> Either inconsistency or an error: at the command-line section stated that app is to be started using "star" command. Later in the second example in the secon "Choosing what database to run in" application is started just by its own name.

Indeed, the following way to start an app does not work:

```
C:\> hello --database=mydb
```

With the exception:

```
c:\PolyjuiceProjects\warpech\Hello\bin\Debug>hello.exe

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assem
bly 'Starcounter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3ab
f' or one of its dependencies. The system cannot find the file specified.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPt
r* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCoun
t, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 ty
peToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodI
nstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] gene
ricTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttribut
eRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModu
le decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType,
 Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeT
ype& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean&
 isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decorate
dModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilter
Type, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTarge
tSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assemb
ly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, B
oolean inherit)
   at System.AppDomain.GetTargetFrameworkName()
```

![image](https://cloud.githubusercontent.com/assets/566463/9935458/01f1b9d0-5d57-11e5-85c9-ed13099b5de7.png)

Is this a bug in Starcounter or should I remove it from docs?

I see that it has worked before: 

- https://github.com/Starcounter/Starcounter/issues/510
- https://github.com/Starcounter/Starcounter/issues/1965

**Comment by alemoi** [comment]
As far as I know we stopped supporting self-starts of applications, so only `star.exe ..` is a suggested way. @per-samuelsson can add something on top of this.

**Comment by per-samuelsson** [comment]
> Is this a bug in Starcounter or should I remove it from docs?

We stopped supporting this quite some time back, mainly because the beneif / cost ratio was way to high (number of problems in different scenarios). So it should be removed from any documentation. Sorry we always fall behind on that. :snail: :disappointed:

**Comment by warpech** [comment]
I fixed both pages:

http://starcounter.io/tutorials/hello-world/
http://starcounter.io/guides/tools/starting-and-stopping-apps/

by removing the section about running `hello` just by its own name:

<img width="675" alt="screen shot 2015-12-08 at 12 52 29" src="https://cloud.githubusercontent.com/assets/566463/11655169/ce427652-9dab-11e5-8c08-a8bc957541d9.png">
