### ISSUE TITLE
Multiple resource dir at startup

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2898]
As discussed, it should be possible to define more than one resource dir when starting an application.
ex:
--resourcedir="dir1;dir2;dir3"
This to avoid needing to hardcode extra folders it in the code.

**Comment by per-samuelsson** [comment]
I'm assigning this to me. I have an aim to fix this and #2976 in a batch, hopefully within days.

**Comment by per-samuelsson** [comment]
Done. Merged and documented as part of #3099.
