### ISSUE TITLE
Public web folders: Regression bootstrapping wwwroot

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2899]
Testing Starcounter 2.0.3329.3, Windows 8.1, VS 2013

[InvoiceDemo2](https://github.com/Starcounter/InvoiceDemo) project does not correctly bootstrap files from `wwwroot` directory:

<img width="1249" alt="screenshot 2015-09-22 12 48 58" src="https://cloud.githubusercontent.com/assets/566463/10016687/258aeb2a-6129-11e5-8c36-8763456e0b3c.png">
<img width="1249" alt="screenshot 2015-09-22 12 49 12" src="https://cloud.githubusercontent.com/assets/566463/10016689/28703750-6129-11e5-9dff-7e0d845e86f8.png">

[InvoiceDemo3](https://github.com/Starcounter/InvoiceDemo) and [InvoiceDemo1](https://github.com/Starcounter/InvoiceDemo) bootstrap `wwwroot` correctly, though the directory is not listed in Administrator:

<img width="1249" alt="screenshot 2015-09-22 12 49 53" src="https://cloud.githubusercontent.com/assets/566463/10016694/2c900b30-6129-11e5-9ecd-5c647b2efd57.png">
<img width="1249" alt="screenshot 2015-09-22 12 50 07" src="https://cloud.githubusercontent.com/assets/566463/10016697/2fc9ca34-6129-11e5-9d81-3ca6525edeb1.png">

There is no difference in default working directories in these projects:

- InvoiceDemo2 project properties dialog shows the following working directory: **C:\PolyjuiceProjects\starcounter\InvoiceDemo\src\InvoiceDemo2**
- InvoiceDemo3 project properties dialog shows the following working directory: **C:\PolyjuiceProjects\starcounter\InvoiceDemo\src\InvoiceDemo3**

@alemoi can you take a look? 

I saw that @chrhol had similar problem today with Launcher.

**Comment by alemoi** [comment]
Thank you for reporting and descriptions!

> InvoiceDemo3 and InvoiceDemo1 bootstrap wwwroot correctly, though the directory is not listed in Administrator:

Some time I created an issue for this: https://github.com/Starcounter/Starcounter/issues/2817

I will check now, how InvoiceDemo2 wwwroot works in my environment!

**Comment by alemoi** [comment]
I looked at it. First I had to set the Working Directory to be actual project .csproj directory for Debugging.
Then I found that "MasterPage.html" contains "/InvoiceDemo/style.css" and should have "/style.css", or you should have a subfolder "InvoiceDemo" in wwwroot. Does it fix problems for you?

However, I think the first step should not be required. I should just download the project and hit F5, right? I thought its already working like that, but its not. We should discuss that I guess.

**Comment by warpech** [comment]
Sorry, my bad! This was indeed regression in InvoiceDemo2 (since May :/)

> However, I think the first step should not be required. I should just download the project and hit F5, right? I thought its already working like that, but its not. We should discuss that I guess.

No, it is working like that. The only problem was the path to `/style.css`. I suppose that the Launcher problem in OP must have been something else.

Closing this issue, since the other request is already described in #2817.
