### ISSUE TITLE
ScErrInputQueueFull (SCERR1026): Operation failed because the target input queue was full.

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2900]
Our starcounter apps crashes with the following error: 

ScErrInputQueueFull (SCERR1026): Operation failed because the target input queue was full.

Any idea what to the reason can be?

**Comment by dan31** [comment]
Hi @Ripipip! I think we already investigated such case when you do a cascaded calls for ```RunAsync```. How do you use it currently?

**Comment by Ripipip** [comment]
Thank you @dan31 ! You pointed my in the right direction and I found the bug :)
