### ISSUE TITLE
Administrator doesn't clean up app installations that are in incorrect state

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2901]
I cannot install an app using the AppStoreClient on Playgrounds server (AWS):

<img width="1493" alt="screenshot 2015-09-23 13 12 20" src="https://cloud.githubusercontent.com/assets/566463/10043649/075e0016-61f5-11e5-8ad6-7a9f6fccef55.png">

Despite the above error message, no such app is installed according to Administrator on the machine:

![image](https://cloud.githubusercontent.com/assets/566463/10043629/dd55ae90-61f4-11e5-867f-5fc02f8eeec6.png)

Indeed there is an app on disk though. The files were created yesterday:

![image](https://cloud.githubusercontent.com/assets/566463/10043696/63cfbb3c-61f5-11e5-94e8-9a30258b26ed.png)

@andwah, any ideas?

**Comment by miyconst** [comment]
This also happened to me in the past.

**Comment by warpech** [comment]
Now I had a similar problem on a clean database and installation:

1. I installed Launcher, Products, AppStoreClient
2. From AppStoreClient I tried to install Barcodes
3. Barcodes installed but it didn't start. (similar effect to the first screenshot above)

I needed to start it manually from Administrator

**Comment by andwah** [comment]
At the moment the only thing i can think of that can cause this is if the folder was "locked" by some appication/cmd prompt when you tried to uninstall the application.

Can you check what's left in your "invalid" ```Polyjuice.Proucts``` folder.

**Comment by warpech** [comment]
I've sent you the server login details so you can take a look around. I left the environment intact

**Comment by andwah** [comment]
I have made some changes on how apps is installed/upgraded/uninstalled.

Can this still be reproduced, otherwise i think we can close this issue

**Comment by warpech** [comment]
I haven't seen this in a while, so I guess so. We can open a new issue if this is reproduced again
