### ISSUE TITLE
Update apps Javascript tests to conform with latest changes

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2905]
Please update Javascript tests for each of the following applications:

- [x] SignIn
- [x] Launcher
- [x] Products
- [x] Barcodes
- [x] Procurement
- [x] Skyper
- [x] ~~Images~~ - does not have any tests
- [ ] ~~Cartographer~~ - very outdated app, should be removed from build tests

Note that root handler is now prohibited, so it should be excluded from tests.

Currently running tests is disabled (previously were running in Polyjuice project in TeamCity that is now paused and will be deleted). To test, run Starcounter daily/nightly build with SC_RUN_APPS_TESTS parameter set to True.

**Comment by alemoi** [comment]
@dan31 this is quite urgent issue since we skip running these tests on the build system.
Reminder: the calling script is located here https://git.starcounter.org/BlueStar/buildsystem/blob/develop/src/Scripts/RunAppsTests.bat
The calling script does not do much except calling JS tests for each app.
Each of the above apps has a `test\test.js` JS test that runs (which should be corrected).

**Comment by warpech** [comment]
@miyconst could you take a look? This should be 15 mins work for each of the apps.

**Comment by warpech** [comment]
Yes. Tests should always be a priority

**Comment by alemoi** [comment]
One comment: root handlers should be removed from tests, since root aliasing is now done outside the applications.

**Comment by miyconst** [comment]
Updated the first comment.

@warpech, I think the Skyper and Cartographer apps should be either fully reworked or completely removed from public access.

**Comment by miyconst** [comment]
Skyper also migrated and checked.

**Comment by alemoi** [comment]
Fixed the remaining problems with build scripts. Now tests are running by default in daily/nightly.

**Comment by miyconst** [comment]
Can we close this issue then? Cartographer has it's own issue: https://github.com/StarcounterSamples/Cartographer/issues/2

**Comment by alemoi** [comment]
I just pushed recent changes related to OntologyMap and updated all above apps accordingly:
https://github.com/Starcounter/Starcounter/issues/2911

**Comment by miyconst** [comment]
Closing this issue as nothing more left to do.
