### ISSUE TITLE
Inconsistent naming of database(s) collection in admin API

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2908]
To get at a specific database in the Starcounter Administrator REST API, one does a:

    GET /api/admin/databases/[Name]

But to list the database's applications collection, it's instead:

    GET /api/admin/database/[Name]/applications

Notice the plural database**s** in the former case, singular database in the latter. I assume this inconsistency is a mistake, particularly since:

    GET /api/admin/database/[Name]

... yields a 404!

/sub @andwah

**Comment by andwah** [comment]
Thanks for finding this.
Yes this was a mistake and has now been corrected in commit d663d7d4d694aaffdb8bc200c48fc1c2a0489911

The correct naming is plural ```databases```

**Comment by warpech** [comment]
@andwah Please add information about this breaking change to the changelog

**Comment by andwah** [comment]
Changelog updated.
