### ISSUE TITLE
Question: Performance implications of dynamically constructing SQL queries

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2910]
In the interest of simplifying maintenance and refactoring I have adopted the following technique for constructing SQL queries. Suppose I have a database object called `Foo`, for which I want to select all instances.

    Db.SQL<Foo>("SELECT f FROM " + typeof(Foo).FullName + " f");

This allows me to rename and move `Foo` whilst remaining relatively confident that the code will still run. However, while this is convenient during development I am concerned that it may carry severe performance implications. For instance, does it impact the SQL engine's ability to cache query plans? (If it does, would interning the string help?)

Is this safe, or should I avoid it altogether?

NB: Unfortunately the compiler doesn't seem to be able to statically determine the value of the concatenated string.

**Comment by dan31** [comment]
@mtornwall, from what I see I don't see impedance on caching, since it caches runtime and by string. @k-rus @alemoi do you agree? @k-rus, a short idea alongside. I've seen in one of @per-samuelsson posts a form like this:
```var p = Db.SQL<Foo>("WHERE Name = 'John'"); // assumes adding a default prefix SELECT p FROM Person p ... ```
Maybe that's something we should opt for? 75% of the time the prefix in queries will be default one. (I'm not raising a support for LINQ driver there intentionally).

**Comment by alemoi** [comment]
I would say as long as its determined once during the program run - its great. However if its on every call, then its bad. It does not affect SQL cache utilization though.

**Comment by miyconst** [comment]
This 
```
typeof(Foo).FullName
```
will cause unexpected errors if class name is a reserved SQL keyword, for example `Order`.

**Comment by k-rus** [comment]
I confirm that the initial example cannot affect the cache, since SQL sees the final string and table name is not considered to be literal.
The main performance drawback comes from the string concatenation, which is quite expensive. Currently, we don't provide good support for this user case.

**Comment by mtornwall** [comment]
Thanks for your feedback everyone!

Regarding the cost of string concatenation I have conducted independent microbenchmarking that show a noticeable overhead. We'll see if I end up running this in production.
