### ISSUE TITLE
Replace instances of /so/ in OntologyMap

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2911]
Code like this is difficult to explain in tutorials:

```cs
Polyjuice.OntologyMap("/chatter/partials/person/@w", "/so/person/@w", null, null);
Polyjuice.OntologyMap("/chatter/partials/chatgroups/@w", "/so/group/@w", null, null);
Polyjuice.OntologyMap("/chatter/partials/chatattachment/@w", "/db/simplified.ring6.chatattachment/@w", null, null);
```

Only local data model should be used in OntologyMap:

```cs
Polyjuice.OntologyMap("/chatter/partials/person/@w", "/db/simplified.ring2.person/@w", null, null);
Polyjuice.OntologyMap("/chatter/partials/chatgroups/@w", "/db/simplified.ring6.chatgroup/@w", null, null);
Polyjuice.OntologyMap("/chatter/partials/chatattachment/@w", "/db/simplified.ring6.chatattachment/@w", null, null);
```

This was agreed with @alemoi and @dan31.

To be done in all demos and code samples.

**Comment by alemoi** [comment]
Basically renaming /so/ to /db/ will solve the issue @warpech ?

**Comment by dan31** [comment]
@alemoi @warpech what should be instead of ```Ontology```?

**Comment by warpech** [comment]
@dan31 This issue is about changing a parameter of `OntologyMap`, not renaming `OntologyMap` (we want that as well but not now).

@alemoi not only renaming `/so/` to `/db/` but also changing shorthand table name to full (Simplified) table name

**Comment by alemoi** [comment]
I am about to finalize this issue, but have a question: its another braking changes, since "/so/" won't be available and only full class names would be allowed. Btw the prefix will be "/sc/db", since it relates to system handlers.
Of course I will have it mentioned in change log, but what about versioning?

**Comment by alemoi** [comment]
For example, this is how things now look for Products:
```cs
UriMapping.OntologyMap("/Products/partials/product/@w", UriMapping.OntologyMappingUriPrefix + "/concepts.ring2.vendible/@w", null, null);
UriMapping.OntologyMap("/Products/partials/supplier/@w", UriMapping.OntologyMappingUriPrefix + "/simplified.ring2.organization/@w", null, null);
```
What do you think?

**Comment by miyconst** [comment]
1. Can't we support both of the syntax for some time and mark the old one as deprecated?
2. Why this `UriMapping.OntologyMappingUriPrefix + ` should be added manually? Are there any other prefixes to use? If no, then it should be added inside the `UriMapping.OntologyMap` method.

**Comment by warpech** [comment]
@alemoi are you doing this at Starcounter level? I intended this to be only a change in the **demos and code samples**, which means it is not a breaking change in Starcounter (because it is not a change in Starcounter at all)

@miyconst:

> 1 . Can't we support both of the syntax for some time and mark the old one as deprecated?

I don't even want marking old one as deprecated, just stop to use it where it doesn't make sense.

> 2 . Why this UriMapping.OntologyMappingUriPrefix + should be added manually? Are there any other prefixes to use? If no, then it should be added inside the UriMapping.OntologyMap method.`

I believe `UriMapping.OntologyMappingUriPrefix` is just a shorthand for "/sc/db" (actually a shorthand that is longer ;) ). There is no obligation to use it. @alemoi it seems that it is not documented anywhere, is it?

**Comment by alemoi** [comment]
Yes, usage `UriMapping.OntologyMappingUriPrefix` will, of course, be documented, its /sc/db. Its publicly given to user because we are creating an actual URI handler out of it, same as for `UriMapping.MappingUriPrefix`.
About breaking change I thought if it breaks the demos as well, which was simply my wrong understanding of "breaking" :)

**Comment by alemoi** [comment]
Just pushed the proposed changes via f4f3a0e1e827e2b886491ea8b74e80a2120d62c3
Change log updated accordingly.

**Comment by alemoi** [comment]
As extra, added a possibility to call OntologyMap and supply only full class name as second parameter.
