### ISSUE TITLE
OFFSETKEY sample in wiki does not work

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2915]
As part of #2455 I am trying to move the page about [SQL OFFSETKEY](https://github.com/Starcounter/Starcounter/wiki/SQL-OFFSETKEY)

The code sample at that page (_Example of using OFFSETKEY_) does not work for 2 reasons:

- `string k  = null;` should be changed to `byte[] k  = null;`
- the execution stops at `if (k == null) return;` because `k` is null

My full test code:

```c#
using System;
using Starcounter;

namespace Snippets {
  class OffsetKey {
    public OffsetKey() {
      Db.Scope(() => {
        Db.SlowSQL("DELETE FROM Snippets.Account");

        for (var i = 1; i < 20; i++) {
          new Account() {
            AccountId = i
          };
        }

        byte[] k = null;
        using (IRowEnumerator<Account> e = Db.SQL<Account>("SELECT a FROM Snippets.Account a WHERE a.AccountId < ? FETCH ?", 100, 10).GetEnumerator()) {
          while (e.MoveNext()) {
            Account a = e.Current;
            Console.Write(a.AccountId + " ");
          }
          k = e.GetOffsetKey();
        }
        if (k == null) return;
        Console.WriteLine();
        using (IRowEnumerator<Account> e = Db.SQL<Account>("SELECT a FROM Snippets.Account a WHERE a.AccountId < ? FETCH ? OFFSETKEY ?", 100, 5, k).GetEnumerator()) {
          while (e.MoveNext()) {
            Account a = e.Current;
            Console.Write(a.AccountId + " ");
          }
          k = e.GetOffsetKey();
        }
        Console.WriteLine();
      });
    }
  }
}
```

@k-rus Please advise what to do with migration of that page.

**Comment by k-rus** [comment]
I confirm the found problems and resolution. The offset key documentation was not changed in accordance to the implementation.

**Comment by k-rus** [comment]
> string k = null; should be changed to byte[] k = null;

I updated this on the page.



> the execution stops at if (k == null) return; because k is null

I confirm that it does not work as expected. Has to be investigated further.

**Comment by k-rus** [comment]
Thank you for testing and reporting!

**Comment by k-rus** [comment]
The bug is fixed. I think the page about `Offsetkey` can be moved to the correct place.

**Comment by warpech** [comment]
Thanks! I will move the page to the .io website

**Comment by dan31** [comment]
Thanks @k-rus! @warpech is doing amazing work (with help of other guys for sure) going through all the corners of our docs, now you can literally read our docs as a book :+1:
