### ISSUE TITLE
Starcounter error - Assertion failed!

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2918]
From time to time I receive this error.

Very often it requires to restart PC to get the applications work back again.

![image](https://cloud.githubusercontent.com/assets/6435556/10134933/386a4f2c-65ea-11e5-8744-397eacd50048.png)

I have discovered, that these sets of apps always trigger this error: SysUpgrade, Launcher, AppStoreClient.

In my scenario all of the apps are opened in a separate VS instance, started with `Ctrl + F5` (no debugging), one after another one (first wait till the previous app starts, then start the next one).

**Comment by miyconst** [comment]
cc @alemoi

**Comment by alemoi** [comment]
Thank you for reporting! After some investigation and trial/error while trying different code/data relocation schemes used in LLVM, the issue seems disappeared (at least on @miyconst machine, but we need to test more). Unfortunately most probably its related to the following relocation-related issues inside LLVM itself:
* https://llvm.org/bugs/show_bug.cgi?id=15356
* https://llvm.org/bugs/show_bug.cgi?id=21423

I will create a separate issue for this for LLVM community.

**Comment by alemoi** [comment]
@miyconst thank you for testing the possible fix. Waiting for the same from @andwah 

Here is the bug I submitted to LLVM: https://llvm.org/bugs/show_bug.cgi?id=24978

**Comment by miyconst** [comment]
Just a little note:

>Environment: Windows 8 x64.

It should be Windows **8.1**.

**Comment by alemoi** [comment]
> It should be Windows 8.1.

Thanks for the info!

**Comment by dan31** [comment]
@alemoi, what sort of assertions it is? Should we build the llvm bins without debug info to suppress that? Since that happens when people run demos, and then you need to do manipulations with server to bring stuff back to life, that is the worst thing to imagine happening.

**Comment by alemoi** [comment]
Its any-build assertion inside the LLVM itself regardless if its Debug or Release.

**Comment by alemoi** [comment]
Here is an excerpt from LLVM Im talking about:
```cs
  case ELF::R_X86_64_PC32: {
    uint64_t FinalAddress = Section.LoadAddress + Offset;
    int64_t RealOffset = Value + Addend - FinalAddress;
    assert(isInt<32>(RealOffset));
    int32_t TruncOffset = (RealOffset & 0xFFFFFFFF);
    support::ulittle32_t::ref(Section.Address + Offset) = TruncOffset;
    break;
  }
```

**Comment by miyconst** [comment]
This is fixed, thanks to @alemoi.
