### ISSUE TITLE
Fix bower.json

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2921]
The files in https://github.com/Starcounter/Starcounter/tree/develop/src/BuildSystem/ClientFiles were upgraded to be compatible with Polymer 1.1 manually.

This should be done with Bower. File [bower.json](https://github.com/Starcounter/Starcounter/blob/develop/src/BuildSystem/ClientFiles/bower.json) needs updating.

**Comment by miyconst** [comment]
Fixed and tested by @alemoi, big thanks for that.

**Comment by warpech** [comment]
Looking good now, thanks!
