### ISSUE TITLE
Question: How to get the thread's ID?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#2923]
How can i get the Thread's ID for monitoring if its live or crashed. My code for creating the Thread is as following : 

                DbSession dbSession = new DbSession();
                dbSession.RunAsync(() =>
                {
                    AdFenix.Database.DownloadQueue.StartDownloadingQueue();
                });

and i want to track "dbSession" thread's status.

**Comment by mtornwall** [comment]
Disclaimer: I'm not a Starcounter employee.

To my knowledge (I'm sure somebody will correct me if I'm wrong), there's a one-to-one mapping from Starcounter schedulers to threads. Notice that `RunAsync` takes a second, optional parameter called `schedId`, which defaults to 255 (which I believe always results in the task being run on scheduler zero).

So, it seems to me that if you want to keep track of the thread that runs your asynchronous code, you could attempt something like this:

```
var dbSession = new DbSession();
var tid = System.Threading.Thread.CurrentThread.ManagedThreadId;
var sid = Starcounter.Internal.StarcounterEnvironment.CurrentSchedulerId;
dbSession.RunAsync(() =>
{
    // Code will be run on scheduler <sid> in thread <tid>.
}, sid);
```

As always, YMMW. :-)

**Comment by atifsheikh** [comment]
Great. This is exactly what i was looking for, but only one thing remains, how do i check the status of "sid"? 
for example after executing this code, i want to keep checking the status of this "sid", how can I do that?

**Comment by mtornwall** [comment]
What exactly do you mean by the status? If the database is operational, then presumably its schedulers are also.

**Comment by atifsheikh** [comment]
I just tested the code, and its giving me the same tid & sid for all the threads that i create. here is my code samples :
for (int loop = 0 ; loop < 10 ; loop++)
{
	DbSession dbSession = new DbSession();
	var sid = Starcounter.Internal.StarcounterEnvironment.CurrentSchedulerId;
	dbSession.RunAsync(() =>
	{
		var tid = System.Threading.Thread.CurrentThread.ManagedThreadId;
	},sid);
}

i tested it both ways, by putting tid outside of "dbSession.RunAsync(())" and inside it. but it always gives the same tid.

**Comment by atifsheikh** [comment]
and by status i mean, i need to check that is the thread still running or stopped or crashed.

**Comment by mtornwall** [comment]
I doubt the code you posted above is creating any threads at all. Presumably it's invoked in response to some HTTP request? In that case, it's being run on a Starcounter scheduler, whose ID is obtained using  `CurrentSchedulerId`. You then go on to schedule an asynchronous task *on that same scheduler*.

As for checking the status of the scheduler thread, I believe this is neither possible nor necessary: like I said, if the database is operational then its schedulers should be running. If you're concerned that some asynchronous operation may fail (which it may, without bringing down the scheduler, mind you!) then you should wrap the code that could fail in an exception handler and provide a facility to notify the caller.

**Comment by atifsheikh** [comment]
Got it. Thank you for your help @mtornwall :)
