### ISSUE TITLE
Invalid css styles for sign up work

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2924]
This is how form looks like if I press "SEND" button before filling any data to invalidate the form.

![image](https://cloud.githubusercontent.com/assets/6435556/10247999/0e869540-691d-11e5-949d-fc4b6535b0e1.png)

cc @warpech

**Comment by warpech** [comment]
Thanks for reporting!

**Comment by warpech** [comment]
Just checked, the problem still exists with the current webinar signup:

<img width="853" alt="screen shot 2015-12-09 at 13 08 02" src="https://cloud.githubusercontent.com/assets/566463/11685004/0613354c-9e76-11e5-9d2f-83fe283d3962.png">

@sabrinareflex could you take a look?

**Comment by sabrinareflex** [comment]
With the CSS, I can’t change that the form turns yellowish when it’s not filled correctly. This is a default setting with Act-on that I already talked to them about before but there is nothing that can be done to change the color of it. They said that they are working on it for future updates of Act-on so we might be able to do it later on.

I did change the text-color though so if the form turns yellowish you can see the text that you fill in.

**Comment by warpech** [comment]
Thanks. Just to note, the same problem applies to the .io form:

<img width="1132" alt="screen shot 2015-12-10 at 11 13 43" src="https://cloud.githubusercontent.com/assets/566463/11712739/3c864cb8-9f2f-11e5-897e-80746f90acf7.png">

**Comment by miyconst** [comment]
Looks to be fixed. Closing the issue.
