### ISSUE TITLE
The sign up form does not work

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2925]
Here http://www.starcounter.com/activities/ the **SIGN UP HERE!** form does not work. After filling in data and pressing **SEND** button nothing happens.

The button is an `<a>` which calls `doSubmit(document.getElementById('form_000d'))`, manual execution of this js in console results in the following exception: 
```
Uncaught ReferenceError: doSubmit is not defined(…)
```

cc @warpech

**Comment by warpech** [comment]
Thanks! Passed it over. We will look into that tomorrow.

**Comment by warpech** [comment]
Thanks for reporting!

Not relevant since the redesign of the page. Future sign-up forms should work ok.
