### ISSUE TITLE
Add link to tutorials that explains how to upgrade starcounter

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#2926]
I tried the [tutorial](http://starcounter.io/tutorials/1-introduction-to-part-1/) but got stucked at section "Render JSON in HTML" because my version of starcounter was missing the file `/sys/dom-bind-notifier/dom-bind-notifier.html`. Fortunately I found the [SysUpgrade app](https://github.com/StarcounterSamples/SysUpgrade) :-)

It would be nice to have a hint there that gives you an idea why your browser window is empty and possible solutions.

**Comment by warpech** [comment]
Tutorials assume you are running current version of Starcounter. 

And this particular thing was just changed on October 1st with the release of Starcounter 2.1... But I agree the we could put an information about required version somewhere on the page.

With Starcounter 2.1, SysUpgrade is not needed. But I admire that you were able to find it on your own!

**Comment by miyconst** [comment]
Added a note to the tutorials page:

>Note: all of the tutorials require the latest version of Starcounter and may not work in the previous versions.

**Comment by warpech** [comment]
I have changed the text to say:

> Note: all of the tutorials require the latest **stable** version of Starcounter and may not work in the previous versions.
