### ISSUE TITLE
Unclear errors when the URL does not begin with /

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2932]
This issue applies to URL handlers and calling urls:

```c#
Handle.GET("People/person/{?}", () => { /*... */} );
Self.GET("People/person/123");
```

Notice that the URLs don't begin with `/` by programmer's mistake.

In case of `Handle.GET`, the above code will work as long as `EnforceURINamespaces` is `false`. I think this should throw an exception because the URL does not begin with `/`.

In case of `Self.GET`, the above code will return `null`. I think this should throw an exception because the URL does not begin with `/`.

@alemoi WDYT? I think this should be discussed before changing. But I have seen this problem multiple times. Last time today in @malx122's screen.

**Comment by alemoi** [comment]
I agree with both statements.

**Comment by warpech** [comment]
Note that it a `Http.GET` on the other hand does not have to begin with `/` (because it is an external call)

**Comment by alemoi** [comment]
Yes, absolutely. The current requirement for `Http.GET` is to begin with `http:\\`.

**Comment by alemoi** [comment]
Big thanks for reporting this! Fixed locally and will be pushed tonight!

**Comment by alemoi** [comment]
Thank you, pushed via 855f00fa638fe69f89ddaf8dfbaa40f4794c4f89
