### ISSUE TITLE
Clicking on the app name in Administrator AppStore shows JSON

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2934]
See screencast:

![bug](https://cloud.githubusercontent.com/assets/566463/10338947/1da15444-6d09-11e5-8d64-c9e1eef8fcde.gif)

For not installed apps, I think the link should be disabled until we have a source to display app detail information.

For installed apps, I think the link should lead to the installed app info, e.g. `/#/databases/default/applications/842E753FA1048B138D2295CD8D26B343`

**Comment by warpech** [comment]
Found today by @jakubklekota

**Comment by andwah** [comment]
The page for showing an apps page has not get been developed yet, it was delayed but it's something im working on now.

**Comment by warpech** [comment]
Any reason why this was closed? It is still reproducible in current nightly 2.1.1058

This was reported to me again yesterday by @MLidstrom

**Comment by andwah** [comment]
> It is still reproducible in current nightly 2.1.1058

 I guess the browser cache needs to be refreshed?

**Comment by warpech** [comment]
You are right. After clearing the cache the link does not appear:

<img width="1403" alt="screen shot 2016-01-20 at 13 55 25" src="https://cloud.githubusercontent.com/assets/566463/12449436/8b2f3942-bf7d-11e5-9f51-60018d8af6c0.png">
