### ISSUE TITLE
Allow to copy text from the server log

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#2942]
At the moment it is not possible to copy text from the server log. It is only possible to copy the whole record. That is not user friendly if I am trying to copy&past the help url out of one record.

**Comment by warpech** [comment]
Thanks! Taking this on me

**Comment by per-samuelsson** [comment]
@jwillmer 

FWIW, if you are OK to go to a CLI environment, you can consume the log from there. Not the same thing o/c, but just saying.

Its done with the `staradmin` command-line tool. For example, putting the last 100 log entries level notice and up on the clipboard, you could fire up a standard command-prompt and do:

```
staradmin list --max=100 log notice | clip
```

Paste them to notepad or whatever, and do whatever with them there.

Thats just until @warpech gets the real thing done of course. :smile:

**Comment by warpech** [comment]
Additionally, when copy pasting multiple rows, changes are copied in strange CSV format. This was reported by @andwah by email and may or may not be related.

**Comment by warpech** [comment]
Thanks a lot for the useful tip @per-samuelsson!

**Comment by warpech** [comment]
Fixed in https://github.com/Starcounter/Starcounter/commit/38b7402b041fa5ca05dbd18f84b4b84c04b046c3. Thanks @jwillmer for reporting!
