### ISSUE TITLE
URL to apps

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#2943]
How do I know which url do I have to enter to open an app (that I have installed from the app store)? Clicking in the database on the app only opens the description and console window of the app but there is no relative path ´~\appstoreApp´.

**Comment by warpech** [comment]
Thanks for the question! The principle is that the first segment of the URL is the same as the name of the exe file (without the ".exe" part).

But I agree that Administrator should be able to display a link to the app. Maybe we should create an entry for this in package.config? @andwah, WDYT?

**Comment by andwah** [comment]
To have in in the config will be the best solution. but at this point i think it's enough to use the appName as @warpech described. But i will have this in mind when we move to the next package handling (nuget, etc..)

**Comment by andwah** [comment]
I Added a ```OPEN``` button, cae854c372bd6f9cd0c331c2d164f3a1f150c559

![image](https://cloud.githubusercontent.com/assets/2656996/10388641/058d84fe-6e6c-11e5-995f-70a92aad0ece.png)

![image](https://cloud.githubusercontent.com/assets/2656996/10388666/2ac9c3b8-6e6c-11e5-8a6c-dfa25518101e.png)
