### ISSUE TITLE
Launcher 2.0.8 is missing Polyjuice.exe/.dll

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#2944]
I can't start the launcher becase he is missing the Polyjuice.exe. I did a fresh installation of the database (uninstall  old, install [2.1.95](http://downloads.starcounter.com/download/Starcounter/DevelopNightlyBuilds/2.1.95)) but it did not resolve the issue.

Is it a launcher problem or a database problem?

**Comment by warpech** [comment]
Starcounter 2.1 introduced some breaking changes (actually simplifications) that are not compatible with Launcher 2.0.8. Make sure you try the current version of Launcher (3.0.3)

List of changes in Starcounter 2.1:

- http://starcounter.io/nightly-changes/starcounter-2-1-now-compatible-with-polymer-1-1/
- http://starcounter.io/nightly-changes/list-breaking-changes-starting-build-2-1-1-3/

We will remove the old app versions from the app store.
