### ISSUE TITLE
Static files in /sys/ does not get refreshed in cache after update

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Starcounter#2946]
I'm working with files provided in `\ClientFiles\StaticFiles\sys` directory. Currently I need to restart entire app to see any changes, as:

1. Open the page that uses something from `/sys` in browser 
2. Change the file in file system
3. Clear the browser cache, refresh the page

Gives previous non-changed version.

/cc @alemoi

**Comment by alemoi** [comment]
Thank you for reporting! I will check this one!

**Comment by alemoi** [comment]
I tried to reproduce this but could not. For example I used Products app, modified "/sys/webcomponentsjs/webcomponents.js", clicked F5 and the actual contents of webcomponents.js were immediately changed. Are you using some kind of network drive or shared network directory in Virtual Machine?

**Comment by tomalec** [comment]
I use just regular local drive, and SC 2.1.116

**Comment by dan31** [comment]
@tomalec is that still an issue?

**Comment by tomalec** [comment]
It's not. Thanks :)
