### ISSUE TITLE
Cross-browser dom-bind-notifier + jsonpatch

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Starcounter#2948]
@miyconst pointed out, there is a serious issue with running `dom-bind-notifier` + `Object.observe` shim  and  `fast-json-patch`.
As puppet's observer is called on it's own changes.

Seems to either be a bug deep in puppetJS, or something really wrong with our dom-puppet-jsonpatch flow.

@warpech Some meeting to clearly define and describe Puppet flow would be great.

**Comment by warpech** [comment]
Is this solved by https://github.com/Starcounter-Jack/JSON-Patch/issues/82?

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Starcounter/issues/2922

**Comment by miyconst** [comment]
No, this was solved by https://github.com/MaxArt2501/object-observe/issues/16 and https://github.com/MaxArt2501/object-observe/issues/18.
