### ISSUE TITLE
Avoid JSON binding for a property

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2953]
I have a database object that looks something like this:

```
[Database]
public class Person {
      public string Name;
}
```

I also have a JSON viewmodel bound to it, defined as follows:

```
{
    "Name": {
        "FullName": "", // should be bound to name
        "OtherThing": "",
        "AnotherThing": ""
    }
}
```

The JSON layer seems to be attempting to bind the `Name` property of `Person` to the `Name` object in the viewmodel, and this fails for obvious reasons. Is there any way that I can opt out of this binding?

**Comment by chrhol** [comment]
Yeah, there are a couple of different ways to opt out or bind to another property you can use. The easiest in this case is probably to add another "metadata"-property in the json that specifies the binding.

```
{
    "Name": {
        "FullName": "", // should be bound to name
        "$FullName": { "Bind": "Name" },
        "OtherThing": "",
        "AnotherThing": ""
    },
   "$Name": { "Bind": null }
}
```

You can also do it from code by modifying the underlying Template. There is some documentation here: http://starcounter.io/guides/json/json-data-binding/

**Comment by mtornwall** [comment]
@chrhol Excellent, that solved the problem! Thanks.

**Comment by Starcounter-Jack** [comment]
We should make sure this goes into the docs.

**Comment by chrhol** [comment]
> We should make sure this goes into the docs.

@Starcounter-Jack: There is an issue a few months old, #2650, about reviewing how we specify metadata (and what should be included) before we document it since it contains a lot of stuff that isn't really used and that is left from other changes.

**Comment by dan31** [comment]
@chrhol, maybe we can just document on .io what we have today as much as possible during the work on code? This is the simplest way to make our current users more productive. When it comes to using TypedJson, there are indeed multiple ways today to do the same thing. We can make the whole thing slicker when addressing TypedJson implementation for SC 3.x. I don't think #2650 impedes us from explaining the existing functionality in doc, correct me if I'm wrong. (This applies not only to TypedJson, we have some other things we don't document thinking they are incomplete, while people are already using them). The same time, writing it down will highlight the existing problems and ways to address them.

**Comment by chrhol** [comment]
Fair enough @dan31 :) I will add a page on io describing the current available options and parameters for specifying special metadata for TypedJSON.

**Comment by warpech** [comment]
I agree with @dan31. `

Bind` metadata is explained on page http://starcounter.io/guides/json/json-data-binding/, but not the `null` usage. I think that only extending info on that page is needed.

A table of contents can be added on that page, similarly to http://starcounter.io/guides/tools/administrator/. Let me know if you need help with that

**Comment by chrhol** [comment]
> Bind metadata is explained on page http://starcounter.io/guides/json/json-data-binding/, but not the null usage. I think that only extending info on that page is needed.

Ahh yeah I see. It's actually in the page already but it's hidden inside another section and you probably will not find it unless you know what to look for. I will update this page first then.

> A table of contents can be added on that page, similarly to http://starcounter.io/guides/tools/administrator/. Let me know if you need help with that

I will take a look and try to add it.

**Comment by warpech** [comment]
Wow, indeed! That proves the table of contents would be nice
