### ISSUE TITLE
Question : How to create a "List" type variable in a Table

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#2957]
I want to achieve something like : 
[Database]
public class Product
{
    public String Name;
    public List<ShoppingStore> AvailableInStores;
}

**Comment by dan31** [comment]
Hi @atifsheikh, and thank you for the question! To get collections, do like described here http://starcounter.io/tutorials/1-introduction-to-part-1/1-6-create-the-database-classes/. Like that:
```c#
public QueryResultRows<Stores> AvailableInStores {
        get {
            return Db.SQL<Stores>("SELECT s FROM Stores s WHERE ...", this);
        }
    }
```
In WHERE clause you will be using a foreign key that you will use to associate products and stores.

**Comment by mtornwall** [comment]
@atifsheikh After reading what @dan31 linked I suggest you also take a look at [modeling many-to-many relations](http://starcounter.io/guides/database/many-to-many-relations/), since it should presumably be possible to have products that are available in multiple stores.

**Comment by dan31** [comment]
Scheme with an edge-relation as a separate class looks very good, @mtornwall :+1:

**Comment by atifsheikh** [comment]
@mtornwall . :+1: Great. I needed this exact thing. 
I am currently doing it the way @dan31 suggested, but its not very optimal. 

Thank you guys for the help :)

**Comment by dan31** [comment]
@mtornwall @atifsheikh Super-easy :+1:
