### ISSUE TITLE
CLR Class is not loaded for table

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2960]
There is a class `MailMessage` in @warpech example for the CodeNight
https://github.com/StarcounterSamples/CodeNight/blob/master/MailMessage/Db.cs
which is inherited from `Simplified.Ring1.Something`.

If there are any `MailMessage` in database and the MailMessage application is not started, then sql query:
```sql
SELECT s 
FROM Simplified.Ring1.Something s
```

fails to execute with the following exception:

```
Starcounter.DbException: ScErrSchemaCodeMismatch (SCERR4177): Operation failed be because input does not match schema. CLR Class is not loaded for table MailMessage
Version: 2.1.185.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4177.
   at Starcounter.Binding.Bindings.CreateExceptionOnTypeDefNotFound(Int32 tableId) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-40\Level1\src\Starcounter\Binding\Bindings.cs:line 442
   at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(Int32 tableId) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-40\Level1\src\Starcounter\Binding\Bindings.cs:line 317
   at Starcounter.Enumerator.MoveNext() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-40\Level1\src\Starcounter\Mock\Enumerator.cs:line 239
   at Starcounter.Query.Execution.IndexScan.MoveNextManaged() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-40\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 475
   at Starcounter.Query.Execution.IndexScan.MoveNext() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-40\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 550
   at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-40\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 139
ErrorCode=4177
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4177
```

cc @chrhol, @alemoi, @k-rus, @warpech, @dan31

**Comment by miyconst** [comment]
Trying to empty database with sql:

```sql
DELETE
FROM Simplified.Ring1.Something
```

produces same error.

**Comment by per-samuelsson** [comment]
I think this is a known limitation (or more precise: a bug). If not this particular case, so at least the fact that some things work a bit poorly when applications are not loaded, there is data in the database, any you do queries on data where apps are not yet loaded. I remember this kind of case has been discussed before.

**Comment by dan31** [comment]
@k-rus, remind me if I'm wrong, I think I recall the discussion @per-samuelsson refers to. This is "by design" in 2.x, right? You have to have apps loaded in order to access their metadata data.

**Comment by per-samuelsson** [comment]
Check this mega-thread out: #2439. Think that tells the story pretty much.

**Comment by per-samuelsson** [comment]
> This is "by design" in 2.x, right? You have to have apps loaded in order to access their metadata data.

Yeah, exactly. See the post I referred to.

**Comment by miyconst** [comment]
Well, this is a very big limitation then. 

Basically it means, that applications can't create any db classes inherited from `Simplified` because this will break all other applications if the original one is not started.

**Comment by k-rus** [comment]
I confirm that SQL processor in 2.x is tightly bound to .NET host environment, thus applications must be loaded, i.e., classes are loaded and runtime metadata populated, to allow SQL processor work on them.

**Comment by dan31** [comment]
Our users would benefit if we explain the limitation and the proposed workflow for 2.x, having the limitation in mind. However, I don't see the best way right now to do the explanation, so I rely on discussing that with you @k-rus.

**Comment by dan31** [comment]
CC @alemoi This relates to how shared data models are to be used in 2.x.

**Comment by k-rus** [comment]
> Well, this is a very big limitation then.
> 
> Basically it means, that applications can't create any db classes inherited from Simplified because this will break all other applications if the original one is not started.

I confirm that queries cannot retrieve objects for a general class if they are of the class, which was not loaded.
I guess the query processor should cast objects to general type when asked. This is not so obvious in 2.x. It will be much simpler in 3.x, I guess, due to hierarchical set specifiers.

I believe the following query also fails in 2.x:
```c#
Db.SQL<Simplified.Ring1.Something>("SELECT s FROM Simplified.Ring1.Something s");
```

**Comment by alemoi** [comment]
> CC @alemoi This relates to how shared data models are to be used in 2.x.

Yes, an example where shared DLL has to be used.

**Comment by miyconst** [comment]
Closing this issue, as this behavior is due to current design/implementation/limitation.

**Comment by dan31** [comment]
@miyconst, I bet we don't have any article regarding this behaviour yet (I believe this should be together with explaining Shared DLLs)? At least I haven't found one. The only mention so far is http://starcounter.io/guides/sql/sql-isolation/. If so, I'd create a ticket to write one.

**Comment by miyconst** [comment]
Yes, looks like we don't have any article about this design/limitation.
