### ISSUE TITLE
Binding JSON-by-example to property in codebehind

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2964]
The current solution to bind a property in JSON-by-example to a property in the codebehind requires that the properties have different names. 

```javascript
{
    "Version": "",
    "$Version": { "Bind": "CodeBehindVersion" }
}
```

```
class MyCodeBehind : Json {
     public string MyCodeBehindVersion {
          get {
              return this.Data.Version.ToString();
          }
          set {
               this.Data.Version = Version.Parse(value);
          }
     }
}
```

The reason for this is that for each property in JSON-by-example an property is added to the generated code that gets and sets the value. This could be simplified and enhanced so that if a property in codebehind exists with the same name, no property in the generated code will be added and the codebehind-property should be used directly.  

Then the extra binding-path is no longer needed and I think the code easier to understand.

**Comment by warpech** [comment]
+1

**Comment by jakubklekota** [comment]
:+1:

**Comment by per-samuelsson** [comment]
> [...] and I think the code easier to understand

Most definitely. :+1:

**Comment by per-samuelsson** [comment]
I'm doing another round of Typed JSON testing and reviewing, trying to get a clearer picture of what is most urgent to fix, and what is lacking in the documentation.

We should do some rating/voting, since there are quite a few issues now in this area, and when we do that, I really think this one deserves a high prio.

If we adress this, we can write an article / guide promoting the pattern I propose [here](https://github.com/Starcounter/Starcounter/issues/3105#issuecomment-162450065). Plus that we can better explain how binding works in the [JSON Data Binding](http://starcounter.io/guides/json/json-data-binding/) guide.

In that guide, we state as a fact

> Properties declared in JSON (the view-model) can be bound to either **a property in the code-behind** file or a CLR object that exposes one or more public properties. Properties that are bound will read and write the values directly to the underlying object with no need to manually transfer the values to the view-model.

and 

> By default each property will try to bind to a property **in code-behind** or a data object. If the binding fail, for example a property with the same name does not exist or no data object is specified, the property will be treated as unbound.

With the syntax described by @chrhol in the OP, this is not really *false*. But its not really straightforward, as I think users might expect, considering how easy it is to do the same if you bind to a POCO.

**Comment by chrhol** [comment]
Just a note on this one: it probably requires us to rewrite the parser for code-behind that currently uses some half internal, half public api from the Mono.CSharp library. This parser collects information that is needed when generating code.

One problem with the current implementation is that the mono-parser is very primitive. Basically you only get low-level tokens. For example when we today finds out methods that are used for validation (`void Handle(Input input)`) we assume that we have one if the first token is 'Void` and the other `Identifier`. 

Now that Roslyn is available, it can be rewritten properly.

Other then that this issue gets a vote from me, maybe even with more urgency to get rid of Mono :+1:

**Comment by per-samuelsson** [comment]
> Now that Roslyn is available, it can be rewritten properly. [...] Other then that this issue gets a vote from me, maybe even with more urgency to get rid of Mono :+1:

But thats not something we do in a day, right? I guess its at least a week or two to get everything written, tested and up and running again, if we make that switch?

I agree it should be done. But I'm not sure where it would fit into the roadmap.

An alternative would be to keep the suggested pattern in the OP, and just be really clear to describe it in all places where we discuss binding of properties to the code-behind. And then we support the desired new pattern in a future major, where we switch to Roslyn and move TypedJSON out to its own repo.

**Comment by chrhol** [comment]
The Roslyn-parser is in place, and is working fine. I will start to implement this feature now.

A couple of things before I start:
- Using this pattern will mean that the Json-property will be a bit more cumbersome to access on the serverside. This shouldn't matter for primitive values, since they will be the same (a string in json will be the same string in the code-behind property), but it will be a bit different for objects and arrays. 
For example in the example below, calling `foo.Bar` inside the codehost will return the result from the code-behind property, *not* the `Bar` jsonobject. To get the jsonobject, you either have to use the template or use the name (`foo.GetValue(foo.Template.Bar)`, `foo["Bar"]`)
- The code-behind property will be treated as a bound property (so we don't really *replace* the json-property), to be able to use the same internal logic for caching, dirtychecking and serializing.

**Foo.json**
```javascript
{
    "Bar": { "Name": "" }
}
```

```csharp
partial class Foo : Json {
    // Automatically bound and used for jsonproperty "Bar"
    public FooBarData Bar { get { return Db.SQL("SELECT f FROM FooBarData").First; } }
}
```

**Comment by chrhol** [comment]
I took some time to refactor and adding some code-comments to the codegenerator, since it's kind of difficult to get in to, when you forgotten how it works, and a lot of bad names for fields and methods were used.

Anyways, when implementing the changes in the codegenerator it occurred to me that there is one more restriction to this pattern, and that is a property that is declared in a base-class. Since we lack the complete typeinformation in this version, we cannot get any information about already existing properties from inherited classes, which means that this will only work for locally declared properties. Of course this is the same limitation as. for example, when it comes to inheritance, that we cannot check that you inherit from a correct baseclass (i.e. some class that is or inerits themselves from `Json`).

I cannot see that this should be a showstopper, but it should be documented as a known limitation when updating the bindind-document.

**Comment by chrhol** [comment]
This now done and pushed to develop and pnext. I also added a short section in the databinding document on starcounter.io (http://starcounter.io/guides/json/json-data-binding/#binding-to-a-property-in-code-behind)
