### ISSUE TITLE
Default constructor for Starcounter.Session

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2966]
Right now we do not use any kind of Session except `SessionOptions.PatchVersioning`.

I think this should be default value when session created, so instead of:

``` cs
Session.Current = new Session(SessionOptions.PatchVersioning);
```

We just write:

``` cs
Session.Current = new Session();
```

Moreover, I think that Session should be created automatically if there is no session yet.

In asp.net session is created automatically, but it can be disabled via configuration file if needed.

cc @alemoi, @warpech.

**Comment by warpech** [comment]
+1

**Comment by warpech** [comment]
This will be beneficial for reducing the amount of boilerplate (Barcodes2).

**Comment by alemoi** [comment]
I tried to modify the default constructor for session to use `SessionOptions.PatchVersioning` but the unit tests started to fail regarding the Json patch: https://scbuildserver/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=32564#_focus=4216

I will re-assign to @chrhol since he is more knowledgeable in this area.

**Comment by chrhol** [comment]
I will do this change for 2.4 to avoid breaking anything.

**Comment by chrhol** [comment]
This is now done.

I also took the opportunity (when we already have breaking changes in XSON) to change the `SessionOptions` enum to a more suitable name. `SessionOptions` is obsoleted in favour of `Session.Flags` and methods using it refactored.

**Comment by miyconst** [comment]
@chrhol could you please also provide some code snippets with examples of how to use the new Session?

@Mackiovello could you please document it?

**Comment by warpech** [comment]
Thanks @miyconst for catching this. Such work is not done until it is documented.

**Comment by chrhol** [comment]
Right, I totally missed documentation. Sorry about that. However I can find no existing documentation about this. 

In the current docs patch versioning is not mentioned at all (unless I missed it)

**Comment by Mackiovello** [comment]
The only documentation about sessions is [here](https://docs.starcounter.io/guides/puppet-web-apps/sessions.html). 

There is nothing about patchversioning in the docs. 

Is is correct that the changes from previous session behavior are these?

1. `Session.Current = new Session(SessionOptions.PatchVersioning);` is now `Session.Current = new Session();`

2. `SessionOptions` is now `Session.Flags`

Is there anything more?

**Comment by chrhol** [comment]
Yes, that's correct.

> Is there anything more?

One old thing, that I'm not sure when it was changed (by me, so I missed another thing to document...), `UseSessionCookie` that is also mentioned on this page is obsoleted and replaced with `UseSessionHeader` (and optionally `SessionHeaderName` if enabled).

**Comment by chrhol** [comment]
I can't find the corresponding issue for that other change I mentioned, I will look some more.

**Comment by warpech** [comment]
@chrhol https://github.com/Starcounter/Starcounter/issues/3798. It is mentioned in CHANGELOG.md

**Comment by chrhol** [comment]
I have (finally) updated the relevant sections with my missing changes. Will close this for real now! 😸
