### ISSUE TITLE
Replace AddFilterToMiddleware with AddRequestFilter

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2969]
This is of low priority.

In Handle class, there a method called [`AddRequestFilter`](https://github.com/Starcounter/Starcounter/blob/ffdeadd3bfc4d8b0440cb150ea16bd415a31daba/src/Starcounter.Internal/Handle.cs)

[Git blame](https://github.com/Starcounter/Starcounter/blame/ffdeadd3bfc4d8b0440cb150ea16bd415a31daba/src/Starcounter.Internal/Handle.cs) shows that it was created as an alternative name for `AddFilterToMiddleware`, but it was never announced.

I think that `AddRequestFilter` is a much better name than `AddFilterToMiddleware`. 

All the docs should be updated to suggest using  `AddRequestFilter` (with mention that it was previously called `AddFilterToMiddleware`. 

All the sample apps should be updated to use `AddRequestFilter`. Code instances can be found with an advanced GH search: https://github.com/search?q=user%3Astarcounter+user%3Astarcountersamples+AddFilterToMiddleware&type=Code&utf8=%E2%9C%93

Let's not break compatibility, but announce `AddFilterToMiddleware` deprecated and mark in the code that it should be removed in some major release in future.

**Comment by alemoi** [comment]
Glad you noticed it. I created this new one exactly because of reasons above (+after I added the response filter now that people are using) ! And will gladly do the work to replace it!

**Comment by alemoi** [comment]
The replacement is pushed via 8719a2e49d01ad5250f228185d60bacbe23dbad6
I added Obsolete attribute to AddFilterToMiddleware and SkipMiddlewareFilters, which produces a warning when building a project containing it. Documentation is updated and the scripts in https://github.com/StarcounterSamples/Tools/issues/5
WIll be available in following nightly.

**Comment by warpech** [comment]
Note to future searchers: `SkipMiddlewareFilters` is now called `SkipRequestFilters`
