### ISSUE TITLE
Thoughts on Handle.X methods

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2970]
Right now we have set of `Handle.X` method for REST handlers, such as `Handle.GET`, `Handle.POST`.

Once a REST handler was attached it can't be detached unless application stopped. This is a limitation. In my CMS application I would like to add/remove pages/handlers dynamically.

Also we have the following methods in `Handle` class:

```cs
public static void AddFilterToMiddleware(Func<Request, Response> filter);
public static void AddRequestFilter(Func<Request, Response> filter);
public static void AddResponseFilter(Func<Request, Response, Response> filter);
```

- Same as for REST handlers, there is no way to remove filter.
- What is the difference between `AddFilterToMiddleware` and `AddResponseFilter`.
- `AddFilterToMiddleware` depends on application start order, and my lead to unpredictable behavior when two or more applications want to process same request with a filter.

In c# delegates with any return type except `void` can't have reference to more then one method. In our case `AddFilterToMiddleware` has to return response or null if not applicable. This always rise a question "What happen if two or more filters return a response?".

In some cases, like authenticating session, I want to be sure, that my filter will be executed first, and all of other filters and handlers will receive already authorized session. There is no way to achieve such functionality right now.

**Comment by miyconst** [comment]
Related issue: https://github.com/Starcounter/Starcounter/issues/2969

**Comment by miyconst** [comment]
cc @alemoi, @warpech

**Comment by warpech** [comment]
@miyconst Can you write what are the consequences of this?

If I understand correctly:

- a user is not able to remove a page in CMS UI without restarting the server
- SignIn will not work as intended if it is started after Launcher

Please write if there is anything else or I got it wrong

**Comment by miyconst** [comment]
I have reworked CMS app, so it does not create dynamic handlers, instead it has only one `/content/{?}` handler which does all the things.

So only second item left.

**Comment by alemoi** [comment]
Thanks for asking!

> What is the difference between AddFilterToMiddleware and AddResponseFilter.
Probably you mean `AddRequestFilter`? Then no difference, the first will be gone in future.

> In my CMS application I would like to add/remove pages/handlers dynamically.
Initially I added support for this. However, no one used it so far. If you need this functionality I will go through and expose/test it.

> Same as for REST handlers, there is no way to remove filter.
Legit. Will add removal of filters. Initially it was on purpose made very primitively, so that applications can not interfere between their filters.

> This always rise a question "What happen if two or more filters return a response?".
As described in documentation: Each filter in the list is executed one by one, until some filter returns a non-null Response.  (http://starcounter.io/guides/network/middleware-filters/)

> In some cases, like authenticating session, I want to be sure, that my filter will be executed first, and all of other filters and handlers will receive already authorized session. There is no way to achieve such functionality right now.

Just curious what will happen if two applications would want to put their filters are first. In any case, I will have to expand the API to allow adding filters to front.

**Comment by miyconst** [comment]
I don't have a good solution for filter execution order. In asp.net I used for long time we have to specify kind of filters in `web.config`, which is an xml document and the order of xml nodes specifies the order of execution.

In our cases applications add those filters on their own, and we can't guarantee that one application will start before/after another one.

So, my suggestion is to add `priority` property to the filters. We will guarantee that filters with higher priority will be executed before filters with lower priority, but can't guarantee that filters with same priority will be executed in some particular order.

**Comment by alemoi** [comment]
> In my CMS application I would like to add/remove pages/handlers dynamically.

Unregistering existing HTTP handlers is added now: `Handle.UnregisterHttpHandler`.

**Comment by alemoi** [comment]
@per-samuelsson did some redesign of middleware filters so I don't think this issue still applies. @warpech please reopen if something.
