### ISSUE TITLE
Where are my static web files?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2971]
Hi!

I've upgraded to:

> Starcounter-Stable-2.1.177 (14 okt 2015 17:28:43)

And I no longer see the root folder of my application as a source for public web folders. Only the default ones are showing:

> c:\program files\starcounter\clientfiles\staticfiles   8181
> c:\program files\starcounter\scadmin   8181

Do I need to supply any new arguments when launching through the debugger?

**Comment by alemoi** [comment]
Thanks for the question! I guess you are refering to Administrator that does not show the folders. The folders are actually registered, they are just not displayed in Adminstrator. There is an issue for that, i will link here.

**Comment by careri** [comment]
OK, but my site isn't working. Maybe it's because of the Polymer changes?
I only get a blank screen

**Comment by warpech** [comment]
Do you see any errors in Chrome Dev Tools console?

Did you follow the template upgrade instructions on http://starcounter.io/nightly-changes/starcounter-2-1-now-compatible-with-polymer-1-1/ ?

Let me know if you need any help with the upgrade.

**Comment by alemoi** [comment]
I was referring to this issue: https://github.com/Starcounter/Starcounter/issues/2817

**Comment by careri** [comment]
I'll try refactoring to Polymer 1.1, that seems to be the problem

**Comment by careri** [comment]
Hmm, got most of the page working again.

But all my bindings had to be prefix by model. e.g.
>{{Name}} -> {{model.Name}}

Your example doesn't prefix InvoiceNo with model:
http://starcounter.io/tutorials/1-introduction-to-part-1/1-5-render-json-in-html/


But I just can't get my Polymer element to work:
><had-upload header="New SoftwareSet" relativeUrl="/upload" fileExt="hsm" uploadedInfo="{{model.NewSetUploaded$}}"></had-upload>

Properties defined in the dom-module:
>Polymer({
      is:"had-upload",
      properties: {
          uploadedInfo: { type: String, notify:true },
          relativeUrl: { type: String, notify:true },
          fileExt: { type: String, notify:true },
          header: { type: String, notify:true } 
        },

header property works for some reason, the other three are undefined. Any ideas?

**Comment by warpech** [comment]
> Your example doesn't prefix InvoiceNo with model:
http://starcounter.io/tutorials/1-introduction-to-part-1/1-5-render-json-in-html/

Thanks for noticing! we tried to update all of the examples but apparently we missed that. I will fix it.

> header property works for some reason, the other three are undefined. Any ideas?

Maybe some lower/uppercase problem? See https://www.polymer-project.org/1.0/docs/migration.html#property-name-to-attribute-name-mapping 

Have you tried using the miration tool that Polymer provides? http://polymerlabs.github.io/polyup/

**Comment by warpech** [comment]
@careri was the problem solved?

**Comment by dan31** [comment]
Archived.
