### ISSUE TITLE
`staradmin new db` does not work

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2973]
According to `staradmin help new`, the following syntax is supported:

```
Creates various types of objects, e.g. databases or applications.

Usage: staradmin new <type|template>
Types:
  app    Create a new application (based on a template)
  db     Create a new database

Examples:
  staradmin new app           Creates a new application from the default
                              template, normally named '+'.

  staradmin new mytemplate    Creates a new application from 'mytemplate'
                              template.

  staradmin new app + foo     Creates a new application from '+' template,
                              naming it 'foo'


Running 'staradmin fubar' is the shorthand of 'staradmin new app fubar';
it creates a new application based on the 'fubar' template. If the template
does not exist, the staradmin usage message is displayed.
```

Trying to create a database using `staradmin new db marcin` gives me an error message:

> Don't know how to create new 'marcin'.

I wanted to add a description to the page http://starcounter.io/guides/tools/staradmin/, but I will skip it until it is implemented. 

I suggest removing the information about `db` from `staradmin help new` or fixing this.

**Comment by per-samuelsson** [comment]
> Don't know how to create new 'marcin'.

There can be only one, thats why! :wink: 

I'm implementing #2950 as part of work I do next week. Let's get this one done while we're at it. The other one basically depend on this functionality.

**Comment by per-samuelsson** [comment]
Done. Merged/pushed as part of https://github.com/Starcounter/Starcounter/commit/1c928c6d7c7bba03d81946ab5cd862042d5fa08d, and documented at [staradmin CLI | New command](http://starcounter.io/guides/tools/staradmin/#new-command).
