### ISSUE TITLE
`staradmin delete log` does not work

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2974]
According to `staradmin help delete`, the following syntax is supported:

```
Deletes various types of objects, e.g. databases or logs.

Usage: staradmin delete [--force] <type>
Types:
  db     Deletes a database
  log    Deletes the server log
```

Trying to create a database using `staradmin --database=default delete log` gives me an error message:

> The method or operation is not implemented.

I wanted to add a description to the page http://starcounter.io/guides/tools/staradmin/, but I will skip it until it is implemented. 

I suggest removing the information about `log` from `staradmin help delete` or fixing this.

**Comment by per-samuelsson** [comment]
Maybe we should consider removing this from the help, rather than implement it? It's not very hard to implement I guess, but it's also something we probably don't want users to do easily (because then we can't ask them for logs when they're in trouble. WDYT, @warpech?

**Comment by warpech** [comment]
No problem, as long as there still is a way to delete the log. I guess this can be done by just deleting the file?

**Comment by per-samuelsson** [comment]
> I guess this can be done by just deleting the file?

Exactly (minus its more than one file). Just deleting everything under the `%serverrootfolder%\Logs` folder will do it.

**Comment by per-samuelsson** [comment]
So, I'll remove it from the command line help, along with all the other stuff I'm planning to do. And you'll remove it from the docs, @warpech. Thanks for the feedback.

**Comment by per-samuelsson** [comment]
This one is done, merged/pushed as part of https://github.com/Starcounter/Starcounter/commit/1c928c6d7c7bba03d81946ab5cd862042d5fa08d.

I alsso have updated the [staradmin CLI | Delete command] (http://starcounter.io/guides/tools/staradmin/#delete-command) documentation, and the help output is now:

```
staradmin help delete

Deletes various types of objects, e.g. databases.

Usage: staradmin delete [--force] [--failMissing] <type>
Types:
  db    Deletes a database

```
