### ISSUE TITLE
ResourceDir changes Application.Current.WorkingDirectory;

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2976]
Maybe I misunderstood the switch for setting the resourcedir.
If I start my program from cmd folder:
>D:\source\Scdb2Apps\HeadsAdmin\BootApp\bin\Debug

Command:
>star.exe --resourcedir=WebApp HAD.exe /a

At the entry point for my application the WorkingDirectory of my Application is:
>D:\source\Scdb2Apps\HeadsAdmin\BootApp\bin\Debug\WebApp

That certainly wasn't my intention! I just wanted my static files hosted from the WebApp folder, not the WorkingDirectory of my application modified.

**Comment by alemoi** [comment]
Thanks for the question! @per-samuelsson do you remember if there were some initial reasons for this behavior?

**Comment by per-samuelsson** [comment]
Hi @careri 

I just think this was not reviewed enough. I agree the experience sound strange. I'll look into it, probably within a few days, and get back to you on that. Hope you can work around it? Maybe pass %cd% as one of your application level arguments, and use that inside your bootstrapper?

**Comment by careri** [comment]
Yepp, no worries. I'll get by for now.
Den 21 okt. 2015 4:51 em skrev "Per Samuelsson" <notifications@github.com>:

**Comment by careri** [comment]
Any progress?

**Comment by per-samuelsson** [comment]
> Any progress?

I've just waited for you to ask that, hating the fact that I still havent had any time to look at this. Sorry. :cry: 

I really want to work with these general improvements, but right now I stuck on things we must deliver, so I constantly have to re-prio. I can just assure you its still on my list, I haven't forgot about it. I'll try find some time to look at it eventually, but I'm just not sure when.

**Comment by per-samuelsson** [comment]
Done. Merged and documented as part of #3099.
