### ISSUE TITLE
pnext: Built-in basic system tables.

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#2979]
Same as built-in in 2.x + tokens.

Token table is required for proceeding with replicator.

Synchronize token table constants for key and setspec column names between system tables and database create (now stored in database configuration file).

**Comment by k-rus** [comment]
Will the system tables replicate data stored in meta-tables?

**Comment by eriohl** [comment]
The idea is to have it compatible with the kernel maintained system tables in develop now. But details is not yet worked out.

**Comment by eriohl** [comment]
I'm hoping that the only built-in table we need will be the token table. For now I will use a hardcoded token table and just try to get things working with this (we'll see how this goes...).

Once I gotten the hello world working (or discovered that the hello world won't work without work on meta-tables) I intend to start looking into this.

Would be great if we could use the new metadata tables obviously. Seems a bit redundant otherwise. Let's discuss this when we've gotten a bit further with this project.

**Comment by k-rus** [comment]
Basic meta-tables are created on database start by calling metalayer from pnext. However, I haven't verified property yet.

**Comment by eriohl** [comment]
Using the new metadata tables instead.
