### ISSUE TITLE
Routed console output is broken?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2982]
Doing

````
mkdir Foo
cd Foo
staradmin +
```

gets me **app.cs**:

```C#

using Starcounter;
using System;

class Program {
    static void Main() {
        Console.WriteLine("{0} starting...", Application.Current);
        // [...]
    }
}

```

then

```
star app.cs
app -> default (started, default port 8080, admin 8181)
```

Nothing more.

Similarily, `staradmin console` seems broken too.

Anyone else experience this? @alemoi, @andwah, this caused by some change in web sockets, etc?

**Comment by alemoi** [comment]
No changes in WebSockets I would say, for a long time at least. Probably something with console processing, that @andwah knows more about.

**Comment by andwah** [comment]
i can confirm that it do not work as expected.. i will take a look

**Comment by dan31** [comment]
Something quite recent. A month ago I was doing some routed console outputs and haven't noticed such.
How would it be possible to test? Maybe through acceptance test @alemoi @andwah?

**Comment by andwah** [comment]
A long time ago we decided to only show console outputs per app (before we had one console output window on the database page). during that work something broke, i found the problem and pushed the fix d27215f2f7aca5ff261823e045a8c6e39b9aebef

**Comment by per-samuelsson** [comment]
> i found the problem and pushed the fix d27215f

```
star app.cs
app -> default (started, default port 8080, admin 8181)
Starcounter.Application starting...
```

Works like a charm now, and I've tested `staradmin console` too, and that works equally well! :clap: :fireworks:

**Comment by per-samuelsson** [comment]
When @andwah fixed this, now its only #2446 left for this to work like it once did. 

I think #2446 was caused by @alemoi moving the application class some time, from `Starcounter` to `Starcounter.Internal` or something like that. Thats when it was broken at least. I can assign it to me to try to figure out what broke it though.

**Comment by dan31** [comment]
I think it is reasonable to grasp @per-samuelsson. Maybe cover with some more tests as well (some changes like that, with good intentions, might happen to be brutal in result).

**Comment by per-samuelsson** [comment]
@dan31, I think #2446 is probably simple to figure out and fix, so lets just do it. This one @andwah fixed was a lot more serios IMO, so I'm glad its now fixed. It seem to work fine.
