### ISSUE TITLE
Where there are two Metadata.Type for System.String type?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2989]
```sql
SELECT * 
FROM Starcounter.Metadata.Type
WHERE Name LIKE '%string%'
```

![image](https://cloud.githubusercontent.com/assets/6435556/10666171/4106a8bc-78d0-11e5-91e0-ea1b8feac654.png)

**Comment by dan31** [comment]
CC @k-rus

**Comment by per-samuelsson** [comment]
I've been confused by the metadata model too a couple of times, and I'm not 100% in this case either. But i *think* that `Type` is a base class for some more specialized ones, where one probably is like `PrimitiveType` and maybe the other is `MapPrimitive` or something like that.

I'm quite sure at least that `Type` is a really general one, and there are several specializations. One of them is `Table` if I remeber correctly.

Making queries on metadata kind of always make me have to think once, a second time and then a third time of what the heck it is one get back. It's rather complex IMO.

**Comment by miyconst** [comment]
`Starcounter.Metadata.Type` is the table referenced by `Starcounter.Metadata.Column` to indicate data type of the columns. At least I was told so by @alemoi.

In c# `System.String` & `string` are same types, same as `System.Int32` & `int`, so there should be only one record in `Starcounter.Metadata.Type` table.

**Comment by per-samuelsson** [comment]
> In c# System.String & string are same types, same as System.Int32 & int, so there should be only one record in Starcounter.Metadata.Type table.

Well, like @dan31 suggest, its probably best to let @k-rus give the true answer. But maybe its so that one record (of e.g. "primtive type" type) is `System.String` and another might be the C# `string` keyword? And both are types.

**Comment by k-rus** [comment]
`Type` is general class and it contains descriptions of data types for different host environments (currently only .NET) and for stored schema. To interpret above query knowing class/type of the objects is important. `string` belongs to `DbPrimitiveType`, i.e., primitive data type supported by kernel, and `String` belongs to MappedType, i.e., CLR type `String`, which is then mapped in `string`.

It is true that meta-schema is not intuitive. It is not really oriented to users. The main purpose is internal use. The public meta-schema will be defined through Views, which will select from the meta-tables. However, Views are not yet supported.

I hope I answered all questions. Let me know if I need to clarify anything.

**Comment by per-samuelsson** [comment]
> string belongs to DbPrimitiveType, i.e., primitive data type supported by kernel, and String belongs to MappedType, i.e., CLR type String, which is then mapped in string.

Wow, then my guess:

> But maybe its so that one record (of e.g. "primtive type" type) is System.String and another might be the C# string keyword? 

was pretty spot on then. :crown: 

> I hope I answered all questions.

Thanks.

**Comment by miyconst** [comment]
From the c# developer point of view this is very confusing, as `System.String` and `string` are absolutely equal. This is why I asked.

Okay, the long story short: it is not a bug, but some kind of requirement for kernel, which should not be visible for end user.

@k-rus, thank you for the clarification, and please, close the issue if I understood you correctly.

**Comment by dan31** [comment]
Just to add. Today me and @k-rus discussed documenting Metadata for our users. User-friendly docs basically, since metadata is used in a numerous of scenarios (maintaining indices is one of them). This is pushed into @k-rus backlog. This point on ```string```, I believe, should be explained there as well.

**Comment by k-rus** [comment]
Created documentation issue #3001. Closing this one.
