### ISSUE TITLE
Review server/service terminology

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2992]
Again, I know!

But since I'm now working on the new directives from last week, and a few of the issues I'm working on touches on this, I just thought I'd bring it up once. The most notable issues are #2950, #2973 and #2423.
### Background

Basics: to run Starcounter applications inside Starcounter databases / VMDBMSs / hosts, a few **supporting processes** must be running. These processes are typically started in batch by a process we currently call **scservice.exe**. Collectively, we refer to these processes as the Starcounter **server**.

Normally, this **server** is started on demand. It can run either in the same Windows session as the user, or in Session 0, as a Windows **service**. In the former case, it's most commonly started the first time the user start an application, either doing `star myapp.exe` or via Starcounter Application project + F5.

Currently, if I start the `scservice.exe` parent process on my machine (and **not** running it as a Windows service), I get the following process tree:

![image](https://cloud.githubusercontent.com/assets/2902045/10725511/dfa2973e-7bcc-11e5-9fb7-fc710d2448b6.png)

The two major ones here are `scnetworkgateway.exe` and `scadminserver.exe`. The former is, well, the gateway, and the later is the server that **expose all adminstrative functionality** as a REST API. Using this API, `star.exe`, `staradmin.exe` and the web administrator can start, stop, list databases, etc. All database/codehost specific process management is govered by this server, driven by said API.
### Whats in it for the user

As a Starcounter user/developer, I can't really do anything unless these processes are running. I can't run databases, the functionality in `staradmin` is very limited, and the web adminstrator can't even show the title/index page.
### What should we call it

Today, we mostly refer to this set of processes as **the server**. With #2950, we are implementing a command to explicitly start `scservice.exe`, and we need a name for it. Should it be `staradmin start server`? I've seen the tray icon use `Start server` too.

Why I want to bring it up a last (hopefully) time is b/c I think its still not really perfect, simple because, well **a)** users tend to think as **their applications** as the server (and they are right, o/c) and **b)** as we see, its not really a server we are talking about here, it's more of a "system".

I know historically, we've had issues reported where users claimed they have "started Starcounter" and it has taken some time to figure out exactly what they mean by that. And it has turned out to mean different things. So we are not perfectly clear in our lingo here obviously.

Any fresh take on this? I'd really like to see some input from the app team guys on this!

**Comment by per-samuelsson** [comment]
After thinking some more on this, I'm leaning towards keeping the "server" term. And describe it / think of it as a compound, virtual server, enabling databases to consume its services (i.e. via the gateway and with the maintenance services of the admin server).

If there is no feedback, I guess no one feel strongly in any other direction, so I think I'll go with that.

**Comment by warpech** [comment]
On the other hand, I lean towards the term "service". 

Admittedly, in stacks like LAMP, Apache and MySQL processes are called *servers*. On Windows, you run a [MySQL *server* as a service](https://dev.mysql.com/doc/refman/5.1/en/windows-start-service.html).

But our architecture is unlike LAMP. As @per-samuelsson puts it:

> a) users tend to think as their applications as the server (and they are right, o/c) and b) as we see, its not really a server we are talking about here, it's more of a "system".

:+1: this. 

Starting `staradmin start server` doesn't serve anything by itself, except for Administrator. For the actual data, my apps are the servers. I would go with `staradmin start service`, aliased as `staradmin start`.

The word "server" should be freed to the userland, so people can call it for whatever they like in their architecture. Starcounter being a "service" for their apps is a more humble term.

**Comment by warpech** [comment]
But then again, my proposal makes sense only if we replace all the usage of the word "server" mentioned in https://github.com/Starcounter/Starcounter/issues/2423 with "service". And that seems like too much work for a little benefit.

Calling this a "server" is way less of an effort, so I will not have any regrets if you do it.

**Comment by k-rus** [comment]
> But then again, my proposal makes sense only if we replace all the usage of the word "server" mentioned in #2423 with "service".

service has special meaning in Windows. So we cannot use word service in this case.

**Comment by per-samuelsson** [comment]
> service has special meaning in Windows.

Right.

> So we cannot use word service in this case.

Wrong. :smile: 

With the same reasoning, we couldn't call it server either, because there are other servers. And Windows server is an OS. Or apps can't be apps, because thats what they're called in your IPhone.

WTBS, and considering everything @warpech wrote, I still think we should call it server. I **think**. I do agree fully on your reasoning @warpech, but I'm still hesitating... Lets think another day. :thought_balloon:

**Comment by per-samuelsson** [comment]
> WTBS, and considering everything @warpech wrote, I still think we should call it server. I **think**. I do agree fully on your reasoning @warpech, but I'm still hesitating... Lets think another day. :thought_balloon:

We kind of decided to stick to "server", mainly b/c of the work involved changing to "service". Closing this for now.
