### ISSUE TITLE
Develop daily broken

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2994]
```
[17:18:18][Step 1/1] Cloning Simplified repository.
[17:18:18][Step 1/1] Cloning into 'Simplified'...
[17:18:19][Step 1/1] Building Simplified.
[17:18:19][Step 1/1] Microsoft (R) Build Engine version 4.0.30319.18408
[17:18:19][Step 1/1] [Microsoft .NET Framework, version 4.0.30319.18444]
[17:18:19][Step 1/1] Copyright (C) Microsoft Corporation. All rights reserved.
[17:18:19][Step 1/1] 
[17:18:19][Step 1/1] CSC : error CS2001: Source file 'Ring2\ContactPerson.cs' could not be found [C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-271\Simplified\Simplified.csproj]
[17:18:20][Step 1/1] Exiting build with error code 1!
```

**Comment by per-samuelsson** [comment]
Now that Simplified are a required part of Starcounter, we need to be as careful there as we are in Starcounter repo. This means every push **must go through a personal build** with the latest Starcounter bits.

Right now, I'm in a situation where I can't push/merge the stuff I have ready, because my personal builds fail b/c of the failure in Simplified.

Should we add some config so that building Simplified can be turned off at least?

**Comment by miyconst** [comment]
@per-samuelsson sorry for this issue.

I fixed a bug and a wrong file name in Simplified, but forgot about `csproj` file, which still was referencing the old file.

This is fixed now.

**Comment by chrhol** [comment]
And now there is some other problem with the buildserver :) I think it's out of harddrive space.

**Comment by miyconst** [comment]
Is there anything I can help with?

**Comment by chrhol** [comment]
I'm talking with @alemoi.

**Comment by per-samuelsson** [comment]
> @per-samuelsson sorry for this issue.

Sure, no problem. It has happened all of us at some point. My comments where more general than that, trying to suggest a way to get away from these things in the future, something we all can commit to follow. My best bet is (as I always suggest) that everybody striktly adhere to the branching model and never push one like of anything until a personal build has succeeded.

> This is fixed now.

:+1: 

> And now there is some other problem with the buildserver

Yeah, its been like that all morning. Hanging/failing with different combinations of problems. :cry: I have like 10 failed personal builds if you need something to diagnose.

**Comment by miyconst** [comment]
@per-samuelsson 

>My best bet is (as I always suggest) that everybody striktly adhere to the branching model and never push one like of anything until a personal build has succeeded.

This would really complicate the workflow, at least for me.

I remember, some time ago I was receiving notifications from the build server, if a build fails, so I was aware when some of my changes broke the build. Those notifications were really useful, no longer see them though.

**Comment by k-rus** [comment]
> @per-samuelsson
> 
> My best bet is (as I always suggest) that everybody striktly adhere to the branching model and never push one like of anything until a personal build has succeeded.
> This would really complicate the workflow, at least for me.

I agree with @per-samuelsson. Failing public builds might be show stopper for others. Our current model in Starcounter is that any commit/push to a main branch in any repo, which affects the product, should first be executed on personal branch on build server and then if the build succeed to push it into the main branch.
I understand that it compacts workflow, but otherwise it complicates life for others and delays their work. We want to automate this procedure, but we didn't have opportunity to do it.

**Comment by miyconst** [comment]
>any repo, which affects the product

Do StarcounterSamples (previously Polyjuice) applications included in this? There are some test which may file during build, but the applications themselves do not affect Starcounter build.

If you are talking about Starcounter/Starcounter and StarcounterSamples/Simplified repo, then I agree.

**Comment by alemoi** [comment]
Yes, right now we test apps as part of daily build, and i want to keep it this way. @miyconst i can help you and show current development workflow with Teamcity.

**Comment by miyconst** [comment]
I would really appreciate your help. Let's do it when I back to Stockholm.
