### ISSUE TITLE
Buildserver down due to out of space.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2996]
There is no space on harddrive for scbuildserver. It needs to be cleaned up. We're working on this now, but the buildsystem will not be available for a while.

**Comment by chrhol** [comment]
I uninstalled some old studios and did some minor disk cleanup, the buildserver is up and running again.

I will remove the showstopper label but keep the issue open so @alemoi  can remove some additional items.

**Comment by alemoi** [comment]
I cleaned up the artifacts in TeamCity. Now there is 250Gb free on scbuildserver and around 130Gb free on scbuildserver2.
