### ISSUE TITLE
Question: How to recover Lost Data

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3007]
I launched my database with some new handlers, and all of my data is gone. Now how can I recover the data?

**Comment by dan31** [comment]
Hi @atifsheikh! What do you mean by gone? What are other changes to the code you made, and what is the current state of image files?

**Comment by atifsheikh** [comment]
I cant see any records in the DB. i have one table in the DB with 2 columns in it. and i have added only one handler in the code. thats the only change I did.

The image files 
![imagefiles](https://cloud.githubusercontent.com/assets/4388707/10826291/556e4320-7e69-11e5-9b46-d34cebe7d449.jpg)

**Comment by eriohl** [comment]
Hi @atifsheikh. I must say I find your statement seriously disconcerting. Would it be possible for you to compress your transaction log (default.0000000000.log and default.0000000001.log) and make it available to us so we can investigate?

**Comment by atifsheikh** [comment]
Here is the link to both files. 
https://drive.google.com/folderview?id=0B3OphiyFByHRM3RVQ01PRmZ0Zzg&usp=sharing

**Comment by atifsheikh** [comment]
I am certain that there is some fault at my end, but i'm just looking a way to recover the data.

**Comment by eriohl** [comment]
Thank you for the files.

Nothing odd about the transaction log I can see however. There are 18371 transactions in there and 28620 record in the database after database has been created.

Also looked for schema upgrades or something like that that might have messed up your data and I can see nothing like that near the end of the log other them some new tables created right at the end.

So nothing odd at this level.

This table that you mentioned with 2 columns (I'm guessing this is the table the data is missing from). Do you have the name for this table (or the name of the class representing this table)?

**Comment by eriohl** [comment]
H

**Comment by per-samuelsson** [comment]
@atifsheikh 

Sorry to hear you experience difficulties like this. We are currently busy in a joint effort trying to catch cases like this, where the product somehow behave in a confusing way or misbehave, causing disturbances.

The table you mention, I guess its created by you defining a C# database class? If so, any chance you might have *renamed* that class. Thats the sort of thing that could cause this behavior. You **never risk loosing** your data, but it can no longer be accessed by the new name, unless you make it available again by renaming it back.

And remember - you don't neccessarily have to change the name of the **class**, just **changing/renaming namespace** will have the same effect (we map classes to tables by their full name).

**Comment by per-samuelsson** [comment]
If this turns out to be a case where the class/namespace was renamed, here are some relevant issues from previous refactoring experiences: #2845, #1764, #1766, #2122, #2116.

**Comment by atifsheikh** [comment]
@eriohl The table name is "WebSites" and and the column in it is URL. 
@per-samuelsson you are right, i created this table in C# Database Class. and i have not modified anything in this class, not the names or the letter or the namespace. I have only added 1 new handler in the solution. the solution is very simple and small, it have only 3 tables. and my target table (which is "WebSites") have no changes.

But lets say we cant recover the data in database, is there any way to access that data in log files? or as @eriohl mentioned that he can see 28620 record in the database. is there any way to access those records manually?

**Comment by eriohl** [comment]
Right a the end of the log there is a new table created "ReconnaissanceProject.Database.WebSites". There is also a previously created table called "ReconnaissanceProject.WebSites". Could it not be the case that you've in fact changed the namespace of the class like @per-samuelsson suggests? If so then if you restore the class "ReconnaissanceProject.WebSites" then you should again be able to access your data.

**Comment by per-samuelsson** [comment]
@atifsheikh 

> But lets say we cant recover the data in database, is there any way to access that data in log files? or as @eriohl mentioned that he can see 28620 record in the database. is there any way to access those records manually?

I'm very sure there is no data lost here, even though it might look like that on the surface. We've basically not experienced data loss in any installation in ... well, 10 years.

If that stint should break today, here and now, yes, we can of course help you bring the data back with some low-level manipulation. So don't worry.

> Right a the end of the log there is a new table created "ReconnaissanceProject.Database.WebSites". There is also a previously created table called "ReconnaissanceProject.WebSites". Could it not be the case that you've in fact changed the namespace of the class like @per-samuelsson suggests?

This finding from @eriohl is very likely the case you are experiencing this.

**Comment by eriohl** [comment]
There seems to be 12922 records in the table ReconnaissanceProject.WebSites and 3 in the table ReconnaissanceProject.Database.WebSites.

**Comment by per-samuelsson** [comment]
> [...] and i have not modified anything in this class, not the names or the letter or the namespace.

Hmm, and the log clearly tells a different story (see above, indicating the **namespace** of the Websites class has in fact changed).

If you haven't done so on purpose, can it be that Visual Studio somehow confuse us here? I know it has some little tricks (that I dont particularly like) here and there, and one of them is that sometimes **when you move files** around in the solution (like moving a file into a different folder), **it can try reflecting this in the namespace too** (just as when you rename a .cs file, it ask you to also rename the class). Have you made any structural changes to the project that could have accidentally caused this? Like moving `ReconnaissanceProject.WebSites` into a `Database` folder?

**Comment by atifsheikh** [comment]
:+1: Awesome. Thank you very much guys, and sorry for my blunder :P
Thank you again for the quick responses :)

**Comment by per-samuelsson** [comment]
> +1: Awesome. Thank you very much guys, and sorry for my blunder :P

I take that as some of the above helped solving your case, so that you now can see your data again. Thats good. 

Your "blunder" is on us, not you. Sorry for the disturbance.

As I wrote earlier, Starcounter is still sometimes a little rough in the edges in the user experience (the intial company lifetime focus has been on the core functionality, i.e. the database engine itself). We are trying to address any such issues as we speak, aiming to eliminate any disturbances or things that confuse people and/or are not intuitive. It will take some time, but we'll get there eventually for sure.

Meanwhile, we really do appreciate any kind of feedback, from end to end (i.e. documentation -> most lower core API), so if you find the time and have something you want us to improve, just get back to us and we'll do our best!

**Comment by atifsheikh** [comment]
@per-samuelsson well thats very nice of you, and sure, i always create issue tickets on this form when ever i get in to trouble. So Thank you very much for this encouragement. I really appreciate it. :)

**Comment by dan31** [comment]
@k-rus, I assign to you so far. Maybe you would create a separate issue. I couldn't find another issue on that topic of documenting. Basically we want to explain in that part of docs: a) what happens when user is changing its classes definitions, b) that data is never lost, c) how to observe all your data you have using metadata info (#3001).
