### ISSUE TITLE
Support transient classes

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3010]
Relates to, but is not a *requirement* for, #3003.

Implement the long-time story summarized [here](https://github.com/Starcounter/Starcounter/issues/2216#issuecomment-51774708) by @dan31:

> Me and @andwah suggested last Friday that excluding classes from persistent namespaces is a common scenario, I think you share the same idea. Is it possible to introduce this behavior when first version is in place and running?

**Comment by per-samuelsson** [comment]
Done, merged and pushed in feature set of #3003 enablers, in https://github.com/Starcounter/Starcounter/commit/7feda6c312233a08dcdc1d1a1dc3c59e6c62f990.

**Comment by dan31** [comment]
Great way how you evolve the story, @per-samuelsson! In the meantime, do you intend to put some docs regarding this feature on .io website? How transient classes are configured?

**Comment by per-samuelsson** [comment]
> In the meantime, do you intend to put some docs regarding this feature on .io website? How transient classes are configured?

Most definitely: https://github.com/Starcounter/Starcounter/issues/3003#issuecomment-153859381. :smile:
