### ISSUE TITLE
Starcounter 1.X, Starcounter.Transaction.State

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3012]
Hi!

This queston regards old SCDB.
What is the field State on Starcounter.Transaction used for? Is it free for use? Or does it have an internal purpose?

I was thinking of caching some data there to speed things up.

@chrhol indicates that @eriohl might have some input?

**Comment by eriohl** [comment]
"User defined attachment." according to documentation. Not used internally. Basically it is to provide a means for application code to attach data to the transaction. Could be used for something in VisualObjects or something however. @chrhol?

**Comment by careri** [comment]
Thanks

**Comment by chrhol** [comment]
I don't remember this property at all, and have not found any use of it in old code for presentations or visualobjects, so it seems to be fine to use.
