### ISSUE TITLE
C# editor web component?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3014]
Any good one out there? What I'm after is one that is easy to use and that provide basic syntax highlighting (and where the source code being edited is accessible of course).

What stuff do we use for syntax highlighting in the web admin SQL tab?

@warpech @tomalec @miyconst @andwah

**Comment by miyconst** [comment]
Ace Editor is the best choice.

Here is a demo for all supported modes:
https://ace.c9.io/build/kitchen-sink.html

Here is the WebComponent wrapper around the editor:
https://github.com/Juicy/juicy-ace-editor

**Comment by per-samuelsson** [comment]
> Ace Editor is the best choice.

Wow, thanks @miyconst, that one looks super. I have these two ideas where an editor like this could come in handy. I'll brief them to you guys after I've done some more progress on #3003, to see what you think.

**Comment by miyconst** [comment]
Sounds intriguing :smile:

**Comment by andwah** [comment]
You may also take a look at OmniSharp http://www.omnisharp.net/ if you want more integration such intelligence etc.. It's a supplement for the editor you choose.

**Comment by per-samuelsson** [comment]
> You may also take a look at OmniSharp http://www.omnisharp.net/ if you want more integration such intelligence.

Yeah, thanks @andwah, I looked at that b/c its whats used behind VS Code in the new DNX / AspNet 5 context, but for this particular case, I think syntax highlighting is enough to start with.

I want to discuss one of these ideas with you next week, btw. I think we can do quite cool new things pretty soon, and parts of it relates to the web admin. I'll get in touch. :sunglasses:

**Comment by tomalec** [comment]
If it's still an issue, you can naturally try our HTML custom element
http://juicy.github.io/juicy-ace-editor/
http://juicy.github.io/juicy-ace-editor/kitchen-sink.html
which would be probably waay easier to integrate with our blog.

**Comment by dan31** [comment]
Guys, I archive this one if you don't mind (when @per-samuelsson will find a moment to go back to his great blogpost writing he will restore it from the closed issues).
