### ISSUE TITLE
Write docs on mapping

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3019]
Starting from here: http://starcounter.io/guides/apps/

**Comment by dan31** [comment]
Entalis #2743.

**Comment by alemoi** [comment]
Forgot to mention that initial version of documentation is published.

**Comment by per-samuelsson** [comment]
> Forgot to mention that initial version of documentation is published.

Great. I'll read it today / weekend, and will give feedback if I have any!

**Comment by warpech** [comment]
Just a friendly note, please don't use newline unless you mean to start a new paragraph. And if you mean to start a new paragraph then make two newlines. MarkDown needs this to understand a new paragraph.

Compare the [Database mapping](http://starcounter.io/guides/apps/database-mapping/) page with http://elixir-lang.org/getting-started/mix-otp/agent.html - see how they use a lot of short, clearly distinct paragraphs.
