### ISSUE TITLE
Document implicit transaction

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#302]
There is no description of implicit transaction on [our wiki](https://github.com/Starcounter/Starcounter/wiki/More-on-Transactions).

**Comment by k-rus** [comment]
@chrhol recently updated the wiki page about transactions. However it seems that the implicit read transaction is still not covered.

**Comment by dan31** [comment]
This is now explained on http://starcounter.io/guides/transactions/running-background-jobs/ - a little weird place, but let's consider it as done.
