### ISSUE TITLE
Improve SQL INSERT

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3020]
It would be really useful if `INSERT` statement would return inserted object. Something like this:

``` cs
var product = Db.SQL<Product>("INSERT INTO Product (Name) VALUES (N'Starcounter database')");
```

Or

``` cs
Db.SQL("INSERT INTO Product (Name) VALUES (N'Starcounter database')");
var product = Db.GetLastInsertedObject() as Product;
```

cc @k-rus, @per-samuelsson

**Comment by per-samuelsson** [comment]
> var product = Db.SQL<Product>("INSERT INTO Product (Name) VALUES (N'Starcounter database')");

Just out of curiosity, when would one do that, when `new Product() { Name = "Starcounter database" }` is available.

As for the question, I wouldn't know. Sorry. Maybe @k-rus has a take on it.

**Comment by per-samuelsson** [comment]
> Just out of curiosity, when would one do that, when new Product() { Name = "Starcounter database" } is available?

Hmm, I guess when you have the type only available as a string, correct? :smile: 

FWIW, there are (other) ways to create instances from type name strings already, just don't know how well they are exposed and/or documented.

**Comment by miyconst** [comment]
I am working on import/export tool. The tool does not have reference to the class, only meta data for loaded clr classes. When importing data back to database I need id of the object or the object itself to make references later.

**Comment by k-rus** [comment]
You can use reflection to create objects. It will do the job.

**Comment by k-rus** [comment]
I don't see how to implement desired functionality through general interface of SQL in a clean way. I think a specialised host oriented API will be needed and will be also cleaner.

**Comment by miyconst** [comment]
It looks like both `INSERT` and `UPDATE` are not officially supported and both do not accept parameters. So, using `INSERT` in my case would not work, Reflection is the way to go. Closing the issue.

**Comment by bigwad** [comment]
Actually, there is no need to use reflection, 
If I correctly understand what you need, then given table name, you may do the following:

```
object create_object_in_table( string table_name )
{
  //find out table definition base on table name
  var table_def = Db.LookupTable(table_name);

  //insert object into the table
  ulong oid, address;
  DbState.Insert(table_def.TableId, ref oid, ref address);

  //create reference to the object
  return Starcounter.DbHelper.FromID(oid);
}
```

**Comment by miyconst** [comment]
What is `DbState.Insert`? Is it a public api? Why there is no docs about it? How and when should I use it?

**Comment by bigwad** [comment]
DbDstate is a class inside Starcounter.Internal namespace. It's public in sense that it's accessible to user code, though I don't know about docs.
I'm not sure about what do you mean in your last question. This method creates the record in the table and does it in the right way, so the record is bindable to database class. You may use it appropriate to your needs.

**Comment by miyconst** [comment]
We never promote this method for object creating. Why it is so? And what potential risk it has?

Making a row in the database without filling up the columns is pretty much useless, as I still have to use Reflection to fill up the values.

**Comment by bigwad** [comment]
>Why it is so?

It's really low-level. Perhaps, that's the answer, but I don't know for sure.

> And what potential risk it has?

As it's low level, obviously, the risk is the possible breaking changes in implementation. Proper tests should be in place.

>I still have to use Reflection to fill up the values.

There are a bunch of helper methods that may help you to fill values. You may take a look at [LogApplicator](https://github.com/Starcounter/Starcounter/blob/pnext/src/Server/Starcounter.TransactionLog/LogApplicator.cs) class in pnext for inspiration or to apply this class directly for your needs.

**Comment by miyconst** [comment]
Thank you, I will take a look at `LogApplicator`. Could you please cc guys, who might know more about public usage of `DbDstate` class?

**Comment by bigwad** [comment]
> Could you please cc guys, who might know more about public usage of DbDstate class?

@per-samuelsson ?

**Comment by miyconst** [comment]
@per-samuelsson are there any documentation for `DbState` class?

**Comment by per-samuelsson** [comment]
> @per-samuelsson are there any documentation for DbState class?

No, just like a lot of classes are not properly documented. But this class is not intended for public use, its public only because we had to for some historical reason.

@bigwad 

Sorry I haven't replied earlier. I just get random notifications from GitHub, its been like that for long unfortunatelly, and I try to keep up as good as I can, but from time to time I miss a post. Sorry. I think I've answered what you cc:ed me about?

**Comment by miyconst** [comment]
>No, just like a lot of classes are not properly documented. But this class is not intended for public use, its public only because we had to for some historical reason.

Okay, then I should not use this class in an open source and free Starcounter sample application, am I right?

**Comment by miyconst** [comment]
Archiving the issue.

**Comment by dan31** [comment]
> Okay, then I should not use this class in an open source and free Starcounter sample application, am I right?

@miyconst thanks for archiving :) yes you are correct, whenever we see a need for functionality - we should address it altogether and see what is the proper way (implement using existing public features, or add feature), but not to fall back to internal APIs.
