### ISSUE TITLE
More efficient resource management for small installations

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3030]
For the purpose of making it less costly to run a lot of instances with smaller databases.

**Comment by eriohl** [comment]
I've done some work on to allow a larger number of (and thus individually smaller) storage memory segments as re-implemented support for releasing segments to shrinking storage memory in **pnext** (this will not work optimally however lacking storage memory defragmentation).

But lacking scenarios to work from I can't do much more. So killing project for now.

**Comment by dan31** [comment]
@eriohl I think when things you prioritise on pnext track get done, we need to go back to this one. We receive questions from potential customers on how to provide cost-efficient multi-tenancy (for scenarios where multiple customers are run on a single machine on its own database each). Basically, as a production instance you don't want to have 256 Mb default memory layout if your customers only run perhaps 50 Mb of data in total. Usually there might be several big customers (100-s of Mb and Gb DBs) and a plethora of small customers (10-s of Mb DBs) Hence, one size doesn't fit all and it is desirable to make it configurable. How exactly - is a question to discuss.
