### ISSUE TITLE
Simplified data model

### ISSUE THREAD

**Issue by jakubklekota** [Starcounter/Starcounter#3031]
Hi guys,
Can you help me described  simplified data model ?
What is Ring1, Ring2, Ring3, Ring4, Ring5, Ring6 and for example where put new database class if i can create common for app ?

Maybe good idea is creating tutorial ?

**Comment by miyconst** [comment]
I can give you basic ideas referring to @warpech:

Ring1 - something that even a monkey could understand.
...
Ring6 - something that only specific range of people could understand.

So, you should think of how many people could understand your entity/class and then decide to which Ring add the class.

In the Simplified data model we do not add custom namespaces, but do add custom folders. 

For example if you are going to add some specific classes for online payments into Ring5, then it might be in `/Simplified/Ring5/Payments` folder, but in `Simplified.Ring5` namespace.

Be sure to inherit your classes from correct class, all of the classes should be inherit from `Something`, implicitly or explicitly.

Tutorial is definitely a good idea.

**Comment by per-samuelsson** [comment]
@jakubklekota 

This stuff is still pretty much onging work, but I'm sure there are some help you can get. And yes, we should most definitely document this more throughly eventually.

@warpech @miyconst ?

**Comment by Starcounter-Jack** [comment]
I will post a tutorial

**Comment by warpech** [comment]
> I will post a tutorial

That will be very welcome!

A similar explanation to this given by @miyconst is available in https://github.com/StarcounterSamples/Simplified/blob/master/README.md

**Comment by warpech** [comment]
Rings are explained in https://github.com/StarcounterPrefabs/Simplified/blob/master/README.md#rings, so I consider this done.
