### ISSUE TITLE
Unable to execute DELETE statement with WHERE clause

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3034]
In administrator this query fails with syntax error exception:

```sql
DELETE
FROM Simplified.Ring3.SystemUser
WHERE Name = 'test'
```

```
Failed to process query: DELETE FROM Simplified.Ring3.SystemUser WHERE Name = 'test': Incorrect syntax. View the log for more details.
```

The log does not contain any info about this error.

This query passes through without exceptions:

```sql
DELETE
FROM Simplified.Ring3.SystemUser
```

cc @andwah, @k-rus

**Comment by per-samuelsson** [comment]
@miyconst 

You've tried the same in the SQL programming API? Still a flaw in administrator of course, just curious if it would work out there.

**Comment by andwah** [comment]
According the the documentation at http://starcounter.io/guides/sql/limitations/ 
>There are three data manipulation statements in SQL92: ```INSERT```, ```UPDATE``` and ```DELETE```. None of these statements are supported in Starcounter SQL


But maybe ```DELETE``` is partly supported? anyone knows?

**Comment by per-samuelsson** [comment]
> But maybe `DELETE` is partly supported? anyone knows?

In `SlowSQL` it is, if I remember correctly. Because the implementation is somewhat naive. Maybe @k-rus can fill in some blanks.

**Comment by miyconst** [comment]
@per-samuelsson, I tried to execute same query, but with a parameter, not with inline value.

**Comment by andwah** [comment]
I think i found the problem. it's about the newline's

Try to write the query in a single line (without newlines).

```DELETE FROM Simplified.Ring3.SystemUser WHERE Name = 'test'```

**Comment by miyconst** [comment]
Yes, inline version work without error.

**Comment by per-samuelsson** [comment]
> I think i found the problem. it's about the newline's

Great you found it, @andwah. Is it simple to fix? IMO, doing SQL statements like @miyconst does in the OP is really useful when statements get a little more complex, so I think it would be good to support.

**Comment by andwah** [comment]
@per-samuelsson It sounds simple to fix what do you think @k-rus ?

**Comment by k-rus** [comment]
`DELETE` is parsed in managed code. It is necessary to check how the managed parser behaves in the above case to see how to fix it.

**Comment by k-rus** [comment]
> DELETE is parsed in managed code. It is necessary to check how the managed parser behaves in the above case to see how to fix it.

Seems to be similar problem with insert into, see [this comment](https://github.com/Starcounter/starcounter.io/issues/117#issuecomment-172562030)

**Comment by miyconst** [comment]
@andwah please fix this. Should be easy.

**Comment by andwah** [comment]
@miyconst Never worked with the parser,   `SELECT ` statement seems to work with newline chars, but not `DELETE`. see @k-rus post above.

**Comment by miyconst** [comment]
Can't we just replace `\r\n` with ` `?

**Comment by andwah** [comment]
@miyconst well it's in the parser. and i do not know how it works.

the lazy and incorrect way should to fix the input string argument to SlowSQL(...). but i recommend it to be fixed where its goes wrong. then it will work even with C# calls to SlowSQL(...)

**Comment by miyconst** [comment]
This issue might get never fixed on the parser level, as we decided to move to a new query processor quite long time ago. That is why I would propose to add this fix on top, means in the administrator itself.

**Comment by andwah** [comment]
> This issue might get never fixed on the parser level,

then we don't have a choice and need to do a workaround in administrator.

Then i will remove all newline from all queries that goes to the administrator REST api.

Anyone knows if that is safe todo? or should i replace it with a <space> ?

**Comment by miyconst** [comment]
You have to replace it with a space for sure.

**Comment by andwah** [comment]
pushed to develop 24d267d325b1ab1f5ddd24088ddecefdf47d5da5

**Comment by k-rus** [comment]
I revisited the source code (in Level1, not parser) and found place for a fix, which was done for `SELECT`. I believe it should work and the fix in admin is not needed any more.
