### ISSUE TITLE
Database - Not delete items in one-to-many relation

### ISSUE THREAD

**Issue by jakubklekota** [Starcounter/Starcounter#3035]
Hello,

I have database model:

```
[Database]
public class Bin
{
	public string BinName;
	public string Lat;
	public string Lon;

	public Bin()
	{
		public Rubbish()
		{
			new Rubbish()
			{
				Bin = this;
			}
		}
	}
}

[Database]
public class Rubbish
{
	public Bin Bin;
	public string RubbishType;
}
```

I observed when in starcounter administrator execute DELETE statments like:
```
DELETE FROM Bin
```
and then

```
SELECT * FROM Rubbish
```
record of Bin was deleted, but in Rubbish items stay. Only the reference/key to Bin was deleted in the Rubbish database .

It's correct for one-to-many relation ?

**Comment by miyconst** [comment]
Yes. Currently it is by design. You can use commit hooks to manually remove the Rubbish of your Bin.

**Comment by per-samuelsson** [comment]
@jakubklekota 

I think what you are looking for here is what is normally referred to as *cascading deletes*, and we in Starcounter, we don't support those of the shelf currently.

As @miyconst suggest, you have the option to use something called *commit hooks*, which basically allow you to register a delegate that is being called on certain transactional commits.

Another way for this specifc scenario is by implementing an interface `IEntity` which expose a single method `OnDelete()`. Try this:

```C#
[Database]
public class Bin : IEntity {
  public Bin() {
    new Rubbish() { Bin = this; }
  }

  void IEntity.OnDelete() {
    foreach (var r in Db.SQL<Rubbish>("SELECT r FROM Rubbish r WHERE r.Bin = ?", this)) {
      r.Delete();
    }
  }
}

[Database]
public class Rubbish {
    public Bin Bin;
}
```

**Comment by jakubklekota** [comment]
@miyconst @per-samuelsson thx :)
