### ISSUE TITLE
Simplification to OntologyMap method

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3036]
Right now we do `OntologyMap` like this:

```cs
UriMapping.OntologyMap("/procurement/partials/product/@w", typeof(Product).FullName, null, null);
```

And this looks much cleaner:

```cs
UriMapping.OntologyMap("/procurement/partials/product/@w", typeof(Product));
```

Just need to add another `OntologyMap` override:

```cs
public void OntologyMap(string url, Type type) {
    UriMapping.OntologyMap(url, Type.FullName, null, null);
}
```

--------------

Or even more simple:

```cs
UriMapping.OntologyMap<Product>("/procurement/partials/product/@w");
```

And the override:

```cs
static void OntologyMap<T>(string url) {
    UriMapping.OntologyMap(url, typeof(T).FullName, null, null);
}
```

cc @alemoi, @dan31

**Comment by per-samuelsson** [comment]
> UriMapping.OntologyMap<Product>("/procurement/partials/product/@w")

That seem most in line with would be the expected I think. I vote for that.

But could it be that we still need to support a string based version as well, for future scenarios where types can exist without a class?

**Comment by miyconst** [comment]
@per-samuelsson is there a typo in your code snippet? There is no generic type in your `OntologyMap` call and only one parameter, which is url. If no type, then how do we know to which class map?

Of course we have to keep support for the original mapping, this is just some overrides of the method.

**Comment by per-samuelsson** [comment]
> @per-samuelsson is there a typo in your code snippet?

Argh, its this thing with using quotes with code - if you hit [Edit comment] on my comment, you'll see it correctly, just that GH drop brackets in comments. :cry: 

> Of course we have to keep support for the original mapping, this is just some overrides of the method.

Good. Then I'm all for your suggestions.

**Comment by miyconst** [comment]
No missunderstanding then :smile:, I have updated your snippet.

**Comment by warpech** [comment]
Looks like a low hanging fruit :+1:

**Comment by alemoi** [comment]
Yes, this is very low hanging. I will fix it.

**Comment by alemoi** [comment]
Added improved ontology map API via 18d2122dbf0d9ea9498d4547e74a1c35d28456a2
Updated the Products app as example:
```
UriMapping.OntologyMap<Product>("/Products/partials/product/{?}");
UriMapping.OntologyMap<Organization>("/Products/partials/supplier/{?}");
```

**Comment by miyconst** [comment]
Cool! Thank you!

**Comment by warpech** [comment]
@alemoi it is a very good change but could you please also update the docs?

http://starcounter.io/guides/apps/ontology-mapping/
http://starcounter.io/guides/web/sharing-screen/

It should be explained that the new API is available since Starcounter `<relevant nightly version>`.

**Comment by alemoi** [comment]
Im sorry, totally forgot about that. Will fix it!

**Comment by alemoi** [comment]
Updated. Thank you for reporting!
