### ISSUE TITLE
Interface between managed Starcounter.SqlProcessor and scsqlprocessor.dll has been broken

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3037]
The problem is that interface function signature has been changed: ```scsql_process_query```. Appropriate fix in managed code is required. On top of that problem is masked in Debug configuration of Starcounter.SqlProcessor since Debug doesn't use scsqlprocessor due to some #ifdef.

I'm going to fix it, but I need to understand one thing. Are we going to process SELECT statements using scsqlprocessor or leave it as it was in 2.x? I guess later.
In this case I'm going to do following:
EDIT: done. 1. Change scsql_process_query to return error on SELECT statements as it was before
2. Adapt managed code for new signature. It shouldn't be difficult since we can ignore iterators for "INSERT" statement.
3. Implement INSERT INTO merely in scsqlprocessor, without any modifications in managed code.

@k-rus, @alexanderstc

**Comment by k-rus** [comment]
> On top of that problem is masked in Debug configuration of Starcounter.SqlProcessor since Debug doesn't use scsqlprocessor due to some #ifdef.

`#ifdef` was always there. I guess @eriohl added PROLOG_ONLY symbol to project configuration in Debug. So I add the task to fix calls to metalayer API in this case, see #3006. (there are also many other places where kernel non-existing functions are called)

**Comment by k-rus** [comment]
> 1. Change scsql_process_query to return error on SELECT statements as it was before

I am not agree with this. I would prefer that the managed code takes care, since it is problem of managed code, which does not have support for returned iterator.



> 3. Implement INSERT INTO merely in scsqlprocessor, without any modifications in managed code.

Reload must call scsql_process_modifyquery.

**Comment by eriohl** [comment]
Comfirming that PROLOG_ONLY was set on project level to get around it not working (not required for queries to run).

**Comment by bigwad** [comment]
@k-rus, what you suggest is effectively cease to support INSERT statement through Db.SQL.
  
Besides reload I'm aware of several places that issues "INSERT INTO" statement. 
1. InsertIntoTests in QueryProcessingTest project
2. [Starcounter.Extensions/Layouts.cs](https://github.com/Starcounter/Starcounter/blob/pnext/src/Starcounter.Extensions/Layouts.cs#L76)
May there're other in other projects. And maybe customers used to issue "INSERT INTO" through Db.SQL, so it's breaking change.

Whatever, I can concentrate on scsql_process_modifyquery and leave this decision to you.

**Comment by k-rus** [comment]
> May there're other in other projects. And maybe customers used to issue "INSERT INTO" through Db.SQL, so it's breaking change.

Why is it going to be breaking change? When pnext will be merged to develop public functionality including using Insert into from Db.SQL will be the same.



> Whatever, I can concentrate on scsql_process_modifyquery and leave this decision to you.

Great.

**Comment by k-rus** [comment]
> 1. Change scsql_process_query to return error on SELECT statements as it was before
> 2. Adapt managed code for new signature. It shouldn't be difficult since we can ignore iterators for "INSERT" statement.

Separate issue #3050

**Comment by alexanderstc** [comment]
scsql_process_query returs SCERRNOTSUPPORTED on SELECT statements.

**Comment by k-rus** [comment]
> scsql_process_query returs SCERRNOTSUPPORTED on SELECT statements.

Why? Some select statements are already processed and an iterator is generated. For other select statements the above error code returned is correct.

**Comment by k-rus** [comment]
> scsql_process_query returs SCERRNOTSUPPORTED on SELECT statements.
> Why? Some select statements are already processed and an iterator is generated. For other select statements the above error code returned is correct.

Created a separate issue for this in the Level0 repo.

**Comment by k-rus** [comment]
Fixed
