### ISSUE TITLE
Make SQL regression test to run in pnext

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3041]
This test might involve fixing different parts. A known part is support Binaries in meta-layer.
However, current problem is that starting test fails with:
> Starcounter.DbException: ScErrNoTransactionAttached (SCERR4003): Operation
must be performed in the context of a valid transaction

I haven't looked what the actual problem is. @eriohl what do you think?

**Comment by eriohl** [comment]
I can look at that specific error at least. I'll check it later today.

**Comment by eriohl** [comment]
I changed so that db_util::Transaction::Create sets the newly created transaction as current. This seemed to be the intention although not done (causing this particular error).

**Comment by eriohl** [comment]
Fixed a few issues and got it running. SqlTest2Input has 15 failures while SqlTest3Input and SqlTest4Input has none. SqlTest1Input has A LOT of failures however. I'll work a bit more on this tomorrow.

**Comment by eriohl** [comment]
Seems like the main reason why SqlTest1Input doesn't work is because DROP INDEX failed silently (this test is basically SqlTest2Input but expecting full scans because all the indexes are supposed to have been dropped).

It is not apparent to me why it fails. Error is ScErrTypeNotFound. Could I get some help investigating?

**Comment by k-rus** [comment]
> Seems like the main reason why SqlTest1Input doesn't work is because DROP INDEX failed silently (this test is basically SqlTest2Input but expecting full scans because all the indexes are supposed to have been dropped).

I fixed this problem and will push shortly.

> 
> It is not apparent to me why it fails. Error is ScErrTypeNotFound. Could I get some help investigating?

I found this problem today morning . @alexanderstc fixed it now in pnext.

**Comment by k-rus** [comment]
> It is not apparent to me why it fails. Error is ScErrTypeNotFound. Could I get some help investigating?
> I found this problem today morning . @alexanderstc fixed it now in pnext.

I tested the fix and it does not work properly.

**Comment by k-rus** [comment]
> It is not apparent to me why it fails. Error is ScErrTypeNotFound. Could I get some help investigating?
> I found this problem today morning . @alexanderstc fixed it now in pnext.
> I tested the fix and it does not work properly.

Now it works.

**Comment by eriohl** [comment]
Great. Thank you

**Comment by eriohl** [comment]
Now all the tests work except for some checking for errors. In these cases the error messages are wrong because it gets the error from the Prolog parser and not the new parser. This I guess will be addressed once the new parser is again working.

**Comment by k-rus** [comment]
> Now all the tests work except for some checking for errors. In these cases the error messages are wrong because it gets the error from the Prolog parser and not the new parser. This I guess will be addressed once the new parser is again working.

This is addressed. Now errors are related to:

1. Incorrect execution plan due to name of auto index was changed
2. Transaction locked on thread exception for create index

**Comment by k-rus** [comment]
> Transaction locked on thread exception for create index

@eriohl or @chrhol Can you look into this problem? Background: nowadays create and drop index creates own transactions and commits them, however it does not restore an old transaction.

**Comment by k-rus** [comment]
> Incorrect execution plan due to name of auto index was changed

This will be fixed when all other errors are fixed.

**Comment by eriohl** [comment]
> This is addressed. Now errors are related to:
>
> 1. Incorrect execution plan due to name of auto index was changed
> 2. Transaction locked on thread exception for create index

? I fixed these yesterday (other then the "wrong exception" these was the one remaining after drop index was fixed). Do you have the latest version?

**Comment by k-rus** [comment]
Sorry, I missed to pull and push. Will do it now.

**Comment by eriohl** [comment]
Or did you break these changes when fixing the "wrong exception" errors?

**Comment by k-rus** [comment]
No, I just missed to pull your changes. Now the test completely works. I will push to pnext now.

**Comment by k-rus** [comment]
Pushed. We have now one fully working regression test.

**Comment by eriohl** [comment]
(Actually the "transaction locked on thread" error is not wrong because all tests are executed within a transaction scope. The difference was that this was checked before the parsing was complete and so this error was prioritized over the parsing error. So all I did was to change the priority order of the errors. And corrected the error output, was a special error code when DDL failed because of this).
