### ISSUE TITLE
Test project for pnext converging to develop

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3043]
Current pnext test checks only native tests, which were designed for new track. Now it is connected to current code host implementation, but no tests are performed on this. One of the reason is that no regression test successfully runs in current state.
The problem is that it is not possible to see if working parts are working with changes.
It would be nice to have build server to auto-test the current state with tests to possible extend.

**Comment by k-rus** [comment]
After discussion with @alemoi we decided that pnext Windows project should be extended to build Level1 and run Level1 tests. Any objections or other ideas?

**Comment by dan31** [comment]
@alemoi, when can you take on this? I remember you've been onto general changes for the build system, do you want to incorporate them together with this issue?

**Comment by alemoi** [comment]
Yes, want to fix the new tests env first and this will come automatically!

**Comment by alemoi** [comment]
Yesterday I created a new build in TeamCity: New Pnext Daily Windows. Its basically based on current Develop Daily: does same steps, except how Level0 is built. It uses "pnext" branches for Level0, Level1 and Buildsystem repos. To add/enable tests - follow the new test framework regulations. Please let me know if you have any issues with the build.

**Comment by chrhol** [comment]
There is still some problem with the build. I will take a look at it since @alemoi is on vacation. I was going to do this on friday, but didn't have the time to fix it.

**Comment by chrhol** [comment]
The failing thing in the build is this custom target in `Starcounter.csproj`:

```
<Target Name="BeforeBuild">
    <CallTarget Targets="GenerateMetaClasses" />
</Target>
```

which fails with:

> C:\BuildAgent\work\sc-2.0.1000\Level1\src\Starcounter\Starcounter.csproj(477,5): error MSB3073: The command "C:\BuildAgent\work\sc-2.0.1000\Level1\bin\Release\GenerateMetadataClasses.exe C:\BuildAgent\work\sc-2.0.1000\Level1\bin\Release\metaschema.json C:\BuildAgent\work\sc-2.0.1000\Level1\src\Starcounter\Metadata" exited with code 9009.

I think I need some help from @per-samuelsson (as he seems to be the one who added this) to understand what this does and how we can make it work on the buildserver.

**Comment by per-samuelsson** [comment]
> error MSB3073

Are we sure the error is because the `GenerateMetadataClasses.exe` does not exist (like you told me off-tracker)?

**Comment by per-samuelsson** [comment]
Its a bit weird, because this [has in fact worked](https://github.com/Starcounter/Starcounter/issues/3051#issuecomment-157757013), so I can't see what could have changed that caused it not to work any longer.

**Comment by chrhol** [comment]
> Its a bit weird, because this has in fact worked, so I can't see what could have changed that caused it not to work any longer.

It's never worked on the buildservers, since Level1 was not built there before for pnext (we found out). So maybe something on a completely clean build?

> Are we sure the error is because the GenerateMetadataClasses.exe does not exist (like you told me off-tracker)?

I assumed it was since I could not find `GenerateMetadataClasses.exe` in the output folder, and errorcode 9009 means that the tool was not found, but maybe something else is making the project not build correctly. 

I will investigate more, I just didnt understand what the tool did or which project used it.

**Comment by alemoi** [comment]
I just checked it and there is no GenerateMetadataClasses.exe in the build output directory.

**Comment by alemoi** [comment]
I looked more and it seems to be again a glitch with MsBuild not properly resolving the build order. Starcounter project even if it depends on GenerateMetadataClasses - its being built before the last one. Its the same story as with error codes project, as you remember.

**Comment by alemoi** [comment]
I think here is the case: http://stackoverflow.com/questions/3640179/visual-studio-and-msbuild-fire-beforebuild-differently-on-a-wix-project

**Comment by alemoi** [comment]
Testing the resolution now.

**Comment by per-samuelsson** [comment]
> Starcounter project even if it depends on GenerateMetadataClasses - its being built before the last one.

WTF? So if I specify a dependency from a standard C# library project, saying that it depends on another one, `msbuild` **dont** guarantee that the depedency is built first?! Are you sure? That sounds like a huge thing to me.

**Comment by alemoi** [comment]
> WTF? So if I specify a dependency from a standard C# library project, saying that it depends on another one, msbuild dont guarantee that the depedency is built first?! Are you sure? That sounds like a huge thing to me.

Yes, and its a difference if built from VS or using MsBuild, you can read here in the suggested answer: ttp://stackoverflow.com/questions/3640179/visual-studio-and-msbuild-fire-beforebuild-differently-on-a-wix-project

That's why it works locally but I guess never worked in automated mode (MsBuild).

**Comment by per-samuelsson** [comment]
> [...] you can read here in the suggested answer: 

And we are using WiX?

**Comment by alemoi** [comment]
> And we are using WiX?

No, but there is a general explanation of a problem there in the answer.

**Comment by per-samuelsson** [comment]
> No, but there is a general explanation of a problem there in the answer.

Ah, ok, yeah, now I saw. Thanks.

Wow. Thats inconsistency to me. Why would the ever want to design it like that... :cry: 

Lets just bring our setup into the light. Its this.

```xml
<Target Name="BeforeBuild">
    <CallTarget Targets="GenerateMetaClasses" />
  </Target>
  <Target Name="GenerateMetaClasses" Inputs="@(MetaSchema)" Outputs="@(MetaClasses)">
    <Message Text="Generating meta classes" />
    <Exec Command="$(TargetDir)GenerateMetadataClasses.exe @(MetaSchema) $(ProjectDir)Metadata" ContinueOnError="false" />
    <Message Text="@(MetaSchema) -&gt; @(MetaClasses)" Importance="high" />
  </Target>
```

Thats in `Starcounter` project. And `Starcounter` is setup to depend on `GenerateMetaClasses` project (that is a tool), to ensure the tool is built before the `Starcounter` project is.

And clearly, thats not sufficient.

What other options do I have to enforce this? Do I need one specific setup for `msbuild`, and one for VS then?

**Comment by per-samuelsson** [comment]
> What other options do I have to enforce this? Do I need one specific setup for msbuild, and one for VS then?

Maybe remove `BeforeBuild` and implement this pattern instead, @alemoi? WDYT about that?

```xml
<Target Name="GenerateMetaClasses" AfterTargets="AfterResolveReferences">
  // Do our stuff
</Target>
```

**Comment by alemoi** [comment]
I tried BeforeCompile and that didn't work well either. I even moved the build of "GenerateMetadataClasses" project outside Level1, but then it complains about not finding "metaschema.json" in Release folder, which I guess is copied from Level0?

**Comment by k-rus** [comment]
> "metaschema.json" in Release folder, which I guess is copied from Level0?

Correct. The json file is defined in Level0, used there for C++ code generation, and copied into Level0 output folder for input to Level1 to generate CLR classes.

**Comment by per-samuelsson** [comment]
> ...

@alemoi, could we try this:

```xml
<Target Name="GenerateMetaClasses" AfterTargets="AfterResolveReferences" Inputs="@(MetaSchema)" Outputs="@(MetaClasses)">
    <Message Text="Generating meta classes" />
    <Exec Command="$(TargetDir)GenerateMetadataClasses.exe @(MetaSchema) $(ProjectDir)Metadata" ContinueOnError="false" />
    <Message Text="@(MetaSchema) -&gt; @(MetaClasses)" Importance="high" />
  </Target>
```

Just exactly that in `Starcounter`, and have GenerateMetadataClasses remain as is. Replace both BeforeBuild and previous `<Target Name="GenerateMetaClasses" ...` and see if that works.

**Comment by alemoi** [comment]
Sure, I will try it.

**Comment by alemoi** [comment]
Let's see if that works, because as I wrote I already tried BeforeCompile and that didn't work well either.

**Comment by per-samuelsson** [comment]
> Let's see if that works,

Did you try?

**Comment by per-samuelsson** [comment]
Those crazy VS strategies always ... sigh. They claim that in this new version X, everything has changed, now VS just runs as on top of msbuild, working the same way. And then you still find stuff like this over and over. :smile:

**Comment by alemoi** [comment]
> Did you try?

Haha, the "AfterResolveReferences" seems working, but not the "BeforeCompile". So I just pushed it.

> Those crazy VS strategies always ... sigh. They claim that in this new version X, everything has changed, now VS just runs as on top of msbuild, working the same way. And then you still find stuff like this over and over. :smile:

Yes, just waste of time for us.

**Comment by per-samuelsson** [comment]
> So I just pushed it.

Great. Thanks a lot.

**Comment by chrhol** [comment]
> So I just pushed it.

awesome! :raised_hands:

**Comment by chrhol** [comment]
pnext is up and running and has almost all tests enabled and are running both Level1 and native tests, and the issue discussed here it solved since long ago so I will close this issue.
