### ISSUE TITLE
No connection to Prolog Server

### ISSUE THREAD

**Issue by jakubklekota** [Starcounter/Starcounter#3047]
Hi,
Somethimes i have error "No connection to Prolog Server", when I execute SELECT statments.

Looks like app started faster then database.

**Comment by k-rus** [comment]
Thank you for reporting. It was reported in #2824. Do you also experience it during debug?

**Comment by jakubklekota** [comment]
Yes.

**Comment by k-rus** [comment]
> Yes.

Thanks. I close this issue as duplicate in favour of #2824.
