### ISSUE TITLE
GenerateMetadataClassses does not generate new classes on metaschema.json change

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3051]
I changed `metaschema.json`, however building Level1 or rebuilding `GenerateMetadataClasses` does not generate new classes. The current work around is manually delete `GeneratedMetadataClasses.cs`.

**Comment by per-samuelsson** [comment]
It's probably something with the semantics of the **msbuild** `prebuild` event, like it doesn't run on all instances, etc. If so, the same thing should apply to error code generation I guess.

I'll take a look at it eventually.

**Comment by k-rus** [comment]
Code generation seems to work correctly. I've never experienced such problem with it.

**Comment by per-samuelsson** [comment]
> Code generation seems to work correctly. I've never experienced such problem with it.

You mean with error codes? Yeah, I've never experienced problems with that either. So something funny going on. I will investigate what.

**Comment by k-rus** [comment]
> Code generation seems to work correctly. I've never experienced such problem with it.
> You mean with error codes? Yeah, I've never experienced problems with that either. So something funny going on. I will investigate what.

Yes, I mean error codes. Sorry for confusion.

**Comment by per-samuelsson** [comment]
Done, merged and pushed in https://github.com/Starcounter/Starcounter/commit/5ea76f82d929391da0be13819660fcd249cd0956.

I also took the opportunity to redesign how metadata class generation integrate in the MsBuild flow, turning to a new approach assuring incremental builds. So now it should work as expected + not trigger any generation of the input schema and existing generated classes are up to date.

@k-rus, I'm closing this, but it would be good if you could sometime test it. If you find it still doesnt work, let me know.

**Comment by k-rus** [comment]
No, it does not work for me. I still have to manually delete generated file to be able to get new class definitions.

**Comment by per-samuelsson** [comment]
> No, it does not work for me. I still have to manually delete generated file to be able to get new class definitions.

Thats weird. I'll contact you to ask some follow-ups.

**Comment by per-samuelsson** [comment]
> No, it does not work for me. I still have to manually delete generated file to be able to get new class definitions.

@k-rus, now I've done further refinements in the project dependencies, to try to cover all cases. Basically, the Starcounter project now has dependencies not only to the generator tool, but also to the master `metaschema.json`. So every time `CopyLocalDependencies` decide that file is out of date, and copies it, the Starcounter project should rebuild.

Please try this and let me know if it solves your issues.

**Comment by k-rus** [comment]
Fix confirmed. Closed.
