### ISSUE TITLE
Fix native API in Level1

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3052]
Most public API from kernel and metalayer was changed. Some changes already reflected, but all the old API function are in place and there is still some source code used.
Some old kernel API functions should be replaced with new kernel API, but some should call metalayer.

**Comment by eriohl** [comment]
I removed declaration of all obsolete kernel interface functions.

**Comment by k-rus** [comment]
I removed obsolete declaration to sql processor. Closing.
