### ISSUE TITLE
Self hosting application

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3055]
Right now Starcounter is an application development platform, which hosts applications inside itself.

I have a theoretical question. Could it be possible to change things inside out?

I want to get only Database functionality of Starcounter and run it inside my application (.exe). The main purpose of this is to get a lightweight light speed database shipped with my console or windows application.

Here is a scenario I would like to see:

- Create windows desktop application.
- Reference Starcounter.dll
- Starcounter.dll exposes `[Database]` attribute and `Db` class with it's methods, such as `Scope`, `Transact`, `SQL`, `SlowSQL`, `FromObjectId` and so on.
- Start using Starcounter in my application.
- Starcounter creates database binary file next to .exe and loads it next time.

I don't need json, handlers, mergers and anything else related to application development, only Database functionality.

Is it anyhow possible?

@eriohl, @k-rus, @alemoi, @dan31, @chrhol

**Comment by dan31** [comment]
@per-samuelsson, isn't it precisely a subject of your new blogpost?

**Comment by per-samuelsson** [comment]
> @per-samuelsson, isn't it precisely a subject of your new blogpost?

Nah, not really. [That one](http://starcounter.io/uncategorized/transacted-apps/)'s about the simplest possible case for what we have enabled recently. What's requested here is a bigger architectural change.

@miyconst 

I totally understand that idea, and we've discussed similar things on and off over the years. But Starcounter is still rather much about hosting, and the VMDBMS in particular. There are several problems we'd have to solve with the suggested approach:

1. Apps in the same process.
2. Weaving - when would that happen?
3. Sharing of database memory across processes (else you would be limited to one client process / database).
4. All management and initialization stuff we do upfront (this could be done though).

With that being said, we can still support very simple database desktop-like applications. See the given blog post.

And also: in the upcoming DNX track, things are changing a bit and at least some of these changes relate to this. For example, the weaving could be solved there, for the setup you request, and we plan to support multiple hosts / database, which would also be an enabler of that.

My idea and initial efforts with the hosting when I've prototyped/researched in DNX, is that we should support custom hosts. And one could very well be the default host (its called the "generic host" in that stack). 

A funny, related side-note on that track is that the DNX initiative actually evolves **towards** "our" model, i.e. that there are no longer any applications that *are'nt* hosted. Even simplest the console application you fire up with the default template will run inside a host by default, and even if its possible to tweak it not to, it's a marginal, non-common case.

**Comment by miyconst** [comment]
@per-samuelsson thank you for the detailed answer. I cannot suggest anything as a developer, as I know too little about the internal Starcounter implementation. Everything I ask/say/suggest should be taken as customer's wish or something like this. 

About the points:

1. Right now apps going to Starcounter's process to access same memory. I want to make it inside out, bring Starcounter to apps process, so Starcounter can access app's memory.

2. As I understand, it should be done "on the fly" and before compiling the code. The VS extension should be able to do this thing. If no, then I am even willing to manually call some tool to weave my classes, just to make Starcounter work.

3. Be limited to one client and one database is completely fine.

4. I don't know what you are doing in there and how, so I can't really suggest anything.

Here are some references I took inspiration from:
http://eloquera.com/eloquera-db
http://www.iboxdb.com/
http://siaqodb.com/
http://brightstardb.com/
https://dbreeze.codeplex.com/

**Comment by miyconst** [comment]
Closing the issue as answered.
