### ISSUE TITLE
Sometimes download page shows error

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3056]
Sometimes I see this instead of download page:

![image](https://cloud.githubusercontent.com/assets/6435556/11122587/3101c0a4-895c-11e5-80eb-e66e4212db3e.png)

cc @alemoi, @andwah

**Comment by dan31** [comment]
Me too. After refresh it disappears.

**Comment by miyconst** [comment]
I have not seen this error for a while. Closing the issue.
