### ISSUE TITLE
downloads.starcounter.com should redirect to downloads.starcounter.com/download

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3057]
It is not clear why http://downloads.starcounter.com/ returns 404.

I think, it should either rewrite to http://downloads.starcounter.com/download or redirect, but not show an error.

cc @alemoi, @andwah

**Comment by warpech** [comment]
+1

--
Marcin Warpechowski
+48 603 607 801

**Comment by miyconst** [comment]
Bump.

**Comment by miyconst** [comment]
This hit me again, can we finally fix it?

**Comment by dan31** [comment]
@andwah, check please. Probably minutes to fix.

**Comment by andwah** [comment]
@dan31 Minutes to fix, hours to install/test :-),

**Comment by miyconst** [comment]
@andwah can we do that?

**Comment by andwah** [comment]
@miyconst  It's up do @dan31 to prioritise this.

**Comment by warpech** [comment]
Was really minutes, just needed to add this to `scnetworkgateway.xml`:

```
<UriAliases>
    <UriAlias>
        <HttpMethod>GET</HttpMethod>
        <FromUri>/</FromUri>
        <ToUri>/download</ToUri>
        <Port>80</Port>
    </UriAlias>
</UriAliases>
```

It is explained here https://starcounter.io/guides/network/aliases-and-redirects/

**Comment by miyconst** [comment]
Finally it is fixed! Thank you @warpech.

**Comment by dan31** [comment]
> @miyconst It's up do @dan31 to prioritise this.
> Was really minutes, just needed to add this to scnetworkgateway.xml:

I adore @warpech -s way of prioritisation 👍
