### ISSUE TITLE
Calls to DDLs should return more meaningful error on transaction locked on thread

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3059]
Now execution of DDL creates own transactions, thus applications should call them, e.g., create or drop index, outside transaction scope. If DDLs are called inside an explicit transaction transaction locked on thread error is returned, which is not very informative to the user. The error message can be easily improved in the case of DDLs.

**Comment by k-rus** [comment]
Another error for the same problem is `ScErrNoTransactionAttached`.

**Comment by eriohl** [comment]
Currently generates the error SCERRCANTEXECUTEDDLTRANSACTLOCKED together with the type of DDL operation that failed. Think it rather specific personally.

**Comment by eriohl** [comment]
> Another error for the same problem is ScErrNoTransactionAttached.

This error should generally not occur because of the implicit transaction.

**Comment by k-rus** [comment]
Seems not to be an issue. Errors are not fired. Closing.
