### ISSUE TITLE
VS-2015 runtime fails to install on certain clean Windows Server 2012 R2 instances

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#3067]
For an unknown reason, VS-2015 fails to be installed on a clean installation of Windows Server 2012 R2 Standard. Quite lots of people experience similar problem: https://social.msdn.microsoft.com/Forums/vstudio/en-US/64baed8c-b00c-40d5-b19a-99b26a11516e/visual-c-redistributable-for-visual-studio-2015-rc-fails-on-windows-server-2012. A potential solution lies in bundling specific Windows Updates packages alongside with installer.

**Comment by dan31** [comment]
After experimenting, I found that fixing this is worth installing several Gigabytes of Microsoft updates. This KB https://support.microsoft.com/en-us/kb/2999226 is a prerequisite for vs-2015 redist. Which in itself depends on https://support.microsoft.com/en-us/kb/2919355. This is a 700 Mb update. When it is installed – kb2999226 is installed fine alongside with vs-2015 redist installation (it downloads this kb), and vs-2015 installs fine as well. However, kb2919355 fails to install on its own, meaning it needs some other dependencies. So I simply let Windows (clean Windows 2012 R2 Standard) install all autoupdates. After 50 of autoupdates, kb2919355 turn has arrived, it is installed and vs-2015 is installed fine just after that. So, in return, being able to install vs-2015 depends on 53 Windows KBs to be installed.

So the only viable way I can see is to go back to redistributing runtime with Starcounter. And, since we are using dlls, no way to get by with static linking to runtime.

**Comment by dan31** [comment]
Note this is only an issue on machines without recent updates. This isn't likely an issue on Amazon and Azure, but most likely an issue on Hetzner and my issue on GleSYS.

**Comment by alokgrimm** [comment]
Visual Studio 2015 C++ Redistributable requires Windows Server 2012 R2 with Update (KB2919335).
KB2919335 will not install without KB2919442 already being installed.
However, at the present time, KB2919442 is not provided automatically via Windows Update to Windows Server 2012 R2.
The actual fix is:
Manually Download and install KB2919442.
https://www.microsoft.com/en-sg/download/details.aspx?id=42153

Run windows update, which will download and install KB2919355 or Alternatively manually download and install KB2919355.
https://www.microsoft.com/en-us/download/details.aspx?id=42334

Uninstall any Failed instance of Microsoft Visual Studio 2015 C++ Redistributable.

Reinstall Microsoft Visual Studio 2015 C++ Redistributable.
https://www.microsoft.com/en-us/download/details.aspx?id=53587
