### ISSUE TITLE
Do not display stores without apps in the AppStore section of Administrator

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3068]
There is a checkbox  in the Administrator on the AppStore page `Show Compatible`. It check's compatibility of applications and hides incompatible ones.

It should also hide entire store, if it doesn't contain any compatible applications.

cc @andwah

**Comment by andwah** [comment]
Good point, ill assign it to me.

**Comment by andwah** [comment]
Partly fixed, If the store has apps but all apps is incompatible i thing we still should show the store but inform about that, 

***With apps***

![image](https://cloud.githubusercontent.com/assets/2656996/12511410/7b30c836-c111-11e5-82ba-0e68553f22a2.png)

***Without apps***
![image](https://cloud.githubusercontent.com/assets/2656996/12511422/9144733e-c111-11e5-8284-950c496dd154.png)



Change ddfb84db21b641f0280b0e5918d1aed4c4aea161

**Comment by warpech** [comment]
Nice
