### ISSUE TITLE
Nightly build failed with no disk space

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3071]
> Error in response: System.IO.IOException: There is not enough space on the disk.

**Comment by chrhol** [comment]
Not the buildserver, the downloadserver

**Comment by chrhol** [comment]
I cleaned up a little, there is 8.9g available now on D: on the downloadserver and started a new build.

**Comment by chrhol** [comment]
I think we need to upgrade our downloadserver to a machine with much more space available. Both C:  and D: partitions are almost full, and especially C: we cannot do much about.

**Comment by dan31** [comment]
I will run the procedure over the night. The expectation on Amazon is to have it seamless.
