### ISSUE TITLE
Is DbHelper.FromID equivalent to Db.SQL select to find if object exists in database

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3073]
Are the following equal?

```c#
if (null != DbHelper.FromID(rel.ToOid)) {
	return true;
}
```

and 

```c#
if (Db.SQL("SELECT o FROM " + toClassFullName + " o WHERE o.ObjectNo = ?", rel.ToOid).First != null) {
	return true;
}
```

Thank you!

**Comment by miyconst** [comment]
Yes and no.

The first one will return `true` if there is an object with id `rel.ToOid`.

The second one will return `true` if there is an object with type `toClassFullName` and id `rel.ToOid`.

**Comment by alemoi** [comment]
Sure :D But I need to know the simplest working way to check if an object with certain ID is in database. For SQL I must supply class name, or is there a way using SQL but no class name?

**Comment by miyconst** [comment]
`DbHelper.FromID` should be the simplest way :laughing:

**Comment by alemoi** [comment]
I mean does it check with database or some local copy of the object? Just want to be sure.

**Comment by k-rus** [comment]
> For SQL I must supply class name, or is there a way using SQL but no class name?

No, SQL always requires table name nowadays.



> does it check with database or some local copy of the object?

You can easily track implementation of `FromID` in Level1. I think it is always a request to the kernel to obtain an object from the database with the given ObjectId.

**Comment by miyconst** [comment]
But it works in given `Db.Scope` only.

If I have an object with id `123` in my database, then removed it, but not yet commited, `DbHelper.FromID(123)` will return `null` inside the `Db.Scope`.

**Comment by per-samuelsson** [comment]
> If I have an object with id 123 in my database, then removed it, but not yet commited, DbHelper.FromID(123) will return null inside the Db.Scope.

Yes, this is  by design. Its transaction isolation in effect. In that transaction, the object is deleted. So its not returned. Same as it wouldnt be if you query for it after you deleted it.

**Comment by alemoi** [comment]
That's the answers I needed. Thank you!
