### ISSUE TITLE
Starcounter VSPackage with VS2012

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3077]
Hi!

There seems to be references to a newer version of Visual Studio, I can't use your package. Meaning that I can't use any of my projects.
From the VS activity log 

    C:\Users\careri\AppData\Roaming\Microsoft\VisualStudio\11.0\ActivityLog.xml:

```
<entry>
    <record>369</record>
    <time>2015/11/17 08:57:39.022</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [Starcounter.VisualStudio.VsPackage, Starcounter.VisualStudio, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf]</description>
    <guid>{1EFE6CB9-CD9D-4DA7-8D30-6DDD65C82BFB}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
```

**Comment by chrhol** [comment]
Hi, we noticed this on friday but have been busy with a demo. The projects are sill comaptible, this is due to a bug. 

The first problem is some missing dependencies after we upgraded our buildenvironment to VS2015. We tried to include those in the installer but for some reason it does not copy them to output which means that they are not included in the installer.

The solution for the moment is to either install VS2015 Community (which is free). You can still use 2012 or 2013 of course. The other option is to manually add the missing files. I will contact you on skype.

After wednesday we will spend time in fixing this properly!

**Comment by careri** [comment]
I tried installing without the VSPackage. Then I installed an older VSPackage 2.1.177 I think.
But that didn't work, VS still tried to load a newer version of Starcounter.VisualStudio.dll

So I overwrote the one in %StarcounterBin% with the one from the extension, now the old Starcounter.VisualStudio.dll is loaded.

It compiles but I still can't start from VS because of a missmatch in the API:
Error	9	The debugging sequence failed with an unexpected error. Consult the Visual Studio activity log for additional information. Error summary: Method not found: 'Void Starcounter.Server.Rest.Representations.JSON.Executable.set_IsTool(Boolean)'. (ScErrDebugSequenceFailUnexpect (SCERR12016))

(Double-click here for additional help)		0	0	


@chrhol gave me a zip, I hade already tried with those file, got them as a NuGet.

So I can compile, but not start from VS. Good enough for now...

**Comment by careri** [comment]
Any progress?

**Comment by chrhol** [comment]
I've started working on this today. Will let you know when a fix is in place.

**Comment by chrhol** [comment]
Update: I found three problems that I'm working on solving. The first one is described above.

The second one is missing c++ runtime for vs2015 that unmanaged parts of the extension needs. So the workaround here is to manually install it from [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145) and select and run `vc_redist.x86.exe`

The last one is that errorreporting does not seem to work. If something fails, no errors is reported to visualstudio and it looks like nothing happened. I guess this is also the reason no error was shown for the second problem above.

Working on having 1 and 2 added to the installation package and will look into the third.

**Comment by alemoi** [comment]
After checking with @chrhol we found that current check for redist x86 was not working on the machine, since the registry entry existed but redist x86 wasn't installed. So I will add a different check.

**Comment by chrhol** [comment]
Update of current status: The latest nightly build includes the fixes for c++ runtime and the missing dependencies, so now the extension for 2012 and 2013 (I haven't verified 2013 though, will do that today) works and you can start the app and connect debugger from the studio directly.

One last thing remains however: I cannot get the error-reporting to work. No exceptions, nothing seems wrong, it just doesn't add anything to the errorlist. I'm not sure how to continue with this, I will talk with @per-samuelsson and see if he remembers anything from when he implemented it before.

**Comment by careri** [comment]
Gr8, I'll install it later today. Have some other work in the pipe first

**Comment by chrhol** [comment]
Just pushed a fix for this problem. Hopefully this issue will now be fully solved. The current pushes will be available in tomorrows nightly build.
