### ISSUE TITLE
Running multiple apps in multiple databases

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3078]
Hi!

I'm trying to run two apps, I want to separate their data. Call them App1 and App2.
App1 runs in default

```
star.exe App1.exe
```

App2 runs in HAD (or should run):

```
star.exe "star.exe" -d=HAD --name=HAD --resourcedir=WebApp App2.exe /a /w="%CD%"
```

But when I try to start App2 I get this error:
 ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already been registered. Can't register URI handler "GET /sc/db/{?}/{?}" on port 8080. This handler is already registered. Version: 2.1.469. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR13003. Help. View the log for more details.

**Comment by careri** [comment]
If I run App2 without -d=HAD it starts. But I doesn't actually start because a seconds sccode.exe instance isn't created. Only App1 is running.

Is that as intended? They seem to be running in the same AppDomain as well

**Comment by per-samuelsson** [comment]
> If I run App2 without -d=HAD it starts. But I doesn't actually start because a seconds sccode.exe instance isn't created. Only App1 is running.

> Is that as intended? They seem to be running in the same AppDomain as well

Applications run in a shared process, yes. In the same application domain. Thats one of the key concepts in our hosting model.

> But when I try to start App2 I get this error:
ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already been registered. Can't register URI handler "GET /sc/db/{?}/{?}" on port 8080. This handler is already registered.

cc @alemoi

**Comment by alemoi** [comment]
I guess HAD database has the same default user port as your DEFAULT database? Can you please check that and get back to us. Thank you!

**Comment by careri** [comment]
Yes, they have the same port. Changing in the admin GUI solved it. 
Is it possible to supply the database port when launching with star.exe?

Or is it only possible through admin gui?

**Comment by alemoi** [comment]
Yes, it is possible I believe. Let me find it. I think its shown in the extended help for star.exe: star - hx

**Comment by alemoi** [comment]
Here is an example of how to do it:
`star --sc-codehostargs="--DefaultUserHttpPort=8282" Products.exe`

**Comment by per-samuelsson** [comment]
> Is it possible to supply the database port when launching with star.exe?

Officially: no.

> Here is an example of how to do it: `star --sc-codehostargs="--DefaultUserHttpPort=8282" Products.exe`

This is an **unofficial** feature, one we made for our own testing needs. Use it if you want to try, but we'll provide no support for it, and we leave no guarantees its future compatible.

Notice the output of `star -hxx` (stripped):

```cmd
Usage: star [options] executable [parameters]

Options:
  -hxx, -helpunofficial Shows unofficial help about star.exe.
  --sc-codehostargs     Allows for the passing of custom code host parameters
```

**Comment by careri** [comment]
Great, I'll give it a try tomorrow. What happens if the database is started. Will it restart with the port from the command line?

**Comment by per-samuelsson** [comment]
> What happens if the database is started. Will it restart with the port from the command line?

No it wont. Thats why I'm not totally happy this very specific internal functionality is exposed like this.

**Comment by careri** [comment]
Ok, good to know. Thanks

**Comment by k-rus** [comment]
Actually it is not possible to start two databases without manual configuration due to the above problem.

I start one database (default) and then I try to start a custom one and it fails with the above error:

```bash
>staradmin start db
Starting default (started, code host PID: 3316)

>staradmin -d=dropttabledb start db
Starting dropttabledb (starting database ..)

[08:39:43, Starcounter (dropttabledb)]
System.Exception: ScErrHandlerAlreadyRegistered (SCERR13003): This handler has a
lready been registered. Can't register URI handler "GET /sc/db/{?}/{?}" on port
8080. This handler is already registered.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR13003.
   at Starcounter.GatewayHandlers.RegisterHttpHandlerInGateway(UInt16 port, Stri
ng appName, String methodSpaceUri, Byte[] nativeParamTypes, UInt16 managedHandle
rIndex, UInt64& handlerInfo) in C:\GitRepositories\Starcounter\Level1\src\Starco
unter\Apps\GatewayHandlers.cs:line 607
   at Starcounter.Rest.UriHandlersManager.RegisterUriHandler(UInt16 port, String
 methodSpaceUri, Byte[] nativeParamTypes, Type messageType, Func`4 wrappedDelega
te, NetworkProtocolType protoType, HandlerOptions ho) in C:\GitRepositories\Star
counter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 606
   at Starcounter.Rest.UriManagedHandlersCodegen.RegisterDelegate(UInt16 port, S
tring methodSpaceUri, MethodInfo userDelegateInfo, Expression delegExpr, Network
ProtocolType protoType, HandlerOptions ho) in C:\GitRepositories\Starcounter\Lev
el1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 606
   at Starcounter.Rest.UriManagedHandlersCodegen.GenerateParsingDelegate[T1,T2,T
3](UInt16 port, String methodSpaceUri, Func`4 userDelegate, HandlerOptions ho, N
etworkProtocolType protoType) in C:\GitRepositories\Starcounter\Level1\src\Starc
ounter.Rest\UriManagedHandlersCodegen.cs:line 887
   at Starcounter.Rest.RestRegistrationProxy.RegisterHandler[T1,T2,T3](UInt16 po
rt, String methodSpaceUri, Func`4 handler, HandlerOptions ho) in C:\GitRepositor
ies\Starcounter\Level1\src\Starcounter.Rest\RestInitialization.cs:line 86
   at Starcounter.Handle.GET[T1,T2,T3](String uriTemplate, Func`4 code, HandlerO
ptions ho) in C:\GitRepositories\Starcounter\Level1\src\Starcounter.Internal\Han
dle.GET.cs:line 228
   at Starcounter.UriMapping.Init() in C:\GitRepositories\Starcounter\Level1\src
\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 1098
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedul
ers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTim
eoutMinutes, String dbName, Boolean noNetworkGateway) in C:\GitRepositories\Star
counter\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 113
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\GitReposi
tories\Starcounter\Level1\src\Starcounter.Bootstrap\Control.cs:line 208
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\GitReposit
ories\Starcounter\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR13003
```

Note that I haven't started any applications with any handlers. I believe this behaviour is very confusing and it is necessary to resolve it, but not high prio I think. I remember somewhere it was discussed to choose port automatically.

**Comment by dan31** [comment]
Archived. @per-samuelsson feel free to reopen if needed.
