### ISSUE TITLE
Adapt installer for 2.2 to new upgrade policy

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3082]
Basically this: https://github.com/Starcounter/CompanyTrack/issues/120#issuecomment-157378644.

And the background is in the previous comments, leading up to that point. In some way or the other, we need to adjust the installer for 2.2, becuase the strategy implemented now is not sufficient (it was broken in **pnext** and will now raise an exception during reading of the image versions, as hinted in the above thread).

When doing this, we can also decide if we should drop or keep [this](https://github.com/Starcounter/CompanyTrack/issues/120#issuecomment-157343051). And if we decide to keep it, we should adapt it to [this](https://github.com/Starcounter/CompanyTrack/issues/120#issuecomment-157346546).

**Comment by dan31** [comment]
This logic is lifted to Starcounter itself through more new issues. This one is archived.
