### ISSUE TITLE
Document JSON dollar signs ($) and "Reuse"

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3086]
Being part of application development as an observer, I find the dollar sign usage is non intuitive, and also I can't find any good throught documentation on it. 

I understand also that dollar-sign has double meaning: one if its place in the beginning of a name (metadata?), another if its at the end of it (editable?). Please someone convince me this is good, because right now, I think its not.

Also: the seem to be some "Reuse" magic I can use in JSON to deal with... I dont know really. Recursion of types / items or something like that? Couldn't find any docs on that either.

**Comment by miyconst** [comment]
There is a page on starcounter.io: http://starcounter.io/guides/json/json-data-binding/

**Comment by miyconst** [comment]
The `Typed JSON` section has to be improved with explanation of `Readonly` and `Editable` properties.

**Comment by per-samuelsson** [comment]
> There is a page on starcounter.io: http://starcounter.io/guides/json/json-data-binding/

Yeah, thanks, I read that through last night. But it could neither find the $ properly explained to me (only how its use to define metadata), and not a word on "Reuse". Hence this issue.

**Comment by chrhol** [comment]
There is an issue created some months ago, https://github.com/Starcounter/Starcounter/issues/2650 about reviewing and documenting it, but no time have been spent on it. 

> Please someone convince me this is good, because right now, I think its not.

I think the only argument you will get is that this is the way it was first implemented in the really early prototype and then never touched again. It would be really good to have some discussion about this and see if we want to change it. 

There is a lot of "hidden" metadata you can set, and most of it should probably be removed since the implementation have changed during the early stages.

**Comment by warpech** [comment]
Clone of: https://github.com/Starcounter/starcounter.io/issues/88

**Comment by per-samuelsson** [comment]
When documenting "Reuse", we should also document the somewhat related concept of inheritance. Some discussion on this in this https://github.com/Starcounter/Starcounter/issues/3200#issuecomment-166566031.

**Comment by per-samuelsson** [comment]
Hm, just found #1028. Are these duplicates? If so, let's close that other one (since it now has less content).

**Comment by warpech** [comment]
@per-samuelsson does the current text about `Reuse` in http://starcounter.io/guides/json/json-data-binding/ satisfy your question regarding the concept of inheritance? 

If yes then this issue can be closed. Otherwise please suggest changes to the text.

**Comment by chrhol** [comment]
I think this issue can be closed now. The documentation will also be updated with issue #3811 and the switch to have more of this set in code-behind.
