### ISSUE TITLE
pnext: Prevent layouts from being garbage collected when referenced from meta-data

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3087]

**Comment by k-rus** [comment]
Note that the relevant design of meta-data will be changed.

**Comment by chrhol** [comment]
I noticed this behaviour when testing schema upgrades. The newly created layout gets GC:ed and you get a false positive for doing an upgrade leading to an error. 

How much work do you think it is to fix this?

**Comment by k-rus** [comment]
> I noticed this behaviour when testing schema upgrades. The newly created layout gets GC:ed and you get a false positive for doing an upgrade leading to an error.
> 
> How much work do you think it is to fix this?

Current work around can be to recreate auto index on new layout.

**Comment by eriohl** [comment]
I'll start looking into this today. If it is an issue we can, a temp fix, disable the GC?

**Comment by alexanderstc** [comment]
I'd be happy to help - to provide some api on the metalayer, which kernel can use to find out if a layout is in use, or to call some kernel api whenever metalayer registers/deregisters a layout.

**Comment by chrhol** [comment]
> I'll start looking into this today. If it is an issue we can, a temp fix, disable the GC?

I dont think that that will be needed. We can wait for the proper fix.

**Comment by eriohl** [comment]
It will be a bit of a fix for now regardless I fear because DM is not aware of meta-data tables currently.

Best approach I think is for the GC to check the "RawView" table. Then is can just add a reference to the layout for each reference from this table. And we are done. I'm not entirely sure how to best do this however since, as mentioned, DM isn't aware of the meta-data tables.

**Comment by alexanderstc** [comment]
> the GC to check the "RawView" table

How/how often to detect the changes?

**Comment by eriohl** [comment]
GC currently only runs after load. Possibly it could also run each time all IWPs are disconnected but it is not possible to run while a IWP is connected (and data is being updated).

**Comment by k-rus** [comment]
What's about suggestion from @alexanderstc to call kernel API when metalayer register or unregister a layout? Can it allow kernel to know that the layout is still in use?
I understand that it is not a beautiful solution, but I don't see such. And I think it is better than kernel knows about meta-data structure.

**Comment by eriohl** [comment]
References are not stored in database but evaluated by GC. So that won't work. GC need to be able to find the reference.

**Comment by eriohl** [comment]
Would is be possible to create a constant for the set specifier on RawView "table" and the column index on LayoutHandle column in this table. This is basically what I need but figuring this out seems a bit of a hazzle. @k-rus @alexanderstc ?

**Comment by alexanderstc** [comment]
Technically it's quite possible. However, @k-rus was leaning towards metalayer providing a clean api for kernel needs, so the kernel wouldn't have to dig around metalayer bowls / know the metaschema etc.

**Comment by eriohl** [comment]
I agree with this in principle. Although I think I will have to duplicate a lot of code from meta-layer to implement this fix. But ok: I'll try to do this from the fixed tokens and see how it goes.

**Comment by alexanderstc** [comment]
> I think I will have to duplicate a lot of code from meta-layer to implement this fix

@k-rus and me would rather give you a nice clean metalayer api function which will do all the digging in the RawView table, so you wouldn't have to re-implement metalayer code in the kernel.

**Comment by eriohl** [comment]
That would be welcome of course.

Could implement support for a subset of the sccoredb API on data manager. Problem is that it can't be fully supported. Will be a lot of work and won't be plug and play anyway.

**Comment by k-rus** [comment]
> Would is be possible to create a constant for the set specifier on RawView "table" and the column index on LayoutHandle column in this table. This is basically what I need but figuring this out seems a bit of a hazzle. @k-rus @alexanderstc ?

As @alexanderstc pointed it is possible, but will require some time to do it in general way.



> Could implement support for a subset of the sccoredb API on data manager. Problem is that it can't be fully supported. Will be a lot of work and won't be plug and play anyway.

Am I correctly interpret this as metalayer cannot use kernel iterators to iterate data at this point?

**Comment by eriohl** [comment]
At this point you can't do very much on DM at all. Iterators and other read-only operations can however be supported with a bit of work. Problem is updates. These can't work the same way on DM.

Currently I'm just looking for the easiest way to solve the problem that is unlikely to lead to a lot of work compensating for the fix in future.

**Comment by eriohl** [comment]
Best approach I've found so far:

1. Find token for "RawView". Lookup layout on token.
2. Find token for "LayoutHandle". Find column index in layout using token.
3. Find token for "RawViewPK". Lookup index on token.
4. Iterate "RawViewPK" index (it only contains RawView records), and read which layouts are referenced.

Tokens you can lookup using the InvariantName index for which the token is a constant. All of these string are constants also of course.

**Comment by k-rus** [comment]
> Find token for "RawView". Lookup layout on token.
> Find token for "LayoutHandle". Find column index in layout using token.
> Find token for "RawViewPK". Lookup index on token.

We already have some support for token constants. To support token constants should not take much time, I guess. We will create them. 

(Creating constants for setspecifier and column index is much bigger task, while tokens are straight forward, since we already have them.)

**Comment by eriohl** [comment]
Ok. I'll do something else until we have the constants then.

**Comment by alexanderstc** [comment]
See #45.

**Comment by alexanderstc** [comment]
@eriohl please use src/include/star/predefined_metadata.h

**Comment by eriohl** [comment]
Ok. Great. I'll work in this today then.

**Comment by eriohl** [comment]
I fixed so that there constants are used for key and setspec column tokens in kernel.

**Comment by eriohl** [comment]
I think the reference to #45 might be a bit off.

**Comment by alexanderstc** [comment]
https://git.starcounter.org/BlueStar/level0/issues/45

**Comment by eriohl** [comment]
I fixed so that GC doesn't drop layouts referenced by RawView isn't garbage collected. Code pushed.

I will clean it up a bit and then this should be done.

Question @k-rus @alexanderstc: I used this error SCERRUNEXPMETADATA when metadata can't be understood. Seems like this is used as a generic error for this. Is this ok or should I use something else? The error message seems a bit of a bad fit.

**Comment by eriohl** [comment]
(For code reference see writer::fix_add_metadata_layout_references, writer.dll.)

**Comment by alexanderstc** [comment]
SCERRUNEXPMETADATA is fine by me.

**Comment by eriohl** [comment]
Ok then.
