### ISSUE TITLE
Bind a checkbox

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3093]
Hi!

I can't figure out how to bind a checkbox with the new version of Polymer. I tried to use the button as a template:

    <button value="{{model.SaveAll$::click}}" onclick="++this.value">Save All</button>

So I though a checkbox should look something like this:

    <input type="checkbox" value="{{model.ShowDenied$::checked}}" onchange="++this.value"/>Show Denied</input>

But nope, I just can't figure it out.

**Comment by miyconst** [comment]
What is data type of ShowDenied? It should be Boolean.

The binding works like this:

```html
<input type="checkbox" checked="{{model.ShowDenied$::change}}"/>
```

**Comment by careri** [comment]
Yes it's a boolean, I had it working with previous version of Polymer. 
I'll try that. Thanks

**Comment by careri** [comment]
It works, thanks

**Comment by warpech** [comment]
I have created a repo to show such patterns: https://github.com/StarcounterSamples/KitchenSink

Need to advertise it a little bit more
