### ISSUE TITLE
Console.WriteLine() does not print when called using Timer and DbSession.RunAsync

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3097]
I would expect this program to emit `Foo` in the Administrator console for the application every second, but nothing appears.

Version: Nightly, 2.1.538

```
using System;
using Starcounter;
using System.Threading;

namespace Foo
{
    class Program
    {
        const int _interval = 1000;
        private static Timer _timer;

        static void Main()
        {
            _timer = new Timer((state) => {
                    (new DbSession()).RunAsync(() => {
                        Console.WriteLine("Foo");
                    });
            },
                   null, _interval, _interval);
        }
    }
}
```

**Comment by andwah** [comment]
After a quick investigation:
When the Console.WriteLine is called the ```Application.Current``` property is throwing an ```InvalidOperationException```

The ```Application.Current.Name``` is used to direct the message to the correct application.

Changed the Assignee back to "no one". i dont have a solution to this (maybe using the stack to get the application?), I hope @per-samuelsson, @chrhol or @alemoi knows the right solution for this.

**Comment by alemoi** [comment]
Maybe its related to recent changes around moving appname?

**Comment by andwah** [comment]
> Maybe its related to recent changes around moving appname?

I think it has been like this since ```Application.Current``` was introduced.
 It was then an acceptable behaviour :-(

**Comment by warpech** [comment]
My workaround for this is to use `RunWithinApplication`:

```cs
        static void Main()
        {
            string appName = StarcounterEnvironment.AppName;
            _timer = new Timer((state) => {
                    (new DbSession()).RunAsync(() => {
                        StarcounterEnvironment.RunWithinApplication(appName, () => {
                            Console.WriteLine("Foo");
                        });
                    });
            },
                   null, _interval, _interval);
        }
```

**Comment by per-samuelsson** [comment]
Wouldn't it be feasible, as a default, to assign the application of the caller of `RunAsync` to the context where the callback actually execute?

Pseudo-code:
```cs
public void RunAsync(Action a) {
  Scheduler.Queue(new Context(Application.Current)).Run(a);
}
```

That seem like the least-suprise principle to me at least.

**Comment by dan31** [comment]
CC @alemoi Question there.

**Comment by alemoi** [comment]
@per-samuelsson if your suggested `RunAsync` impl would be called from an arbitrary .NET thread, I suppose the `Application.Current` will not be available, isn't it?

**Comment by per-samuelsson** [comment]
> @per-samuelsson if your suggested `RunAsync` impl would be called from an arbitrary .NET thread, I suppose the `Application.Current` will not be available, isn't it?

I'm not sure I understand that question?

First, `Application.Current` is just a lookup using the `StarcounterEnvironment.AppName`, so if that underlying thing work, `Application.Current` will work. And likewise, if the name is not defined,  `Application.Current` will not work.

Second, what I meant was simply that when a thread has `StarcounterEnvironment.AppName` set to a valid app name, it seams feasible to transfer that name to the thread that will eventually run the `RunAsync` callback. Basically just sugaring for what @warpech define [here](https://github.com/Starcounter/Starcounter/issues/3097#issuecomment-173146206), relieving the user from having to explicitly invoke `StarcounterEnvironment.RunWithinApplication`.

**Comment by alemoi** [comment]
Everything you have mentioned is definitely true. However, when starting arbitrary .NET threads - the `StarcounterEnvironment.AppName` is no longer set there, which is the actual problem. Just to mention `RunAsync` already sets the appname correctly.

**Comment by warpech** [comment]
Is it fixed?

**Comment by linkdata** [comment]
IIRC @alemoi worked on it so the behavior is as expected when called from within a `ScheduleTask()` delegate. When called from a .NET thread, it would require parsing the callstack so that isn't supported.

So it's a mix of "improved" and "wont fix".
