### ISSUE TITLE
WebSocket connection closed. Status code: 1011. Reason: No value found in patch.

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3098]
Reported by @jwillmer.

I've now set up an environment and can reproduce it on my machine, and @alemoi helped me to find where I could look at the diagnostic content. I have isolated it, but I cant really understand what goes wrong.

These are the three relevant patches being sent:

```
[{"op":"replace","path":"/_ver#c$","value":1},{"op":"test","path":"/_ver#s","value":0},{"op":"replace","path":"/workspaces/0/PIM/ProductTypeModel/Breadcrumb/ChildName$","value":"a"}]
[{"op":"replace","path":"/_ver#s","value":1},{"op":"test","path":"/_ver#c$","value":1},{"op":"replace","path":"/workspaces/0/PIM/ProductTypeModel/Breadcrumb/SelectedChild","value":{}},{"op":"replace","path":"/workspaces/0/PIM/ProductTypeModel/Breadcrumb/AdjacentSibblings","value":[]},{"op":"replace","path":"/workspaces/0/PIM/ProductTypeModel/Breadcrumb/IsButtonActive","value":true}]
[{"op":"replace","path":"/_ver#c$","value":2},{"op":"test","path":"/_ver#s","value":1},{"op":"replace","path":"/workspaces/0/PIM/ProductTypeModel/Breadcrumb/OnSubmit$"}]
```

I'll preserve the environment here on my box. Maybe @chrhol has some idea? You are free to ask followups / instruct me, or come by to debug it here if that could help!

**Comment by chrhol** [comment]
The last patch on the third row is not correct, the `op` and `path` pairs looks correct but there is no value which is not allowed according to the jsonpatch rfc (https://tools.ietf.org/html/rfc6902#section-4.3): 

> The "replace" operation replaces the value at the target location
   with a new value.  The operation object MUST contain a "value" member
   whose content specifies the replacement value.

`{"op":"replace","path":"/workspaces/0/PIM/ProductTypeModel/Breadcrumb/OnSubmit$"}`

I'm not sure why a value is not added. Is this a custom component on the client?

**Comment by per-samuelsson** [comment]
> I'm not sure why a value is not added. Is this a custom component on the client?

Wow, I'm not really sure. But I'll make sure to doublecheck that, and get back to you. If I'd do my best guessing, I think its this one:

```html
<button type="button" class="btn btn-box-tool" data-widget="collapse" value="{{model.OnSubmit$::mousedown}}" onmousedown="++this.value">
  <i class="fa fa-plus"></i>
</button>
```

I'll get back to you once I find out for sure. Thanks for the help.

**Comment by jwillmer** [comment]
I created a bug report as well but it seams like it is a polymer bug: [Bug report at Starcounter](https://github.com/Starcounter/Starcounter/issues/3096)

**Comment by miyconst** [comment]
@per-samuelsson, @jwillmer, @chrhol,

You don't need to waste your time on this.

Puppet has two modes, debug mode and production mode. The production mode is enabled by default. In the production mode all of the patches are not validated. That is why a patch with `undefined` value got through to the server. This is obviously an incorrect patch, and server closes the connection.

Polymer has a bug, setting value of such button to `undefined` if the button has any tags inside. I have reported the bug, they have accepted the bug, but not fixed yet.

```html
<button value="{{model.Click::click}}">Click</button>
```

When Puppet runs in debug mode, then such patch will be caught on client side, and puppet will fail with an exception.

**Comment by per-samuelsson** [comment]
@jwillmer @miyconst 

Thanks for that guys. Great we got on top of it at least, even though its still a problem (but one we can workaround). Let's just wait for Polymer to address it then. :+1:

**Comment by warpech** [comment]
Closing as this is the same issue as https://github.com/Starcounter/Starcounter/issues/3096

Solution is tracked in #3511
