### ISSUE TITLE
Html delay update value?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3100]
Is it possible to delay the update of a bound value in e.g. a input textbox?

Now each keypressed sends and update to the server, this is great in most cases. But sometimes it would be better with a delay or an update on focus lost

**Comment by warpech** [comment]
Yes, it is. The below code sends changes after each keystroke:

```
<input type="text" value="{{model.Name$::input}}">
```

This one sends after input is unfocused:

```
<input type="text" value="{{model.Name$::blur}}">
```

I will add it to [KitchenSink](https://github.com/StarcounterSamples/KitchenSink)

**Comment by careri** [comment]
Nice thanks!
What frameworks exposes these events? Polymer or Puppet?

**Comment by warpech** [comment]
This is a Polymer's thing: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#two-way-native

**Comment by warpech** [comment]
I added a more proper example using `::input` and `::change` to the KitchenSink app: https://github.com/StarcounterSamples/KitchenSink/blob/master/src/KitchenSink/wwwroot/KitchenSink/TextPage.html

Thanks for asking!
