### ISSUE TITLE
Suppress exception in PopulateFromJson(..)

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3101]
When source and destination model differ ```destination.PopulateFromJson(source)``` will throw an Exception.

It would be nice if there was an option to Suppress the exception and let ```destination.PopulateFromJson(source)``` only bind matching properties.

**Comment by chrhol** [comment]
Thanks for reporting this. We had another request for this quite some time ago, but unfortunately it was not implemented then, and other things got in between.

**Comment by chrhol** [comment]
It's now possible to specify that properties that does not exist in the template will be ignored (#3802)
