### ISSUE TITLE
How to add a list of items to a database class?

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3104]
I get a compile error ([DataTypeNotSupported](https://github.com/Starcounter/Starcounter/wiki/SCERR4012)) with this code:
   
``` 
    [Database]
    public class Order
    {      
        public IEnumerable<Product> Products;
    } 

    [Database]
    public class Product
    {
    }
```

Which data type do I have to use to add a list of items to my class? [Creating database classes on Starcounter.io](http://starcounter.io/guides/database/creating-database-classes/) does not have any example on lists.

**Comment by warpech** [comment]
The [InvoiceDemo Tutorial](http://starcounter.io/tutorials/1-introduction-to-part-1/1-6-create-the-database-classes/) example shows the usage of `QueryResultsRows<T>`. That should work.

**Comment by warpech** [comment]
Note to team: This should be explained somewhere in the http://starcounter.io/guides/database/ section

**Comment by per-samuelsson** [comment]
> Note to team: This should be explained somewhere in the http://starcounter.io/guides/database/ section

Totally agree, this is a super common case, I can't understand we havent caught it earlier.

@jwillmer, the way this is normally done is that you would implement a pattern like this:

```C#
class Order {
  public QueryResultsRows<Product> Products {
    get { return Db.SQL<Product>("SELECT p FROM Product p WHERE ..."); }
  }
}

We can probaly improve in this area, and years ago, we had a declarative style to support this kind of 1-many-relationships, using a custom attribute. Not now though.

**Comment by per-samuelsson** [comment]
To be even clearer on the above, the normal pattern is

1. You define some class that is the "item", referencing the "head".
2. You have this:

```C#
[Database]
public class OrderItem {
  public Order Order;
  public Product Product;
}

[Database]
public class Order {
  public QueryResultsRows<OrderItem> Items {
    get { return Db.SQL<OrderItem>("SELECT i FROM OrderItem i WHERE i.Order = ?", this); }
  }
}
```

**Comment by jwillmer** [comment]
So in short I need to create the reference class/table myself.
Thank you @per-samuelsson for the example.
