### ISSUE TITLE
Hook on a base class

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3108]
@per-samuelsson is it possible to fire hooks of parent class for children instances?

Something like this:

```cs
[Database]
public class Something {
    public DateTime CreateDate;
}

[Database]
public class Someone : Something {
    
}

Hook<Something>.CommitInserted += (sender, entity) => {
    entity.CreateDate = DateTime.Now;
};

Db.Transact(() => {
    new Someone();
});
```

The idea is to fill `CreateDate` field in one hook for all classes inherited from `Something`.

**Comment by per-samuelsson** [comment]
@miyconst 

No, its not. Sorry. By design, hooks are for the class they are specified on only.

**Comment by per-samuelsson** [comment]
For information, the recommended pattern for this particular case is to use simple constructor logic:

```C#
```cs
[Database]
public class Something {
    public DateTime CreateDate;
    protected Something() {
      CreateDate = DateTime.Now;
    }
}

[Database]
public class Someone : Something {
    public Someone() : base() {
      // And if you need logic here...
    }
}

```

**Comment by miyconst** [comment]
Yeah, thank you @per-samuelsson! For me it is a pleasant news, because I thought that constructors are not supported for db classes.
