### ISSUE TITLE
The RAM not being released when data deleted from database

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3109]
I have ran test with inserting and then deleting `1 000 000` records into database.

Once data was inserted, the RAM usage grew up for 2-3 gb.
Once data was deleted, the RAM usage didn't go down till I restart database.

Is it a bug or I miss something?

@alemoi, @k-rus, @per-samuelsson, @warpech

**Comment by k-rus** [comment]
If I don't mistake the memory is never released, but it is available for the database use.
cc @eriohl

**Comment by chrhol** [comment]
It might also be that the implicit transaction is blocking the purge of deleted objects, if there are any threads running forever or longrunning jobs (see second paragraph in http://starcounter.io/guides/transactions/running-background-jobs/)

**Comment by miyconst** [comment]
No, there are no background threads, at least I didn't create any. Only one handler to insert rows, and then deleted the rows manually with an sql query from administrator.

**Comment by eriohl** [comment]
Storage memory is allocated in segments with a size depending on the size of memory of your machine. This segments will be released if no longer in used (and then RAM usage will shrink).

However: There is some limitations to this.

First, as @chrhol pointed out there might be and open transaction preventing memory from being purged. The memory used for a deleted record is not released immediately.

Secondly there might be fragmentation that prevents the segment from being released. Segments can only be released if no longer in used. Storage manager tries to defragment storage memory so it can later release memory. But often the system is required to run for a while before memory be reclaimed.

So short answer is that storage memory is generally released when you delete a large part of the records in the database. But often not immediately.

(In next release memory is currently not returned to the OS at all. But we are working on re-implementing and improving this and hopefully we will be able to deliver something that is working better then the current solution in the near future.)

**Comment by miyconst** [comment]
Does this all mean, that memory won't be released at all in Starcounter 2.x? Once some memory were used for database, it will be occupied till server restart.

**Comment by eriohl** [comment]
> Does this all mean, that memory won't be released at all in Starcounter 2.x? Once some memory were used for database, it will be occupied till server restart.

No. Sorry for not being clear. What I meant to explain was that:

1. Memory is generally released to OS when space is freed but generally not immediately.

2. In 2.2 (development version) it is currently not working but it will in future (and probably better then is does in current released).

**Comment by miyconst** [comment]
Okay, now it's clear. Thank you.
