### ISSUE TITLE
Literals are not supported in the query

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3110]
I try to get all ProductTypes there TypeCode is not string empty with this query:

```csharp
return Db.SQL<ProductType>("SELECT pt FROM ProductType pt WHERE pt.TypeCode <> ''");
```

Exception:
> Literals are not supported in the query. Method Starcounter.Db.SQL does not support queries with literals. Use variable and parameter instead.

> Version: 2.1.177.

> Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7029.

The help page is empty. Can you tell me what excatly is not supported and how to do it the 'right' way?

**Comment by miyconst** [comment]
Hello @jwillmer.

You should pass values as parameters:

```cs
return Db.SQL<ProductType>("SELECT pt FROM ProductType pt WHERE pt.TypeCode <> ?", string.Empty);
```

**Comment by k-rus** [comment]
[This page](http://starcounter.io/guides/database/variables/) describes the need of using variables/parameters in SQL queries and not use literals directly.



> Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7029.
> The help page is empty.

This is due to [this bug](https://github.com/Starcounter/Starcounter/issues/1728#issuecomment-37878999). So I bumped there.
