### ISSUE TITLE
Benefits of SynonymousTo

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3111]
Are there any benefits of using the SynonymousTo attribute compared to a getter?

```
[SynonymousTo("m_owner")]
public MQParticipant Owner;
```

Compared to 

```
    public MQParticipant Owner { get { m_owner; } }
```

I'd rather use the getter since the simplifies refactoring

**Comment by careri** [comment]
On second though SynonymousTo should enable SQL querying without creating a CLR instance, right?

**Comment by per-samuelsson** [comment]
> On second though SynonymousTo should enable SQL querying without creating a CLR instance, right?

Yep, but if you implement the pattern exactly as in your second case, where your getter contain just a single statement that return a database field, we detect that and know that we can skip the managed code.

**Comment by per-samuelsson** [comment]
Here's an [old discussion](https://github.com/Starcounter/Starcounter/issues/1193) by the way. This has been "on tapeten" previously.

**Comment by careri** [comment]
Ok, I'll stop using it in new code at least.

**Comment by k-rus** [comment]
> Are there any benefits of using the SynonymousTo attribute compared to a getter?

Only in the case if you want to narrow down the type. Otherwise I prefer to use getter and as @per-samuelsson  mentioned Starcounter recognises it and it works in SQL.

**Comment by per-samuelsson** [comment]
> Only in the case if you want to narrow down the type.

That could be done by hand in a manual case as well of course, but with some extra typing:

```C#
class Foo {
  Bar Bar;
}
class Bar {}
class Baz : Bar {}

class Foo2 : Foo {
  Baz Baz {
    get { return (Baz) Bar; }
    set { Bar = value; }
  }
} 
```

equals

```C#
class Foo2 : Foo {
  [Synonym("Bar")]
  Baz Baz;
} 
```

**Comment by k-rus** [comment]
> That could be done by hand in a manual case as well of course, but with some extra typing:
> 
>
> class Foo2 : Foo {
>   Baz Baz {
>     get { return (Baz) Bar; }
>     set { Bar = value; }
>   }
> }

Will the weaver treat the getter as database property or code property?

**Comment by dan31** [comment]
Archived.
