### ISSUE TITLE
Feedback request: Relative resource directories

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3113]
All,

We are trying to finalize #3099, but we have one thing we just can figure out the right approach to.

If you are giving a **relative directory** to `star.exe`, where would you expect it to be quailified from?

**A)** From the current directory
**B)** From the executable

Example:

```cmd
C:\Users\Per>star --resourceDir=myfiles d:\apps\app1.exe
```

For **[A]**, "myfiles" would expand to `C:\Users\Per\myfiles`.
For **[B]**, "myfiles" would expand to `d:\apps\myfiles`.

Anyone - really anyone - please advice on this. We really want to settle this just once.

**Comment by malx122** [comment]
My vote is [A], everything else will confuse normal terminal users.

**Comment by per-samuelsson** [comment]
Thanks @malx122. Appreciated! That is our current track too, and we actually decided to push that as a first alternative. 

But we are very open to changing it to something else if users get back to us with strong opinions for some other way, so we are keeping this open for a while, to hear what people will say.

**Comment by k-rus** [comment]
From my experience with command line, I expect **A**, i.e., the current directory. I also have experience, e.g., in VS, that the actual location of my project is the starting folder.
Since we are speaking about executable, then I vote for **A**.

**Comment by per-samuelsson** [comment]
> I also have experience, e.g., in VS, that the actual location of my project is the starting folder.

This is because we set it like that by default (in our template). It makes sense.

Thanks for the feedback. And extra thanks because it suggest what I decided to push as a first version.  :wink:

**Comment by per-samuelsson** [comment]
Thanks for the feedback everyone. We settled for what was documented as described in #3099.
