### ISSUE TITLE
Improvements: running background jobs

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3114]
In the end of the article: http://starcounter.io/guides/transactions/running-background-jobs/

>Having this pattern will lead to the following entries in the starcounter log and the shutdown will take longer time.

Can't this issue be solved by replacing: 

```cs
foreverThread = new Thread(new ThreadStart(RunForever));
foreverThread.Start();
```

with

```cs
ThreadPool.QueueUserWorkItem(o => { RunForever(); });
```

In this case the `RunForever` won't block main application thread, and the app will shut down properly.

cc @chrhol, @dan31

**Comment by chrhol** [comment]
Thanks for the input @miyconst!

I was not aware of this, I just assumed that these two patterns would work the same when it came to shutdown. I've tested it and using threadpool instead of creating your own thread works. 

I will update the documentation :santa:

**Comment by miyconst** [comment]
@chrhol did you have a chance to take this? It should be an easy update?

**Comment by miyconst** [comment]
@chrhol I have updated the documentation at http://starcounter.io/guides/transactions/running-background-jobs/.
