### ISSUE TITLE
Replace public API for switching into a Session from manually calling start and stop.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3117]
In some cases you have an asynchronous callback and want to reconnect to a `Session` and a viewmodel (for example if you want to update or push latest changes).

Currently there are two methods that needs to be used, `session.StartUsing()` and `session.StopUsing()`. Since we limit the access to the session using a waitevent, it is important to always call `session.StopUsing()` when finished otherwise no one else will get access to it.

```csharp
...
session.StartUsing();
try {
    session.CalculatePatchAndPushOnWebSocket();
} finally {
     session.StopUsing();
}
...
```

These two methods should **not** be public, instead we should have a method that takes a delegate to be executed in the scope of a session, that automatically switch out of it in the end (similar to `Db.Transact`and `Db.Scope`)

```csharp
session.Scope(() => {
    session.CalculatePatchAndPushOnWebSocket();
});
```

Maybe calling this method `Scope` is confusing and should be called something else?

**Comment by per-samuelsson** [comment]
> Maybe calling this method Scope is confusing and should be called something else?

What about `Use`? `Reuse`?

```csharp
session.Use(() => {
    session.CalculatePatchAndPushOnWebSocket();
});
```

**Comment by chrhol** [comment]
> What about Use? Reuse?

Yeah, I like `Use()`. Will go for that :thumbsup:

**Comment by chrhol** [comment]
I've added a set of methods with the base signature like: `session.Use(Action action);`. I also added some overloads that takes generic arguments and possibility to return a value (using `Func`).

`session.StartUsing()` and `session.StopUsing()` are no longer public, so existing code that uses these will have to be updated when changing Starcounter version.

/cc: @mtornwall, @andwah

**Comment by mtornwall** [comment]
@chrhol :+1: 

I currently have this (poorly named) method in my code:

```
[DebuggerStepThrough]
public static void WithState(this Json json, Action action)
{
    var session = json.Session;
    json.Transaction.Scope(() =>
    {
        session.StartUsing();
        try
        {
            action();
        }
        finally
        {
            session.CalculatePatchAndPushOnWebSocket();
            session.StopUsing();
        }
    });
}
```

I've found that when I want to reattach the session from an async callback I always want to enter a transaction scope and end by pushing any changes to the WebSocket. Personally I think something like this would be a useful extension to the `Use()` method you proposed. WDYT?
