### ISSUE TITLE
Review changes in working- and resource directory from perspective of web admin and app stores

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3119]
Basically, just check that everything I've done in #3099 haven't messed up anything in the client parts. I have tried to adapt where I thought it was needed, but it's best @andwah verifies this as well, before we ship a new stable.

**Comment by andwah** [comment]
I fixed the issue where the resource folder was not set when starting apps from Administrator.

**Comment by per-samuelsson** [comment]
> I fixed the issue where the resource folder was not set when starting apps from Administrator.

OK, good. Thanks. Have you verified all app-related use cases you know of and they seem to work? When you say "go", I'll close all related issues and will OK the upcoming stable build w.r.t to this set of issues.

**Comment by andwah** [comment]
> Have you verified all app-related use cases you know of and they seem to work?

I have not. 

At the moment all my time is invested in the Demo project, no time for testing :-(

**Comment by per-samuelsson** [comment]
> At the moment all my time is invested in the Demo project, no time for testing :-(

OK, I see. Thats probably the right thing to do. Dont worry about this for now then. I'll check with the others whats the way forward. Thanks for clarifying.

**Comment by andwah** [comment]
If someone finds an issue i will of course fix it as soon as possible. probably i will take me 1-5min to find and fix the it.

**Comment by per-samuelsson** [comment]
> If someone finds an issue i will of course fix it as soon as possible.

I know you will, you always do :smile: I just wanted to run through all the stuff once before we decide on a stable release. But again: dont bother with this now, @andwah. Focus on the demo. Either we wait with a stable (don't think theres an urgent need), or else I can set that up some other way. No problem.

**Comment by per-samuelsson** [comment]
Reviewed, and we haven't found anything that indicate anything was broken.
