### ISSUE TITLE
SQL console can not handle GROUP BY

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3120]
If I navigate to ```http://127.0.0.1:8181/#/databases/default/sql``` and enter something like 
```sql
SELECT COUNT(*)                      
FROM OrderStatus status
GROUP BY status.Order
```
I get an incorrect syntax error. Maybe [Db.SlowSQL](http://starcounter.io/guides/sql/aggregates/) is not used?

**Comment by miyconst** [comment]
Can you try to run same query type in one line?

**Comment by jwillmer** [comment]
```sql
SELECT COUNT(*) FROM OrderStatus status GROUP BY status.Order
```
does also not work

**Comment by miyconst** [comment]
Bad. Anyway, I vote up to fix this.

**Comment by per-samuelsson** [comment]
Yeah, like I said off-tracker, I think there are some limitations in web admin SQL compared to `Db.SQL`. I don't know what those are though, or if its documented. And neither why the need to differ. But this might be one of them?

> I vote up to fix this.

Me too.

**Comment by dan31** [comment]
CC @k-rus @andwah

**Comment by k-rus** [comment]
> Maybe Db.SlowSQL is not used?

The answer is [here](https://github.com/Starcounter/Starcounter/issues/2834#issuecomment-145847483). It is used.



> SELECT COUNT(*) FROM OrderStatus status GROUP BY status.Order

`Order` is [a reserved keyword](http://starcounter.io/guides/sql/reserved-words/) in current version of SQL. It will be relaxed in future version.

**Comment by k-rus** [comment]
> Order is a reserved keyword in current version of SQL. It will be relaxed in future version.

Since it is reserved keyword in current version and not in future version, good error message is not reported.

**Comment by jwillmer** [comment]
I encountered another problem that is related:
```SELECT o FROM Namespace.Order.OrderItem o```

This throws an incorrect syntax. If I query for something else that does not have the name "Order" in the Namespace it works.

**Comment by k-rus** [comment]
> I encountered another problem that is related:
> SELECT o FROM Namespace.Order.OrderItem o
> 
> This throws an incorrect syntax. If I query for something else that does not have the name "Order" in the Namespace it works.

As I [wrote](https://github.com/Starcounter/Starcounter/issues/3120#issuecomment-160616766) `Order` is [a reserved keyword](http://starcounter.io/guides/sql/reserved-words/) in current version of SQL. The workaround is to double quote it.

**Comment by miyconst** [comment]
Closing this issue as answered and will be fixed in the new version of SQL Query Processor.
