### ISSUE TITLE
UPDATE does not support parameters

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3121]
It is really annoying that `UPDATE` and `INSERT` can't use parameters same as `SELECT`.

@k-rus, @dan31, @warpech

**Comment by k-rus** [comment]
`UPDATE` does not exist in our SQL. `INSERT` is not available for public use. No plans to do any enhancements to SQL in the current version. This will be targeted in new version.

**Comment by miyconst** [comment]
Okay, closing the issue.
