### ISSUE TITLE
If a table has nullable property and some rows with null in there, then administrator fails to run select over it

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3125]
Was just discovered by TargetEveryOne guys, that if a table has a nullable field, like `DateTime?` and a row with `null` value in it, then query like:

```sql
SELECT * FROM Table
```

Fails with the following exception:

```
System.InvalidOperationException: Nullable object must have a value.
```

cc @andwah

**Comment by andwah** [comment]
I tried a couple of different scenarios, but i could not reproduce.
Can you descried the class and the content of object.  
Where did you see there error? in log, gui popup?

**Comment by Prav962** [comment]
Hi @andwah , 

Please try run application with given below sample code. you got the same exception.
there are two DB object one is nullable and other not nullable.
1. http://127.0.0.1:8080/NullableobjectError/InsertNullable
2. http://127.0.0.1:8080/NullableobjectError/InsertNotNullable

when you try this (Select * from NullableobjectError.NullableobjectEN)) sql query in SQL panel you got error message in popup.

![image](https://cloud.githubusercontent.com/assets/3205560/11741279/e80a179c-a01d-11e5-8e0b-2600e4e4176a.png)


using System;
using Starcounter;

namespace NullableobjectError
{
    [Database]
    public class NullableobjectEN
    {
        public string stringValue1;
        public decimal? decimalNullableValue;
    }

    [Database]
    public class NotNullableobjectEN
    {
        public string stringValue1;
        public decimal decimalNotNullableValue;
    }
    class Program
    {
        static void Main()
        {
            Handle.GET("/NullableobjectError/InsertNullable", ()=> {
                
                Db.Transact(() =>
                {
                    Db.SlowSQL("Delete from NullableobjectError.NullableobjectEN");

                    NullableobjectEN obj = new NullableobjectEN();
                    obj.decimalNullableValue = 12;
                    obj.stringValue1 = "NotNullable1";

                    NullableobjectEN objnull = new NullableobjectEN();
                    objnull.stringValue1 = "Nullable2";
                });
                return "Inserted Try Query (Select * from NullableobjectError.NullableobjectEN)  In SQL Admin Panel";
            });

            Handle.GET("/NullableobjectError/InsertNotNullable", () =>
            {
               
                Db.Transact(() =>
                {
                    Db.SlowSQL("Delete from NullableobjectError.NotNullableobjectEN");

                    NotNullableobjectEN obj = new NotNullableobjectEN();
                    obj.decimalNotNullableValue = 12;
                    obj.stringValue1 = "NotNullable1";

                    NotNullableobjectEN objnull = new NotNullableobjectEN();
                    obj.decimalNotNullableValue = 14;
                    objnull.stringValue1 = "NotNullable2";
                });
                return "Inserted Try Query (Select * from NullableobjectError.NotNullableobjectEN)  In SQL Admin Panel";
            });
        }
    }
}

**Comment by miyconst** [comment]
@Prav962 thank you for the detailed explanation.

**Comment by andwah** [comment]
@Prav962 Thanks for the example, i could reproduced the issue, i tested with a DateTime property and it seemd to work fine, but all other types gives the same error as in this issue.

@chrhol Should it be possible to set/bind a nullable value to a property in a template?

**Comment by chrhol** [comment]
> @chrhol Should it be possible to set/bind a nullable value to a property in a template?

We dont support nullable values today in TypedJson, so the value needs to be converted (to default value) before setting it. This is similiar to this issue: https://github.com/Starcounter/Starcounter/issues/3144

It should be discussed by us and see if we should support nullable valuetypes or not.

**Comment by andwah** [comment]
@chrhol Thanks for the clarification.

I have adapted the query result so it handles nullable's, 
If property value is null the value will be converted to it's default value (false/0/"") and returned. 

Note: The original value in the database will not be changed.

Fix 94b912bfa3b75c5c1c40b92e1ceacf969c7cff6c

**Comment by miyconst** [comment]
@andwah thank you for the fix.

I will close the issue when a nightly build available for test.

**Comment by miyconst** [comment]
@andwah thanks for fixing.
