### ISSUE TITLE
Unable to start Starcounter on a machine

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3127]
Starcounter fails to start on a fresh install of windows 10.

Here are the records from Windows Event Log:

```
Application: scservice.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
Stack:
   at Starcounter.Server.ServerServiceProcess.StartMonitor(System.String, Boolean)
   at Starcounter.Server.ServerServiceProcess.RunUntilStopped()
   at scservice.Program.Main(System.String[])
```

```
Faulting application name: scservice.exe, version: 1.0.0.0, time stamp: 0x565c3823
Faulting module name: KERNELBASE.dll, version: 6.3.9600.16408, time stamp: 0x523d557d
Exception code: 0xe0434352
Fault offset: 0x000000000000ab78
Faulting process id: 0x1554
Faulting application start time: 0x01d12ccd0f77c3c5
Faulting application path: C:\Program Files\Starcounter\scservice.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: 4d329d24-98c0-11e5-9c12-d8cb8a282a6f
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 128966410707, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 128897662565

Problem signature:
P1: scservice.exe
P2: 1.0.0.0
P3: 565c3823
P4: Starcounter.Server
P5: 2.0.0.0
P6: 565c3822
P7: e3
P8: c
P9: System.DllNotFoundException
P10: 

Attached files:
C:\Users\asharma2.TEO\AppData\Local\Temp\WER13AB.tmp.WERInternalMetadata.xml
C:\Users\asharma2.TEO\AppData\Local\Temp\WER1F64.tmp.appcompat.txt
triagedump.dmp
C:\Users\asharma2.TEO\AppData\Local\Temp\WER1FE3.tmp.WERDataCollectionFailure.txt

These files may be available here:
C:\Users\asharma2.TEO\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_scservice.exe_cb6e4a434e352da7d4805a7823fd3ace2ab485d_16bb512a_cab_14689e76

Analysis symbol: 
```

This happens with Starcounter `2.1.656` and up, does not happend with Starcounter `2.1.177`, not sure about the middle ones.

@k-rus, @chrhol, @alemoi, @per-samuelsson, @eriohl

**Comment by chrhol** [comment]
Hi @miyconst. 

If I understand you correctly, you can properly install Starcounter and this happens afterwards? or is the installation reverted when scservice is started in the end (assuming you don't install the VS extension)?

I've tried to reproduce it in a virtual machine using an image from https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/ (MSEdge on Win10) and could not get the same behaviour. Installing, compiling and running InvoiceDemo2 worked fine.

And you tried the old version of Starcounter (2.1.177) and that one worked?

**Comment by miyconst** [comment]
Yes, you are correct. The issue occurs when I try to start Starcounter, either from VS or from anchor on desktop.

It does occur only on one particular machine, works fine on others. And the `2.1.177` version works fine on that machine.

**Comment by chrhol** [comment]
2.1.177 is built before we switched over to VS2015, so maybe the C-runtimes for VS2015 is corrupt or not installed properly on that machine.

Could you try to manually install/repair them and see if that works? https://www.microsoft.com/en-us/download/details.aspx?id=48145

You need both runtimes, x86 and x64

**Comment by alemoi** [comment]
Does Starcounter log contain something?

**Comment by miyconst** [comment]
No, nothing :(

**Comment by alemoi** [comment]
Ok thanks. Seems like incomplete environment since DllNotFoundException is thrown, as @chrhol suggests. What if you run scservice.exe from cmd directly, I would like to see which DLL is not being found.

**Comment by miyconst** [comment]
![image](https://cloud.githubusercontent.com/assets/6435556/11553045/f72a35ea-99b0-11e5-8393-79ece9f66f3d.png)

**Comment by miyconst** [comment]
Here is what happens when I try to run Starcounter from command line.

**Comment by miyconst** [comment]
Trying to reinstall vc runtime gives this error:

![image](https://cloud.githubusercontent.com/assets/6435556/11553118/a85e9d9c-99b1-11e5-9514-07b792a3036b.png)

**Comment by miyconst** [comment]
Googled for the issue, seems like Windows 8.1 installation is corrupted. The logs shows some failures trying to install Windows update. Updating the system now, will see what happens next.

**Comment by miyconst** [comment]
I was wrong about windows 10, it's windows 8.1 Enterprise.

Just installed all of the updated, reinstalled vc++ runtime. Same issue.

**Comment by miyconst** [comment]
Closing the issue as no longer relevant.
