### ISSUE TITLE
Static content served wrong when Working directory points to wwwroot

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3129]
Starcounter `2.1.656` and up fail to serve static content if working directory points to `wwwroot`, work fine when working directory points one level up of `wwwroot`.

This is a big issue, because Images app needs it to be set to `wwwroot` so the `Starcounter.Application.Current.WorkingDirectory` gets correct value.

Even bigger issue comes when static content folder is not `wwwroot`.

@alemoi, @chrhol, @warpech

**Comment by chrhol** [comment]
This is probably something to do with @per-samuelsson latest changes in how resourcedirs are handled. I will assign it to him.

**Comment by per-samuelsson** [comment]
@miyconst 

This is now by design. We no longer make the working directory an implicit resource directory, since it was suggested that would be a security vulnerability.

You can read about the changes done in this https://github.com/Starcounter/Starcounter/issues/3099#issuecomment-160137228, and also under [Static file server](http://starcounter.io/guides/network/static-file-server/) on `.io`.

We discussed this over and over, and I asked for feedback in both #3099 and #3113 and the design was derived from that.

**Comment by per-samuelsson** [comment]
> This is a big issue, because Images app needs it to be set to `wwwroot` so the `Starcounter.Application.Current.WorkingDirectory` gets correct value.

You can always explicitly instruct Starcounter to include the working directory as a resource directory. Just add `--resourceDir=.` Works in both in CLI and VS.

**Comment by miyconst** [comment]
@per-samuelsson thank you for the info.

Could you please provide instruction here what should I do to let Starcounter serve static files from `Images/wwwroot` and the same time `Starcounter.Application.Current.WorkingDirectory` gets correct value?

**Comment by miyconst** [comment]
And we also should update our tutorials.

**Comment by per-samuelsson** [comment]
> Could you please provide instruction here what should I do to let Starcounter serve static files from `Images/wwwroot` and the same time `Starcounter.Application.Current.WorkingDirectory` gets correct value?

Did so [here](https://github.com/Starcounter/Starcounter/issues/3129#issuecomment-161220648) just 5 minutes ago. :smile:

**Comment by per-samuelsson** [comment]
> Did so here just 5 minutes ago.

Cheat-sheet:

In Visual Studio, set Working directory under `Project | Properties | Debug` to where you want it to be. This hasn't changed from before.

Then, in "Command-line arguments" text box, specify the `--resourceDir=[path]`. The path can be absolute or relative. If its relative, its relative to the *working directory*. You can provide several paths by separating them with ";", like so `--resourceDir=foo;bar;.` Notice the last one; its a period. That will map to the working directory itself.

**Comment by miyconst** [comment]
@per-samuelsson, thank you. Internet sucks in here, didn't see your answer, but the second one I like much more ;)
