### ISSUE TITLE
Quoted resource directories in VS extension prevent app from starting

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3131]
Reported by @careri [here](https://github.com/Starcounter/Starcounter/issues/3099#issuecomment-160893288). I have now tested and confirmed; doing this:

```
--resourceDir="somefolder"
```

in VS raise an error. Removing the quotes make it work. Doing `star --resourceDir="somefolder" app.exe` works fine though.

**Comment by per-samuelsson** [comment]
Fixed, pushed and merged in https://github.com/Starcounter/Starcounter/commit/02b0b7ca42294f3c1fd57a783384fff6267035da.

@careri, it should be part of the next nighly. Please verfify it if you have some sparetime. (I know you have a lot of that!) :sunglasses:

**Comment by careri** [comment]
Could someone trigger a build? There is no build from tonight.

**Comment by careri** [comment]
Seems to be working, Thanks
