### ISSUE TITLE
pnext: scdata terminates unexpectedly reloading database

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3135]
cc @eriohl 

Steps to reproduce
1. Build level0 and level1 pnext in debug configuration
2. Edit sqlregression_test.bat to overcome #3123:  pass --disableeditionlibraries flag to scweaver in the line 22
3. Run sqlregression_test.bat
4. Edit sqlregression_test.bat to prevent database cleanup on second run: comment out line 10 and 11
5. Run sqlregression_test.bat
6. See scdata terminates unexpectedly. 

Log says: 
20151203T125341 Critical SQLTEST Starcounter - Assertion failed (true == found_module) at C:\projects\starcounter\pnext\level0\src\behemoth\behemoth.cpp:170 (Data 0).
    00007FFC15EE3A2E sccoredbg!_DumpCallstack : callstack-win.cpp (122)
    00007FFC15EE2CAF sccoredbg!do_handle_assertion_failed : assert-win.cpp (68)
    00007FFC15EE2AA6 sccoredbg!handle_assertion_failed : sccoredbg.cpp (30)
    00007FFC0592AB5E behemoth!behemoth_scllvm_destroy_module : behemoth.cpp (170)
    00007FFC07790429 writer!tree_index::unload_function_lib : tree_index.cpp (368)
    00007FFC0778AD57 writer!purge::purge_dropped_index : purge.cpp (41)
    00007FFC0778ACE1 writer!purge::purge_single_entry : purge.cpp (52)
    00007FFC0778AC51 writer!purge::purge_entries_in_and_free_block : purge.cpp (84)
    00007FFC0778AA34 writer!purge::purge_all_deleted_objects : purge.cpp (138)
    00007FFC0778A74B writer!purge::purge_all_deleted_objects : purge.cpp (294)
    00007FFC0778E3EA writer!tp::direct_commit_write : tp.cpp (110)
    00007FFC0778E7CB writer!tp::commit_write : tp.cpp (527)
    00007FFC077808AA writer!writer::commit_write : export.cpp (172)
    00007FFC05D99C3C loader!recover_commit : recover_commit.cpp (24)
    00007FFC05D98A14 loader!process_transaction : execute_recovery.cpp (70)
    00007FFC05D988AA loader!process_transaction : execute_recovery.cpp (88)
    00007FFC05D9CB5F loader!recovery_manager::process_transaction : recovery_manager.cpp (37)
    00007FFC05D9CDD6 loader!recovery_manager::end_transaction : recovery_manager.hpp (227)
    00007FFC05D9D49F loader!recovery_manager::process_log_entry : recovery_manager.hpp (9)
    00007FFC05D98628 loader!execute_recovery : execute_recovery.cpp (189)
    00007FFC05D9C74A loader!loader$exec : recovery.cpp (59)
    00007FF76E40E56A scdata!run_load : load-win.cpp (192)
    00007FF76E40EC2D scdata!_load_storage : load-win.cpp (358)
    00007FF76E40B1C2 scdata!_main : main.cpp (169)
    00007FF76E40EDB2 scdata!wmain : main-win.cpp (94)
    00007FF76E407284 scdata!invoke_main : exe_common.inl (90)
    00007FF76E40718E scdata!__scrt_common_main_seh : exe_common.inl (264)
    00007FF76E40704E scdata!__scrt_common_main : exe_common.inl (309)
    00007FF76E407299 scdata!wmainCRTStartup : exe_wmain.cpp (17)
    00007FFC1DA62D92 KERNEL32!
    00007FFC1FAC9F64 ntdll!

**Comment by eriohl** [comment]
I can look at this.

**Comment by per-samuelsson** [comment]
@bigwad, others

What about we either create a "pnext" label, or at least use a "pnext" title prefix in all issues specific to that?

**Comment by bigwad** [comment]
I heard that there is a label "BAH" to be attached to issues to be fixed for upcoming release. Is it the case to attach it?

**Comment by per-samuelsson** [comment]
> Is it the case to attach it?

I can't answer that. Sorry. The cryptic ones like "bt" and "BAH" I've never figured out what they mean.

**Comment by eriohl** [comment]
Title prefix is good on bugs in development version I think. Makes it fairly easy for customers to understand that this doesn't apply to them (more so then a label does). But maybe some other prefix would be better.

(Seems like this discussion might be unrelated to the issue however.)

**Comment by per-samuelsson** [comment]
> Makes it fairly easy for customers to understand that this doesn't apply to them.

Exactly. That was my main concern actually.

> Seems like this discussion might be unrelated to the issue however.

Yeah, OT is my fault. Sorry. Back to topic now.

**Comment by dan31** [comment]
Guys, I think I need to re-order "Milestones" labels here, so that the "bug" goes to the right version being in work. Just I need to come up with a right scheme according to today's layout. I will keep you posted.

**Comment by eriohl** [comment]
Resolved.
