### ISSUE TITLE
pnext: Remove extra prefix byte binary

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3146]
Legacy. Binary values keps a byte to keep track of how the data is stored. This is no longer needed and should be dropped.

(Will also affect client).

**Comment by eriohl** [comment]
Prefix byte is used to define a full range. So might not be so easy to drop.

**Comment by eriohl** [comment]
Done. Prefix byte is no longer stored in database.

**Comment by alexanderstc** [comment]
metalayer_functest fails now at search by a binary key.
Please see branch alexander-pnext, file metalayer_functest.cpp, line 683.

BTW, is that right:
sccoredb/update/u_write.cpp line 18: _SC_ASSERT_DEBUG(value[4] == 0);
?

**Comment by alexanderstc** [comment]
That's in debug mode at least.

**Comment by eriohl** [comment]
Debug assert so not that odd if fails only in debug. Runs fine in pnext. Checking your branch.

**Comment by alexanderstc** [comment]
That's not that debug assert what fails.

**Comment by alexanderstc** [comment]
To clarify - the search returns no records, where it should.

**Comment by eriohl** [comment]
Ahh. Ok. Yes that assert is correct.

Works fine for me. Could you:

1. Erase database (stored data is not compatible).
2. Make sure that code generation is rebuilt (easiest to do is to save input.list).
3. Try again.

**Comment by alexanderstc** [comment]
> 2. Make sure that code generation is rebuilt (easiest to do is to save input.list).

That helped just lovely, thanks!
Though I swear I tried to erase the whole build directory before, that didn't help. Go figure.

**Comment by eriohl** [comment]
Code generation has a file that is created from concatenated source files. This one is generated by behemothrcc. This generation only runs under certain conditions however (like updating input.list). It does not detect changes to the individual source files that is included in the list. But a full rebuild should work as well.
