### ISSUE TITLE
ToJson() returns the namespaced json.

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3148]
Hi! 

When I use the `ToJson()` method to serialise a view model I get the merged json as string (namespaced by `AppName`). 

I would expect the `ToJson()` to only return the json specific for my application.

I guess the `ToJson` and `PopulateFromJson` should be each others inverse operations. 
However:

    myJson.PopulateFromJson( myJson.ToJson() )

fails if  `myJson` contains a `AppName` namespace. 

    System.Exception: ScErrJsonPropertyNotFound (SCERR14003): The property is not defined in the template. Property="tunity_terminal"

where `tunity_terminal` is my `AppName`

**Comment by chrhol** [comment]
Thank you for reporting this. You are correct, the namespace should not be added in this case, and perhaps `PopulateFromJson` should handle namespaces as well. 

This happens when a TypedJson instance that is part of a Puppet viewmodel (i.e. is connected to a session) is serialized and the session have namespacing enabled.

I will take a look at it when I'm finished with my current assignment.

**Comment by Starcounter-Jack** [comment]
You should not get the merged JSON. This is a bug.

**Comment by dan31** [comment]
@chrhol will try to address this before 25 Dec 2015, but more likely in January. @chrhol works on a big chunk on pnext branch now that he wants to finish first.

**Comment by chrhol** [comment]
I've been thinking about this one, and I think I have a solution that doesn't require much changes. The namespacing should only be added in two cases:
- The root viewmodel is requested and it is stateful, i.e. stored on a Session, with namespacing enabled
- A patch is requested on the same viewmodel as the point above.

All other cases should simply return ordinary json.

I think I can squeese this in and have it ready some time tomorrow.

**Comment by chrhol** [comment]
Code with the changes specified earlier is pushed to develop and should be included in the next nightly. Serializing TypedJson should result in json without namespaces except for the cases above.

Let me know how it works out @ivarbergman. I will test a bit more tomorrow to make sure I didn't break anything :)

**Comment by ivarbergman** [comment]
Hi! This change solved my problem.
Thanks!

**Comment by chrhol** [comment]
Great, then I will close this issue!

**Comment by Starcounter-Jack** [comment]
I missed this one. Calling ```ToJSon``` from an app should never return the merged tree. This causes app leakage.

**Comment by chrhol** [comment]
> I missed this one. An app calling session.current.tojson should NOT get a merged model. Is this the case?

This is the bug that was solved in this issue. 

> Calling ToJSon from an app should never return the merged tree. The launcher middleware (the same app that merges the html partials) should request the merged viewmodel using an explicit API (GetMergedJSON()).

I'm not sure what you mean or that you know how it works today, but there is room for enhancment of course, maybe a specific mimetype for this is a better alternative? Or is that what you are talking about?
