### ISSUE TITLE
ActiveSocket is null

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3150]
```
Handle.GET("/myapp/test", ( Request request) => {
    Session session = Session.Current;
});
```
Im running with websockets enabled. but ```session.ActiveWebSocket``` is ```null```

Is this expected behaviour?

**Comment by alemoi** [comment]
Thank you for the question! Did you attach a session to a WebSocket when you did request SendUpgrade?

**Comment by andwah** [comment]
> Did you attach a session to a WebSocket when you did request SendUpgrade?

No, Maybe that is done underneath (with the puppet handling)?

**Comment by alemoi** [comment]
Please check that ActiveWebSocket existed at some point (for puppets Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs seach SendUpgrade) and that WebSocket is still alive (not disconnected).

**Comment by alemoi** [comment]
Is this issue still relevant, @andwah ? If not please close it.

**Comment by andwah** [comment]
It's totally normal that the ActiveSocket can be null at the point that i was trying to use it.
