### ISSUE TITLE
Add partial page after assigning a model to the Data object

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3152]
I try to assign a partial view to my current page but it is not possible if I like to assign my model as well: 

```json
{
    "Html": "/.../something.html",

    "Name": "",
    "Age": 0,

    "HistoryPartialPage ": { },

    "OnButtonSaveClick$": 0,
    "IsButtonSaveClickable": false
}
```

```csharp
partial class Page1: Page, IBound<ViewModel>
{ 
    public void Initialize(string id)
    {
           this.Data = new ViewModel(id);   
           this.HistoryPartialPage = new HistoryPage(); // cast exception
    }
```
My current wiring looks like that:

Class | Logical Function
------------ | -------------
URL Mapping | Open page X if url equals Y (call init on page)
View | Display the UI
ViewModel | Properties needed in the view (Name & Age)
CodeBehind | Reference ViewModel, partial views & handle user interactions (button click)

**Comment by per-samuelsson** [comment]
Would [this](http://starcounter.io/guides/json/json-data-binding/#specify-datatype) be of any help?

**Comment by jwillmer** [comment]
I am afraid not @per-samuelsson

**Comment by warpech** [comment]
I did this multiple times, though the value of `this.Data` was always a database object.

I wonder why do you need to have a separate `ViewModel` class. `Page1` *is* the viewmodel.

Can you paste what the text of the exception?

**Comment by jwillmer** [comment]
Now it is working. Seams like while investigating the problem I added a property to my model that was called exactly like the one I tried to use to input the partial.

@warpech Why I need a seperate viemodel: #3105

**Comment by per-samuelsson** [comment]
> Now it is working. Seams like while investigating the problem I added a property to my model that was called exactly like the one I tried to use to input the partial.

Great.

> @warpech Why I need a seperate viemodel: #3105

@jwillmer, did you consider what I proposed [here](https://github.com/Starcounter/Starcounter/issues/3105#issuecomment-162450065)? Would remove quite a few lines of code from what you have now I think. Is it to trivial for you case do you think?

**Comment by warpech** [comment]
> Now it is working. Seams like while investigating the problem I added a property to my model that was called exactly like the one I tried to use to input the partial.

You intrigued me so much that I created a working example of partial nesting, which works after assigning `Data`: https://github.com/StarcounterSamples/KitchenSink/blob/master/src/KitchenSink/NestedPartial.json.cs. `Data` is assigned by the code that creates an instance of NestedPartial.

> @warpech Why I need a seperate viemodel: #3105

Hopefully we can come up with something elegant that will take use of implicit data binding, so we can keep being glue code free!

**Comment by jwillmer** [comment]
Cool :+1: 

@per-samuelsson & @warpech I have a good example of why I need (extra) models for the view. Maybe we can have a look at them and infer some good pattern for it next week :)
