### ISSUE TITLE
SetFlag/GetFlag does not work

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3153]
According to the page http://starcounter.io/guides/database/database-configuration/, the following requests should work:

GET http://localhost:8080/sc/default/SetFlag/UriMappingEnabled/True
GET http://localhost:8080/sc/default/GetFlag/UriMappingEnabled
GET http://localhost:8080/sc/default/SetFlag/OntologyMappingEnabled/False
GET http://localhost:8080/sc/default/GetFlag/OntologyMappingEnabled

But they all return 404 for me.

**Comment by alemoi** [comment]
Thanks for reporting! I will check this!

**Comment by alemoi** [comment]
From the documentation: `All should be called on system port.` Can you please try the same but on your system port, by default 8181. Thank you!

**Comment by warpech** [comment]
Sorry! I have made this mistake more than once. What fools me is that the initial implementation used the current database port (8080, etc).

I have taken the liberty to make it more apparent in the docs: http://starcounter.io/guides/database/database-configuration/

**Comment by alemoi** [comment]
Thank you for adding clarification!
