### ISSUE TITLE
List of ignored tests in pnext

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3155]
Here is a list of ignored (not necessarily failing, can be simply not tested) tests in pnext. Posting it just to track things. Eventually the list should become empty:

SimpleMainWithHandler_test-cs
fletcher32_test-exe
log_reader_test-exe
log_writer_test-exe
max_io_bandwidth_test-exe
sccorelog_test-exe
stream_buffer_test-exe
tt_test-exe
sc_ipc_test-exe
CycleTime_test-exe
ipc_test-bat
loadandlatency_test-bat
prepare_sqlregression_test-bat
tpcc_long_test-bat
retaildemo_test-bat
store_apps_test-bat
apps_separation_test-bat
node_looped_proxy_test-bat
node_proxy_test-bat
node_test-bat
umbrella_node_test-bat
poleposition_test-bat
siege_test-bat
sqlcachetrasher_test-bat
apps_test-bat
urls_test-bat
udp_test-bat
websockets_test-bat
star_loop_exception_test-bat
star_loop_test-bat
dbmapping_test-bat
pokerdemo_test-bat

**Comment by k-rus** [comment]
This list is a strange mix. Some names are duplicated. I am not sure that some names correspond to tests.
Can you explain how did you get the list and why do you think they are tests?

**Comment by alemoi** [comment]
> This list is a strange mix. Some names are duplicated. I am not sure that some names correspond to tests.
Can you explain how did you get the list and why do you think they are tests?

Now I see the duplicates too. Will fix that, thank you.

The list contains everything that the testing framework picked up, using patterns: "*_test.cs *_test.exe *_test.bat *_hosted_test.exe", but what is currently not running as tests.

**Comment by alemoi** [comment]
Except for duplicates that I will fix, the list of succeeding, failed and ignored tests can be seen in Tests tab of every build in TeamCity, e.g.: https://scbuildserver/viewLog.html?buildId=32502&buildTypeId=Starcounter_NewPnextDaily&tab=testsInfo

**Comment by alemoi** [comment]
I thought through and now the tests are shown with the full filename with extension (however I can't use the dot for extension, because TeamCity formats it specifically).
Ignored tests duplicates are fixed. Thanks for noticing.

**Comment by alemoi** [comment]
Some tests are being run using CTest, that's why not all of the have extension.

**Comment by alemoi** [comment]
This is no longer relevant.
