### ISSUE TITLE
Reference to Simplified dll, Copy Local: True

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3156]
Typically when working with Simplified DLL, when I set a reference to it in Visual Studio, it has a value "Copy Local: `True`" by default. 

I need to remember to manually change it to `False`, otherwise it causes a weaving error. It happened to me multiple times on presentations. 

Even if I remember to change it, is there anything we may do to improve the learning curve for developers that will not know what to do in this case?

![image](https://cloud.githubusercontent.com/assets/566463/11682119/4b3839b4-9e63-11e5-99a4-17e9a3d30839.png)

![image](https://cloud.githubusercontent.com/assets/566463/11682162/7740f78a-9e63-11e5-9be8-217298aec341.png)

**Comment by miyconst** [comment]
It also applies to `Starcounter.Extensions` and `SocietyObjects.*`.

**Comment by alemoi** [comment]
I think we should add Simplified and SO to VS project templates by default, so user does not need to add them explicitly.

**Comment by miyconst** [comment]
+1 for the suggestion from @alemoi.

**Comment by jakubklekota** [comment]
+1 @alemoi good suggestion

**Comment by dan31** [comment]
I think it is necessary. Until NewSQL with views is emerged, models are
needed to have in place. @per-samuelsson, your view on this?

**Comment by per-samuelsson** [comment]
> @per-samuelsson, your view on this?

Well, based on the fact that we have already taken a decision that these are necessary dependencies in our new versions, I would consider it rather strange **not** to have them part of the templates. :sunglasses:

**Comment by per-samuelsson** [comment]
#3175 up for grabs!

**Comment by warpech** [comment]
Cool!
