### ISSUE TITLE
Reduce Handsontable file size in the Administrator

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3157]
@budnix since we are only using Handsontable for readonly purposes, could you switch to use a minimal build? 

Currently Administrator is using a "maximal" build that weights about [1 MB](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.Administrator/app/vendor/handsontable/handsontable.full.js) unminified uncompresseed. I believed this can be shrinked to a fraction of that.

**Comment by miyconst** [comment]
@warpech, I would like to use it for editing purposes in future as well.

**Comment by budnix** [comment]
Connected with https://github.com/Starcounter/Starcounter/issues/2991

**Comment by warpech** [comment]
> @warpech, I would like to use it for editing purposes in future as well.

No problem, I think that the minimum build also contains editing. Anyway, you are most likely never going to use 100% of the features, so using a custom build will still a way to go.

**Comment by miyconst** [comment]
Agree.

**Comment by warpech** [comment]
@budnix wrote in an email:

> Added minified version of Handsontable and ngHandsontable. Handsontable is now customized it includes only necessary plugins.
	
> Comparing Handsontable full build with customized build we saved about 300k - comparing uncompressed code and 145k - comparing compressed code.

> I have added information about Handsontable customized build to TEST.md. I went through the tests described in this file and looks good for me.

I confirm that https://github.com/budnix/Starcounter/commit/e258f21c0a9490be9fc3f72dd5d32a2d5c6c6e59 fixes the problem.

This commit changes paths to JS files in `index.html`. I need to make sure they are updated in `.csproj` as well.

I will merge it later.

**Comment by warpech** [comment]
@budnix is there any reason why you kept on using `handsontable.full.css` instead of `handsontable.full.min.css` in https://github.com/budnix/Starcounter/commit/e258f21c0a9490be9fc3f72dd5d32a2d5c6c6e59?

**Comment by warpech** [comment]
Switched to use minified CSS. @budnix said it's ok in IM.
