### ISSUE TITLE
Start the new database by default

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3158]
When I'm creating a new database, I always forget that I need to start it before it can be used.  Being used to traditional RDBMS, I always find this surprising.

Could we add a checkbox to the "Create a new database" form (checked by default):

`[x] Start the database now`

<img width="1431" alt="screen shot 2015-12-09 at 11 02 41" src="https://cloud.githubusercontent.com/assets/566463/11682382/be56c892-9e64-11e5-9baf-77d1bfd3eeae.png">

When it is checked, the database will be started immediately after it is created.

**Comment by per-samuelsson** [comment]
> Could we add a checkbox to the "Create a new database" form (checked by default).

Lets not even add that checkbox IMO. If you create a database, we start it. And if someone comes back saying this is wrong, we adress it there and then.

**Comment by per-samuelsson** [comment]
@andwah, WDYT? Just send a `StartDatabaseCommand` once you've created it? Shouldn't be more than that, no?

**Comment by andwah** [comment]
Not hard to do,,

What do you think ppl usually want to do directly after they created the database? 
1. Install apps.
2. ?

I can not directly come up with a scenario when a user do not want to have it started. 
I agree with @per-samuelsson that there is no need for a checkbox.

**Comment by per-samuelsson** [comment]
> What do you think ppl usually want to do directly after they created the database?

I'm also curious about this. @warpech? @miyconst?

And why do *you* create databases like this normally, @warpech? I mean, we always create the database for you once you start an application.

**Comment by warpech** [comment]
> Lets not even add that checkbox IMO. If you create a database, we start it. And if someone comes back saying this is wrong, we adress it there and then.

This is fine for me. I proposed a checkbox in case there would be opposition of someone in the team who thinks it is important to be able to create databases without starting them.

> And why do you create databases like this normally, @warpech? I mean, we always create the database for you once you start an application.

Ha! Assume I don't have VS. I have just installed Starcounter on a new PC. 

1. I start Starcounter server
2. Go to the Administrator 
3. Create a database
4. Start the database
5. Go to the app store
6. Install an app
7. Start the app

Currently I can't skip points 4 and 7, and I think both are easily skippable.

This issue is only about skipping point 4, for now. I will let @andwah consider skipping 7 as well (starting installed apps automatically).

**Comment by per-samuelsson** [comment]
> Ha! Assume I don't have VS. I have just installed Starcounter on a new PC.

Aha, so it seem the workflow is quite different, and not really consistent. In the CLI or in VS, you just run your application. The database "is there" for you like that.

Wouldn't it make sense to have the same workflow in the web administrator? Like "Download and run this app from the app store", and that creates a default database if I dont have one, and run the app inside it.

**Comment by andwah** [comment]
> 7. Start the app

Is done if you use the AppStore application.  

We had some thoughts of removing the appstore part in the administrator and run the "real" appstore client there instead. so only ONE appstore app. 

I think we agree that point (4 start database)  can be automated in code. It's an easy fix, 1h or so.

@dan When do you think i should do this?

**Comment by per-samuelsson** [comment]
> @dan When do you think i should do this?

You want to ping @dan31, I think. :smile:

**Comment by andwah** [comment]
> You want to ping @dan31, I think.

oups. yes, thanks :-)

**Comment by andwah** [comment]
This has now been fixed, now when user creates a database it will also be started.

**Comment by warpech** [comment]
Nice, thanks!
