### ISSUE TITLE
pnext: Fix native filter to handle unexpected layouts in result

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3159]
Since a filter is built for a fixed layout (the expected layout), filter processing needs to use the expected layout rather then the layout of the record.

**Comment by eriohl** [comment]
This is not so trivial because of inheritance. Even if the layout of the record is not the same as the layout of the filter it could still be a compatible layout. And figuring this out from the layout handle is both costly and unnecessary (because the client already know this).

Also, we want to use the expected layout rather then the the filter layout in case the layout is incompatible because the kernel currently can't handle reading a pending updated with a different layout then that if the pending update (although we might want to fix this).

So then we have two options I think:

1. Have the filter processing be aware of the expected layouts of all layouts.

 OR

2. Check if layout is compatible with filter layout and if not always process the filter with the layout of the filter (and fix the previously mentioned issue with pending updates).

My vote is for 1 because it is easier to implement and has less overhead. But it does require the client (of the filter layout) to register expected layouts for all layouts. Opinion @chrhol, @k-rus, @alexanderstc?

**Comment by k-rus** [comment]
What is the filter?

Expected layouts are registered in meta-data and connected to setspecifier and any layout has connection to a setspecifier, therefore it is just technical work to register expected layouts for all layouts. Actually this can be done in meta-data as part of new meta-schema design.

**Comment by eriohl** [comment]
> What is the filter?

Filter created by ```star_context_create_filter```. Not sure what you mean?

> Expected layouts are registered in meta-data and connected to setspecifier and any layout has connection to a setspecifier, therefore it is just technical work to register expected layouts for all layouts. Actually this can be done in meta-data as part of new meta-schema design.

I was thinking to register the layout with the filter processing when registering the type binding in managed code. This is legacy stuff to be discarded so we should avoid additional references to it I think (to filter.dll that is). And yes, this is trivial to implement. But it will add a bit of maintenance possibly.

**Comment by k-rus** [comment]
> What is the filter?
> Filter created by star_context_create_filter. Not sure what you mean?

I've never dealt with it, thus I don't know what it is and how it is used. Therefore, my question. To understand I will look into the actual code.

**Comment by eriohl** [comment]
Ok. I thought you owned this code. Thus the question.

I'll fix so that is works according to option 1. It is fairly trivial and we can address this later if this is not good enough.

One more question @k-rus @alexanderstc: If query processor comes across a record of an unregistered type: Is this record simply filtered from the result or should there be an error? I remember this was an error earlier right?

**Comment by eriohl** [comment]
> One more question @k-rus @alexanderstc: If query processor comes across a record of an unregistered type: Is this record simply filtered from the result or should there be an error? I remember this was an error earlier right?

Never mind. I can see from the code that an error is generated.

**Comment by k-rus** [comment]
> One more question @k-rus @alexanderstc: If query processor comes across a record of an unregistered type: Is this record simply filtered from the result or should there be an error? I remember this was an error earlier right?
> Never mind. I can see from the code that an error is generated still.

Great that you found. @alexanderstc is not involved with old query processor at all. I am involved for bug fixing and enhancements, but the most of the code is written by someone else. Usually I need to look to the code to understand what is happening as you did.

**Comment by eriohl** [comment]
Because the records are not filtered for unregistered types we need to be able to check the filter against records without a registered expected layout as well. So in this case we use the layout of the filter.

However, because of previously mentioned issue with pending updates this might not be completely stable (although generally it is probably pretty safe to assume that a record where type is not registered won't be updated). So we will be address [this](https://github.com/Starcounter/Starcounter/issues/3177) anyway.

**Comment by eriohl** [comment]
Done.
