### ISSUE TITLE
How to trigger a model change event in JS

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3160]
With this code I can access the model in JS

```js
  <script model="{{model}}">
            (function () {
                var scriptElement = document.currentScript;
                var model = scriptElement.model;
                // ...
```

But how can I trigger an model change event?

Related Issue: [How to get a event in JS if some JSON property changes?](#3145)

**Comment by warpech** [comment]
There is no need to trigger a model change event, since PuppetJS observes for changes in the existing viewmodel. You just make a change and it will be observed and sent to server in the next few miliseconds.

Do you have any particular problem with it?

**Comment by miyconst** [comment]
But if you really need to trigger a model change event you can do that as follow:

```html
<template is="dom-bind">
</template>
<script>
    var t = document.currentScript.previousElementSibling;

    //Set a new value for a property
    t.set("model.MyCustomProperty", "MyCustomValue");

    //Notify Polymer about a change inside model without changing actual value
    t.notifyPath("model.MyCustomProperty", "MyCustomValue");
</script>
```

**Comment by miyconst** [comment]
***Note***: This works in Chrome only. Scripts inside `dom-bind` and `dom-if` are not properly executed in FF and IE.

```html
<script model="{{model}}">
```

**Comment by jwillmer** [comment]
With this JSON

```json
{
    "Html": "/ProductsPage.html",
    "Products": [
        {
            "Id":  "",
            "Name$": ""            
        }
    ]
}
```

and this JS

```js
<script model="{{model}}">
            (function () {
                var scriptElement = document.currentScript;
                var model = scriptElement.model;

                model.Products[0].Name$ = 'test';
                // ...
```

the breakpoint in ```HasChanged(TValue property)``` will not be reached.

```csharp
    partial class ProductsPage : Page
    {
        protected override void HasChanged(TValue property)
        {
            base.HasChanged(property);
        }

        // ...
```

**Comment by miyconst** [comment]
>and this JS

Are you sure that this js is executed and executed without errors?
Are there any patches to server about that change?

**Comment by jwillmer** [comment]
In the patch I can see that the value will be send. (I did not mention that this is a partial page if that makes any difference.)

16:18:24.697
```
[{"op":"replace","path":"/_ver#c$","value":1},{"op":"test","path":"/_ver#s","value":0},{"op":"replace","path":"/workspaces/0/PIM/ProductsPage/Products/0/Name$","value":12}]
```

16:18:24.721
```
[{"op":"replace","path":"/_ver#s","value":1},{"op":"test","path":"/_ver#c$","value":1}]
```

**Comment by miyconst** [comment]
Then it is a server side issue, not client side. The client does it job properly, - generates and sends the change patch.

**Comment by per-samuelsson** [comment]
@chrhol, do you have a take on that?

**Comment by jwillmer** [comment]
Have created a [test project](https://github.com/jwillmer/StarcounterModelChangeEventTestProject) to demonstrate the probblem. 
It seams like it is not related to a partial class but to changing properties of objects.

**Comment by warpech** [comment]
Thanks a lot for illustrating the problem! 

Note to @chrhol: any chance of explaining HasChanged on starcounter.io? There is an issue about that: https://github.com/Starcounter/starcounter.io/issues/91

I will take my chance to explain the solution. `HasChanged` method of the `Json` class is only triggered for the changes at the root of the Json.

If you want capture a change in a child subtree, you need to define another partial class for that.

The below code will work:

```cs
using Starcounter;
using Starcounter.Templates;

namespace ModelChangeEventTestProject
{
    partial class Page2 : Page
    {
        protected override void HasChanged(TValue property)
        {
            base.HasChanged(property);
        }
    }

    [Page2_json.Property2]
    partial class Page2Property2 : Page {
        protected override void HasChanged(TValue property) {
            base.HasChanged(property);
        }
    }
}
```

**Comment by per-samuelsson** [comment]
> Have created a [test project](https://github.com/jwillmer/StarcounterModelChangeEventTestProject) to demonstrate the probblem. 

Just wow, @jwillmer. You just set the standard for how to approach issues being reported. Now there is no turning back! :wink: 

Really, thanks a lot. I'm too eager to see the final answer for this.

**Comment by jwillmer** [comment]
@warpech thank you, it works but my example did not cover lists. How do I proceed if I have a list?

```json
"Products": [
        {
            "Id":  "",
            "Name": ""          
        }
    ]
```

**Comment by miyconst** [comment]
You can define `partial` class for lists as well:

```cs
[Page_json.Products]
partial class PageProductItem : Json, IBound<Anything> {
    protected override void HasChanged(TValue property) {
        base.HasChanged(property);
    }
}
```

The `IBound` and `Json` is not required, unless you need it.

**Comment by jwillmer** [comment]
@miyconst I have updated the example (and added a $ to the name) and it works. The only thing that does not work is adding a new object in JS. 

```js
// will not be send as patch
model.Propertys$.push({Name$: "Ne"});
```

**Comment by miyconst** [comment]
This is not supported by Starcounter server. You have to add `model.AddPropertyClick$` value, subscribe to it's change and add the array item on server side.

Starcounter does not support any model changes from client side.
