### ISSUE TITLE
Add _timeoutMinutes automatic json property

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3161]
Right now we have two automatic values in the root json object: `_ver#c$` and `_ver#s`. There should be another one `_timeoutMinutes`. The property should be automatically filled with current session timeout.

Original issue: https://github.com/Starcounter/Starcounter/issues/3084

**Comment by warpech** [comment]
@miyconst is this still needed, given the final solution to https://github.com/Starcounter/Starcounter/issues/3084?

**Comment by miyconst** [comment]
I don't think so. It might be in use later, but not now.
