### ISSUE TITLE
Transaction.Current is null

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3169]
How do I commit the current transaction?
In the code below m_factory will make another call to Db.Transact, creating a nested transaction on another thread. But then when I return to ```Transaction.Current.Commit();``` Current is null. Is that as intended?

```
internal void Execute()
            {
                // Create a light weight transaction. 
                Db.Transact(Commit);
            }

            private void Commit()
            {
                try
                {
                    Result = m_factory();
                    Transaction.Current.Commit();
                    State = Status.Processed;
                }
                catch (Exception ex)
                {
                    s_logger.Error(ex, "Unhandled exception in MQScheduler");
                    State = Status.Failed;
                }
                finally
                {
                    m_done.Set();
                }
            }
```

**Comment by chrhol** [comment]
If you use `Db.Transact()` you don't call commit explicitly, but the transaction is committed automatically when the code leaves the scope. And for the same reason you have to throw an exception and catch it outside the scope if you want to do a rollback or cancel the transaction.

**Comment by careri** [comment]
Yeah, just added some debug code where I noticed Transaction.Current is never set.
Thanks

**Comment by per-samuelsson** [comment]
Seems this one is fully answered.
