### ISSUE TITLE
Question: Overriding synonymousTo

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3171]
What will happen here?
```
public class BaseClass
{
     public Something BaseProperty;
}
public class Class1: BaseClass
{
    [SynonymousTo('BaseProperty')]
     public Somebody Property1;
}

public class Class2: Class1
{
    [SynonymousTo('BaseProperty')]
     public Something Property2;
}
```
(Something is another baseclass and Somebody:Something)

**Comment by per-samuelsson** [comment]
> What will happen here?

All fields (translated to properties) will read/write to/from `BaseClass.BaseProperty`. Is this in line with what you would expect?

**Comment by malx122** [comment]
But lets say I do this:
```
var a = new Class2();
a.Property2 = new Something();
if (a.Property1 == null)
     Alert('My Something is not a Somebody');
```
Or do I get another behavior?

**Comment by per-samuelsson** [comment]
> Or do I get another behavior?

Well, you would get an `InvalidCastException`. Because the `new Something()` is (obv) not a `Somebody`.

Just the same as you would have this in regular C#:

```C#
public class BaseClass {
    public object BaseProperty;
}

public class Class1 : BaseClass {
    public string Property1 {
        get { return (string)BaseProperty; }
        set { BaseProperty = value; }
    }
}

public class Class2 : Class1 {
    public object Property2 {
        get { return BaseProperty; }
        set { BaseProperty = value; }
    }
}
```

and do this:

```C#
var x = new Class2();
x.Property2 = 10;
if (x.Property1 == null) {
    Console.WriteLine("No way");
}
```

**Comment by malx122** [comment]
Ok, good to know! Then it is at least possible to do even if its ugly and you need to avoid using Property1. (The reason of the question is that I want to change some structure in our DB and might be limited by our current data)

**Comment by per-samuelsson** [comment]
I take that as an "question answered". :smile: Let me know if you want us to reopen this.
