### ISSUE TITLE
Question: Forcing a JSON change notification

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#3181]
I have a JSON viewmodel with a notification string that gets displayed using a `paper-toast` element. The notification gets updated periodically, whenever the user should be notified of something. Occasionally, I want to display the same message twice in a row, so as far as the JSON layer is concerned, the value never actually changes.

Is there any way to force a patch to be generated even if the value technically didn't change?

**Comment by miyconst** [comment]
What kind of patch do you want to generate?

Can you create two properties, like `MessageText` and `MessageVisible`? If so, then you can send a change patch for `MessageVisible` property.

**Comment by mtornwall** [comment]
> What kind of patch do you want to generate?

I want to generate a patch that always changes the value of the `NotificationMessage` property, regardless of whether it was "changed" to its current value.

> Can you create two properties, like `MessageText` and `MessageVisible`? If so, then you can send a change patch for `MessageVisible` property.

Right now I'm doing something similar: I'm incrementing a counter that causes the toast to be displayed again.

**Comment by miyconst** [comment]
This is somehow against the algorithm. The change should represent a change in the view-model, but if there were no change, what to represent?

You can set the value to `null` after showing it, then next time the patch will be generated again.

@warpech what do you think?

**Comment by warpech** [comment]
We [don't support nullables in JSON](https://github.com/Starcounter/Starcounter/issues/3144) but very similar pattern is used in [puppet-redirect](https://github.com/PuppetJs/puppet-redirect): After rendering, the client changes the value to `""` (empty string) so that the server can change it again.

**Comment by miyconst** [comment]
@mtornwall is your issue solved?

**Comment by mtornwall** [comment]
@miyconst I have now implemented the solution proposed by @warpech, and it seems to be satisfactory.

My only concern is that this introduces unnecessary coupling between the elements and the server-side viewmodel.

**Comment by miyconst** [comment]
Okay, let's keep it like this for now. I close the issue.

If you would like to discuss the coupling between the element and view-model, then create a new issue, please.
