### ISSUE TITLE
Apps tests is failing on pnext

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3182]
Here is the error:
```
Compilation errors (2):
3LevelSchemaChange.cs(78,32): error CS1061: 'Starcounter.Metadata.RawView' does not contain a definition for 'MaterializedTable' and no extension method 'MaterializedTable' accepting a first argument of type 'Starcounter.Metadata.RawView' could be found (are you missing a using directive or an assembly reference?)
3LevelSchemaChange.cs(78,79): error CS1061: 'Starcounter.Metadata.RawView' does not contain a definition for 'MaterializedTable' and no extension method 'MaterializedTable' accepting a first argument of type 'Starcounter.Metadata.RawView' could be found (are you missing a using directive or an assembly reference?)
```
Build log: https://scbuildserver/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=32670#_focus=8240

**Comment by k-rus** [comment]
@alemoi Is it you added the test from ignored into the build? The build fails now and is showstopper for developers. Can you fix it?

**Comment by alemoi** [comment]
Yes, I added this after it was decided today to add tests that will fail the build: @dan31 @bigwad @linkdata
That was the first one I found failing simply :) Lets discuss this since its quite controversial.

**Comment by dan31** [comment]
@alemoi why are failing tests are showstopper in our case? How it should be adjusted that people still see how much tests failing and not have it as a showstopper, but let them gradually reduce amount of failing tests instead.

**Comment by k-rus** [comment]
This is showstopper for developers, e.g., for @alexanderstc and @chrhol work on schema upgrade.
Please, guys fix the issue. If you want to fix more, there are number of issue in issue tracker. For example, there is disabled code in QueryProcessingTest, which waits to test.

**Comment by k-rus** [comment]
> @alemoi why are failing tests are showstopper in our case? How it should be adjusted that people still see how much tests failing and not have it as a showstopper, but let them gradually reduce amount of failing tests instead.

I marked as showstopper as failing build is a showstopper, Furthermore, there was a request to build artefacts from @per-samuelsson some time ago. The artefacts also will be needed to be able to install and test on non-development machines. And I guess it will be needed quite soon. Note that Artefacts are not built if tests are failing.

Before gradually adding tests, fix #3042.

**Comment by alemoi** [comment]
As decided, I have created a nightly build with failing tests enabled. I will add failing tests gradually there.

**Comment by chrhol** [comment]
I think this issue can be closed. The initial comment is no longer valid (the test compiles and runs), and other tests are up and running on pnext.

There is one issue left with the initial test, 3levelschemachange, but I will create a new issue for that one.
