### ISSUE TITLE
Database browser

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3183]
I think it is a good idea to have a database browser to display all data in the database. I know it could be complicated to archive this with the isolated app concept but for an admin or developer who is searching for a bug in the data that would be supper convenient.

**Comment by miyconst** [comment]
Good idea. Was also requested by me a year ago and by TargetEveryOne guys.

**Comment by per-samuelsson** [comment]
Just to be clear: are we talking about a tool that display the *schema*, or the *data* (in which case it would be both, I guess)?

A schema browser has been requested several times over the years. A data browser I don't recall I've ever heard anything about. Not sure it will be usable (and thats what we should have query langagues for... well, sort of :smile: ).

**Comment by miyconst** [comment]
I think, it should be schema browser with possibility to automatically execute 

```sql
SELECT * FROM Table FETCH 1000
```

On any table.

Also the navigation properties should be clickable.

**Comment by per-samuelsson** [comment]
@miyconst 

Yeah, thats what is usually requested. I've always thought of it as something like [.NET Reflector] (https://www.red-gate.com/products/dotnet-development/reflector/), scoped only to properties/fields targetting the database.

Minus methods and the ability to see the code.

And plus the ability to do those selects, now that you bring that into the mix!

As for implementation, in the history, I've always pictured I'd do this by consuming like the trees I build up in the weaver, or those we construct during binding. 

But like the last year, I'm leaning more on that we make this an acid test of the new metadata. `SELECT * FROM Table`, `SELECT * FROM ClrClass`, `SELECT * FROM Column`, just build it up like that. And we package it up as a general app that anyone can run, with a nice tree view, and supporting partials we can display in the web admin. Voila - now we have a schema browser, another app prefab and a real world test of the metadata we produce. 

Thats three goodies for the price of one!

My favorite developer I would like to see pull it of - you, @miyconst! :sunglasses: :rocket:

**Comment by miyconst** [comment]
@per-samuelsson you described it almost same way I see it. The only one major difference is that I would like to run it in Administrator.

Let's say developer has some issues with his launcher or whatever, which result in not working solution on hist screen. This should not break up debugging tools, and this app is a debugging tool.

Thanks for giving me such privileges. I have similar project to import/export data from Starcounter: https://github.com/miyconst/StarcounterImporter, and I would like to take this one over as well. Not sure about available time though.

**Comment by per-samuelsson** [comment]
By chance, it turns out that @andwah made some kind of mock of this just a few days ago. Still just local on his machine, and not production-ready, but I pointed him here and he'll update here when he get the chance to work on and refine it.

**Comment by andwah** [comment]
For the moment i posted the app "DatabaseEditor" in the appstore under the "smörgåsbord" store.

***Be away it's still an early prototype.***

**Comment by per-samuelsson** [comment]
> For the moment i posted the app "DatabaseEditor" in the appstore under the "smörgåsbord" store.

Great!

You mind open-sourcing it too? Suggest eiher under your personal hub or under `StarcounterSamples` (but you might want to check that with @warpech / @miyconst). I think its one of those tools we can several people involved in eventually.

**Comment by andwah** [comment]
> You mind open-sourcing it too?

Absolutely!. that is my intention!. but i like to get past the "prototype" stage first :-)

**Comment by per-samuelsson** [comment]
> [...] but i like to get past the "prototype" stage first :-)

Stop being shy like that. :sunglasses:

**Comment by miyconst** [comment]
Come on @andwah, publish it on GitHub, so we can all work on it.

**Comment by miyconst** [comment]
Thanks to @andwah the is a new app called `Database Editor`, now available from the App Warehouse. It provides functionality to find a table by name and edit it's data.
