### ISSUE TITLE
QueryResultRows long running?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3190]
Is there anyway of having a long running QueryResultRows. I'm thinking in the terms of having an instance that will find new items in the database. In this example I try to call MoveNext on an instance that might previously have returned false (there were no items at that moment). The reason to reuse the same instance is to keep track of which items have been returned.

It seems like this approach isn't valid, so any suggestions on how to solve the problem?
```
using System;
using Starcounter;
using System.Threading;
using System.Threading.Tasks;
using System.Diagnostics;
using System.Net;

namespace QueryResultRowsIsSmart
{
    class Program
    {
        private static readonly CancellationTokenSource m_source = new CancellationTokenSource();
        private static ManualResetEventSlim m_available = new ManualResetEventSlim(false);

        static void Main()
        {
            Db.DatabaseStopping += Db_DatabaseStopping;
            Console.Write("PID: " + Process.GetCurrentProcess().Id);
            var session = new DbSession();
            session.RunAsync(PrintLogs);

            Handle.POST<Request>("/sandbox/sqltest", (r) =>
                {
                    var msg = r.Body;

                    Db.Transact(() =>
                        {
                            var log = new DummyLog(msg);
                        });
                    m_available.Set();
                    return HttpStatusCode.OK;
                });
        }

        static void Db_DatabaseStopping(object sender, EventArgs e)
        {
            m_source.Cancel();
        }

        private static void PrintLogs()
        {
            // Try to leave the enumerator open and find new items (doesn't work)
            var items = Db.SQL<DummyLog>("SELECT l FROM DummyLog l Order By l.Created").GetEnumerator();
            var waitHandles = new WaitHandle[] { m_available.WaitHandle, m_source.Token.WaitHandle };

            while (!m_source.IsCancellationRequested)
            {
                if (WaitHandle.WaitAny(waitHandles) == 0)
                {
                    while (items.MoveNext())
                    {
                        Debug.WriteLine("Read: {0}", items.Current);
                    }
                    m_available.Reset();
                }
            }
        }
    }

    [Database]
    public class DummyLog
    {
        public readonly DateTime Created;
        public readonly string Message;

        public DummyLog(string msg)
        {
            Created = DateTime.Now;
            Message = msg;
        }

        public override string ToString()
        {
            return string.Format("[{0}] {1}", Created, Message);
        }
    }
}
```

**Comment by per-samuelsson** [comment]
@careri 

What would be the problem just reshooting the query on each pulse? I mean, I doubt what you are trying here is standard behaviour in any kind of platform? (I'm really not an expert, but just guessing).

**Comment by careri** [comment]
Not a problem, the thing is that I than have to loop/filter the query myself to find the last item already processed and return the next one if any.

Would have been simpler (for me, not for you) to just call MoveNext again to see if any new records are available. I understand that this requires the rows to be sorted, and that items added before the last item according to sort would not be returned.

**Comment by per-samuelsson** [comment]
>  [...] the thing is that I than have to loop/filter the query myself to find the last item already processed and return the next one if any.

And 

```C#
Db.SQL<DummyLog>("SELECT l FROM DummyLog l WHERE l.Created > ? Order By l.Created", lastItemProcessed.Created);
```

is no good?

**Comment by careri** [comment]
That's exactly the solution I implemented already. Just would have been simpler/cleaner to reevaluate MoveNext.

Simpler for me that is :)
This solution is fine, just wanted to now if it was possible,

You can close this issue as far as I'm concerned

**Comment by careri** [comment]
Or actually your solution wasn't exactly how I implemented it. I have a unique sort id, your solution might skip over a couple of items if they have the exact same timestamp.

**Comment by per-samuelsson** [comment]
> [...] your solution might skip over a couple of items if they have the exact same timestamp.

Bah! `WHERE l.Created > ?` => `WHERE l.Created >= ?` then? :smile:

OK, so closing this. Let us know if you want to discuss it more and we'll reopen it.
