### ISSUE TITLE
pnext: scdata doesn't respect death of scdblog

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3195]

**Comment by bigwad** [comment]
Keeps running and performing writes.
CC @eriohl

**Comment by eriohl** [comment]
(pnext issue: in previous versions scdata does not send log entries to scdblog).

**Comment by eriohl** [comment]
It will detect it eventually when log buffer fills up. But yes: It should of course detect it as soon as possible (I thought there was an issue for this already).

**Comment by bigwad** [comment]
done
