### ISSUE TITLE
logopt: may leave orphaned temporary files on crash

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3196]

**Comment by eriohl** [comment]
There is also the issue of removing replaced checkpoints. I was planning to put some effort into this when time allows. Maybe we can incorporate cleanup of these files in this (the current idea is that this is to be done on starting log writer and after new checkpoint has been created).

https://github.com/Starcounter/Starcounter/issues/2882

**Comment by bigwad** [comment]
Fixed.
Logopt utility removes orphaned files when running with special option "-clean <dbname> <logpath>".
On_new_log.cmd launches logopt with this option on every run.
