### ISSUE TITLE
Do I need to explicitly include "Html" property?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3200]
Distant related to #3165.

Having this typed JSON:

```json
{
  "Foo": "",
  "Bar": ""
}
```
 and this code-behind

```C#
partial class FooView: Partial, IBound<Foo> {}
```

and returning an instance backed with a template HTML like this

```C#
return new FooView() { Data = new Foo(), Html = "/path/to/template.html" }
```

render a white screen (and no errors).

When I extend the JSON to this

```json
{
  "Html": "",
  "Foo": "",
  "Bar": ""
}
```

the html renders. Thats a bit confusing.

**Comment by miyconst** [comment]
Yes, looks like so, otherwise the response is ignored by html merger. @chrhol should know better.

**Comment by miyconst** [comment]
Just to note, I prefer to set html value in json:

```js
"Html": "/path/to/template.html"
```

**Comment by per-samuelsson** [comment]
> [...] otherwise the response is ignored by html merger.

OK, I really don't understand why. I mean, I *do set* the Html. Just that I do it in code. Or is that some other property then the one generated? Should we consider this a bug?

> Just to note, I prefer to set html value in json:

And I dislike that approach, and prefer the exact opposite, based on my reasoning in #3165. :smile:

**Comment by chrhol** [comment]
This is not a bug. This is how we implemented inheritance for TypedJson.

We wanted to allow codebehind being reused, but that you have to specify explicitly properties of the viewmodel that should be exposed to the client.

It's probably a part which could be enhanced though.

**Comment by miyconst** [comment]
@chrhol thank you for the clarification. For me it sounds fairly reasonable, that we have to specify which properties are available on the client side.

@per-samuelsson I have responded in your issue about the `Html` property.

**Comment by warpech** [comment]
@chrhol - Regarding the problem in the OP, could we throw a warning when setting `Html` value in code if it was not declared in `.json` file?

**Comment by per-samuelsson** [comment]
> For me it sounds fairly reasonable, that we have to specify which properties are available on the client side.

Yes, thats a sound and good decision. I think that too. But it's for sure confusing when you can assign `Html` and it does not render. So the problem here is not a general one, but one very specifc, relating to only that property.

> @per-samuelsson I have responded in your issue about the Html property.

I noticed that. Thanks!

**Comment by Starcounter-Jack** [comment]
The merger should be moved from the view model to a separate HTML provision layer. See #3165

**Comment by per-samuelsson** [comment]
> $:{inherit:"Product"},

Is this something that actually work? How does it relate/compare to "Reuse"? I havent seen it documented anywhere?

@chrhol?

**Comment by per-samuelsson** [comment]
> @chrhol?

Found [this comment](https://github.com/Starcounter/Starcounter/issues/2059#issuecomment-53392122) that I guess explains it and where we are at.

**Comment by chrhol** [comment]
> > $:{inherit:"Product"},
> Is this something that actually work? How does it relate/compare to "Reuse"? I havent seen it documented anywhere?

> @chrhol?

The keyword `inherit` cannot be set in json-by-example as the example above show, but you can just specify inheritance on code-behind and it will work.

`Reuse` is not the same thing. We really need to have this discussion concerning metadata and how we specify it.

**Comment by chrhol** [comment]
> Found this comment that I guess explains it and where we are at.

Hmm, I think that I might not have been correct in that comment. Reuse and inheritance is not the same thing.

**Comment by per-samuelsson** [comment]
Thanks for the input, @chrhol.

> The keyword `inherit` cannot be set in json-by-example as the example above show.

The it's not really good we write such examples, that will only confuse our users. We should remember this is the public tracker, and people will try the stuff we write here. I'll add a disclaimer to that comment then.

> `Reuse` is not the same thing. We really need to have this discussion concerning metadata and how we specify it. [...] Reuse and inheritance is not the same thing.

Let's try to document both, to get a better feeling of what we *do have*, and then take it from there when we start those discussions then. I'll update the issue that I've created earlier about documenting "Reuse" to include inheritance too.

> [...] but you can just specify inheritance on code-behind and it will work.

And the way to do that is this?

**Sex.json**
```json
{
  "Id": "Male or Female"
}
```

**Female.json**
```json
{
}
```

```C#
partial class Sex : Json {
}
partial class Female : Sex {
}
```

**Comment by chrhol** [comment]
> And the way to do that is this?

Yes, but remember that you have to explicitly add all properties you want to expose in `Female.json`

```javascript
{
   "Id": "Female"
}
```

**Comment by per-samuelsson** [comment]
> Yes, but remember that you have to explicitly add all properties you want to expose in `Female.json`

Ah, great. Thanks for clarifying that! Good catch.

**Comment by per-samuelsson** [comment]
Closing this, as suggested in #3443, since it's pretty much answered.
