### ISSUE TITLE
Scope nesting question

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3203]
I have a long running method (create object) with a Db.Scope and inside I have a Db.Transact. Why does the object inside of Db.Transact got saved regardless of Transaction.Commit? I thought I can have sub scopes and they are only submitted if the parent is.

**Comment by per-samuelsson** [comment]
@jwillmer 

Thanks for taking the time creating this issue!

Lets try get simple-as-possible code to discuss around. Is this what you do?

```C#
Db.Scope(() => {
  Db.Transact(() => {
    new Foo();
  });
  throw new Exception("This scope blew up");
});
```

And you expect `new Foo()` not to be stored, but the actual result is that it *is* being stored?

We have some content about transactions in general, [here](http://starcounter.io/guides/transactions/more-on-transactions/) and [here](http://starcounter.io/guides/transactions/long-running-transactions/), including sections on nesting them, but I cant find any example mixing `Db.Scope()` and `Db.Transact()`. We might need to improve on that.

**Comment by per-samuelsson** [comment]
I made a sample snippet, testing a few simple cases:

```C#
try {
    Db.Scope(() => {
        Db.Transact(() => { new Foo(); });
        throw new Exception("This scope fails");
    });

} catch (Exception e) {
    Console.WriteLine(e.Message);
}
int count = Db.SQL<Foo>("SELECT f FROM Foo f").Count();
Console.WriteLine("{0}", count);

try {
    Db.Transact(() => {
        Db.Transact(() => { new Foo(); });
        throw new Exception("This transaction fails");
    });

} catch (Exception e) {
    Console.WriteLine(e.Message);
}
count = Db.SQL<Foo>("SELECT f FROM Foo f").Count();
Console.WriteLine("{0}", count);

try {
    Db.Transact(() => {
        Db.Transact(() => { new Foo(); });
    });

} catch (Exception e) {
    Console.WriteLine(e.Message);
}
count = Db.SQL<Foo>("SELECT f FROM Foo f").Count();
Console.WriteLine("{0}", count);
```

Running that on an empty database gives:

>This scope fails
>1
>This transaction fails
>1
>2

I guess you would expect 0, 1, 2, @jwillmer? (I kind of would, but I'm not fully read up on using `Db.Scope`).

**Comment by jwillmer** [comment]
In this example I would expect that I do not get another instance of Foo because I have not added ```this.Transaction.Commit()```. I thought I needed to actively commit or abort the transaction in a long running transaction.

```csharp
Db.Scope(() => {
  Db.Transact(() => {
    new Foo();
  });
});
```

**Comment by Starcounter-Jack** [comment]
Scope() and Transact() work differently. They do not interact. The Db.Transact call will execute an independent transaction. 

Scopes are created, attached to a view model and explicitly closed. A scope is never closed automatically. Scopes are used to allow database classes to act as storage for view models. This is powerful as multiple apps can share scope and as domain logic is respected both for UI and database. Please examine InvoiceDemo to see how this is useful. Any viewmodel created inside the same outer scope delegate will share the same scope.  See InvoiceDemo to learn how scopes are commited (form save) or aborted (form cancel).

Transactions are closed when they exit their delegate. If transactions are nested, only the outermost will commit.

**Comment by Starcounter-Jack** [comment]
In short, Scopes only relate to creation of view models. Any viewmodels created under the same scope will be sharing the same database transactional scope.

On another note, View models should always bind to database objects. Unlike non RAM databases, forms should not have a copy of the data. Again, investigate the invoice demo carefully and you willl see how domain logic is respected in the viewmodels (total calculation for example). 

The most important reason to have view model state (InvoicePage) reflect domain model (Invoice/InvoiceItem) state is that it is vital for "mixing and blending" many apps in the same form.

Have you seen the barcode app and product app example?

**Comment by jwillmer** [comment]
O.K., thank you for your example. Now I get it :-)
