### ISSUE TITLE
pnext: ClrClass table is empty

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3204]
The ```Starcounter.Metadata.ClrClass``` is empty even if there is loaded ```classes```

**Comment by bigwad** [comment]
Perhaps, we may get rid of this table? As I see this table makes sense only if there are some clients outside of codehost to query this table. I'm not aware of such clients in pnext.

On top of it, this table is to be wiped out on code host restart. Right? So it imposes unnecessary load on database as we don't have concept of temporary tables.

**Comment by k-rus** [comment]
I guess the code was disabled to connect Level1 with pnext Level0 and is marked as TODO. So this is part of the on-going work on brining pnext to develop.

`ClrClass` and related classes already contain some information unavailable in `RawView`and will be necessary in future. Furthermore, there is a big chance that difference between names of the tables and names of runtime classes will diverge in the future.
Meta-data about runtime metadata will need to live in future for new query processor to work correctly. I believe the schema of them will be changed.

**Comment by k-rus** [comment]
I found the problem, generated CLR classes for meta-tables do not set `SetSpecifier` property for inserted records. I will investigate how to fix it.

**Comment by k-rus** [comment]
`ClrClass` is populated now for all database classes, user defined and meta. However, `MappedProperty` are not fully populated.

**Comment by k-rus** [comment]
Fixing population of `MappedProperty` will enable tests in the query processing test and the 3 level schema change test.

**Comment by k-rus** [comment]
`MappedProperty` is also populated.
