### ISSUE TITLE
Question: How starcounter is with multi-threading

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3205]
I have a project where i have to run 20,000+ threads simultaneously. and each thread will go to a webpage. Now my question is that 
1. Is Starcounter good in handling this much of threads load? 
2. How can i keep track of Thread crashes? (so i can relaunch the thread)
3. Is AWS Server good for this sort of Starcounter project? (In terms of performance)

**Comment by per-samuelsson** [comment]
@atifsheikh 

I'm not the best suited person to answer this, but I think a very general answer is that Starcounter is at least not optimized for this particular case. But lets see if others could provide better answers.

Out of curiosity, care to explain why you have to run that many threads? :smile: Just context switching will take quite some time doing that, won't it?

/cc @eriohl @Starcounter-Jack @linkdata @dan31

**Comment by atifsheikh** [comment]
I have to crawl 20,000 websites simultaneously, and then store the crawled data in DB. 
So my question is that lets say Starcounter is not good in multithreading, What option do i have to run 20,000 processes at the same time?

**Comment by per-samuelsson** [comment]
@atifsheikh 

Thanks for clarifying. Let's see what the experts have to say about it. :smile:

**Comment by linkdata** [comment]
There is no point in running more threads than you have cores if you're only using them to store state of individual web crawls. You should run them [concurrently](http://stackoverflow.com/questions/1897993/difference-between-concurrent-programming-and-parallel-programming) to be sure, but not all in parallel. [There are specialized frameworks for this](https://www.google.se/search?q=web%20crawler%20framework&rct=j), you might start by looking at them. Once you have data being produced in an efficient way, you can store and process it in Starcounter using handlers.
