### ISSUE TITLE
How to get the admin server port from within my app?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3206]
My app is running inside the code host. How can I retreive the admin server port?

```C#
class Program {
  static void Main() {
    Console.WriteLine("Hello, I'm {0} inside {1}.", Application.Current.Name, Db.Environment.DatabaseNameLower);
    Console.WriteLine("The admin server port is {0}", "...?");
  }
}
```

/cc @alemoi? @andwah?

**Comment by alemoi** [comment]
Another good question. Here you go: `StarcounterEnvironment.Default.SystemHttpPort`

**Comment by per-samuelsson** [comment]
> Here you go: `StarcounterEnvironment.Default.SystemHttpPort`

Great. Thanks. I have verified it works, and now we have this documented when someone else ask that same question! :sunglasses:
