### ISSUE TITLE
How to get the version from within my app?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3207]
Hello!

My app is running inside the code host. How can I retreive the installed *version* of Starcounter?

```C#
class Program {
  static void Main() {
    Console.WriteLine("Hello, I'm {0} inside {1}.", Application.Current.Name, Db.Environment.DatabaseNameLower);
    Console.WriteLine("The Starcounter version is {0}", "...?");
  }
}
```

/cc @alemoi? @andwah?

**Comment by alemoi** [comment]
Good question. Here you go: `Starcounter.Internal.CurrentVersion.Version`

**Comment by per-samuelsson** [comment]
> Here you go: `Starcounter.Internal.CurrentVersion.Version`

Great. Thanks. I have verified it works, and now we have this documented when someone else ask that same question! :sunflower::
