### ISSUE TITLE
WebSocketDisconnected event

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3211]
I've got a working websocket that I write/read from using a c# client app. 
If  I call (System.Net.WebSockets.ClientWebSocket).CloseAsync on the client the event is triggered as expected.

A few questions about the disconnected event:
1. But what if the client just dies, will that event ever be triggered? 
2. Is there a timeout that will trigger the event?
3. Do I need to implement a heartbeat to monitor the ws myself?

The event:
```
Handle.WebSocketDisconnect(s_port, UL_ChannelName, ws =>
{
    var cargoId = ws.ToUInt64();
    Debug.WriteLine("Server.ws{0}.Disconnected", cargoId);
});
```

**Comment by dan31** [comment]
@alemoi, after answering please populate the docs there http://starcounter.io/guides/network/websockets/, thanks in advance!

**Comment by alemoi** [comment]
Thank you for your questions!

> 1. But what if the client just dies, will that event ever be triggered? 

Yes, if connection socket dies, then you will get a disconnect event.

> 2. Is there a timeout that will trigger the event?

No. Its for the lifetime of the socket.

> 3. Do I need to implement a heartbeat to monitor the ws myself?

Yes. For example, we have such custom implementation in Puppets: https://github.com/Starcounter/Starcounter/issues/3084

Let us know if anything regarding disconnect event is not working for you.
