### ISSUE TITLE
stari_context_get_index_infos_by_setspec() doesn't find "parent" setspec's index

### ISSUE THREAD

**Issue by alexanderstc** [Starcounter/Starcounter#3216]
Create base and child table, create an index on the parent, call stari_context_get_index_infos_by_setspec() on the child, returns no index infos.

I assume should return info on the parent index.

Please try branch alexander-bug-index-by-setspec,
see src/tests/metalayer_functest/metalayer_functest.cpp lines 454, 457.

**Comment by eriohl** [comment]
Assuming there are two indexes:

A on ~a~a~
B on ~a~a~b~

Query on ~a~ gets index A and B. Query on ~a~a~ gets A and B. Query on ~a~a~b~ gets only B.

It doesn't work this way?

**Comment by alexanderstc** [comment]
It does in this case. That means this bug report is false.


However, I think in other cases, when I search by child setspec, it returns info for "base" indices.

I'll try to make another example then.


________________________________

**Comment by eriohl** [comment]
I figured that I needed to check that because is didn't seem correct. And it isn't.

How is it supposed to work is that if there is an index on A on ~a~ and query is on ~a~b~ then index A is to be included in the output. If it isn't this is incorrect.

But I think I know what the problem is....

**Comment by eriohl** [comment]
Actually it is not entirely well defined how it is supposed to work. But this is how I think it should work.

**Comment by eriohl** [comment]
Ok. Should work better now.
