### ISSUE TITLE
Question: How can I create a "SELECT DISTINCT " query in starcounter?

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3218]
I want to make a query on a table which have only 1 column "Name". Now i dont want to select duplicate Names, how can i achieve that in Starcounter?

**Comment by miyconst** [comment]
```sql
var names = Db.SQL<T>("SELECT t FROM T").Select(x => x.Name).Distinct();
```

**Comment by miyconst** [comment]
```sql
var names = Db.SQL<string>("SELECT t.Name FROM T GROUP BY t.Name");
```

**Comment by miyconst** [comment]
Here are two solutions. The first one works slightly faster.

**Comment by atifsheikh** [comment]
Thank you for replying @miyconst.
Just one more thing, Is the following syntax supported in Starcounter Version 2.0.3226 ? 
var names = Db.SQL<T>("SELECT t FROM T").Select(x => x.Name).Distinct();

**Comment by miyconst** [comment]
```cs
var names = Db.SQL("SELECT t FROM T").Select(x => x.Name).Distinct();
```

Does not work, you have to select a specific type:

```cs
var names = Db.SQL<T>("SELECT t FROM T").Select(x => x.Name).Distinct();
```

And this is `.net` part, not Starcounter.

```cs
.Select(x => x.Name).Distinct();
```

**Comment by atifsheikh** [comment]
@miyconst Any idea why am i getting this error? i know its not a starcounter specific error, but any sort of help or suggestion will be really appreciated. :) 

![error](https://cloud.githubusercontent.com/assets/4388707/11976622/3c4902c2-a97a-11e5-9b2c-e4a3410a3fc3.jpg)

**Comment by bigwad** [comment]
Probably, you've missed 
```
using System.Linq;
```

**Comment by atifsheikh** [comment]
:+1: @bigwad Thank a lot guys :)

**Comment by miyconst** [comment]
Just to note, the returned type will be `IEnumerable<string>`, not `QueryResultRow<ExternalFeature>`.

Please close the issue if your question was answered.

**Comment by atifsheikh** [comment]
One last thing, how can make the return type IEnumerable<ExternalFeature> instead of IEnumerable<string> ?

**Comment by miyconst** [comment]
Hm, this is not logical for me.

If you have two or more features with same `Name`, they still have different `Id`. Which of the objects you want to select?

**Comment by atifsheikh** [comment]
I want to return the entire object, but with distinct applied on Name column only.

**Comment by miyconst** [comment]
So, which object you want to return?

You can do like this to return the first object of a group:

```cs
IEnumerable<ExternalFeature> features= Db.SQL<ExternalFeature>("SELECT ef FROM ExternalFeature ef").GroupBy(x => x.Name).Select(x => x.First());
```

**Comment by atifsheikh** [comment]
Perfect. this works fine :+1: 
Thank you @miyconst
