### ISSUE TITLE
Question: How to populate Launcher's Header menu?

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3221]
Attached is an image to explain my question. Please attach the url, If there is some documentation to achieve this result.

![launcher](https://cloud.githubusercontent.com/assets/4388707/12089390/8cff3600-b2e4-11e5-813f-29283a1d8897.jpg)

**Comment by atifsheikh** [comment]
Also how can i use a different URL behind Home button. Currently when i click on Home button, i land on Url : http://localhost:8585/launcher, but i want to land to Url : http://localhost:8585/adfenix/master

**Comment by miyconst** [comment]
Current Launcher does not have the top menu section. You can:

- Use css styles to place your menu over the launcher's menu.
- Fork the Launcher and add another section for the top menu.

For the home url, you can use url aliases to rewrite `/launcher` to `/adfenix/master`, or you can fork launcher and replace the home url in the code.

**Comment by atifsheikh** [comment]
Thats the solution i was thinking, but what happens when I have to upgrade Starcounter DB version along with Launcher, UserAdmin & SignIn app?
do you guys keep updating code in Launcher, UserAdmin & SignIn apps?

**Comment by miyconst** [comment]
We always try to keep our sample apps up to date and compatible with the latest Starcounter version.

**Comment by atifsheikh** [comment]
Ok nice, so think i'll fork the Launcher code and modify it as my requirements. Thanks :+1:
