### ISSUE TITLE
The application could not be resolved based on the given arguments or context

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3223]
Unable to access `Starcounter.Application.Current` inside `AsMimeType` method of `Page` class.

I am trying to make my own `Page` class which inherits `Starcounter.Page` and overrides the `AsMimeType` method.

In the method I try to access `Starcounter.Application.Current` which results in the following exception:

```
System.InvalidOperationException: ScErrApplicationCantBeResolved (SCERR4264): The application could not be resolved based on the given arguments or context.
Version: 2.1.944.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4264.
   at Starcounter.Application.get_Current() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Starcounter\Application.cs:line 146
   at StarcounterRazor.RazorPage.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in F:\StarcounterRazor\StarcounterRazor\RazorPage.cs:line 27
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Starcounter.Internal\Http\Response.cs:line 830
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Starcounter.Internal\Http\Request.cs:line 1243
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 569
HResult=-2146233079
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4264

More information about this error may be available in the server error log.
```

cc @alemoi, @chrhol

**Comment by alemoi** [comment]
I guess its something with Json. @chrhol what do you think?

**Comment by chrhol** [comment]
Not directly related to Json I think. The `AsMimeType` method comes from an interface, `IResource`.

The method is called when the response is sent (in `Response.ConstructFromFields`) and is not wrapped with the appname.

I'm not sure how the correct appname can be retrieved. We only have access to the response and the `IResource` object when the response is sent, not the `Json` object (due to dependencies).

**Comment by alemoi** [comment]
I checked by setting appname at the time when `Response.ConstructFromFields` is called, and there are other problems related to this when mixing several apps responses.

**Comment by miyconst** [comment]
I have also tried to access the `Starcounter.Application.Current` directly from the `Main` method - same result.

**Comment by alemoi** [comment]
Hmm, so you can access `StarcounterEnvironment.AppName` but not `Starcounter.Application.Current`?

**Comment by miyconst** [comment]
`StarcounterEnvironment.AppName` I didn't check this value, but can do that if needed.

**Comment by miyconst** [comment]
Anything on this issue?

**Comment by alemoi** [comment]
I will try to reproduce the issue with accessing `Starcounter.Application.Current` directly from the Main method first.

**Comment by alemoi** [comment]
When I execute the following code, `app` receives correct value.
```c#
static void Main(String[] args)
{
    Debugger.Launch();
    Application app = Starcounter.Application.Current;
}
```

@miyconst can you please post the failing code. And original issue code here, so I can debug the thing. Thank you!

**Comment by miyconst** [comment]
@alemoi I don't know what happened, but the `Starcounter.Application.Current` value is available in `Main` function now. I tried to test a couple more times, but it works :confused:.

In the `AsMimeType` it still does not work. I am working on a demo project: 
https://github.com/miyconst/StarcounterRazor

To reproduce the exception you have to uncomment those lines:
https://github.com/miyconst/StarcounterRazor/blob/master/StarcounterRazor/RazorPage.cs#L19, start project, open it in browser.

You also have to set working and resource directories to `wwwroot` to make it work without those lines.

**Comment by miyconst** [comment]
Closing the issue as partially fixed and too old.
