### ISSUE TITLE
pnext: missing files in installer.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3231]
I'm trying to add all files that are currently missing in the installer for pnext version. I've found the following differences between my local environment and an installed version. Some are quite clearly needed, but other I'm not sure about. 

These I'm currently adding to the whitelist to be able to start database and apps:
- loader.dll
- scdbmetalayer.dll
- TurboText_x-tid_3.dll

These ones are not needed to run (for my apps), but maybe some of them should be included:
- behemothrcc.exe
- dbhistory.exe
- fssmap.exe
- logopt.exe
- perfmon.exe
- temptt.dll

Have I missed anything and which of the ones in the second list should be included? Also I have a bunch of `.lib` files but I guess none of these are needed other for building Level1.

/cc @eriohl,  @linkdata, @k-rus, @alexanderstc, @bigwad

**Comment by chrhol** [comment]
The first section is added to whitelist and pushed to pnext branch. Will add any other when I know which ones.

**Comment by eriohl** [comment]
logopt.exe should be include as well.

**Comment by chrhol** [comment]
> logopt.exe should be include as well.

added.

**Comment by chrhol** [comment]
Looks like all needed files are included (at least for the time being). I will close this issue.
