### ISSUE TITLE
DbSession dos and don'ts

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3234]
I'm not quite sure how to use DbSession. Can I have a singleton instance to be shared by multiple threads?
If I can have a singleton instance, I guess that using RunAsync is safe. But what about calling RunSync from multiple threads.
Is it lightweight?

It seems to be that DbSession is a factory for producing tasks to put on a scheduler. So my guess is that it's safe to have a singleton instance shared between threads?

**Comment by alemoi** [comment]
Yes, its a singleton and safe to be used. I will create a new API soon with static methods.

**Comment by alemoi** [comment]
An updated scheduling API: http://starcounter.io/guides/transactions/running-background-jobs/#basic-information-about-scheduling-in-starcounter
