### ISSUE TITLE
Question : How to make redirect work.

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3235]
In SC version 2.0.3226.3 i was using the following code to redirect to a url :
void Handle(Input.Redirect action)
        {
            this.RedirectUrl = "/adfenix/campaign/new/view/all";
        }

I have upgraded my SC version 2.0.3226.3 to 2.1.177, and the same code is not working, however if i search this variable my SC Debugger i find 2 variables as shown in the attached image, and updating the URL in "menu.UserAdmin.RedirectUrl" redirects my page. 

So my question is, how can i update variable "menu.UserAdmin.RedirectUrl" from my code behind json?
![image](https://cloud.githubusercontent.com/assets/4388707/12236253/f27caadc-b878-11e5-91ad-44c053286f3a.png)

**Comment by miyconst** [comment]
@atifsheikh do you fully understand how the redirect works on client side?

The `RedirectUrl` in the menu object belongs to `UserAdmin` app, and it is not correct to use some app's model to do your staff.

You need your own property and your own `puppet-redirect` to make the redirection work.

**Comment by atifsheikh** [comment]
@miyconst No i dont fully understand how the redirect works on client side. i just checked the existing code. 
can you please suggest me any documentation where i can understand this puppet-redirect?

**Comment by miyconst** [comment]
Surprisingly the `puppet-redirect` readme is the best tutorial :)
https://github.com/PuppetJs/puppet-redirect

**Comment by atifsheikh** [comment]
:+1: Great. Thanks @miyconst :)
