### ISSUE TITLE
Add comments about /gw/updateconf to scnetworkgateway.xml

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3239]
The `/gw/updateconf` feature described in here: http://starcounter.io/guides/network/networkgateway/ is used so rare that I forget the exact to url when I have to use it again.

Could we:

- [x] Add a comment with a link to the info page and an example of usage to the scnetworkgateway.xml itself?
- [x] Rename or add alias `/gw/updateconfig` as it is easier to remember.

@alemoi, @warpech, what do you think?

**Comment by miyconst** [comment]
@alemoi please add the comment line, should be easy to do.

**Comment by alemoi** [comment]
Added explanation of the examples, links in config and added alias for `/gw/updateconfig`

**Comment by miyconst** [comment]
Thanks @alemoi.
