### ISSUE TITLE
Json instance to JsonString

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3245]
A picture says more than...
![json_exception](https://cloud.githubusercontent.com/assets/4263597/12294434/b7710ebe-b9fa-11e5-9b99-3db86da767c8.PNG)

**Comment by careri** [comment]
I think I figured it out, I had a property that returned a linq query which resulted in new instances each time the property was queried. I changed it so that the query result is cached and returned.
This was the original property that yielded new instances for each call
```
public IEnumerable<LogGroupMessage> Messages { get { return (IEnumerable<Tuple<long, string, DateTime>>)m_group).Select(t => new LogGroupMessage(t.Item2, t.Item3)); } }
```

**Comment by chrhol** [comment]
Alright, good that you found a way to avoid it. I will take a look why you got the exception though, should not happen.
