### ISSUE TITLE
Glyphicons don't work

### ISSUE THREAD

**Issue by diliger** [Starcounter/Starcounter#3247]
In the tutorial i read that any glyphicon can be used:

> Launcher loads Bootswatch Paper styles and Glyphicons icons, so you can choose any menu icon from the glyphicon collection.

So I try to use **glyphicons-vector-path-line** but my icon doesn't appears on the page:
![glyphicon line](https://cloud.githubusercontent.com/assets/15857369/12299014/ed0239e2-ba25-11e5-9d14-e06c866fe41d.png)

![no glyphicon](https://cloud.githubusercontent.com/assets/15857369/12299055/19e91f98-ba26-11e5-8da7-f524399b0fa0.png)

cc @miyconst

**Comment by miyconst** [comment]
Thanks for reporting this, looks like we have to update the `glyphicons` in the `/sys/` folder.

**Comment by miyconst** [comment]
The tutorial has a partially wrong statement.

You can use only icons from *bootstrap* [glyphicon collection](http://getbootstrap.com/components/#glyphicons-glyphs), but not from entire set of the glyphicons.

The tutorials are fixed now. Please choose one of the available icons.
