### ISSUE TITLE
pnext: broken database and no informative logentries

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3255]
After running some tests locally my default database stopped working. It's no longer possible to start it (only the database, no applications) and the only error that is reported and logged is this one:

```
Starcounter.DbException: ScErrDataManagerUnavailable (SCERR4293): Failed to connect to data manager is unavailable. Occurs when data manager is not started or not yet properly initialized.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4293.
   at StarcounterInternal.Bootstrap.Control.ConnectDatabase(UInt32 instanceId, UInt32 schedulerCount, UInt64 hlogs) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.Bootstrap\Control.cs:line 526
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.Bootstrap\Control.cs:line 235
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
ErrorCode=4293
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4293
```

It's reproducible every time. 

A copy of my repo is available on dropbox (`Exchange\Christian.Holmstrand\broken_db.zip`). I will try to attach a debugger and see if I can find anything more.

**Comment by chrhol** [comment]
Oh, forgot to add: deleting it and using a fresh database works fine!

**Comment by chrhol** [comment]
I found this in eventlog:

```
Faulting application name: scdata.exe, version: 0.0.0.0, time stamp: 0x5698b001
Faulting module name: loader.dll, version: 0.0.0.0, time stamp: 0x5698afea
Exception code: 0xc0000005
Fault offset: 0x000000000000d63f
Faulting process id: 0xa1c8
Faulting application start time: 0x01d14f8247e66f04
Faulting application path: D:\Code\Starcounter\PNEXT\Level1\bin\Debug\scdata.exe
Faulting module path: D:\Code\Starcounter\PNEXT\Level1\bin\Debug\loader.dll
Report Id: 7acbf367-f7cc-45b5-99ce-c835fe12375a
Faulting package full name: 
Faulting package-relative application ID: 
```

@eriohl: can you take a look?

**Comment by eriohl** [comment]
The application has managed to write a log entry with an update to a reference value with size 0, which is  kind of unexpected according to the recovery.

Could I get some instructions on how to run the code that created the bad log entry?

**Comment by chrhol** [comment]
> Could I get some instructions on how to run the code that created the bad log entry?

I was running and debugging the `Tunity.CRM` app several times. Not really sure exactly what happened, but I killed the processes in an unfriendly way more then once to start the debugging from the beginning.

I can try and see if I can reproduct it on a clean database.

**Comment by chrhol** [comment]
I've been able to reproduce it by simply starting and killing all processes over and over.

There is a zip-file with the app on dropbox, same place as before (`CRM.zip`).

Simply start the app (there is a bat file that can be used) and after it's sucessfully started kill all processes (with `staradmin kill all` for example) and then repeat. After a few times the error occurs.

It doesn't seem to happen if I just restart the app without killing the processes first.

**Comment by eriohl** [comment]
Need some SocietyObjects assemblies as well (weaver is missing SocietyObjects.Concepts.Ring1.dll as far as it gets). Where can I find these?

**Comment by chrhol** [comment]
> Need some SocietyObjects assemblies as well (weaver is missing SocietyObjects.Concepts.Ring1.dll as far as it gets). Where can I find these?

Ahh, right. These are included when you install starcounter so I always forget them. I have copied them to the zip.

**Comment by eriohl** [comment]
Ok. I assumed this should come from the installer but when installing from a downloaded installer I still didn't get the binaries... But no matter. I can reproduce the problem. Working on trying to figure out what goes wrong.

**Comment by eriohl** [comment]
Resolved. Was a fix in recovery when setting default value in reference column that caused the problem.
