### ISSUE TITLE
pnext: loader reopens log file for every log entry

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3257]
logreader class may reopen log file many times (presumably for every log entry). It affects db loading and logreader component.

**Comment by eriohl** [comment]
I think you might have misunderstood this. I double checked this and, unless you are doing something very different from what I'm doing (running recovery), log reader opens each log element file only once during load.

**Comment by bigwad** [comment]
Have you tried to load database from log with more than one log file? I noticed this problem with all log files except the first one.

**Comment by eriohl** [comment]
You are right. There is something that isn't working properly.

**Comment by eriohl** [comment]
Problem is that file_.elem_index isn't updated when opening a new file (so reader always things it is file 0 that is open and thus closed and opens a new one for every read). Fix pending.

**Comment by eriohl** [comment]
Fixed.
