### ISSUE TITLE
Create a <table> alternative to juicy-tile-grid

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Starcounter#3258]
As an alternative approach to https://github.com/Starcounter/Starcounter/issues/3238 for [browser support of `<juicy-tile-grid>`](https://github.com/Juicy/juicy-tile-grid/issues/29)

It seems that even though flex box layout is now widely supported, and gives lots of flexibility to applying responsive layouts, it's hard to mimic grid-like 2d behavior to single dimensional flexbox.

I thought, that we could use another CSS property/ HTMLElement, that is supported even wider, and for sure is more stable, which definitely is more suitable for gridlike display: `display: table;`/`<table> ;)

Pros:
- `table` is already grid-like,
- super stable and cross-platform
- with ShadowDom distribution could give us same flexibility to span over rows/cols, make tracks(colmuns/rows) or items flexible, fixed, resizable etc.
- Feels like getting 16yrs younger, let's go back to the 90s :sunglasses: 

Cons:
- we would need to create ShadowDOM containers for rows - flexbox would need it as well.

**Comment by miyconst** [comment]
@tomalec I thought and even tried to make something like this.

The `colspan` and `rowspan` is not supported on

```html
<div style="display: table-cell"></div>
```

This is what stopped me. If you can find an alternative for this, then I really vote up for the idea!

**Comment by tomalec** [comment]
I hope for `<td>` in shadow dom :)

**Comment by warpech** [comment]
@tomalec if you get bugged by the default auto column resizing in `<td>`, you can check out the CSS `table-layout: fixed` property.

https://css-tricks.com/fixing-tables-long-strings/

It is used in Handsontable

**Comment by tomalec** [comment]
Thanks :)

**Comment by miyconst** [comment]
>I hope for `<td>` in shadow dom :)

So.. you are actually going to generate `<table>` layout in Shadow DOM?

**Comment by tomalec** [comment]
yes
