### ISSUE TITLE
Minimum cermony HTML bound to view model?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3259]
Having this

```json
{
  "Html": "/test.html",
  "Name": "Per"
}
```

and this,

```cs
partial class Test : Page
```

whats the minimum required in `test.html` with a body like this

```html
<body>
    <p>{{model.Name}}</p>
</body>
```
returned like this

```cs
Handle.GET("/test", () => {
  return new Test();
});
```

to have **Per** rendered in the browser?

Read-only display is fine, i.e no patching, and preferably something a little less than what is suggested [here](http://starcounter.io/tutorials/1-introduction-to-part-1/1-5-render-json-in-html/#displaying-json-in-html).

**Comment by per-samuelsson** [comment]
Basically, what I want is to have the built-in template engine to just replace that single mustache for me, not bothering with sessions, patching, styling, whatever.

**Comment by warpech** [comment]
In order to use the templating engine that we use in apps (Polymer), you need to use PuppetJS (which itself requires session and includes patches support) that loads the view-model and binds it to a JS object.

The minimum HTML becomes:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Per's app</title>
    <script src="/sys/webcomponentsjs/webcomponents.js"></script>
    <link rel="import" href="/sys/polymer/polymer.html">
    <link rel="import" href="/sys/starcounter.html"><!-- includes PuppetJS and json-patch -->
</head>
<body>
    <template is="dom-bind" id="puppet-root">
      <p>{{model.Per}}</p>
    </template>
    <puppet-client ref="puppet-root"></puppet-client>
</body>
</html>"
```

Which is not very different to https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/Partial.cs

**Comment by per-samuelsson** [comment]
Thanks @warpech, I actually almost nailed it by just playing around, but couldn't get it to work because I missed including `<puppet-client ref="puppet-root"></puppet-client>`.

**Comment by per-samuelsson** [comment]
This one is clearly answered.
