### ISSUE TITLE
pnext: Building Starcounter ("Level1.sln") without access to Bluestar

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3261]
In 2.x, I can clone the Starcounter repo, checkout `develop` and build `Level1.sln` only having access to the network for the build system to fetch the Bluestar bits for me.

If I try the same with **pnext**, I experience a myriad of errors. 

Starting to diagnose it, I noticed one of the first was that `GenerateMetadataClasses.exe` build tool couldn't find `\PNext\Level1\bin\Debug\metaschema.json`.

Should it not be possible to build **pnxt** `Level1.sln` without having to go through the entire ceremony of building Bluestar?

**Comment by per-samuelsson** [comment]
Bump.

I'm thinking it would be good not to have a source-code requirement on Bluestar once we go and promote **pnext** further (I don't really know when that is scheduled though, so this might not be a high prio concern).

**Comment by alemoi** [comment]
@per-samuelsson lets discuss this in the office.

**Comment by dan31** [comment]
@alemoi Today we guesstimated with @k-rus and @chrhol that the problem
should be the ftp deployment mechanism is broken for level0 tarball. Maybe
the reason being are your recent deeds on teamcity. The goal is really to
fix pnext so that the issue works as in develop.

**Comment by per-samuelsson** [comment]
> Today we guesstimated with @k-rus and @chrhol that the problem should be the ftp deployment mechanism is broken for level0 tarball.

So did you verify everything needed to build Level1 is actually part of the bundle? It can't work exactly 1-1 out of the box, since there are changes in **pnext** that affect this, for example the meta schema file as I have pointed out above.

**Comment by per-samuelsson** [comment]
The test case is super simple btw:

1. Clone https://github.com/Starcounter/Starcounter.git to some random place on your hard drive.
2. Run `git checkout pnext`.
3. Make sure you have a VPN to the network.
4. Open `Level1.sln` and build. It should work (but does not).

**Comment by alemoi** [comment]
Thank you for the information. So I suppose I will take over if there are any problems left after the author of new metaschema changes fixes the new pnext problem @per-samuelsson described. Let me know if any help is needed!

**Comment by k-rus** [comment]
> So I suppose I will take over if there are any problems left after the author of new metaschema changes fixes the new pnext problem @per-samuelsson described.

Which problem? New meta-schema file is in place and has to be always used.



> Let me know if any help is needed!

It is expected that you fix this issue as it is one of the requirements for merging pnext.

**Comment by alemoi** [comment]
Sure, I can help fixing it but I have no idea how this metaschema works, because I didn't add it :) Who did introduce this metaschema in pnext? Who designed it so that Level1 is dependent on Level0 sources? I need to talk to the author in order to help fixing it.

**Comment by k-rus** [comment]
> Who designed it so that Level1 is dependent on Level0 sources?

Level1 does not depend on the sources of Level0. To my knowledge it depends on the output folder of Level0. The meta-schema file as PB files are located in the output folder of Level0. So it should work. I don't believe that @per-samuelsson implemented C# metadata class generations based on the meta-schema files located in src. I think he uses the one, which is copied into Level1 output. The question is why the file is not copied when copy remote is used. To my understanding copy local works correctly.

**Comment by per-samuelsson** [comment]
> To my understanding copy local works correctly.

But copy local depends on Bluestar output build. That's what this whole issue is about. Removing such dependency. I just dont want to build Bluestar (and here, I represent a category of developers that cant / shouldn't / dont want to).

**Comment by dan31** [comment]
@alemoi come on :feelsgood: Please fix it so that it works, don't break things and gather all needed info from the relevant people. That issue is important because many developers don't need to build Level0 every time.

**Comment by per-samuelsson** [comment]
> That issue is important because many developers don't need to build Level0 every time.

I don't know the status now, but in the past, not everybody even had access to it (among those that built Level1).

**Comment by alemoi** [comment]
Seems to be fixed now, basically just changed the Level0 branch name in `CopyDependenciesRemote.csproj` in pnext Level1, otherwise the build system worked correctly. Tried building Level1 without Level0 - built from the first attempt. You can verify this.

**Comment by per-samuelsson** [comment]
> You can verify this.

I will for sure. Super, @alemoi. Great work! If anything still shouldn't work, I'll let you know.

**Comment by per-samuelsson** [comment]
> C:\Users\Per\Git\Starcounter\PNext\Level0\src\include\sccoredb.h(13): fatal error C1083: Cannot open include file: 'star\uuidhelp.h': No such file or directory (compiling source file OurSources\urimatch_codegen.cpp)


Get about 200 errors building still, caused by the above. I tried searching that file under "Level1", but couldn't find it. Starting with the latest Starcounter **pnext** commits, and deleted the auto-created "Level0" folder before building.

**Comment by per-samuelsson** [comment]
> Get about 200 errors building still, caused by the above. I tried searching that file under "Level1", but couldn't find it.

I've tried understand the build better now, to see if I could understand what goes wrong. To me, it look like the error would be in `CopyDependenciesRemote.csproj`. If I look at the FTP, some header files reside in subdirectories to `Include` and I can't see how this pattern can resolve that:

```
<RemoteLevel0IncludeFiles Include="$(BinariesFTP)\SCBuilds\Level0\$(GIT_LEVEL0_BRANCH)\LatestStable\Include\*" />
```

With my rather basic understanding of MsBuild, I'm suspecting this does not include subdirectory trees, does it? If not, that's the problem. 

I'll wait for @alemoi to confirm/fix this, since I don't feel 100% confident that's the case. I can't see how it ever could have worked without those files though (or was it not tested)?

**Comment by alemoi** [comment]
Haha, so typical :D I cleaned Level1 but not the include folder, that's why build succeeded! In develop Level1 the include folder is plain I suppose, not at the computer now. Thank a lot for checking! I will verify and submit the thing.

**Comment by alemoi** [comment]
I checked and pushed the fix now. The build from scratch however requires building Level1 two times. Thank you again @per-samuelsson !

**Comment by per-samuelsson** [comment]
> The build from scratch however requires building Level1 two times.

Yeah, the first time always fails. The second time sometimes too. But third time usually work. That's not optimal, but not a super prio in any way.

> I checked and pushed the fix now. 

Great. Thanks.
