### ISSUE TITLE
pnext: failing builds on buildserver

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3262]
From time to time a build fail on the buildserver and I see the following error

```
[13:41:09][Step 1/1] C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsSDK.targets(520,5): error VSSDK1025: Could not add the file "..\..\..\bin\Release\\ItemTemplates\CSharp\Starcounter\1033\CSTypedJson.zip" to the zip package "..\..\..\bin\Release\Starcounter.VS12.vsix". Could not find file 'C:\TeamCity\TeamCity9\buildAgent\work\sc-1471\Level1\bin\Release\ItemTemplates\CSharp\Starcounter\1033\CSTypedJson.zip'. [C:\TeamCity\TeamCity9\buildAgent\work\sc-1471\Level1\src\Development\Starcounter.VS.VSIX.2013\Starcounter.VS.VSIX.2013.csproj]
```

Running the same build again often succeds. 

It doesn't happen quite that often though, and since the history was cleaned in the last teamcity upgrade, I only found two builds in the existing history:
https://teamcity.starcounter.org/viewLog.html?buildId=88&buildTypeId=Starcounter_PnextDailyWindows&tab=buildResultsDiv
https://teamcity.starcounter.org/viewLog.html?buildId=111&tab=buildResultsDiv&buildTypeId=Starcounter_PnextDailyWindows

I haven't seen this error on develop builds so maybe something is different or not merged correctly to pnext?

**Comment by k-rus** [comment]
I often get this problem locally. For example, if I clean Level1 then I catch it on the first build.

**Comment by chrhol** [comment]
I guess it's some problem with msbuild, buildorder and dependencies again. I will add some additional dependencies to the project that fails and see if that helps.

**Comment by chrhol** [comment]
I have not seen this error anymore after my change. I will close it, but keep an eye open if it should happen again.

**Comment by alemoi** [comment]
Same happens on develop for two nights in a row: https://github.com/Starcounter/AdminTrack/issues/62

**Comment by alemoi** [comment]
@chrhol was the dependency fix applied to develop as well?

**Comment by chrhol** [comment]
> @chrhol was the dependency fix applied to develop as well?

I don't really remember what I did...seems strange if I only made the changes in pnext. I will check

**Comment by chrhol** [comment]
For some reason I only added it in pnext. I will do the same for develop. Lets hope it will help.

**Comment by chrhol** [comment]
Fix pushed to develop as well now. Let's hope it will help!

**Comment by chrhol** [comment]
Looks like it helped for this problem on develop as well. Closing...
