### ISSUE TITLE
Nightly installations fail

### ISSUE THREAD

**Issue by MLidstrom** [Starcounter/Starcounter#3264]
After installing latest stable 2.1.177 (14 okt 2015 17:28:43) I wanted to install the latest nightly so I uninstalled 2.1.177 and installed 2.1.1048 (19 jan 2016 03:00:59) but it failed with:

![1](https://cloud.githubusercontent.com/assets/538395/12421327/0f543ac2-bec2-11e5-81da-9b0a8d684ea4.png)

and

![2](https://cloud.githubusercontent.com/assets/538395/12421336/1f1aa068-bec2-11e5-8139-b87743b0d4f0.png)

I got the same result with  958 and 987 from nightly.

OSX with VMware Fusion running Windows 8.1 x64 with Visual Studio 2013 installed (not running)

**Comment by alemoi** [comment]
Thank you for reporting this! There are some known problems in Windows regarding VS 2015 redistributable. We have a thread addressing this: https://github.com/Starcounter/Starcounter/issues/3067

**Comment by alemoi** [comment]
I will modify the messages so they comply with each other.

**Comment by dan31** [comment]
Nice catch @MLidstrom :+1:

**Comment by alemoi** [comment]
The error 3010 is an exceptional case that we didn't met before. It means that restart is required after redist installation. I made a patch that shows a special message box for this case: "Installation of Microsoft Visual Studio 2015 Redistributable (x64) succeeded but requires system restart. Please restart your computer now and start Starcounter installation again.". Later I need to fix that Starcounter installation is proceeded after the restart.

**Comment by warpech** [comment]
Can the first alert message also say "Microsoft Visual Studio 2015 Redistributable (x64)"? 

Right now it says "Microsoft Visual Studio C-runtime", which is confusing because it is not apparent if it means the same thing.

Also, can we make it clear that installation of "Microsoft Visual Studio 2015 Redistributable (x64)" does NOT mean that Visual Studio 2015 will be installed?

**Comment by alemoi** [comment]
Yea, i fixed the texts as well. Not the clarification though)
