### ISSUE TITLE
Teamcity builds with random changes

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3267]
I noticed that updated Teamcity starts builds with changes from different time instead of latest one. Thus it starts builds, which cannot succeed. It uses changes, which were committed to a personal branch and were committed to master branch with other changes, but the teamcity ignores the other changes. See latest builds in [pnext-daily-windows](https://teamcity.starcounter.org/viewType.html?buildTypeId=Starcounter_PnextDailyWindows). I don't know if it is applicable to other projects.

The problems are confusion for developers and occupying build server with large amount of builds.

**Comment by alemoi** [comment]
Thanks for reporting! I looked at the settings that were imported from previous version of TeamCity and I guess they didn't work in that old version properly. In the new version they seemed to work properly, but the settings were strange, so I cleaned them up. Let's see now if changes are collected properly!

**Comment by alemoi** [comment]
@k-rus did you experience this issue again after the fix i made?

**Comment by k-rus** [comment]
I didn't run much builds, especially with long merges. So I cannot say, but since nobody complains, I will close the issue until further notice.
