### ISSUE TITLE
Teamcity does not recognize native tests

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3269]
Teamcity was reporting passed and failed tests for native tests, which are written in gtest and run with ctest, earlier. But now it does not report them, instead only exit code is used for errors and log requires inspection.
See [this build](https://teamcity.starcounter.org/viewLog.html?tab=buildLog&buildTypeId=Starcounter_PnextDailyWindows&buildId=145) of pnext daily windows.

**Comment by alemoi** [comment]
Thanks for reporting! Again some changes with TeamCity. I have fixed the CTest report processing. Should work better now.
