### ISSUE TITLE
Starcounter administrator log not showing proper URI

### ISSUE THREAD

**Issue by MLidstrom** [Starcounter/Starcounter#3274]
Prior to "System.Exception: ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already been registered." there's an entry that says: 'Attempt to register URI handler duplicate on port "8080" and URI "€phrq".'

**Comment by alemoi** [comment]
Thank you for reporting! I guess this on is on me, not a problem with Administrator.

**Comment by alemoi** [comment]
Fixed via acaf41206dd609200890cea280f723e4ab5c3b49
