### ISSUE TITLE
pnext: Separate layouts for indexes and records

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3278]
On index searches record layout will always be translated to index layout (same as when no index and record layouts are incompatible). Optimize layout translation.

Purpose being less impact in index search performance where indexed set contains records with incompatible layouts. As it is now, to maintain good index scan performance, records in a specific set needs to be quickly updated to have a uniform layout when new layout is introduced and then indexes will have to be recreated to reflect the new layout. This makes layout updates complicated. Goal is to make it possible to skip the index recreation and allow for records with unexpected layout to linger longer without it affecting performance overly much.

**Comment by eriohl** [comment]
Standard performance tests shows no measurable difference between not and always translating schema on record key compare in indexes and key generation for index updates. However, if keys stored in indexes are ignored, performance drops about 40%. Suggests that key generation for index updates is not a big issue but that index search performance is affected a lot by this in cases where record key compare is used (which generally is a lot more common then standard performance test suggests).

**Comment by eriohl** [comment]
I've gotten it down to about 5-6% slower in the above mentioned case where comparison is always done against record (now done the same way regardless if record is compatible or not). This is done by caching the layout translations per index. Considering the benefit and most compares should be resolved using the keys in the index I would argue that this makes is viable (I will still make an effort to improve on it further).

**Comment by eriohl** [comment]
This is now pretty much working (branch **pnext-3278**). There is however some compatibility issues due to ```STARI_INDEX_INFO``` being different (no connection to a layout but instead containing information about the layout of the index). Affects index selection in query processor and metadata layer.

There are some work also on optimization and memory management (for layout transaction cache) which I intend to look into today.

**Comment by eriohl** [comment]
Having some performance issues with my latest changes. Work on this is suspended until I have the opportunity to work this out.

**Comment by eriohl** [comment]
Added separate issue for garbage collecting layout translation caches in IWP #3348. Most likely not a problem so postponing work on this.

**Comment by eriohl** [comment]
@k-rus @alexanderstc I've changed in metadata table creation so that whether index belongs to a specific table is determined by comparing the set specifiers rather then the layout handle. This of course because index no longer has a layout handle. This is correct right?

**Comment by eriohl** [comment]
Think I got everything working now:

1. Added the ability to filter inherited indexes calling ```stari_context_get_index_infos_by_setspec```. This was filtered by query process by checking layout handle of index info which obviously doesn't work when no layout is attached to index (or rather have its own layout).

2. Added ```struct STARI_INDEX_INFO_OLD``` that is compatible with old structure containing column indexes or layout rather then column tokens and types. Added ```stari_context_get_index_infos_by_setspec_OLD``` to allow fetching this structure instead providing a layout as a basis for generating the output (index layout is translated to selected record layout in terms of column indexes). Again this is for compatibility with query processor.

3. Removed a fix in query processor related to offset keys that are no longer required.

4. Fixed metalayer ```TABLE_INFO::load_indexes``` to filter inherited indexes on set specifier rather then layout handle (mentioned earlier). Passes all the tests but it is still incorrect because method returns layout handle from index which no longer can be fetched, so now it always returns an invalid handle. Should be possible to use the kernel support filter here mentioned above here as well I figure.

5. Disabled some code in ```INDEX_INFO::verify``` that no longer can be supported. Did not seem to be a hindrance for things to work but rather error checking.

1 and 4 is included in branch **pnext** already. The other ones are implemented in **pnext-3278**.

@k-rus and/or @alexanderstc : Could you check this changes as promptly as possible for obvious fails so that we can merge this? This is the last planned change that affects database compatibility so it would be really good to get it out of the way. (Then I will leave you with fixing the issues in metalayer and the compatibility work arounds in query processor when planning allows). Ok?

**Comment by alexanderstc** [comment]
@eriohl 
> I've changed in metadata table creation so that whether index belongs to a specific table is determined by comparing the set specifiers 

Looks fine to me.

**Comment by eriohl** [comment]
Can I merge then? As it now there is again no measurable difference in performance in my tests. I currently have a problem with this 3LevelSchemaChange timing on build server (need to increase the time cap on this test is seems) but once that is resolved I'm done on my end.

**Comment by k-rus** [comment]
@eriohl You can merge.

**Comment by eriohl** [comment]
Merged.

**Comment by k-rus** [comment]
Do I correctly understand that new `sari_context_create_index` uses name tokens for columns in `column_definitions` to find out the columns to index on?

**Comment by eriohl** [comment]
No. Name and type (including type flags). That is: The whole type definition.
