### ISSUE TITLE
Question : how to load default database in another computer?

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3280]
I have 2 servers, 1 is Production server and 2nd is Testing server. 
Now my question is that how can I use Data from Production Server(Server 1) in my testing Server(Server 2)?

(Note: The DB name in Production Server is "Default")

**Comment by miyconst** [comment]
You can use the reload command:
http://starcounter.io/guides/tools/staradmin/#reload-command

**Comment by atifsheikh** [comment]
How do i get "data.sql" file?
I cant find this file in my Personal folder. I am using SC version 2.0.3226.3

**Comment by miyconst** [comment]
You should use the unload command to create the file:
http://starcounter.io/guides/tools/staradmin/#unload-command

**Comment by atifsheikh** [comment]
:+1: 
Thanks

**Comment by miyconst** [comment]
Make sure you "reload" into a newly created database.

Currently unload and reload commands save object ids, and if a database was in use, some of the ids won't be available and reload command will fail.

That is why you have to create a new database each time you load it with an sql script.

**Note**: Deleting all items from database is not enough. You have to physically remove the old database and create a new one.

**Comment by atifsheikh** [comment]
I am getting this error on Unloading the database.

![image](https://cloud.githubusercontent.com/assets/4388707/12451892/09a8c852-bf8c-11e5-9216-508643ea6314.png)

**Comment by miyconst** [comment]
Unfortunately, in current version of Starcounter you have to load all classes into memory before you can access it's data.

This means you have to start all applications which define at least one database class. Then you will be able to unload the sql script.
