### ISSUE TITLE
Make the Download page channels more clear

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3290]
Currently, the sorting order of channels on the [Download page](http://downloads.starcounter.com/download) is: `Daily`, `Nightly`, `PnextNighty`, `Stable`.

![screen shot 2016-01-22 at 14 54 19](https://cloud.githubusercontent.com/assets/566463/12512335/0e6d8142-c118-11e5-9fa7-f9758e5b6678.png)

A newbie does not know what to download from here. I think we need to do two things:

1. Change the order to: `Stable`, `Nightly`, `PnextNighty`, `Daily`
2. Add a one line description for each channel. Something like:
  - `Stable`: Stable release channel. Updated once in few weeks. All the Docs contain information relevant to the latest version in this channel, unless said otherwise. Sample Apps and Prefab Apps run in latest version in this channel and sometimes support more stable versions back (see the package information for details).
  - `Nightly`: Unstable release channel. Updated daily. Contains features considered release candidate for a next stable release. Feel free to use it for the bleeding edge developer experience.
  - `PnextNighty`: Experimental release channel. Might contain breaking changes. Use it at your own risk.
  - `Daily`: Unstable release channel. Updated irregularly. Typically out of date. Contains custom releases for test purposes.

The above is just how I would explain the channels to a stranger. Please adjust these texts if needed.

**Comment by k-rus** [comment]
See an older issue #2295

**Comment by warpech** [comment]
The fallacy of the current page was confirmed today by @aloscha. A person who wants to download the latest nightly is the most likely to incorrectly download the latest daily (which is currently 4 months old).

**Comment by warpech** [comment]
> See an older issue #2295

Sorry, I will merge the issues
