### ISSUE TITLE
Question : How to sync Table Data between 2 different servers

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3291]
I have 2 servers on different locations, and both servers are using the same application. Now I want to sync data of a Table from Server 1 to Server 2.

One way is that i create 2 handlers, 1st will be Data Sender and 2nd will Receive Data & Store in DB, and also i will have to create a Starcounter Typed JSON aswell. But the drawback in this method is that i will have to update the Starcounter Typed JSON if i have any new columns or any changes in my table.

So the question is that, is there any Starcounter Built-in Method to sync data of a table between 2 installations of StarcounterDB?

**Comment by per-samuelsson** [comment]
@atifsheikh 

There are ongoing development of a [replicator sample](https://github.com/Starcounter/Replicator) that might be worth having a look at. It might not be what you need, but thought I'd let you know in case you would find it interesting.

The transaction log reader library it's based on is not part of any stable build yet, but soon will be.

**Comment by atifsheikh** [comment]
Awesome, this is exactly what i was looking for.
