### ISSUE TITLE
Implement new general middleware API, supporting middleware classes

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3296]
Work issue for the outcome of #3251.

**Comment by per-samuelsson** [comment]
I've reviewed the  prerequisites on this and the related issues, and decided now that I'll do it in this order:

1. I'll add the new API in *addition* to the current one (also extending it, to support middleware classes). This, I'll do in **develop**.
2. Functionality wise, I won't touch how request- and response filtering works under the hood at the moment, and likely not at all in 2.x-based versions. I think it will risk messing with current applications.
3. I'll probably do the implementation for replacing partials and "automatic JSON Html property" (instead turning those to be middleware-enabled) only in **pnext**.

@warpech, is that plan OK with you? Or do you feel strongly that we should do even [3] in **develop**?

**Comment by warpech** [comment]
It is OK, as confirmed in https://github.com/Starcounter/RebelsLounge/issues/16.

Since 1 (the new API) is done in `develop`, what else do you mean for 3? Is it just removal of `Page` and `Partial` or something more?

**Comment by per-samuelsson** [comment]
> [...] what else do you mean for 3? Is it just removal of `Page` and `Partial` or something more?

Point [3] was a) to replace `Partial` and b) to replace `Page`. And introduce similar functionality driven by registration of middleware.

My initial idea was to do this only in **pnext**, but based on your input in https://github.com/Starcounter/RebelsLounge/issues/16 (and as I wrote there too), I'll now do 3a fully already in **develop** (i.e. becoming 2.2), and try to do 3b in someway that users can switch `Page` out gradually, but I won't drop the page class itself.

Is that fuzzy? I hope it is in line with what I wrote in the related issue, and let me know if you have objections or want me to further elaborate on it.

**Comment by warpech** [comment]
It makes perfect sense now, thanks!

**Comment by per-samuelsson** [comment]
Merged, pushed and wrapped up in https://github.com/Starcounter/Starcounter/commit/a2df928f382b9d39dbf187a896916324eb647914. And documented in https://github.com/Starcounter/RebelsLounge/blob/master/Uncategorized/Middleware.md.

Just merging it to **pnext** is still to be done, which I'll do eventually.

**Comment by per-samuelsson** [comment]
> Just merging it to **pnext** is still to be done, which I'll do eventually.

Done.

Sorry @alemoi for not doing it instantly and that it became a hazzle for you in the middle of the night! My idea was to merge it right after I finished this other issue that also need to be merged, but that was a bad decision to wait. From now on, I'll always merge instantly!
