### ISSUE TITLE
pnext: running store_apps_test fails with unhandled unspecified error on release build

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3297]
The store apps test, that pulls and runs some tests on our sample/prefab apps fails on pnext, release build on the buildserver.

The test is disabled currently, so to reproduce it on the buildserver you have to do a custom build and set the parameter `env.RUN_STORE_APPS_TEST` to `True`

To run it locally requires a bit more work and requires some additional stuff installed (like nodejs). I will try to simplify the script if possible. The original testscript can be found in Level1 repo, `\src\Buildsystem\Tests\store_apps_test.bat`

Worth to notice is that the test succeeds running a debug build of Starcounter. Only release fails and the error reported does not contain much:

```
20160125T165816 Critical sc://chrhol-pc/personal/polyjuicetestsdb Starcounter - Unhandled unspecified error (E0434352) detected (Thread 504588).
    00007FFD3B691F08 KERNELBASE!
    00007FFD210C38F9 clr!
    00007FFD211025BB clr!
    00007FFD21102618 clr!
    00007FFD21527731 clr!
    00007FFD2132AB11 clr!
    00007FFD20001C44 mscorlib.ni!
    00007FFD1FF38272 mscorlib.ni!
    00007FFCC1C104C2 <unknown>!
    000000320E1BF760 <unknown>!
    0000013C750D4D98 <unknown>!
    0000013AF6173268 <unknown>!
    0000013EFFB47D60 <unknown>!
```

Is there something I can do to get a better stacktrace? This one is taken from a local build of pnext.

/cc: @eriohl, @bigwad

**Comment by bigwad** [comment]
@chrhol, please check %LOCALAPPDATA%\CrashDumps for crash dumps. If folder is empty, create registry value HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\@DumpType=2 and reproduce the crash.
Once we have a dump I'll probably need .pdb files of your local build to investigate it further.

**Comment by eriohl** [comment]
Intercepting CLR exceptions in unmanaged code and using the legacy debug output generally doesn't provide much information. Better to not intercept it.

**Comment by chrhol** [comment]
> Once we have a dump I'll probably need .pdb files of your local build to investigate it further.

I have a dump available now, do you have access to the exchange-folders in our dropbox?

**Comment by bigwad** [comment]
Root cause of crash is AV:
```
    0000000A3757E980 0000000000000001 UNKNOWN!Starcounter.SqlProcessor.SqlProcessor.scsql_process_query(UInt64, System.String, Byte ByRef, UInt64 ByRef)+0x2
    0000000A3757EA50 00007FFCC196BE07 UNKNOWN!Starcounter.SqlProcessor.SqlProcessor.CallSqlProcessor(System.String, Byte ByRef, UInt64 ByRef)+0x27
    0000000A3757EA90 00007FFCC196BA70 UNKNOWN!Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[[System.__Canon, mscorlib]](System.String, Boolean, System.Object[])+0x50
    0000000A3757EB30 00007FFCC196AD45 UNKNOWN!Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[[System.__Canon, mscorlib]](System.String, Boolean, System.Object[])+0xd5
    0000000A3757EBB0 00007FFCC196ABA4 UNKNOWN!Starcounter.Db.FullQueryProcess[[System.__Canon, mscorlib]](System.String, Boolean, System.Object[])+0xf4
    0000000A3757EC70 00007FFCC1DEE856 UNKNOWN!Products.DefaultStyles+<>c__DisplayClass1_0.<Apply>b__0()+0x36
    0000000A3757ECA0 00007FFCC195F03D UNKNOWN!Starcounter.Db.Transact(System.Action, UInt32, Boolean, Int32)+0xcd
    0000000A3757ED80 00007FFCC1DEE800 UNKNOWN!Products.DefaultStyles.Apply()+0xd0
    0000000A3757EDC0 00007FFCC1DE9B31 UNKNOWN!Products.Program.Main()+0x71
```

Does it help?

**Comment by chrhol** [comment]
@k-rus, @alexanderstc: Can you take a look? As I mentioned in my first post, it's possible to run this test locally, but it requires manual steps. I could try to simplify it to reproduce easier locally if needed.

**Comment by chrhol** [comment]
Actually it was quite easy to reproduce:
1) Run release version of Starcounter
2) Clone and build [Products](https://github.com/StarcounterSamples/Products). Release or debug here doesn't matter
3) Start `product.exe` with Star or start directly from Products solution.

**Comment by chrhol** [comment]
Hmm, it actually looks like some recent (as in today) change have fixed the problem. I just tried to run it  on a daily pnext build and it succeeded. 

I will enable it for the nightly build and check back tomorrow. If it succeeds there, we can close this issue.

**Comment by chrhol** [comment]
I've been running some builds now on the buildserver with this test enabled and it seems to work fine now. Treating this issue as solved!
