### ISSUE TITLE
Git HEAD of Level1 on our remote server is set to wrong branch

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3299]
When I checkout Level1 from our remote origin, it fetches default branch, which is set to **andwah** branch, which is personal branch of @andwah

**Comment by k-rus** [comment]
Can it be a some bug in git that it chooses wrong default branch? I remember @per-samuelsson experienced this issue some time ago.

**Comment by per-samuelsson** [comment]
> When I checkout Level1 from our remote origin

Can you clarify that? It does not map 1-1 to git lingo, does it? You mean clone? Pull? What exact command are you running?

**Comment by k-rus** [comment]
> Can you clarify that? It does not map 1-1 to git lingo, does it? You mean clone? Pull? What exact command are you running?

I mean clone. Sorry for confusion.

**Comment by per-samuelsson** [comment]
> I mean clone. Sorry for confusion.

I can't really reproduce this.

If I'm doing a plain fresh clone, I get this:

![image](https://cloud.githubusercontent.com/assets/2902045/12642940/387e7734-c5b9-11e5-9072-5cf468289c87.png)

Thats exactly what I would expect based on the setting here:
https://github.com/Starcounter/Starcounter/settings/branches

Could you clarify further?

**Comment by per-samuelsson** [comment]
```
cat .git\HEAD
ref: refs/heads/develop
```

Also what I would expect.

**Comment by k-rus** [comment]
@per-samuelsson you complained about the same problem in issue #2570 (finally I found it).

As I understood it is limitation of git protocol if several branches are located at the same position as head, the local cloning gets the list of the branches and no clue, which one is the default.

**Comment by per-samuelsson** [comment]
> As I understood it is limitation of **git protocol** if several branches are located at the same position as head.

Aha, so maybe that's why I can't reproduce it on my end. As you can see from my screenshot, I'm cloning using `https`. Maybe it's a flaw in the SSH-based protocol (because your are not really using the *git* protocol, are you?)

**Comment by k-rus** [comment]
> As you can see from my screenshot, I'm cloning using https. Maybe it's a flaw in the SSH-based protocol (because your are not really using the git protocol, are you?)

I guess I used SSH link to clone. Do you think that git protocol is different between SSH or HTTPS cloning?
By the way, which protocol have you used when experience the same problem (#2570)?

**Comment by dan31** [comment]
Is that still an issue?

**Comment by k-rus** [comment]
I think developers will meet this issue time to time as it is a limitation of git. So I close the issue.
