### ISSUE TITLE
Add all links of your demo apps to the readme please

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3301]
I noticed you moved the launcher to yet another namespace. Could you please add that link to the readme as well? It is not intuitive ;)

**Comment by miyconst** [comment]
Added to the [readme](https://github.com/Starcounter/Starcounter/blob/develop/README.md).

![image](https://cloud.githubusercontent.com/assets/6435556/14953344/1c77d062-1069-11e6-864a-5e89d542a84d.png)
