### ISSUE TITLE
pnext: New build agent fails on kernel func tests

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3303]
I just finished installation and configuration of new build agent sctestsrv03. Develop builds fine, however when running on pnext daily I have an error message: 

``` c#
[metalayer_functest] [Test Error Output]
Running metalayer_functest
Colud not find clang++.exe 
metalayer_functest failed
```

How is clang++.exe used there and where it tries to locate it? Strange why it works on other build agents.

For example: https://teamcity.starcounter.org/viewLog.html?buildId=535&buildTypeId=Starcounter_PnextDailyWindows&tab=testsInfo

**Comment by k-rus** [comment]
(The test is not kernel test. Native is not equivalent to kernel.)

Issue Starcounter/CompanyTrack#79 discusses how to set up environment to run such tests. It might be enough to add the location of clang++ and ld to the path.

**Comment by alemoi** [comment]
Thank you for response. And how is clang utilized these days for these tests? Since we use in memory clang for SQL.

**Comment by alemoi** [comment]
That fixed the problem, thank you! But still I have a question if clang++.exe and ld.exe are used somewhere in pnext kernel or the support should be removed since I added clang in-memory SQL support. @eriohl @alexanderstc @bigwad do you have any insight on this?

**Comment by eriohl** [comment]
clang++.exe and ld.exe are not used by the kernel.

**Comment by alemoi** [comment]
Thank you, then I will dedicate time in cleaning that up using preprocessor in relation to the inmemory clang I did earlier.

**Comment by k-rus** [comment]
> clang++.exe and ld.exe are not used by the kernel.

This explains why the kernel func test does not fail. Metalayer uses clang to compile generated C++ code of query plans.

**Comment by alemoi** [comment]
> This explains why the kernel func test does not fail. Metalayer uses clang to compile generated C++ code of query plans.

Aha, so its being used actually. Is there any plan to convert to the usage of in-memory Clang as in SQL codegen now?

**Comment by k-rus** [comment]
> Is there any plan to convert to the usage of in-memory Clang as in SQL codegen now?

Clang is used according @alemoi instructions. It was implemented in September I think.
cc @alexanderstc

**Comment by alemoi** [comment]
> Clang is used according @alemoi instructions. It was implemented in September I think.
cc @alexanderstc

Yes, but that was in-memory Clang DLL (which I also use for codegen SQL), not clang++.exe that seems to be used in metalayer as you point: `Metalayer uses clang to compile generated C++ code of query plans.`

**Comment by alemoi** [comment]
@alexanderstc do you use clang++.exe/ld.exe somehow?

**Comment by alexanderstc** [comment]
metalayer doesn't use clang. QP does, to compile queries.

**Comment by k-rus** [comment]
As conclusion metalayer_functest fails on clang++ because of the test dependency on the kernel.

I guess QP uses Clang DLL, not clang++.exe.

**Comment by dan31** [comment]
I am a bit disoriented here, hm. On one hand, we want to compile queries once-until-update, hence the result of compilation must persist somewhere. On the other hand, I remember @alemoi assisted @alexanderstc with migration to a new clang dll, quite recently, probably in October.

**Comment by alemoi** [comment]
> I am a bit disoriented here, hm. On one hand, we want to compile queries once-until-update, hence the result of compilation must persist somewhere. On the other hand, I remember @alemoi assisted @alexanderstc with migration to a new clang dll, quite recently, probably in October.

I am also confused :laughing:
Once again, @alexanderstc do you use clang++.exe or Clang DLL? :)

**Comment by alexanderstc** [comment]
@dan31,

> I remember @alemoi assisted @alexanderstc with migration to a new clang dll

More precisely, @alemoi helped me to use his clang.dll to implement a simple, but full-cycle, compiled query in the new QP like "SELECT x FROM x".

> we want to compile queries once-until-update, hence the result of compilation must persist somewhere

Caching and persistence of compiled queries is one of the things which are to be designed and implemented for the new QP to move from demo to a real thing.

**Comment by alexanderstc** [comment]
Some demo-quality caching is already implemented in the new QP, BTW.

**Comment by dan31** [comment]
Some enlightenment seems to be coming into place. I believe we now have both new QP and old QP (to which new QP is fallen back most of the time for constructions it doesn't yet support). Hence, advances done for new qp of course aren't applicable to the "old" QP. It means that we either keep things as is, or decide to move old qp into some of these advances of old qp. This might makes sense mainly not to bloat the distribution with redundant tools. @k-rus @alexanderstc what are your opinion.

**Comment by alemoi** [comment]
I still have a question if anyone uses clang++.exe (not scllvm.dll :)) and for what code :)

**Comment by alexanderstc** [comment]
> or decide to move old qp into some of these advances of old qp

"old" used twice, does not compute that way. Please clarify.

**Comment by alexanderstc** [comment]
> @k-rus @alexanderstc what are your opinion

It's mostly up to @k-rus to decide, I'll happily code up (probably, almost) anything you guys can come up with.

**Comment by k-rus** [comment]
> Some enlightenment seems to be coming into place. I believe we now have both new QP and old QP (to which new QP is fallen back most of the time for constructions it doesn't yet support). Hence, advances done for new qp of course aren't applicable to the "old" QP. It means that we either keep things as is, or decide to move old qp into some of these advances of new qp. This might makes sense mainly not to bloat the distribution with redundant tools. @k-rus @alexanderstc what are your opinion.

This is off-topic of the issue. Furthermore, I don't fully understand the question. I suggest to move this discussion into an issue in CompanyTrack repo.

**Comment by alexanderstc** [comment]
@alemoi,

> I still have a question if anyone uses clang++.exe (not scllvm.dll :)) and for what code :)

I don't use clang++.exe and I don't know else does.
