### ISSUE TITLE
Json Refresh

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3305]
Hi!

I've removed all caching of values in my Json App. But I'm a bit confused. I have a IEnumerable<DbObject> bound to a property at top level of the json.

This property is called 4 times before even sending the data to the web browser. This seems insane!

Once the data is sent to the server and the client invokes a change the property is only read once. So this seems valid.

The problem seems to be the initial reading of data

**Comment by chrhol** [comment]
Hi, this is a known issue reported in #2551.

We will start to create a roadmap for the work that needs to be done for TypedJSON. We'll keep this issue in mind and try to get some time to fix it.

**Comment by per-samuelsson** [comment]
This seem like an exact duplicate of #2551? I vote we close it as such.

**Comment by careri** [comment]
Yepp, seems like #2551 covers it

**Comment by chrhol** [comment]
Closed as duplicate
