### ISSUE TITLE
Http request client culture?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3306]
Doesn't a request from the web browser (chrome) provide the culture in the http request to starcounter?

I can't find it on the Starcounter.Request instance

**Comment by alemoi** [comment]
Thank you for the question. Currently this header is not exposed as a property butwe can add it. For now you can access any header using req["HeaderName"] syntax.

**Comment by per-samuelsson** [comment]
> Currently this header is not exposed as a property butwe can add it.

I think we should think one extra time before making each and every header into a property. It's not always good doing so (it makes it harder to see the essentials when the API keep growing).

> For now you can access any header using req["HeaderName"] syntax.

Eventually, I think we could consider changing that pattern to `req.Headers["HeaderName"]`. Would make it a little more clear IMO.

Finally, on a very general note: when we have to decide on something regarding the HTTP API's and how to design them (like this issue), I think a good pattern is to consult the [OWIN .NET API](http://owin.org/html/owin.html) and take inspiration from that. [Here's](http://owin.org/html/owin.html#3-2-1-request-data) about request data in general, leading to the section of [headers](http://owin.org/html/owin.html#3-3-headers).

It's not the absolute truth in any way, but will not result in any really bad design either. :sunglasses: An additional upside is that we slowly will move towards DNX by doing that.

**Comment by careri** [comment]
Thanks I'll try that. I seem to remember that you mentioned that way of accessing headers before. But it's not clear at it seems, so maybe a syntax change is a good thing :)

**Comment by per-samuelsson** [comment]
> But it's not clear at it seems, so maybe a syntax change is a good thing :)

Yeah, agree. Would you find this above proposal a good candidate?

> Eventually, I think we could consider changing that pattern to `req.Headers["HeaderName"]`. Would make it a little more clear IMO.

**Comment by careri** [comment]
In this case following a "standard" like OWIN seems like a good idea

**Comment by alemoi** [comment]
The request `Headers` property is in place. Closing the issue.
