### ISSUE TITLE
Add support for non-public database classes

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#331]
In the current version, database classes must be public. The main reason for this (if I'm correct) is that there is no real good way to deal with non-public classes and SQL.

One possible solution is to simply not expose them to SQL at all, including references to them from public classes, but there is some work involved for this and hence the constraint to keep them public has stayed.

We should reconsider this to come up with a concrete answer if 1) this will be addressed and if so, 2) when and 3) with what constraints.

One specific question has been raised currently, issue #298.

**Comment by dan31** [comment]
No demand raised from current users. Perhaps it shows that decision to support only ```public``` was good. Please reopen if you consider it differently (cc @warpech @miyconst).

**Comment by warpech** [comment]
Sometimes I get asked about it by developers. I respond that the databases classes cannot be private, at least for now. It is always met with understanding so far, so I think it is good to mark it as won't fix.

**Comment by miyconst** [comment]
+1 for what @warpech says. It is not possible to make `private` table in SQL, and everyone understands that.
