### ISSUE TITLE
All nightly builds were not able to start

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3312]
The error is:

>Failed to collect changes, error: List remote refs failed: org.eclipse.jgit.errors.TransportException: https://github.com/StarcounterSamples/Society-Objects.git: 500 Internal Server Error

**Comment by alemoi** [comment]
Thanks for noticing this! I guess there was something with github.com
Unfortunately I can't do much in this case.

**Comment by dan31** [comment]
Github has been reported down for 4 hours during this night and morning.
