### ISSUE TITLE
Enexpected handler is called

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3315]
When i Navigate to 

`http://localhost:8484/warehouse/organization/mT/stores/mn/settings`

This handler is called

`Handle.GET("/warehouse/organization/{?}/stores/{?}", (string orgkey, string key) => {...});`

There is no handler for 

`http://localhost:8484/warehouse/organization/mT/stores/mn/settings`

**Comment by alemoi** [comment]
Thanks for reporting! So the handler is called on different port?

**Comment by andwah** [comment]
@alemoi Same port,  my default user port is 8484

**Comment by alemoi** [comment]
After a discussion we concluded that handlers are called correctly. Last parameter resembles "ends with" no matter if matched string portion contains slashes or not. Closing as invalid.
