### ISSUE TITLE
Two json files with the same name cant be compiled

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3316]
I have two json files with the same name but under different folder and namespaces.

`{
  "$": { "Namespace": "Warehouse.ViewModels.User" },
  "Html": "/warehouse/viewModels/user/mainPage.html",
  "$Organizations" : { "Bind" :  "Organizations_"},
  "Organizations": [
    {
      "Key": "",
      "Name": ""
    }
  ]
}`

`Error	CS0101	The namespace '<global namespace>' already contains a definition for 'MainPage_json' Warehouse`

Example project can be found in dropbox Exchange/Anders.Wahlgren/Issues/3316

**Comment by chrhol** [comment]
I think the problem is that the attribute `MainPage_json` is in the wrong place in the generated code so that it actually is defined outside the namespace. 

I will move it so it's declared inside the same ns as the rest of the class.

**Comment by chrhol** [comment]
I've pushed a fix for this to develop. I moved the generated bits around some and all parts (classes and aliases) should now be included inside a namespace.

I will wait for your confirmation before closing the issue.

**Comment by andwah** [comment]
Tested and it works, thanks!.
