### ISSUE TITLE
Question: do request filters affect fellow apps?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3322]
Trying to dig into more of how our current request / response filter mechanism operate, and I get curious of how the design is meant to be.

I have two apps, "app1" and "app2", running in the same host. To my understanding, if I start "app1" first, and register this filter

```cs
Handle.AddRequestFilter((req) => {
  return new Response() {
        StatusCode = 404,
        StatusDescription = "Not Found"
    };
});
```

I'll effectively block any request from reaching any other application in the same host. Is that so?

**Comment by per-samuelsson** [comment]
Bumpsy. 

@alemoi? @chrhol?

**Comment by alemoi** [comment]
Sorry, I missed this one. In the current design Im affraid that would be the case, request filter can seriously mess things up.

**Comment by per-samuelsson** [comment]
> Sorry, I missed this one.

No problem! We all do sometimes :smile: 

> In the current design Im affraid that would be the case, request filter can seriously mess things up.

OK, thanks. Then I understood the code correctly. Yeah, we should probably change this at some point, but its not a showstopper or anything IMO. It just gives a lot of power to filters, and developers have to be aware of that. And now we have it "documented". :sunglasses:
