### ISSUE TITLE
DbMapping.MapDefault works strange

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3323]
The [Warehouse](https://github.com/Starcounter/Warehouse/) application, `so` branch.

I have `Warehouse.Database.UserSession` class which is mapped to `Simplified.Ring5.SystemUserSession`, and commit hooks over `UserSession` class.

The mapping seems to work in random order. Sometimes it applies, sometimes does not. Which results in different records among tables and not working commit hooks.

The way I was able to reproduce the bug most often:

1. Checkout Warehouse `so` branch.
2. Start Launcher + SignIn app.
3. Start Warehouse app in debug mode.
4. Set break point into [UserSessionHook](https://github.com/Starcounter/Warehouse/blob/so/src/ViewModels/WrapperPage.json.cs#L28) method.
5. Navigate to `http://localhost:8080/warehouse`.
6. User sign in form should appear.
7. Sign in with admin/admin.
8. The break point does not hit.
9. The data in two tables is different.

![image](https://cloud.githubusercontent.com/assets/6435556/12701977/154547d0-c81a-11e5-97c1-d4fd280edb17.png)

![image](https://cloud.githubusercontent.com/assets/6435556/12701978/1e3fb302-c81a-11e5-84fe-5ad2b5f33050.png)

Starcounter version: `2.1.1152`

cc @alemoi, @chrhol

**Comment by alemoi** [comment]
Thanks for  reporting! I will check it tomorrow!

**Comment by alemoi** [comment]
I was able to reproduce the problem and will start working on it shortly.

**Comment by alemoi** [comment]
I found that `DbMapping.Init()` was not called in Warehouse as it should be. After I added the call everything seems working fine. I pushed to "so" branch. Can you please test @miyconst ? Thank you!

**Comment by miyconst** [comment]
@alemoi what the `DbMapping.Init()` does and why it should be called manually?

**Comment by alemoi** [comment]
> @alemoi what the DbMapping.Init() does and why it should be called manually?

It enables mapping basically. Every mapper app should call it just before calling mapping API, as Warehouse does already.

**Comment by alemoi** [comment]
Did you experience any problems after I added `DbMapping.Init()`.

**Comment by miyconst** [comment]
@alemoi sorry, I didn't have time to check it. @andwah how does it work for you?

**Comment by andwah** [comment]
@miyconst at the moment i disabled the mapping from `UserSession` to `SystemUserSession`

I disabled it so i could easy clean the database of all warehouse tables ( i did not want to delete Simplified/so tables),

**Comment by alemoi** [comment]
I will close this issue. If problem appears again, please reopen it.
