### ISSUE TITLE
Question: How can I start the code host and debug an application .cs file?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3327]
I have a Starcounter `.cs` file, created with `staradmin +`. Now I want to debug the entrypoint. How do I do that?

**Comment by per-samuelsson** [comment]
1) Start the database you want to debug:

```
C:\Users\Per>staradmin -d=foo start db
Starting foo (started, code host PID: 123)
```

2) Open VS and attach the debugger to `sccode.exe` with the given PID (e.g. 123)

3) Use ```File -> Open -> File ...``` and open the `.cs` file.

4) Set optional breakpoints (e.g. in the entrypoint).

5) Run the application (optionally with ```--async```):

```
C:\Users\Per>star -d=foo [--async] app.cs
app -> foo (started, default port 8080, admin 8181)
```

**Comment by k-rus** [comment]
I confirm it works like a charm if I start database without VS being attached already to a sccode. (#3325).
