### ISSUE TITLE
Question: Suggested replication setting for built-in "Starcounter.Extensions" classes?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3328]
We have some problem with a replication setup that causes constraint violations in transactions created by Starcounter, involving classes from the built-in `Starcounter.Extensions` library. Mainly, we experience these conflicts with class "Starcounter.Layout".

I'm suspecting that it might be a good idea to disable replication of these classes in standard scenarios, right? That would involve the above layout class and the mapping classes too. If so, I'll eventually make them part of some default replication blacklist.

@alemoi? @dan31?

**Comment by alemoi** [comment]
Yes, I think layout classes should be excluded. However not sure about mapping information replication. What if replicated database would want to be set as master (if current master dies for example), then the mapping information between apps would not be preserved if we don't replicate it.

**Comment by per-samuelsson** [comment]
> Yes, I think layout classes should be excluded. However not sure about mapping information replication.

OK, then I'll see if I can disable them. Thanks.

> What if replicated database would want to be set as master (if current master dies for example), then the mapping information between apps would not be preserved if we don't replicate it.

If the question is to me, then I can't really answer it I'm afraid, since I'm not involved enough in how it all should work. :smile: The practical problem for me at this point is that Starcounter create / assure data that crash replication, since it produce duplicates when you start to ship entries around. If that does not apply to mapping, I'm fine with whatever decision.

**Comment by per-samuelsson** [comment]
Closing this, since at least parts of it was answered.
