### ISSUE TITLE
Crash with newest stable version of starcounter

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#3329]
Small database, not a heavy load and the applications crash with this error: 

Starcounter,System.NullReferenceException: Object reference not set to an instance of an object.
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 113
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 68
HResult=-2147467261

**Comment by mtornwall** [comment]
Looks like it could be a duplicate of #3032.

TLDR: Wrap any code executed with `DbSession.RunAsync()` in a rock-solid exception handler.

**Comment by per-samuelsson** [comment]
Thanks for reporting this @Ripipip.

Also looks like it could be a duplicate of #3122. Any particular thing about the context of the crash? Is it executing a handler? The entrypoint? A transaction?

**Comment by Ripipip** [comment]
Okay, false alarm! I panicked but then I realized that an index was missing, for some still unknown reason, and when I added it no longer crashed :)

**Comment by mtornwall** [comment]
@Ripipip if you do run unprotected unprotected asynchronous callbacks you still have a potential bug, though - beware. ;-)

**Comment by Ripipip** [comment]
Okay, it is a real problem because it keeps crashing no matter the indexes. @mtornwall What does that mean, how can I debug it?

**Comment by mtornwall** [comment]
@Ripipip Let's assume this is the same bug that I've experienced (the stack trace seems to strongly suggest this - particularly, the fact that you are not getting any useful stack trace :-)).

In that case, you need to go through all of your code and find any calls to functions like:

* `DbSession.RunAsync` (note: not a static method!)
* `{Node,Http}.{GET,POST,...}` (but only the ones that take a callback)
* ... and any other methods I might have forgotten that also schedule asynchronous tasks on the Starcounter scheduler.

Here's a typical example of a "bad" method:

~~~
new DbSession().RunAsync(() => {
    // ...
    var contents = File.ReadAllBytes(...); // IOException, boom!
    // ...
});
~~~

To fix it, simply wrap the delegate in a `try...catch` block:

~~~
new DbSession().RunAsync(() => {
    try {
        // ...
        var contents = File.ReadAllBytes(...); // IOException, boom!
        // ...
    } catch (Exception ex) {
        // Log exception here...
    }
});
~~~

**Comment by chrhol** [comment]
Thank you for the responses @mtornwall :) As you pointed out the stacktrace is not correct. The original exception is stored on the task and is rethrown after the task is executed, but the stacktrace is not kept, which hides any easy way to find the cause of it.

@Ripipip: If you add your own `try...catch` block in your code, you should be able to find where the nullreference occurs.

In the meantime I will change our code, so that at least the original stacktrace is kept and discuss with @dan31 is any further improvements needs to be done.

**Comment by mtornwall** [comment]
@chrhol The behavior I've come to expect is that when exceptions occur, they are allowed to unwind as much as possible of the stack up to the point where they would bring down the process. At that point the exception is caught and logged. I think the behavior should be similar here.

**Comment by per-samuelsson** [comment]
> The behavior I've come to expect is that when exceptions occur, they are allowed to unwind as much as possible of the stack up to the point where they would bring down the process. At that point the exception is caught and logged. I think the behavior should be similar here.

That's very standard, yes. And I think we should rarely diverge from that pattern, and be especially careful we *never catch exceptions that we don't actually handle*, but instead goes ignored. That include catching exceptions and log them without any further reaction.

WTBS, things are somewhat a little different in server models, and certainly so in our model, where we have to consider not only that the database / host keep running, but also that *other apps in the same process* keep doing that. One failing app should never be allowed to fuck it up for others.

The right thing to do seem for me to be that the host would catch exceptions that slip out from any application, assure as much information as possible is **logged** (including context and inner exceptions) and then **terminate the application**.

**Comment by Ripipip** [comment]
Try catch did actually help. thanks! 

This only started to occur after the upgrade from version 2.0.3226 to the latest stable version. Is it there any reason for it to work better in the earlier version?

**Comment by chrhol** [comment]
Lets move to the other issue (#3032) for further discussion since that one already contains some input.

**Comment by chrhol** [comment]
> This only started to occur after the upgrade from version 2.0.3226 to the latest stable version. Is it there any reason for it to work better in the earlier version?

Yes, in the older versions the exception was ignored. It still happened, but if you didn't catch it yourself you never saw it, no logging, nothing. Which was a quite serious flaw.
