### ISSUE TITLE
pnext: memory management failure on database start

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3330]
I often get an error that the memory management cannot allocate memory on database start:

```
C:\GitRepositories\Starcounter\Level1\src\Samples\TestApps\DropTable>staradmin s
top db
Stopping default (stopped)

C:\GitRepositories\Starcounter\Level1\src\Samples\TestApps\DropTable>staradmin s
tart db
Starting default (starting database)

[17:05:49, Starcounter (default)]
A fatal error was detected: ScErrCantCreateDbMemoryFile (SCERR4186): The memory
manager was unable to create a memory file to store database memory.

[17:05:49, Starcounter (default)]
ScErrUnexpErrorCreateDbMemFile (SCERR6058): An unexpected error was detected whe
n creating a memory file for database data. OS error=1450 (CreateFileMapping).
```

Sometimes it is really difficult to get through.

**Comment by dan31** [comment]
CC @bigwad @eriohl

**Comment by eriohl** [comment]
Error code indicates insufficient system resources. Which seems odd. Is it easy to reproduce?

**Comment by k-rus** [comment]
> Error code indicates insufficient system resources. Which seems odd. Is it easy to reproduce?

It happens in a VM on my Mac. It happens often, but not every time and I haven't noticed any pattern. So it is not easy to reproduce. Any suggestions what I should do when I get it again?

**Comment by eriohl** [comment]
Question is what kind of resource is running out. My guess is that it is the page file and the difference from previous versions is that larger segments is allocated. So if you could check if close ti or less then 1/8 physical memory of swapfile is remaining when it occurs this would be useful. This will then be adressed once we shrink the size of the segments as planned. Otherwise if you could figure out which resource is running out that would help.

**Comment by eriohl** [comment]
Do you have other databases running when error occurs or something like that?

**Comment by k-rus** [comment]
I will try to reproduce and look to the suggestions as soon as I am able to run Starcounter again.

**Comment by k-rus** [comment]
I've got it again. The amount of available main memory is 543 MB (out of 4GB), since I run two VSs. Before I tried to create and start a database all Starcounter's processes were killed  and databases have not existed:

```bash
>staradmin kill all
15:22:16.1111429: process 'scservice' successfully killed!
15:22:16.1111429: process 'scipcmonitor' successfully killed!
15:22:16.1111429: process 'scnetworkgateway' successfully killed!
15:22:16.1267689: process 'scadminserver' successfully killed!
15:22:16.1267689: process 'scsqlparser' successfully killed!
15:22:16.1423998: process 'sctrayicon' successfully killed!

>staradmin start db
Starting default (starting database)

[15:32:35, Starcounter (default)]
A fatal error was detected: ScErrCantCreateDbMemoryFile (SCERR4186): The memory
manager was unable to create a memory file to store database memory.

[15:32:35, Starcounter (default)]
ScErrUnexpErrorCreateDbMemFile (SCERR6058): An unexpected error was detected whe
n creating a memory file for database data. OS error=1450 (CreateFileMapping).

>staradmin list db
default
  Running         False
  Host process ID n/a
  Applications    n/a
```

> So if you could check if close too or less then 1/8 physical memory of swapfile is remaining when it occurs this would be useful.

How do I check this?

**Comment by k-rus** [comment]
I tried again and it failed immediately even 1,2GB was available. Page pool is 373MB.

**Comment by bigwad** [comment]
To monitor available memory you may run following commands:

```
logman create counter mem_available -f csv -o c:\temp\mem.csv -si 5 -c "\memory\commit limit""\memory\commited bytes"
logman start mem_available
```

They will create and start custom performance counters collection. Monitoring result will be placed in c:\temp\mem.csv file

To cleanup environment:

```
logman stop mem_available
logman delete mem_available
```

**Comment by k-rus** [comment]
> They will create and start custom performance counters collection. Monitoring result will be placed in c:\temp\mem.csv file

Thank you, but didn't help. The only collected info is time. This is what file contain after I stopped logman:

>"(PDH-CSV 4.0) (Central Europe Standard Time)(-60)"
"02/02/2016 16:06:07.695"
"02/02/2016 16:06:12.696"
"02/02/2016 16:06:17.711"
"02/02/2016 16:06:22.712"
"02/02/2016 16:06:27.711"
"02/02/2016 16:06:32.696"
"02/02/2016 16:06:37.696"
"02/02/2016 16:06:42.711"

**Comment by bigwad** [comment]
Syntax errors in command line Should be:
```
logman create counter mem_available -f csv -o c:\temp\mem.csv -si 5 -c "\memory\commit limit" "\memory\committed bytes"
```

**Comment by k-rus** [comment]
The result:

>"(PDH-CSV 4.0) (Central Europe Standard Time)(-60)","\\RUSLANFOMKI49C1\Memory\Commit Limit","\\RUSLANFOMKI49C1\Memory\Committed Bytes"
"02/02/2016 16:48:10.022","6022688768","3445489664"
"02/02/2016 16:48:15.023","6022688768","3791581184"
"02/02/2016 16:48:20.022","6022688768","3841667072"
"02/02/2016 16:48:25.023","6022688768","3836792832"
"02/02/2016 16:48:30.007","6022688768","3835973632"

**Comment by eriohl** [comment]
Ohh. It seems like there is some debug code checked in fixing segment size to 4 GiB. Might be the cause of the problem...

**Comment by eriohl** [comment]
I get the same error if out of commit space in the case of CreateFileMapping (should be translated to out of memory, I will fix this). So this is most likely the source of the problem. Should have been addressed now then.

**Comment by per-samuelsson** [comment]
For what its worth, I also experienced this earlier this morning. Trying to create a new database, and seeing:

```
ScErrUnexpErrorCreateDbMemFile (SCERR6058): An unexpected error was detected when creating a memory file for database data. OS error=1450 (CreateFileMapping).
```

followed by

```
A fatal error was detected: ScErrCantCreateDbMemoryFile (SCERR4186): The memory manager was unable to create a memory file to store database memory.
```

I'm on a local debug build of **pnext**, last pulled last night.

**Comment by eriohl** [comment]
@per-samuelsson: That is odd since you shouldn't get that error anymore in this case (you should get an out of memory instead). Could you check for this line of code: ```mem_status.ullTotalPhys = 32ULL * _GB;``` in scdata/initps-win.cpp (line 56). Just to make sure you have the latest.

**Comment by k-rus** [comment]
I confirm that it works for me now and I don't experience the problem.

**Comment by per-samuelsson** [comment]
> That is odd since you shouldn't get that error anymore in this case.

Maybe I pulled earlier than your fix. I don't know. It might have been like late afternoon. Also, I don't build Bluestar for **pnext** locally anymore, it was to much of a hazzle IMO. Just building "Level1" and having latest Bluestar builds pulled from the FTP for me. So possibly I didn't get your fix as part of that pull.

> Could you check for this line of code: mem_status.ullTotalPhys = 32ULL * _GB; in scdata/initps-win.cpp (line 56). Just to make sure you have the latest. It shouldn't be there to be clear.

Sorry, can't. See above comment. But I'll make sure to pull a new version later today, and if I should experience it still, I'll get back to you. In case you don't hear anything, I haven't experienced it again.

**Comment by k-rus** [comment]
I guess the issue can be closed.
