### ISSUE TITLE
pnext: nightly build project in Debug configuration

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3333]
It is very valuable to test Starcounter build in Debug configuration, since it executes assertions, which does not exist in Release build.

**Comment by k-rus** [comment]
I run [a personal build in Debug configuration](https://teamcity.starcounter.org/viewLog.html?buildId=733&tab=buildResultsDiv&buildTypeId=Starcounter_PnextDailyWindows) and several tests failed.

**Comment by alemoi** [comment]
Thanks for reporting @k-rus 
Yes, there was an issue with illegal Self calls that I fixed (https://github.com/Starcounter/Starcounter/issues/3332)

**Comment by k-rus** [comment]
You haven't fixed the issue, which is to create a build for Debug configuration.

**Comment by alemoi** [comment]
I added the debug build configuration for Pnext daily now.

**Comment by k-rus** [comment]
> I added the debug build configuration for pnext daily now.

Great! I am not sure if the name is good, but since current daily is an extended build with a lot of tests, it works for the purpose.
