### ISSUE TITLE
How to protect internal Handlers from direct access

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3339]
Is there any solution to mark a handler to be `Self.GET`-able only?

I know, I can check the `CallLevel` property and rise an exception if the call level is more than 0, but this requires additional three lines of code, and the call level could be 0 with `Self.GET` from a commit hook.

The question came from this one: https://github.com/Starcounter/Warehouse/issues/5

In ASP.NET we can mark handle methods with an attributes like `[Internal]`.

cc @alemoi, @chrhol, @warpech

**Comment by miyconst** [comment]
ping

**Comment by warpech** [comment]
Previously we've discussed a new APIs for `Internal.GET`, but it doesn't exist. 

Maybe @alemoi knows of some `HandlerOptions` that solve this (though I am not a big fan of hiding behavior in HandlerOptions).

**Comment by alemoi** [comment]
I checked the code. The handler is registered on gateway only of level is `DefaultLevel`. But I can introduce another option for `HandlerOptions`. How would you like to name it? `CodehostOnly`, `DontRegisterOnGateway`?

**Comment by miyconst** [comment]
I would call it `SelfOnly`, I thought we had something for it, probably it was only in discussions.

**Comment by alemoi** [comment]
Sounds reasonable. I will add this.

**Comment by alemoi** [comment]
Fixed via 9535c3570dbbc3029653e4cd68a66d86626e88c6

**Comment by miyconst** [comment]
@alemoi thank you.

**Comment by warpech** [comment]
Please document: https://github.com/Starcounter/Starcounter/issues/3464
