### ISSUE TITLE
Stable release schedule

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#3340]
The current stable release (2.1.177) is now nearly four months old. Much has happened since then, and as a developer running Starcounter in production I am eager to put the new features and fixes to good use. So, is there any chance we might be seeing a new release soon? :-)

I also have a few release-related suggestions:

1. I think there needs to be a clarification (as in a description on the developer site) of what support commitments you make to stable releases versus development builds. I believe that if this were to be put in writing, it would serve as a mutually beneficial contract between Starcounter and its developer community, ensuring that
  * from a developer's perspective, there is never any doubt as to what level of commitment to expect for a given release; and conversely,
  * developers can't blame Starcounter when things break because they picked a development build over a stable one

2. There should be a fixed release schedule with new stable builds released *at least* quarterly. This achieves two goals:
  * developers are encouraged to use the stable, less buggy version (because it's sufficiently up-to-date)
  * the cost of upgrading applications to work with a new release is "amortized" over several upgrade cycles (consider the amount of work needed to go from the old 2.0 stable to the latest build :-))

/sub @dan31

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/RebelsLounge/blob/master/release_cycle.md

**Comment by dan31** [comment]
Hi @mtornwall! We are preparing to issue a release 2.2. The new release will contain several incompatible changes. In order to manage this and let our partners adopt to the changes and provide feedback, we would like to propose a quarantine routine, when one of nighty-s is promoted as stable, and this promoted nightly is a matter of partner's try-out. If the try-out reveals no need to adjust the changes and is accepted by the partners, the corresponding nightly is established to be the next stable. Otherwise we do the next iteration of a quarantine mode for a nightly with adjustments. More on that is in a follow-up letter to our current users. We aim to solve that during the next week, once the time allows :)

**Comment by k-rus** [comment]
I have internal suggestion that when stable is released it will great to tag corresponding version in git for both Level0 and Level1 with the version tag, like @warpech does for Simplified.

**Comment by dan31** [comment]
@k-rus that is a great suggestion, especially knowing that @alemoi already have it in-place not activated. We had an idea that we tag for any build in general, not only for Stable. This will allow to promote nightlies to stables in a regular way. @alemoi, do you have any objection to activate tagging for our builds?

**Comment by k-rus** [comment]
> This will allow to promote nightlies to stables in a regular way. @alemoi, do you have any objection to activate tagging for our builds?

IMHO, tagging every nightly will make tags not really useful, since it will be too many tags. If I don't mistake it is possible to tag branches in past, so even now it should be possible to tag the stable builds.

**Comment by warpech** [comment]
Definitely tags can be applied to commits in the past. 

Tags can also be moved, replaced and deleted (though this is not advised).

I agree that tagging only stable releases sounds like a good compromise.

**Comment by per-samuelsson** [comment]
> I agree that tagging only stable releases sounds like a good compromise.

Me too.

While we are getting closer to realizing this, can I also propose we take the oppurtunity to take a small step closer to this:

> http://nvie.com/posts/a-successful-git-branching-model/

Take a special look at this section:

> http://nvie.com/posts/a-successful-git-branching-model/#the-main-branches

that states

> We consider `origin/master` to be the main branch where the source code of `HEAD` always reflects a *production-ready* state.

What is it I suggest? That once we are about to release anything we consider a stable, we

1. Define a version of it (outlined in @dan31's OP)
2. Tag it (as suggested by @k-rus @warpech)
3. **Merge it into origin/master** (this comments suggestion)

Building any historic stable (possibly with local patches/tweaks on top of it) then becomes as easy as

1. Checkout and pull master branch (possibly with a certain tag, if you don't want the very last stable)
2. (Optional: Apply patches)
3. Build

That kind of predictability is really nice when someone report a bug (normally coming from the latest stable) and that's the only steps you need to take.

To begin with, we don't need to even change any thing in terms of default branches for build systems, etc. Just that simple thing of merging develop -> master on every new release. If we never touch master for anything else, every such merge will also be a fast-forward merge, and hence never experience any conflicts.

**Comment by per-samuelsson** [comment]
(Just realized I post this in the wrong tracker, and hence the reference to "@dan31's OP" is a bit off, but I think you all get a hang of it anyway). :sunglasses:

**Comment by dan31** [comment]
Guys, I just move that discussion to https://github.com/Starcounter/RebelsLounge/issues/16, since it serves both establishing the release protocol with our partners and releasing 2.2 with all necessary routines discussed. Next releases checklist we can cater for in public tracker.
