### ISSUE TITLE
Error when i changed the namespace of an existing database class

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3342]
When calling `DbMapping.MapExistingObjects() i get this Exception after i renamed the namespace of the database class.

`Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. ScErrSchemaCodeMismatch (SCERR4177): Operation failed be because input does not match schema. CLR Class is not loaded for table Warehouse.Database.Organization
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4177.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in C:\github\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 580
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\github\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 270
   at Starcounter.Hosting.Package.Process() in C:\github\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\github\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\github\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 71
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
`

**Comment by miyconst** [comment]
+1

**Comment by k-rus** [comment]
@andwah Can you provide more information? I don't even understand if the exception complains about new class or old class.

**Comment by miyconst** [comment]
@k-rus, this is about the old class.

The `MapExistingObjects` tries to map records of old class which is no longer loaded into memory. And it rises exception.

**Comment by miyconst** [comment]
@warpech this is the issue I was talking about. It also occurs if I just turn off the app, not only rename the class.

**Comment by k-rus** [comment]
> @k-rus, this is about the old class.
> 
> The MapExistingObjects tries to map records of old class which is no longer loaded into memory. And it rises exception.

Thank you for clarifying! Then it is related to the mapper implementation and not to code host. (does not involve me)

**Comment by chrhol** [comment]
I guess it's a similar problem like in the discussion to #2960 which will get more apparent when we're going to a scheme of smaller private datamodels for each app.

**Comment by alemoi** [comment]
Is there any inheritance involved in the mapped classes?

**Comment by andwah** [comment]
@alemoi No inheritance

**Comment by alemoi** [comment]
Thank you. Then I will have to reproduce this one on my machine, when I am back on Tuesday

**Comment by andwah** [comment]
@alemoi I can help you to set things up so you can reproduce it on you machine.

**Comment by alemoi** [comment]
Great! Do you have some simple way to reproduce?

**Comment by andwah** [comment]
I had a class `Organization` in this `Warehouse.Database`.
I created some `Organization` objects. Then i renamed the namespace to just `Warehouse` and restarted my app,when the app starts it calls `DbMapping.MapExistingObjects()`

**Comment by alemoi** [comment]
I tried to build master branch of Warehouse and have the following error:
```c#
1>------ Build started: Project: Warehouse, Configuration: Debug x64 ------
1>CSC : error CS2001: Source file 'c:\github\Starcounter\Warehouse\src\Packages\DeployedConfigFile.cs' could not be found.
1>CSC : error CS2001: Source file 'c:\github\Starcounter\Warehouse\src\Packages\PackageConfigFile.cs' could not be found.
1>CSC : error CS2001: Source file 'c:\github\Starcounter\Warehouse\src\Packages\PackageManager.cs' could not be found.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by alemoi** [comment]
How did you create `Organization` objects? Just by running standalone app and clicking around?

**Comment by andwah** [comment]
@alemoi In the Warehouse app by clicking `New Organization` button, otherwize you can just do `new Oragnization()` in the code

**Comment by alemoi** [comment]
Ok thanks. Still can't build the project though.

**Comment by alemoi** [comment]
I dug into this and the problem was that `DbHelper.FromID` throws an exception when class is not loaded into code host. Now, those classes that are not loaded are simply ignored (since they can be possibly loaded later, that's why i can not cleanup those relations). Pushed via 2e4e4d3d1bdae087c8b5b45a194e0f26679e637b
