### ISSUE TITLE
JSON design question

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3347]
In my json file I have a lot of this:
```json
    "$VesselOptions": { "Bind": "FilteredVesselOptions" },
    "$IsButtonCreateClickable": { "Bind": "ModelIsValid" },
    "$IsPersonValid": { "Bind": "IsPersonSet" },
    "$BadgeOptions": { "Bind": "FilteredBadgeOptions" },
    "$Persons": { "Bind": "PersonsSearchResult" },
    "$CanModifyPerson": { "Bind": "IsNewPerson" },
    "$Birthday": { "Bind": "DateOfBirth" }
```

because I like to have properties in the code behind that automatically are up to date like:
```csharp
 public bool ModelIsValid {
    get {
        ...
    }
}
```

I could move a few of this properties to my model but most of them are depending on the current page. For example `ModelIsValid` does check among other things if `this.Data` is `null`. It does not make sense to move it somewhere else.

Is there a pattern to reduce the mapping?

**Comment by miyconst** [comment]
I don't think there is a pattern to reduce the mapping in JSON view-model, but you can move it to code behind.

Personally I dislike the "$" in JSON view-model, and on a private Starcounter meeting with @warpech and @per-samuelsson it was decided to rid of this sign at all. So, in the future all of such magic bindings should be done in code behind.

See example here: https://github.com/StarcounterSamples/Barcodes/blob/master/src/Barcodes/ViewModels/BarcodePage.json.cs#L8

**Comment by chrhol** [comment]
We discussed in #2964 a possible way to simplify binding to properties in code-behind. With that issue implemented you would simply use the same name for the property in JSON-by-example and codebehind and get rid of the unnecessary specified "Bind"-properties.

Maybe that issue should be prioritized.

**Comment by per-samuelsson** [comment]
@jwillmer 

We've kind of decided that the recommended pattern for this would be what was suggested in this https://github.com/Starcounter/Starcounter/issues/3105#issuecomment-162450065. But as @chrhol states, #2964 is a requirement for that.

> Maybe #2964 should be prioritized.

Yeah, I think it should. But I remember that we discussed that, and it's not really low hanging. Or could you find a hack around it with the mono-parser? Otherwise, as I remember, the idea was to switch to Roslyn when doing so, wasn't it?

**Comment by miyconst** [comment]
Closing this issue as answered.
