### ISSUE TITLE
Starcounter.Session.RunSync the transaction is readonly

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3349]
Hi!

I've written a helper method that distributes work on the different schedulers:
```
public static void RunAttached(Action a)
        {            
            Session.RunSync(() =>
            {
                a();
            }, SchedulerPartitioner.GetNext());
        }
```
Then all of a sudden when I try to use Db.Transact I get this error:
>ScErrReadOnlyTransaction (SCERR4093): The transaction is readonly and cannot be changed to write-mode.
Version: 2.1.1169.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4093.

I though that all working threads used by Session.RunSync had a default readonly transaction that allows querying for data. But once you want to write you execute a small code block in a Db.Transact.

So why do I get this error? It seems to me that one of the worker threads is bound to a transaction. I don't use ```new Transaction``` at all. 
I use Db.Scope to create readonly "transactions" when I create the two websites hosted. One Db.Scope for each application. 

Do I need to exclude the threads bound to the websites from my helper method?

**Comment by careri** [comment]
Hmm, if my last comment is true we have a problem. That would mean that the worker threads would all be bound to webrequests... that sounds bad

**Comment by dan31** [comment]
Hi @careri! @alemoi is the best to clarify. Maybe what you want to achieve is to be done differently. A closer look is needed. (We are currently conducting a review of RunSync/Async methods to be included into a next Stable). CC @alemoi @chrhol

**Comment by careri** [comment]
I'm thinking maybe you're throwing the wrong exception? I hade a bug in my code that deleted the wrong object. I was suppose to delete a timestamp-instance pointing to my data-object. But instead I deleted the data-object.

I then continued working with the data-object believing that it still existed. Not quite sure how to reproduce in a simple fashion.

I'll get back to you if the problem persists.

**Comment by careri** [comment]
Or might it be that a callback from an BeforeDelete commithook is readonly?

**Comment by alemoi** [comment]
RunSync just schedules a task and waits for its completion. I don't think we set any transaction scopes there. @chrhol do you have any idea on the matter?

**Comment by alemoi** [comment]
I haven't found anything related to transactions in ScheduleTask methods. `Session.RunSync` is gone by the way, so I would suggest to use latest nightly and then let's get back to the problem, if it still persists!

**Comment by alemoi** [comment]
Hi @careri! Let's take it from the beginning: can you please explain why you used `Session.RunSync` and why scheduler ID was supplied?

The old API `Session.RunSync` was just doing old `DbSession.RunSync`. That's why I am curious why you specifically used `Session.RunSync` in your code with scheduler ID. The API behind scheduling task has been changed and that affected session interface as well. Some design problems were found with `Session.ForAll`, that is why it was replaced with `Session.ScheduleTask` interface (same with `Session.RunSync`). More on this you can read here: http://starcounter.io/changes-in-session-and-scheduling-api-starting-from-build-2-1-1183/

Let's try to find how we can correctly upgrade your code!

**Comment by careri** [comment]
Sorry, confusing fieldname in my example. It's a singleto. Instance of DbSession that I store in my helper class

**Comment by alemoi** [comment]
> Sorry, confusing fieldname in my example. It's a singleto. Instance of DbSession that I store in my helper class

Thank you. Yes, now we have `Scheduling.ScheduleTask` singleton that you should use instead of `DbSession`: http://starcounter.io/guides/transactions/running-background-jobs/#basic-information-about-scheduling-in-starcounter

Let us know if your original issue is resolved.

**Comment by careri** [comment]
I'll look into that, thanks

**Comment by alemoi** [comment]
@careri do you still experience problems with this? Thank you for the response!

**Comment by careri** [comment]
Sorry for the late response. Been busy with other development. Haven't seen this in av whiile. You can close this issue
