### ISSUE TITLE
Redundant log entry

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3350]
I just saw this log entry, which does not make sense.

```
Gateway XML: MaximumReceiveContentLength parameter exceeds maximum value of 2096936. Value of 2096936 will be used.
```

cc @alemoi

**Comment by alemoi** [comment]
I just wanted to say that maximun value will be used. I will rephrase the log message

**Comment by miyconst** [comment]
Just add what is the current value set, and it will make sense.

**Comment by alemoi** [comment]
Thanks for suggestion. Changed.
