### ISSUE TITLE
Incorrect number of CPUs detected in Starcounter installer on VMWare

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#3354]
Hi @alemoi, maybe you know how this situation is possible. There is a VMWare virtual machine (GleSYS) with 4 cpu cores attached in a configuration. I see those 4 cpus in a device manager, however they aren't visible in a task manager and also not visible to Starcounter, resulting into this:

<img width="635" alt="untitled" src="https://cloud.githubusercontent.com/assets/7162535/12942811/c3fd7af2-cfdd-11e5-9b34-aff75257e3cf.png">

What would you say? What exactly is the method you use to read up CPU cores number? Maybe that will help me understand what is so special about this machine.

**Comment by dan31** [comment]
Correction: 4 CPUs are actually visible in task manager, I didn't switch to logical CPUs view. I tried both Starcounter PNextNightly installer and Stable installer and they aren't detecting number of CPUs properly. Not a high prio, yet the virtual machine is available for future investigation.

**Comment by alemoi** [comment]
That's strange because we use standard dotNET Api to get the number of processors. So I suppose something is with this API.

**Comment by eriohl** [comment]
Problem is that you have less then 4 GiB RAM (2 GiB according to image). Not the CPU count.

**Comment by alemoi** [comment]
Yes, that's correct. Good you saw that on the screenshot! I will add more specific error message.

**Comment by dan31** [comment]
@eriohl thank you, actually that is obvious right from the pic :) I haven't considered such option and ignored the possibility. @alemoi so we are left with a case of https://github.com/Starcounter/Starcounter/issues/3355. This one I close.

**Comment by alemoi** [comment]
I have improved the error message. Will be available in the coming nightly.
