### ISSUE TITLE
pnext: Non-informative message and installation rollback on Starcounter service

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#3355]
I have two identical machines in VMWare. Just in case, UAC on both is set to the most lower setting and all is run on Administrator. When being installed, on one of the machines I have the following (on the second machine installation is successful):

<img width="1279" alt="untitled3" src="https://cloud.githubusercontent.com/assets/7162535/12944395/fd2894d4-cfe6-11e5-8dea-fa16ca767636.png">

This doesn't happen with Stable installer, but happens regularly with PNext installer.
The point of this issue is to provide better user experience. The installer says to check server logs, however the only entries in the log after installer has finished are as follows:

<img width="258" alt="untitled4" src="https://cloud.githubusercontent.com/assets/7162535/12944433/4413d818-cfe7-11e5-9bd2-ed186a597cba.png">

Is it possible to make the experience be more informative?

**Comment by alemoi** [comment]
Thanks for reporting! So the actual error is not even known as I understand. Can you please check Windows event log if anything is there?

**Comment by bigwad** [comment]
Problem with loading scservicelib.dll
Continue to investigate.

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'scservicel
ib.dll': The specified module could not be found. (Exception from HRESULT: 0x800
7007E)
   at Starcounter.Server.ServerServiceProcess.StartMonitor(String server, Boolea
n logSteps)
   at Starcounter.Server.ServerServiceProcess.RunUntilStopped() in C:\TeamCity\T
eamCity9\buildAgent\work\sc-53\Level1\src\Server\Starcounter.Server\ServerServic
eProcess.cs:line 165
   at scservice.Program.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\
work\sc-53\Level1\src\Server\scservice\Program.cs:line 71
```

**Comment by bigwad** [comment]
Seems like c runtime hasn't been fully installed

**Comment by bigwad** [comment]
The problem has gone after I installed runtime

**Comment by dan31** [comment]
@bigwad thanks for investigation! @alemoi, for some reason the Runtime reported as installed during Starcounter installation, but it hasn't been properly installed in return. Maybe you don't treat all the error codes from the runtime installer?

**Comment by alemoi** [comment]
My prediction is like in the last case: very first time the runtime installation will succeed but be broken, second installation fixes it, not matter if second installation is done by Starcounter or MS direct installer. Do you have environment I can repro the issue?

**Comment by dan31** [comment]
@alemoi I know glesys machines give me this. When I'll be setting the one for @andwah I will try to reproduce it.

**Comment by alemoi** [comment]
Ok, waiting for the reproducible case :)
