### ISSUE TITLE
Session.ForAll is still required

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3357]
The `Session.ForAll` method was replaced with `ScheduleTask`, which are not the same.

I don't really know how this all works underneath, but I think that:

1. It should be possible to get all live sessions at the moment. For example for `LiveStats` application.
2. We should not break compatibility like this. It is still possible to workaround `ForAll` with `ScheduleTask`, but it requires quite a lot of code.
3. We should not mark `ForAll` as `[Deprecated]`, but should rewrite it, so it grabs all live sessions and calls `ScheduleTask` per each. So the method will never be removed.
4. I would really appreciate inline comments for intellisense, as most of the time this is my main and the only manual.
5. I really hate to use `Action` and `Func` as a parameter. The parameters of `Action` and `Func` does not have names, which makes it very difficult to remember what is what.

This code snippet below demonstrates how to wrap such parameters into nice and self-explanatory delegate:

```cs
using System.IO;
using System;

class Session {
    public string ID { get; set; }
    public string Name { get; set; }
}

class Program {
    static Session StaticSession = new Session();
    delegate void ScheduleDelegate(Session session, string sessionId);
    
    static void ScheduleWithDelegate(ScheduleDelegate action) {
        action(StaticSession, StaticSession.ID);
    }
    
    static void ScheduleWithAction(Action<Session, string> action) {
        action(StaticSession, StaticSession.ID);
    }
    
    static void Main() {
        StaticSession.ID = Guid.NewGuid().ToString();
        StaticSession.Name = "My default static session";
        
        ScheduleWithDelegate((session, id) => {
            Console.WriteLine("ScheduleWithDelegate {0} {1}", session.Name, id);
        });
        
        ScheduleWithAction((session, id) => {
            Console.WriteLine("ScheduleWithAction {0} {1}", session.Name, id);
        });
    }
}
```

Note that usage of both of the methods is the same simple.

P.S. You can use this service to compile c# snippets online: http://www.tutorialspoint.com/compile_csharp_online.php

cc @alemoi, @warpech

**Comment by per-samuelsson** [comment]
[Here](https://github.com/Starcounter/Starcounter/issues/3318#issuecomment-178442570) is some relevant discussion we had once it was removed.

**Comment by alemoi** [comment]
Thanks for reporting! I have started the work to recover the `ForAll` API based on new `ScheduleTask`. Will soon be finished!

**Comment by alemoi** [comment]
I just pushed the changes. You can try it out on your application. Any input is welcome!

**Comment by per-samuelsson** [comment]
Nice @alemoi!

/cc @careri

**Comment by miyconst** [comment]
The inline comments are nice, thanks for that.

The `Session.SessionTask` is also self explanatory, now the question is why `Session.ForAll` does not use it.

**Comment by alemoi** [comment]
That was actually on purpose, since Session in ForAll can never be null. And in ScheduleTask it can be. But for consistency I can make it use the same signature.

**Comment by miyconst** [comment]
I would like to keep it consistent.

**Comment by alemoi** [comment]
Input is all I need :) I will change it accordingly.

**Comment by alemoi** [comment]
Thanks for input! You can check the interface in the coming nightly.

**Comment by miyconst** [comment]
Looks good. Closing the issue. Thanks.
