### ISSUE TITLE
Question : How to add Public Web Folder in latest starcounter versions

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3361]
We have tried using "--resourcedir=C:\MyWebsite\Content" but no use, We see only 2 Public web directories in SC Admin, but our directories are not listed in there. In starcounter older version 2.0.3226 we were able to see all the public directories.

![image](https://cloud.githubusercontent.com/assets/4388707/12977706/b07157d4-d0cc-11e5-89cf-b56ed7fc5d00.png)

**Comment by atifsheikh** [comment]
Here is a snapshot of how it looks in SC Admin version 2.0.3226 
![image](https://cloud.githubusercontent.com/assets/4388707/12977764/03a4d368-d0cd-11e5-9a95-a641e0835360.png)

**Comment by per-samuelsson** [comment]
@atifsheikh 

Have you consulted this:
http://starcounter.io/guides/network/static-file-server/

We somewhat recently did some rewriting and polishing of this, maybe it's something that changed. The documentation link instruct how it should work in the latest version. Here's (partial) background leading up to that: #3099.

**Comment by atifsheikh** [comment]
yes i used the mentioned Command line argument from your provided url. I also tried the code line "AppsBootstrapper.AddStaticFileDirectory("C:\\MyWebsite\\Content", 80);" but I am unable to get AppsBootstrapper object.

**Comment by atifsheikh** [comment]
I run the project with following attributes :
-d=adfenix -resourcedir=C:\adfenix-backend\src
-d=adfenix --resourcedir=C:\adfenix-backend\src

but on both cases i can see only 2 public web directories as shown in the 1st image

**Comment by per-samuelsson** [comment]
OK, I see. I'll see if I can help you.

Can you specify the version you are trying this on, and the version you "came from" (i.e. the version where you last know it worked)? I'm guessing the later would be `2.0.3226`. If so, just give me the version you run now (`star -v | clip` will copy the version to the clipboard for you).

**Comment by atifsheikh** [comment]
I am trying on verser 2.1.177. (not showing public folders)
and the older version is 2.0.3226 (this one shows public folders)

**Comment by per-samuelsson** [comment]
Thanks. Give me a few minutes to test a little!

**Comment by atifsheikh** [comment]
Sure

**Comment by per-samuelsson** [comment]
Can you try this in your browser (assuming you are running the "adfenix" database on 8080): http://localhost:8080/staticcontentdir. And paste the JSON string here.

**Comment by atifsheikh** [comment]
This looks good
{"Items":[{"Port":8080,"Folder":"c:\\program files\\starcounter\\clientfiles\\staticfiles"},{"Port":8080,"Folder":"c:\\adfenix-backend\\launcher-master\\src\\launcher\\wwwroot"},{"Port":8080,"Folder":"c:\\adfenix-backend\\useradmin-master\\src\\useradmin\\wwwroot"},{"Port":8080,"Folder":"c:\\adfenix-backend\\signin-master\\src\\signin\\wwwroot"},{"Port":8080,"Folder":"c:\\adfenix-backend\\src\\"}]}

**Comment by atifsheikh** [comment]
I have a gif file in "C:\adfenix-backend\src\sf2.gif "
So if Public Web Folder is working fine, i should be able to access it via http://localhost:8080/adfenix/sf2.gif. But i am unable to do that

**Comment by per-samuelsson** [comment]
> This looks good

I see. Hmm, I'm not sure what that "Public Web Folders" tab is meant to show actually. Could it be something weird with like client side caching? Can you try disable your browser cache and hit F5 on that page? (If you are using Chrome, run Ctrl+Shift+I and enable "Disable cache")

![image](https://cloud.githubusercontent.com/assets/2902045/12978551/ebf8634c-d0d1-11e5-8ec8-4b143fb4a5b2.png)

**Comment by atifsheikh** [comment]
Sorry, my bad. i can access it by going to url "http://localhost:8080/sf2.gif", i was trying "http://localhost:8080/adfenix/sf2.gif"

**Comment by per-samuelsson** [comment]
> Sorry, my bad. i can access it by going to url "http://localhost:8080/sf2.gif", i was trying "http://localhost:8080/adfenix/sf2.gif"

Well, thats good then, isn't it? :smile: Still wonder why you wouldn't see folders under that tab though. Did you try disabling the cache?

**Comment by atifsheikh** [comment]
yes, i still dont see the folders there. even after disabling the cache. But my issue is fixed. Thanks :+1:

**Comment by per-samuelsson** [comment]
> But my issue is fixed. Thanks.

Good to hear. I didn't really do anything, but thanks. :sunglasses:

**Comment by alemoi** [comment]
@per-samuelsson thank you for assisting @atifsheikh to resolve the issue!

**Comment by atifwaqar** [comment]
Hi, I just saw the following syntax from [this url ](http://starcounter.io/guides/network/static-file-server/)

`AppsBootstrapper.AddStaticFileDirectory("C:\\MyWebsite\\Content", 80);`

I am using SC Version 2.2.1.2631. and the Syntax is not working. Am I doing something wrong or missing some info on how to use the syntax?

**Comment by per-samuelsson** [comment]
> I am using SC Version 2.2.1.2631. and the Syntax is not working.

Sorry to hear that. I'm reopening this.

Can you specify in what way it doesn't work? You get a 404 when accessing a static resource in the given folder? Are you providing a relative or an absolute path?

**Comment by atifwaqar** [comment]
I'm not able to build the solution with this line of code. May be I'm missing some reference. This is what I see when I use the code line and try to build :

![image](https://cloud.githubusercontent.com/assets/4388707/16467432/903c1042-3e47-11e6-82cb-a5ce2112162d.png)

**Comment by per-samuelsson** [comment]
> I'm not able to build the solution with this line of code. May be I'm missing some reference.

Aha, I see. Looks like it has been moved to an internal namespace. I think you should be able to use it still though, and I'll ask around some tomorrow to see whats up.

Try adding `using Starcounter.Internal` to the file. Or qualify the type:

```cs
Starcounter.Internal.AppsBootstrapper.AddStaticFileDirectory("C:\\MyWebsite\\Content", 80);
```

**Comment by atifwaqar** [comment]
I tried that as well, Still the same : 
![image](https://cloud.githubusercontent.com/assets/4388707/16467778/188a2cee-3e49-11e6-9ec5-7b6adb2d6f58.png)

**Comment by per-samuelsson** [comment]
You might also need to add a reference to `Starcounter.Apps.JsonPatch.dll` if it's not already referenced in your project.

**Comment by per-samuelsson** [comment]
Can you try:

> You might also need to add a reference to Starcounter.Apps.JsonPatch.dll if it's not already referenced in your project.

**Comment by atifwaqar** [comment]
Also, I've been noticing some strange behavior in SC Version 2.2.1.2631. 
We can have a Hangout chat tomorrow if you want some feedback on the strange behavior.

**Comment by per-samuelsson** [comment]
> Also, I've been noticing some strange behavior in SC Version 2.2.1.2631. 
We can have a Hangout chat tomorrow if you want some feedback on the strange behavior.

We could certainly have a hangout if you want that. But please report the strange behavior as an issue too, even if you just describe it vague in one or two sentences.

**Comment by atifwaqar** [comment]
Awesome, This worked. Thanks :+1: 
> Can you try:
> 
> You might also need to add a reference to Starcounter.Apps.JsonPatch.dll if it's not already referenced in your project.

**Comment by per-samuelsson** [comment]
> Awesome, This worked. Thanks :+1: 

Great. Sorry for the trouble. I'll see if we can have a review on this with the team tomorrow. I'll keep it open until then.

**Comment by atifwaqar** [comment]
> We could certainly have a hangout if you want that. But please report the strange behavior as an issue too, even if you just describe it vague in one or two sentences.

May be its something that you guys coded recently, and its part of your plan. So I suspect it may not be an issue, but i'll still create the issue if you say.

**Comment by per-samuelsson** [comment]
> May be its something that you guys coded recently, and its part of your plan. So I suspect it may not be an issue, but i'll still create the issue if you say.

Is it #3728 you are referring to? Then I think we are already on it (seeing that @alemoi and @dan31 is now involved in it).

**Comment by atifwaqar** [comment]
Yes this is what i was talking
