### ISSUE TITLE
Exclusive access to the session could not be obtained.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3363]
One of my server is malfunctioning. and i get this exception in SC Admin Logs.

System.Exception: ScErrAcquireSessionTimeout (SCERR5008): Exclusive access to the session could not be obtained.
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR5008.
   at Starcounter.GatewayHandlers.StartSessionThatCameWithRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 279
   at Starcounter.GatewayHandlers.HandleHttpRequest(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 398
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR5008

the page is extremely slow, Loads 3 records/rows from a table in 3-4 min.

**Comment by alemoi** [comment]
Thank you for reporting! @chrhol is this timeout exception thrown when session is being in use (without releasing) at the moment? So I suppose some code holds the session and not releasing it.

**Comment by alemoi** [comment]
Can you please explain the structure of your code? Maybe there is a Session.StartUsing() somewhere and no Session.StopUsing() is called?

**Comment by atifsheikh** [comment]
code is as following: 
            Handle.GET("/adfenix/campaign/{?}/view/all", (string status, Request request) =>
            {

                Json page;
                if (!Master.TryNavigateTo("/adfenix/campaign/" + status + "/view/all", request, "/Client/redirecttest.html", out page))
                {
                    return page;
                }
                Server.Partials.Campaign.Campaigns rules = null;
                Db.Scope(() =>
                {
                    rules = new Server.Partials.Campaign.Campaigns()
                {
                    Html = "/client/partials/campaign/campaigns.html"
                };
                Simplified.Ring5.SystemUserSession userSession = Db.SQL<Simplified.Ring5.SystemUserSession>("SELECT o FROM Simplified.Ring5.SystemUserSession o WHERE o.SessionIdString=?", Session.Current.SessionIdString).First;
                var user = userSession.Token.User;
                string group = Master.GetGroup();
//Some more logic but no 
                return rules;
            });

**Comment by atifsheikh** [comment]
but the control enters in this Handler after a long time. for other handlers, as soon as i hit the url, the control enters in the code. (i can monitor it if i have breakpoint at start of handler's code body)

**Comment by alemoi** [comment]
That is why I thought that there is some other code that could block the same session. Do you have any long running handler (that apparently utilizes the same session and not releasing it)  or handlers that do Session.StartUsing()?

**Comment by atifsheikh** [comment]
we have couple of handlers that are long running handlers, but we don not use "StartUsing()" anywhere in out code.

**Comment by chrhol** [comment]
>  @chrhol is this timeout exception thrown when session is being in use (without releasing) at the moment?

Yes, the timeout is set to one minute.

> the page is extremely slow, Loads 3 records/rows from a table in 3-4 min.

This could potientially be a problem I guess. How come it's so slow? Is it doing external requests?

Do you always get this error in the same place or does it only happen sometimes?

**Comment by atifsheikh** [comment]
I found the cause behind this issue. We had a Query which was taking alot of time. 
Previously the query was : 
`ClassifiedAd ca = Db.SQL<AdFenix.Database.ClassifiedAd>("SELECT c FROM AdFenix.Database.ClassifiedAd c WHERE AdFenixAd.TwitterAd=?", this).First;`

and i updated that query to:
`ClassifiedAd ca = Db.SQL<AdFenix.Database.ClassifiedAd>("SELECT c FROM AdFenix.Database.ClassifiedAd c WHERE AdFenixAd=?", this.AdFenixAd).First;`

We have 470954 records in TwitterAd.cs. and the above mentioned query is inside a get constructor in TwitterAd.cs.

**Comment by atifwaqar** [comment]
I am getting the exception in my error log again (from source `Starcounter.Host`), but with different content in it, please let me know if a separate issue needs to be created for this one :

```
System.Exception: ScErrAcquireSessionTimeout (SCERR5008): Exclusive access to the session could not be obtained.
Version: 2.2.1834.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR5008.
   at Starcounter.Session.StartUsing() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 519
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR5008
``` 

And i suspect that this is caused by my code, but i can not pin point the issue, is it possible for you guys to add some more details for this exception?

**Comment by chrhol** [comment]
Hi atif, 
Could you try to run it on a newer version of Starcounter? Parts of this code have already been changed, to retry getting access to the session a couple of times before failing. Also the id of the session should printed out in the logentry now. 

It could simply be that the timeout in your version is too short.

**Comment by atifwaqar** [comment]
Sure. and by newer version of Starcounter you mean the latest nightly build? 
If so, do you think it is stable enough to run on a Live server?

**Comment by chrhol** [comment]
> Sure. and by newer version of Starcounter you mean the latest nightly build? 

Yeah, that would be best I think.

> If so, do you think it is stable enough to run on a Live server?

Which version are you using now on the liveservers? Or is this problem occurring live? Maybe you also want to wait for #3604 before upgrading.

**Comment by atifwaqar** [comment]
> Which version are you using now on the liveservers? Or is this problem occurring live? Maybe you also want to wait for #3604 before upgrading.

I am using the latest stable build 2.2.1834 on all live servers. And sure I can wait for the referred issue. Any Idea when is the expected date fot that fix?

**Comment by chrhol** [comment]
We're currently working on the other issue so hopefully we will find and solve it during the day. I'll let you know when we get closer to a solution.

**Comment by careri** [comment]
I get the same exception. But I get it when I'm debugging. Maybe you should check if the debugger is breaking before throwing the exception?

**Comment by per-samuelsson** [comment]
> Maybe you should check if the debugger is breaking before throwing the exception?

[Debugger.IsAttached](https://msdn.microsoft.com/en-us/library/system.diagnostics.debugger.isattached(v=vs.110).aspx).

**Comment by atifwaqar** [comment]
@careri I guess you are right. when i detached my debugger, I stopped getting this error in log.
@per-samuelsson you can close this issue now. 
Thanks guys :)

**Comment by chrhol** [comment]
Thanks for the input @careri and great that you found out it was the same problem @atifwaqar . I have some other changes for sessions pending (just waiting for the next stable to be released). I will make sure that I include the check for if the debugger is attached or not.
