### ISSUE TITLE
pnext: Request for info about new data files

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3365]
In **pnext**, the physical files have changed somewhat. No more image files, instead a `.cfg`.

While I'm at #3362, I figured I'd take height for this in terms of what can be given. Is there any decided (internal or public) issue/documentation where I can read about what to expect and what we should support? For example, should we still support having log files and the `cfg` in different directories (in the past, we supported specific image- and transaction logs directories, since way back in history, there was a strategy to keep the write-ahead, disk-spin-forward transaction log on a separate disk, not for it to interfere with checkpoints. I guess that's kind of not the case any more).

@eriohl @bigwad, could you provide some insight/pointers?

**Comment by per-samuelsson** [comment]
Relate to #3346.

**Comment by per-samuelsson** [comment]
> (in the past, we supported specific image- and transaction logs directories, since way back in history, there was a strategy to keep the write-ahead, disk-spin-forward transaction log on a separate disk, not for it to interfere with checkpoints. I guess that's kind of not the case any more)

Just recalled I rather recently adapted the admin server regarding this and by looking there, it looks like we utilize only a single data directory now. Would still be good if you guys could confirm that, @eriohl, @bigwad.

**Comment by eriohl** [comment]
The cfg file is not a replacement for the image file. It is not written after database creation and only read at startup. Would be silly to put it in another directory.

The checkpoint replacement, the optlog files, would possibly, but probably not, benefit by being put on a different directories (it reads the log while creating it so it would still interfere). But I figured that no one would actually do that anyway so I figured not worth the added complexity. So now there is only one log directory.

But configuration on where this is put (as well as backup and such) is not finished. @bigwad is working on this.

**Comment by per-samuelsson** [comment]
> But configuration on where this is put (as well as backup and such) is not finished. @bigwad is working on this.

I see. Then, until we get settled, I'll just keep things as they are. That is: put the `.cfg` in the `ImageDirectory` by default, logs in the `TransactionLogDirectory` and keep to have them point to the same physical directory by default. In the REST API I'm now extending, I'll just expose a single "Data" directory, and that value would set those two directories to the same single path. That makes for as little work as possible right now, and I don't want to get fancy rewriting when things underneath is not finally settled.

**Comment by eriohl** [comment]
https://github.com/Starcounter/CompanyTrack/issues/177

**Comment by per-samuelsson** [comment]
> Starcounter/CompanyTrack#177

Thanks. I think I know now what I need to know and asked for.
