### ISSUE TITLE
Nightly develop failed due to insufficient disk space

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3366]
[Last nightly](https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1114#_focus=8047) failed with:

>Error: ScErrNotEnoughDiskSpace (SCERR3031): Operation failed due to insufficient disk space. OS error=112 (WriteFile).

**Comment by alemoi** [comment]
Thank you for reporting! I just checked and it has free space. I moved cleanup routine earlier than nightly, so now it should be fine. Closing until further problems.
