### ISSUE TITLE
AppName is not defined

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#3369]
For some reason this issue is not gotten enough attention, hence I have to escalate it and bump it more explicitly. This is what it impedes so far:
https://github.com/Starcounter/Starcounter/issues/3097
https://github.com/Starcounter/Starcounter/issues/2902
https://github.com/Starcounter/InvoiceDemo/issues/55
https://github.com/StarcounterSamples/SignIn/issues/7
It also kills off automatic app namespace resolution in SQL queries in timer's scheduled task, as in http://starcounter.io/guides/transactions/running-background-jobs/ examples. I promote to include the fix in 2.2 and make a fix asap. Currently @alemoi is busy with other works, hence I assign @chrhol there. Correct this if reasonable.
CC @alemoi @per-samuelsson @warpech @andwah

**Comment by dan31** [comment]
Please let's take care of a proper postmortem for this bug. I'm curious how it became broken to prevent such in future.

**Comment by alemoi** [comment]
There was a suggestion from Johan to traverse the stack up to find the app name (if its not already defined of course) .

**Comment by warpech** [comment]
I am able to help with hunting down #2902, Starcounter/InvoiceDemo#55, StarcounterSamples/SignIn#7 - these need to be fixed in JSON merger. Thank you for marking this as a showstopper.

I have no idea how can this be related to https://github.com/Starcounter/Starcounter/issues/3097 and SQL queries in scheduled tasks - but that's possible. I think @chrhol should be able to provide more info.

**Comment by dan31** [comment]
Shortly, the AppName is thread static, hence not visible from non-starcounter spawned threads. So these issues should all be related. Maybe I'm wrong there @chrhol and #2902 is simpler than #3097? For the latter at least, I talked to @alemoi and we don't see any other way rather than traversing the managed stack.

**Comment by warpech** [comment]
I'd just like to add that the fix for this is very welcome because it is indeed very annoying.

**Comment by chrhol** [comment]
> I have no idea how can this be related to #3097 and SQL queries in scheduled tasks - but that's possible. 

They are not, these are two separate issues with two separate solutions.

> There was a suggestion from Johan to traverse the stack up to find the app name (if its not already defined of course) .

Is that viable? I thought an operation like that is superslow? So for every spawned, non-starcounter thread we have to traverse the stack and try to find an appname.

**Comment by per-samuelsson** [comment]
> Is that viable?

I was thinking the exact same thing. I don't think we want to go that way. Even if it would only kick in when the name was not assigned.

**Comment by dan31** [comment]
Removed showstopper, added it though to #2902. The current one needs more thinking from us.

**Comment by warpech** [comment]
All the linked issues apart from https://github.com/Starcounter/Starcounter/issues/3097 are now fixed. Closing.
