### ISSUE TITLE
Correspondence between Starcounter Level1 and Edition Libraries

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3371]
How are Edition Libraries provided to Starcounter build? I build Starcounter from past and thus want to have Edition Libraries, which are from the same time. How do I do it? With Level0 it is easy, I just need to have a source code locally. Is it possible to do the same with Edition Libraries?

**Comment by k-rus** [comment]
I found the answer, which is confirmed by @per-samuelsson. I need to obtain `Simplified` repo and build it. The build output of it goes to build output Level1, which allows to control the version to be used in Level1 build.
Note `Public Assemblies` might need to be updated manually.

**Comment by alemoi** [comment]
Good question!

I have updated the build system with information on building EditionLibraries: https://github.com/Starcounter/RebelsLounge/blob/master/buildsystem.md#building-editionlibraries
