### ISSUE TITLE
Performance degradation in Self calls (scllvm generated code in general)

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3375]
As you know we have some performance statistics for the build server: https://teamcity.starcounter.org/viewType.html?buildTypeId=Starcounter_DevelopNightly&tab=buildTypeStatistics

I noticed a severe degradation in `NumSimpleSelfGetsPerSec` which are caused by the following changes: https://teamcity.starcounter.org/viewLog.html?buildId=899&buildTypeId=Starcounter_DevelopNightly&tab=buildChangesDiv

@eriohl seems that scllvm started to produce much slower code after your changes. Do you have an idea why?

**Comment by alemoi** [comment]
Clarification: Self uses URI matcher (generated code compiled by scllvm) to determine which handler to execute.

**Comment by eriohl** [comment]
Odd. Generally optimization doesn't reduce performance. The performance of generated code for indexes went up a log. Maybe the test includes the code generation time or something?

**Comment by eriohl** [comment]
@alemoi Why am I assinged this one. What am I expected to do with it?

**Comment by alemoi** [comment]
I will assign this to myself, and will check the test details and your changes.

**Comment by alemoi** [comment]
The problem was in measuring the first Self call that includes code generation/compilation, which is taking significant time since the amount of handlers is 1000. Now the performance measurement is corrected as one can see in the stat graphs. @eriohl thank you for the tip.
