### ISSUE TITLE
How do I start an application in a non-default database from Visual Studio?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3380]
I have several applications which has `[Database]` classes inherited from `Simplified`. If any of the apps has some data in those tables, then they don't work separately.

I want to create two databases and don't run them together, but I can't find a way how to start an app into a specific database from Visual Studio.

cc @alemoi, @chrhol

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Starcounter/issues/3094

**Comment by per-samuelsson** [comment]
@miyconst 

`Project | Properties | Debug | Command line arguments` support most of what `star` support, e.g. specifying a datbase such as:

![image](https://cloud.githubusercontent.com/assets/2902045/13104819/cbbdaef6-d55f-11e5-933e-f1c8dda21a12.png)

**Comment by miyconst** [comment]
Thanks @per-samuelsson!

Looks like we have it documented.
http://starcounter.io/guides/tools/staradmin/

**Comment by warpech** [comment]
Not really! http://starcounter.io/guides/tools/staradmin/ is about `staradmin`. As I just learned, VS is using `star`. @per-samuelsson could you document this on http://starcounter.io/guides/tools/starting-and-stopping-apps/?

**Comment by miyconst** [comment]
@warpech good catch!

**Comment by per-samuelsson** [comment]
> As I just learned, VS is using `star`. 

Minor note, so we don't confuse anyone: VS is not actually spawning `star.exe`. Instead, they both build on a common underlying (REST-based) API to get things done, where jobs are coordinated by a shared admin server. Internally, I'm using the term "management clients" when referring to all components that utilize this same API - `star.exe`, `staradmin.exe`, the Visual Studio extension and (with a slightly different approach) our Web Admin tool.

> @per-samuelsson could you document this on http://starcounter.io/guides/tools/starting-and-stopping-apps/?

Well, yeah, in like a year or two when things slow down a bit. :wink:

**Comment by dan31** [comment]
Was just working with the documentation a bit, and added a short explanation along: http://starcounter.io/guides/tools/starting-and-stopping-apps/#starting-app-from-visual-studio-in-a-specific-database.

**Comment by miyconst** [comment]
@dan31 thanks. @warpech do you think it's enough to close the issue?

**Comment by warpech** [comment]
Yes, I think so. I have added a screenshot to the page.
