### ISSUE TITLE
pnext: Access violation (C0000005) detected at bmx.cpp:63 (Thread 4304)

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3381]
Playing around with Warehouse app Starcounter database crashed with the following error:

```
Access violation (C0000005) detected at bmx.cpp:63 (Thread 4304).
```

No more details. All apps got stopped.

If this is something wrong in the application, the error should explain what is wrong.

cc @alemoi, @chrhol, @eriohl

**Comment by miyconst** [comment]
```
Starcounter-PnextNightlyBuilds-2.3.852
```

**Comment by miyconst** [comment]
This issue is reproducible. Steps:

1. Start [Warehouse](https://github.com/Starcounter/Warehouse) application.
2. Start SignIn application.
3. Navigate to `http://localhost:8080/warehouse/`.
4. Sign in with admin/admin.
5. Create an application.
6. Upload a package for the application.
7. Check that the package has been successfully added to the application page.
8. Upload same package again.
9. Navigate back to home page.
10. Navigate to application details page.
11. Exception should be here.
12. If the exception does not happen, navigate to some more pages, up to five times.

cc @andwah

**Comment by dan31** [comment]
@miyconst Please when using pnext as of now, add "pnext: " to the beginning of the title and add a milestone "pnext" as well. Thank you!

**Comment by miyconst** [comment]
@dan31 sure, did so.

**Comment by dan31** [comment]
@miyconst is this reproducible for you?

**Comment by miyconst** [comment]
Yes, it is reproducible on my office machine. Will also test on my home machine.

**Comment by dan31** [comment]
@miyconst please upload the test case somewhere like Dropbox and provide a link to here.

**Comment by andwah** [comment]
I did some testing on the "develop" branch and i have not yet got any errors

**Comment by miyconst** [comment]
@dan31 what kind of test case can I upload? The application source code is available on GitHub. Starcounter version I provided, what else is missing?

**Comment by dan31** [comment]
@miyconst, thanks for clarification, so the empty database case should also reproduce the error, right?

**Comment by miyconst** [comment]
Yes. It was like this for me. I will double check that tomorrow again.

**Comment by miyconst** [comment]
No longer reproducible in the latest pnext (`Starcounter-PnextNightlyBuilds-2.3.864`). Closing the issue. Will reopen if happens again.
