### ISSUE TITLE
stari_context_get_index_setspec() asserted on the global index

### ISSUE THREAD

**Issue by alexanderstc** [Starcounter/Starcounter#3385]
Please run metalayer_functest on branch alexander-get_index_setspec in debug mode.

First, stari_context_get_index_infos_by_setspec() is called on setspec "",
stari_context_get_index_setspec() is called on returned index info, works OK.

Then, stari_context_get_index_infos_by_setspec() is called on setspec "~a~",
stari_context_get_index_setspec() is called on returned index info which is still the global index
with setspec "", debug assert is triggered.

**Comment by eriohl** [comment]
This is how it is supposed to work because all indexes on set "" is also on "~a~" (because "~a~" inherits ""). However, you can exclude inherited indexes by setting the STAR_EXCLUDE_INHERITED. Which I did in your branch and seems to work after that (at least the test passes).

Some need for documentation on my part I think.

**Comment by alexanderstc** [comment]
> Which I did in your branch and seems to work after that (at least the test passes).

No, it doesn't pass. The assertion kicks in at a later stage.

sccoredb.cpp line 4960:
_SC_ASSERT_DEBUG(value[ir] == 0);

**Comment by eriohl** [comment]
Ahh. Missunderstanding. I got the impression that the problem was that inherited indexes wasn't filtered on call to stari_context_get_index_infos_by_setspec.

The problem turns out is that the TT4 decoder doesn't add null termination to the end of the string is passing and empty string.

**Comment by eriohl** [comment]
Ok. Fixed the bug in the TT4 decoder and reverted my previous change.

**Comment by alexanderstc** [comment]
It works now, thans.
STAR_EXCLUDE_INHERITED flag is also useful.
