### ISSUE TITLE
Question : How to delete a table from Database

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3386]
I am trying to unload my DB using the following command : 
> staradmin -d=default unload db --file=data.sql

and i get an exception saying : 
> Table StarcounterApplication5.Image cannot be unloaded.

Now I do not recognize this table, and i want to delete it from my DB so i can proceed with my DB UnLoading. How can I delete this table?

**Comment by per-samuelsson** [comment]
@atifsheikh 

Have you tried `DROP TABLE StarcounterApplication5.Image`?

**Comment by atifsheikh** [comment]
:+1: i tried  `DROP StarcounterApplication5.Image` before and it gave me error. But your command worked. Thanks :)
