### ISSUE TITLE
pnext: ScErrTableNotFound (SCERR4230) after several hours running

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3392]
I left five databases running (on the same SC installation) overnight, all of them running `LogStreamer` and `Bulker`. When I came in this morning, I was greeted with an exception that should not be possible since there is only ever two tables modified (`LogStreamer.LastPosition` and `Bulker.Record`), and both applications are running on all databases (also running after exception).

There are no relevant entries in the Starcounter Administrator log. We absolutely, positively, have to report the table name with SCERR4230.

```
ScErrTableNotFound (SCERR4230): Table with specified name not found.\r\nVersion: 2.3.864.\r\nHelp page: https://github.com/Starcounter/Starcounter/wiki/SCERR4230.
   at Starcounter.TransactionLog.LogApplicator.Apply(TransactionData transaction_data) in C:\TeamCity\TeamCity9\buildAgent\work\sc-61\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 16
   at LogStreamer.LogStreamerSession.<>c__DisplayClass112_0.<ProcessIncomingTransaction>b__0() in C:\Proj\LogStreamer\LogStreamerSession.cs:line 535
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity9\buildAgent\work\sc-61\Level1\src\Starcounter\Db.cs:line 272
```

The WebSocket message that triggered the exception. As you can see, no tables except `Bulker.Record` are referenced here, but `LogStreamer.LastPosition` is also modified apart from these.

`RPu12558  TI"Bulker.Record" r20029000 C"oid" u20029000  C"oidSum" u887792127720  C"origin" "ground"   I"Bulker.Record" r20028999 C"oid" u20028999  C"oidSum" u887772098720  C"origin" "ground"   I"Bulker.Record" r20028998 C"oid" u20028998  C"oidSum" u887752069721  C"origin" "ground"   I"Bulker.Record" r20028997 C"oid" u20028997  C"oidSum" u887732040723  C"origin" "ground"   I"Bulker.Record" r20028996 C"oid" u20028996  C"oidSum" u887712011726  C"origin" "ground"   I"Bulker.Record" r20028995 C"oid" u20028995  C"oidSum" u887691982730  C"origin" "ground"   I"Bulker.Record" r20028994 C"oid" u20028994  C"oidSum" u887671953735  C"origin" "ground"   I"Bulker.Record" r20028993 C"oid" u20028993  C"oidSum" u887651924741  C"origin" "ground"   I"Bulker.Record" r20028992 C"oid" u20028992  C"oidSum" u887631895748  C"origin" "ground"   I"Bulker.Record" r20028991 C"oid" u20028991  C"oidSum" u887611866756  C"origin" "ground"`

/cc @bigwad @eriohl

**Comment by linkdata** [comment]
Continuing, I get lots more of the same exception (note I can still query both of the tables in the Administrator). Then I get this one:

```
"ScErrSqlUnknownColumn (SCERR7038): The column is unknown. The name of the column or property specified in the query is unknown and cannot be matched to a database column.\r\nVersion: 2.3.864.\r\nHelp page: https://github.com/Starcounter/Starcounter/wiki/SCERR7038."
   at Starcounter.TransactionLog.LogApplicator.fill_record(UInt64 object_id, UInt64 object_ref, TableDef table_def, column_update[] columns) in C:\TeamCity\TeamCity9\buildAgent\work\sc-61\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 60
   at Starcounter.TransactionLog.LogApplicator.Apply(TransactionData transaction_data) in C:\TeamCity\TeamCity9\buildAgent\work\sc-61\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 25
   at LogStreamer.LogStreamerSession.<>c__DisplayClass112_0.<ProcessIncomingTransaction>b__0() in C:\Proj\LogStreamer\LogStreamerSession.cs:line 535
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity9\buildAgent\work\sc-61\Level1\src\Starcounter\Db.cs:line 272
```

**Comment by bigwad** [comment]
ScErrTableNotFound  is thrown by LogApplicator when it fails to find table using Db.LookupTable() method. Db.LookupTable() uses metadata to construct table definition, so cc @k-rus 
As to ScErrSqlUnknownColumn - it is thrown when we've found table using Db.LookupTable() but there is no definition for required column, thus maybe some metadata missed as well.

**Comment by k-rus** [comment]
> ScErrTableNotFound is thrown by LogApplicator when it fails to find table using Db.LookupTable() method. Db.LookupTable() uses metadata to construct table definition, so cc @k-rus

Thank you for clarifying. `LookupTable` will be rewritten, so the message will be improved with the table name and the its behaviour itself might improve. This is related to #3378.



> As to ScErrSqlUnknownColumn - it is thrown when we've found table using Db.LookupTable() but there is no definition for required column, thus maybe some metadata missed as well.

Can you clarify, where is the exception thrown from? Improvement of `LookupTable` might improve this behaviour too.

**Comment by dan31** [comment]
Just to reassure: there are no changes in classes during this run. It was just left running and suddenly tables have gone. Might it be connected to logopt-related issue https://github.com/Starcounter/Starcounter/issues/3359? CC @bigwad @k-rus @eriohl

**Comment by bigwad** [comment]
As Db.LookupTable() doesn't throw on missed table - both exceptions are thrown from the client of Db.LookupTable(), namely LogApplicator.

**Comment by bigwad** [comment]
> Might it be connected to logopt-related issue #3359?

That is unlikely, as #3359 requires database reload

**Comment by eriohl** [comment]
We can reproduce it then I understand? Why not just debug it and see why Db.LookupTable fails?

**Comment by linkdata** [comment]
It's inconsistent, and so hard to reproduce. I'll try, but someone should look at the underlying code for clues to how it could happen.

**Comment by k-rus** [comment]
> As Db.LookupTable() doesn't throw on missed table - both exceptions are thrown from the client of Db.LookupTable(), namely LogApplicator.

You are right. It returns `null` if the table is not found. It would be great if you improve your error message with the table name information.

> As to ScErrSqlUnknownColumn - it is thrown when we've found table using Db.LookupTable() but there is no definition for required column, thus maybe some metadata missed as well.

Can you use another error code, since it has nothing to do with SQL? And adding information about the column and the table might help users.

**Comment by eriohl** [comment]
> It's inconsistent, and so hard to reproduce. I'll try, but someone should look at the underlying code for clues to how it could happen.

From discussion I interpret it that the problem is that Db.LookupTable either finds no layout with the specific name or the wrong layout (or rather that the layout if finds doesn't match the transaction data). What it does is to translate the input string to token and then lookup layout from token. If this is so then it seems to indicate that either input is bad or that there is something wrong with the index on tokens or layouts on token. I think the later is somewhat unlikely since these indexes are not even updated unless memory is trashed somehow (which should lead to less consistent errors one would think).

Could it be then that the input message gets messed up somewhere on the way?

**Comment by k-rus** [comment]
> From discussion I interpret it that the problem is that Db.LookupTable either finds no layout with the specific name or the wrong layout (or rather that the layout if finds doesn't match the transaction data). What it does is to translate the input string to token and then lookup layout from token. If this is so then it seems to indicate that either input is bad or that there is something wrong with the index on tokens or layouts on token. I think the later is somewhat unlikely since these indexes are not even updated unless memory is trashed somehow (which should lead to less consistent errors one would think).

Implementation of `Db.LookupTable` is incorrect (see for example #3387). I am planning to fix it that it uses metalayer API. The current problem is that if a table was removed, while layout still exists, it will find the layout for non-existing table.



> Could it be then that the input message gets messed up somewhere on the way?

The message is created by `LogApplicator`, if I understood your question correctly.

**Comment by dan31** [comment]
@k-rus if I understand you correctly, your fix will not help resolve the current issue, right? The current issue appears to be somewhat different, since it designates disorder with no manipulation on schema.

**Comment by k-rus** [comment]
> @k-rus if I understand you correctly, your fix will not help resolve the current issue, right? The current issue appears to be somewhat different, since it designates disorder with no manipulation on schema.

I don't know if my fix will solve the issue or not, since the issue cannot be reproduced.

**Comment by dan31** [comment]
@linkdata what happens if you stop all Bulker instances, start the database and then start some modified Bulker which only attempts to insert a single ```Record``` into it. Does the situation reproduce?

**Comment by linkdata** [comment]
I'm having strange problems running Bulker and LogStreamer in debug build - heavy CPU load, no actual work being done. Inspecting the processes and threads show a Bulker query and TransactionLog.LogManager.OpenLog() using up all CPU. Investigating.

**Comment by k-rus** [comment]
I can think that table not found error might happened due to running new version of pnext against an existing database, created with older version of pnext. I noticed that pnext always contains several tables, which are not meta-data. I don't know what are the tables for and how often are their schemas changed.

**Comment by linkdata** [comment]
The heavy CPU load is caused by the log reader while it's scanning the log file. Using the debug build, it will take a long time to get to the initial reading position (even for a small database it can take minutes or hours). @bigwad may need to look into speeding it up.

> I can think that table not found error might happened due to running new version of pnext against an existing database, created with older version of pnext.

But the error happens in the middle of a run - it's been accessing the tables being referenced thousands of times, then it fails a couple of times and then all is well again.

**Comment by k-rus** [comment]
> But the error happens in the middle of a run - it's been accessing the tables being referenced thousands of times, then it fails a couple of times and then all is well again.

Thank you for clarifying. I misunderstood where it happens.I thought it was starting. @bigwad uses `Db.LookupTable()`, which is not designed to be used in runtime, but is for bootstrapping. For runtime, queries against meta-data tables should be used.
On the other side I don't see why `Db.LookupTable()' should return `null`, why it does not find a table.

**Comment by linkdata** [comment]
After leaving three databases running LogStreamer on a debug build of SC over the weekend, the error failed to materialize. This leads me to believe it's probably a race condition. I'll see if I can push it a bit harder.

**Comment by linkdata** [comment]
> @bigwad uses Db.LookupTable(), which is not designed to be used in runtime, but is for bootstrapping. 

That's interesting. It should be changed, ofc, but do you also think it's likely to be the source of the problem? 

@bigwad, please let me know when `TransactionLog` have been changed over to meta-data tables as well, and I'll try to reproduce it in release mode under high load.

**Comment by k-rus** [comment]
> It should be changed, ofc, but do you also think it's likely to be the source of the problem?

I don't see why it should fail. The only reason for the error is if `sccoredb.stari_context_get_layout_infos_by_token`, implemented by @eriohl,  does not find any results, while it should.

`Db.LookupTable` is very expensive method as it creates many new objects in the object heap. Furthermore, the result of it should never be used outside bootstrapped. The information, which it creates, is already stored in the binding list.

**Comment by linkdata** [comment]
> I don't see why it should fail. The only reason for the error is if sccoredb.stari_context_get_layout_infos_by_token, implemented by @eriohl, does not find any results, while it should.

Well, unless the implementation is thread-safe, it's likely to fail under high load when the likelihood of multiple simultaneous lookups becomes higher.

**Comment by k-rus** [comment]
Another reason can be that `star_get_token`, implemented by @alexanderstc, returns a non-existing token, or problem with pInvoke, which is unlikely. If I understand correctly, `star_get_token` reads meta-data in the database, i.e., querying the database using kernel API, thus I don't expect it should fail.

**Comment by bigwad** [comment]
>@bigwad, please let me know when TransactionLog have been changed over to meta-data tables as well, and I'll try to reproduce it in release mode under high load.

I doubt it's the way to go. To query raw metadata LogApplicator would do all the same actions as  Db.LookupTable does. No reason to duplicate knowledge about metadata structures. Perhaps Db.LookupTable requires some redesign to ensure it may be called from LogApplicator, but I don't see why it can't be called as is. As Ruslan doesn't see why it may fail, me neither.

>Db.LookupTable is very expensive method as it creates many new objects in the object heap. Furthermore, the result of it should never be used outside bootstrapper. The information, which it creates, is already stored in the binding list.

LogStreamer creates a bunch of objects as well, so it's unlikely to add much performance impact. Sure, subject to profiling. And not using binding lists not only decouples the code, but adds possibility to replicate data for apps not being loaded yet.

**Comment by k-rus** [comment]
> Sure, subject to profiling.

Do you call `Db.LookupTable` once per table at runtime or is it called many times per the same table?



> And not using binding lists not only decouples the code, but adds possibility to replicate data for apps not being loaded yet.

Thank you for clarifying. It's correct that binding contains only tables infos for loaded classes.

> Perhaps Db.LookupTable requires some redesign to ensure it may be called from LogApplicator, but I don't see why it can't be called as is.

Does LogApplicator need to know about all layouts, which are presented for the given table?

**Comment by bigwad** [comment]
> Do you call Db.LookupTable once per table at runtime or is it called many times per the same table?

Now it's called for every record being inserted/updated

>Does LogApplicator need to know about all layouts, which are presented for the given table?

Unfortunately, I'm not exactly sure what do you mean here. Is it related to table upgrade?
For record being updated LogApplicator needs to know primitive type of each named column and column's index in the record. And for record being inserted it additionally needs layout handle.

**Comment by k-rus** [comment]
> Do you call Db.LookupTable once per table at runtime or is it called many times per the same table?
> Now it's called for every record being inserted/updated

This means that GC needs to clean up all the objects created. Under heavy load as in this issue GC should work a lot.



> Unfortunately, I'm not exactly sure what do you mean here. Is it related to table upgrade?
> For record being updated LogApplicator needs to know primitive type of each named column and column's index in the record. And for record being inserted it additionally needs layout handle.

Same table/type can contain records with different layouts. Currently, it happens if a table was altered with additional columns. `Db.LookupTable` collects the list of layout handles, which might be not needed for your purpose.

**Comment by bigwad** [comment]
>This means that GC needs to clean up all the objects created. Under heavy load as in this issue GC should work a lot.

As mentioned, records themselves (column names, values) being processed are allocated on the heap as well.

>Same table/type can contain records with different layouts. Currently, it happens if a table was altered with additional columns. Db.LookupTable collects the list of layout handles, which might be not needed for your purpose.

As I see from the code, Db.LookupTable peeks the first layout it finds. As to different layouts - are those layouts have to be compatible thus index for existing column never changes? If this is true - than getting the most recent layout should work for LogApplicator.

**Comment by k-rus** [comment]
> As I see from the code, Db.LookupTable peeks the first layout it finds.

No, it uses the expected layout, which is defined in the meta-data.



> As to different layouts - are those layouts have to be compatible thus index for existing column never changes?

I don't fully understand your question. It is correct that layouts have to be compatible or at least compatible now, however index needs to adapt to different layouts for the set specifier, which is index for. @eriohl knows that details how it adapts. The main concern is when inherited layout is added.

**Comment by bigwad** [comment]
LogApplicator doesn't rely on indices. The only it needs is the right column type and column index (here by index I mean column number in layout) based on column name to update the record. So it behaves mostly like an UPDATE statement. Does expected layout provide this information correctly?
There are some tests for LogApplicator, that test updating column in the base class via the record of descendant class. No problems with this so far.

**Comment by linkdata** [comment]
> As mentioned, records themselves (column names, values) being processed are allocated on the heap as well.

I don't think I understood that correctly. Are you making the argument that since we allocate (at least) (numrecords) x 2 objects on the heap already, increasing it to (numrecords) x 2 x ("many new objects") shouldn't affect performance noticeably?

The LogStreamer might be processing thousands of records each second, so unless "many new objects" is a low single digit number, I think it'd be worth at least investigating moving away from doing calls to `Db.LookupTable()` for each record.

And then there's the concurrency issue. SELECTing from metadata tables should be fine from a thread safety point of view, but `Db.LookupTable()` may not be.

**Comment by bigwad** [comment]
>I think it'd be worth at least investigating moving away from doing calls to Db.LookupTable() for each record.

That's what I mentioned as a subject to profiling. Each movement away from calling Db.LookupTable() for each record will either complicate the code (in case of querying metadata manually) or introduce cache and related coherency issues or both. Sure, will have to do that anyway, if there is a significant performance impact.

>And then there's the concurrency issue. SELECTing from metadata tables should be fine from a thread safety point of view, but Db.LookupTable() may not be.

It's the one point of what is currently discussing with Ruslan. In any case, there should be a method that abstracts matadata schema from LogApplicator. Current state of Db.LookupTable() maybe not perfect for LogApplicator's purpose but at least no obvious reason to fail.

**Comment by eriohl** [comment]
All kernel interface functions (except for initialisation) are made thread safe in the same way (i e isolated contexts). So ```stari_context_get_layout_infos_by_token``` is thread safe (or there is a bug and no kernel interface functions are thread safe).

**Comment by linkdata** [comment]
> All kernel interface functions (except for initialisation) are made thread safe in the same way (i e isolated contexts).

`stari_context_get_layout_infos_by_token()` and other kernel calls should be fine then, as this is all done inside a database transaction.

**Comment by k-rus** [comment]
> increasing it to (numrecords) x (2 + ("many new objects")) shouldn't affect performance noticeably?

Just for information `LookupTable` creates much more objects. Per each successful call it creates as many objects as columns in the layout + 1 object + 1 array.

Using `Db.SQL` will be the same inefficient as it materialises all query results and queries will search for instances of meta-columns and meta-tables.

 

> LogApplicator doesn't rely on indices. The only it needs is the right column type and column index (here by index I mean column number in layout) based on column name to update the record. So it behaves mostly like an UPDATE statement. Does expected layout provide this information correctly?

Expected layout only provides information about indexes/positions of the columns in itself. It does not necessary match with actual layout of existing record. I do not know/remember current implementation of VMDBMS in terms of expected and actual layouts. It is/will be either implemented in the code host or in the kernel. I think @eriohl can clarify.

Furthermore, I have no idea how it will/should behaviour in the context of replicator.

**Comment by k-rus** [comment]
@linkdata In your experiment, where you got the issue, could it be that the input somehow contained unknown table or column? For example, database was upgraded at the source.

**Comment by k-rus** [comment]
> introduce cache

As mentioned earlier a cache (`TypeBindings`) already exists for the loaded classes.

In future cache covering non-loaded classes will be needed. However, nothing is plan for this so far.

**Comment by linkdata** [comment]
> @linkdata In your experiment, where you got the issue, could it be that the input somehow contained unknown table or column? For example, database was upgraded at the source.

No, the setup is fully synthetic. Only two user classes exist, and the databases are all newly created.

**Comment by bigwad** [comment]
>The heavy CPU load is caused by the log reader while it's scanning the log file. Using the debug build, it will take a long time to get to the initial reading position (even for a small database it can take several minutes or longer). @bigwad may need to look into speeding it up.

Should be significantly improved with my latest check in.

**Comment by linkdata** [comment]
I found the bug. It was [indeed](https://github.com/Starcounter/Starcounter/issues/3392#issuecomment-187059474) a race condition, but not in Starcounter. The LogStreamers deserializer was using a static StringBuilder to avoid creating a new one for each string but failed to guard it with a lock. 

I will close this issue and open a separate one for this (to quote myself):

> We absolutely, positively, have to report the table name with SCERR4230.

If the table name had been reported, it would have been immediately obvious that it was a bug in the deserializer... :(
