### ISSUE TITLE
Question : Is there a way to check total number of records in the DB?

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3393]
I am in process of reloading my DB using command `staradmin -d=mydb reload db --file=data.sql`.
I can see that my entire database is loaded, except "Starcounter.Raw.Simplified.Ring5.UriPermission" table, and i am getting the following error on loading the DB :
`Cannot create object with the given id, since the object id is not free.`

I understand the reason of error, there should be 0 records in DB when i am ReLoading the data. 

Now my question is, When i create a new/clean DB, and run all my 4 apps in it, how do i make sure if there are no records in DB? and if there are any records, how do i clean them before starting Reload process?

**Comment by miyconst** [comment]
Removing items from database is not enough. The id keys are still used and not available.

You have to remove database and create new one.

**Comment by atifsheikh** [comment]
Thats what i am doing, but before running the Reload command, i have to run all the apps as instructed in the following link : 
https://github.com/Starcounter/Starcounter/wiki/Reloading-database-between-Starcounter-versions

But i think i have found the issue, these records are being created in UserAdmin app, so i commented out everything from Main function. and have started ReLoad process, lets see how it goes.

**Comment by k-rus** [comment]
If your apps create data in the Main script, then your database is not empty and load cannot succeed. You have to create versions of your apps, which do not create data, since the data will be loaded. Another approach you should not load the data, which are created in Mains. Either you don't unload them, or you remove from the reload SQL script. The latter is not feasible if the file is huge.



> But i think i have found the issue, these records are being created in UserAdmin app, so i commented out everything from Main function. and have started ReLoad process, lets see how it goes.

It should work as soon as you removed all populations.

**Comment by atifsheikh** [comment]
My app was not creating data in Main Script as i commented out every line of code from Main function.
UserAdmin was creating some records in DB, so i commented all lines of code from Main Function in that project aswell, and i successfully Reloaded my Database.

Thanks @k-rus for your response.

**Comment by per-samuelsson** [comment]
@atifsheikh 

The case when fellow apps "assure" data like that, out of control for other applications, is something we are currently having a conversation about on our internal tracker: https://github.com/Starcounter/CompanyTrack/issues/179.

If you have any ideas on how to make that sort of thing more manageable, all input is highy welcome!

**Comment by atifsheikh** [comment]
I can not access your internal tracker. 

Also, I dont have good knowledge of how internal SC code works, but i think the easiest way will be to somehow delete all records from DB and free up all Object Ids when the reload command is executed. 

Alternatively, (before starting ReLoad process, code should automatically check) if the ObjectId is already used, code should get a new ID (that is not being used in DB), and replace it with the used ID in SQL file. 
And the Reload process should start, once all Ids are checked/replaced.

I.E.
In my case, `object 13` was in use (in the clean DB), and lets say 'object 99' was free in my DB, so code should replace 'object 13' with 'object 99' from everywhere in unloaded sql file. and then start the Reload process.
