### ISSUE TITLE
pnext: Unload on a live database with LogStreamer fails with exception

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#3399]
When unloading the database:
```C:\Users\Administrator>staradmin unload --file=C:\dump.sql
Unloading Default (unloading ...)
Unload started at 10:13:12.5945267```
The exception caught is
```
[10:16:10, Starcounter (default)] [--failMissing] <type>
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entry
point method raised an exception. Failed to process query: SELECT __o as __id ,"
CommitId","TableId" FROM "LogStreamer"."LastPosition" __o: Unknown class LogStre
amer.LastPosition. Unknown property or alias CommitId. Unknown property or alias
 TableId. e type of objects to list.
End position: -1
```
I believe this is due to additional logreader system tables not known what to do with.

**Comment by dan31** [comment]
CC @per-samuelsson @bigwad @linkdata @k-rus

**Comment by k-rus** [comment]
This can be related to separation of apps that apps cannot access schema's of other apps. I don't know how it exactly works. It might be related to that replicator specific schema is created as user defined schema while playing purpose of storing some meta-data for replicator. However, unload is a specialised app, which should be able to read all schemas and it worked fine with all other user-defined classes.
cc @bigwad @alemoi

**Comment by dan31** [comment]
Taking this input, I believe the relevant thing would be to adopt the generic ```staradmin unload``` / ```staradmin reload``` to play nicely with logstreamer specific tables. I'm not sure whether there is somewhat deeper problem of mixing/misusing concepts of metadata tables, do you think it is the case @k-rus? @per-samuelsson @bigwad please keep the thing within your view and address it when time allows.

**Comment by k-rus** [comment]
@dan31 
By the way have you loaded apps, which loads the classes? This is current prerequisite to use the unload.

**Comment by per-samuelsson** [comment]
> @per-samuelsson @bigwad please keep the thing within your view and address it when time allows.

Me, I'm sorry, but I don't really have any input on this. I know I tested unload a long time ago, and also was hit by the thing that it failed when all classes where not loaded, and (as I remember) the error really didn't illustrate that was the error.

As for the `staradmin unload` command, it's quite stupid / transparent. It pretty much just invoke `Db.Unload()` after parsing and validating the given arguments.

**Comment by linkdata** [comment]
The `LogStreamer.LastPosition` class is just a regular database class. Nothing special about it. Does `unload` require all application to be loaded when running?

**Comment by per-samuelsson** [comment]
> Does unload require all application to be loaded when running?

Yes, it does, as @k-rus wrote earlier:

> By the way have you loaded apps, which loads the classes? This is current prerequisite to use the unload.

**Comment by k-rus** [comment]
> The LogStreamer.LastPosition class is just a regular database class. Nothing special about it. Does unload require all application to be loaded when running?

Yes, it uses normal `Db.SQL` to retrieve data for unload, see also [unload/reload documentation](https://github.com/Starcounter/Starcounter/wiki/Reloading-database-between-Starcounter-versions)

**Comment by per-samuelsson** [comment]
WTBS, and if nothing has changed since I tested it some year ago or so, you can instruct it to allow "partial" unloading. When you do that, every class that is not loaded will simply be ignored.

Use `staradmin help unload` to see example for when that option is used (hint: `--allowPartial`).

As the context here is **pnext**, maybe the unload implementation does not support this anymore. If so, I guess @k-rus could inform about that.

**Comment by k-rus** [comment]
> As the context here is pnext, maybe the unload implementation does not support this anymore. If so, I guess @k-rus could inform about that.

I have not touch unload/reload for pnext. @bigwad was fixing implementation of reload, but I don't think he was doing anything with unload affecting this.

**Comment by dan31** [comment]
> By the way have you loaded apps, which loads the classes? This is current prerequisite to use the unload.

@k-rus true, it is the case, to clarify my statement "on a live database" actually means that I have all the apps running, hence the database is live.

**Comment by dan31** [comment]
"All the apps" namely are Bulker and LogStreamer, two apps in total.

**Comment by bigwad** [comment]
App is definitely loaded otherwise error would be from Unload itself, while we see SQL error. @dan31, could you craft some query to this table from admin console?

**Comment by k-rus** [comment]
> @k-rus true, it is the case, to clarify my statement "on a live database" actually means that I have all the apps running, hence the database is live.

Thank you for clarifying. Sorry I missed this information, which is only in title, while I unintendantly assume that the issue body is self-contained.

How can the issue be reproduced? Does it require data being created? How apps can be obtained or where are they located?

**Comment by dan31** [comment]
@k-rus steps to reproduce:
1. Take latest pnext.
2. Take https://github.com/StarcounterSamples/LogStreamerBulker. Run it.
3. Take https://github.com/StarcounterPrefabs/LogStreamer. Run it.
3. In cmd, do ```staradmin unload --file=C:\dump.sql```

**Comment by k-rus** [comment]
I am able to reproduce this error with any two apps. The steps:

1. Start any two Apps with different schemas.
2. do `staradmin unload --file=C:\dump.sql`

The reported exception appears, but with different table and column names.

I suspect that the bug is introduced by app separation implemented by @alemoi and @dan31. Since `Unload` is just an App, it is not given access to retrieve data from tables of other apps.

**Comment by alemoi** [comment]
In case if an app requires to access all database classes in SQL it can do queries inside "null" application context (StarcounterEnvironment.AppName set to null) , for this there is a method StarcounterEnvironment.RunWithinApplication.

**Comment by alemoi** [comment]
In this case full namespaced sql names should be supplied.

**Comment by k-rus** [comment]
> In case if an app requires to access all database classes in SQL it can do queries inside "null" application context (StarcounterEnvironment.AppName set to null) , for this there is a method StarcounterEnvironment.RunWithinApplication.

Is there any instructions how to do it? I don't really understand what to do with the method and when the application context should be reset to make SQL working.

**Comment by alemoi** [comment]
> Is there any instructions how to do it? I don't really understand what to do with the method and when the application context should be reset to make SQL working.

This API is not documented because normal applications should never use this API. Here is an example of usage:

```cs
StarcounterEnvironment.RunWithinApplication(null, () => {

                    if (null == Db.SQL<Starcounter.Metadata.Table>("select t from starcounter.metadata.table t where fullname = ?", fromClassFullName).First) {
                        throw new ArgumentOutOfRangeException("From class name with given full name does not exist: " + fromClassFullName);
                    }
});
```

**Comment by k-rus** [comment]
Thank you! It works.

**Comment by k-rus** [comment]
Fixed

**Comment by dan31** [comment]
Works well on a running Bulker too, great! :+1:
