### ISSUE TITLE
Suggestion: Mixins for JSON

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3401]
I like to propose a minor variant of the `$Reuse` instruction.

Lets say that I have a JSON that I like to reuse in several other JSON's.

    User: {
      Username: "",
      Created: "",
    }
 
This User-json i bound to some User concept in the databas.

Now, I would like to be able to do some thing like this:

    UserDetails: {
      User: { $: {Mixin: "User"} },
      Alias: "",
      Foo: "",
      Bar: "",
    }

Where the Mixin json is automatically bound to the same database concept as the parent UserDetails.

I think that I can achieve this pattern by using Reuse and Bind. But since Bind only can be used on Properties, I need to do some extra work in the code behind class.

What do you think?

**Comment by per-samuelsson** [comment]
Thanks for taking the time to give us this input @ivarbergman.

We have ongoing discussions on different variants we want to do with reusage in general, but I'm not skilled enough yet to see all the implications of your suggestion and/or if we already support something similar.

@chrhol ? @warpech ?

**Comment by chrhol** [comment]
Since we have taken the decision to move away from specifying metadata inside the JSON-by-example file, and that this can be solved by setting a binding to the `Data` property in json this will not be added.
