### ISSUE TITLE
Help writing minimal web app with Puppet + partial

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3403]
It should display a single text field and a button, bound to a JSON viewmodel. When I press the button, I want to handle the input and reverse the text field value (I can write the logic in the handler).

It should not adapt to any mixing, merging, blending, mapping. Using `Page` class is OK.

I'm guessing a triplet + a Program.cs with an entrypoint.

@miyconst @warpech, any of you guys can help me write that? Just in this issue, and it doesn't need to compile, I just want to see the basic propose structure really.

**Comment by per-samuelsson** [comment]
Here's a skeleton which I think is somewhat like you'll suggest, if you want something to start with:

Simple.json
```json
{
  "Text" : "",
  "Reverse": 0
}
```

Simple.json.cs
```cs
partial class Simple : Page {
}
```

Simple.html
```
<html>
  <head><title>Simple</title></head>
</html>
```

Program.cs
```cs
void Main() {
  Handle.GET("/simple", () => {
    return new Simple();
  });
}
```

**Comment by warpech** [comment]
10 minutes :)

**Comment by warpech** [comment]
https://github.com/warpech/SimplePuppet

Mind that the HTML is "standalone" and will only work without Launcher. I can also write a "implicit standalone mode" version using Partial.cs, that will work with or without Launcher.

**Comment by per-samuelsson** [comment]
> 10 minutes :)

You are my true hero. :smile: Thanks a lot.

> Mind that the HTML is "standalone" and will only work without Launcher. I can also make an "implicit standalone mode" version using Partial.cs, that will work with or without Launcher.

Standalone is actually exactly what I wanted. I tried hint on that on the above HTML. Never mind the "implict standaolone one" (using Partial.cs), I can make that myself if I need that to illustrate something.
