### ISSUE TITLE
Review and cleanup IResource

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3407]
The kind of overloading going on with `AsMimeType`, we should try to avoid in interfaces. There are 4 overloads. They should at least be narrowed down to 2, possibly even one.

Furter, a method such as `GetHtmlPartialUrl` seem a bit off in such a generic interface. Let's see if we can try improve on that too.

**Comment by per-samuelsson** [comment]
Trying to figure out alternatives to this, and to do that, I need to understand it better. In particular, it's the `GetHtmlPartialUrl()` I want to get rid of, as I mentioned elsewhere.

One idea I had that would fit good into the other adaptions I'm using when replacing Page/Partial was to introduce a custom, vendor-specific MIME to represent "partial HTML". And by that, the `IResource` could answer to that, by forwarding it to installed middleware.

There are problems with that approach though, and I don't like it 100%. But I want to have one more high-level thing confirmed:

The usage of `Json.GetHtmlPartialUrl()` is in the *html merger*, correct? And that runs on the server, and the idea is as simple as that it builds up a string with resource URI's for every merged JSON viewmodel, where the URI can be used to fetch the corresponding view HTML for that particular view model. Basically ending up with something like:

```json

{
  "App1": {
    "Name": "Per",
    "Age": 43
  },
  "App2": {
    "Lives": "Älvsjö"
  },
  "Html": "sc/merger&App1:app1.html;App2=app2.html"
}
```

(Nevermind the details/syntax).

@chrhol, can you just confirm that, and/or correct/complement it if that's necessary?

**Comment by chrhol** [comment]
> @chrhol, can you just confirm that, and/or correct/complement it if that's necessary?

Yes, this is the current solution. If a partial responds with something from `Json.GetHtmlPartialUrl()` it's appended to a string and added as the `Html` property.

Just to clarify: there is no real `html merger` on the server today. It's hardcoded in the serializer for json. So this really needs to be changed :)

**Comment by per-samuelsson** [comment]
This one is done.
