### ISSUE TITLE
JSON-Patch slows down the browser over time.

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3408]
After i upgraded the JSON-Patch version from v0.5.3 to v0.5.6 in the Administrator i noticed that the browser got more and more responsive,

Just by clicking the `Auto-Start` button several times in a row the delay between each click got bigger and bigger.  It's not about  the socket. Even the drop-down menu got extremely slow.

![image](https://cloud.githubusercontent.com/assets/2656996/13378561/8fe4faa2-de0a-11e5-91ea-9733d64b8b14.png)

Maybe this issue should be posted in the JSON-Patch repo?

@miyconst I assigned it to you, i think you will the best person to understand the problem

**Comment by miyconst** [comment]
@andwah what version of SC should I check?

**Comment by andwah** [comment]
@miyconst I used the latest "develop" but i think you can use any version after 1 feb.

**Comment by miyconst** [comment]
@andwah  I can't reproduce the issue. Could you please investigate a bit more? 

- Do you see high CPU/RAM usage?
- Try to profile page in Chrome and see what is taking that much of CPU usage if so.

**Comment by andwah** [comment]
Some screenshot from Chrome profile page:

![image](https://cloud.githubusercontent.com/assets/2656996/13427028/994ed344-dfb1-11e5-8e8b-9b2bbe398d39.png)

**Comment by warpech** [comment]
Reproducible for me as well. If you put a `console.log` in `jsonpatch.generate`, you will notice that after few clicks it gets executed 100s of times.

Looks like a problem in Angular controllers, because I have never seen such problem it our Polymer apps.

**Comment by andwah** [comment]
@warpech oh, any clue how to solve it?

**Comment by warpech** [comment]
This is definitely a bug in JSON-Patch. There are event listeneres that are never removed:

```
            if (typeof window !== 'undefined') {
                if (window.addEventListener) {
                    window.addEventListener('mousedown', fastCheck);
                    window.addEventListener('mouseup', fastCheck);
                    window.addEventListener('keydown', fastCheck);
                }
                else {
                    document.documentElement.attachEvent('onmousedown', fastCheck);
                    document.documentElement.attachEvent('onmouseup', fastCheck);
                    document.documentElement.attachEvent('onkeydown', fastCheck);
                }
            }
````

This was not apparent before we switched from Object.observe.

I will create a fix.

**Comment by miyconst** [comment]
@warpech thanks for taking this one.

**Comment by warpech** [comment]
I pushed a fix in JSON-Patch and released a new version.

I commited the new version to Starcounter's `/sys/` directory, but did not update the file in Administrator. @andwah can you do that?

(this would help: https://github.com/Starcounter/Starcounter/issues/3194)

**Comment by andwah** [comment]
@warpech Sure ill update Administrator.

**Comment by warpech** [comment]
Nevermind, I did it :)

**Comment by warpech** [comment]
Please let me know how this works for you

**Comment by andwah** [comment]
@warpech I was confused when i checked the version number and it was already up'to'date :-)

**Comment by andwah** [comment]
Works just perfect, thanks!.
