### ISSUE TITLE
New type of exception "Unexpected critical windows error detected"

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3412]
My apps crashed, and I got the following exception in SC Admin Logs :
Unexpected critical windows error detected at "void __cdecl _init_block_detect(struct __WT_CTXT *)" (error=6).

Any one have any idea of what this error is about?

**Comment by atifsheikh** [comment]
@dan31 i can see no errors prior to this one. the last error before this error occurred days ago. so it cant be related.

**Comment by dan31** [comment]
@atifwaqar have you experienced similar thing then?

**Comment by atifwaqar** [comment]
@dan31 we have upgraded our SC versions, and i havent seen this error after upgrading.
