### ISSUE TITLE
Exception : Access violation (C0000005)

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3416]
(I'm not sure if the following 3 exceptions are related. But I am just adding the detail here. I know for sure that the first exception "Access violation" caused crash of all apps)
My apps crashed, and I got a new exception in SC Admin Logs:

Access violation (C0000005) detected at ..\..\src\sccoredb\sccoredb\sccoredb.cpp:1289 (Thread 5264).
    00000035EDCB26DD sccoredb!update::Rregister_bad_ref_read : u_badrefs.cpp (152)
    00000035EDCCF5AF sccoredb!evaluate_reference_value : objread.cpp (1508)
    00000035EDCCFF68 sccoredb!_object_read_committed_objref : objread.cpp (921)
    00000035EDCD073E sccoredb!_object_read_objref : objread.cpp (403)
    00000035EDCAE73B sccoredb!star_get_reference : sccoredb.cpp (1280)
    000007FA923E7EFE <unknown>!
    000000000185EDE9 <unknown>!
    0000000D14A5ED65 <unknown>!
    0000002F00000002 <unknown>!
    0000003805F4E628 <unknown>!
    0000003805F4E630 <unknown>!
    0000003805F4E620 <unknown>!
    0000AEC831F7FA70 <unknown>!
    000007FAF1E654B0 clr!
    0000003805F4FAE8 <unknown>!
    000007FA921D9200 <unknown>!
    0000000D14A5ED65 <unknown>!
    0000003805F4E5B0 <unknown>!
    000007FA923E7EFE <unknown>!
    0000003805F4E5E0 <unknown>!
    000007FA925A0187 <unknown>!
    000000000185EDD3 <unknown>!
    0000000D17B56649 <unknown>!
    000007FA00000002 <unknown>!
    0000000D14A5ED65 <unknown>!
    000000000185EDE9 <unknown>!
    0000003803F2BD70 <unknown>!
    0000002FA5138038 <unknown>!
    0000002FA5138040 <unknown>!
    00000037FEAEACA8 <unknown>!
    00000037FEAEAC68 <unknown>!
    0000002FA51127E8 <unknown>!
    00000031A2CA80D0 <unknown>!
    0000002FA51381A0 <unknown>!

Also in the logs i can see that there were 4 exception before the above one : 
System.Exception: ScErrAcquireSessionTimeout (SCERR5008): Exclusive access to the session could not be obtained.
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR5008.
   at Starcounter.Session.StartUsing() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 368
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 661
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR5008

and now after this exception I started my apps, and got the following exception : 
ScErrDbProcNotSignaling (SCERR10027): The database data process, when started, didn't signal it was operational in time. scdata.exe, PID=7776, Database=default. Start time: 3/2/2016 12:58:55 PM; time spent waiting: 00:00:05.
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10027.

**Comment by eriohl** [comment]
Thank you for reporting. Sorry for the late response.

The access violation we've seen before and it should have been fixed in a later version (see #3046). As for the other errors they are unlikely to be related.

**Comment by atifsheikh** [comment]
This "access violation" exception occurred only once for me (so i thought to inform you guys), if it occurs again i will definitely update my Starcounter Version.

And i can ignore the other 2 exceptions, as they are not disrupting or disturbing my Apps. 

Thank you for your response. :)

**Comment by dan31** [comment]
@atifsheikh, thank you for the instant feedback :) I still warmly recommend to migrate to the latest Nightly as we discussed before in chat, since it has a number of important fixes. This will make you prepared to move to upcoming 2.2 version as well. In regards to BMX-related one, this should also be off the table in the Nightly, since @alemoi addressed it around a month ago. Maybe @alemoi have a chance to clarify more in the thread.

**Comment by atifsheikh** [comment]
@dan31 ok sure, we will migrate to the latest nightly build then. Thanks :)
