### ISSUE TITLE
Replacing Session.Current.Data object generates patch with ver#s = 1

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3418]
If the `Session.Current.Data` object was replaced with another view-model server resets server patch version to 1 and client fails with the following exception:

```
Uncaught Error: Given version was already applied.
```

My handlers:

```cs
Handle.GET("/playground", () => {
	if (Session.Current == null) {
		Session.Current = new Session(SessionOptions.PatchVersioning);
	}

	return new IndexPage() {
		Session = Session.Current,
		Data = null
	};
});
```

```json
[{"op":"replace","path":"/_ver#s","value":1},{"op":"test","path":"/_ver#c$","value":0},{"op":"replace","path":"","value":{"_ver#c$":0,"_ver#s":1,"Html":"/Playground/IndexPage.html","MessageText":"","MessageButton":"","Button$":0,"Text$":"","Items":[],"AddItem$":0,"RemoveItem$":0,"AddAndRemoveItem$":0,"SubPage":{"Playground":{"Html":"/Playground/SubPage.html","Items":["i7 - 4790k","i7 - 5820k","i7 - 6700k"],"Remove$":0,"Add$":0},"Html":"/sc/htmlmerger?Playground=/Playground/SubPage.html","AppName":"Playground","PartialId":"/Playground/SubPage.html"},"LoadSubPage$":0,"UnloadSubPage$":0}}]
```

Test bench is available here: https://github.com/miyconst/Playground/, the `Reload current model` link.

cc @chrhol

**Comment by miyconst** [comment]
ping

**Comment by miyconst** [comment]
This issue happens only if the `Session.Data` of the main app replaced. If an included by another app via `Self.GET` and then replaces it's `Session.Data` it causes this issue: https://github.com/Starcounter/Starcounter/issues/3556.

**Comment by chrhol** [comment]
Pushed to develop and pnext (soon).

>  If an app included by another app via Self.GET and then replaces it's Session.Data it causes this issue: #3556.

I don't really get how this could be. Setting `Session.Data` for another app doesn't do anything else then storing the viewmodel on the session. Anyway, lets continue investigating that part in the other issue.

**Comment by miyconst** [comment]
Me either, it might be just a coincidence. Thank you for fixing this issue.
