### ISSUE TITLE
VS2015 "Step Over" (F10) doesn't break at the beginning of Main

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3421]
1. Create a Starcounter Application project from template.
2. Hit F10 (Step Over).

Normally this breaks the debugger at the beginning of the Main function. Not with the Starcounter application however. Then it acts as F5 (Start Debugging). It attached the debugger and breaks on breakpoint. But not in the beginning of Main function.

**Comment by per-samuelsson** [comment]
Yeah, I've noticed that at some point as well, and similarly, F11 doesn't step in as it should. As far as I know, this has never worked with out extension, so it's not specific to VS 2015.

**Comment by dan31** [comment]
Archived. Don't think things are different in 2017 either.
