### ISSUE TITLE
Creating/opening projects take really long time

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3423]
@eriohl has reported this on Gitter recently, and we have discussed it there, and when he debug the extension, he can see that it get stuck on `IVsOutputWindow.CreatePane`, which is some MS API we use to create the "Starcounter" output pane.

He's reported that on his machine, creating projects take like 5 minutes (!) because of this.

We have really no idea what this method do internally, taking that long, and neither anyone else has reported this, so it seem to be isolated to that machine for the moment.

The only alternative I can come up with right now is to drop support for this pane. It's not crucial or anything for us. At the same time, it would be nice to understand what is causing this.

**Comment by per-samuelsson** [comment]
Didn't come through in the title: "Starcounter" projects that is.

**Comment by eriohl** [comment]
For the record I run VS2015 Community Edition on Windows 10.

Removing the Starcounter output pane and project creation takes 1-2 seconds.

Also tried running VS as Administrator and it seems to make no difference.

**Comment by per-samuelsson** [comment]
> For the record I run VS2015 Community Edition on Windows 10.

I do too.

> Removing the Starcounter output pane and project creation takes 1-2 seconds.

That's good I guess, because then we have a least an option to do so to fix it. Feels a bit weird to do the effort though, when we've seen it on one machine only and that we still don't know *what* is causing it underneath.

At the same time, it's not acceptable you can't use our templates / the extension of course, and if we come up with nothing else, that's the only option we have. :confused:

**Comment by per-samuelsson** [comment]
Discussed further on Gitter, and me and @eriohl agree we should drop this thing. I'm trying to do that like in the weekend or beginning of next week.

**Comment by per-samuelsson** [comment]
Started this one. Decided to do it in both main branches. Speak up in case anyone think thats wrong.

**Comment by per-samuelsson** [comment]
Fixed in **develop**. Merged and pushed in https://github.com/Starcounter/Starcounter/commit/0dd33ba363490c4af132288ec2ff7011a42bb335.

About to merge it into **pnext** too.

**Comment by per-samuelsson** [comment]
> About to merge it into pnext too.

Build time for **pnext** is pretty horrible btw. Approx 15 minutes for simple daily custom builds with default configuration is quite far off.

Reading about how these kind of cycles work and when they don't, everybody quite agree that ~ 5 minutes is a hard ceiling, and for like every time slice you add to that, people will try more to get away from doing it. Plus of course that it involves a real cost, since even if people really *do* behave and actually go through with it, they tend to always wait for a result until the restart with something new, normally just browsing around or whatever.

Not sure what the hell is taking 15 minutes to build/test, for a single platform, so I can't really give any good feedback on it. I just know it's bad and comes with the above two effects in general.

**Comment by per-samuelsson** [comment]
> About to merge it into pnext too.

Done.

I'll let you verify and close this issue eventually, @eriohl. Should now be fixed in both main trunks.

**Comment by k-rus** [comment]
> Build time for pnext is pretty horrible btw. Approx 15 minutes for simple daily custom builds with default configuration is quite far off.
> 
> Reading about how these kind of cycles work and when they don't, everybody quite agree that ~ 5 minutes is a hard ceiling, and for like every time slice you add to that, people will try more to get away from doing it. Plus of course that it involves a real cost, since even if people really do behave and actually go through with it, they tend to always wait for a result until the restart with something new, normally just browsing around or whatever.
> 
> Not sure what the hell is taking 15 minutes to build/test, for a single platform, so I can't really give any good feedback on it. I just know it's bad and comes with the above two effects in general.

Can you create a separate issue about it? We discussed it and it requires some work to have possibility to disable/enable tests. Another problem with pnext is instability and big changes all the time. (note develop nightly failed probably due to your changes)

**Comment by per-samuelsson** [comment]
> Can you create a separate issue about it?

#3433

> note develop nightly failed probably due to your changes)

?

**Comment by per-samuelsson** [comment]
> note develop nightly failed probably due to your changes

I guess you where referring to that I'm the cause of #3429? Can you go in there and give me some clue on how I can better understand your test?

**Comment by eriohl** [comment]
Certainly seems to work a lot better. Creating and opening Starcounter projects are now pretty much instant.
