### ISSUE TITLE
pnext: ScErrDbProcNotSignaling warning starting database

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3425]
Happens every time a database is started. Server waits for an event named SC_S2MM_PMONLINE_<database_name> to be set by scdata.exe. It no longer sets this event however.

Not as easy as add addressing this in scdata.exe however. Database is now loaded on process startup so with a larger database this timeout would always occur anyway. Needs to be redesigned.

**Comment by per-samuelsson** [comment]
Clarifying the underlying demand: a way (for the admin server) to boot up a database (as in "the backend process-set, including the host") on demand, and wait for it to signal it's "operational".

Not sure how that maps to recent discussions/redesign of "process management backend" area in **pnext** though. But with that, we at least have a clear demand.

**Comment by eriohl** [comment]
I fixed so that the admin server waits for scdata.exe to accept connection requests rather then waiting for the non-existing event to be signaled. This is sufficient for the code host never to fail because scdata.exe hasn't booted up to a point where is accessible from it.

Note that this does not wait for database to be loaded into memory before proceeding. I figure it was better that this was done in parallel to booting up the code host. But it could of course fail in which case scdata.exe might still not be available when core host tries to attach. scdata.exe sets storage lock before accepting connection requests so it made sure that database exists and isn't accessed by someone else at this point. So this will only occur on unexpected errors.
