### ISSUE TITLE
Improve static resources HTTP caching policy

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3427]
It was reported numerous times by our users that HTTP caching headers for static resources are too agressive. 

The problem is that whenever there are updates to static `/sys/` files (because of installing a new version of Starcounter or an app), your browser still serves you the old files from browser cache. 

I know that @malx122 uses middleware to alter headers to make it more usable:

```
            Handle.AddResponseFilter((Request req, Response resp) =>
            {
                try
                {
                    if (resp.FileExists)
                    {
                        String mt = resp.FileModified.ToString();
                        String ims = req["If-Modified-Since"];

                        if (mt.Equals(ims))
                        {
                            resp = new Response() { StatusCode = 304 };
                        }
                        resp["Cache-Control"] = "max-age=0, must-revalidate";
                        resp["Last-Modified"] = mt;
                    }
                }
                catch (Exception )
                {
                }
                return resp;
            });
```

I am assigning this on me to propose a general solution and then come back to @alemoi to discuss changes.

**Comment by mtornwall** [comment]
+1

The default behavior is dangerous and simply cannot be deployed to production, unless you want to go through the hassle of remapping lots of URL's just to circumvent your users' browser caches.

**Comment by warpech** [comment]
@alemoi do you think it would be possible to include the above behavior directly in Starcounter? In place where we currently have: `Cache-Control: public,max-age=31536000`

https://github.com/Starcounter/Starcounter/blob/961fc6935381ddcc7f74018f121980e9e483c6b7/src/Starcounter.Hypermedia/StaticWebServer.File.cs#L135

It could be implemented according to https://www.httpwatch.com/httpgallery/caching/

This is very important to improve the developer experience

**Comment by alemoi** [comment]
Its a good initiative, thank you. Yes, I think it should be possible, I can add the above behavior.

**Comment by alemoi** [comment]
Thank you, good article. Question: in case when resource has not changed (`mt.Equals(ims)`), is it really correct to return it with "Cache-Control" and "Last-Modified" headers as given in example above?

**Comment by warpech** [comment]
> Thank you, good article. Question: in case when resource has not changed (mt.Equals(ims)), is it really correct to return it with "Cache-Control" and "Last-Modified" headers as given in example above?

My understanding is that it should return the regular set of headers (including "Cache-Control" and "Last-Modified") but the response should be with status 304 and **without body**.

You can use Chrome Dev Tools on any decent website (e.g. GitHub) to check how they perform 304 responses (just make sure to disable "Disable cache" in Chrome Dev Tools settings).

More info:

- http://stackoverflow.com/questions/5400180/what-response-should-if-modified-since-http-header-return-if-request-is-head
- http://www.restpatterns.org/HTTP_Headers/If-Modified-Since
- some tests: https://github.com/aspnet/StaticFiles/blob/dev/test/Microsoft.AspNetCore.StaticFiles.Tests/CacheHeaderTests.cs

**Comment by warpech** [comment]
I just found that this issue duplicates https://github.com/Starcounter/Starcounter/issues/1801, https://github.com/Starcounter/Starcounter/issues/2299

Btw. `ETag` + `If-None-Match` is a hash-based alternative to `Last-Modified` + `If-Modified-Since`. I was not able to find a resource that would clearly recommend `ETag` over `Last-Modified`, so I think it's up to you to decide.  I am fine with any of them. And we should *not* implement both.

**Comment by alemoi** [comment]
Just pushed the changes as proposed. Tested with Administrator seems working fine (file modification as well). Also added header Vary when Gzipping: `response.Headers["Vary"] = "Accept-Encoding";`

**Comment by warpech** [comment]
Big win! I will get the today's nightly and see for myself.

**Comment by alemoi** [comment]
> Big win! I will get the today's nightly and see for myself.

Let me know! :)

**Comment by warpech** [comment]
Just tested it with Starcounter 2.1.3199 and found one major glitch:

The date format of the `Last-Modified` header is not [according to HTTP/1.1 spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3.1):

<img width="1216" alt="screen shot 2016-03-13 at 14 44 22" src="https://cloud.githubusercontent.com/assets/566463/13729022/9f03611a-e92a-11e5-921f-42d9f4d24912.png">

**Comment by alemoi** [comment]
Good point, thanks! I will fix right away. Any other remarks on the way it works?

**Comment by alemoi** [comment]
The date format fixed via c963d576ee124906c0296620ca4edbcfc99eca6a and tested.

**Comment by dan31** [comment]
@warpech @alemoi Can we consider this tested and closed now?

**Comment by warpech** [comment]
Yes. Just did a final test (testing Administrator and KitchenSink) in Chrome, Firefox, Edge and IE11.

Thanks @alemoi!

**Comment by mtornwall** [comment]
Reopening this as there seems to be some issue preventing `304 Not Modified` responses from being sent even if `Last-Modified` matches `If-Modified-Since`. This *could* be due to my nginx reverse proxy setup.

@warpech Did you get 304's in your testing?

**Comment by warpech** [comment]
> @warpech Did you get 304's in your testing?

Yes, I got 304's as expected. Can you try to isolate the problem without nginx?

**Comment by mtornwall** [comment]
@warpech I can confirm that it works as expected without nginx, so it seems to be my fault. Sorry for wasting your time!

**Comment by warpech** [comment]
Ok, thanks for the update. Closing then

**Comment by mtornwall** [comment]
Should anyone else find their way here, the problem with nginx resulted from the use of a `proxy_cache` directive that prevented the `If-Modified-Since` request header from propagating to the Starcounter upstream.

**Comment by dan31** [comment]
Thanks @mtornwall, I marked the issue as a "KB" label.
