### ISSUE TITLE
pnext: Changing database configuration in admin GUI doesn't work

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3428]
(Cogwheel next to database name in database list called Database settings.)

Update scheduler count. Save button lights up. But nothing happens when the save button is pressed. Works in develop.

**Comment by k-rus** [comment]
sorry for closing the issue. I made typo in the issue number in the commit message. Reopen.

**Comment by dan31** [comment]
CC @andwah @per-samuelsson Please have a look once possible (this is pnext).

**Comment by dan31** [comment]
Ping @andwah

**Comment by andwah** [comment]
Works as expected in develop 2.4.0.1340 and in RC 2.3.0.5971

**Comment by per-samuelsson** [comment]
> Works as expected in develop 2.4.0.1340 and in RC 2.3.0.5971

Then lets close it 💯

**Comment by dan31** [comment]
Thx (adjusted in https://github.com/orgs/Starcounter/projects/2 correspondingly).
