### ISSUE TITLE
pnext: Failing to install an app from Warehouse

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3431]
I am trying to install Sign In app into `Starcounter-PnextNightlyBuilds-2.3.977` and getting the following error:

![image](https://cloud.githubusercontent.com/assets/6435556/13563090/e012acce-e43e-11e5-9f57-497e828cc9c9.png)

Log entries:

```
Non database type Starcounter.Metadata.MetadataEntity of property Type in class Starcounter.Internal.Metadata.SetSpecifier
```

```
"ScErrDbProcNotSignaling (SCERR10027): The database data process, when started, didn't signal it was operational in time. scdata.exe, PID=20268, Database=default. Start time: 3/7/2016 8:11:35 AM; time spent waiting: 00:00:05.
Version: 2.3.977.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10027."
```

Same thing happens for other applications. Did we change compatibility between pnext and current Warehouse?

**Comment by andwah** [comment]
@miyconst Can you double check you log, , i was expecting some other log-entry for this error you get. 
I got the same GUI error (but other log entry) and it has to do with a change in the timeout parameter to Handler.GET (maybe on all verbs) ,, 
the timeout parameter was changed from ms to s,
@alemoi I did you come up with a solution so we do not have to break the code?

**Comment by alemoi** [comment]
Thanks for the question. There was a parameter change in Http calls from ms to seconds. Not sure how to make it so it does not break the code. @andwah I guess we need to merge develop into pnext?

**Comment by alemoi** [comment]
Merged develop into pnext. So the nightly should have the fix, if succeeds :)

**Comment by andwah** [comment]
@alemoi ah.. I did not change/fix anything about this, i was not sure if you found a solution where it was not necessary to fix all Http calls (with timeouts) in all apps.

**Comment by miyconst** [comment]
Now it does not work at all:

```
Failed to download application. Service Unavailable. . View the log for more details.
```

The log it empty.

**Comment by andwah** [comment]
@alemoi i Updated all Http calls with a timeout that i know of effdbbd8d138e7d732c149f3971b612fb65cafa3

There was two test-projects that i did not update,  `NodeTest` and `SiegeTest`.

**Comment by miyconst** [comment]
@andwah what is the status of this issue?

**Comment by andwah** [comment]
@miyconst I have not got this issue after i pushed my fixes.

**Comment by miyconst** [comment]
Thanks, closing it.
