### ISSUE TITLE
pnext: Daily builds take > 15 minutes

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3433]
Reflection here: https://github.com/Starcounter/Starcounter/issues/3423#issuecomment-193183292.

**Comment by chrhol** [comment]
Currently (as mentioned in the other issue) there are a lot of tests running for daily builds. I think that all tests are added as a parameter to the build (https://teamcity.starcounter.org/admin/editBuildParams.html?id=buildType:Starcounter_PnextDailyWindows for those that have access to it) but we need to go through them and decide which ones needs to run and which ones takes too long time or is not really needed for a daily build.

One change from before is that if you add a new test, it will be run per default. Which means that the person that adds the test needs to add a parameter to the build and set it to false if it shouldn't be.

**Comment by k-rus** [comment]
As I mentioned in my original comment:

pnext is unstable now and is easy to break. So testing many tests is important now. Thus, imho, it is not an emergency issue to reduce building time, even it is annoying and slowing our development.

**Comment by dan31** [comment]
Archived. Feel free to re-open.
