### ISSUE TITLE
Problems with include custom-style in partials

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3434]
Hi! We have in previous versions of SC used `custom-style`in partials

```
    <style is="custom-style" include="our-common-style"></style>
```

to share some common css rules. However in the current version of SC these css rules area no longer applied to the content of the partials. 

Is this a known problem? 

Note that local custom css rules are applied. Ie the following works:

```
<style is="custom-style" >
    .horizontal        
    {
      display: flex;
      flex-direction: row;
    }
</style>
```

**Comment by miyconst** [comment]
We recently migrated to Polymer `1.3.0` from `1.1.5`. This might be an issue.

**Comment by miyconst** [comment]
@ivarbergman were you able to solve the issue? If no, then provide some more details please.

- Your custom style declaration.
- What do you mean by "these css rules area no longer applied to the content of the partials"? Does it work outside of a partial?

**Comment by dan31** [comment]
Archived.
