### ISSUE TITLE
pnext: incompatibility on using index with ORDER BY statement

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3437]
Given the class 
```
    [Database]
    public class TestClass
    {
        public long A;
        public long B;
    }
```
and the index:
``` 
CREATE UNIQUE INDEX TestClassIdx ON TestClass (A,B)
```

Such query:
```
select * from TestClass Order by A
```

use index on develop but not on pnext.
To make pnext use the index, both indexed fields should be specified in ORDER BY statement: 
```
select * from TestClass Order by A,B
```

**Comment by dan31** [comment]
CC @k-rus

**Comment by k-rus** [comment]
Thank you for reporting the issue! I will look at it.

**Comment by k-rus** [comment]
I reproduced the issue. Not so easy to understand how it is supposed to work. The implementation in pnext was done by @eriohl about 6 months ago.

**Comment by k-rus** [comment]
Using diff found a possible solution. Seems to work.

**Comment by k-rus** [comment]
Fixed and regression test added.
