### ISSUE TITLE
Introduce Roslyn-based TypedJSON code-behind parser

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3439]
Side-by-side for some time, with the aim to drop the legacy parser.

**Comment by per-samuelsson** [comment]
Enabler of #2964, #3105, #3347.

**Comment by per-samuelsson** [comment]
@chrhol 

I'm having some problems understanding a few constructs in the `CodeBehindMetadata` I'm set to generate.

1. Is `List<CodeBehindClassInfo> JsonPropertyMapList` in `CodeBehindMetadata` simply a list of all classes declared in the code-behind file?
2. `CodeBehindMetadata.RootClassInfo`, is that the "default" class, i.e the class that correspond to the JSON-by-example top-object? (That is: the one that is emitted by the template when I add a new "Typed JSON with code-behind" item in VS?)
3. `CodeBehindClassInfo.ParentClasses`, is that a recursive list of *nesting* classes, found by traversing "outbound" from any inner / nested class?

**Comment by chrhol** [comment]
> I'm having some problems understanding a few constructs in the CodeBehindMetadata I'm set to generate.

1. It's a list of classes that have a mapping attribute specified so that the class can be connected to a property in JSON-by-example. The name of the attribute is composed from the classname and the propertyname  (`[MyJson__json.Items]` for example) 

2. Yes.

3. Yes, although I cannot remember why this is needed right away. Maybe to be able to write a fully namespaced name when generating code.

**Comment by per-samuelsson** [comment]
Great. Thanks.

I think we should force any class being present in the code-behind to somehow relate to a corresponding node in the JSON (i.e. to an object node, either the "master", or a sibling). Do you think that´s doable, or is it even so already?

My thinking is it makes it clearer to understand what the code-behind accept and that it relate to the JSON-by-example.

**Comment by chrhol** [comment]
> I think we should force any class being present in the code-behind to somehow relate to a corresponding node in the JSON (i.e. to an object node, either the "master", or a sibling). Do you think that´s doable, or is it even so already?

It's not like that today, a class that is not mapped is simply ignored. 

But I like the idea that we force every class (in the code-behind) to be mapped. I think overall we have been to forgiving when it comes to what you are allowed to do or not, which make both explaining and understanding TypedJSON more difficult.

It's definitely doable.

**Comment by per-samuelsson** [comment]
> But I like the idea that we force every class (in the code-behind) to be mapped. I think overall we have been to forgiving when it comes to what you are allowed to do or not, which make both explaining and understanding TypedJSON more difficult.

I agree totally. It's way to often we act like this, and it bites us in the foot. It's often better to be specific.

The most notable example I remember is from our [sessions](http://starcounter.io/guides/web/sessions/) documentation, and this extract from there:

> Here are some examples of creating a new session (property UseSessionCookie is described below). All examples will produce the same result:

```cs
Json m = new Json();

// Creating a new session

Session.Current = new Session() {
    Data = m,
    UseSessionCookie = true
};

// Above is EXACTLY the same as

m.Session = new Session() {
    UseSessionCookie = true
};

// Above is EXACTLY the same as

m.Session = new Session() {
    UseSessionCookie = true,
    Data = m
};
```

Thats a bit off-topic, bit it kind of illustrate what you suggest above.

> It's definitely doable.

With Roslyn, it sure is. I'm doing it. Thanks for the feedback!

**Comment by per-samuelsson** [comment]
Regarding *base classes*, what's the set of base classes that are valid to specify for any class in the code-behind, @chrhol?

I know `Json` (`Starcounter.Json`), and I've figured out how we process the `IBound<T>` declarations. But can 

1. other base **class** types be given, to achieve JSON inheritance or anything like that?
2. classes **omit** to specify a base-class? Should we care about that? Like:

```cs
public partial class Foo : IBound<Whatever>, IDisposable {
  // ...
}
```

**Comment by chrhol** [comment]
1. Yes, exactly. This is the way we do it for inheritance (for example the `Page` class works like this). The requirement is that the baseclass is a subclass of `Json`. Unfortunately I don't think we can make sure this is the case during the parsing since we don't have access to the full type (only a string-identifier).

2. Not sure if we should enforce this or not. How it works today is if you omit the baseclass in code-behind, `Json` will be added as the baseclass in the generated code, and the other way around if you specify it in code-behind.

**Comment by per-samuelsson** [comment]
> Unfortunately I don't think we can make sure this is the case during the parsing since we don't have access to the full type (only a string-identifier).

Yeah, thats what I was thinking too, and Roslyn doesn't help here unfortunately. But I think its a minor limitation, let's just accept it for now.

> How it works today is if you omit the baseclass in code-behind, Json will be added as the baseclass in the generated code ...

OK, I'll keep it like that initially. Thanks for the feedback.

**Comment by per-samuelsson** [comment]
@chrhol 

Processing of the custom attributes is not very straightforward, and made even more complex since we support *two different syntaxes*. Do we need that still? Can't we just drop the "old syntax", or is it needed for backwards-compatibility?

**Comment by chrhol** [comment]
> *two different syntaxes*

What is the old syntax? I thought we only had one, but maybe have just forgotten how it works :)

**Comment by per-samuelsson** [comment]
> What is the old syntax?

Example: `json.ActivePage.SubPage1.SubPage2`. And parser [here](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.XSON.PartialClassGenerator/CodeBehindMetaData/CodeBehindClassInfo.cs#L192-L204).

**Comment by per-samuelsson** [comment]
And [CreateClassPathFromOldSyntax](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.XSON.PartialClassGenerator/CodeBehindMetaData/CodeBehindClassInfo.cs#L233-L251).

**Comment by per-samuelsson** [comment]
This one is a bit weird though:

```cs
#if DEBUG
            if (attribute.Contains("json.")) {
                throw new Exception("Internal error when detecting .json attribute in code-behind");
            }
#endif
```

Considering its just a few lines below where we support the "old syntax" and that one contain that pattern... :smile:

**Comment by chrhol** [comment]
Aha, thanks for clarifying it. We should remove it and only support the new attributes. 

To be honest I don't really know why this is still left in the code. You cannot specify the attributes in this way anymore.

**Comment by per-samuelsson** [comment]
> We should remove it and only support the new attributes.

OK, then I'll drop it. Thanks. I need to try to trim down the code a bit to better understand how to implement the new parser.

**Comment by per-samuelsson** [comment]
Next thing: `BindChildren` custom attribute.

The code look like this:

**Bound.cs**
```cs
public enum BindingStrategy {
		UseParent,
        Bound,
        Unbound,
        Auto
    }

	[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
	public class BindChildrenAttribute : Attribute {
		public BindChildrenAttribute(BindingStrategy strategy) {
			Strategy = strategy;
		}

		public BindingStrategy Strategy { get; set; }
	}
```

And then the parser-code look like this:

```cs
if (attribute.Contains("BindChildren")) {
	int count;
	int index = attribute.IndexOf("Bound.");
	if (index == -1)
		throw new Exception("Invalid value for BindChildren attribute");

	index += 6;
	count = attribute.Length - index - 1;

	BindingStrategy bound;
	if (!Enum.TryParse<BindingStrategy>(attribute.Substring(index, count), out bound))
		throw new Exception("Unable to get correct value from BindChildren attribute");

	if (existing == null)
		existing = new CodeBehindClassInfo(null);
	existing.BindChildren = bound;
	return existing;
}
```

I guess this is never used, because it appears to me that it would be quite hard getting pass:

```cs
int index = attribute.IndexOf("Bound.");
	if (index == -1)
		throw new Exception("Invalid value for BindChildren attribute");

```

Or is the parser for something else? (Since it also use `.Contains("BindChildren")` and not `.StartsWith("BindChildren")`, or is that to support it being fully qualified?)

**Comment by chrhol** [comment]
It was never fully implemented. We can probably remove it and add it later if needed or when we have decided on how we want to specify these things.

**Comment by per-samuelsson** [comment]
> It was never fully implemented. We can probably remove it and add it later if needed or when we have decided on how we want to specify these things.

OK, good. I vote for that too, so let's do it.

**Comment by Starcounter-Jack** [comment]
In Roslyn (ICompileModule) we have access to the entire type tree.

**Comment by per-samuelsson** [comment]
@chrhol 

I'm making an attempt to document (raw-ish) my findings and the decisions we'll take for code-behind, hosting it here: https://github.com/per-samuelsson/Misc/wiki/Typed-JSON-and-the-role-of-code-behind

Then we can use that as the base for user documentation eventually.

**Comment by per-samuelsson** [comment]
I'll dust this one off, after talking to @chrhol. We have quite a few possibilities to improve Typed JSON if we realize this. I'll try to make some progress on it during the upcoming week.

**Comment by per-samuelsson** [comment]
@chrhol 

I need help with something. Having this new test thing I've enabled:

```cs
var source = "namespace Foo { namespace Bar { public partial class Fubar {} } }";
var mono = ParserAnalyzeCode("Fubar", source);
var roslyn = ParserAnalyzeCode("Fubar", source, true);
Assert.AreEqual(mono.RootClassInfo.Namespace, roslyn.RootClassInfo.Namespace);
```

gives me

```
Starcounter.Internal.XSON.PartialClassGeneration.Tests.CodeBehindParserTests.CodeBehindParsersEqualityTest:
  String lengths are both 7. Strings differ at index 0.
  Expected: "Bar.Foo"
  But was:  "Foo.Bar"
  -----------^
```

Is the namespace I should return for `Fubar` really `Bar.Foo`?

**Comment by chrhol** [comment]
> Is the namespace I should return for Fubar really Bar.Foo?

No, this seems to be a bug in the mono-parser when two namespaces are declared after each other.

 I tested with `Starcounter.Internal.XSON.PartialClassGeneration.Tests.CodeBehindComplexAnalyzeTest` (yes yes, long namespaces and methodnames are awesome :blush:) and added a second namespace after another class, and this seems to work:

```csharp
namespace MySampleNamespace {
    namespace WrongNamespace {
        [Test]
        public class WrongClass {
            public string Apa;

            public void GetApa() {
                return Apa;
            }
        }
    }

    namespace AnotherNS {
        [Complex_json]
        partial class Complex : MyBaseJsonClass {
        ...
    }
```

However I get the same error as you do if I use the same case as you pointed out. Should we fix it in the mono-parser you think, or is it not worth the effort if we are planning to move anyway (and since noone reported this before I guess pattern it's not used anywhere currently)

**Comment by per-samuelsson** [comment]
Another parser-question:

```cs
var source = "namespace Foo { { public partial class Bar { [BarMap_json] public partial class Fubar {} } }";
var mono = ParserAnalyzeCode("Bar", source);
Assert.True(mono.CodeBehindClasses[0].IsRootClass);
Assert.False(mono.CodeBehindClasses[1].IsRootClass);
```

If I add that test, it fails. Both classes claim to be the root class. Are nested classes considered root classes too, or are they not even supported? Should I produce (and allow) similar results?

**Comment by per-samuelsson** [comment]
> Should we fix it in the mono-parser you think, or is it not worth the effort if we are planning to move anyway [...]

I honestly don't know really. Generally speaking, I guess we might as well just redefine what stuff is allowed and what is not, and make this new parser a lot stricter. It will mean that users will have to refactor their code behind once they install the first version with this new parser.

More specifically for the case with "reversed namespacing", I think we should make the Roslyn-parser use the "correct" pattern at least - i.e. the one it produce in my test above. But that will mean we need to change other stuff I guess, like code generation? Is that doable?

**Comment by chrhol** [comment]
> If I add that test, it fails. Both classes claim to be the root class. Are nested classes considered root classes too, or are they not even supported? Should I produce (and allow) similar results?

This test looks correct to me, and should succeed. The mono-parser parses incorrectly. Nested classes should not be considered a root-class. 

> More specifically for the case with "reversed namespacing", I think we should make the Roslyn-parser use the "correct" pattern at least - i.e. the one it produce in my test above. 

I agree!

> But that will mean we need to change other stuff I guess, like code generation? Is that doable?

Do we really need to change anything in the codegeneration (for this case I mean)? I don't think so. Or do you mean in general when we switch parser? Then it's doable and neccessary anyways since we want to add some additional features.

**Comment by per-samuelsson** [comment]
> Do we really need to change anything in the codegeneration (for this case I mean)? I don't think so.

I have absolutely no idea - it was a question, not a statement. All I try to do is to parse the code-behind and generate a metadata tree that is similar to that returned from the mono-compiler. If I return one that is different (i.e. one where namespace-paths are reversed), I just assumed some other code consuming that metadata would fail. If it doesn't, then I think changing is a no-brainer.

Regarding class declarations in the code-behind in general, I'd like to take a moment to really define what we should allow and what not - as I want to make it a lot stricter than what it is today. Is it OK if I open an issue on that, presenting some proposals, to see what others think? I thinking it's good that I do that, since I don't know very much about the history or complex details of stuff (and then I hand that over to you). :sunglasses: :beers:

**Comment by chrhol** [comment]
> I have absolutely no idea [...]  I just assumed some other code consuming that metadata would fail. If it doesn't, then I think changing is a no-brainer. [...]

Aha, alright. No, this change should not affect the codegeneration in any way (except that the namespace will be correct afterwards :smile:)

> Regarding class declarations in the code-behind in general, I'd like to take a moment to really define what we should allow and what not - as I want to make it a lot stricter than what it is today. [...] 

Sure, sounds good. Do that.

**Comment by per-samuelsson** [comment]
> Sure, sounds good. Do that.

#3625. And for the record, I'm for "nested only". :bank:

**Comment by per-samuelsson** [comment]
> This test looks correct to me, and should succeed. The mono-parser parses incorrectly. Nested classes should not be considered a root-class.

I found the error. I used an illegal attribute syntax in the test (forgot a dot), and the way `CodeBehindClassInfo.EvaluateAttributeString` determine if a mapping attribute reference the root object is this:

```cs
var strings = attribute.Split('.');

// Example: "[MyFile_json.Somestuff]
for (int t = 0; t < strings.Length; t++) {
  existing.IsRootClass = (t == strings.Length - 1);
}
```

which will fail when there is no dot defined (and seem a bit confusing overall). I'll rewrite that to check if the attribute is equal to "[RootName]__json" instead, which seem more predictable. Let me know if you think it will cause trouble.

**Comment by chrhol** [comment]
Another issue which produces a bad exception back to the user: missing `_json` in the attribute for an nested class, #3626.

**Comment by per-samuelsson** [comment]
@chrhol 

Is this declaration valid with the Mono parser:

```cs
public partial class Foo5 : IBound<Fubar.Bar> {}
```

I notice that what is produced is `BaseClassName: IBound` and `BoundDataClass: Fubar.Bar`. At least the BaseClassName seem a bit off?

In the Roslyn-parser, I'm currently producing `BaseClassName: IBound<Fubar.Bar>` and `BoundDataClass: null`.

**Comment by chrhol** [comment]
> Is this declaration valid with the Mono parser:

The `IBound` interface is currently used to specify datatype for the Data-property when generating code, so `BoundDataClass` should be set to the generic parameter, leaving that with `null` will generate incorrect code.

`BaseClassName` is off, I agree. If I remember correctly, the mono-parser simply takes the first identifier from after the class-declaration and assumes that's the baseclass for inheritance, since we cannot know if the identifier is for a class or interface. Although `IBound` is known so we could filter that one out.

**Comment by chrhol** [comment]
By the way, this is probably the cause for #3624. When `BaseClassName` is set, the codegenerator assumes that the partial class in code-behind specifies the inheritance and leaves it out of the generated code.

**Comment by per-samuelsson** [comment]
Thanks for clarifying @chrhol.

I'm designing the Roslyn parser on these premises:

1. You must specify a base class. Normally `Json`/`Starcounter.Json`, but we can't limit to that, since we support custom base classes that derive `Json`.
2. If you declare `class Foo : IBound<...>` (or `class Foo : Starcounter.IBound<...>`), I'll raise an exception, that will instruct to declare `Json` as the baseclass, and add `IBound` after that.
3. Doing `class Foo : IWhatever` will yield `IWhatever` as the `BaseClassName`, which is of course not right. But there's just no way for us to know that `IWhatever` is not a class that derive `Json` (in which case it would be legal).
4. Declaring `class Foo : Json, IWhatever, IBound<Foo>, IDisposable` will make `Json` the base class and `Foo` the bound type.

Let me know if you think any of that is off.

**Comment by per-samuelsson** [comment]
When thinking about it - should it be possible to define code-behind classes that specify no inheritance, and we emit `Json` in that case, as is suggested in OP in #3624? I think we might want to support that, or maybe we already do? In C#, when you define a partial class, only one place has to define the base list if I remember correctly. If so, we could allow the same (since we for sure will generate the "other" partial class).

In such case, I can detect that the code in #3624 OP actually make sense, and allow it.

**Comment by chrhol** [comment]
Yes, currently this is allowed, if no baseclass is specified in code-behind, `Json` is emitted in the generated code instead.

**Comment by per-samuelsson** [comment]
@chrhol 

I see there is rather little validation of input handler methods (naturally, since it's such a pain with the old parser). While I'm at it, I'll define them a little stricter. How about this?

1. Must be instance method.
2. Must have `void` return type.
3. Can not have type parameters.
4. Can only have a single parameter of type `Input.*`
5. Can not be abstract.
6. More/less?

**Comment by per-samuelsson** [comment]
> 1. Must be instance method.
2. Must have `void` return type.
3. Can not have type parameters.
4. Can only have a single parameter of type `Input.*`
5. Can not be abstract.

Done.

**Comment by chrhol** [comment]
> Done.

Cool, missed you previous post. I agree on the points though, and cannot think of anything else.

**Comment by per-samuelsson** [comment]
Update: I'm more or less done with the parser now, and have it fairly covered in unit tests. Seem to be working pretty well.

What I'm working on now is to get error propagation to work to provide a good experience in VS, where user can see pinpointed file/line/column info for invalid code behind. Takes bit of a time since I haven't tried out those span-related things in Roslyn previously. But I'm getting there.

What's left to finalize this is to decide on a Roslyn version to start shipping and including in builds, and also if we should ship both parsers side-by-side for a while, or just drop the old one straight away. 

I think we can finalize all these things and be done with this whole replacement in the beginning of next week (monday or tuesday). Let's hook up for a discussion on the final details on monday.

**Comment by chrhol** [comment]
> What's left to finalize this is to decide on a Roslyn version to start shipping and including in builds, and also if we should ship both parsers side-by-side for a while, or just drop the old one straight away.

I know we talked about running them side-by-side for a while, but judging by the issues/strangeness you found in the old parser, I think just dropping the old one might be better.

**Comment by per-samuelsson** [comment]
> [...] I think just dropping the old one might be better.

Yeah, I tend to lean in that direction too. Let's take that final decision when I'm merging it in the beginning of next week.

**Comment by per-samuelsson** [comment]
> Let's take that final decision when I'm merging it in the beginning of next week.

Regarding keeping parsers side-by-side or not, I ended up deciding that I'll keep the mono parser around for a while, but the only way to run it will be using a (temporary) labs-like environment variable.

That way, we can keep all sanity comparison unit tests I've written for a while. And easily go back and verify how something in a live environment work with the old parser, if we get reports of something with the new one that doesn't work.

Then if things seem to go good, we can just drop all references to the old parser in a few weeks or so.

**Comment by per-samuelsson** [comment]
![image](https://cloud.githubusercontent.com/assets/2902045/15463964/d807c81e-20cc-11e6-86d7-2b3a9d166695.png)

**Comment by per-samuelsson** [comment]
I think I have most things covered now, including successful build server build (with tweak that takes us to NuGet 3.x) and tested Typed JSON code-behind basic scenarios after building a custom installer and installed it locally.

There are 2 things that does not yet feel perfect:

1. In the custom installer I built, I noticed Roslyn binaries didn't bundle and hence didn't end up in the installation directory. I think there is some whitelisting thing I've forgot. **However**, the parser still worked fine in VS on that installation, so it seem the build task can reference those assemblies from VS (I guess they are loaded already). I'm not sure how we should tackle this.
2. Are we 100% sure we can redist Roslyn binaries today? I'm using `Microsoft.CodeAnalysis.Common` and `Microsoft.CodeAnalysis.CSharp` (packages/assemblies), both of version 1.2.2 (latest stable). 

@dan31, any chance you could straighten out [2] so I don't get hanged when we get sued for $100- gazzillion? :wink: :sunglasses:

**Comment by per-samuelsson** [comment]
> [...]  so it seem the build task can reference those assemblies from VS (I guess they are loaded already)

Found for sure at least that I was right in that. They are loaded from the installation directory, e.g `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.dll`.

**Comment by per-samuelsson** [comment]
> In the custom installer I built, I noticed Roslyn binaries didn't bundle and hence didn't end up in the installation directory. I think there is some whitelisting thing I've forgot.

I found it, have fixed it by including corresponding binaries in the whitelist, built a new custom installer and successfully installed it (with artifacts now included).

With that, this issue is done except for updating the change log and merge it into main branches. Don't want to do that until I get a confirmation on licensing request made above though.

**Comment by dan31** [comment]
Great results there, @per-samuelsson!

The license for Roslyn is Apache (https://github.com/dotnet/roslyn/blob/master/License.txt), which is largely permissive. We have to follow this:
>  Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions: ...  __You must give any other recipients of the Work or Derivative Works a copy of this License__

Hence please put the file with Roslyn license in Starcounter distrib folder. I suggest creating a folder ```Licenses``` and fill it with licenses to our 3-rd party components. For this one, you do:
```C:/Program files/Starcounter/Licenses/Roslyn/License.txt```).

@per-samuelsson, I bet you don't modify any Roslyn source, do you? :)

**Comment by per-samuelsson** [comment]
> @per-samuelsson, I bet you don't modify any Roslyn source, do you? :)

Not for this one, no. I simply fetch latest stable packages from NuGet.org, which is totally sufficient for our code-behind parser.

Thanks for helping out. I'll make sure to finish this completely and fulfill those requirements before the end of this week.

**Comment by per-samuelsson** [comment]
Finally done, merged and pushed in https://github.com/Starcounter/Starcounter/commit/7280e4831f615d0dfe3b5cb00a6374b13be7073c.

Just about to run personal tests in a merge to **pnext**. Hope to push to that one too soon, and close this.

**Comment by chrhol** [comment]
Awesome, I will pull and test it right away!

**Comment by per-samuelsson** [comment]
> Just about to run personal tests in a merge to pnext. Hope to push to that one too soon, and close this.

Done. Time to close this one, and go over and close related/fixed issues too.
