### ISSUE TITLE
pnext: scerr12019 editionlib

### ISSUE THREAD

**Issue by hentil** [Starcounter/Starcounter#3440]
Trying to start latest version of pnext, running Heads application. Since Heads application also contains a definition for societyobjects, weaver reports error. 

I have tried to disable this using the configuration LoadEditionLibraries = false in the following files.

Personal.server.config
.sample.db.config
Default.db.config

Still getting this error message on startup.

HeadsSCDB2 -> default (starting application)

[14:43:24, Starcounter.Server.Weaver (scadminserver)]
 ScErrAppDeployedEditionLibrary (SCERR12019): At least one file considered a Starcounter edition library was found locally deployed with an application, i.e. residing in the same directory as the application file. 1 duplicate(s): Starcounter.Extensions.dll Version: 2.3.1003. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR12019.    vid Starcounter.Weaver.FileManager.AddEditionLibraries(String[] editionLibraries, List`1 sourceFiles) i C:\TeamCity\TeamCity9\buildAgent\work\sc-84\Level1\src\scweaver\FileManager.cs:rad 267    vid Starcounter.Weaver.FileManager.Open() i C:\TeamCity\TeamCity9\buildAgent\work\sc-84\Level1\src\scweaver\FileManager.cs:rad 174    vid Starcounter.Weaver.CodeWeaver.Execute(
) i C:\TeamCity\TeamCity9\buildAgent\work\sc-84\Level1\src\scweaver\CodeWeaver.cs:rad 307    vid Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) i C:\TeamCity\TeamCity9\buildAgent\work\sc-84\Level1\src\scweaver\CodeWeaver.cs
:rad 234    vid Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) i C:\TeamCity\TeamCity9\buildAgent\work\sc-84\Level1\src\scweaver\Program.cs:rad 156    vid Starcounter.Weaver.Program.Main(String[] args) i C:\TeamCity\TeamCity9\buildAgent\work\sc-84\Level1\src\scweaver\Program.cs:rad 37

**Comment by k-rus** [comment]
cc @alemoi @per-samuelsson

**Comment by per-samuelsson** [comment]
@hentil 

> ScErrAppDeployedEditionLibrary (SCERR12019): At least one file considered a Starcounter edition library was found locally deployed with an application, i.e. residing in the same directory as the application file. 1 duplicate(s): Starcounter.Extensions.dll

It looks like you have a local `Starcounter.Extensions.dll` in your application. Most likely, the reference in the project is set to "Copy Local: True". Can you make sure this file is not in your bin directory when you start your application? Either go there and manually delete it (if it's not referenced), or adapt the reference to "Copy Local: False".

The error message is not perfect, and maybe we can do better here, like for instance just ignoring such file or whatever. But that's not a quick fix. I hope the above can get you passed it for now!

**Comment by per-samuelsson** [comment]
Here's the relevant weaver code if that's of interest: [FileManager.AddEditionLibraries](https://github.com/Starcounter/Starcounter/blob/ef1355f03e18caa855cc537ef69e8468fa70090d/src/scweaver/FileManager.cs#L250-L273).

The basic flow is that any file "part of Starcounter" shall not be deployed along with the application. This include files that exist in the installation directory, and those we consider "built-in" (e.g edition libraries).

**Comment by hentil** [comment]
OK, thanks that solved it. 

I was distracted by SO, so I did not see the problem. It has happened before that this particular problem occurred...
