### ISSUE TITLE
Future of the Typed JSON 

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3443]
In this issue I try to summarize all similar issues about the Type JSON to have some clear vision and close those old endless issues.

## Current state

We have set of features of `$` dollar sign in our JSON files. Some of them used very widely others very rarely, some of them have c# equivalent.

#### List of most common `$` features and JSON syntax:

1. Indicate whether a property is editable. `"Name": "readonly"`, `"Name$": "editable"`. **Always used**.
2. Bind a property to take value from another place. `"$Name": { "Bind": "CustomName"  }`. **Switching to c#**.
3. Specify data type. `{ $:{ "DataType": "MyNamespace.Person" } }`. **Never used**.
4. Reuse same JSON object multiple times. `{ $:{ "Reuse": "MyNamespace.Person" } }`. **Always used**.

#### And the c# equivalents.

1. `DefaultTemplate.Name.Editable = true;`. **Never used**.
2. `DefaultTemplate.Name.Bind = "CustomName";`. **Switching to c#**.
3. `partial class MyJson : IBound<MyNamespace.Person>`. **Always used**.
4. **No c# equivalent**.

## Future of the Typed JSON

A while ago we had multiple conversations between @per-samuelsson, @warpech, @chrhol, and me. The one big thing we all agreed on is that we have to clean up JSON files by moving all the logic to the code behind class. That is why we should:

- Stop promoting usage of `$` sign in JSON files.
- Start using code behind by ourselves.
- Find a solution for `Reuse` keyword as currently it's available only with `$` magic.

#### [Suggestion: Mixins for JSON](https://github.com/Starcounter/Starcounter/issues/3401)

Another proposition to add some more magic to the `$` sign. The idea behind is to bind child JSON object with parent's data. 

I can think of the cases where it could be useful, but this could be easily achieved with code, that is why I think the issue should be rejected.

#### [Do I need to explicitly include "Html" property?](https://github.com/Starcounter/Starcounter/issues/3200)

Discussion about inheritance and implicit/explicit JSON properties exposure. A big comment from @Starcounter-Jack.

>[Why JSON property exposures are not inherited](https://github.com/Starcounter/Starcounter/issues/3200#issuecomment-165704948)

The issue can be closed, @per-samuelsson confirm please.

#### [Review and document how we specify metadata in json for TypedJson](https://github.com/Starcounter/Starcounter/issues/2650)

A small discussion issue with not very valuable information. Should be closed to don't sink in similar issues. @chrhol please confirm.

#### [Reuse Json in other Jsons](https://github.com/Starcounter/Starcounter/issues/2059)

I have added documentation for the `Reuse` keyword. Even though we would like to avoid the `$` usage, we have no other options of doing the `Reuse` and our customers keep asking about it.

The documentation is available on [starcounter.io](http://starcounter.io/guides/json/json-data-binding/#reuse-same-json-object). The issue closed.

#### [Document JSON dollar signs ($) and "Reuse"](https://github.com/Starcounter/Starcounter/issues/3086)

This issue is almost a duplicate of the one above. Should be closed, @per-samuelsson confirm please.

cc @per-samuelsson, @warpech, @chrhol, @dan31, @andwah

**Comment by per-samuelsson** [comment]
Nice initiative, @miyconst.

Off-tracker, @chrhol has assembled a nice document, somewhat similar to this, that I got some time ago in a mail. That one group similar efforts in logical areas of work, and currently, both me and @chrhol is working with stuff related to that, supervised by @dan31.

@chrhol: maybe you can put the content of that doc on Rebels Lounge?

**Comment by per-samuelsson** [comment]
> The issue (#3200) can be closed, @per-samuelsson confirm please.

Closed.

**Comment by per-samuelsson** [comment]
A few more comments on this issue:

> Some of them used very widely others very rarely, **some of them have c# equivalent**.

According to @chrhol, they have always had an aim that everything that is supported in JSON-by-example-"magic" should be driven by an underlying C# equivalent, so I think we are covered there.

On a more general note, the main challenges we are facing here is *editable fields* and how to support the *Reuse* feature in code. 

Regarding the former, it can be achieved with code-behind already, as you point out. But it's such a commonly used feature, even a purist such as myself are not convinced we should have people add that quite verbose code to make their properties editable, or should we? Maybe this thing is kind of a threshold feature, and one we actually should *continue* to feature as the one-and-only JSON-by-example-magic? But then again, if we do, and when we fix so that properties can "auto-map" to code-behind properties with the same name (something high up in the pipe), we can't use $, since that is not allowed in C# identifiers (I think). So there are several things to consider.

**Comment by miyconst** [comment]
>Maybe this thing is kind of a threshold feature, and one we actually should continue to feature as the one-and-only JSON-by-example-magic?

I tend to agree with this statement.

**Comment by per-samuelsson** [comment]
>> Maybe this thing is kind of a threshold feature, and one we actually should continue to feature as the one-and-only JSON-by-example-magic?

> I tend to agree with this statement.

Then to summarize, if we choose to take that path, our aim is:

1. Keep support JSON-by-example fields to be declared editable with a certain syntax (currently '$').
2. Remove all other "magic" from JSON-by-example.
3. Clearly define what things can be customized by code-behind and document every such feature.

**Comment by warpech** [comment]
I agree with the above.

**Comment by miyconst** [comment]
Sounds good for me as well.

I think the `$` sign to mark editable fields is a good solution, and we should not reinvent something new.

The only issue is `Reuse` keyword. It should be applied before compilation, not when program starts.

**Comment by chrhol** [comment]
> The only issue is Reuse keyword. It should be applied before compilation, not when program starts.

This is not true, it's only used during compile when the code is generated for TypedJson. That's true for most of the metadata that is specified. It's used to control what code is generated in the background and then compiled. 

Only `Bind`, and `Editable` properties can be changed runtime.

**Comment by miyconst** [comment]
@chrhol probably you misunderstood me.

I mean, that the `Reuse` should be applied and generate appropriate code instantly after user press `Ctrl + S` and before compilation. Otherwise it won't be available to write code with intellisense and without  errors.

**Comment by chrhol** [comment]
>  @chrhol probably you misunderstood me.

Yeah, I think so :)

> I mean, that the Reuse should be applied and generate appropriate code instantly after user press Ctrl + S and before compilation. Otherwise it won't be available to write code with intellisense and without errors.

This is exactly how it works. When you save (either the JSON-by-example file or the code-behind file) the TypedJson codegenerator is triggered and VS does an intellisense compile, which is then available for the developer. However it doesn't always work perfectly (working with build and VS triggers seldom does) and for example if there is a compiler-error from the generated code or some misspelling of something in the json file the intellisense build does not report it back to the user properly. You have to start a real build for that.

**Comment by miyconst** [comment]
>This is exactly how it works.

That is why I called it a limitation, I don't see how we can move it from JSON declaration to code behind.

**Comment by chrhol** [comment]
> That is why I called it a limitation, I don't see how we can move it from JSON declaration to code behind.

What do you mean? The codegeneration is triggered when you save the codebehind file as well. So add the reuse-command (however it looks) in codebehind, save and you will have intellisense for it.

**Comment by miyconst** [comment]
So, you can parse actual c# class and look for the `Reuse` declaration? I thought it would be much more complex than parsing a json file.

**Comment by chrhol** [comment]
> So, you can parse actual c# class and look for the Reuse declaration? I thought it would be much more complex than parsing a json file.

Aha, then I get your point. But yes, it's possible. Some info are already gathered from the codebehind-file today and when #3439 is in place it will be easier to add more things there. Hopefully enough so that we can keep as much as possible outside the Json-by-example file (or keep everything we don't want out).

**Comment by miyconst** [comment]
It would be really good. Then we can clean up json file from `$` usage.

**Comment by per-samuelsson** [comment]
> It would be really good. Then we can clean up json file from `$` usage.

I think we all agree on the aim outlined in this https://github.com/Starcounter/Starcounter/issues/3443#issuecomment-197271961. And one enabler for that, as @chrhol points out, is #3439, which I volunteered for last week. I already started it (but got interupted by evil @warpech and he's pushing for middleware view-from-viewmodel provision :smile:). As soon as I can finish that, I'm back on #3439.

**Comment by miyconst** [comment]
@per-samuelsson, @chrhol do we need this issue? I am about to close it.

**Comment by chrhol** [comment]
> @per-samuelsson, @chrhol do we need this issue? I am about to close it.

sorry, missed your last comment. Lets keep it open for now, as a reminder. I will probably start to work on some of these points. I assing it to me for the time being.

**Comment by chrhol** [comment]
Closing this issue now.
