### ISSUE TITLE
DLL duplicated error

### ISSUE THREAD

**Issue by binte** [Starcounter/Starcounter#3448]
I keep getting the error below when I run starcounter. The version I'm using is the 2.1.1389 version (nightly). Any idea on what I can do to fix this?

> At least one file considered a Starcounter edition library was found locally deployed with an application, i.e. residing in the same directory as the application file. 1 duplicate(s): Simplified.Data.Model.dll Version: 2.1.1389. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR12019.    at Starcounter.Weaver.FileManager.AddEditionLibraries(String[] editionLibraries, List`1 sourceFiles) in C:\BuildAgent\work\sc-develop-nightly-213\Level1\src\scweaver\FileManager.cs:line 267    at Starcounter.Weaver.FileManager.Open() in C:\BuildAgent\work\sc-develop-nightly-213\Level1\src\scweaver\FileManager.cs:line 166    at Starcounter.Weaver.CodeWeaver.Execute() in C:\BuildAgent\work\sc-develop-nightly-213\Level1\src\scweaver\CodeWeaver.cs:line 307    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\BuildAgent\work\sc-develop-nightly-213\Level1\src\scweaver\CodeWeaver.cs:line234    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\BuildAgent\work\sc-develop-nightly-213\Level1\src\scweaver\Program.cs:line 156    at Starcounter.Weaver.Program.Main(String[] args) in C:\BuildAgent\work\sc-develop-nightly-213\Level1\src\scweaver\Program.cs:line 37

**Comment by miyconst** [comment]
Set `Copy local: false` to the `Simplified.Data.Model.dll` reference.

**Comment by miyconst** [comment]
Read more here about deploying third party assemblies. http://starcounter.io/guides/tools/weaver/

**Comment by binte** [comment]
Thanks for the replies @miyconst ! 

I followed your tip, and set the property to false in all the references to the DLL, but it didn't fix the problem. Tomorrow morning I will go through the documentation and see if I can find a solution. I will then reply to this thread

**Comment by per-samuelsson** [comment]
@binte 

Sorry to see you experience this, and as @miyconst suggested, setting the reference not to copy local should do the trick. It's pretty weird that didn't solve it.

Can you try this tomorrow:

1. Set the reference as suggested, not to copy local.
2. Issue a Rebuild of the solution / project.
3. Open up the folder where the project build to (i.e. normally `bin\Debug` under your project folder). See if `Simplified.Data.Model.dll` is there, next to your `.exe` (it shouldn't be).

Thanks.

**Comment by binte** [comment]
Good morning,

I have three references in different projects within the solution, all set to false now. After rebuilding, in the folders related to projects in which I have the reference, the `Simplified.Data.Model.dll` is not there, as expected. Nonetheless, it is created in two other project folders. Which is the same behaviour I experience on the server, but it is working there, and not on my local machine. 

Removing the .dlls prior to restarting starcounter will lead to a ` ScErrWeaverFailedResolveReference (SCERR2147)`, so I decided to delete the solution folder and download the code again from github. Hopefully this will fix the issue

**Comment by per-samuelsson** [comment]
@binte 

About this:

> After rebuilding, in the folders related to projects in which I have the reference, the `Simplified.Data.Model.dll` is not there, as expected. **Nonetheless, it is created in two other project folders**.

How could that be? I don't understand the setup that produce this? Could you try elaborate a little on it, because the best guess I can have from this angle is that is what mess things up.

**Comment by binte** [comment]
I don't really understand why that happens, but I guess it's because of the dependencies. See the remaining of my answer, it might help you reach a conclusion! 

Deleting and downloading the code again didn't work. But I managed to fix the issue: 

The problem was the project A which had a reference to project B, and the latter runs with no problems. Since the project A just uses few functions from B, I copy pasted all the functions I needed in A, and removed the reference to B. Now I can also run project A

**Comment by per-samuelsson** [comment]
I'm glad to see you managed to work around it. But sad to see it was not easily solved. Also, I'd really would want to understand *what* happened here, and why it failed.

If it would be possible, I'd really want to take a look at your setup and see what you actually changed to fix it. Or that you describe the full, *failing* setup like a tree, and then I can try reproduce it with some similar setup. Like

```
my.sln
  foo.proj (dll)
    depends on: bar.dll
    depends on: simplified.data.model.dll
  bar.proj (dll)
  baz.proj (exe)
    depends on: foo.dll
```

With that being said, I do understand and respect you probably got more important and/or funnier things to do with your time, so if you are fine with how things worked out and just don't want to bother with it, feel free to close this issue. Just let us know how we can help if you need that!

**Comment by binte** [comment]
I am sorry, but I kept postponing this due to a lot of work in the office, and then I forgot about it :/  I am no longer working on the machine where I experienced this, so I can't reproduce the setup in which this error happened... Once again, sorry for that! I am closing the issue now
