### ISSUE TITLE
Support multiple, chained MIME provider middleware

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3451]
Extends #3444, after review.

As defined in #3444 (started [here](https://github.com/Starcounter/Starcounter/issues/3444#issuecomment-197763316)):

1. Mime providers must get access not only to the resource, but also to the request.
2. We must support multiple providers for a single MIME type.
3. We must support chaining of mime providers, so that they can invoke (or choose not to invoke) the next provider in the chain.)
4. Mime providers must get access to the result of previous providers in the chain.

Based on that, we are also splitting up `HtmlFromJsonProvider` into two distinct middleware: one providing the HTML, and another that can wrap the result of that in a "standalone" version (and possibly some more).

**Comment by per-samuelsson** [comment]
> We must support multiple providers for a single MIME type.

I'm putting a constant limit on how many MIME types any given application can provide for, setting the limit to 6. I'm doing this to be able to make a more efficient thread-safety mechanism, allowing reads to be lock-free.

Note this does not mean that we limit the number of *providers* in the chain, responding to a certain MIME type. That's still unrestricted.

@warpech, speak up if you think this is a limitation we can't have.

**Comment by warpech** [comment]
I think 6 is a low value... For example Google Docs supports 7 export formats:

<img width="572" alt="screen shot 2016-03-18 at 10 03 52" src="https://cloud.githubusercontent.com/assets/566463/13873292/c86a7038-ecf0-11e5-8a00-d071e9d461d2.png">

Another example: This is a chart of the image formats supported by the web browsers: https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support. It is possible that I have a web app which uses mime-based content negotiation to serve the best optimized image depending on the browser.

I think that the Pareto principle will be in place:

- most apps using 2-3 mime types
- some apps using 10-20 mime types

**Comment by per-samuelsson** [comment]
> I think 6 is a low value ...

Thanks for the input. Then lets go for 20. It waste a little more RAM, but still a very limited amount in real numbers.

The one that comes in asking for 21, we'll simple tell them that the have to switch to write their custom handlers, and not rely on MIME providers. Or, if they pay us (read: me) very much money, we can raise the limit in the upcoming version.

How about that?

**Comment by per-samuelsson** [comment]
Update: I'm in quite good shape with this one now. I've redesigned the API's and rewritten most of the underlying middleware code from the first version, and have now more or less completed 1-4 in the OP. I've also written a few tests (because underlying structures and locking-free mechanism got quite complex), and things seem to work. I need to move out the tests to some other spot eventually though.

With this, the experience now have changed to this:

```cs
static void Main() {
    var app = Application.Current;
    app.Use(new HtmlFromJsonProvider());
    app.Use(MimeProvider.Html((context, next) => {
        // context.Request give access to the request object
        // context.Resource give access to the resource as returned from the handler
        // context.Result is a byte[] that will be the result of previous providers, or null
        Console.WriteLine(context.Result == null);  // Will print false in this case
        next();
    }));
    app.Use(MimeProvider.Html((context, next) => {
        // The context also indicate how many previous providers have been invoked
        if (context.ProvidersInvoked != 2) {
            throw new Exception("Expected 2 providers, not " + context.ProvidersInvoked);
        }
        next();
    }));

    Handle.GET("/foo", () => {
        return new Foo();
    });
}
```

**Comment by per-samuelsson** [comment]
@warpech 

I'm not ready to merge it into main branch yet. But if you want to try it before I do that, branch `/issue/3451` is ready to be fetched and support everything described above.

**Comment by per-samuelsson** [comment]
I've now just merged and pushed this one, in https://github.com/Starcounter/Starcounter/commit/a116fc7c1563e31a8d0ab06136d95b64c3e2077e, along with an implementation of #3446.

That merge implements everything in the OP, plus that it split up the `HtmlFromJsonProvider`.

The new experience is described in this https://github.com/Starcounter/Starcounter/issues/3451#issuecomment-198390941. On top of that, there is now two new built-in middleware serving "implicit standalone wrapping" and auto-creation of sessions for scenarios where HTML is provisioned from JSON view models:

```cs
void Main() {
  var app = Application.Current;
  app.Use(new HtmlFromJsonProvider());
  app.Use(new PartialToStandaloneHtmlProvider());
  app.Use(new JsonAutoSessions());

  Handle.GET("/foo", () => { ... });
}
```

All feedback and/or testing is highly welcome!

**Comment by per-samuelsson** [comment]
(Now also merged to **pnext**)

**Comment by per-samuelsson** [comment]
Closing this one, and related, finished issues, @warpech. Once we get to another feedback round, we'll open up new specific issues if applicable.
