### ISSUE TITLE
Question : Whats the difference between daily and nightly build

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3456]
What is the main difference between daily and nightly builds. and what is the most stable build after 2.1.177?

**Comment by per-samuelsson** [comment]
@atifsheikh 

Daily builds runs just the most basic tests. Nighly builds are built once every night normally, and run a lot more tests.

The latest stable is `2.1.177`. We are just about to release a new stable. Maybe @dan31 can provide the best link to read about that plan?

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Starcounter/issues/2295

**Comment by warpech** [comment]
Releasee channels are also explained here: http://starcounter.io/guides/tools/release-channels-starcounter/
