### ISSUE TITLE
Push seems to work just sporadic

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3457]
We have implemented our own chat application and are using CalculatePatchAndPushOnWebSocket() to push messages and notifications to all sessions that needs it.

However, it seems to work very sporadic. Sometimes it works and sometimes it doesn't.
It seems like i have all appropriate sessions in my

```
Session.ScheduleTask(SessionsToUpdate...
```

But nothing seems to happen...

**Comment by dan31** [comment]
@malx122 thanks for reporting, @alemoi is now working on a very related zone and will take a look promptly. We now hope to have these all addressed during this week to have 2.2 released.

**Comment by alemoi** [comment]
Thank you for reporting! I would ask if 'Session.ScheduleTask' is not working properly or CalculatePatch inside each session task delegate? Do you have some test application with a few sessions to check this?

**Comment by malx122** [comment]
You can call me so I can show you!

**Comment by malx122** [comment]
Might be both actually... 
There is definitely problem with Session.ScheduleTask where it seems to skip all sessions provided at times (Can one wrong sessionid make all not run? There should be no problem with given ids since I remove them on Session.AddDestroyDelegate but you never know...)

**Comment by chrhol** [comment]
Is this still a problem or was it solved (uninentionally) when I fixed another bug around this?

**Comment by malx122** [comment]
It works a lot better now. But we did have a case last week when one of our members didn't get the pushes for a while. So we are not 100% sure yet.

**Comment by dan31** [comment]
@malx122 @chrhol @alemoi any more news on it?

**Comment by mtornwall** [comment]
Not sure if this is related to the issue I've been having, but here's a hint:

It seems that push, at least for me, is much more prone to failure if it happens very soon after the view model has been constructed. For me this happens when the view model starts an asynchronous operation that completes almost instantly and updates the view model with its result.

**Comment by dan31** [comment]
Last time we chatted in regards to 2.2.1 release and this issue. Should have been fixed by now. If not, let's reopen.
