### ISSUE TITLE
Replace Bootswatch Paper with another theme that does not use shadows

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3462]
Bootswatch Paper theme that is currently added by default to Starcounter does not play well with `juicy-tile-table`.

The reason for this is that is uses a lot of box-shadow for not only shadows, but also borders around elements. For `j-t-t`, it causes:

- hiding of the shadows on the top and left of the element
- scrollbars for the shadows on the right and bottom of the element

Long term solution is to allow shadows to bleed outside of the cell, but as far as I understand this is not doable right now (@tomalec correct me if I'm wrong). This long term solution is tracked in https://github.com/Juicy/juicy-tile-table/issues/4

Short term solution agreed with @miyconst is to find a theme that does not use shadows.

**Comment by warpech** [comment]
Related: https://github.com/StarcounterPrefabs/Launcher/issues/210

**Comment by tomalec** [comment]
I didn't say it's not doable, I said that we need to agree on consistent behavior of `juicy-tile-*` first.

**Comment by aloscha** [comment]
@warpech what about Material Design for Bootstrap?
Like that one: http://fezvrasta.github.io/bootstrap-material-design/#getting-started

**Comment by miyconst** [comment]
We currently use something like this, and such elements causes the issues described above.

![image](https://cloud.githubusercontent.com/assets/6435556/14112213/188f9c06-f5ce-11e5-9feb-bc8cc8750f8d.png)

**Comment by miyconst** [comment]
I found that applying simple css tricks/styles to the default bootstrap styles fixes issues with layout editor.

For example add the following lines to `/sys/bootstrap.html`:

```html
<style>
    .btn {
        /* Increase button tile size to show shadows */
        margin-bottom: 5px;
        margin-right: 5px;
    }

     /* Remove negative margin to eliminate horizontal scroll bar */
    .list-group-item {
        margin-bottom: 0px;
    }
</style>
```

**Comment by warpech** [comment]
I find this fundamentally wrong, for two reasons: 

1. box-shadows should not be part of the tile size
2. there is no such thing as `box-sizing: margin-box`, so how come can a button margin affect the measured size of a tile?

**Comment by miyconst** [comment]
I agree, but this could be a short term fix of current bootstrap theme.

**Comment by aloscha** [comment]
@miyconst maybe short term would be that one:
`<style>
    .btn {
        box-sizing: none !important;
    }
</style>`
?

**Comment by tomalec** [comment]
As https://github.com/Juicy/juicy-tile-table/issues/4 is fixed, and `juicy-tile-table` supports shadows for tiles gently. Do we still need this one?

**Comment by miyconst** [comment]
I don't think so. Now it looks really good with current theme.

@warpech do you agree?

![image](https://cloud.githubusercontent.com/assets/6435556/14263545/7065134c-fabb-11e5-8c47-85a5d170bf20.png)

**Comment by miyconst** [comment]
Closing this issue for now.
