### ISSUE TITLE
Explain SelfOnly

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3464]
Explain new API that was added in https://github.com/Starcounter/Starcounter/issues/3339

**Comment by warpech** [comment]
Sorry, this issue was supposed to be added in https://github.com/Starcounter/Starcounter.io/issues

The point is to explain the new API that was added in #3339 on starcounter.io

**Comment by alemoi** [comment]
Thanks for noticing! I explained `SelfOnly` in http://starcounter.io/guides/network/handling-requests/
