### ISSUE TITLE
JsonPatch: send patch for changed sibling instead of sending the whole json.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3465]
Currently when a new jsonsibling is detected on a merge, the whole json-object (including all siblings) are marked as replaced and sent to the client.

This should be changed so that only the changed sibling/values are sent, i.e work as patching is intended.

**Comment by chrhol** [comment]
I'm currently working on this. It requires some changes in how we treat siblings, but I think I have most of it in place. There are a few things left to make it work properly but should be finished soon.

**Comment by chrhol** [comment]
I have just pushed a possible solution for this issue to a separate branch (https://github.com/Starcounter/Starcounter/tree/issue/3465). It needs more testing though, which I will continue with tomorrow.

**Comment by chrhol** [comment]
I found a couple of bugs and I think this fix is in a good state now. I will check with @warpech though before pushing it to develop.

**Comment by warpech** [comment]
The original problem is fixed, but still there is one redundant replace for Launcher's data.

1. Run Launcher + People
2. Go to `http://localhost:8080/people/organisations`
3. Click on "People" in to menu (morphs to `http://localhost:8080/people/persons`)
4. See the incoming patches: https://gist.github.com/warpech/8faf3d2b568ebdea98673e3f1cd4a30d

The incoming patches first replace every property in `Launcher` data (for example: `/workspaces/0/Launcher/AppName`, etc), but finally again replace the whole `/workspaces/0/Launcher` object (see the last patch).

**Comment by chrhol** [comment]
> The original problem is fixed, but still there is one redundant replace for Launcher's data.

Yeah, this is another problem. The merger gets called more then once for the same object and two siblings from the launcher get's added. The first sibling get only it's values updated while the whole json is sent for the other.

For this we probably need to investigate and review how the merger and substitute-handlers works, maybe starting with what Alexey suggested in [this](https://github.com/Starcounter/Starcounter/issues/2690#issuecomment-193216563) comment

**Comment by chrhol** [comment]
Added another issue for reviewing the other problem and jsonmerger: https://github.com/Starcounter/Starcounter/issues/3470

**Comment by chrhol** [comment]
I've pushed the fix to develop and pnext now.

**Comment by chrhol** [comment]
Some more issues with this was found by @malx122. Does not work properly when changing and reusing siblings/partials. 

Working on a fix that is almost done.
