### ISSUE TITLE
Remove juicy-redirect

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3469]
@tomalec, do we actually need to distribute `juicy-redirect` with Starcounter? I think it is only used in Puppet web apps, and these rather use `puppet-redirect` (see: https://github.com/StarcounterPrefabs/Launcher/issues/216)

If `juicy-redirect` is needed, then I have to update it to 0.4.1 (released already). If not, then it should be removed.

**Comment by tomalec** [comment]
I don't think we need that.  We include libraries that are required to create an app in our way (Puppet-way). If app developer would like to create an app in his own way, he can always include `juicy-redirect`  or Polymer's `carbon/iron-router`

**Comment by warpech** [comment]
To make it smoother for developers, I will not remove it, but add a deprecation notice about juicy-redirect in Starcounter 2.2

**Comment by warpech** [comment]
I added a deprecation notice directly in the static file (bypassing Bower). I have no idea how to do it better without increasing repolepsy. 

Maybe I should just "freeze" the version by removing `juicy-redirect` from Starcounter client files `bower.json`? 

@tomalec WDYT?

**Comment by tomalec** [comment]
I think it's worth removing it from `bower.json` it would not get overwritten by update, and it would be easier to spot that something i going one, when you are running clean bower install that entire folder is to be removed.

The only idea that I have is to add a branch to `juicy-redirect` but it definitely increases repolepsy and branchitis.

**Comment by warpech** [comment]
> The only idea that I have is to add a branch to juicy-redirect but it definitely increases repolepsy and branchitis.

Also, we are not deprecating `juicy-redirect` but just its distribution with Starcounter. So this would need to be on Starcounter's fork of `juicy-redirect`. Totally not worth doing.

I will remove it from `bower.json`

**Comment by warpech** [comment]
Note to self: add a blog post that elaborates on why juicy-redirect is deprecated, how to switch to puppet-redirect and how to add juicy-redirect to your app if you want to use that one. 

(inspired by https://github.com/Starcounter/Starcounter/commit/8bd57a780f5ff9a04d3919285d1f530788d6ab4a#commitcomment-16966707)

**Comment by warpech** [comment]
Starcounter 2.2 release notes will contain the following information about why was this removed and how to update your apps:

> **juicy-redirect** was marked as deprecated. It will be removed from distribution with future versions of Starcounter. Puppet web apps should use `puppet-redirect` for morphing between pages.
