### ISSUE TITLE
Review the jsonmerger and in what conditions it should be executed.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3470]
After the merge-callback was added we started noticing that the merger of jsonresponses that is used to allow blending on the client gets called a lot and sometimes more then once for the same json.

This together with how the substitute-handlers and the mergecallback works sometimes make an app have more then one json in the siblings which is not good.

As @alemoi suggested in [this](https://github.com/Starcounter/Starcounter/issues/2690#issuecomment-193216563) comment, we should start with documenting when it should be called and then see what the next steps will be.

/cc @alemoi, @warpech, @miyconst

**Comment by chrhol** [comment]
Here is one problem with the current implementation. I'm not saying that it is the merger that is the problem though, maybe it's the callback or the substitute-handler, but it's difficult to say without knowing exactly how the merger should work. Copied from https://github.com/Starcounter/Starcounter/issues/3465#issuecomment-204335008

1. Run Launcher + People
2. Go to `http://localhost:8080/people/organisations`
3. Click on "People" in to menu (morphs to `http://localhost:8080/people/persons`)
4. See the incoming patches: https://gist.github.com/warpech/8faf3d2b568ebdea98673e3f1cd4a30d

The incoming patches first replace every property in `Launcher` data (for example: `/workspaces/0/Launcher/AppName`, etc), but finally again replace the whole `/workspaces/0/Launcher` object (see the last patch).

**Comment by chrhol** [comment]
@malx122 found another place where a lot of `LayoutInfo` objects are added due to having many apps mapped to the same data and making their own `Self.Get`. 

This led to that the wrong layout (and merged html) was used on the client. 

I'm not sure how to solve this, so I added a workaround/hack in the merger that filters out all old partial responses from the same app. Now this works due to the fact that we don't handle more than one partial response from the same app anyway, but it needs to be changed when we do (and when we find the proper solution of course). 

Just wanted to add it here, so it doesn't get forgotten. Will link this issue in the commit.

**Comment by warpech** [comment]
I just checked the last stable (2.2.1811) and the last nightly (2.2.1813) and still `Html` property does not work well. In fact, when a single app is running, the `Html` property seems to be not populated at all. See the below screenshot.

The code is here: https://github.com/warpech/HelloWorld/blob/0d9cae5f4ad423b7cf65f0287ce2780b0ddd90f5/Program.cs

Instructions:

1. Start HelloWorld app
2. Create some expense item (by clicking "Add")
3. Reload the page and see the view-model

![2016-04-19 10_34_21-helloworld](https://cloud.githubusercontent.com/assets/566463/14632994/cf09a2ee-061b-11e6-8fcd-ad3306770ec9.png)

**Comment by chrhol** [comment]
Yes, our current solution for htmlmerger does not work together with the new middleware for returning partials as far as I know.

This together with that we require the Launcher to run to use the merger is the two main reason for fixing the htmlmerger.

**Comment by chrhol** [comment]
Note: I have not touched how the `Html`-property works in the serializer. This code is exactly the same as before.

**Comment by warpech** [comment]
> Yes, our current solution for htmlmerger does not work together with the new middleware for returning partials as far as I know.

This badly needs a fix then, because Page class is about to be removed (https://github.com/Starcounter/Starcounter/issues/3202, https://github.com/Starcounter/Starcounter/issues/3165).

**Comment by tomalec** [comment]
I have created separated issues to the ideas we found today. 
https://github.com/Starcounter/Starcounter/issues/3539
https://github.com/Starcounter/Starcounter/issues/3538

To you think we can close this one?

**Comment by chrhol** [comment]
> To you think we can close this one?

Yes, lets do that.
