### ISSUE TITLE
How to set cookie in Starcounter.Response

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#3473]
I am failing to set a http cookie. The response looks perfectly fine when I debug but my brwoser is enable to store the cookie that I specify

Code: 

		Response response = new Response() {
			Body = responseBody
		};
		string cookie = "uid=testId; path=/; expires=Fri, 10 Jun 2016 11:58:18 GMT; httponly; domain=www.hiddenurl.net:8282;";
		response.Cookies.Add(cookie);
		response["Access-Control-Allow-Origin"] = "*";
		response.StatusCode = 200;
		return response;

Response: 
		HTTP/1.1 200 OK
		Server: SC
		Access-Control-Allow-Credentials: true
		Access-Control-Allow-Origin: *
		Date: Tue, 05 Apr 2016 11:07:59 GMT
		Cache-Control: no-store
		Set-Cookie: uid=testId;path=/; expires=Fri, 10-Jun-2016 11:58:18 GMT;HttpOnly;domain=www.hiddenurl.net:8282;
		Content-Length: 21

Is this a Starcounter issue, code issue, or server issue? 

Any help would be appreciated.

**Comment by miyconst** [comment]
This happens because Response you set the cookie to is not the root level response.

You should use the following code to set cookies:

```cs
Handle.AddOutgoingCookie("cookieName", "cookieValue");
```

**Comment by Ripipip** [comment]
Just as before the response I get contains the right information for storing a cookie without it actually storing it. With this code I dont know how to set expires, path and domain though. How would I do that? Just as before the response I get contains the right information for storing a cookie without it actually storing it. With this code I dont know how to set expires, path and domain though.

**Comment by miyconst** [comment]
Seems like your date format is incorrect. See an example: https://www.nczonline.net/blog/2009/05/05/http-cookies-explained/

```
Set-Cookie: name=Nicholas; expires=Sat, 02 May 2009 23:38:25 GMT
```

You can use `Starcounter.Cookie` class to generate cookie value.

**Comment by miyconst** [comment]
The source code for the `Cookie.cs` class is available here: https://github.com/Starcounter/Starcounter/blob/57c6d056c5a43e4ffabbea3f261e3f30219220b1/src/Starcounter.Internal/Http/Cookie.cs

**Comment by Ripipip** [comment]
Handle.AddOutGoingCookie(string,string) seems difficult to use for adding cookies. it kinda gives the right response by doing it like this: 

                Starcounter.Cookie cookie = new Starcounter.Cookie() { Name = "uid", Value = "testCookie", Expires = DateTime.Now.AddMonths(6), Path = "/" };
                Handle.AddOutgoingCookie(cookie.Name, cookie.GetFullValueString());

But the datetime for expires is now even more weirdly formatted. 

Response: 

HTTP/1.1 200 OK
Server: SC
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Date: Tue, 05 Apr 2016 11:44:32 GMT
Cache-Control: no-store
Set-Cookie: uid=testCookie; expires=2016-10-05T13:44:32.514Z; path=/
Content-Length: 20

**But most important is that the cookies is not stored.**

**Comment by miyconst** [comment]
I bet it's something wrong with your browser. I just tested same setup:

```cs
Cookie cookie = new Cookie() { Name = "MyCookie", Expires = DateTime.Now.AddDays(10), Value = "MyValue", Path = "/" };
Handle.AddOutgoingCookie(cookie.Name, cookie.GetFullValueString());
```

![image](https://cloud.githubusercontent.com/assets/6435556/14281034/e92b7fca-fb36-11e5-9add-ad02f353d487.png)


![image](https://cloud.githubusercontent.com/assets/6435556/14281010/c0ae915e-fb36-11e5-9b0d-f170f89e94c9.png)

**Comment by Ripipip** [comment]
I get the exact same response. But if you actually look at your stored cookies in your browser, do you see the cookie? I dont. And when I send a new http request to the same server the cookie is not in the request.

**Comment by miyconst** [comment]
Yes, as my images shows, the cookie is stored, and it also persists in the next request:

![image](https://cloud.githubusercontent.com/assets/6435556/14281146/a430ba1a-fb37-11e5-900d-b0981096eba5.png)

**Comment by Ripipip** [comment]
Do you return this inside of a scope or something? 

I return this in a handler with a url that I then just reload over and over again. 

I have tried with multiple browsers without achieving any different result.

**Comment by miyconst** [comment]
@Ripipip I will create an example in KitchenSink. You can track progress in this issue: https://github.com/StarcounterSamples/KitchenSink/issues/30.

**Comment by alemoi** [comment]
Are you using the same version of Starcounter guys? Just to be sure.

**Comment by miyconst** [comment]
My version: `Starcounter-DevelopNightlyBuilds-2.1.1605`.

**Comment by Ripipip** [comment]
Current version: Starcounter-Stable-2.1.177 (Oct 14, 2015 5:28:43 PM)

**Comment by miyconst** [comment]
@Ripipip I have just created an example in KitchenSink for setting a cookie on server side. The example was tested with Starcounter stable and nightly. Take a look please.

**Comment by Ripipip** [comment]
Thank you! This helped me figure out how to deal with the cookies :)

**Comment by miyconst** [comment]
Glad to help. Please close the issue if it works for you.
