### ISSUE TITLE
Build server with multiple starcounter versions

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3476]
We have a dedicated build server for our Starcounter apps. What would be the recommended way to build against different versions of Starcounter?

My idea is to 

1. manually create a set of Starcounter folders:

    C:\Program Files\Starcounter-DevelopDailyBuilds-2.1.1658
    C:\Program Files\Starcounter-DevelopDailyBuilds-2.1.XXXX

2. set the `StarcounterBin` environment variable in each BAT-file that coordinate the `MSBuild.exe`calls.

Would this solution work? Do you do something similar on your build-server?

**Comment by alemoi** [comment]
Good question!

> Would this solution work? Do you do something similar on your build-server?

Yes, if you keep the isolated environments with independent folders with binaries and different `StarcounterBin` variables for each cmd session, then everything should work. However, this might not work with Visual Studio extension, but I suppose you don't need that, do you?

If you need to build certain projects but you don't need UI, then the following might be helpful, for example:
```
"%MsbuildExe%" "Simplified/Simplified.sln" /p:ReferencePath="%StarcounterBin%;%StarcounterBin%/EditionLibraries;%StarcounterBin%/LibrariesWithDatabaseClasses" /p:Configuration=%Configuration%
```

On our build servers there are sometimes several installations like that. So, cmd with specific StarcounterBin, does the trick.

**Comment by alemoi** [comment]
To create a server repository in folder .srv, run the following command (StarcounterBin should be defined at this point): star.exe @@CreateRepo .srv

**Comment by per-samuelsson** [comment]
> However, this might not work with Visual Studio extension, but I suppose you don't need that, do you?

I actually think that should work too, at least in theory. If I recall correctly, the registry entries we need to write to install the extension is specified with that same environment variable, resolved at VS loading up the package.

I've never tested that myself though.

> To create a server repository in folder .srv, run the following command (StarcounterBin should be defined at this point): star.exe @@CreateRepo .srv

Just be aware of #2109, even that one is pretty old by now and doesn't get much love. :smile:

**Comment by ivarbergman** [comment]
This is great! Adding `/p:ReferencePath=...` in the msbuild parameter list was the missing piece. Now we build our applications on different Starcounter.

Thanks!
