### ISSUE TITLE
Handle.AddRequestFilter is deprecated in favour to Application.Use

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3477]
I just have discovered that 

```cs
Handle.AddRequestFilter((Request req) => { });
```

Is now deprecated, but still promoted on our [Request and response filters](http://starcounter.io/guides/network/request-response-filters/) page.

The new syntax proposed to use is `Application.Use`, and it does not have a sign of documentation.

cc @warpech, @per-samuelsson, @alemoi, @chrhol

**Comment by warpech** [comment]
Are "obsolete" and "deprecated" synonyms? CHANGELOG says it is "made obsolete".

First step is to include documentation for `Application.Use` in http://starcounter.io. Right now, it is only on https://github.com/Starcounter/RebelsLounge/blob/master/Uncategorized/Middleware.md, which is not ccessible to the general public.

After that we we need to switch [remaining sample apps](https://github.com/search?q=addrequestfilter+user%3AStarcounter+user%3AStarcounterSamples+user%3AStarcounterPrefabs+user%3AJuicy+user%3AStarcounter-Jack+user%3APuppetJs&type=Code&utf8=%25E2%259C%2593) to use the new recommended pattern. I will make separate issues for that.

Most importantly, Launcher is already changed.

The previous pattern (`AddRequestFilter`) should stay supported at least until 2.3. 

@per-samuelsson do you agree? Could you write the docs for `Use` on starcounter.io?

**Comment by warpech** [comment]
Documentation for `AddRequestFilter` for reference should be available at least as long as Starcounter 2.1.177 is available to download.

**Comment by miyconst** [comment]
Okay. SignIn app should also be fixed then.

`obsolete` - old, going to be removed feature.
`deprecated` - not recommended, going to be removed feature.

So it's kind of synonyms.

**Comment by per-samuelsson** [comment]
> Are "obsolete" and "deprecated" synonyms? 

In practice, yes.

> @per-samuelsson do you agree? 

I do.

> Could you write the docs for Use on starcounter.io?

I can. :smile: 

Also, I just recalled that I might have forgot to add this thing to the changelog. I'll take it on me to verify that and do it if it's not done.

**Comment by miyconst** [comment]
The [Request and response filters](http://starcounter.io/guides/network/request-response-filters/) page has been updated. 

@alemoi you are the author of the page, I tried not to rewrite entire page, but adjust it with the new API. Please take a look and add any change you like.

**Comment by warpech** [comment]
Great job!

Shouldn't the page be renamed to `Middleware`?

**Comment by miyconst** [comment]
`Middleware` seems to be too unclear, actually I don't know how to name it, so I left it as it was before.

**Comment by warpech** [comment]
I don't agree, I think this is a well known concept in every modern web framework that I can think of:

- https://docs.asp.net/en/latest/fundamentals/middleware.html
- http://expressjs.com/en/guide/using-middleware.html
- https://docs.djangoproject.com/en/1.9/topics/http/middleware/
- http://www.sinatrarb.com/intro.html#Rack%20Middleware
- https://laravel.com/docs/master/middleware

Nevertheless the [first paragraph](http://starcounter.io/guides/network/request-response-filters/#request-previously-middleware-filters) explains what is the purpose of it quite well.

**Comment by miyconst** [comment]
Okay, it's me not updated with the latest terminology. Renamed the page to [Using middleware](http://starcounter.io/guides/network/using-middleware/).

**Comment by warpech** [comment]
Great, thank you!
