### ISSUE TITLE
Question : Is there any query to check all Tables and total number of rows in each table

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3478]
Is there any query to check all Tables and total number of rows in each table?

**Comment by k-rus** [comment]
Thank you for your question.
Metadata does not contain any statistics. Current version of SQL does not allow to write your request in single query (as any standard SQL implementation). Thus you need to write program, which first retrieves list of tables from meta-data and then issues aggregate queries to count number of rows. Note it will be expensive.

**Comment by atifsheikh** [comment]
@k-rus Thanks :+1:
