### ISSUE TITLE
Remove link to object.obser & array.observe from Partial.cs

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3483]
The object.observe and array.observe shims are no longer required.

cc @warpech, @per-samuelsson

**Comment by warpech** [comment]
Thanks for reporting. The highlighted lines need to be removed: https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/Middleware/PartialToStandaloneHtmlProvider.cs#L22-L23

I will do it.

**Comment by warpech** [comment]
Done. Once again - thanks for noticing!
