### ISSUE TITLE
Why substitute handlers should return a result?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3484]
We support substitute `Self.GET` calls like:

``` cs
page.Partial = Self.GET("/an/un-registered/url", () => new Page());
```

In most cases when a substitute handler is called, the local response is just an empty page. Why do we need it?

I tried: 

``` cs
page.Partial = Self.GET("/an/un-registered/url", () => null);
```

It throws null reference exception. I propose to add another overload for substitute handlers:

``` cs
page.Partial = Self.GET("/an/un-registered/url", true);
```

cc @alemoi

**Comment by per-samuelsson** [comment]
Anyone care to explain exactly 

1. what a "substitute handler" is, 
2. when those where introduced, and 
3. some use-case where they are needed?

I've seen them considered in quite a few spots in the code when I reviewed the request pipeline, and never understood what they were.

**Comment by miyconst** [comment]
Here is a short explanation:

1. It's a `Self.GET` call with func to be used instead of handler.
2. It was introduced long time ago, not sure when.
3. This is needed to get partials from other applications via `UriMapping` when requesting app does not have a handler for this url.

The most common example is Launcher. It has a section menu, Launcher has to show menu partials from other applications, but does not have a partial on its own.

```cs
masterPage.MenuPartial = Self.GET("/sc/mapping/launcher-menu", () => new Page());
```

There is no handler for `/sc/mapping/launcher-menu`, but the exact url will be never be triggered as the response is provided in place `() => new Page()`. The response will be merged with all responses from other apps mapped to `/sc/mapping/launcher-menu`.

**Comment by per-samuelsson** [comment]
Thanks for the clarification of that @miyconst. Sorry if it was a bit off-topic.

**Comment by warpech** [comment]
@miyconst care to add this explanation to http://starcounter.io/guides/network/handling-requests/?

**Comment by miyconst** [comment]
Added an issue for that: https://github.com/Starcounter/starcounter.io/issues/153, will try to find sometime for it as well.

**Comment by per-samuelsson** [comment]
> care to add this explanation to http://starcounter.io/guides/network/handling-requests/?

Really, should we? It seem to me that this kind of feature is rather ... well, very niched. Isn't it? And that section there seem quite general in comparison.

If like < 1% of our developers will ever need it or get in contact with it, then I think we should keep it somewhere more "advanced". 

Documentation is always good, but we need to consider where stuff are to be documented and about the audience. A lot of documentation can give you the impression of a complex product to use, which is not what we want.

**Comment by miyconst** [comment]
@per-samuelsson I was asked about this feature by @aloscha and Harri from ModularManagement. So, I think it should be explained.

Even if no, I still think it should be explained, and possible renamed to `anonymous handlers`. In c# we have anonymous delegates, anonymous functions, similar things in JavaScript.

The concept of providing `body` of something in place where it is used rather than defining such block is very common.

**Comment by per-samuelsson** [comment]
>  [...] possible renamed to anonymous handlers. In c# we have anonymous delegates, anonymous functions, similar things in JavaScript.

Sound like a wise idea to me! :+1:

**Comment by alemoi** [comment]
I was thinking a bit about this. For example, for the following Self call:
```
page.Partial = Self.GET("/an/un-registered/url", true);
```
what should the `page.Partial` be? Probably it should be a valid JSON, so that it has JSON siblings (that come from other apps) which will be serialized when response is returned. Right?

**Comment by alemoi** [comment]
It also means that siblings has to attach to something, so there can't be "no JSON" to attach to, it should be at least an empty JSON object (that we have as a `new Page()` here), right @chrhol ?

**Comment by miyconst** [comment]
I don't know how this created on server side. On the client side it's an object with property per each app response. The substitute handler owner's response is empty. For me it is logical to remove it at all.

**Comment by chrhol** [comment]
> what should the page.Partial be? Probably it should be a valid JSON, so that it has JSON siblings (that come from other apps) which will be serialized when response is returned. Right? @chrhol am I correct in explanation about how JSON siblings are found?

> It also means that siblings has to attach to something, so there can't be "no JSON" to attach to, it should be at least an empty JSON object (that we have as a new Page() here), right @chrhol ?

Yes, exactly. The app that makes the original call (or initiates the `Self.GET`) have to return and attach something  to the viewmodel. If nothing is returned, the app cannot attach anything to the viewmodel and the siblings will never be found. 

> I don't know how this created on server side. On the client side it's an object with property per each app response. The substitute handler owner's response is empty. For me it is logical to remove it at all.

I'm not sure what you mean by remove it all. Not include that property when sending the json to the client if it is empty? Or are you talking about how the substitute handler works today?

It should be possible to include any empty Json (as @alemoi stated above) as a substitute automatically if no response for the calling app was found.

**Comment by miyconst** [comment]
Okay, I try to explain a bit more.

### Launcher app

```cs
MasterPage master = new MasterPage();

master.Partial = Self.GET("/sc/mapping/menu", () => new Page());
```

### Products app

```cs
UriMapping.Map("/products/menu", "/sc/mapping/menu");
```

### On the client side

```json
{
    "Partial": {
        "Launcher": { "Html": "" },
        "Products": { "Html": "/Products/viewmodels/MenuPage.html" },
        "Html": "/sc/htmlmerger?Products=/Products/viewmodels/MenuPage.html"
    }
}
```

So, my question is, what for we need `() => new Page()` and `"Launcher": { "Html": "" }` if it does not make any difference in the application?

I would prefer to see:

```cs
master.Partial = Self.GET("/sc/mapping/menu", true);
```

```json
{
    "Partial": {
        "Products": { "Html": "/Products/viewmodels/MenuPage.html" },
        "Html": "/sc/htmlmerger?Products=/Products/viewmodels/MenuPage.html"
    }
}
```

**Comment by alemoi** [comment]
> So, my question is, what for we need () => new Page() and "Launcher": { "Html": "" } if it does not make any difference in the application?

Sure, in this particular case this is not needed. Just a side question: do we use substitute handlers anywhere outside Launcher, @miyconst ?

**Comment by miyconst** [comment]
Right now only in Launcher and ModularManagement sample app.

**Comment by alemoi** [comment]
> Right now only in Launcher and ModularManagement sample app.

Good. How many of substitute handlers return something different then `new Page()`? Just few, none or many? :)

**Comment by miyconst** [comment]
Right now all of them return empty page.

**Comment by alemoi** [comment]
> Right now all of them return empty page.

Good. Do we see other usages for substitute handler, other then this situation related to mapping, that calling app does not define a mapped handler and just wants the substitute with empty page? @warpech maybe you have some opinions also on this.

**Comment by dan31** [comment]
The question is almost a year old, thus I am archiving it in hope it is answered fully enough. @miyconst if it isn't, please feel free to re-open. Often don't be ashamed to close old questions too 😺
