### ISSUE TITLE
MaximumReceiveContentLength parameter exceeds maximum value

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3492]
I get warnings in Latest nightly build :

"Gateway XML: MaximumReceiveContentLength parameter exceeds maximum value. Current value is set to 2096936."

should i be worried?

**Comment by alemoi** [comment]
Thanks for the question. Nothing to worry about. This value was decreased in time but the configuration contains the old value. If you change the value to `2096936` in the configuration - the warning will disappear.
