### ISSUE TITLE
Critical type crash : "Assertion failed"

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3493]
I got this exception and everything crashed. I could not even see the SC Admin Panel. 

```
Assertion failed (!""Reached maximum number of tries to obtain a global lock."") at C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-268\Level1\src\scnetworkgateway\OurHeaders\gateway.hpp:2106 (Data 0).
    00007FFB415A11E9 sccoredbg!do_handle_assertion_failed : assert-win.cpp (76)
    00007FFB415A1039 sccoredbg!handle_assertion_failed : sccoredbg.cpp (29)
    00007FF6233A8FDC scnetworkgateway!starcounter::network::GatewayWorker::WorkerEnterGlobalLock : worker.hpp (368)
    00007FF6233AF315 scnetworkgateway!starcounter::network::HttpProto::HttpUriDispatcher : http_proto.cpp (645)
    00007FF6233AFB0B scnetworkgateway!starcounter::network::OuterUriProcessData : http_proto.cpp (1060)
    00007FF62339559B scnetworkgateway!starcounter::network::GatewayWorker::RunReceiveHandlers : worker.hpp (534)
    00007FF6233B8149 scnetworkgateway!starcounter::network::GatewayWorker::WorkerRoutine : worker.cpp (1788)
    00007FF62339DDA8 scnetworkgateway!starcounter::network::GatewayWorkerRoutine : gateway.cpp (3126)
    00007FFB497513D2 KERNEL32!
    00007FFB4C0354E4 ntdll!
```

**Comment by alemoi** [comment]
Thanks for reporting! My guess that this occurs occasionally when you start a database (or the first application)?

**Comment by atifsheikh** [comment]
This occurred 1st time for me. But i could not check the scenario in which this occurred. My team saw the crash and i reported it. Sorry for few details.

**Comment by alemoi** [comment]
Just to note, the current workaround is to set `WorkersNumber` to 1 in `scnetworkgateway.xml` in your server directory.

**Comment by atifsheikh** [comment]
Do you recommend to update the xml anyway or should i wait for the server to crash again. 
As i mentioned I have seen this crash for the 1st time.

**Comment by alemoi** [comment]
I thought if this crash annoys you and occurs not during startup but during runtime (which I doubt actually) then you can set it to 1.

**Comment by atifsheikh** [comment]
Sure, if it occurs again, i will update the XML. Thanks :)

**Comment by alemoi** [comment]
@atifsheikh can you please give an overview if there is anything special in the `main()` of your startup application? Like WebSockets registration or something specific? Thank you!
Also did it occur again after setting `WorkersNumber` to 1?

**Comment by atifwaqar** [comment]
@alemoi we are registering all of our handlers in main(), and nothing other than that. 

and the exception didnt occur again.

**Comment by alemoi** [comment]
Thank you for the response @atifwaqar !
The code related to this original issue is rewritten, the issue should be fixed now. However, if it occurs again we will reopen the issue.
