### ISSUE TITLE
Can't use HtmlFromJsonProvider

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3496]
Based on the sample use case illustrated in https://github.com/Starcounter/Starcounter/issues/3451#issuecomment-198390941, the code in https://github.com/warpech/SimplePuppet/blob/middleware/Program.cs should result in either:

1. a partial HTML response (blank browser screen without implicit standalone mode)
2. actual working app in the web browser (with implicit standalone mode)

Instead, I am seeing just a JSON response. Am I using it wrong or is it a regression in middleware?

![screen shot 2016-04-13 at 22 13 28](https://cloud.githubusercontent.com/assets/566463/14507860/f904e564-01c4-11e6-8318-0db0ed9e6ac2.png)

cc @per-samuelsson

**Comment by per-samuelsson** [comment]
@warpech 

Give me a moment to consider this and take a look at the code again, and I'll get back to you.

**Comment by per-samuelsson** [comment]
I've now set up an environment and diagnosed it, and some recent change in the request pipeline has invalidated middleware to be called. :cry: 

I need to investigate more to see what it actually is.

**Comment by per-samuelsson** [comment]
Wow, this one beats me. As I see it, this could just never have worked. I'm really surprised this did not surface before.

I can add a really simple thing and it will work (just passing an optional parameter), but I'm not sure if it's safe to do so, so I need to consult someone that know that code better before I dare to. I'll get back on that.

**Comment by per-samuelsson** [comment]
Note to self: when fixing this, also add #3451 to the changelog. I forgot the last time around.

**Comment by per-samuelsson** [comment]
I've now made the proposed fix, after doing some consulting on it, and merged/pushed it in https://github.com/Starcounter/Starcounter/commit/1b4aa1fabf5e6b4a3f42e1aa361b2071302efe57.

Will merge that to **pnext** too, but I need to switch to some other emergency right now, so it will be a little later.

**Comment by per-samuelsson** [comment]
> Will merge that to pnext too

Done. Feel free to close this issue once you've had the chance to test it @warpech. And sorry for the inconvenience.

**Comment by per-samuelsson** [comment]
> Done. Feel free to close this issue once you've had the chance to test it @warpech. And sorry for the inconvenience.

Bump @warpech.

**Comment by warpech** [comment]
Assigning to myself for testing

**Comment by warpech** [comment]
I confirm, `HtmlFromJsonProvider` now works as expected. Thanks!

**Comment by warpech** [comment]
@per-samuelsson do you confirm that this is the correct way to use `PartialToStandaloneHtmlProvider`? I am not suspicious, just wanting to confirm :)

https://github.com/warpech/SimplePuppet/blob/6038b47ccecd7fc73f907061b89b1b91212ddbaa/Program.cs

**Comment by per-samuelsson** [comment]
> @per-samuelsson do you confirm that this is the correct way to use PartialToStandaloneHtmlProvider? I am not suspicious, just wanting to confirm :)

It is, yes. It's important to remember that the order in which middleware is registered is important, and that follow the design of how DNX / ASPNet 5 model it. The order you register that pair is the correct one. If you toggle it, partial-to-standalone will produce nothing (and you'll just get the partial back).

**Comment by warpech** [comment]
> It is, yes. It's important to remember that the order in which middleware is registered is important, and that follow the design of how DNX / ASPNet 5 model it. The order you register that pair is the correct one. If you toggle it, partial-to-standalone will produce nothing (and you'll just get the partial back).

I think this is fully understandable, but it will be good to include a notion of it in the docs.
