### ISSUE TITLE
Question about changing properties

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3499]
Hi, we have a DB object that have properties as 

```
        public Person _receiver;
        public Person Receiver
        {
            get { return _receiver; }
            set { _receiver = value; }
        }
```

But we have realised that "Person" was not a good type to use so we want to change it to "TunityUser" instead. We however, want to preserve any data already in the DB. So I try this

```
        //Efter:
        [Obsolete]
        public Person _receiver;

        public TunityUser _userreceiver;
        public TunityUser Receiver
        {
            get { return _userreceiver; }
            set { _userreceiver = value; }
        }
```

Will this work? (I have an manual upgrade function that moves and update data from `_reciever` to `_userreceiver` )

I also have a Index on `Receiver`, what will happen there?

**Comment by k-rus** [comment]
Thank you for your question. First of all this depends on the version, which you are using. Behaviour of version from nightly or stable is different from pnext nightly. This is important to know

I cannot answer your question immediately as it is necessary to check the actual source code.

I can say directly about Nightly or Stable that if you change `public Person Receiver` to `public TunityUser Receiver`, the app will start without problem. If `TunityUser` is subtype of `Person`, the queries will work accordantly without errors, since the actual type is tracked when CLR proxy objects are allocated. Furthermore, if all your actual receiver objects are already `TunityUser`, then I expect that everything works. However, it has to be tested to be sure. (if some receivers are not `TunityUser`, but `Person`, the queries might not show them and you have to manually convert them and fix references)

Let us know if you need more information.

**Comment by malx122** [comment]
I'm using 2.1.1658 at the moment.
First of all `TunityUser` and `Person` is NOT of any subtype to eachother, totalt different DB-objects.
Second If you look above you see that I only change the get/set property `Reciever` to change Type and point to another property, the `_receiver` property is not changed.

So my hope was that for DB objects already created,  `_receiver` would go unhanged and still include the `Person`s I assigned by using `Receiver` before the modification. But that new assigned `Reciever` in the form of `TunityUser` will be stored in `_userrecevier`. This way I can manually convert already created DB objects.

**Comment by k-rus** [comment]
Thank you for the clarifications. I think it should work as you expect however it is necessary to check to fully confirm. If you don't want to wait you can do small app example with your case and see if it works as expected or not.

**Comment by malx122** [comment]
But my biggest conern is about the Index that looks like this
```
TunityX.RegisterIndex("NotificationReceiverTimeIndex", "Concepts.Ring8.Tunity.Notification (Receiver, NotificationTime DESC)");
TunityX.RegisterIndex("NotificationReceiverViewedTimeIndex", "Concepts.Ring8.Tunity.Notification (Receiver, Viewed, NotificationTime DESC)");
```
What will happen to them? Will they be automatically rebuilt with the new `Recevier` property?

**Comment by k-rus** [comment]
Thank you for reminding about the index question. Indexes are defined in terms of underlying columns. If our assumption is correct, then the indexes are defined in terms of `_receiver`.  Thus you need to create new indexes. I suggest to drop the old ones too.

**Comment by malx122** [comment]
Ok, thanks!

**Comment by malx122** [comment]
Is this enough to recreate index (no restart of server):
think `forceRecreate=true`
```
        public static dynamic RegisterIndex(String name, String index, Boolean forceRecreate = false)
        {
            var mdi = Db.SQL<Starcounter.Metadata.Index>("SELECT i FROM Starcounter.Metadata.\"Index\" i WHERE Name = ?", name).First;
            if (mdi != null && forceRecreate)
            {
                mdi.Delete();
                mdi = null;
            }
            if (mdi == null)
            {
                return Db.SQL(String.Format("CREATE INDEX {0} ON {1}", name, index));
            }
            return null;
        }
```

**Comment by malx122** [comment]
Or do I need "DROP INDEX" ?

**Comment by k-rus** [comment]
It is not possible to create an index with the same name. So if you want to use the old name for the index, you have to drop it. Yes, you use `DROP INDEX index_name ON table_name`. See [our guide about indexes](http://starcounter.io/guides/sql/indexes/).

**Comment by malx122** [comment]
ok, thanks!

**Comment by dan31** [comment]
All legit refactorings in 2.3 are thoroughly documented in here: https://docs.starcounter.io/guides/working-with-starcounter/database-refactoring/.
