### ISSUE TITLE
Problem connecting to the DB on 2.1.1742

### ISSUE THREAD

**Issue by binte** [Starcounter/Starcounter#3504]
We have been experiencing some problems since we updated the starcounter version, to the nightly build 2.1.1742. Please see the attached screenshot. We are getting that error every now and then. Do you recognise the issue? Is there a way for us to fix it?

![starcounter bug](https://cloud.githubusercontent.com/assets/5520287/14557565/3a3c925e-02fe-11e6-8164-fe2f80a9f0eb.png)

**Comment by miyconst** [comment]
@binte could you please provide some more information?

- Starcounter logs.
- Send/received patches.

**Comment by binte** [comment]
Seems that the problem was with one of our servers, which was down. And with this new version we were getting a response from SC, which is a new feature and it made us confused. Sorry for bugging you guys! 

Closing the issue!
