### ISSUE TITLE
Suggestion: Improved error message on a failed installation. 

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3512]
Hi! 

When I upgrade SC from `2.1.1367` to `2.1.1793`the installer failed with this message:

![screen shot 2016-04-19 at 08 38 49](https://cloud.githubusercontent.com/assets/112064/14630088/8629604c-060b-11e6-8a31-5f0c1cf32636.png)

In the log I see something familiar. 

```
20160419T064434 Warning sc://tunityrc/personal/networkgateway Starcounter - Gateway XML: MaximumReceiveContentLength parameter exceeds maximum value. Current value is set to 2096936.
20160419T064437 Critical sc://tunityrc/personal/networkgateway Starcounter - Assertion failed (!"Reached maximum number of tries in wait for suspended workers.") at OurSources\\gateway.cpp:2949 (Data 0).
    000007FB7AF711E9 sccoredbg!do_handle_assertion_failed : assert-win.cpp (76)
    000007FB7AF71039 sccoredbg!handle_assertion_failed : sccoredbg.cpp (29)
    000007F7E8648EBA scnetworkgateway!starcounter::network::Gateway::WaitAllWorkersSuspended : gateway.cpp (2949)
    000007F7E86467C2 scnetworkgateway!starcounter::network::RegisterUriHandler : gateway.cpp (1543)
    000007F7E864FCE1 scnetworkgateway!starcounter::network::RegisteredUri::RunHandlers : http_proto.cpp (162)
    000007F7E864F5DA scnetworkgateway!starcounter::network::HttpProto::HttpUriDispatcher : http_proto.cpp (779)
    000007F7E864FB3B scnetworkgateway!starcounter::network::OuterUriProcessData : http_proto.cpp (1060)
    000007F7E863559B scnetworkgateway!starcounter::network::GatewayWorker::RunReceiveHandlers : worker.hpp (538)
    000007F7E8658189 scnetworkgateway!starcounter::network::GatewayWorker::WorkerRoutine : worker.cpp (1788)
    000007F7E863DDA8 scnetworkgateway!starcounter::network::GatewayWorkerRoutine : gateway.cpp (3125)
    000007FB9BC31842 KERNEL32!
    000007FB9C18E379 ntdll!


20160419T064437 Error sc://tunityrc/personal/service Starcounter - ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
20160419T064437 Error sc://tunityrc/personal/service Starcounter - Process exitcode: 1070
```

When I changed the `WorkersNumber` in the `scnetworkgateway.xml` to `1`installation worked fine. Maybe the Installer should be able to finish even if the starcounter service failed to start?

**Comment by dan31** [comment]
CC @alemoi

**Comment by k-rus** [comment]
I've got the same stack trace in different scenario describe in #3513

**Comment by k-rus** [comment]
> I've got the same stack trace in different scenario describe in #3513

No, actually it is not the same stack trace. Sorry for confusion.

**Comment by alemoi** [comment]
I have increased the allowed spinning interval significantly, so the problem should disappear. Regarding:
> Maybe the Installer should be able to finish even if the starcounter service failed to start?
That's an interesting idea. I don't have arguments against it actually. @dan31 what do you think?

**Comment by alemoi** [comment]
Eventually I decided to rewrite the code. Tested it and it seems working well. The new stable is provided. Thank you for the report @ivarbergman ! Please let us know if you still experience any problems with it.
