### ISSUE TITLE
pnext: cannot start database due to network gateway terminated

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3513]
I have local build of pnext from yesterday (Apr 18). I stopped and deleted default database and then I started the following code with `star constraintviolation.cs`, where `constraintviolation.cs`is:

```c#
using Starcounter;
using System;

[Database]
public class Invoice {
	public int InvoiceNo;
}

class Progrma {
	public static void Main() {
		if (Db.SQL("select i from starcounter.metadata.\"index\" i where name = ?", "InvoiceNoIndx").First == null)
			Db.SQL("create unique index InvoiceNoIndx on invoice (invoiceno)");
		Db.Transact(delegate {
			new Invoice {InvoiceNo = 1};
		});
		Db.Transact(delegate {
			new Invoice {InvoiceNo = 1 };
		});
	}
}
```

The application obviously stops with:

>Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entry
point method raised an exception. ScErrConstraintViolationAbort (SCERR8001): A t
transaction was aborted because a constraint was violated.

Then I modified the code to:
```c#
using Starcounter;
using System;

[Database]
public class Invoice {
	public int InvoiceNo;
}

class Progrma {
	public static void Main() {
		if (Db.SQL("select i from starcounter.metadata.\"index\" i where name = ?", "InvoiceNoIndx").First == null)
			Db.SQL("create unique index InvoiceNoIndx on invoice (invoiceno)");
		Db.Transact(delegate {
			new Invoice {InvoiceNo = 1};
		});
		try {
			Db.Transact(delegate {
			new Invoice {InvoiceNo = 1 };
		});
		} catch (Starcounter.ConstraintViolationException e) {
			Console.WriteLine("Cought exception: "+ e.Message);
		}
	}
}
```

This code obviously should stop, since the first uncaught insert already violates the unique constraint. However, I get that the server cannot be started:

```bash
>star constraintviolation.cs
constraintviolation -> default (starting server ..)

ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network
 gateway executable (scnetworkgateway.exe) unexpectedly terminated.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10021.

Type "star -h" to see help
Type "star 10021" to launch the help page for error 10021

Stack trace:
   at Starcounter.Server.ServerServiceProcess.WaitUntilServerIsOnlineOrSignalExi
t[T](Func`2 checkExited, T context) in C:\GitRepositories\Starcounter\Level1\src
\Server\Starcounter.Server\ServerServiceProcess.cs:line 219
   at Starcounter.Server.ServerServiceProcess.WaitUntilServerIsOnline(Process se
rverProcess) in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Ser
ver\ServerServiceProcess.cs:line 176
   at Starcounter.Server.ServerServiceProcess.StartInteractiveOnDemand(Boolean w
ithNoWindow) in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Ser
ver\ServerServiceProcess.cs:line 103
   at Starcounter.CLI.StartServerCLICommand.RunWithinContext() in C:\GitReposito
ries\Starcounter\Level1\src\Server\Starcounter.CLI\StartServerCLICommand.cs:line
 51
   at Starcounter.CLI.StartServerCLICommand.Run() in C:\GitRepositories\Starcoun
ter\Level1\src\Server\Starcounter.CLI\StartServerCLICommand.cs:line 33
   at Starcounter.CLI.CLIClientCommand.ExecuteWithin(CLIClientCommand context) i
n C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.CLI\CLIClientComm
and.cs:line 113
   at Starcounter.CLI.StartApplicationCLICommand.Run() in C:\GitRepositories\Sta
rcounter\Level1\src\Server\Starcounter.CLI\StartApplicationCLICommand.cs:line 12
8
[10:12:19, Starcounter (service)]
Process exitcode: 1070

[10:12:19, Starcounter (service)]
ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network
 gateway executable (scnetworkgateway.exe) unexpectedly terminated.

[10:12:19, Starcounter (networkgateway)]
Assertion failed (!"Reached maximum number of tries in wait for suspended worker
s.") at OurSources\gateway.cpp:2949 (Data 0).
```

Trying to start the database without application leads to the same error:

```bash
>staradmin start db

Starting default

Starting default (starting server)

Starting default (starting server ..)

Starting default (starting server ...)


ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network
 gateway executable (scnetworkgateway.exe) unexpectedly terminated.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10021.

Type "star -h" to see help
Type "star 10021" to launch the help page for error 10021

Stack trace:
   at Starcounter.Server.ServerServiceProcess.WaitUntilServerIsOnlineOrSignalExi
t[T](Func`2 checkExited, T context) in C:\GitRepositories\Starcounter\Level1\src
\Server\Starcounter.Server\ServerServiceProcess.cs:line 219
   at Starcounter.Server.ServerServiceProcess.WaitUntilServerIsOnline(Process se
rverProcess) in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Ser
ver\ServerServiceProcess.cs:line 176
   at Starcounter.Server.ServerServiceProcess.StartInteractiveOnDemand(Boolean w
ithNoWindow) in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Ser
ver\ServerServiceProcess.cs:line 103
   at Starcounter.CLI.StartServerCLICommand.RunWithinContext() in C:\GitReposito
ries\Starcounter\Level1\src\Server\Starcounter.CLI\StartServerCLICommand.cs:line
 51
   at Starcounter.CLI.StartServerCLICommand.Run() in C:\GitRepositories\Starcoun
ter\Level1\src\Server\Starcounter.CLI\StartServerCLICommand.cs:line 33
   at Starcounter.CLI.CLIClientCommand.ExecuteWithin(CLIClientCommand context) i
n C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.CLI\CLIClientComm
and.cs:line 113
   at Starcounter.CLI.StartDatabaseCLICommand.Run() in C:\GitRepositories\Starco
unter\Level1\src\Server\Starcounter.CLI\StartDatabaseCLICommand.cs:line 55
[10:13:08, Starcounter (service)]
Process exitcode: 1070

[10:13:08, Starcounter (service)]
ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network
 gateway executable (scnetworkgateway.exe) unexpectedly terminated.

[10:13:08, Starcounter (networkgateway)]
Assertion failed (!"Reached maximum number of tries in wait for suspended worker
s.") at OurSources\gateway.cpp:2949 (Data 0).
```

In addition to the above errors the log contains the following stack trace:

>    00007FF9825C3A2E sccoredbg!_DumpCallstack : callstack-win.cpp (122)
    00007FF9825C2CAF sccoredbg!do_handle_assertion_failed : assert-win.cpp (68)
    00007FF9825C2AA6 sccoredbg!handle_assertion_failed : sccoredbg.cpp (30)
    00007FF603A45261 scnetworkgateway!starcounter::network::Gateway::WaitAllWorkersSuspended : gateway.cpp (2949)
    00007FF603A6624B scnetworkgateway!starcounter::network::Gateway::EnterGlobalLock : gateway.hpp (2120)
    00007FF603A697E2 scnetworkgateway!starcounter::network::GatewayWorker::WorkerEnterGlobalLock : worker.hpp (373)
    00007FF603A4BDB9 scnetworkgateway!starcounter::network::RegisterUriHandler : gateway.cpp (1543)
    00007FF603A402C2 scnetworkgateway!starcounter::network::HandlersList::RunHandlers : handlers.hpp (280)
    00007FF603A7C9BF scnetworkgateway!starcounter::network::RegisteredUri::RunHandlers : http_proto.cpp (162)
    00007FF603A7D475 scnetworkgateway!starcounter::network::HttpProto::HttpUriDispatcher : http_proto.cpp (779)
    00007FF603A7C570 scnetworkgateway!starcounter::network::OuterUriProcessData : http_proto.cpp (1060)
    00007FF603A402C2 scnetworkgateway!starcounter::network::HandlersList::RunHandlers : handlers.hpp (280)
    00007FF603A40247 scnetworkgateway!starcounter::network::GatewayWorker::RunHandlers : worker.hpp (581)
    00007FF603A40349 scnetworkgateway!starcounter::network::GatewayWorker::RunReceiveHandlers : worker.hpp (538)
    00007FF603A8EF69 scnetworkgateway!starcounter::network::GatewayWorker::FinishReceive : worker.cpp (751)
    00007FF603A8AA13 scnetworkgateway!starcounter::network::GatewayWorker::WorkerRoutine : worker.cpp (1776)
    00007FF603A4D933 scnetworkgateway!starcounter::network::GatewayWorkerRoutine : gateway.cpp (3125)
    00007FF988648102 KERNEL32!
    00007FF98A2FC5B4 ntdll!

**Comment by k-rus** [comment]
cc @alemoi

**Comment by k-rus** [comment]
It is not possible to start or create any database. Manually deleting database files do not help either. I don't really see how can I get back from this situation without re-installing starcounter.

**Comment by chrhol** [comment]
Check the setting `<WorkersNumber>` in scnetworkgateway.xml and change that to `1` if its not already set. Tunity had the same problem (although in develop) and this helped.

If I'm not mistaken I also think @alemoi changed this value to 1 as default.

**Comment by k-rus** [comment]
> Check the setting <WorkersNumber> in scnetworkgateway.xml and change that to 1 if its not already set. Tunity had the same problem (although in develop) and this helped.

The number is set to 2. I will set to 1 next time, since I uninstalled starcounter now.

Since it is a common problem, I label it as high priority bug.

**Comment by alemoi** [comment]
Thank you for reporting. I know what is the problem: its how much time one worker waits for the other to suspend. I will have to significantly increase this value. Typically does not occur on build servers or my machine.

**Comment by k-rus** [comment]
I think it something more in this error. I've never had the problem and suddenly it stopped working after an error.

**Comment by k-rus** [comment]
Furthermore, the fix to use single worker is ridiculous. :and

**Comment by alemoi** [comment]
I have increased the global spinning interval 50 times. The error should disapear. If it appears again, the issue should be reopened.

**Comment by k-rus** [comment]
This is not serious. Increasing time is not a proper fix, it is just workaround.
Furthermore, my comment about workers is ignored.

**Comment by dan31** [comment]
> Furthermore, the fix to use single worker is ridiculous. 👿

It is a devil's deal @k-rus. @alemoi couldn't figure out the root for this problem, and the current workaround is to set workers to 1. (I don't know anyone to whom 2+ gateway workers is critical, really). The fix is to address it by abandoning the existing Gateway and using Kestrel in SC 3.0.

**Comment by dan31** [comment]
The problem with this is that all existing customers will bounce on that after upgrading their (2-workers configured) instances to new Stable 2.2. @alemoi, how we should deal with that?

**Comment by alemoi** [comment]
> Furthermore, the fix to use single worker is ridiculous. :imp:

I can not say anything else but agree with you.

> It is a devil's deal @k-rus. @alemoi couldn't figure out the root for this problem, and the current workaround is to set workers to 1. (I don't know anyone to whom 2+ gateway workers is critical, really). The fix is to address it by abandoning the existing Gateway and using Kestrel in SC 3.0.

No this is unrelated. Its a new code that was introduced last week regarding faster database startup.

> This is not serious. Increasing time is not a proper fix, it is just workaround.

One gateway worker is waiting for another gateway worker to be in a safe state. Should there be no timeout and wait time to be indefinite? I don't think so. The problem is that there were not enough testing since the fix last week, because people started to use only today. The problem didn't appear on my machine neither on any of the build servers.

**Comment by alemoi** [comment]
>  @alemoi couldn't figure out the root for this problem, and the current workaround is to set workers to 1.

The problem in this case is how different machines behave, for some, as one can notice - its not enough wait time, which was discovered only today.

**Comment by dan31** [comment]
> The problem in this case is how different machines behave, for some, as one can notice - its not enough wait time, which was discovered only today.

@alemoi, can you confirm that the lesson "don't make timeouts tiny" is now learned? ;) I will always repeat that timeouts is a proper thing to have, but they should be reasonably long, since they are just circuit breakers in case of exceptional situation.

**Comment by k-rus** [comment]
Thank you for clarifying. So am I correct, that there is only one gateway is needed per server, however the default was 2?

**Comment by k-rus** [comment]
> @alemoi, can you confirm that the lesson "don't make timeouts tiny" is now learned? ;) I will always repeat that timeouts is a proper thing to have, but they should be reasonably long, since they are just circuit breakers in case of exceptional situation.

Another nightly build failed on pnext on timeout issue, see [this](https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2876#_focus=14086). Let me know if separate issue should be created.

**Comment by alemoi** [comment]
> Thank you for clarifying. So am I correct, that there is only one gateway is needed per server, however the default was 2?

Yes, default before was 2 but now its 1. And I don't modify the gateway configuration during installation.

**Comment by alemoi** [comment]
> Let me know if separate issue should be created.

Yes, its a separate issue. That I will have to look at now.

**Comment by k-rus** [comment]
Default value for gateworkers 2 is confusing. Can you explain how many gateworkers should run the same machine and why?
Another issue: since the default is 1 now, do you have a regression test, which uses more than one gateworker?

**Comment by alemoi** [comment]
The value was 2 because we discovered that was enough for most production cases (when gateway saturates the database enough).
> Another issue: since the default is 1 now, do you have a regression test, which uses more than one gateworker?

Good question. No automatic now (it uses the default configuration). I was running manually on build servers and locally, no problems.

I was thinking through and I am changing the spinning now to use some signalling instead.

**Comment by k-rus** [comment]
I keep this issue open, since it is necessary to do at least:

1. Implement regression test using more than 2 gateway workers.
2. Change default number of gateway workers to 2 as it is the most common for production environment.

An optional task:
Improve the failing part as you currently suggest.

If the tasks are moved to another issue, this issue can be closed.

**Comment by alemoi** [comment]
I was going to write that I will:

> Change default number of gateway workers to 2 as it is the most common for production environment.

If there will be an issue with this, I will have to fix it. @dan31

**Comment by alemoi** [comment]
I rewrote the original code and tested it, on several machines with number of workers 8. Could not reproduce the hang. Now default number of workers is back to 2 since I consider the issue fixed. If you experience the issue again please reopen it.

**Comment by k-rus** [comment]
You need to add regression test with explicit number of workers (not default). Any bug leads to test and added regression test. Reopening this issue until regression test is implemented or separate issue is open.

**Comment by alemoi** [comment]
Yes, I will add 2 regression tests: 1 for 1 gateway worker, another for 8 :) And that would be a modified star_loop_test.

**Comment by k-rus** [comment]
> Yes, I will add 2 regression tests: 1 for 1 gateway worker, another for 8 :) And that would be a modified star_loop_test.

Am I correct that the default will be used in other tests?

**Comment by alemoi** [comment]
Yes, that's correct. Now default is back to 2.

**Comment by k-rus** [comment]
Great

**Comment by alemoi** [comment]
Ok, the tests are now added :) 
Both are nightly and test the actual problem previously: `env.run_star_loop_1_gwworker_test`
and `env.run_star_loop_8_gwworkers_test`
All succeed on all machines now. So I consider the original issue to be fixed.
@k-rus thanks for the input!

**Comment by k-rus** [comment]
Thank for the fix and test.
