### ISSUE TITLE
Starcounter components doesn't have appropriate version info 

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3516]
2.2.1811
How to know which starcounter version is installed if administrator doesn't work?

ARP reports unknown version:
![image](https://cloud.githubusercontent.com/assets/2953584/14636144/1ecb1fac-062a-11e6-8336-55c6b0f79eb3.png)

Binary components have meaningless versions: 1.0.0.0, 2.0.0.0 or just empty

cc @alemoi

**Comment by per-samuelsson** [comment]
> How to know which starcounter version is installed if administrator doesn't work?

Tried `star -v` in a CLI?

**Comment by dan31** [comment]
The version data must be provided to the installer. CC @andwah @alemoi.

**Comment by bigwad** [comment]
>Tried star -v in a CLI?

That works. Haven't known about that. Not the most obvious thing, isn't it? :smile:

**Comment by per-samuelsson** [comment]
> Not the most obvious thing, isn't it?

Well, no. :smile:  I just felt is was a good thing to do at some point a few years ago, and added it. I'm sometimes asking users to utilize it when I want their version. That's all there is too it, I guess. I've always wanted to promote Starcounter more as a CLI-centric platform, but that's not what we do. Instead, the browser (web admin) and VS extension is our main interaction points. So I'm probably the only one using those things on a regular basis, and documentation of all CLI features are not very visible either.

**Comment by per-samuelsson** [comment]
And just to be clear: `star -v` is shorthand for `star --version` (and `-version` also work).

**Comment by alemoi** [comment]
Regarding add/remove programs I think I just fixed that. Need to test though.

**Comment by warpech** [comment]
> So I'm probably the only one using those things on a regular basis

You are not :) I use `star --info` few times a day to know the version and ask everyone who needs my help to run it. Didn't know about `star -v`, though.

**Comment by per-samuelsson** [comment]
> You are not :) 

Haha, good to hear. :smile: 

> Didn't know about `star -v`, though.

Just `star` is your guide:

```
C:\Users\Per>star
Usage: star [options] executable [parameters]

Options:
  -h, --help            Shows help about star.exe.
  -hx, --helpextended   Shows extended help about star.exe.
  -v, --version         Prints the version of Starcounter.
  -i, --info            Prints information about the Starcounter installation.
  -p=,--serverport=port Port to the admin server.
  --server=name         Specifies the name of the server. If no port is
                        specified, star.exe use the known port of server.
  --serverhost=host     Specifies the identity of the server host. If no
                        host is specified, 'localhost' is used.
  -d=,--database=name   The database to use. 'Default' is used if not given.
                        Example "star d=foo bar.exe"
  --stop                Stops the given application.
  --norestart           Prevent the application from being restarted if running.
  --name=name           Gives the application the specified name.
  -t, --transact        Runs the entrypoint in the scope of a write transaction
```

We should probably review and polish a little on parameters we support and how we promote them though, but since CLI is not our main focus, I guess it can wait. Might be something we want to do for DNX, where we might need to change a few things anyway.

**Comment by alemoi** [comment]
The original issue is fixed. Thanks @per-samuelsson for additional info!
