### ISSUE TITLE
Microsoft Security Essentials warning (still)

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#352]
I still get the warning every time I create a new Starcounter application project and run it the first time. Am I the only one, and if so, I guess it's some remain on my machine that makes this pop-up?

It's not really a problem for me, but its not something we want in the face of our users.

![image](https://f.cloud.github.com/assets/2902045/511664/61e76b8a-be0a-11e2-8416-84ecddb9f8c9.png)

Anyone that can spread some light on this? Thanks.

**Comment by dan31** [comment]
@alemoi have recently found a principal solution using object files.
