### ISSUE TITLE
Installer fails on Un-Installing SC

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3520]
I had SC version 2.1.1742 on one of my server, I want to Upgrade its SC to Latest Stable Build, But im not able to uninstall SC now. I get the following 2 errors on uninstalling :

![image](https://cloud.githubusercontent.com/assets/4388707/14675127/b9116052-0707-11e6-9664-666569d3b06a.png)

On pressing yes, it starts to uninstall SC. but then i get the following error: 
![image](https://cloud.githubusercontent.com/assets/4388707/14675160/defc1334-0707-11e6-8476-cf5351a2dda2.png)

If i run the installer again, the whole process of uninstalling starts all over again, and the same thing happens again

**Comment by per-samuelsson** [comment]
@atifwaqar 

I was sure to see the same errors as we've worked with from yesterday, in #3486, but this seem to be something different.

@alemoi, any take on it?

**Comment by per-samuelsson** [comment]
Also, @atifwaqar 

1. When you get that first question, do you press Yes or No?
2. Can you open VS and look under `Help | About ...` and then see if the version information says you have VS Update 1 or Update 2?

Thanks.

**Comment by atifwaqar** [comment]
Looks like the issue was VS 2015 related, I launched the VS 2015 setup and repaired it. now everything works fine.

**Comment by alemoi** [comment]
Thanks for reporting! This is very strange. Because it complained about missing file: SetupSettings.xml in your StarcounterBin directory (Program Files). Can you please check if you see this file in directory or is it missing?

**Comment by atifwaqar** [comment]
I have the file C:\Program Files\Starcounter\SetupSettings.xml

**Comment by alemoi** [comment]
Thank you. I wonder if you start the old Starcounter-Setup.exe in `C:\Program Files\Starcounter` as Administrator and choose uninstall there, will it work? Thanks for trying.

**Comment by atifwaqar** [comment]
I havent tried that. but if i see the issue again, i'll surely test it

**Comment by alemoi** [comment]
Ok, so now you mean now the old installation succeeded and you have a new version installed already?

**Comment by atifwaqar** [comment]
Yes, i repaired my VS installation.
then launched the SC installer again, it uninstalled things first and then reinstalled everything. and now i have SC 2.2 installed.
