### ISSUE TITLE
Starcounter HtmlMerger processes urls with parameters in wrong way

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3527]
It's assumed that path to an HTML file won't have any parameters, and links like this

```
/ScLocale/viewmodels/IndexPage.html?l=en
```

are split into three and more parts. Which results in a ` Self.GET(a[1]);` to a wrong URL.

```cs
String[] a = appNamePlusPartialUrl.Split(new char[] { '=' });

if (String.IsNullOrEmpty(a[1]))
    continue;

Response resp = Self.GET(a[1]);
```

https://github.com/Starcounter/Starcounter/blob/21345582673c882eef81f59d77be47f4440b3731/src/Starcounter/Apps/OntologyAndOrdinaryMapping.cs

cc @chrhol, @alemoi

**Comment by chrhol** [comment]
Should be a quite easy fix to split the string from the first occurrence of `=` instead of from all. I will do it.

**Comment by chrhol** [comment]
Maybe wa s a bit too fast with the comment above :)

Take this url for example: 
`/htmlmerger?App1=/ScLocale/viewmodels/IndexPage.html?l=en&x=y&App2=/app2/partial.html`

For `App1` the partial is `/ScLocale/viewmodels/IndexPage.html?l=en&x=y`, but how can we separate `&x=` and `&App2=`?

The first one should be a part of `App1`'s url while the second one is the appname for the second partial url.

Would it be correct to look for not only `=` but `=/` as the start for a new partial url? So if `=/` is found then the token before is the appname for a new partial and not belonging to the current partial url. But maybe a parameter can be a url as well and then this wont work.

The other option is to parse each parameter that we are not sure about and check if we have an app with the same name and if so assume that this is the beginning of the next partial url.

Maybe easier to set a limitation on parameters on partial url's, that parameters with url-values it not allowed.

**Comment by miyconst** [comment]
>Would it be correct to look for not only = but =/ as the start for a new partial url? So if =/ is found then the token before is the appname for a new partial and not belonging to the current partial url. But maybe a parameter can be a url as well and then this wont work.

I think, the correct way would be to encode the partial URLs.

```
App1=/ScLocale/viewmodels/IndexPage.html?l=en&x=y
```

Would look like

```
App1=IndexPage.html%3Fl%3Den%26x%3Dy
```

**Comment by chrhol** [comment]
> I think, the correct way would be to encode the partial URLs.

Ahh yes, if we have this restriction for parameters on partial url's, then splitting the string will be easy. And I guess the htmlmerger function should decode each partial url before doing the `Self.GET`, or is this something that is done automatically for all requests? I have some vague memory of reading some about this in another issue but I can't remember which one.

**Comment by miyconst** [comment]
I doubt it will automatically decode. The parameter value should be decoded by merger and then send a `Self.GET`.

Anyway, this issue might get irrelevant after HtmlMerger rework. So, lets postpone it.

**Comment by chrhol** [comment]
Since we decided yesterday that this part of the htmlmerger will work as before, this needs to be fixed still.

How it should work, as @miyconst pointed out in the comment above (https://github.com/Starcounter/Starcounter/issues/3527#issuecomment-214205151) is that the partial URL:s needs to be encoded. 

I will change the handler in Starcounter (and Launcher) to decode the partial URL:s before calling `Self.GET`

**Comment by chrhol** [comment]
A fix for this together with @tomalec changes is pushed to develop. The partial url:s are encoded when the handler for the htmlmerger is called and decoded before the call to `Self.GET`.

**Comment by miyconst** [comment]
Thank you guys for the fixes. Now it works.
