### ISSUE TITLE
Unable to bind Html property value when app in running inside Launcher

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3528]
I have a Partial with `Html` property bound to `HtmlBind`:

```cs
partial class IndexPage : LanguagePage {
	static IndexPage() {
		DefaultTemplate.Html.Bind = "HtmlBind";
	}

	public string HtmlBind {
		get {
			return "/ScLocale/viewmodels/IndexPage.html?" + this.Language;
		}
	}
}
```

The `LanguagePage` is a `Starcounter.Page` with additional property `Language`. The `Language` value depends on `Session.Data` and database.

When Launcher [wraps the partial and calls](https://github.com/StarcounterPrefabs/Launcher/blob/master/src/Launcher/Api/LauncherHelper.cs#L235) `GetHtmlPartialUrl` the code of the `Language` getter is executed in scope of Launcher app. The `Session.Data` contains Launcher's data, the `Application.Current` is Laucnher, and the database classes defined in my app is not available.

cc @chrhol, @per-samuelsson, @warpech, @alemoi

**Comment by warpech** [comment]
In other words, `GetHtmlPartialUrl` executes the `Html` getter with Launcher's session instead of  LanguagePage's session?

**Comment by chrhol** [comment]
> In other words, GetHtmlPartialUrl executes the Html getter with Launcher's session instead of LanguagePage's session?

I would guess that it's the same session, but the wrong appname is used. Everything around Session.Data, Application.Current and database classes is based on the appname.

I wonder, if it's not better to focus on fixing the htmlmerger first? Since we already know that we *have* to fix it ASAP. This particular code with `GetHtmlPartialUrl` will most likely be changed.

**Comment by chrhol** [comment]
I will assign this issue to me as well, to keep track of the ones that concerns the htmlmerger.

**Comment by per-samuelsson** [comment]
> I wonder, if it's not better to focus on fixing the htmlmerger first?

I was thinking the same thing. Lets redesign the merger (the cause) before trying to fix any symptoms.

**Comment by chrhol** [comment]
This part will no longer be used when #3539 is in place. Will close it when I can confirm it.

**Comment by miyconst** [comment]
Yes, let's close this issue then.
