### ISSUE TITLE
Starcounter AppStore Shows the same app multipletimes

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3530]
As marked in attached image, i can see 11 apps for "Launcher app" only. 
Are all these apps the same? I suspect the difference is in Version's or Builds only. am i right?

![sc store](https://cloud.githubusercontent.com/assets/4388707/14744783/82dfd5b6-08a8-11e6-9b14-1219dca708d7.jpg)

Also if i want to use these apps, is it recommended to just install from AppStore? or should i stick to the traditional way? (by getting the code from github, and then build and execute it)

**Comment by miyconst** [comment]
Yes, you are right. It's different versions of the same application.

**Comment by atifwaqar** [comment]
Thanks
