### ISSUE TITLE
Unhandled access violation

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3531]
I am using SC Version 2.2.1834. as soon i launch my solution i get the following exception. this happened twice in 10 min

![image](https://cloud.githubusercontent.com/assets/4388707/14809731/45b10162-0b8f-11e6-9e59-2276e30f172d.png)

**Comment by atifwaqar** [comment]
If someone needs access to that server, i can provide. you can investigate the issue directly on my server.

**Comment by k-rus** [comment]
cc @alemoi

**Comment by alemoi** [comment]
According to stack trace the exception occurs in some GUI forms with MSHTML in them. So, something is trying to display some sort of dialog maybe?
@atifwaqar do you get this right after doing F5 in Visual Studio?

**Comment by atifwaqar** [comment]
Thats correct @alemoi. 
But give me some time to copy the same version of DB again. 
I think it occurred without using VS once. but im not sure about this, so let me test it again.

**Comment by atifwaqar** [comment]
I have 2 types of details in Unhandled access violation error : 
```
Unhandled access violation (C0000005) detected (Thread 11864).
    00007FFE8390D669 MSHTML!
    00007FFE83A6BBED MSHTML!
    00007FFE9A9B9863 clr!
    00007FFE9A96FABA clr!
    00007FFE9A970027 clr!
    00007FFE9A96FF19 clr!
    00007FFE9A96FDD5 clr!
    00007FFE9A970254 clr!
    00007FFE9AA20086 clr!
    00007FFE9AA1FDFB clr!
    00007FFE9AA203FB clr!
    00007FFE9AA20313 clr!
    00007FFE93510922 System.Windows.Forms.ni!
    00007FFE92E7EF2C System.Windows.Forms.ni!
    00007FFE937EE1C0 System.Windows.Forms.ni!
    00007FFE3B78037C <unknown>!
    000000551B375BF0 <unknown>!
    000000551B13C780 <unknown>!
    000000561B737DB8 <unknown>!
```



```
Unhandled access violation (C0000005) detected (Thread 21968).
    00007FFE8439D669 MSHTML!
    00007FFE9A9B9863 clr!
    00007FFE9A96FABA clr!
    00007FFE9A970027 clr!
    00007FFE9A96FF19 clr!
    00007FFE9A96FDD5 clr!
    00007FFE9A970254 clr!
    00007FFE9AA20086 clr!
    00007FFE9AA1FDFB clr!
    00007FFE9AA203FB clr!
    00007FFE9AA20313 clr!
    00007FFE93510922 System.Windows.Forms.ni!
    00007FFE92E7EF2C System.Windows.Forms.ni!
    00007FFE937EE1C0 System.Windows.Forms.ni!
    00007FFE3B77CAAC <unknown>!
    00007FFE92FC9318 System.Windows.Forms.ni!
    0000007A06681688 <unknown>!
    0000007B09CFD390 <unknown>!

```

**Comment by atifwaqar** [comment]
@alemoi I got this crash now and I havent used VS at all, my VS is closed. I launched the app using run.bat. It is possible that this is caused by some of my incomplete codes, but this exception makes it hard to find the error location.

![image](https://cloud.githubusercontent.com/assets/4388707/14814993/251c54d2-0ba9-11e6-83bf-85a96c1db6e2.png)

**Comment by alemoi** [comment]
Is it failing on startup of the specific app that comes after Launcher, UserAdmin, SignIn and AdFenix?

**Comment by atifwaqar** [comment]
I am launching only these 4 apps, and for a while everything works fine. and i have access to my app dashboards/pages.

This is my Test server, and before this issue appeared, This is what i did:
1. A week ago I installed almost all of the apps from your store, just to test them. 
2. Then today I copied a DB from another server (to test some issues), 
3. Saved current "Personal" folder as backup 
4. Placed the downloaded "personal" folder
5. Launched apps
6. As expected all of my installed apps were gone (as the Db was changed), but this Crash appeared.

**Comment by alemoi** [comment]
There is a suggestion from @bigwad to obtain crash dumps as suggested here: https://github.com/Starcounter/Starcounter/issues/3297#issuecomment-174574035
I guess we should check them.
On Thursday I can have a personal look through remote desktop to your machine.

**Comment by atifwaqar** [comment]
@alemoi Can you please check what am i doing wrong?

I created the Regex entry, The folder is open but i dont have "CrashDumps" folder in it, even after reproducing the crash.
![image](https://cloud.githubusercontent.com/assets/4388707/14844901/1ab7ee68-0c5b-11e6-84a6-9ce68d32f00b.png)

**Comment by bigwad** [comment]
@atifwaqar, there are two problems:
1. Wrong registry path - you have excessive key "Registry". Path should be: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps
2. Wrong value type - should be REG_DWORD instead of REG_SZ

**Comment by atifwaqar** [comment]
@bigwad Thanks for you response. can you please verify if this is ok?

![image](https://cloud.githubusercontent.com/assets/4388707/14845377/13dc275a-0c5e-11e6-934d-481c34bf39af.png)

**Comment by bigwad** [comment]
Looks right. Have you got a dump with this setting?

**Comment by atifwaqar** [comment]
yup, i have the dump now. its 9GB approx

**Comment by atifwaqar** [comment]
Thanks @bigwad

**Comment by bigwad** [comment]
@atifwaqar 
Any chance for me to get it for investigation? 
If it's too large to share, you may try to set DumpType to 1. It should generate significantly smaller dump. It will contain less information but still useful.

**Comment by atifwaqar** [comment]
The dump is shareable easily, do you have access to server "82.99.7.11" that you have provided us?
if yes, i can put the dump file in that server, and then you can copy it easily

**Comment by atifwaqar** [comment]
Or i can provide you direct access to that machine aswell

**Comment by bigwad** [comment]
I don't have an access. Could you give it to me? vadim.senchukov@starcounter.com

**Comment by bigwad** [comment]
vadim.senchukov@gmail.com on hangouts

**Comment by bigwad** [comment]
Summary of our progress on it so far. Just to let team know.
I've got a dump from @atifwaqar and guessed the problem is in AdFenix app, using Windows.Forms.WebBrowser class in non thread-safe way. Waiting for feedback.

**Comment by dan31** [comment]
@bigwad thanks for investigation. @atifwaqar can you explain exactly how you utilise ```WebBrowser```, inside which facilities: .net threads, Starcounter ScheduleTask (sync/async), .net async/await? Can you provide a code snippet to here also.

**Comment by atifwaqar** [comment]
@dan31 & @bigwad sorry for the late response guys, I was stuck with some other crash fixes.

I had a deprecated function, which was using WebBrowser. I dont use that function anymore, but somehow that function was being called on my test server. The error is gone as soon as I removed this deprecated code. But I am pasting the code here, if you guys need to reproduce the error : 
```
WebsiteToImage websiteToImage = new WebsiteToImage(PageUrl, @"C:\Page2Image\Image.jpg", 350, 525);
websiteToImage.Generate();
```

and following is the class where i had the `Generate` function :
```
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Net;
using System.Threading;


namespace AdFenix.Functions
{
    public class WebsiteToImage
    {
        private Bitmap m_Bitmap;
        private string m_Url;
        private string m_FileName = string.Empty;
        private int m_width;
        private int m_height;

        public WebsiteToImage(string url, string fileName, int width, int height)
        {
            // With file 
            m_Url = url;
            m_FileName = fileName;
            m_height = height;
            m_width = width;
        }
        public void Generate()
        {
            try
            {
                // Thread 
                var m_thread = new Thread(_Generate);
                m_thread.SetApartmentState(ApartmentState.STA);
                m_thread.Start();
                m_thread.Join();
            }
            catch (Exception ex)
            { }
        }


        public void _Generate()
        {
            try
            {
                System.Windows.Forms.WebBrowser browser = new System.Windows.Forms.WebBrowser { ScrollBarsEnabled = false };
                browser.ScriptErrorsSuppressed = true;
                browser.Navigate(m_Url);
                while (browser.ReadyState != System.Windows.Forms.WebBrowserReadyState.Complete)
                {
                    System.Windows.Forms.Application.DoEvents();

                }
                byte[] DownloadedImageBytes = new byte[1];
                int LoopCount = 0;
                do
                {
                    System.Windows.Forms.Application.DoEvents();
                    Thread.Sleep(1000);
                    if (LoopCount > 0 && DownloadedImageBytes.Length < 5000)
                    {
                        browser.Navigate(m_Url);
                        while (browser.ReadyState != System.Windows.Forms.WebBrowserReadyState.Complete)
                        {
                            System.Windows.Forms.Application.DoEvents();
                        }
                    }

                    browser.ClientSize = new Size(m_width, m_height);
                    browser.ScrollBarsEnabled = false;
                    m_Bitmap = new Bitmap(m_width, m_height);
                    browser.BringToFront();
                    browser.DrawToBitmap(m_Bitmap, browser.Bounds);

                    // Save as file? 
                    if (m_FileName.Length > 0)
                    {
                        // Save 
                        m_Bitmap.SaveJPG100(m_FileName);
                    }
                    string FileNameFromServer = m_FileName.Replace(@"C:\adfenix-backend\src\Client\reports\Images\", "http://"+GlobalDictionary.LocalHostAddress+"/Client/reports/Images/");

                    var DownloadedImage = GetImageFromUrl(FileNameFromServer, 0);
                    System.Drawing.ImageConverter converter = new System.Drawing.ImageConverter();
                    DownloadedImageBytes = (byte[])converter.ConvertTo(DownloadedImage, typeof(byte[]));
                    LoopCount++;
                    if (LoopCount > 30)
                    {
                        break;
                    }
                } while ((DownloadedImageBytes.Length < 140000 && m_FileName.Contains("UnCropped")) || (DownloadedImageBytes.Length < 100000 && !m_FileName.Contains("UnCropped")));
                //}
                browser.Dispose();
            }
            catch (Exception ex)
            { }
        }
        public static System.Drawing.Image GetImageFromUrl(string url, int RetryNumber)
        {
            HttpWebRequest httpWebRequest = (HttpWebRequest)HttpWebRequest.Create(url);

            try
            {
                using (HttpWebResponse httpWebReponse = (HttpWebResponse)httpWebRequest.GetResponse())
                {
                    using (Stream stream = httpWebReponse.GetResponseStream())
                    {
                        return System.Drawing.Image.FromStream(stream);
                    }
                }
            }
            catch (Exception ex)
            {
                if (RetryNumber < 20)
                {
                    RetryNumber++;
                    return GetImageFromUrl(url, RetryNumber);
                }
                else
                {
                    return null;
                }
            }
        }
    }

    public static class BitmapExtensions
    {
        public static void SaveJPG100(this Bitmap bmp, string filename)
        {
            var encoderParameters = new EncoderParameters(1);
            encoderParameters.Param[0] = new EncoderParameter(System.Drawing.Imaging.Encoder.Quality, 100L);
            bmp.Save(filename, GetEncoder(ImageFormat.Jpeg), encoderParameters);  // save the image to the specified file
        }

        public static ImageCodecInfo GetEncoder(ImageFormat format)
        {
            var codecs = ImageCodecInfo.GetImageDecoders();

            foreach (var codec in codecs)
            {
                if (codec.FormatID == format.Guid)
                {
                    return codec;
                }
            }
            return null;
        }
    }
}
```

**Comment by dan31** [comment]
Archived.
