### ISSUE TITLE
Gathering changes for a viewmodel does not always checkpoint siblings correctly.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3533]
When generating changes for a viewmodel, siblings are sometimes not checkpointed, which leads to that they are still considered dirty/modified. This might in turn lead to incorrect behaviour on later patch-requests.

This bug was introduced after #3465 was implemented.

**Comment by chrhol** [comment]
Fix pushed to develop and pnext.

**Comment by miyconst** [comment]
Now we need a successful pnex build :(

**Comment by k-rus** [comment]
> Now we need a successful panel build :(

Issue is Starcounter/AdminTrack#32
Vote for it as nothing happens there.
