### ISSUE TITLE
Scdb 1.5.0.5 create images tool

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3537]
Just noticed a switch on the tool that says that images can be created from a backup file. What does this mean? I can't create from scdx files. Guessing @per-samuelsson is the author?

> >scdbc.exe -dbs 256 -tls 256 -ip "..\Images" -lp "..\TransLog" -scb "..\Images\RetailMaster.scdx" -coll Tur
> boText_en-GB_2 -repl RetailMaster  
> Starcounter permanent storage creation utility (version 0.0.0).  
> Copyright (C) Starcounter Ltd 2007-2011. All rights reserved.  
> Error: SC_E_VERIFY_BACKUP_MAGIC_FAILED (0x40095): Verification of backup file against magic number failed. The file could not be identified as a backup file.  
> Error: SC_E_CANT_VERIFY_BACKUP_FILE (0x40091): Backup file could not be verified.

**Comment by per-samuelsson** [comment]
> Guessing @per-samuelsson is the author?

Hmm, I'm not sure I am actually, and I can't remember I should have ever implemented this (although I *do* have quite a bad memory). @eriohl?

**Comment by eriohl** [comment]
It is for creating an image file (or set of image files) from a backup image. But you can not create a backup image because the API for that is disabled. So it is a less then useful feature.

**Comment by careri** [comment]
What was the intention of a backup image? Some idea prior to scdx?
Den 27 apr. 2016 7:05 em skrev "eriohl" <notifications@github.com>:

**Comment by eriohl** [comment]
More an alternative. Creates a backup from the image file instead of doing a dump in a different format. Faster and less disruptive to create and faster to load but with some other drawbacks as well.

**Comment by careri** [comment]
Ok, that does sound quite interesting. What would be drawbacks?
Guess it has something to do with migrating data between different schemas?

**Comment by eriohl** [comment]
Well, as mentioned, this feature is not available. Nor is this backup scheme available in later versions. So it is nothing you will actually be able to use.

But yes: The main drawbacks is that you it doesn't handle schema updates or database structure updates. Another drawback is that if the image for some reason gets corrupted the backup will bad as well.

**Comment by careri** [comment]
Yepp, I got that it was disabled. Just curios. Thanks

**Comment by dan31** [comment]
Archived.
