### ISSUE TITLE
Clean up serverside code concerning htmlmerger.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3541]
When the parts for the clientside is in place for #3539 the following steps should be done: 
- Hack in serializer that generates the `Html` property should be removed.
- Clean up interface `IResource`. The method `GetHtmlPartialUrl()` should be removed. (For this step Launcher probably needs to be updated as well since it uses it in one place)

**Comment by chrhol** [comment]
- The hack in the serializer is removed.
- `IResource.GetHtmlPartialUrl` has been marked as obsolete and all usage of it have been changed (both internally in Starcounter and in Launcher). Will keep it for some time to not break older versions of Launcher.

Will keep this issue open until the method from `IResource` interface is properly removed.

**Comment by chrhol** [comment]
The last piece of this issue is in place now. I have removed `GetHtmlPartialUrl` from the interface, and the places that implemented it.

**Comment by per-samuelsson** [comment]
> The last piece of this issue is in place now. I have removed `GetHtmlPartialUrl` from the interface, and the places that implemented it.

Great! Well done! 🎉 That mean we could close #3407 too, right?
