### ISSUE TITLE
Cannot create Starcounter application in VS 2015 Update 2

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3543]
I have installation of Starcounter from local source built yesterday. Starcounter was installed after I updated VS2015 with Update 2. I create a Starcounter application. After I pushed button to create I got the following message:

![cannotopenscproject](https://cloud.githubusercontent.com/assets/1726044/14909691/c5304688-0de6-11e6-8758-460781685726.png)

After pressing OK in the error window, VS shows me the start page, not the created solution. In the file explorer I can see that the solution file is created in expected location (*c:\GitRepositories\Starcounter\Level1\src\Tests\Offsetkey3502_test\*), but no project files are created. The folder of the project is empty. Opening solution file in VS brings empty solution with no projects.

I uninstalled Starcounter, build it locally from latest source code obtained now, installed Starcounter and got the same problem that I cannot create Starcounter project.

I obtained source code for pnext. I am not sure if it is valid for develop too or not.

cc @per-samuelsson

**Comment by k-rus** [comment]
I downloaded latest nightly for both develop and pnext and both worked successfully. So the problem is only related to development environment and can be local to my machine.

**Comment by k-rus** [comment]
I cannot solve this issue on my MV. Any suggestions? Cleaning of Level1 does not help. Cleaning temp files does not help.

Installing Starcounter from downloadable works, but from local always this issue. I guess there is some kind of cache.
@per-samuelsson  May be you can suggestion something where to look?

**Comment by per-samuelsson** [comment]
> @per-samuelsson May be you can suggestion something where to look?

Can [this](https://github.com/Starcounter/Starcounter/issues/3486#issuecomment-216764160) be of any help?

**Comment by per-samuelsson** [comment]
> Can this be of any help?

What I mean is, try uninstalling the extension only like that. And the just reinstall the extension ("Add components") using the installer, to see if that helps.

**Comment by k-rus** [comment]
> Can this be of any help?
> What I mean is, try uninstalling the extension only like that. And the just reinstall the extension ("Add components") using the installer, to see if that helps.

No, it does not help. It seems to me that something is broken in the building sequence on my machine.

**Comment by k-rus** [comment]
Now I also get another error when I try to create Starcounter Application:


![scnotloadcorrectly](https://cloud.githubusercontent.com/assets/1726044/15144645/1003ca18-16b1-11e6-9ed8-440e8a7670b0.png)

**Comment by k-rus** [comment]
In the activity log file I found following warnings:

```xml
<entry>
    <record>421</record>
    <time>2016/05/10 11:11:19.076</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>One or more templates do not match any installed project packages.</description>
  </entry>
  <entry>
    <record>422</record>
    <time>2016/05/10 11:11:19.076</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Found templates with duplicate template ids at &quot;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplatesCache\CSharp\Windows Root\Store Apps\Windows Phone\1033\Discover\Discover.vstemplate&quot; and &quot;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplatesCache\VisualBasic\Windows Root\Store Apps\Windows Phone\1033\Discover\Discover.vstemplate&quot;</description>
  </entry>
  <entry>
    <record>423</record>
    <time>2016/05/10 11:11:19.372</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Found templates with duplicate template ids at &quot;C:\Users\ruslan\AppData\Local\Microsoft\VisualStudio\14.0\VTC\{7B89C9D9-403F-4D47-A7A4-B0C088BAD732}\CSharp\Windows Root\Windows UAP\0E9DCF39\s.vstemplate&quot; and &quot;C:\Users\ruslan\AppData\Local\Microsoft\VisualStudio\14.0\VTC\{7B89C9D9-403F-4D47-A7A4-B0C088BAD732}\JavaScript\Windows Root\Windows UAP\3EA750AD\s.vstemplate&quot;</description>
  </entry>
  <entry>
    <record>424</record>
    <time>2016/05/10 11:11:19.372</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Found templates with duplicate template ids at &quot;C:\Users\ruslan\AppData\Local\Microsoft\VisualStudio\14.0\VTC\{7B89C9D9-403F-4D47-A7A4-B0C088BAD732}\JavaScript\Windows Root\Windows UAP\3EA750AD\s.vstemplate&quot; and &quot;C:\Users\ruslan\AppData\Local\Microsoft\VisualStudio\14.0\VTC\{7B89C9D9-403F-4D47-A7A4-B0C088BAD732}\VisualBasic\Windows Root\Windows UAP\81404822\s.vstemplate&quot;</description>
  </entry>
```

**Comment by k-rus** [comment]
I think this entry gives a hint:

```xml
 <entry>
    <record>454</record>
    <time>2016/05/10 11:11:24.300</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [Starcounter.VisualStudio.VsPackage, Starcounter.VisualStudio, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf][Could not load file or assembly &apos;file:///C:\Program Files\Starcounter\Starcounter.VisualStudio.dll&apos; or one of its dependencies. The system cannot find the file specified.]:{   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)}</description>
    <guid>{1EFE6CB9-CD9D-4DA7-8D30-6DDD65C82BFB}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'file:///C:\Program Files\Starcounter\Starcounter.VisualStudio.dll' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
```

I will investigate this.

**Comment by k-rus** [comment]
Yes, it was the problem. The project `Starcounter.VisualStudio` of Level1 was disabled.

The issue is resolved

**Comment by per-samuelsson** [comment]
> Yes, it was the problem. The project `Starcounter.VisualStudio` of Level1 was disabled.

Wow. Well done you found that!

Do you know why it was so? Because this will reoccur then if others set this project not to build, and it's not easy from the experience to tell what is wrong. Even though it's "just" for local builds, it's still time-consuming.

The problem really is that templates and the extension itself are separated. So it's perfectly fine to have the project templates (e.g. "Starcounter Application") installed, but not the extension. But if you do, when you try to *instantiate* the project template, you'll get this (or similar) error.

I'm not sure of what we could possibly do about it, since it's kind of by design from Microsoft. It's somewhat comparable to that you can perfectly fine compile an application with a dependency, and ship that application without the dependency. At runtime, you'll see the loader fail on it, because the dependency is not there.

**Comment by k-rus** [comment]
I cannot tell why it was disabled. May be I disabled as workaround for some issue (thus I hate such work arounds like disable, set an environment variable, similar) and forgot to enable. Or something else happened without my intervention that the project became disable.

Yes, it is very frustrating to lose so much time.

The only thing, which comes to my mind, is to check that all white listed files are in place during installation.
