### ISSUE TITLE
pnext: LogStreamer suddenly stopped to stream logs with "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3547]
Found it while trying to reproduce #3404.

After successfully processing more than 3M transactions, I consistently get this error:

```
ws://localhost:8081/logstreamer/service: "An existing connection was forcibly closed by the remote host": Reconnect at 4/29/2016 2:34:52 PM
```

App restart doesn't help. No other errors in the log.

cc @linkdata

**Comment by linkdata** [comment]
cc @alemoi

**Comment by linkdata** [comment]
You restarted the LogStreamer app on the upstream server?

**Comment by bigwad** [comment]
yes

**Comment by linkdata** [comment]
Limitation of SC websocket implementation. Looking into workarounds.

**Comment by alemoi** [comment]
Yes, this is the same problem as with maximum upload size in HTTP. For now I will write log warning entries that socket is closed because of too big upload. Its quite a big thing to fix, if we want to enable any size streaming to code host.

**Comment by alemoi** [comment]
I have added logging of warning of maximum upload size (which is defined in `scnetworkgateway.xml` in `MaximumReceiveContentLength`) for all protocols.

**Comment by linkdata** [comment]
I will add splitting transactions into multiple smaller parts as a feature request in LogStreamer.
