### ISSUE TITLE
ScErrSqlExportSchemaFailed (SCERR7001) on starting apps

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#3551]
I am trying to start our apps on a production server and I get the following exception: 

System.Exception: ScErrSqlExportSchemaFailed (SCERR7001): SQL module was unable
to write a schema file to the current temp directory. Failed to load SQL schema
info from file: C:/Users/Administrator/Documents/Starcounter/Personal/Temp/default/default-20160221T131142365/sqlschemas/schema1605011219127381802107085.pl

This is happening for all apps, and no syntax changes to the database schema has been made. 

How can I fix this?

**Comment by dan31** [comment]
CC @k-rus

**Comment by k-rus** [comment]
Thank you for reporting the problem.
Can you try to move the `*.pl` files into some place that Starcounter doesn't see them and start your apps again? Do not forget to stop Starcounter by `staradmin kill all` before moving them.

Let us know if it helps, but I doubt.

What version of Starcounter are you using? Have you installed new version on top of existing database?

**Comment by alemoi** [comment]
I have checked and there are several possible reasons for the failure:
```
 if (answer == null)
            {
                return new SqlExecutableException("Incorrect answer.");
            }
            if (answer.IsError)
            {
                return new SqlExecutableException("SQL process error: " + answer.Error);
            }
            if (answer.queryFailed())
            {
                return new SqlExecutableException("SQL process query failure.");
            }
```

Current error message is not providing this extra info. So I just added this information which will be available in tonight's nightly after 2.2.1.1961

**Comment by Ripipip** [comment]
Today I am unable to reproduce it. If It occurs again I will try and update to latest starcounter version though.

**Comment by k-rus** [comment]
> Today I am unable to reproduce it.

I am wonder how have you fixed it? As I understood you cannot to get through the problem. Can you describe us what you've done to get through?

**Comment by alemoi** [comment]
Any new cases of this problem reproduction, @Ripipip ? Or it was gone and not appeared anymore?
