### ISSUE TITLE
pnext: LogStreamer opens transaction log even if no upstream configured

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3552]
For example in one-way master-slave replication, slave opens transaction log. If it fails to open log for any reason (say due to log retention), replication will stop and no way to restart it.

cc @linkdata

**Comment by linkdata** [comment]
From the README:
```
Each database is allowed one URI to designate it's "parent" database, but may have any number of "children". This parent-child relationship does not regulate data flow; it only specifies that the child database is responsible for maintaining the WebSocket connection to it's parent. **Once connected, data flow is bidirectional (but not necessarily symmetric).**
```

So yes, both connected machines will open their logs. Having no upstream configured has no bearing on it. Why is this an issue?

**Comment by bigwad** [comment]
>Why is this an issue?

Because there is no logical reason to do so in master-slave replication and it makes master-slave impossible to functioning in long term (after slave performs first log retention)

**Comment by linkdata** [comment]
Ok, I see. Yeah, that makes sense. I will add "don't open log if we will never send" as a feature request on the LogStreamer.

**Comment by linkdata** [comment]
Just a final note here. I [previously suggested](https://github.com/Starcounter/CompanyTrack/issues/177#issuecomment-188744564) that unless the logs take up too much space, there is no reason to remove them:

> Just have an option to limit the size the logs are allowed to occupy. So you could say "keep at least X days worth of logs, but you may keep more as long as you stay within Y MB of space used".

We still would have added this "don't-open-log" feature though, as I can think of use cases where it would be required.
