### ISSUE TITLE
Installer does not set the provided path to Personal folder.

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3560]
Hi! I just installed the `Starcounter-DevelopNightlyBuilds-2.2.1.1974-Setup.exe` and choosed to make setting changes during the installation process. I changed the path to the Data folder. 

But when I look in `C:\Program Files\Starcounter\Configuration\Personal.xml` my given path is replace with the default `C:\...`

/Ivar

**Comment by mattiasmak** [comment]
Mine was: <server-dir>\\Mac\Home\Documents\Starcounter\Personal</server-dir>
Changed it manually to: <server-dir>C:\Starcounter\Personal</server-dir>

**Comment by ivarbergman** [comment]
Yes, manually changing the path in `C:\Program Files\Starcounter\Configuration\Personal.xml` solved the problem.

**Comment by alemoi** [comment]
Thank you for reporting!
Was it a fresh installation or Starcounter was previously installed on the machine?

>  I changed the path to the Data folder.

To what in particular the path was changed? Thank you.

**Comment by ivarbergman** [comment]
Hi, It was our stage server that had an existing sc installation. I used this `F:\Starcounter` as path during the installation. `F:` is an mounted data disk on Azure. We have had this path for a long time, without any problems.

But, maybe there is some problems related to network mounted disks. 

Usually we get a warning that we should make sure that the path is writable. But I didn't get that message this time.

**Comment by alemoi** [comment]
@ivarbergman I will try to recreate the situation you have. Let's see what comes out!

**Comment by andwah** [comment]
I think i found the cause of this and im working on a fix. See #3570
