### ISSUE TITLE
The operation failed because the current thread wasn't attached

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3565]
Why am I not able to use Db.Transact in this code snippets and how can I fix it?

```csharp
 private async Task<bool> Update() {
            HtmlDocument doc = await Task.Run(() => new HtmlWeb().Load("http://sweoffshore.se/news"));
            var articles = doc.DocumentNode.SelectNodes("//article");

            Db.Transact(() => {
```

```csharp
        public void Run() {
            BackgroundWorker bw = new BackgroundWorker();
            bw.DoWork += Bw_DoWork;
            bw.RunWorkerCompleted += Bw_RunWorkerCompleted;
 
            bw.RunWorkerAsync();
        }
 
        private void Bw_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e) {
            BackgroundWorker worker = sender as BackgroundWorker;
 
            System.Threading.Thread.Sleep(5000);   
            worker.RunWorkerAsync();
        }
 
       private void Bw_DoWork(object sender, DoWorkEventArgs e) {
            BackgroundWorker worker = sender as BackgroundWorker;
 
            Db.Transact(() => {
 
            });

```

> The operation failed because the current thread wasn't attached to the scheduler. ( ScErrThreadNotAttached (SCERR1004))

**Comment by dan31** [comment]
Guys, @jwillmer finally approached the topic and we need to help him figure out what one can do and cannot do today with Starcounter 2.x when it comes to .NET threads, and how to properly utilise ```ScheduleTask```. @alemoi could you assist there?

**Comment by alemoi** [comment]
@jwillmer thank you for the question! The problem you are facing is generic and related to execution of Starcounter code on arbitrary .NET threads (code that is not called in Main, handlers or handles). In your example you have a .NET background worker. In this case "Starcounter code" is your transaction execution `Db.Transact`. For the moment, when executing on arbitrary .NET threads, for all Starcounter code (transactions, SQL, Self calls, etc) one should use `Scheduling.ScheduleTask` that takes a delegate with Starcounter functions in it and wait for completion flag. 

We have a dedicated article on this matter: http://starcounter.io/guides/transactions/running-background-jobs/

Here is what probably should be done in your example:
```c#
       private void Bw_DoWork(object sender, DoWorkEventArgs e) {
            BackgroundWorker worker = sender as BackgroundWorker;

           Scheduling.ScheduleTask(() => {
               Db.Transact(() => {
                    ...
               }); 
           }, true);
```

Please read the article and let us know how it goes!

**Comment by jwillmer** [comment]
works perfectly, thank you :)
