### ISSUE TITLE
Image file writer unable to acquire the SE_MANAGE_VOLUME_NAME privilege.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3569]
I keep getting a warning, It is not effecting my Apps, so nothing to worry about. 
I tried to figure out the reason of this warning, but no clue yet. 
The only thing I noticed is that is somehow coupled with "Gateway XML" warning. 

![image](https://cloud.githubusercontent.com/assets/4388707/15067617/062dd994-1372-11e6-9886-7bfe96fa2359.png)

**Comment by dan31** [comment]
@atifwaqar thanks for the question! I looked into our tracker and there is quite some feedback on this matter: https://github.com/search?p=1&q=org%3AStarcounter+SE_MANAGE_VOLUME_NAME+&type=Issues. However, I couldn't find the exact way to address the warning. What would be a recommendation? Run Starcounter with Admin privilege (which should also, in general, improve performance)? cc @eriohl @per-samuelsson (and thanks in advance for any feedback on the issue).

**Comment by per-samuelsson** [comment]
Yes, this is an old and known issue. It's "just" a warning that file IO could be faster if the user launching that process had that given privilege. I think the way to solve it is to do some Windows-configuration on the user account.

Here's a relevant search that will point to such issues:

https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=SE_MANAGE_VOLUME_NAME

Make sure to restart the server for it to take effect, and I think that should solve it.

**Comment by eriohl** [comment]
You need to run with elevated priviledges (as administrator) or in session 0 (as a det service) for the process to be able to acquire this priviledge. Thus you will aways get this warning when  running user mode.

**Comment by atifwaqar** [comment]
@per-samuelsson from your search, I followed [this link](https://msdn.microsoft.com/en-us/library/ms175935.aspx), and performed the mentioned steps. Lets see if I get the warning again.

**Comment by atifwaqar** [comment]
This info worked for me, i dont have the warning in my logs anymore. Thanks :+1:

**Comment by dan31** [comment]
@atifwaqar that is a great link, I will add it to our http://starcounter.io/guides/tools/run-starcounter-in-production/.
