### ISSUE TITLE
pnext: Fix issues Linux kernel build

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3595]
Make sure the Linux build compiles and runs properly and that the automatic tests are properly implemented.

**Comment by alexanderstc** [comment]
Do we have Linux version of scllvm?

**Comment by eriohl** [comment]
> Do we have Linux version of scllvm?

Not that I know of. Has never worked to the kernel åt least. Kernel supports falling back to creating binaries however so this is not a showstopper.

**Comment by alexanderstc** [comment]
I'll have to disable llvm-dependent part of QP and related tests until scllvm is avalable on Linux,
please let me know when it becomes a priority.

**Comment by eriohl** [comment]
Any project not related to the kernel that doesn't build will be removed (from Linux build) when this is addressed (currently this project is in the backlog). This is only about fixing the kernel build (changing the title accordingly).

**Comment by dan31** [comment]
@alexanderstc @eriohl I hear you. This will be a new interesting task for linux for @alemoi. A bit too early (as @eriohl points out this isn't a showstopper) though shall be addressed mid-term.

**Comment by alemoi** [comment]
Today I looked at the state of Linux build agent and its working actually (project `PNext-Daily-Linux `), but the builds are failing. Here I reference corresponding issue: https://github.com/Starcounter/CompanyTrack/issues/200
Which is kind of a duplicate of this one, so I will close that one.

**Comment by alemoi** [comment]
> Do we have Linux version of scllvm?

I remember that I produced a binary for you actually :smiley: that was placed in Level0 somewhere, as a part of Cmake. But I need to recover whole building process of scllvm in Linux.

**Comment by alexanderstc** [comment]
> I remember that I produced a binary for you actually

Thanks! I forgot the details by now.

**Comment by alemoi** [comment]
Just to remind the Linux build still fails with Windows related things and some other errors (https://github.com/Starcounter/CompanyTrack/issues/200#issuecomment-219100042):
```
[13:55:45][Step 1/1] [  2%] Linking CXX static library ../../../../make/x64/libevent_helper.a
[13:55:45][Step 1/1] In file included from /home/teamcity/buildAgent/work/sc-pnext-daily-linux-1380/level0/src/include/jupitertp/client/signal_port.hpp:71:0,
[13:55:45][Step 1/1]                  from /home/teamcity/buildAgent/work/sc-pnext-daily-linux-1380/level0/src/tests/jupitertp_test_client/main.cpp:3:
[13:55:45][Step 1/1] /home/teamcity/buildAgent/work/sc-pnext-daily-linux-1380/level0/src/include/jupitertp/client/impl/signal_port.hpp:3:31: fatal error: signal_port-lnx.hpp: No such file or directory
[13:55:45][Step 1/1]  #include "signal_port-lnx.hpp"
[13:55:45][Step 1/1]                                ^
[13:55:45][Step 1/1] compilation terminated.
[13:55:45][Step 1/1] /home/teamcity/buildAgent/work/sc-pnext-daily-linux-1380/level0/src/shared/sccoredbg2/sccoredbg2.cpp:7:21: fatal error: Windows.h: No such file or directory
[13:55:45][Step 1/1]  #include <Windows.h>
[13:55:45][Step 1/1]                      ^
[13:55:45][Step 1/1] compilation terminated.
```

**Comment by eriohl** [comment]
No one has been working on this so not so odd that it still isn't working.

**Comment by eriohl** [comment]
But on this topic: We have some C# in the source tree again I noticed yesterday (for code generation). So we to set up so this builds properly with Mono or .NET Core on Linux.

**Comment by alemoi** [comment]
What code is it related to? URI matcher generator or something else?

**Comment by dan31** [comment]
@alemoi my guess it is TurboText tool that generates TT source code from collation files. URI matcher isn't needed for that Linux build in work. As I recall, this TT tool is straightforward to build by mono ```xbuild```. I've tried that on TT tool back in 2014, but I lost this code and it is just 7 lines in a script. @alemoi you are the closest one to fix it straight in a build, correct me if not.

**Comment by alemoi** [comment]
Yes, it should be easily fixable using a build script. I just need to know what exactly we want to build as a highest priority first. I will check what exists there regarding C# code.

**Comment by dan31** [comment]
@alemoi these are all the things beyond the kernel but which kernel needs in order to run. For instance, this TT tool is needed in a chain to actually having the kernel run. I will not name you more, this is common sense, you simply navigate though build reports and bring the other needed parts to surface.

**Comment by eriohl** [comment]
I'll make it build locally first. Just a note that we need to install tools on buildserver.

**Comment by eriohl** [comment]
Done. Kernel without persistence is again running on Linux.
