### ISSUE TITLE
Setup: support updating existing SC installation

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3596]
1. Install SC in version A with custom settings
1. Open Visual Studio
1. Run setup for version B

Actual:

1. Setup removes completely version A (along with settings)
1. Setup requires you to close Visual Studio (because it needs to remove and then re-add SC plugin)

Expected:

1. Setup Acknowledges existence of previous version ("it seems you have previous version of SC installed. Do you want to upgrade it to latest version?")
1. Setup uses settings from previous installation
1. Setup doesn't force anyone to close their Visual Studio

Rationale:
this is developers' daily routine, this should be as easy as possible

**Comment by warpech** [comment]
@joozek78's specific problem was with the database files installation path, which he wants to have outside of current user's `Documents` folder.

I can completely understand that. I keep my database files in `c:\db` and have to change that path manually every time I install Starcounter.

**Comment by miyconst** [comment]
+1 for keeping the database files path among installations.

>Setup requires you to close Visual Studio (because it needs to remove and then re-add SC plugin)

I am afraid this is required by Visual Studio. What we can do, is to check whether latest plugin installed and if so, then don't reinstall it.

@andwah what do you think?

**Comment by andwah** [comment]
I also agree, the settings should be kept between upgrades.

**Comment by joozek78** [comment]
@andwah What's the ETA for this? It bugs everyone every day

**Comment by andwah** [comment]
ETA:  before end of 2016-05-31

**Comment by andwah** [comment]
Development done now testing..

I also made the "upgrade" more streamline, no need to confirm uninstallation and close window when it's done. (there is still one question left to the user to answer and it's about confirming ending running starcounter processes) 

to be continued...

**Comment by andwah** [comment]
I could not fully test my development due to the build server failed to build (unrelated to my changes).

Hopefully this will be resolved tomorrow so i can continue the testing..

**Comment by joozek78** [comment]
I just installed new nightly and it asked me if I want to upgrade. Unfortunately this was the only difference from the old version (I still had to click through a lot of things)

**Comment by andwah** [comment]
@joozek78 Yes. When a new version is installed the old one is uninstalled by executing the "OLD" setup executable, and i your case the old setup executable does not yet have the new fixes in it. So next time you do an upgrade you hopefully will see different behaviour.

**Comment by joozek78** [comment]
Can't wait to see it! :D

**Comment by joozek78** [comment]
I just ran it and it went like a breeze! Closing
