### ISSUE TITLE
Json action, serverside change url?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3599]
I'm using the KitchenSink partial class to divide my application into pages. 
I can think of multiple ways of solving this scenario (it' just an example, not the real scenario).
1. Search for product
2. The search yielded no result, so we show a "create new" button. 
3. The user clicks "create new", the json server sides creates a new product with a unique id (4433). The url to this new product would be something like:
 http://localhost/product/4433
4. How do I tell the client to go to this url?

The thing is that is websocket communication, so there is no response where I can set a redirect.
I could put some custom field in my main model with the redirect info.

But as I said, I can come up with multiple solutions. Do you have a recommendation?

**Comment by per-samuelsson** [comment]
cc @warpech @miyconst

**Comment by careri** [comment]
There is an example in KitchenSink. Seems like pu

**Comment by miyconst** [comment]
@careri thank you for the question. As you already found it out, you have to use `<link is="puppet-redirect" />` to trigger client side redirect.

Please, close the issue if it works for you.
