### ISSUE TITLE
Dynamically generate Json

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3601]
Since you already have a msbuild task that generates a Json class consisting of the partial based on the .json-file and the optional .json.cs file I assume there is a tool for building json-classes.

I would like to build my own json-class to be used with the hot-table. The base class should have a SelectedIndex-property to bind to, this reflects the selected row in the UI.
It should also be possible to add the column-properties.

So the actual question is, do you expose a json template builder?

(I guess I could just take a generated .cs file from the obj-folder, but it would be nice if there was a simpler way)

**Comment by chrhol** [comment]
Do I understand you correctly that you want to create TypedJson objects (including the template) runtime, or do you want to use them where the buildtask is not available?

The core concept that we have tried to aim for is that everything that the buildtask does, should be possible to do in your own code. And if you look at a generated file, you can see that it actually builds a template from scratch. Of course, the generated file contains a lot of extra stuff to point the debugger away from the g.cs file so it's a bit bloated.

Now, these parts are not well documented (:flushed: suprise) and the API probably contains parts that should be enhanced.

> So the actual question is, do you expose a json template builder?

Yes, kind of. There are two ways to create a template, you can either call `Starcounter.Templates.Template.CreateFromJson(jsonStr)` (weird namespace though, should change that...) that will parse and build a template from the specified input. Or you build it similary as the generated code does.

There is short description of how TypedJSON looks like, and what templates exists on our internal wiki. I will try to find it and give it to you as a starting point.

**Comment by chrhol** [comment]
I moved the document to starcounter.io: http://starcounter.io/guides/json/typed-json-internals/

**Comment by careri** [comment]
Great I'll have a look

**Comment by chrhol** [comment]
I think this issue is answered and will close it.
