### ISSUE TITLE
DB_CLOSE_BEGIN & DB_CLOSE_END

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3605]
I have 2 entries in my logs SC Version 2.2.1834.

`20160507T012521 Debug sc://owneror-pvpjthq/personal/default Starcounter - DB_CLOSE_BEGIN(True)/OC:29188734/Objects:0/Transactions:0/TScope:0.`

`20160507T012521 Debug sc://owneror-pvpjthq/personal/default Starcounter - DB_CLOSE_END(True)/OC:29188734/Objects:0/Transactions:0/TScope:0.`

I dont think they are harming anything, but i'm posting this just to understand the log.

**Comment by per-samuelsson** [comment]
@atifwaqar 

These two are kind of a legacy. They've been around for a very long time, and basically just spit out some internal information gathered when the database is closing down.

As you can see from their severity, they are classified as `Debug` messages, so they are normally not displayed, and more for internal use than intended for our users.

**Comment by per-samuelsson** [comment]
With that answer, I hope you don't mind me closing this issue. Let me know if we can help you further in any way.

**Comment by atifwaqar** [comment]
@per-samuelsson This makes sense. Thank you.
