### ISSUE TITLE
Inconsistent behaviour with mapped partial uri:s and accessing inputhandler.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3606]
Moved from other issue to be continued here, @aloscha writes:

In serveral apps we use Session.Current.Data, but now that code return null value.
I do small investigation and create demo to show the problem https://github.com/warpech/HelloWorld/tree/Session_example (that branch from small hello world app).

Generally I register in main application (HelloWorld) PersonJson and InjectionJson. In second app (HelloWorldPart) I register just handler to get from previous app InjectionJson. So it's working that (please run first HelloWorld and HelloWorldPart):
1. Go to HelloWorld
2. Page Master set current page to PersonJson
3. Meanwhile other app is in ontology maping to Illustration, which called with PersonJson
4. HelloWorldPart called helloworldpart, which is ontology maping to Somebody
5. InjectionJson is registered to Somebody so content is send to HelloWorldPart and then send back to HelloWorld

(Yeah it looks a bit confused)

So after click to Announce buttom, we will have exception in InjectionJson because Session.Current.Data is null.
![image](https://cloud.githubusercontent.com/assets/5141943/15109577/4e653510-15dc-11e6-8150-e25f4830ad63.png)

Please notice that in older version of SC that demo works, I mean untill 2.2.1936 is released (so in 2.2.1901 (29 April 2016 04:56:23) it works, but start from 2.2.1936 (30 April2016 04:57:11) don't). That demo also works (Session.Current.Data contains MasterPage) in daily version  2.2.1834 (19 Apr 2016) 

So my question is how to use Session in proper way since 2.2.1936 is released (or it's some bug)?

**Comment by chrhol** [comment]
Something is messed up here. Not sure exactly what though yet.

1. The response in `HelloWorldPart` app from calling `Self.GET("/helloworldpart/partials/helloworldpart/" + objectId);` contains the resource from `HelloWorld` app. This should NOT happen, resources should not be accessible from other apps.
2. The handler in `HelloWorldPart` app, `Handle.GET("/helloworldpart/partials/helloworldpart/{?}"` is never called.
3. Clicking the `Announce` button comes to the inputhandler with `HelloWorldPart` app as active when it should be `HelloWorld` app (since `InjectionJson` was created there).

Number 3 is the reason `Session.Current.Data` is empty. I will investigate more.

**Comment by warpech** [comment]
Thank you @chrhol for taking care of this. We need this to integrate Chatter + Images in a completely non-hardcoded way.

**Comment by aloscha** [comment]
1. Why NOT happen, sometimes in first app I crate container just for another one. I would like to see that conainer only if second app is creates
2. It's just create because if don't ontology mapping throw new exception

Please notice that HelloWorld didn't know about HelloWorldPart and viceversa, but if second occurs then first will add something more

**Comment by chrhol** [comment]
The reason why it worked before was probably because of this bug: #3548. Then the inputhandler would have been called with the app that created the first instance of that particular Json. 

After I fixed that one, this issue got exposed.

**Comment by aloscha** [comment]
So @chrhol how to do it in proper way?

**Comment by chrhol** [comment]
> So @chrhol how to do it in proper way?

I think the bug is in Starcounter code. Not sure where yet. So until I find and fix it, I'm not sure what the proper way is, or if anything should be changed in this code.

**Comment by chrhol** [comment]
I will probably have to postpone investigating this for some time. I got two other quite serious crashes to investigate first.

**Comment by chrhol** [comment]
I've spent some time this morning figuring out what the problems are. And I found several things that behaves a bit strange. Not sure in all cases what the expected behaviour should be.

**1. Custom converters in mapping**
When null is returned from a custom converter for the mapping, the handler is just skipped, and will never be called.

So having this mapping (where the last converter returns `null`):
`UriMapping.OntologyMap("/helloworldpart/partials/helloworldpart/@w", "simplified.ring1.Somebody", objectId => objectId, objectId => null);`

Means that the handler will never get called when doing `Self.GET("/helloworldpart/partials/helloworldpart/" + objectId)`.

Instead the response returned from that call will be the response from `HelloWorld` app. Which is clearly a bug and breaks the requirement of apps being separated from each other.

**2. Returning `null` from a handler**
If the first point is changed so that the mapper does not return `null`, and the handler instead returns `null`, the received response from the `Self.GET` is the response from the `HelloWorld` app, so the result is the same as the point above.

**3. Multiple responses from the same app**
If both points above are changed so none of them returns `null`, the proper response is received from every `Self.GET`, however the `InjectionPage.json` from `HelloWorld` app is never sent to the client due to the current limitation that only one partial per app is allowed.

**Conclusion**
These bugs together with a different bug (#3548) made it so that this sample actually worked at one time (if we ignore the fact that the app isolation was broken in several places) :smile:

Points 1 and 2 are clearly bugged, but I'm not sure what the correct solution is. Point 3 we are aware of.

I will add separate issues for 1 and 2. For point 3 there are several issues reported already, I will try to find them and link here.

**Comment by aloscha** [comment]
I do that intentionally `UriMapping.OntologyMap("/helloworldpart/partials/helloworldpart/@w", "simplified.ring1.Somebody", objectId => objectId, objectId => null);`

I need to insert code only from others application (not from that), which is mapped to somebody (it's just an example), so is there any other solutoon which do that? (second app don't know about first app).

But let's back to Session.
By SessionId I could attach to current session?. I think above example it's complicated. Another one is in upload example. In each upload method calls from page I can't see Session.Data.Current (it returns me null)

**Comment by chrhol** [comment]
> I do that intentionally UriMapping.OntologyMap("/helloworldpart/partials/helloworldpart/@w", "simplified.ring1.Somebody", objectId => objectId, objectId => null);

> I need to insert code only from others application (not from that), which is mapped to somebody (it's just an example), so is there any other solutoon which do that? (second app don't know about first app).

I don't really understand what you are trying to do? It seems to me that the second app, `HelloWorldPart`, is not doing anything and has kind of a soft dependency on `HelloWorld` app, which is not good and make it hard to suggest alternative solutions. In this case I would probably just create and add `InjectionJson` directly to the viewmodel in `HelloWorld`. 

An app should not be implemented with the mappings as a part of the internal logic. The mappings should be added outside of the app, preferably by someone other than the app-developer, to allow blending. However our current design kind of obscures this (i.e. adding the mappings directly in the application).

It is a good test though of our API, where you found several flaws in our design and implementation.

> But let's back to Session.
By SessionId I could attach to current session and get data from there?
Something like that Session.ScheduleTask(SessionId, (s, id) => {}) And will it works in out situation?

No, this won't work since the original response was handled by the wrong app (and by that is tied to `HelloWorldPart` instead of `HelloWorld`). So scheduling a task would lead to the same problem.

`Session.Current.Data` from `InjectionJson` should not be `null` if the other bugs were not there.

**Comment by aloscha** [comment]
>I don't really understand what you are trying to do? It seems to me that the second app, HelloWorldPart, is not doing anything and has kind of a soft dependency on HelloWorld app, which is not good and make it hard to suggest alternative solutions.

It's just an example so second part do nothing.

But please imagine situation that main application is same chatter. And I could send some message, which could be everything with settings (that settings neds to be handled from main application). And I register new application called video, I would like to put it into box (randered from main app with some other actions) and video don't know about anything more than showing video.
So video call to main app "Give me container where I can loaded", after that video will rander into that container and send back container with video into main application. Main app just add that container bottom.

**Comment by chrhol** [comment]
The issues for point 1 and 2 are solved, which means that you will only see the responses made from the app that made the `Self.GET` call. So with your code, you will get `null` back if you return `null` from either the handler itself or the custom converter (which make sense).

I thought I had another pattern/workaround that should work, and I can't understand why it's not. The resulting viewmodel that is sent to the client looks ok, but all parts are not rendered and it looks like the second call to the htmlmerger (which should retrieve `injectionjson.html`) is never executed.

This is what I thought should work:
Since we have the limitation of only allowing one response per app, as a workaround I would probably add a new TypedJson, which contains one property that you assign the second `Self.GET` to in `HelloWorldPart` app for the response from `/helloworldpart/partials/helloworldpartannouncment/{?}` and also remove the custom converters from the mappings:

**JsonWithSubPage.json**
```javascript
{
    "SubPage": {}
}
```

**Program.cs** 
```csharp
Handle.GET("/helloworldpart/partials/helloworldpartannouncment/{?}", (string objectId) =>
{
    var page = new JsonWithSubPage();
    page.SubPage = Self.GET("/helloworldpart/partials/helloworldpart/" + objectId);
    return page;
});

Handle.GET("/helloworldpart/partials/helloworldpart/{?}", (string objectId) => {
    return new Page(); // Just a placeholder to allow merging of partials.
});

UriMapping.OntologyMap("/helloworldpart/partials/helloworldpartannouncment/@w", "simplified.ring1.Illustration");
UriMapping.OntologyMap("/helloworldpart/partials/helloworldpart/@w", "simplified.ring1.Somebody");
```

**Comment by aloscha** [comment]
Thanks @chrhol, I've pushed new version with session on current branch (https://github.com/warpech/HelloWorld/tree/Session_example) and your solutions works with `Session.Current.Data`

**Comment by chrhol** [comment]
Great! I will close this issue then.
