### ISSUE TITLE
DM terminates with assertion failure

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3607]
Intentionally not labeling this a bug, since it might very well be something f-ed up with the environment.

I'm having a ~6 GB database, downloaded from a live server. It was downloaded as part of a full server repository zip (i.e. `Documents\Starcounter\Personal` tree zipped).

I'm not sure what exact version created the database, but I'm running it with a local build of **develop**, latest bits fetched like yesterday.

When I try to start the database, here's what I get:

```
Assertion failed (imageFooters[1].Volatile == 0) at ..\..\src\scdata\load.c:229 (Data 0).
    00007FFED4DF11E9 sccoredbg!do_handle_assertion_failed : assert-win.cpp (76)
    00007FFED4DF1039 sccoredbg!handle_assertion_failed : sccoredbg.cpp (29)
    00007FF68D7A6C3C scdata!_load_storage : load.c (229)
    00007FF68D7A8B10 scdata!_proccmd_connect : proccmd.c (102)
    00007FF68D7AA46A scdata!WinMain : winmain.cpp (126)
    00007FF68D7AB2C6 scdata!__scrt_common_main_seh : exe_common.inl (255)
    00007FFED9888102 KERNEL32!
    00007FFED9EFC5B4 ntdll!
```

This in turn materialize as a higher-level error in the code host (which is correct):

```
Starcounter.DbException: ScErrMemoryManagerIsDead (SCERR4101): The memory manager has terminated unexpectedly.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4101.
   at StarcounterInternal.Bootstrap.Control.ConnectDatabase(UInt32 schedulerCount, UInt64 hmenv, UInt64 hlogs) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Bootstrap\Control.cs:line 582
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Bootstrap\Control.cs:line 230
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
ErrorCode=4101
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4101

```

I do have a vague memory that we had some trouble years ago with some particular database instance, downloaded like this, and it turned out to be an issue with not all bytes being really copied. We discussed to add some checksum (MD5 or similar), but I'm not sure it was ever done.

**Comment by per-samuelsson** [comment]
@eriohl, do you have any idea here? Does it make sense to believe that this could be caused by a failing download, where not all bytes have been properly fetched? If so, I'll initiate a new one (and a new copy).

Any help appreciated.

**Comment by eriohl** [comment]
This is because both images are marked as volatile (so none can be loaded).

I remember you could get to this state is database initialization was aborted. Can't remember exactly how but it had to do with there having to be a checkpoint after initialization. Can also not remember if it was properly fixed but I think it was.

Otherwise I haven't seen anything like this.

**Comment by eriohl** [comment]
You got the error the first time you started locally?

**Comment by per-samuelsson** [comment]
> I remember you could get to this state is database initialization was aborted. Can't remember exactly how but it had to do with there having to be a checkpoint after initialization. Can also not remember if it was properly fixed but I think it was.

OK, thanks. I'll see if we can somehow redo this scheme then. Thanks for the input.

**Comment by per-samuelsson** [comment]
> You got the error the first time you started locally?

To be honest, I'm not sure, since I had some struggling getting the environment right. I know for sure that I never have successfully started this particular instance, but I *attempted* to start it maybe 1 or 2 times before, but got errors b/c of failing setup. I can check the log and try to remember. Hang on.

**Comment by per-samuelsson** [comment]
No, it was not the first attempt. It was the second attempt, after I first got an error saying `ScErrCantAccessImageFile`, which in turn was the result of me not running as an administrator, and files were under a directory where such rights where needed.

When I elevated the prompt, I got pass that and instead was faced with the error in the OP.

**Comment by per-samuelsson** [comment]
Regarding `ScErrCantAccessImageFile`, there's something weird going on there as well, and I'm trying to find out what. I can constantly reproduce it. The weird thing is that I get the error in the CLI, but there is absolutely no trace of any error in the logs, not even when including `Debug` entries, so I'm trying to understand the flow there.

**Comment by eriohl** [comment]
```ScErrCantAccessImageFile``` occurs when the user isn't allowed to access the image file (ERROR_ACCESS_DENIED).

So then it was the first time you actually could read the file I gather? You didn't copy the image files while the database was loaded at the source or something like that?

**Comment by per-samuelsson** [comment]
> ```ScErrCantAccessImageFile``` occurs when the user isn't allowed to access the image file (ERROR_ACCESS_DENIED).

Yes, that much I know, and hence I knew I could get passed it by elevating. But there experience is a bit weird. Nevermind though, it's totally a management thing, I'm just looking it up to see if we should make an issue on it to improve that experience.

> So then it was the first time you actually could read the file I gather? 

Yes.

> You didn't copy the image files while the database was loaded at the source or something like that?

I don't think so, no. Quite sure actually. But just to be 100%, let me just restart from the ZIP again. I'll unpack it to the correct location, make sure I have correct privileges and start over from that. Will get back after that.

**Comment by per-samuelsson** [comment]
> I don't think so, no. Quite sure actually. But just to be 100%, let me just restart from the ZIP again. I'll unpack it to the correct location, make sure I have correct privileges and start over from that.

Did that now. To no prevail unfortunately. So my conclusion is that both image files are then marked volatile once they arrive in that zip.

It's a 33GB database unpacked if of any interest, 2 *.sci2-files * 10 GB, 2 *.sci-files * 6,5 GB.

**Comment by eriohl** [comment]
Well. Logically: If the database could be restarted on the server is was copied from it has to be broken in transfer. So it the database now up and running again there on the server?

**Comment by per-samuelsson** [comment]
> So is the database now up and running again there?

I'm not sure. But the took it down to send us because it was one of the slow starting ones, not because they had other problems. So I guess so.

I'll ask them to repackage/resend it. Thanks for the feedback.

**Comment by per-samuelsson** [comment]
We've decided to close this one because we think there is a strong possibility it is caused by a database that was copied when running, and a conflicting checkpoint is the cause. For the discussion that lead us to this, see this https://github.com/Starcounter/Starcounter/issues/3494#issuecomment-218671939 and those responding to that.
