### ISSUE TITLE
pnext: Drop sccoredbg.

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3609]
Obsolete code cleanup.

* Unhandled exception handler is no longer used in kernel.

* Use standard asserts for debug build. Release build assertion failure should same as an unhandled exception.

**Comment by eriohl** [comment]
sccoredbg is still used by some components outside the kernel. Current plan is to leave that as is and have separate definitions for these things for the kernel. But I can remove these as well if that is preferred? @alemoi @dan31

**Comment by eriohl** [comment]
I will also replace all the process termination in the kernel with exceptions for consistency. Host is required to terminate process on unhandled exception regardless. This way it might be possible to get more information about the reasons for the failure. Critical errors will still be logged as before.

**Comment by eriohl** [comment]
Discovered a case where an exception thrown from an APC (block detection) is translated to an out of memory exception by .NET framework (seems to be the case regardless of what exception is thrown) hiding the underlying exception. Only possible way to get around this I found is to raise a fail fast exception.

```
20160614T152235 Critical sc://desktop-7da680j/personal/sqltest Starcounter.Host - System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.\r\n   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)\r\n   at Starcounter.Binding.TypeLoader.Load() in C:\\Git\\level1\\src\\Starcounter\\Binding\\TypeLoader.cs:line 63\r\n   at Starcounter.Binding.BindingBuilder.CreateTypeBinding() in C:\\Git\\level1\\src\\Starcounter\\Binding\\BindingBuilder.cs:line 92\r\n   at Starcounter.Binding.Bindings.LockedBuildTypeBindingFromTypeDef(TypeDef typeDef, UInt16[] currentAndBaseTableIds) in C:\\Git\\level1\\src\\Starcounter\\Binding\\Bindings.cs:line 421\r\n   at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(TypeDef typeDef) in C:\\Git\\level1\\src\\Starcounter\\Binding\\Bindings.cs:line 385\r\n   at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(String name) in C:\\Git\\level1\\src\\Starcounter\\Binding\\Bindings.cs:line 369\r\n   at Starcounter.Binding.Bindings.GetTypeBinding(String name) in C:\\Git\\level1\\src\\Starcounter\\Binding\\Bindings.cs:line 330\r\n   at Starcounter.Hosting.HostManager.Starcounter.Hosting.IBackingHost.InitializeTypeSpecification(Type typeSpecType) in C:\\Git\\level1\\src\\Starcounter\\Hosting\\HostManager.cs:line 63\r\n   at Starcounter.Hosting.HostManager.InitTypeSpecification(Type typeSpecification) in C:\\Git\\level1\\src\\Starcounter\\Hosting\\HostManager.cs:line 46\r\nHResult=-2147024882\r\n
```

Note that this is a host specific problem however an beyond the scope of this work. Thought it worth documenting however.

**Comment by alemoi** [comment]
Sorry for confusion but will _SC_ASSERT and _SC_BEGIN / END function tge same way as before regarding logging the exceptions? As I understood the definitions are for now just moved to kernel but have the same behavior.

**Comment by eriohl** [comment]
> Sorry for confusion but will _SC_ASSERT and _SC_BEGIN / END function tge same way as before regarding logging the exceptions? As I understood the definitions are for now just moved to kernel but have the same behavior.

_SC_BEGIN / END is not used in the kernel. _SC_ASSERT will not work the same in the kernel as before (instead it will throw an exception in release and work as regular assert in debug). Kernel will no longer use sccoredbg.

Question was it I should make the same changes outside the kernel or if I should leave the stuff outside the kernel as it. If I leave it as is it will work just as before. If I do not it will work like in the kernel.

**Comment by alemoi** [comment]
Ok, now i understand. Practically I wonder how the unhandled exception in native code would be handled in managed code? Right now sc_assert in release terminates the process and creates a server log entry with stack trace etc. For me, regarding gateway and codehost I just need stack traces and termination, and if its possible using the new exceptions way - I would prefer same new way to be used everywhere, and not maintaining the old way.

**Comment by eriohl** [comment]
It should not be handled preferably. Instead it should let the process crash so a crash dump can be produced.

In managed code this is a bit of a problem of course since anyone can intercept the exception. This can be handled by turning the exception into a fail fast exception for example.

**Comment by eriohl** [comment]
Done. Left level1 as is.

**Comment by dan31** [comment]
@alemoi so how it looks now after the change?
Also note that in 3.x architecture apps are independent (in default setup, unless a setup is done deliberately so that several apps are hosted in a single process for performance reasons), and only small amount of things actually happen directly inside of the app process. Meaning that there is pretty much nothing to intercept from other parts, they are other processes. The processes will crash and the watchdog (which we would be introducing into 3.x) will restore the dead processes, including apps processes needed for the running apps suite.
Albeit 3.x is great and so on, currently we have to deal with changes in 2.x, which is a production-use version of Starcounter.

**Comment by alemoi** [comment]
> @alemoi so how it looks now after the change?

Need to test regarding some asserts failures/access violations in gateway and codehost. If processes are terminated correctly and stack traces exist - then its all we need I suppose.

@eriohl I now remember one thing regarding:

> Use standard asserts for debug build. Release build assertion failure should same as an unhandled exception.

Is it possible to switch to use releasing assertions handling for debug builds when running on build servers? This is probably needed for running debug builds: https://github.com/Starcounter/Starcounter/issues/1076
This one is however for managed assertions, but still can be the same problem for native if they behave standard.

**Comment by eriohl** [comment]
> @eriohl I now remember one thing regarding:

> > Use standard asserts for debug build. Release build assertion failure should same as an unhandled exception.

> Is it possible to switch to use releasing assertions handling for debug builds when running on build servers? This is probably needed for running debug builds: #1076
This one is however for managed assertions, but still can be the same problem for native if they behave standard.

We use regular CRT asserts in the kernel a lot as well. So you are better of changing the global definition of the CRT assert I think.
