### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3610]
I'm not sure if this error is Starcounter related, or AdFenix related, so asking here just to confirm it. 

![html error](https://cloud.githubusercontent.com/assets/4388707/15211209/3e8d36c8-183a-11e6-8f9c-c4b6a16fd203.jpg)

**Comment by mtornwall** [comment]
`ERR_BLOCKED_BY_CLIENT` could be caused by an ad blocker. Based on your screenshot you're running ABP, so that might be it. If that's indeed the case I suspect it's triggered by the occurrence of "AdFenix" in the URI.

**Comment by dan31** [comment]
@atifwaqar this must be most likely related to your AVG issue that you previously posted (as @mtornwall guesses) coupled with internal logic of AVG. I would recommend you to try some other protection software. :)

**Comment by atifwaqar** [comment]
@dan31 my AVG is always off in office hours. so it was not an issue

@mtornwall Thanks for the information. ABP was the reason of this error. I uninstalled that extension and now I can access my page easily.

Sorry for the trouble guys :P

**Comment by dan31** [comment]
@atifwaqar you mean AdBlocker? :)

**Comment by atifwaqar** [comment]
Yes ABP is an AdBlocker extension. I dont know why I added it in the first place :P
