### ISSUE TITLE
Public directories not enabled when project launched by hitting F5 in Visual Studio

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3612]
SC version 2.2.1834
If I use batch files this is how my chrome console looks like. (Everything is fine till this point) : 
![when works fine](https://cloud.githubusercontent.com/assets/4388707/15213190/f47d120e-1845-11e6-99b8-43cca7246e27.jpg)

But when I run my project from Visual Studio by pressing F5 this is what I see in chrome console : 
![does not work](https://cloud.githubusercontent.com/assets/4388707/15213195/f9674208-1845-11e6-93e2-4ebea4e78feb.jpg)

and this is how my Project settings look like : 
![my project setting](https://cloud.githubusercontent.com/assets/4388707/15213231/2f9942cc-1846-11e6-8e81-c21109760682.jpg)

The folder `client/partials/*` are placed in `C:\adfenix-backend\src\` . 
Any suggestion on how to fix this? or where am I going wrong?

**Comment by per-samuelsson** [comment]
cc @miyconst @warpech @andwah

**Comment by warpech** [comment]
As [this page](http://starcounter.io/guides/network/static-file-server/) puts it:

> you can specify resource directories in the “Command line arguments” under the Project | Properties | Debug tab.

In your case, that would be `--resourcedir=client/partials`

Btw. you can preview the currently used static file directories in Starcounter Administrator (`http://localhost:8181/#/server/network`)

I guess this will solve the issue. If not, please reopen

**Comment by warpech** [comment]
(Or, just change working directory in VS to `client/partials`)

**Comment by atifwaqar** [comment]
@warpech My directory is fine, it should not be `--resourcedir=client/partials` , it should be `--resourcedir=c:/adfenix-backend/src`.

This is what i see when i run my apps using the batch files, and everything works as expected : 
![working public dir](https://cloud.githubusercontent.com/assets/4388707/15240154/e3b79d0c-18e7-11e6-9380-feba85210c54.jpg)

This is what is see when I run by hitting F5 in Visual Studio, and things do not work as expected : 
![notworking public dir](https://cloud.githubusercontent.com/assets/4388707/15240155/e3b96fba-18e7-11e6-89f6-f3f959749419.jpg)

The reason I created this issue is that previously in older version of SC things were working fine, like if i configure a working directory in my VS (as shown in 3rd image if my 1st comment), and run the project by hitting F5, VS was adding my working directory in SC `Public Web Folders`, But now its not behaving the same.

**Comment by atifwaqar** [comment]
> you can specify resource directories in the “Command line arguments” under the Project | Properties | Debug tab.. In your case, that would be --resourcedir=client/partials

@warpech Thank alot. Your suggested method worked, I just had to add `--resourcedir=C:/adfenix-backend/src/` as command line arguments, previously I had this directory set in `working directory`. :+1:

**Comment by warpech** [comment]
I am happy that you managed to fix the problem. Any suggestion what we should improve in static files root directory discovery?

**Comment by atifwaqar** [comment]
I think the way you deal with Public Directories in your Launcher project, or any other project, you make a `wwwroot` and that `wwwroot` becomes the public directory for the project, thats the perfect way to deal with public directories. 

So if SC searches/detects a `wwwroot` directory in OR under the directory where we have the project sln file, that directory should automatically become the public directory. 

But this is just a suggestion. Things works perfectly fine for us now.
