### ISSUE TITLE
http VS https with SC

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3618]
I have following handler which works fine : 
http://www.hiddenurl.net:8080/ChatBot/https

I have an SSL certificate installed on this server and the certificate works fine:
https://www.hiddenurl.net/

But i cant access the following SC handler : 
https://www.hiddenurl.net:8080/ChatBot/https

Any Ideas how can I make this work?

**Comment by dan31** [comment]
Hi @atifwaqar! You need to use an HTTPS proxy. Presumably a separate machine (SSL is very expensive operation) running Linux + nginx or HAProxy. This is pretty straightforward. @mtornwall might give you more info on that when he can.

**Comment by mtornwall** [comment]
@atifwaqar Which type of web server is serving https://hiddenurl.net?

**Comment by mtornwall** [comment]
I'm guessing your setup is:

1. Generic web server (Apache, nginx, etc) listening on port 443.
2. Starcounter listening on port 8080.

Starcounter doesn't speak HTTPS, so you'll want to configure the generic web server as a reverse proxy. I can provide instructions for nginx, but for others I can't help.

**Comment by atifwaqar** [comment]
Thanks @mtornwall .
My network guy fixed it using IIS.

**Comment by atifwaqar** [comment]
@mtornwall the fix we have is not working 100%. Like the simple Handlers that return HTML, they work fine. but when I want to use Launcher pages, it doesnt work.
Like for example [this](https://botchattechnology.com/adfenix) works fine, but [this one with launcher page](https://botchattechnology.com/adfenix/master) does not work fine.

It would be great if you can provide some instructions on how to have SC handlers on HTTPS / 443

**Comment by dan31** [comment]
@alemoi your input on this? Why this is not meant to work in a configuration @atifwaqar describes?

**Comment by mtornwall** [comment]
@atifwaqar The error you are experiencing with the launcher page is:

> WebSocket connection to 'wss://botchattechnology.com/__default/A4AA8FC5E32A9D0300000040' failed: Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value

This is very strange indeed. Looking at the request and response headers of the WebSocket handshake it looks ok, though I haven't verified the `Sec-WebSocket-Accept` value that the browser is complaining about.

My best guess is that the WebSocket upgrade is being trapped by IIS rather than forwarded to Starcounter.

See here for a possible hint: http://www.iis.net/learn/get-started/whats-new-in-iis-8/iis-80-websocket-protocol-support. Specifically, it says:

> If you are using the WebSocket support in socket.io on node.js in your site, you will need to disable the default IIS WebSockets module by adding the below snippet to your web.config or applicationHost.config. If this is not done, the IIS WebSockets module will attempt to handle the WebSocket communication rather than letting this task fall through to node.js (and hence your application). This will result in unexpected errors when you attempt to access your site.

This is likely the root cause of your problem.

**Comment by alemoi** [comment]
@mtornwall thanks for the notes! I think IIS proxy does interfere somehow with network packets, maybe even modifies them (like adds extra headers and such). And WebSocket protocol is quite strict in that way. So, @atifwaqar please follow the advice from @mtornwall and let us know.

**Comment by atifwaqar** [comment]
@mtornwall It worked, i just had to install websocket in IIS, and i did not needed to modify the config file. simple installing the websocket in iis fixed the issue.

Thanks a lot guys :)
