### ISSUE TITLE
Request for input: stricter class declaration in Typed JSON?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3625]
### Background
We are [currently busy](https://github.com/Starcounter/Starcounter/issues/3439) doing some internal changes in how we parse Typed JSON code behind. While doing that, we are looking over the format with the overall aim to make it **more intuitive**.

One thing that currently is very forgiving in this area is how classes can be defined in the code-behind file. Basically, everything is allowed, just as in any standard C# file. Our strategy is to parse the file and look for classes that explicitly say they *map* to the JSON tree, and if they don't, well, we just don't bother.

That's sometimes good. And sometimes bad.

One bad thing about it is that it's simple to make errors that will make apps work in an unintentional way. For example, having this model:

**Foo.json**
```json
{
  "Bar": {
    "Name": "Value"
  }
}
```

with this code-behind

**Foo.json.cs**
```cs
public class Foo { /*...*/ }
public class Bar { /*...*/ }
```

will make the `Foo` class map to the root object in the JSON, while `Bar` is just a plain old C# class (while one would think it would be mapped).

### Changes
One thing in the new parser we've done to make it stricter is to raise an error in this case: any class defined in the code-behind file **must map** to the JSON tree.

### Considerations
Another thing we are *considering*, is to restrict *where* classes can be defined. 

Currently, you can map the "Bar" JSON object hive either with a class *side by side* to `Foo`, or as a nested class. In either case, you have to decorate it with a custom attribute:

**Side by side**
```cs
public class Foo { /*...*/ }
[Foo_json.Bar] public class Bar { /*...*/ }
```

**Nested class**
```cs
public class Foo { 
  /*...*/
  [Foo_json.Bar] public class Bar { /*...*/ }
}
```

In a yet stricter model, we could go for an alternative where it's legal to define them **only side by side**, or **only as nested classes**. The advantage with the later is that we could then go for path-based mapping, allowing classes to map without a custom attribute.

### Consideration 1: Side by side only
Mapping is **not allowed** in inner classes: we don't even consider them. If you define an inner class, it's not our business, and it has no correspondence to the JSON tree.

Drawback: defining inner classes could confuse on the surface, looking like they are mapped, while they in fact are not. This could be restricted by us not allowing inner classes in JSON code behind at all.

### Consideration 2: Nested only
To map code-behind classes to the JSON tree, the code model must have a corresponding structure to the JSON tree, naming included. Hence, having a JSON tree such as this:

**Foo.json**
```json
{
  "Bar": {
    "Name": "Value",
    "Fubar": {
      "Color": "Yellow"
    }
  }
}
```

it would only be possible to define a code-behind class for `Fubar` doing this:

```cs
public class Foo {
  public class Bar {
    public class Fubar {
      // ...
    }
  }
}
```

Pros: intuitive, and doesn't require any custom attributes.
Cons: Forced to define (possibly empty) classes to make a code-behind for a deep JSON node, and less flexible.

### Consideration 3: Side by side OR nested
The choice is yours, and mixing the two is allowed too.

Any input is highly appreciated!

**Comment by joozek78** [comment]
I think that prohibiting user from creating unrelated class is bad - just
as is forcing him to place his classes in some specific place. IMO it's
totally justifiable to require marking with attributes all classes that
should map to JSON - this way there's no room for confusion and user can
organize his code however he pleases

**Comment by per-samuelsson** [comment]
Thanks for the input @joozek78.

Personally, I always like strict over that more forgiving approach. My experience tell me there is far more often we get weird error reports or make people not understand some of our concepts by "allowing everything" than we hear users complain over that things can just be done in a single, more narrow way.

Let's see if there are others with input too.

**Comment by chrhol** [comment]
I'm not sure what I think. The original thought was more or less the same as @joozek78 pointed out, to not interfere too much in how the developer wanted to organize the classes. 

However, as we have noticed again and again in other places, that this makes it more difficult to understand since there are many different to do the same thing. And also makes it harder for us to parse since we need to support more features.

I think I'm leaning towards a more strict approach. Especially after the comments in #3626

**Comment by per-samuelsson** [comment]
Thanks for input @chrhol.

One thing I want to make really clear here (if it's not obvious for someone), is that this strictness concerns Typed JSON **code behind files only**. For me, these are a **pair** with the JSON-by-example, and that's why I think a more strict approach is justified. 

I just really don't see that there would be a problem if someone wanted to define some arbitrary class that didn't relate to the JSON tree and were presented with an error saying that this has to be done in some other `.cs` file, that we reserve the code-behind file for JSON-specific code.

**Comment by joozek78** [comment]
I think allowing people to add whatever classes they want to code-behind file doesn't make anything more difficult. Allowing to choose nested / side-by-side is IMO really clear - we say that the only thing that determines whether or not class will be bound is its attribute. For me, nested / side-by-side constraint feels strange and artificial

**Comment by per-samuelsson** [comment]
> I think allowing people to add whatever classes they want to code-behind file doesn't make anything more difficult. [...] For me, nested / side-by-side constraint feels strange and artificial.

What you describe there is exactly what we have today, and yet we experience quite some confusion from users. But you might be right, being stricter is not necessarily the best approach to solve it.

**Comment by per-samuelsson** [comment]
For now, I'm switching back to the relaxed nature of how things are today, meaning I'm reverting even the stricter policy that all classes in the code-behind must be mapped. And then wait to see if anyone else give their view, and maybe we can discuss it more, and make it stricter later.

**Comment by per-samuelsson** [comment]
So turns out the ideas I presented here didn't really get any love. The new Roslyn-based parser is hence relaxed to a grade similar as the old one (although it still catches quite a few more errors, when code-behind classes and input handlers are defined wrong).
