### ISSUE TITLE
Question : Weaving C:\...\AdFenix.exe failed with code 6066. Retrying without the cache.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3628]
I always get the following `Notice` when I launch my application : 
`Weaving C:\adfenix-backend\src\bin\Debug\AdFenix.exe failed with code 6066. Retrying without the cache.`

Is it something to worry about? If so, what is the solution for it?

**Comment by per-samuelsson** [comment]
> Is it something to worry about? If so, what is the solution for it?

Nothing critical, no. It indicates the weaver code not properly use the cache of weaved previous results, and that it has to retry not using the cache (which then succeed).

The reason this happen is a limitation in the version of PostSharp the weaver use that can not properly resolve all references in more complex reference trees, such as that used by Society Objects. And hence we must always weave clean in such case.

In an upcoming version, we are turning away from PostSharp, and you will not see this any more. It's quite some time still, but if it's not to bothering, just ignore that notice for now.

**Comment by atifwaqar** [comment]
Thanks.
