### ISSUE TITLE
Unable to bind JSON view-model with :IBount to a nullable type

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3634]
I am trying to use a `struct` type as a binding type for a JSON view-model, but this has side effects. The struct types can't be null, and as soon as an instance of the view-model created it's `Data` populated with a default value of the `struct`. If the `struct` is a database type, and my case it is, it is automatically saved into database. To avoid this I try to bind to a nullable version of the struct:

```cs
public class JsonPage : IBound<MyStruct?> {
}
```

But the `?` sign is ignored and the `JsonPage.Data` property type is still `MyStruct`. The generated code looks as follow:

```cs
public new MyStruct Data { get { return (MyStruct)base.Data; } set { base.Data = value; } }
```

Changing `MyStruct?` with `Nullable<MyStruct>` produces even worse result, which does not even compile:

```cs
public new NullableMyStruct Data { get { return (NullableMyStruct)base.Data; } set { base.Data = value; } }
```

Instead of ignoring `?` and `<>` it should be copied together with type name. I manually changed the generated code to:

```cs
public new MyStruct? Data { get { return base.Data as MyStruct?; } set { base.Data = value; } }
```

It compiles and works.

**Note:** this is not the same issue as https://github.com/Starcounter/Starcounter/issues/3256. In this case we still do not support nullable values inside JSON, but only fix a code generation issue.

Nullable bound objects are already supported, as I can define `IBount<MyClass>` while any class is a nullable type.

cc @per-samuelsson, @chrhol

**Comment by miyconst** [comment]
ping

**Comment by per-samuelsson** [comment]
@chrhol?

**Comment by chrhol** [comment]
Forgot about this one, I will take it.

**Comment by chrhol** [comment]
This seems to be working now that we use the new Roslyn-based parser for Code-behind. It parses the correct typename for both versions of the nullable syntax (`?` and `Nullable<T>`).

Is the new parser in use now for our nightly builds @per-samuelsson or have disabled it?

**Comment by per-samuelsson** [comment]
> Is the new parser in use now for our nightly builds @per-samuelsson or have we disabled it?

It's in use by default, but I'm still working trying to solve #3666, that will happen on some environments. But yeah, the Roslyn-parser should cover this case. Came with something good then at least :smile:

**Comment by chrhol** [comment]
> Is the new parser in use now for our nightly builds @per-samuelsson or have we disabled it?

I meant if it's used when compiling starcounter projects when Starcounter is installed...

**Comment by chrhol** [comment]
I'm too slow when writing comments :) Great, could you verify that it works for you as well then @miyconst?

**Comment by miyconst** [comment]
Yes, I confirm the fix, thank you very much guys.
