### ISSUE TITLE
Can I rely on ObjectNo to determine which of the objects were created first?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3635]
Right now we have unique `ObjectNo` which is a `ulong` value. Each new objects has a new number which is greater than the previous one.

Can I rely on this behavior to determine which of the objects where created first and which second? Considering standard application usage without manual objects insertion.

cc @eriohl

**Comment by miyconst** [comment]
cc @HRidge

**Comment by eriohl** [comment]
Short answer is no. Although a record with a lower id is generally created before a record with a higher idea there is no guarantee that this is the case. It also depends on what you mean by created (id is allocated when pending insert is created, not when it is committed).

**Comment by miyconst** [comment]
By `created` I mean the moment of time when `new` operator was called, so right now it behaves right the way I want.

The only question is whether it's a documented feature, or it will be changed in the future.

**Comment by eriohl** [comment]
It is generally, but not always true now as mentioned. Furthermore it is most likely allocation scheme will change in future. So no: You should not rely on this.

**Comment by miyconst** [comment]
Thank you @eriohl. @HRidge please consider this and add `DateTime` property where it's needed.

**Comment by k-rus** [comment]
> Furthermore it is most likely allocation scheme will change in future.

Just curiosity question about what kind of changes can be. Is it because of certain bits will be used for some specific things or will it be different from counter based allocator?

**Comment by eriohl** [comment]
There is this with the prefix but this does not change much from the current solution, just a different way of dealing with series for replication.

What I was mainly thinking of was multi-processor optimizations. We will then be working with multiple series on the same machine in order to reduce conflicts and off node memory access.
