### ISSUE TITLE
My apps crashed, and I only have the message "The database has been unloaded."

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3637]
![image](https://cloud.githubusercontent.com/assets/4388707/15395587/a8eb7fe0-1dd8-11e6-9c5b-c3bb40e08a8b.png)

**Comment by atifwaqar** [comment]
![image](https://cloud.githubusercontent.com/assets/4388707/15395849/b26b8938-1dd9-11e6-9f31-354766c31d22.png)

**Comment by per-samuelsson** [comment]
@atifwaqar 

The notice in the log saying that the database has been unloaded indicate that Starcounter decided to shut down gracefully the backing database process because it found there were no code host actively referencing it. It's not an error in itself, but indicate there is no code host running (which you hinted could be caused by another error, that was not logged).

**Comment by alemoi** [comment]
@bigwad had a great suggestion to collect crash dumps in such situations. 
Here are the steps to enable crash dumps collection from @bigwad :+1: 
```
Please check %LOCALAPPDATA%\CrashDumps for crash dumps. If folder is empty, create registry value HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\@DumpType=2 and reproduce the crash.
Once we have a dump I'll probably need .pdb files of your local build to investigate it further.
```

@atifwaqar maybe you already had dumps enabled on this machine?

**Comment by atifwaqar** [comment]
@alemoi I dont remember if i have done such thing on this server.
I will confirm and enable it on coming Monday. Hopefully we will not get the error during the weekend.

**Comment by alemoi** [comment]
@atifwaqar did you experience this again?

**Comment by atifwaqar** [comment]
Not really. No server have crashed after it.

**Comment by dan31** [comment]
@atifwaqar activating crash dumps investigation is explained here: https://starcounter.io/guides/tools/guidestoolsinvestigating-apps-crashes/.
