### ISSUE TITLE
Question : Converting MVC handlers to Starcounter HTTP handlers

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3638]
How can I convert this sort of MVC GET handler to SC GET handler? 
`public virtual HttpResponseMessage Get([FromUri]Hub hub)`

Basically I want to achieve what's written in first answer of this post http://stackoverflow.com/questions/17844491/net-mvc-api-dots-period-in-get-request

**Comment by dan31** [comment]
CC @alemoi @miyconst

**Comment by atifwaqar** [comment]
Is this even possible in StarCounter?

**Comment by miyconst** [comment]
@atifwaqar thank you for the question.

Currently Starcounter does not support named parameters, but you can parse entire query string using .net resources:

```cs
var parsedQuery = HttpUtility.ParseQueryString(input);
Console.WriteLine(parsedQuery["q"]);
```

http://stackoverflow.com/questions/6082664/extract-query-string-from-a-url-string

**Comment by atifwaqar** [comment]
@miyconst What will be feeded in the variable `input`, lets say i have this code after you gave the syntax : 

```
Handle.GET("/ChatBot/webhook", (Request input) =>
{
	var parsedQuery = HttpUtility.ParseQueryString(input);
	string var1 = parsedQuery["q"];
	string asdf = System.Text.Encoding.UTF8.GetString(req.RequestBytes);
	Response res = new Response();
	if (req["hub.verify_token"] == "hellotoken")
	{
		res = req["hub.challenge"];
		return res;
	}
	res = "We have an error.";
	return res;
}, new HandlerOptions() { SkipMiddlewareFilters = true });
```

**Comment by atifwaqar** [comment]
If you want to understand what I actually am trying to develop. then you can follow this page : 
https://developers.facebook.com/docs/messenger-platform/quickstart

and I am stuck in the first step, which is Authentication.

**Comment by miyconst** [comment]
@atifwaqar see my example here: https://github.com/miyconst/Playground/commit/a419675cacf77c169a606bceb84666816431630d.

You can open the urls like:

```
http://localhost:8080/playground/parse-query/a=1
http://localhost:8080/playground/parse-query/a=1&b=2
http://localhost:8080/playground/parse-query/a=1&b=2&host.a=123
```

**Comment by miyconst** [comment]
The entire playground solution is available here: https://github.com/miyconst/Playground/.

**Comment by miyconst** [comment]
I have updated the example, so you can use traditional `?` parameters splitter.

```
http://localhost:8080/playground/parse-query?a=1
http://localhost:8080/playground/parse-query?a=1&b=2
http://localhost:8080/playground/parse-query?a=1&b=2&host.a=123
```

**Comment by atifwaqar** [comment]
Sorry, My question was not clear. I hope this may help in understanding my issue.
Facebook says the following : 

> At your webhook URL, add code for verification. Your code should look for the Verify Token and respond with the challenge `sent in the verification request.` Click Verify and Save in the New Page Subscription `to call your webhook with a GET request.`

And then facebook have displayed the following pseudocode, And I am trying to convert this in SC code : 
```
app.get('/webhook/', function (req, res) {
  if (req.query['hub.verify_token'] === '<validation_token>') {
    res.send(req.query['hub.challenge']);
  }
  res.send('Error, wrong validation token');
})
```

**Comment by miyconst** [comment]
@atifwaqar, this is very straight forward:

```cs
Handle.GET("/playground/webhook?{?}", (string s) => {
    var query = System.Web.HttpUtility.ParseQueryString(s);
    string token = query["hub.verify_token"];
    string challenge = query["hub.challenge"];

    if (token != "_validation_token_") {
        Handle.SetOutgoingStatusCode(403);
        return "wrong validation token";
    }

    return challenge;
});
```

The handler answers to any URL like:

```
http://localhost:8080/playground/webhook?
http://localhost:8080/playground/webhook?hub.challenge=my-challenge&hub.verify_token=_validation_token_
```

**Comment by atifwaqar** [comment]
@miyconst Thanks for the update. I have been doing the same way as you suggested, but its not working, Probably its an error at Facebook's end. I'll try to contact their support now.

**Comment by miyconst** [comment]
If it does not work, then you have to post here full URL including query string which you receive from facebook and you `Handle` code, then I can help.

**Comment by atifwaqar** [comment]
@miyconst Sorry for the trouble, it looked like there was some issue in our network or facebook end, I started working on the project today, and everything worked fine. 
Thanks for the help :)
