### ISSUE TITLE
pnext: index_group_setspec_index_sm doens't follow DRY

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3639]
Too fragile. Needs to be redesigned. Requires changes every time we make changes to setspec collation.

**Comment by eriohl** [comment]
The reason for this is that there was no other way to inline reading one character at a time (a function call to the formatter for each character read would be prohibitively expensive). Considered embedding the setspec formatter but this didn't seem feasible for a number of reasons. But I think this is the only way to make this work better.

**Comment by bigwad** [comment]
Probably, key comparison could be done on byte (not character) level, but I don't see immediately how to handle last potentially-partial byte.

**Comment by eriohl** [comment]
Problem is that you need to move up the hierarchy to find the best fit if no match. Couldn't figure this one out without being able to interpret the individual characters. Which is why the key comparison is on character and not byte.
