### ISSUE TITLE
sqlregression_test fails if db core changes order of rows being returned

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3643]
I work on turbotext optimization in the branch tt_fast (level0). As a side effect of changes I've made kernel may return records in another order then it used to. It revealed that sqlregression_test incorrectly relies on that order.
For instance, given the query
```
select e.FirstName, e.Manager.FirstName from SQLTest.EmployeeDb.Employee e order by e.Manager.FirstName
```

it expects
```
 ! 0:String ! 1:String ! 
 | Joachim | <NULL> | 
 | Alexey | <NULL> | 
 | Erik | Åsa | 
 | PETER | Åsa | 
 | Petros | Åsa | 
 | Åsa | Joachim | 
 | per | PETER | 
 | Christian | PETER | 
 | Andreas | PETER | 
```

but actually gets
```
 ! 0:String ! 1:String ! 
 | Joachim | <NULL> | 
 | Alexey | <NULL> | 
 | PETER | Åsa | 
 | Erik | Åsa | 
 | Petros | Åsa | 
 | Åsa | Joachim | 
 | Christian | PETER | 
 | per | PETER | 
 | Andreas | PETER | 
```

cc @k-rus

**Comment by k-rus** [comment]
The test framework is not good enough to cover the cases where the result is partially ordered, like in the above example. Such cases are fixed manually in the test after confirming that the difference in the result does not violate correctness.

**Comment by bigwad** [comment]
I've improved framework a little bit and adapted failed test cases. If other test cases will fail in the future - it's better to utilize new framwork's features, than manually reorder results.
