### ISSUE TITLE
Admin: deleting active database

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3644]
Problem statement
---

People are often confused when they want to delete an active database. They see the 'delete' button, but it's disabled and it's not obvious for them that they first need to stop it (I thought that maybe I can't delete the default database).

Proposed solution
---

When database is active, let the button read 'stop and delete' and make it active. That way it will be obvious that stopping is required to delete a DB, and also make it a click faster

**Comment by per-samuelsson** [comment]
cc @andwah

**Comment by andwah** [comment]
I propose to just enabled the button and let the system stop the database automatically if it's running.

**Comment by per-samuelsson** [comment]
> I propose to just enabled the button and let the system stop the database automatically if it's running.

When you refer to "the system", what layer is that? The underlying management REST API is better to keep strict and clean IMO, and have HTTP DELETE fail in case the resource (i.e. the database) can't be deleted because it conflict with the servers state (i.e. it's running).

But that intermediate admin-specific layer you've added on top of that could certainly do it.

**Comment by per-samuelsson** [comment]
FWIW, I don't think this enhancement is one of the important ones, simply because deleting databases should be relatively uncommon, and also should be done with care. Making it fast and simple can, in worse case, accidentally fuck up big time.

WTBS, this thing:

> They see the 'delete' button, but it's disabled and it's not obvious for them that they first need to stop it (I thought that maybe I can't delete the default database).

is probably good to improve, to make it more clear that it *can* be deleted, just that the user has to stop it first.

**Comment by joozek78** [comment]
> Making it fast and simple can, in worse case, accidentally fuck up big
time

We still have a safety net in form of re-typing database name - IMO it's
sufficient. I raised this issue, becuase @warpech mentioned people are
often confused about this

**Comment by andwah** [comment]
> When you refer to "the system"

I thought of the first layer REST Api that the administrator uses, not the core one.  But we can make it even better just by putting the logic on the client side (Angular).

**Comment by warpech** [comment]
For me it would be enough to show a tooltip or an alert saying "Only stopped databases can be deleted".

**Comment by andwah** [comment]
If the user clicks the "Delete" button i think he want's to delete the database, so why not just do that for him?.. 

Let the user be is in charge :-)

**Comment by per-samuelsson** [comment]
> We still have a safety net in form of re-typing database name - IMO it's sufficient.

Ah, do we? It's similar to what we have in `staradmin delete db` then, and that is certainly sufficient.

> If the user clicks the "Delete" button i think he want's to delete the database, so why not just do that for him? Let the user be in charge :-)

Yeah, sure, in the light of the fact that he/she has to type the name, I totally agree.

> I thought of the first layer REST Api that the administrator uses, not the core one. But we can make it even better just by putting the logic on the client side (Angular).

It's not my decision, but I'd vote for the admin-specific REST API. Not the client. It's up to you though. :sunglasses: :smile: 

On a related note, if we change this, maybe we should adapt `staradmin delete db` too, to make them somewhat consistent? If so, I think we should detect that the database is running, and when we ask for the user to type the name, we also inform that we'll stop the database before deleting it. And the `--force` flag would do both without prompting. WDYT @andwah @warpech @joozek78?

**Comment by joozek78** [comment]
>  maybe we should adapt staradmin delete db too, to make them somewhat consistent? If so, I think we should detect that the database is running, and when we ask for the user to type the name, we also inform that we'll stop the database before deleting it. And the --force flag would do both without prompting

I agree - CLI should always have `--force` option, otherwise it's a pain to script it.

**Comment by per-samuelsson** [comment]
> CLI should always have --force option, otherwise it's a pain to script it.

FYI, it does already. For that reason. But today it acts as web admin does, i.e. it fails if you try to delete a running database (with a message saying the database need to be stopped first). So in scripting you would normally go about doing:

```
staradmin stop db
staradmin delete --force db
```

The question was if we should adjust `staradmin delete db` accordingly to what is proposed in this issue.

**Comment by joozek78** [comment]
> The question was if we should adjust staradmin delete db accordingly to what is proposed in this issue.

I also agree with this adjustment. `--force` is well-known flag and I'd expect it to try and delete this db with by all means

**Comment by andwah** [comment]
> We still have a safety net in form of re-typing database name - IMO it's sufficient.

see #448




> It's not my decision, but I'd vote for the admin-specific REST API. Not the client. It's up to you though.

we can use the same REST api that `staradmin `use if there is one call to "stop and delete" database, otherwise i think the best solution is to put the logic on the client side. It still use REST of course to Stop and Delete the database but in two steps.

**Comment by per-samuelsson** [comment]
> we can use the same REST api that staradminuse if there is one call to "stop and delete" database, 

It's not. Today, `staradmin delete db` will fail if the database is running.

If I change it as is proposed here, I will make implement that functionality in `staradmin`, so that it use one call to stop the database, and a successive call to delete it.

**Comment by andwah** [comment]
> I will make implement that functionality in staradmin, so that it use one call to stop the database, and a successive call to delete it.

Nice. then it will do the same thing as the Administrator does. 

Everyone agrees?  let's do it :-)

**Comment by andwah** [comment]
Fixed in the Administrator 9ab0645f53f1e0032fe463749a93b1e86314deb7

Removed the button `disabled` state.

![image](https://cloud.githubusercontent.com/assets/2656996/15531982/9d6b173c-225d-11e6-84e1-ae68e629b825.png)

**Comment by per-samuelsson** [comment]
> Fixed in the Administrator.

Great. And I'm just done with #3649.

@joozek78, feel free to test these changes and close this issue if it works to your satisfaction. :smile:

**Comment by joozek78** [comment]
It works just fine. Closing
