### ISSUE TITLE
pnext: The archive subfolder grows quickly and seems to contain redundant files

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3646]
Looking inside the archive folder of my database, it seems redundant `.optlog` files aren't being cleaned out. Looking at the increasing file sizes, I would expect that `REPL0.000008094314.optlog` contains all the information that the previous `.optlog` files have.

Is there some cleaning operation that should be running that isn't?

```
REPL0.000000000000.log	268 435 456	2016-05-20 17:21	-a--c
REPL0.000000000001.log	268 435 456	2016-05-20 17:23	-a--c
REPL0.000000000002.log	268 435 456	2016-05-20 17:25	-a--c
REPL0.000000000003.log	268 435 456	2016-05-20 17:33	-a--c
REPL0.000000000004.log	268 435 456	2016-05-20 17:36	-a--c
REPL0.000000000005.log	268 435 456	2016-05-20 17:38	-a--c
REPL0.000000000006.log	268 435 456	2016-05-20 17:40	-a--c
REPL0.000000000007.log	268 435 456	2016-05-20 17:42	-a--c
REPL0.000000000008.log	268 435 456	2016-05-20 17:48	-a--c
REPL0.000000000009.log	268 435 456	2016-05-20 17:51	-a--c
REPL0.000000000010.log	268 435 456	2016-05-20 17:54	-a--c
REPL0.000000000011.log	268 435 456	2016-05-20 18:01	-a--c
REPL0.000000000012.log	268 435 456	2016-05-20 18:04	-a--c
REPL0.000000000013.log	268 435 456	2016-05-20 18:08	-a--c
REPL0.000000000014.log	268 435 456	2016-05-20 18:11	-a--c
REPL0.000000000015.log	268 435 456	2016-05-20 18:15	-a--c
REPL0.000000000016.log	268 435 456	2016-05-20 18:18	-a--c
REPL0.000000000017.log	268 435 456	2016-05-20 18:22	-a--c
REPL0.000000000018.log	268 435 456	2016-05-20 18:26	-a--c
REPL0.000000455583.optlog	189 456 384	2016-05-20 17:21	-a--c
REPL0.000000903486.optlog	376 958 976	2016-05-20 17:23	-a--c
REPL0.000001353190.optlog	565 174 272	2016-05-20 17:25	-a--c
REPL0.000001791294.optlog	749 219 840	2016-05-20 17:33	-a--c
REPL0.000002210002.optlog	925 556 736	2016-05-20 17:37	-a--c
REPL0.000002633519.optlog	1 103 994 880	2016-05-20 17:38	-a--c
REPL0.000003057264.optlog	1 282 613 248	2016-05-20 17:40	-a--c
REPL0.000003481086.optlog	1 460 871 168	2016-05-20 17:42	-a--c
REPL0.000003904250.optlog	1 638 707 200	2016-05-20 17:48	-a--c
REPL0.000004325532.optlog	1 816 244 224	2016-05-20 17:52	-a--c
REPL0.000004747292.optlog	1 993 875 456	2016-05-20 17:54	-a--c
REPL0.000005164352.optlog	2 168 991 744	2016-05-20 18:01	-a--c
REPL0.000005582581.optlog	2 344 656 896	2016-05-20 18:05	-a--c
REPL0.000006001522.optlog	2 520 440 832	2016-05-20 18:08	-a--c
REPL0.000006420459.optlog	2 696 216 576	2016-05-20 18:12	-a--c
REPL0.000006839048.optlog	2 872 131 584	2016-05-20 18:15	-a--c
REPL0.000007256777.optlog	3 048 099 840	2016-05-20 18:19	-a--c
REPL0.000007675829.optlog	3 223 994 368	2016-05-20 18:23	-a--c
REPL0.000008094314.optlog	3 399 561 216	2016-05-20 18:27	-a--c
```

**Comment by per-samuelsson** [comment]
Somewhat related to #3642.

Are these both **pnext**-specific, or concern both branches?

**Comment by bigwad** [comment]
@per-samuelsson, it's all about log retention and specific to pnext.

Regarding issue: it's because log files are not self-sufficient. To read particular log file, the entire history prior to that file should be in place. Either in form of optimized or non-optimized logs.
Removing too many optlog files we got this issue: https://github.com/StarcounterPrefabs/LogStreamer/issues/32

Logically, it's enough to keep one optlog file. The oldest one - that made of all already removed logs.
The problems with this are 
- it will slow down logreader positioning significantly
- it will require performing logopt inside archive folder on logs retention, consuming CPU and disk.

**Comment by per-samuelsson** [comment]
> @per-samuelsson, it's all about log retention and specific to pnext.

Thanks @bigwad. Then I hope you don't mind me changing the title of those two issues accordingly.

**Comment by linkdata** [comment]
After six hours of running `LogStreamerBulker`, approximately 80% of the disk space used by the database folder are `archive` folder contents. Database files and latest optlog is 4GB, and `archive` folder is 32GB.

@bigwad @dan31 @eriohl : Is this really working as intended?

**Comment by eriohl** [comment]
> @bigwad @dan31 @eriohl : Is this really working as intended?

Kind of a tricky question to answer on my part since I don't know how it is intended to work.

**Comment by linkdata** [comment]
> Kind of a tricky question to answer on my part since I don't know how it is intended to work.

So who does know? It's a problem for me since it keeps filling up my disk.

**Comment by bigwad** [comment]
it's safe to remove all optlog files from archive folder unless you're going to run your test for more than 30 days

**Comment by linkdata** [comment]
> it's safe to remove all optlog files from archive folder unless you're going to run your test for more than 30 days

Running this for 30 days would probably require more disk space for `archive` than is available in all of europe, including CERN... :smile: 

So if a customer needs to run Starcounter for more than 30 days, which are *not* safe to remove?

**Comment by bigwad** [comment]
For production it's more tricky. What could help a lot is if we may remove archived files that are __likely__ no more required for replication.

**Comment by linkdata** [comment]
> For production it's more tricky. What could help a lot is if we may remove archived files that are likely no more required for replication.

Well, like I said in the [original post](https://github.com/Starcounter/Starcounter/issues/3646#issue-156462483), the optlog files seem to be redundant. Or are they really growing exponentially in size?

For instance, two early optlog files have a size difference of about 200MB:
```
REPL0.000000455583.optlog   189 456 384   2016-05-20 17:21    -a--c
REPL0.000000903486.optlog   376 958 976   2016-05-20 17:23    -a--c
```

Two later ones also have that same difference in size, about 250MB:
```
REPL0.000007675829.optlog   3 223 994 368    2016-05-20 18:23    -a--c
REPL0.000008094314.optlog   3 399 561 216    2016-05-20 18:27    -a--c
```

That suggests to me that the actual *new* data is increasing at a constant rate (which is consistent with what the system is actually doing), but the optlog system is keeping a huge amount of unneeded data around.

I have a really hard time believing that all of those optlog files need to be saved.

**Comment by bigwad** [comment]
I answered in the same thread: https://github.com/Starcounter/Starcounter/issues/3646#issuecomment-221230875

In short - yes, they are redundant, in the sense that they could be restored from other log files.
But ultimately all of them could be in need (but not all at the same time).

**Comment by bigwad** [comment]
Anyway, for production this quadratic growth is not acceptable.
I see two ways to keep it manageable:
1. remove files that are likely no more required for replication.
2. implement [shema](https://github.com/Starcounter/Starcounter/issues/3646#issuecomment-221230875) that will remove logopt files that are not currently in need and recreate them lately.

These items don't contradict to each other - we can implement either or both. I'll implement the second one as I'm fully responsible for all components involved. Then will see how it goes.

**Comment by linkdata** [comment]
> 1. remove files that are likely no more required for replication.

We can never know that, as it depends on the (possibly changing) needs of the user.

**Comment by bigwad** [comment]
Right, but anyway finally some logs get removed. Probably in some cases it's safe enough to remove those logs earlier. Probably with some help from user side.

**Comment by bigwad** [comment]
implemented as described [here](https://github.com/Starcounter/Starcounter/issues/3646#issuecomment-221230875)
