### ISSUE TITLE
WebSocket server "WebSocketDisconnect()" handler does not fire reliably

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3647]
Running LogStreamer with inbound tasks on one scheduler and outbound tasks on another provokes this under heavy load. Eventually the SC WS server aborts the TCP connection but doesn't deliver a "disconnected" event to the app, so it keeps on happily sending messages even though there is no TCP connection.

Talking with @alemoi about this.

**Comment by alemoi** [comment]
Thanks for reporting. I know the reason, which is not having enough IPC chunks. I will change the design and get back to you.

**Comment by linkdata** [comment]
Branch of LogStreamer that exhibits this behaviour: https://github.com/StarcounterPrefabs/LogStreamer/tree/Starcounter/issues/3647

**Comment by linkdata** [comment]
Duplicate of https://github.com/Starcounter/Starcounter/issues/3463
