### ISSUE TITLE
Question : Can I run 1 app (adfenix.exe) on a machine twice?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3655]
Is it possible to run 1 app on a machine twice? 
like I create 2 databases, 1st runs on port 8080 and 2nd runs on port 7070 (or any other port), and then I launch the same exe file in both databases?

**Comment by miyconst** [comment]
Yes, databases are isolated between each other. The only limitations are:

- Only one running database per port.
- Uniquer application name per database.

**Comment by per-samuelsson** [comment]
I can only confirm what @miyconst already have written.

Does that fully answer your question @atifwaqar? If so, let's close this issue.

**Comment by atifwaqar** [comment]
Thanks @miyconst
