### ISSUE TITLE
Question : How can I query DateTime in SC Admin Panel

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3656]
Is it possible to execute a Query with DateTime in `WHERE` clause ?
If not, do you plan to have this in future?

**Comment by miyconst** [comment]
Yes. You can query `DateTime` properties as any other values.

```cs
var products = Db.SQL<Product>("SELECT p FROM Product p WHERE p.CreateDate > ?", DateTime.Today);
```

**Comment by per-samuelsson** [comment]
> Yes. You can query `DateTime` properties as any other values.

The title suggest that it's about how to do it in SQL tab in web administrator. Is that correct, @atifwaqar?

cc @k-rus @andwah

**Comment by andwah** [comment]
`SELECT e FROM Employee e WHERE e.HireDate = DATE '2006-11-01'`

See http://starcounter.io/guides/sql/literals/

**Comment by per-samuelsson** [comment]
Great, @andwah!

@atifwaqar, does this answer your question? If so, let's close this.

**Comment by atifwaqar** [comment]
Thank you guys.

**Comment by binte** [comment]
I can't fetch any data with that. Which version are you using @andwah ?

**Comment by atifwaqar** [comment]
We are using SC Version 2.2.1834

In this query you can see the DateTime :
![image](https://cloud.githubusercontent.com/assets/4388707/15605363/c522b024-2405-11e6-911c-7bd6c3485135.png)

In this query when I try use your suggested syntax I get nothing :
![image](https://cloud.githubusercontent.com/assets/4388707/15605402/0083315c-2406-11e6-92ad-4c1136609c39.png)

**Comment by per-samuelsson** [comment]
@atifwaqar 

Can you try and test 

1. with DATE (upper) to see it it's case-sensitive, and if that doesn't work
2. with different formatting, such as that provided by @andwah above, like `SELECT e FROM Employee e WHERE e.HireDate = DATE '2006-11-01'`

I'm really not an expert, just trying and guessing here.

**Comment by binte** [comment]
It doesn't work here!

**Comment by per-samuelsson** [comment]
@binte 

> It doesn't work here!

OK, thanks for letting us know.

@andwah? @k-rus?

**Comment by miyconst** [comment]
>It doesn't work here!

What and where is not working?

I just made a local test:

```sql
SELECT *
FROM Palma.Event
WHERE "Timestamp" = DATE'2016-05-18T15:20:19.3959015'
```

![image](https://cloud.githubusercontent.com/assets/6435556/15606478/ca94be4c-240c-11e6-8d4a-eb32e2eea7f9.png)

Also it works with `>` and `<` operators. The `DATE` keyword is not case sensitive, so it can be `date` as well.

What is the type of the `Updated` column?

**Comment by andwah** [comment]
As i understand from the documentation the date format should be like this `yyyy-mm-dd hh:mm:ss[.nnn]`  when you do your query.

**Comment by Ripipip** [comment]
It works perfectly fine for me over here so I think we can figure this out :)

**Comment by binte** [comment]
I confirm it's also working here as well! But the '=' operator doesn't work very well. 

![screen1](https://cloud.githubusercontent.com/assets/5520287/15607778/bb5b48fc-2415-11e6-9bc1-d6b2c4fd6b93.png)
![screen2](https://cloud.githubusercontent.com/assets/5520287/15607779/bb5ba130-2415-11e6-9bce-077dba9df954.png)
![screen3](https://cloud.githubusercontent.com/assets/5520287/15607780/bb5e92c8-2415-11e6-8bc2-a38ead2b593b.png)

**Comment by per-samuelsson** [comment]
> But the '=' operator doesn't work very well.

@andwah , it worked for you, didn't it? Any idea the queries provided by @binte doesn't get any hits?

**Comment by per-samuelsson** [comment]
@andwah @binte 

By looking at the strings you provide, and specifically the format of the DATE value, it looks like it's very sensitive to the format. The one provided by @binte does *not* exactly match that of @andwah in terms of formatting. I guess that's the case?

Also, @andwah, is your "Timestamp" property in C# a `DateTime`? And @binte, is your `Updated` property that as well?

**Comment by per-samuelsson** [comment]
I see @andwah suggested this

> As i understand from the documentation the date format should be like this `yyyy-mm-dd hh:mm:ss[.nnn]`  when you do your query.

And it looks like the (second) query of @binte match that. But looking at your query, @andwah, it does not, it include the `T` delimiter, instead of a space, i.e. `yyyy-mm-ddThh:mm:ss[.nnn]` (notice the "T" literal delimiter).

We need to straighten these question marks out so that we can provide accurate documentation on what works and what does not.

**Comment by per-samuelsson** [comment]
And on a related note, shouldn't a query that omit the time return a hit, like the one @binte do [here](https://cloud.githubusercontent.com/assets/5520287/15607779/bb5ba130-2415-11e6-9bce-077dba9df954.png)?

**Comment by miyconst** [comment]
>And on a related note, shouldn't a query that omit the time return a hit

No, it should not, unless we provide some sugaring on top. A `DateTime` value is a number value,
`130000 != 130010`, in .NET `DateTime` objects with different time return `false` after comparison.

If someone wants to get all entries per day, it should be done with `>=` and `<` operators.

**Comment by binte** [comment]
@per-samuelsson it is a DateTime! 

Thanks for letting us know about this feature. We will use it and abuse it for sure :)
