### ISSUE TITLE
Log reader performance is insufficient

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3659]
I have a database where the log reader isn't doing so well. Making a copy of it for @bigwad. Database itself seems to run fine, but the log reader isn't making progress reading it.

**Comment by bigwad** [comment]
I've managed to dump the entire transaction log using dbhistory utility. So don't see any obvious problem with logreader. What make you think you have any?

**Comment by linkdata** [comment]
LogStreamer stopped receiving transactions from ILogReader.ReadAsync() even though new transactions were being generated. I'll see if I can reproduce it again.

**Comment by linkdata** [comment]
> I've managed to dump the entire transaction log using dbhistory utility. 

I can also do that successfully. However, the LogStreamer uses the `ILogReader.ReadAsync()` API, not the `dbhistory.exe` utility.

The `Task` that `ILogReader.ReadAsync()` returns never completes.

**Comment by bigwad** [comment]
dbhistory uses the same task-based API.
Have you reproduced the problem? May I take a look at the live process?

**Comment by linkdata** [comment]
I can. You may reproduce it yourself as well. The databases and replication configs are on the FTP. Grab and run `LogStreamer` (branch `issue/35`) and `LogStreamerBulker` (master branch) on both `repl0` and `repl1`.

**Comment by linkdata** [comment]
Actually, hold off a bit. The one I had running in the background eventually started to send after an hour. It might be that the LogReader is simply extremely slow. What's the expected scan rate of the log? How many commits per second would you expect the LogReader to be able to process on our work machines on a Debug build?

**Comment by linkdata** [comment]
On my machine (Core i7-3770 @ 3.5GHz), a call to `ILogReader.ReadAsync()` in the release build will usually take 0.2 - 2.0 ms, meaning that it limits the `LogStreamer` to run at a fraction of the speed the rest of the system is able to produce transactions.

Worse, if the average system transaction rate is higher than what the `LogReader` can process, the system as a whole will never catch up and eventually fail.

It's possible I'm doing something wrong, but I fairly confident in these measurements. We should ask @dan31 to allocate time for you to have a look at this.

**Comment by bigwad** [comment]
I've got opposite results.
1. dbhistory in debug mode dumps transactions at the rate 800 transactions per second
2. @linkdata configuration (two databases, logreader, logbulker) in debug mode transmits about 400 transactions per second both way. It takes almost four cores to process, two thirds of which takes LogStreamerBulker.exe!LogStreamerBulker.Program::CheckRecords and the rest third is for logreader.
3. @linkdata configuration in release mode transmits about 400 transaction per second. It takes about two cores performining LogStreamerBulker.exe!LogStreamerBulker.Program::CheckRecords. Logreader in release configuration takes negligible time.

I'll keep this configuration running to see if I can reproduce original issue.

**Comment by linkdata** [comment]
Thanks for setting that up and testing it out.

For testing in release mode, you should use the latest `master` branch of `LogStreamer`.

The Bulker is the load simulator - it does a lot of work (both CPU-wise and database-wise). So it's expected for it to use a lot of resources. I will add a feature to it to disable the most CPU-heavy task (it's constantly scanning the DB and doing MD5 hashes on it's records). 

However, the log reader must be able to read from the transaction log at a (much) higher rate than any set of applications can add to it. Otherwise, the system as a whole can never be stable.

**Comment by bigwad** [comment]
Have measured pure logreader rate: 24000 transactions per second. Aligned very good with numbers I showed for dbhistory. Disk queue was persistently more than 1 (SDD drive) that shows that computationally logreader is pretty well optimized. Although definitely it may be improved both CPU and IO wise, performance doesn't seem all that bad for practical purposes.

To original issue: test in release mode was running for 14 hours and finally it created so many transactions that bulker started to crash with:
```
20160601T093759 Critical sc://wad-pc/personal/repl0 Starcounter - System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\\projects\\starcounter\\pnext\\level1\\src\\Hosting\\Starcounter.Hosting\\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\\projects\\starcounter\\pnext\\level1\\src\\Starcounter\\DbSession.cs:line 194
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\\projects\\starcounter\\pnext\\level1\\src\\Hosting\\Starcounter.Hosting\\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\\projects\\starcounter\\pnext\\level1\\src\\Hosting\\Starcounter.Hosting\\Processor.cs:line 99
HResult=-2146233088\r\nHelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at LogStreamerBulker.Program.Check(Record record) in C:\\projects\\starcounter\\pnext\\LogStreamerBulker\\LogStreamerBulker.cs:line 74
   at LogStreamerBulker.Program.<>c.<CheckRecords>b__51_0() in C:\\projects\\starcounter\\pnext\\LogStreamerBulker\\LogStreamerBulker.cs:line 120
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\\projects\\starcounter\\pnext\\level1\\src\\Starcounter\\Db.cs:line 310
   at LogStreamerBulker.Program.CheckRecords() in C:\\projects\\starcounter\\pnext\\LogStreamerBulker\\LogStreamerBulker.cs:line 115
   at Starcounter.Task.Run() in C:\\projects\\starcounter\\pnext\\level1\\src\\Starcounter\\DbSession.cs:line 100
HResult=-2147024882
```

So, I failed to reproduce original issue. I'll setup it again in debug mode and will see how it goes.

**Comment by linkdata** [comment]
> So, I failed to reproduce original issue. I'll setup it again in debug mode and will see how it goes.

Original issue isn't valid. See https://github.com/Starcounter/Starcounter/issues/3659#issuecomment-222624591:

> Actually, hold off a bit. The one I had running in the background eventually started to send after an hour. It might be that the LogReader is simply extremely slow.

> Have measured pure logreader rate: 24000 transactions per second. 

The absolute read rate of the log reader on any given machine isn't really important. It just needs to be able to read faster than any set of applications can write to the log. Even if those applications are also using the CPU to do work.

I'll try boosting the thread priority for the log reader, but since we can push hundred of thousands of transactions per second in general, I don't think it will help those 24000 TPS enough.

**Comment by bigwad** [comment]
>"Actually, hold off a bit. The one I had running in the background eventually started to send after an hour. It might be that the LogReader is simply extremely slow."

Not extremely, not slow, no hour delay in my experiment as I can say. What do you think your processes did during that hour? Any clue? Not sure what happened to your lab. Will try to reproduce.

>It just needs to be able to read faster than any set of applications can write to the log.
Hardly achievable in practice, considering additional work for text formatting and that even TT decoding is slower than encoding. So should be connected with the expected average transaction rate. It's very pleasant if db may handle bursts in query rate, but it's not that significant for logreader.

**Comment by linkdata** [comment]
> What do you think your processes did during that hour? Any clue?

It was scanning past transactions that were being filtered out (not part of the set to be transmitted to that receiver).

> Hardly achievable in practice, considering additional work for text formatting and that even TT decoding is slower than encoding.

Performing a database transaction usually requires (a lot) more work than text formatting and TT encoding. That reading the transaction log would require the same amount of work (or more) seems strange. Please explain your reasoning a bit more.

**Comment by bigwad** [comment]
>It was scanning past transactions that were being filtered out (not part of the set to be transmitted to that receiver).

Hope LogStreamer was rescanning the log due to some configuration changes. Otherwise besides poor performance, it is a subject to the same retention problem as [here] (https://github.com/Starcounter/Starcounter/issues/3552).

>Performing a database transaction usually requires (a lot) more work than text formatting and TT encoding. That reading the transaction log would require the same amount of work (or more) seems strange. Please explain your reasoning a bit more.

Performing simple transaction actually requires not so lot of work. And it scales on multiple cores. Not sure we want logreader to be that complicated. 
Text handling shouldn't be underestimated as well. For example text encoding takes about 25% for simple transaction updating string of 1000 characters. Obviously, fraction of time dedicated to encoding grows accordingly to the string size.

As I said it's definitely possible to optimize logreader. It just the criteria you suggest may be unreachable in all scenarios, but at least it's a good asymptote. Other question is do we actually need to spend time on it. I don't think it's critical, but will take a look. And sure it's up to @dan31 to raise the priority.

**Comment by linkdata** [comment]
> Hope LogStreamer was rescanning the log due to some configuration changes.

Why would you assume it was rescanning?

It wasn't connected to the peer while those transactions were written, and so needs to scan them once the peer connects and let's it know where to start from. This is likely to be fairly common for some customers.

**Comment by bigwad** [comment]
ok, I see. I was misleading by your note that those transactions "were being filtered out". Anyway, yes after the long disconnection period you need to catch up a lot of transactions.

**Comment by bigwad** [comment]
Numerous improvements have been pushed.
One of them is a filtering of log entries based on a table name. Pass Func<string, bool> predicate to ILogManager.OpenLog to enable filtering. The predicate is assumed to be idempotent.
