### ISSUE TITLE
Question : How to populate Json From String? & then store in DB?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3661]
I read the SC_Json related guide from [here ](http://starcounter.io/guides/json/populate-json-with-database-data/).

But my scenario is entirely Reverse of `Populate JSON with database data`, with an additional step, I have a JsonSting not an SC_Typed_Json.

**Comment by atifwaqar** [comment]
What I think is that there may be 2 easy ways and 1 hard way of doing this in SC :
1. Convert the JsonString to an SC_TypedJson, and then Populate/Store the SC_TypedJson in DB
2. Convert the JsonString to standard C# Json, and then Populate/Store the standard C# Json in DB
3. Convert the JsonString to standard C# Json, Map it to SC_TypedJson line by line, and then Populate/Store the SC_TypedJson in DB

**Comment by miyconst** [comment]
@atifwaqar do you want to populate database with string JSON data?

**Comment by atifwaqar** [comment]
Yes @miyconst

**Comment by per-samuelsson** [comment]
@atifwaqar 

It's not really clear what the setup looks like.

But in a rather common case, you'll have a database model, that is exposed to views with with a view-model, like:

**Database model**
```cs
[Database] public class Foo {
  public string Bar;
}
````

**View model**
```json
{
  "Bar" : ""
}
```

```cs
partial class FooViewModel : Json, IBound<Foo> {
}
```

With that, if you have a JSON string that correspond to the view model, you could do something like:

```cs
var f = new Foo();
var f2 = new FooViewModel();
f2.Data = f;
f2.PopulateFromJson("your-json-string-goes-here");
```

Executing that in a transaction will effectively store your JSON in the database (in the form of a Foo-instance).

**Comment by miyconst** [comment]
@atifwaqar if you need to populate database with data from JSON you don't need to use JSON view-model or TypedJSON at all. I have created an example for you:

```cs
string json = "[{ \"Name\": \"fx-8350\", \"Socket\": \"AM3\" }, { \"Name\": \"i7-6850k\", \"Socket\": \"2011-3\" }]";
 
 Db.Transact(() => {
     List<Cpu> cpus = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Cpu>>(json);
 });
```

See the full example in the commit referenced to this issue.

**Comment by atifwaqar** [comment]
Awesome @miyconst , Now just one more question, How the DB should look like for the following Json?

`string json = "[{ \"Name\": \"fx-8350\", \"Sockets\": [{\"Socket\": \"AM3\"},{\"Socket\": \"AM3\"}]}, { \"Name\": \"i7-6850k\", \"Sockets\": [{\"Socket\": \"AM3\"},{\"Socket\": \"AM3\"}]}]";`

**Comment by per-samuelsson** [comment]
> Now just one more question, How the DB should look like for the following Json?

I guess like in the [referenced source, Cpu.cs](https://github.com/miyconst/Playground/blob/master/Playground/Data/Cpu.cs).

**Comment by atifwaqar** [comment]
My example is a bit different, I have an array of Sockets

**Comment by per-samuelsson** [comment]
> My example is a bit different, I have an array of Sockets.

Ah, sorry. My bad. Now I see.

**Comment by atifwaqar** [comment]
No problem, I had an idea :P

**Comment by miyconst** [comment]
@atifwaqar the database class definition does not make any difference. You can use any database class as long as JSON represents it and `Newtonsoft.Json.JsonConvert` is able to deserialize the string.

**Note:** you can use any JSON converter you like, the `Newtonsoft` was used in the example as the most popular one.

**Comment by atifwaqar** [comment]
@miyconst Sorry i could not understand you.

**Comment by atifwaqar** [comment]
My Json strings are now being deserializing perfectly fine, the only issue i have now is that when i have an Array in my Json, I get an exception. Which makes sense, because my database declaration is not representing an array.

So what i need now is something like :
```
using System;
using Starcounter;

namespace Playground {
    [Database]
    public class Cpu 
    {
        public string Name;
        public List<Socket> Sockets;
    }
}

```

but I know that `List<Socket>` is not doable in StarCounter, so I need suggestion for an alternative.

**Comment by atifwaqar** [comment]
Basically its gonna be be a [`One-to-many relation`](http://starcounter.io/guides/database/one-to-many-relations/), but what required is an option to set `IEnumerable ` like following : 

```
using System;
using Starcounter;

namespace Playground {
    [Database]
    public class Cpu 
    {
        public string Name;
        public IEnumerable Sockets
        {
            get
            {
                return Db.SQL<Socket>(@"SELECT s FROM Socket s WHERE Cpu=?", this;
             }
            set
            {
                foreach (socket valueOfOneSocket in value)
                {
                    Socket _Socket = new Socket;
                    _Socket.Cpu = this;
                    _Socket = valueOfOneSocket;
                }
            }
        }
    }
}
```

**Comment by miyconst** [comment]
@atifwaqar the `QueryResultRow<T>` collection is readonly, and obviously you can't set it or add values. The solution your propose won't work, because `Newtonsoft.Json.JsonConvert` get's the value of `public IEnumerable Sockets` and tries to append values to there.

You have to define a custom collection to be able to add values. See my latest referenced commit with an example.

**Comment by atifwaqar** [comment]
@miyconst :+1: :+1: I replicated your code in my solution, and it works fine. 
But I am facing an issue in with this code, I am unable to do following with `Cpu.Reviews`:

```
var Cpu = Db.SQL<Cpu>("SELECT c FROM Playground.Cpu c fetch ?", 1);
FunctionToEmailReview(Cpu.Reviews);
```

Instead I have to do something like :

```
var Review = Db.SQL<Review>("SELECT r FROM Playground.Review r fetch ?", 1);
FunctionToEmailReview(Cpu.Reviews);
```

Now I have a case where I have 5 level deep nesting. an example will be like : 
`DataCenters.Racks.Shelfs.Cpus.Reviews`

In this case I have to make 5 queries. Do you have a way where I just make 1 query to get an object of `DataCenter` and then I can get to `Reviews` directly?
I'll totally understand if you say this is not possible, but i'm just asking for confirmation.

**Comment by miyconst** [comment]
If I understood your problem correctly, then you can do a single query like this:

```cs
var reviews = Db.SQL<Review>("SELECT r FROM Review r WHERE r.Cpu.Shelf.Rack.DataCenter = ?", dataCenter);
```

**Comment by atifwaqar** [comment]
@miyconst Perfect, This fixes my problem. 
Just out of curiosity, is it possible to get `reviews` without querying? like for example if I just created the object `dataCenter` with full details and I want to do something as following : 
`dataCenter[0].Rack[5].Shelf[2].Cpu[7].Revew`
OR 
`dataCenter["Stockholm"].Rack["AdFenix"].Shelf["Second"].Cpu["Intel I-7"].Revew`

**Comment by miyconst** [comment]
@atifwaqar this is pure C#, you have to read more of how `List<T>` and `Dictionary<TKey, TValue>` work. Also [indexers](https://msdn.microsoft.com/en-us/library/6x16t2tx.aspx) might help.

Please close the issue if you find your question answered.

**Comment by atifwaqar** [comment]
Thanks a lot @miyconst

**Comment by atifwaqar** [comment]
@miyconst  I am using your suggested `Json to DB conversion`, and my code is something like :
```
string CpuName = ReceivedVariableInPostRequest;
Cpu cpu = Db.SQL<Cpu>("SELECT cpu FROM Database.Cpu cpu Where Cpu.Name = ?", CpuName);

string json = "{ \"Name\": \"fx-8350\", \"Socket\": \"AM3\",\"CpuLoad\" }";//or the json received in Post Request, which have different CpuLoad value every time
 Db.Transact(() => {
     cpu = Newtonsoft.Json.JsonConvert.DeserializeObject<Cpu>(json);
 });
```

This code is executed every min. When I run this code for the first time, I dont have the Cpu Object in my DB, and the code creates the object as it should. 
But when I run this code for second or third time, it still creates the db object instead of just updating the previously created object. 

How do I avoid the Creation of objects in 2nd or third request and just Update the pre-created objects?

**Comment by atifwaqar** [comment]
The alternate way is to code as following :

```
string CpuName = ReceivedVariableInPostRequest;
Cpu cpu = Db.SQL<Cpu>("SELECT cpu FROM Database.Cpu cpu Where Cpu.Name = ?", CpuName);

string json = "{ \"Name\": \"fx-8350\", \"Socket\": \"AM3\",\"CpuLoad\" }";//or the json received in Post Request, which have different CpuLoad value every time
 Db.Transact(() => {
     if (cpu == null)
     {cpu = new Cpu();}
     cpu.Name = json.parse("name");
     cpu.Socket = json.parse("Socket");
     cpu.CpuLoad = json.parse("CpuLoad");
 });
```

Which is a good solution only if i had 3 or 4 attributes in Json, but My json have more than 170 attributes.

**Comment by miyconst** [comment]
>But when I run this code for second or third time, it still creates the db object instead of just updating the previously created object.

This is expected and correct behavior. Please read more about [reference data types](https://msdn.microsoft.com/en-us/library/490f96s2.aspx) in .NET. 

If you want to update an existing object, then you have to write an update method. You can:

- Copy values from the new object to the old one and then remove the new one.
- Create a new object and delete the old one.

Please use this repository to ask Starcounter related questions. Stackoverflow is the bset place for .NET questions.

**Comment by atifwaqar** [comment]
@miyconst Thanks for the help, I am creating my Objects as you suggested.
> Copy values from the new object to the old one and then remove the new one.
