### ISSUE TITLE
System.Collections.Immutable is missing

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3666]
Since the latest **nightly build**, we have various reports with failures caused by missing `System.Collections.Immutable` assembly, and we are currently investigating it.

Among others, @mattiasmak has reported this.

I think we are getting closer to finding the cause, but I need some help to check some environment-specific things. When you have a minute @mattiasmak, could you please open a "Developer command prompt for VS2015" and run the following?

```
gacutil /l System.Collections.Immutable 
```

Any hits on that? And if so, what version(s) do you see?

(Hint: run it piped via `| clip` and paste content here).

**Comment by per-samuelsson** [comment]
Workarounds until we can nail this for sure:

**Either**

1. Close VS.
2. Set environment variable `SC_LABS_JSON_CODEBEHIND_MONO_PARSER=True`
3. Open VS / project again. Build should now be possible.

**or**

1. Close VS
2. Download https://www.nuget.org/packages/System.Collections.Immutable/1.1.37 and https://www.nuget.org/packages/System.Reflection.Metadata/1.2.0.
3. Copy the dlls in those packages into %StarcounterBin% folder (normally `C:\Program Files\Starcounter`).
4. Open VS / project again. Build should now be possible.

**Comment by miyconst** [comment]
For me this issue has gone after installing Visual Studio 2015 Update 2.

**Comment by per-samuelsson** [comment]
> For me this issue has gone after installing Visual Studio 2015 Update 2.

Really? And you experienced this before that, and it appeared in a version during the latest days?

**Comment by per-samuelsson** [comment]
> When you have a minute @mattiasmak, could you please open a "Developer command prompt for VS2015" and run the following?

```
gacutil /l System.Collections.Immutable 
```

Here's my result of that:

```
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL

Number of items = 1
```

And here's the result from one of our build servers, where we've seen this failure:

```
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL

Number of items = 1
```

Not sure what to make of that though, and even more so since I think it fails not always on that machine either.

**Comment by miyconst** [comment]
>Really? And you experienced this before that, and it appeared in a version during the latest days?

I experienced this issue when tried to build a solution with `msbuild Solution.sln`. Trying to build same solution from Visual Studio worked. Installing Update 2 solved the issue when using `msbuild` as well.

I never met this exception before, just today trying to run latest Starcounter on a Windows 10 machine with VS2015 without updates.

**Comment by per-samuelsson** [comment]
> I experienced this issue when tried to build a solution with msbuild Solution.sln. Trying to build same solution from Visual Studio worked.

That's just weird. Thanks for sharing that. VS claim to build using just `msbuild` underneath, but your story indicates something else.

I also got the impression @mattiasmak built using VS. Let's see what feedback we can get from there. Meanwhile, I'm trying to learn more.

**Comment by per-samuelsson** [comment]
The more I'm reading about it, the more it seem this problem is related to how MsBuild work, and that for some reason, this reference does not always work. Still have no idea under what circumstances though.

Here's someone with problems previously relating to references not resolving:
http://stackoverflow.com/questions/23918413/msbuild-requiring-dll-to-be-copied-to-both-net-directory-and-current-build-dire?rq=1

**Comment by alemoi** [comment]
Just to let you know the develop daily started to constantly fail on scbuildserver2 so I added the env var `SC_LABS_JSON_CODEBEHIND_MONO_PARSER=True`.

**Comment by chrhol** [comment]
> Just to let you know the develop daily started to constantly fail on scbuildserver2 so I added the env var SC_LABS_JSON_CODEBEHIND_MONO_PARSER=True.

I get the same problem on scbuildserver now. My three last personal builds failed with this error. Have anything changed, or why did it suddenly start happening?

**Comment by alemoi** [comment]
> Have anything changed, or why did it suddenly start happening?

Not that I am aware about. I will do the same procedure for `scbuildserver`.

**Comment by per-samuelsson** [comment]
This is just nuts, and I can't figure out what the fuck is happening. I mean, really. How can a framework dependency that clearly worked several times before just *stop* working?

**Comment by alemoi** [comment]
And moreover it stopped working on several machines simultaneously. Maybe its Nuget related things? Because it tried to fetch a different version before?

**Comment by per-samuelsson** [comment]
I think I actually have a clue on why it acts so randomly at least - I think it's an ordering thing, and that MsBuild fail because of that.

I took a closer look at the build script and noticed we use MsBuild with the `/maxcpucount` and this is [notoriously error-prone](https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=msbuild%20maxcpucount%20fails) (I've read about weird failures over and over when that one has been in use).

Then I went on and built locally using the same command-line as is used by our build servers:

> MSBuild.exe "/Level1/src/Level1.sln" /p:Configuration=Release /maxcpucount /verbosity:minimal

and it just goes bananas over and over.

On my machine, it fails constantly if I make builds *close in time* and that is for sure because of how MsBuild reuse nodes, in combination with that Level1 both build **and** use `Starcounter.MsBuild.dll`, which is just a guarantee for random weird failures. Why? Because sometimes, one node will keep that file locked while another node want to build it. Then we get errors like this (from my env):

```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): error MSB3027: Could not copy "obj\x64\Release\Starcounter.MsBuild.dll" to "..\..\bin\Release\Starcounter.MsBuild.dll". Exceeded retry count of 10. Failed. [C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.MsBuild\Starcounter.MsBuild.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): error MSB3021: Unable to copy file "obj\x64\Release\Starcounter.MsBuild.dll" to "..\..\bin\Release\Starcounter.MsBuild.dll". The process cannot access the file '..\..\bin\Release\Starcounter.MsBuild.dll' because it is being used by another process. [C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.MsBuild\Starcounter.MsBuild.csproj]
```

I'm not sure exactly why it started to appear more frequently when I recently changed to use Roslyn-based parser, but I'm 99% sure now this is the cause of this problem.

**Comment by per-samuelsson** [comment]
@alemoi, do you mind if I turn paralell building off for Level1 specifically, and maybe just for a day or so to see if it solves it? For both main branches.

**Comment by per-samuelsson** [comment]
```
Project "\Level1\src\Starcounter.Bootstrap\Starcounter.Bootstrap.csproj" (9) is building
"\Level1\src\Starcounter.MsBuild\Starcounter.MsBuild.csproj" (24) on node 4 (default targets).
```

Here's an example of the weirdness going on (when I'm running parallelt builds): Bootstrap project trigger (and run) building of MsBuild project, because it depends on that task (because, in turn, it contains Typed JSON with code-behind), and if that runs while that project build on another node, well, then trouble occur. :smile:

**Comment by per-samuelsson** [comment]
> @alemoi, do you mind if I turn paralell building off for Level1 specifically, and maybe just for a day or so to see if it solves it? For both main branches.

I've set this up now in a dedicated branch of the build system, and I will run it on different builds and agents tonight and tomorrow. Let's see if it fixes this.

If anyone else want to run it, just set `env.GIT_BUILDSYSTEM_BRANCH` on the build server to `issue/3666` and it will use single-node builds when building Level1.

**Comment by alemoi** [comment]
> @alemoi, do you mind if I turn paralell building off for Level1 specifically, and maybe just for a day or so to see if it solves it? For both main branches.

Of course, please do! It just increases the build time a bit but no other drawbacks.

**Comment by per-samuelsson** [comment]
This just keep getting more weird.

Last night, when I triggered a build using single-node MsBuild, Level1 failed because it can't locate a reference to *PostSharp*?!

`
[Step 1/1] C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "PostSharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\BuildAgent\work\sc-develop-daily-1780\Level1\src\scweaver\scweaver.csproj]
`

and then

`
CodeWeaver.cs(8,7): error CS0246: The type or namespace name 'PostSharp' could not be found (are you missing a using directive or an assembly reference?) [C:\BuildAgent\work\sc-develop-daily-1780\Level1\src\scweaver\scweaver.csproj]
`

I mean what is *that*? Even if one idea was that this had to do with our new Roslyn-introduction or even the introduction of `NuGet` 3.x, we don't use NuGet to locate PostSharp binaries, do we? Those we just copy from our corporate server, no?

**Comment by per-samuelsson** [comment]
> Last night, when I triggered a build using single-node MsBuild, Level1 failed because it can't locate a reference to *PostSharp*?!

Turns out this one is very likely consistent, both accross runs and on different agents. At least I've got the same error on like 5 straight builds, when building with a single (non-parallel) MsBuild node.

I'm quite sure this one has to do with another long-time flaw of MsBuild: that [building solution files with MsBuild does not guarantee the build order](https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=msbuild%20solution%20project%20build%20order). MsBuild simply doesn't know about (and respect) those dependencies setup within a solution. 

It seem even to be a known flaw in the most recent MsBuild, and one they don't have a solution for, as is hinted in this recent issue: [MSBuild.exe orders the build incorrectly when using a solution file](https://github.com/Microsoft/msbuild/issues/421).

What this means for us, in the context of Level1, that we are kind of trapped in a catch 22: if we build in parallel, things will *normally* work, but will fail from time to time because we are using our own MsBuild task within the build. And if we switch to single-node MsBuild building ("single threaded") to cure that, we get bitten by the above.

**Comment by per-samuelsson** [comment]
If going back to the original problem here, it's pretty clear for me now we are suffering from something that others have suffered from too, including MS themselves; examples [here](http://atmel.force.com/support/articles/en_US/Workaround/Installing-Visual-Studio-2015-Update-1-leads-to-Atmel-Studio-no-longer-starting) and [here](https://github.com/aspnet/EntityFramework/issues/2855).

The cause of it is that when we introduced Roslyn dependency (#3439) recently, those bits require `System.Collections.Immutable 1.1.37`, while on those servers where we've seen this fail, the GAC contains version `1.1.36`.

Doing `gacutil /l System.Collections.Immutable` on my machine shows `1.1.37`, while when I'm doing it on our build servers, I get

```
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL

Number of items = 1
```

**Comment by per-samuelsson** [comment]
Based on the above comment, I'm pretty sure the missing piece here what @miyconst commented on:

```
Installing Update 2 solved the issue when using `msbuild` as well.
```

My guess would be that Update 2 upgrade that assembly to `System.Collections.Immutable 1.1.37` and then resolving it works.

I have confirmed one of the build servers this fail on does *not* have Update 2.

**Comment by per-samuelsson** [comment]
One alternative to solve this could be to take a chance and see if our code-behind parser could use an older version of Roslyn. I've tracked down their history to the point where they only used `1.1.36` of `System.Collections.Immutable`, but then we are back at [1.0.0, November 2015](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/1.0.0).

The other way would of course be to force end-users to have the latest bits in the .NET framework, by applying something like VS Update 2. But I'm not sure how feasible that is, and neither what it means for those that still use 2013 (which we still support in the installer at least).

**Comment by per-samuelsson** [comment]
Another alternative I intentionally haven't brought up is to redistribute those assemblies Roslyn depend on - `System.Collections.Immutable` and `System.Reflection.Metadata` - locally (having them in our installation).

Problems doing so:

1. Is it legal (I think it is, but need to make sure)
2. We use Roslyn inside our build task, which in turn runs inside MsBuild/VS, and we can not be sure we get a first time option to load them; any of those hosts can (and I've seen them do) load them before us, and then if versions are incompatible, we are back to square 1.

**Comment by per-samuelsson** [comment]
Think I have finally nailed this one, merged and pushed in https://github.com/Starcounter/Starcounter/commit/b8507629279517d1f3ec04d5bcb20d861738fa28 to develop. I'll merge it to **pnext** right away.

**Comment by per-samuelsson** [comment]
> I'll merge it to **pnext** right away.

Done.
