### ISSUE TITLE
'Starcounter.Session.ToAsciiString()' is obsolete: 'Please use SessionId property instead.

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3668]
Didn't you change it in the other direction just some month ago?
Should I update our code again?

**Comment by miyconst** [comment]
@malx122 I am sorry for the inconvenience.

The `ToAsciiString()` was introduced as a part of a big code refactoring, @alemoi knows more. Then `SessionIdString` got obsolete, but from the client side point of view `ToAsciiString()` is the same as `SessionIdString`.

The `SessionIdString` is a bad name itself, that is why we renamed it to be just `SessionId`. I hope there will be no more changes in this part.

**Comment by malx122** [comment]
What?
I do not understand the answer.
`SessionIdString` got obsolete and replaced by `ToAsciiString() `but since the now obsolete `SessionIdString` is a bad name its renamed to `SessionId` and not obsolete any more?

But the important this is that I use the right one now. I will change everything to `SessionId` and hope that is correct!

**Comment by miyconst** [comment]
>But the important this is that I use the right one now. I will change everything to SessionId and hope that is correct!

Yes, please do so.
