### ISSUE TITLE
ScErrAnotherSessionActive: Another session for this thread is already active.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3672]
Found by @malx122.

This happened when having a background job running that creates some data, which in turn have a commithook that schedules a task on a session to push updates.

The exception is thrown because there already is another session active on the same thread (which should, in normal circumstances, never happen). 

```
System.Exception: ScErrAnotherSessionActive (SCERR5007): Another session for this thread is already active.
Version: 2.2.1.2230.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR5007.
```

It's not easily reproduced. I've been trying but not managed to get it. So we will keep an eye on it and see if we can come up with a way, and after that find out why this happens.

**Comment by dan31** [comment]
@alemoi @per-samuelsson what do you think?

**Comment by per-samuelsson** [comment]
> @per-samuelsson what do you think?

On my part, I have no clue unfortunately. Just recently, I tried to step through code that create / assign sessions, described in [this comment](https://github.com/Starcounter/Starcounter/issues/3575#issuecomment-221688632), but it's really not something simple, and does *a lot* of stuff, so just based on that, I'd guess there is something going on in there.

Sorry I can't be of better help.

**Comment by alemoi** [comment]
Is there a stack trace for the place where it occurs?

**Comment by miyconst** [comment]
This exception happened to me a couple of times when I tried to created multiple sessions by a mistake.

**Comment by chrhol** [comment]
This doesn't seem to occur anymore. I will close this issue for now.
