### ISSUE TITLE
Upgrade Polymer to version 1.5

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3673]
Yesterday Polymer 1.5 was released. Update the version bundled with Starcounter.

Instructions (freshly written by me) are here: https://starcounter.gitbooks.io/rebelslounge/content/client-side_libraries.html

Note that point 5. from the instructions might be not doable before https://github.com/Starcounter/Starcounter/issues/3666 is fixed. At least my personal builds don't work ATM.

**Comment by dan31** [comment]
@warpech do you suggest not to include Polymer 1.5 into 2.2.1 release? I have an agreement with customers awaiting on 2.2.1 that the fixes included are good and 2.2.1 can be released. However there are a couple more bugs left to address. Do you think 1.5 in 2.2.1 will be disruptive for them, or not likely?

**Comment by warpech** [comment]
Release notes for Polymer 1.5 show nothing disruptive. We should avoid lagging behind the Polymer releases.

Only if there is less than a week until 2.2.1, I would skip upgrading Polymer.

**Comment by warpech** [comment]
Test plan:

1. test locally in some apps (e.g. Chatter + Images + Launcher)
2. test locally in Selenium tests:
- Launcher
- KitchenSink
3. test locally in Web Component Tester:
- puppet-polymer-client
- starcounter-include
- imported-template
- juicy-html
4. test on build server

After all 4 points pass, let's put it to Starcounter develop.

**Comment by aloscha** [comment]
1. Passed for Chatter + Images + Launcher and Products + Launcher
2. Fails

      OpenQA.Selenium.WebDriverTimeoutException : Timed out after 10 seconds
         at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
         at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
         at KitchenSink.Test.ButtonPageTest.ButtonPageTest_DisabledButton() in C:\Users\aloscha\Documents\KitchenSink\test\KitchenSink.Tests\Tests\ButtonPageTest.cs:line 135

**Comment by warpech** [comment]
Re 2: Is it something that passes in 1.4 and fails in 1.5?

**Comment by aloscha** [comment]
I think not, It's just an observation (it's timeout), I recheck with 1.4 and write down result (also test rest cases)

**Comment by aloscha** [comment]
2. The same result in 1.4.0 and in 1.5.0, so KitchenSink code fails, not error by updating polymer.

**Comment by warpech** [comment]
> Re 2: The same result in 1.4.0 and in 1.5.0, so KitchenSink code fails, not error by updating polymer.

Agreed. I have created an issue for that: https://github.com/StarcounterSamples/KitchenSink/issues/52

Since that test fails in Edge only, this will not affect build server.

**Comment by aloscha** [comment]
For me all tests pass, just wait for build server tests

**Comment by warpech** [comment]
What's the status of it? Can it be merged today?

**Comment by aloscha** [comment]
All tests passes, I've already merge it into `pnext` and waiting for nightly build.

**Comment by warpech** [comment]
Closing as the job is finished. @malx122 please feel free to test it in the next nightly. We have not observed any important differences.
