### ISSUE TITLE
Improve documentation on ObjectID

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3685]
The page [Object identity and object references](http://starcounter.io/guides/database/object-identity/) should tell what is the used format for `ObjectID` value and what kind of strings to expect in there.

**Comment by miyconst** [comment]
@alemoi is it something you can help me with?

**Comment by alemoi** [comment]
No sorry, I am not the best person to describe ObjectId. CC @k-rus @per-samuelsson

**Comment by eriohl** [comment]
Base64 formatting of "object no".

**Comment by miyconst** [comment]
Then we can't use it as a URL parameter. [Base64](https://en.wikipedia.org/wiki/Base64) format includes `/` and it has different meaning in the URL.

Looking at the `Base64Int` class implementation I see that we use some other format for `Base64`, which excludes the `/` sign.

Need some clarification, why it's called `Base64` while not the same as the standard.

**Comment by eriohl** [comment]
"Base 64 Encoding with URL and Filename Safe Alphabet" then. Also part of standard.

**Comment by miyconst** [comment]
Okay. So, the answer is that `ObjectID` is `URL Base 64` encoded `ObjectNo`. I will update the documentation.

**Comment by eriohl** [comment]
Well, it supposed to be. Maybe double-check the code that it adheres correctly to this standard.

**Comment by miyconst** [comment]
The source code checked, the documentation has been updated. Closing the issue.
