### ISSUE TITLE
Question : What is the table name of "MaterializedIndex" in SC Version 2.3.1657?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3695]
The query `SELECT i FROM MaterializedIndex i` works fine in SC Version 2.2.1.2237, but not in SC Version 2.3.1657

**Comment by per-samuelsson** [comment]
@atifwaqar 

This is one of the areas that has changed quite a lot between versions 2.2 and 2.3. Metadata has been extended and changed a lot.

Let's see if @k-rus can answer.

**Comment by atifwaqar** [comment]
Its ok, I have switched back to SC 2.2.
I noticed some DB images change as well. and it looks like upgrading from 2.2 to 2.3 will be quite a struggle. So we can wait a bit for 2.3 to get stable.

**Comment by k-rus** [comment]
Thank you for the question. Any materialised tables are not supported and should not be used in any 2.x version. For the purpose of index table `Starcounter.Metadata.Index` should be used. The change was made few years ago and issue describing the changes exists somewhere, but I cannot find it. The documentation will come, but there will be more changes in metadata schema.

**Comment by k-rus** [comment]
Very limited documentation can be found in [this answer](http://stackoverflow.com/a/39490683/840340)
