### ISSUE TITLE
Custom constructors are not currently supported in typed json (BindHelper)

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3696]
I have a private helper class withing a typed Json. The constructor check should ignore inner classes that don't inherit json

````
partial class WorkstationSubGroupInfo : Json, Starcounter.IBound<WorkstationSubGroupViewModel>
{
    void Handle(Input.IsMember isMember)
    {
        var vm = Data as WorkstationSubGroupViewModel;
        
        if (vm != null)
        {
            var bindHelper = new BindHelper(vm, isMember);
            bindHelper.Ask(); 
        }
    }

    private class BindHelper
    {
       public BindHelper(WorkstationSubGroupViewModel vm, Input.IsMember isMember) { ... }
    }
}
````

**Comment by chrhol** [comment]
Thank you for reporting this. Which version do you use of Starcounter?

**Comment by per-samuelsson** [comment]
> The constructor check should ignore inner classes that don't inherit json.

The problem today (even after switching to Roslyn) we have no context to traverse the tree, so we can't tell for sure if a class derive Json or not.

We should ignore it if it doesn't map to a JSON hive though. I'm surprised we don't already. That's a bug.

And @careri,

```cs
void Main() {
  Console.WriteLine("Syntax highlighting looks nice, especially on a friday!");
}
```

Just saying. :wink:

**Comment by careri** [comment]
I'm using 2.2 stable.

Hehe, I'll look into how to use syntax highlightning :)

BTW, I turned the inner class into a struct, that worked

**Comment by chrhol** [comment]
> I'm using 2.2 stable.

Then you're not running the new parser for code-behind (based on Roslyn). I will test it in the latest version and see if this bug is fixed already.

**Comment by chrhol** [comment]
This seems to be working fine in the latest version. Since you found a workaround in the version you use, and it's solved in later versions I will close this issue.

**Comment by miyconst** [comment]
>Hehe, I'll look into how to use syntax highlightning :)

It's very easy, when you define a code block add the language after it's name like:

- \```cs
- \```js
- \```json
- \```css

**Comment by careri** [comment]
Thanks @miyconst

**Comment by careri** [comment]
Version: 
We'll my internal struct is no longer allowed to have a constructor. Damn it!
Starcounter-DevelopNightlyBuilds-2.2.1 (20 sep 2016 04:34:45)
