### ISSUE TITLE
DbSession obsolete

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3707]
I'm not quite certain that replacing DbSession with Scheduling.ScheduleTask is a great idea?

That forces me to have an instance of Starcounter.Session, which seems to be a client oriented session with Json references etc.

It should be possible to run database tasks without a client session instance

**Comment by chrhol** [comment]
There are two different methods to use to schedule a task, `Session.ScheduleTask` and `Scheduling.ScheduleTask`. Only the first one requires a session. The second one only takes the delegate  to execute, and is not connected to a session in any way.

**Comment by careri** [comment]
Ah, missed that one. Thanks
