### ISSUE TITLE
Writable view-model without Db.Scope

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3709]
Is it possible to get a writable view-model outside of `Db.Scope` with automatic `Db.Transact` execution on data change?

cc @chrhol

**Comment by chrhol** [comment]
No, automatic handling of transactions only works with `Db.Scope` currently. What is the exact reason for having an automatic `Db.Transact` instead of committing the long-running transaction each time? Do you want conflicts?

**Comment by miyconst** [comment]
> ...  instead of committing the long-running transaction each time?

How to do that?

**Comment by chrhol** [comment]
> How to do that?

There is a method that can be overriden in the code-behind, `protected void HasChanged(TValue property)` which is called every time a property is updated. There you can call `this.Transaction.Commit()` to enable autocommits. But you will get no conflicts from this, of course.

**Comment by miyconst** [comment]
Thanks @chrhol! I will try it out.
