### ISSUE TITLE
Session thread?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3714]
Is there any way of figuring out if the current thread is executing within a Session?

In my applicaiton the same method can be triggered either by an evaluation of a property within a json-session. Or by updating a database-property, say that it's a poll loop looking for changes.

If the method is called from a json-property there is no need to call 
```cs 
Starcounter.Session.Current.CalculatePatchAndPushOnWebSocket
```

But if the call is made from a db-change the thread isn't connected to a json-session. Is it enough to check if Current is null?
```cs 
Starcounter.Session.Current
```

**Comment by chrhol** [comment]
>  Is it enough to check if Current is null?

Yes, that should work. `Session.Current` will always be set to the currently running session for that thread.

**Comment by per-samuelsson** [comment]
@careri 

Does that answer your question fully? If so, can you close this issue?
