### ISSUE TITLE
Add version number to Starcounter.Layout

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Starcounter#3718]
As we are now moving towards completely different layout concept, previous layouts will not work with new code, even though we would like to store them in the same manner.

Therefore we need to store the version, to be able to filter those.

Naturally we need it, only if we would like to support new layouts still keeping old ones.

**Comment by warpech** [comment]
@alemoi could you pls help @tomalec with this?

**Comment by alemoi** [comment]
Yes, sure! Just describe what exactly field should be added there of what type? String version? Or Int32 version?

**Comment by tomalec** [comment]
`.Version` with SemVer is tempting, so we could keep it in line with `starcounter-include`, but Int32 is fair enough so far, and probably way faster and easier to handle.

**Comment by alemoi** [comment]
I looked at the code @tomalec @warpech and have a few questions to you guys:
I can of course add `Int32 Version` to the `Layout` but need to know how you are going to access the field. Right now the `Value` filed is a `Body` in `/sc/layout` handlers (either POST body request or GET body response).

What about having `Body` as a Json instead?:
```
{
   "Value":"blabla",
   "Version":123123
}
```

**Comment by alemoi** [comment]
At the same time, if I change the layout to be Json (instead of pure body = `Value` as today), than it breaks backwards compatibility. Client and server commits have to be synchronized also.

**Comment by alemoi** [comment]
Here is the code I am talking about: https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.Extensions/Layouts.cs

**Comment by tomalec** [comment]
I think, all we need is to select layout using version, we do not need to fetch version - I suspect Launcher will use only one version at a time (not to over-complicate things).

So we would need 
```c#
Handle.[POST|GET|DELETE]("/sc/layout?key={?}&v={?}", (Request request, string key, Int32 version) 
```
if version is not given it will pick the last one.

Then, it may return it as currently.

**Comment by warpech** [comment]
I have a reflection on this. Would you agree that `v` (or `version`) can mean so many different things:

1. API version
2. resource version

And actually we don't mean either of that. We mean **3. resource schema version**.

Wouldn't it be simpler to put the resource schema version as **part of the key**? Then we leave the `v`/`version` concept for some future use (for API versions or resource versions)

**Comment by alemoi** [comment]
Interesting suggestion! Then no server changes are needed! What do you think @tomalec

**Comment by tomalec** [comment]
Good catch @warpech.

We have already thought about versioning of layout resources (within same schema version), that's why, now I would say that `Version` in JSON should be reserved for __resource version__

I'm a little bit afraid adding version as a part of the key could make it confusing.

On the other hand, I thought about renaming "Layout" to "Composition". With full HTML structure it could be way more that layout, and it even does not have to deal with anything visual, as non-visual (custom-)element may be used, for example for A/B testing, speech recognition, etc.

Therefore, instead of adding version number to `Starcounter.Layout` we could add `Starcounter.PartialComposition` (naming related to https://github.com/Starcounter/Starcounter/issues/3538). Then, the new `starcounter-include` will use new API, and will not use old JSON layouts as HTML strings - which I believe was the main reason to introduce version here.

However, some day we still may get the problem of resource schema change, so the need for the version number.

**Comment by alemoi** [comment]
Yes, adding a new class will not break the existing apps. I can add the class, even with the version in there. Can we have a meeting about this, so we decide?

**Comment by tomalec** [comment]
Sure, just say when.

**Comment by alemoi** [comment]
I have added initial support as we discussed, some things might not work, so lets test it with your stuff @tomalec. The `Version` field I made a string for now because of reusing same handlers, just easier, e.g.: `GET /sc/partialcomposition?key={?}&ver={?}` where `ver` can be an empty string.
So the API is: 
`GET /sc/partialcomposition?key={?}&ver={?} ` returns `Value` in the response body.
`POST /sc/partialcomposition?key={?}&ver={?}` sends `Value` in the request body.
`DELETE /sc/partialcomposition?key={?}&ver={?}`
`GET /sc/generate/partialcomposition/{?}` gets appname as parameter (not sure if this one is used).

**Comment by tomalec** [comment]
LGTM :) thanks!

**Comment by tomalec** [comment]
I've just get a doubt regarding naming...

_PartialComposition_ - means it's rather part of composition,
It should be rather _Partial's Composition_? In view-model, `instanceOfPartial.Composition` looks good. but how we can achieve `'` in C# class name? _"PartialsComposition"_ would suggest sommething different - composition build of many partials.

Can we use `Starcounter.Partial.Composition`?
(https://github.com/Starcounter/Starcounter/issues/3538)

**Comment by alemoi** [comment]
I now enclosed the class into namespace and changed URIs ("/partialcomposition" -> "/partial/composition"). Going to push tonight.
