### ISSUE TITLE
Question : How to restrict access of SC Admin Panel 

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3721]
(Note : I remember I have posted this question before but i can not find it now, so I'm re-posting it, please ignore this if its a duplicate.)

We can access SC Admin Panel by going to `http://[server-ip]:8181/#/databases/default/sql`. Which is kind of dangerous when we have it on a live server, because anyone can come to this link and can manipulate our DB data, or even delete the records from DB.
So my question, Is there a way to set some login to access Admin Panel? One way is to block port 8181, but the issue is, when ever I upgrade SC, it reopens the ports, and sometimes I forget to re-block the ports. 

Drawback of blocking the port 8181 : 
1. If I need to access the Admin Panel, I have to access the server via remote desktop. 
2. Sometimes I have to compare some data from 2 of my servers. In that case I have to keep switching between my Remote Desktops.
3. Sometimes multiple developers have to work on SC Admin Panel. and with Remote Desktop we can have only 1 login at a time.

**Comment by dan31** [comment]
@bigwad is this the installer which reopens the ports?
CC @alemoi @andwah

**Comment by atifwaqar** [comment]
@dan31 Sorry, my bad.
I just confirmed from my network admin. Installer do not reopens the ports.

**Comment by dan31** [comment]
@bigwad sorry for typing in your name :)
@atifwaqar thanks for confirming! I will close it now.

**Comment by atifwaqar** [comment]
@dan31 The question is still there, is there a way to restrict access of SC Admin Panel with a user login?

**Comment by dan31** [comment]
@atifwaqar currently there is no such plan to support admin panel's sign-in in the run of next releases, however, even presented, the recommended way is to always protect the main admin panel in hard way and do administration through a secure tunnel. This is applicable to any software product with web panel. I recommend not to open admin panel at all, or at least to route and hide the port beyond an ```nginx auth_basic port``` as soon as possible. Btw I can show you sometime in August, if you won't manage to fix it yourself before.

**Comment by atifwaqar** [comment]
Ok. For now I have blocked the port for public network, and created an VPN for my servers. Now i can access the port 8181 only on my VPN. 
Thanks for the info. :)
