### ISSUE TITLE
pnext: it's possible to commit two objects with the same object id, though hopefully not at the same time

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3722]
Optimized log doesn't keep track of latest allocated object id. 

Hence consider the scenario:
1. Create an object.
2. Remove the object created in p1.
3. Perform logopt.
4. Restart database.
5. Create an object.

Objects created will share the same object id.

**Comment by eriohl** [comment]
This is a bug. Optlog files already stores next record id for this purpose. Not sure why it is not set properly after load but it should be.

(Should double check also that this value is properly transferred when creating a new optlog file from a previous optlog file.)

**Comment by bigwad** [comment]
fixed by https://git.starcounter.org/BlueStar/level0/commit/0f51c90d7c48b31e1a9a6e4e7e0906dfe4d772dd
