### ISSUE TITLE
Unable to stop a database with custom name from CLI

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3723]
I am trying to stop a database called `mm` from command line:

```
C:\Users\IEUser>staradmin stop db mm
Stopping default                                                                                                        
ScErrDatabaseNotFound (SCERR10002): A database with the specified name was not found. Database: "default".
Version: 2.2.1.2631.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10002.

Type "star -h" to see help
Type "star 10002" to launch the help page for error 10002
```

cc @andwah, @per-samuelsson

**Comment by k-rus** [comment]
I think it is incorrect use of `staradmin`. It should be:
```bash
staradmin -d=mm stop db
```

I was also confused, but it is not a bug and our manual contains correct description.

**Comment by miyconst** [comment]
@k-rus thank you for the answer. You are right.

**Comment by per-samuelsson** [comment]
Also, we have a related issue where we plan to improve this, but we never prio'd it: #3000.

Also somewhat related #3489.

**Comment by dan31** [comment]
Guys, I confirm we'd likely prioritise that story even in 2.x track. I constantly have difficulties with the current syntax (the current way doesn't resemble any typical way I might know of from other CLI tools on *nix, thus I don't memorise ours), and recently @okostina had the same difficulties with using CLI tools.

**Comment by per-samuelsson** [comment]
> Guys, I confirm we'd likely prioritise that story even in 2.x track.

OK, lets treat these related ones in a batch. I'm not sure exactly how though, since even if the supported CLI syntax today is not as intuitive as we'd like it to be, it's still *consistent*. How to still achieve that *and* be backwards-compatible is a challenge.

@dan31, what timeframe are you thinking on here? Is August fine, or should we bump it even more?
