### ISSUE TITLE
Strange behavior of SC Databasae

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3728]
1. When I Stop any of my 4 apps, my DB gets unloaded, and then reloads again, which takes some time.
2. The SC Icon in `Icon Tray` is not showing the correct status. Sometimes the DB is loaded and running, but the Icon stays gray and if I right click on it, it shows an option `Start Server`

**Comment by dan31** [comment]
@atifwaqar do you currently run cbwatchdog on this machine?

**Comment by dan31** [comment]
CC @alemoi please be in a loop if @atifwaqar needs follow up.
I think @atifwaqar meant that the codehost stops and then starts, not that db is unloaded (which is a very different thing).

**Comment by atifwaqar** [comment]
@dan31 I had to stop the cbwatchdog, because nothing was working. apps were behaving very strange. 
but I will give it a try again tomorrow. 

> I think @atifwaqar meant that the codehost stops and then starts, not that db is unloaded (which is a very different thing).
I'm not sure about the difference, I just monitored the RAM. When I stop AdFenix app, the RAM gets freed up and only 1.5 GB is in use at that point, then it starts getting full, and when its 14 GB acquired, The app disappears(/Stops) from SC Admin Panel.

**Comment by alemoi** [comment]
> When I Stop any of my 4 apps, my DB gets unloaded, and then reloads again, which takes some time.
The SC Icon in Icon Tray is not showing the correct status. Sometimes the DB is loaded and running, but the Icon stays gray and if I right click on it, it shows an option Start Server

Yes, we probably talk about the codehost here.
Regarding the trayicon it has a polling interval, when it fetches the state of databases. But that seems to be a different issue. CC @andwah 

How much memory do you have totally? Maybe it gets completely eaten up, so the codehost and other components start to behave strange?

**Comment by atifwaqar** [comment]
I have 64 GB of memory, which is more than enough for my DB

**Comment by dan31** [comment]
@atifwaqar any log record for that? And which exactly version do you run?

**Comment by dan31** [comment]
@atifwaqar hi! Any fresh news on this?

**Comment by atifwaqar** [comment]
@dan31 
Sorry for the late response. I was trying to understand the behavior. In the latest nightly build, it looks like the behavior is back to normal. so I started your CB WatchDog. It works fine, but sometimes, if i stop any one of my apps, CBWatchDog does not start the app. even if I restart the CBWatchDog.

**Comment by atifwaqar** [comment]
SC Version : 2.2.1.2709
Ok this is strange. I just experienced the same behavior again on the server where we have CBWatchDog running.
1. I stopped AdFenix from SC AdminPanel
2. Ram Dropped and started filling again
3. I was expecting that CBWatchDog will run AdFenix exe but it didnt
4. I restarted CBWatchDog, just to check if it takes any action to start the AdFenix app, but it did nothing
5. I ran "Run.bat". this file runs AdFenix.exe on all other servers. but its not working on this server (Do you think its cuz of CBWatchDog?)
6. I used http://localhost:8181/#/databases/default/executabeStart to start AdFenix and it worked.
