### ISSUE TITLE
Stack exception in the 2.3 installer when upgrading from any version

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3743]
I have Starcounter 2.2.1.2657 (`develop` nightly). 

When trying to install 2.3.2083 (`pnext` nightly), I get the following error message with a stack exception inside of it:

![2016-07-13 14_50_30-starcounter installation](https://cloud.githubusercontent.com/assets/566463/16803955/8ee6627a-4909-11e6-9bcb-a06bc5075111.png)

Clicking "Yes" and "No" works as expected.

**Comment by aloscha** [comment]
If in some reason, you don't get this notification, installed pnext and start debugging app you received unexpected error, you should:
1. Uninstall SC
2. Remove Starcounter folder from ProgramFiles
3. Remove Starcounter folder with older database from Documents

**Comment by warpech** [comment]
Still happens for me, but now actually the error message asked me if i want to "downgrade":

```
Would you like to downgrade Starcounter v2.2.1.2998 to v2.3.3675?Error occurred during verification of existing database image files versions.
Please follow the instructions at: 
https://github.com/Starcounter/Starcounter/wiki/Reloading-database-between-Starcounter-versions 
to unload/reload databases.
Error message: System.NotSupportedException: The image file API's are not supported in 2.2. See this post: https://github.com/Starcounter/CompanyTrack/issues/120#issuecomment-157342000
   at Starcounter.Server.ImageFile.Read(String directory, String databaseName)
   at Starcounter.InstallerWPF.InitializationWindow.CheckExistingDatabasesForCompatibility(List`1& dbListToUnload)
   at Starcounter.InstallerWPF.InitializationWindow.IsAnotherVersionInstalled(InstallationSettings& previousSettings)
```

The pnext and develop nightly builds were done in the same night:

```
2.2.1.2998 (Aug 31, 2016 5:08:10 AM)
2.3.3675 (Aug 31, 2016 2:01:05 AM)
```

Screen:

![2016-08-31 13_50_05-starcounter installation](https://cloud.githubusercontent.com/assets/566463/18127665/1d908994-6f82-11e6-939e-071c87157b7a.png)

**Comment by warpech** [comment]
Still happens to me, even when upgrading from 2.3 to 2.3:

![2017-01-03 17_59_41-starcounter installation](https://cloud.githubusercontent.com/assets/566463/21615625/96627904-d1de-11e6-8e67-999cd68310be.png)

**Comment by mmnosek** [comment]
@warpech  Here is possibly already assigned duplicate: https://github.com/Starcounter/Starcounter/issues/3843

**Comment by alemoi** [comment]
This is the things we discussed today on the meeting: only manual reload is possible between 2.2 and 2.34. We just need to write a proper dialog message and no stack trace. @ubbeK can you please post the link to your migration app for 2.2.

**Comment by warpech** [comment]
Please note that this error appears also when upgrading from `2.3.(n-1)` to `2.3.n`

**Comment by ubbeK** [comment]
Source code: https://github.com/Starcounter/StarDump.Migrator.2.2

There is a version in the old warehouse but it is not updated with the latest since it needs some testing.

**Comment by warpech** [comment]
The problem is still reproducible when upgrading from yesterday's RC to today's RC using the instructions from https://github.com/Starcounter/Starcounter/issues/3743#issuecomment-270164216

**Comment by warpech** [comment]
The problem is still reproducible when upgrading from yesterday's RC to today's RC using the instructions from https://github.com/Starcounter/Starcounter/issues/3743#issuecomment-270164216

![2017-02-17 13_50_47-starcounter installation](https://cloud.githubusercontent.com/assets/566463/23065903/1f771a40-f518-11e6-9e4d-720638ddff30.png)

**Comment by dan31** [comment]
On Monday @andwah is on it. Thanks @warpech for additional attention.

**Comment by andwah** [comment]
Stacktrace and Database Compability check removed,
