### ISSUE TITLE
Starcounter.Json as an anonymous response is not merged

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3755]
Since the last JSON merging rework we can use `Starcounter.Json` instead of `Starcounter.Page`, but this does not work with anonymous (substitute) handlers.

### App Playground

```cs
this.AnonymousPage = Self.GET(UriMapping.MappingUriPrefix + "/playground-anonymous-page", () => new Json());
```

### App Subground

```cs
Handle.GET("/subground/anonymous", () => {
    return = new SubPage() {
        Data = null,
        Session = Session.Current
    };
});

UriMapping.Map("/subground/anonymous", UriMapping.MappingUriPrefix + "/playground-anonymous-page");
```

The `this.AnonymousPage` object is always sent as `{ }` to the client. If I replace `Json` with `Page` then it works as expected.

Also the `OnJsonMerge` callback is called properly with two items in the `IEnumerable<Json> partialJsons`, but those items never reach the client side.

You can see the source code in my [Playground](https://github.com/miyconst/Playground/), see the commit attached to the issue.

cc @chrhol

**Comment by ubbeK** [comment]
:+1:

**Comment by chrhol** [comment]
I have reproduced it and have an idea what's causing it. If I'm correct it shouldn't be that difficult to fix.

**Comment by chrhol** [comment]
The problem was a shortcut in the jsonserializer that skipped some parts if no template was defined. I fixed this so that an empty jsonobject gets no special treatment in case it's a part of a merged result.

Pushed to develop and pnext.

**Comment by chrhol** [comment]
Let me know when you verified that it works as expected so I can close this issue :)

**Comment by miyconst** [comment]
Checked, works good! Thank you.

**Comment by chrhol** [comment]
Found another place, when gathering changes, which also suffers from this. Siblings are not checked properly. Will push a fix for it shortly.

**Comment by chrhol** [comment]
Pushed the fix to develop now. Will push it to pnext a bit later tonight.

**Comment by chrhol** [comment]
> Will push it to pnext a bit later tonight.

Which I didn't do. Pushed now though!

**Comment by miyconst** [comment]
Found another bug. See my [Playground](https://github.com/miyconst/Playground/) as usual.

- Start both apps: Playground and Subground.
- Open `http://localhost:8080/playground`.
- Click `Load sub page` button.
- It loads two responses from Playground and Subground.
- Click `Unload sub page`.
- It removes response from Playground, but keeps the one from Subground.

**Note:** the `Unload sub page` button replaced the partial with empty JSON like: `this.SubPage = new Json();`, when setting the value to NULL it works fine: `this.SubPage = null;`.

**Comment by miyconst** [comment]
@chrhol sometime ago you told me to empty JSON object by setting the value to `new Json()` because setting to `null` had some issues. Are those issues resolved now? How should I empty the JSON objects?

**Comment by chrhol** [comment]
Yes, this is how we implemented it. When simply replacing a partial json, the other partials are kept. Ideally you would only control your apps responses, not all other apps so I'm not sure what the bug is in this case. Maybe that setting it to null removes other apps responses?

**Comment by chrhol** [comment]
Just to clarify: Somewhere there is a bug or inconsistency, I'm not sure what the correct behaviour of this is.

**Comment by chrhol** [comment]
> @chrhol sometime ago you told me to empty JSON object by setting the value to new Json() because setting to null had some issues. Are those issues resolved now? How should I empty the JSON objects?

Since we dont support null-values, using null will produce undefined behaviour. It might work in some cases and in other not.

**Comment by miyconst** [comment]
I would consider it be a bug.

Replacing a JSON object with another value should replace app's own response with the value provided **and** responses from other apps with the one attached to the new value. If there is no values attached to the new value, then the old one should simply be removed.

It is ridiculous to do the following to just empty a JSON value.

```cs
this.SubPage = Self.GET("/empty-url", () => new Json());
```

**Comment by chrhol** [comment]
But then stateful partials will not work, which was the reason we added this behaviour in the first place...so we need to decide which features we want

**Comment by chrhol** [comment]
I would like to take a step back and decide how things should work before fixing anything more. Especially when it comes to merged partials beacuse there are a lot of vaguely defined behaviour now, and as seen we have some conflicting features.

**Comment by miyconst** [comment]
The last issue has been moved to it's track: https://github.com/Starcounter/Starcounter/issues/3786.

Closing this one.
