### ISSUE TITLE
pnext: Support in-memory compiler for kernel code generation on Linux

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3756]
Currently generated source files is stored on disk and shared libraries are built from them and then loaded into memory.

**Comment by eriohl** [comment]
This was not so difficult as I imagined since the in memory compiler seems to like pthread. So works after addressing some minor compiler issues.

However: Needs to fetch libscllvm.so as part of the build process. Could you help out with this @alemoi?

**Comment by alemoi** [comment]
Sure! I will try to find some time next week to add "\\scbuildserver\FTP\Temp\scllvm_linux\libscllvm.so" to the build system. How urgent do you need this?

**Comment by alemoi** [comment]
Maybe even tonight/tomorrow. I will do simplest way so that "libscllvm.so" is stored in git and copied in Linux to the output directory.

**Comment by alexanderstc** [comment]
I remember @alemoi once told me scllvm compilation was not thread-safe.
We should then make a bluestar-wide serializer for scllvm, since more than one subsystem is going to use scllvm: kernel and metalayer.
Or make scllvm tread-safe.

**Comment by alemoi** [comment]
Thanks for reminding here. I will simply make scllvm thread-safe.

**Comment by alemoi** [comment]
@alexanderstc are you struggling with no libscllvm.so in build? I will try to add it today.

**Comment by alexanderstc** [comment]
I'm OK, but Team Cognitive were sort of asking if bluestar on linux is gonna be available sometime.

**Comment by eriohl** [comment]
Linux build is not using in-memory compiler for kernel code generation.

**Comment by alemoi** [comment]
> I remember @alemoi once told me scllvm compilation was not thread-safe.
> We should then make a bluestar-wide serializer for scllvm, since more than one subsystem is going to > use scllvm: kernel and metalayer.
> Or make scllvm tread-safe.

Just pushed the thread-safe scllvm (both for Windows and Linux).
@alexanderstc any other requests maybe?
