### ISSUE TITLE
Accessing Enum property from Json by string indexer returns NULL

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Starcounter#3759]
There is some problems regarding `Enum` in a database. When assigning `QueryResultRows<T>` to an JSON object array which does not contain any predefined properties, `"List": [ { } ]`, Enum values cannot be accessed through `jsonObjArr["iAmAnEnumProperty"]`. It returns null like it does not exist. 

It does work through reflection though. See demo for more information.

Get demo from [here](https://github.com/ubbeK/ShowcaseEnum)
1. Open up and build project
2. Deploy and debug through F5
3. Set a breakpoint [here](https://github.com/ubbeK/ShowcaseEnum/blob/master/ShowcaseEnum/EnumPage.json.cs#L39) 
4. go to url [http://localhost:8080/enumbug](http://localhost:8080/enumbug)
5. variable `enumPrimeColor2` will be null

**Comment by miyconst** [comment]
@chrhol I confirm the issue, please take a look.

**Comment by chrhol** [comment]
Looks like the implementation that dynamically created needed properties from a dataobject does not handle enums. I will take a look at the code and see how to add support for it.

**Comment by chrhol** [comment]
I've pushed a fix to develop, and will soon merge it to pnext. Can you please verify that it works, when you have time @ubbeK or @miyconst

**Comment by miyconst** [comment]
I confirm the fix, thank you @chrhol.
