### ISSUE TITLE
Administrator SQL: strange error when using semicolon at the end of statement

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3767]
If I put a semicolon at the end of my SQL statement (e.g. `select o from simplified.ring2.organization o;`) I get the following error:

> Incorrect SQL syntax. Query string must contain a valid statement. The error near or at position 0. In query: select o from simplified.ring2.organization o;

It is extremely confusing, as the error points the user to position `0` which is perfectly fine. Probable cause is that the statement is split by semicolon, and second line is (of course) empty.

**Proposition:** Error message should refer to line (or statement) number when describing errors. So the message in question would look like that: 

> Incorrect SQL syntax. Query string must contain a valid statement. The error near or at position 0 **in statement 2**. In query: select o from simplified.ring2.organization o;

**Proposition:** Ignore semicolon at the end of last line (in other words, ignore empty statement at the end)

**Comment by k-rus** [comment]
I am sorry to say but it is not possible to improve error message in this case in current old SQL.

**Comment by k-rus** [comment]
https://github.com/Starcounter/Starcounter/issues/2319 might resolve the cause.

**Comment by joozek78** [comment]
Probably fixed by #2319
