### ISSUE TITLE
Can I observe an aggregation?

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3768]
I can select an object from database and later bind it with puppetjs. That way, it will always be up-to-date in the browser window, even if someone changes it from another application.

Can I achieve this when I bind to an aggregate? For example `select sum(pi.quantity) from simplified.ring3.productInstance pi where ...` (of course I could select interesting objects and sum them manually). To observe this aggregate I would essentially need to observe any new objects that fall under the `where` clause. Is this possible? Is there some other way of achieving that?

**Comment by miyconst** [comment]
Yes, it is possible.

See an example here: https://github.com/miyconst/Playground/blob/master/Playground/IndexPage.json.cs#L7

**Comment by miyconst** [comment]
And more detailed answer:

```json
{
  "Html": "",
  "Sum": 0
}
```

```cs
public class SumPage : Json {
	static SumPage() {
		DefaultTemplate.Sum.Bind = "SumBind";
	}
	
	public int SumBind {
		get {
			return (int)Db.SQL<long>("SELECT SUM(p.Quantity) FROM Product p").First;
		}
	}
}
```

**Comment by miyconst** [comment]
Although it is possible, you should be aware that the bound property getter will be executed on every patch to check if the value was changed.

If you have a very complex query which takes time to execute, you have to apply some caching inside the property.

**Comment by joozek78** [comment]
So it's not really observing, it's more like recalculating every time the change could've happen. But that can do the trick, thanks

**Comment by miyconst** [comment]
What do you mean by "observing" then? With database classes a value is a read/write property, it's getter will be executed on each "observation", the only difference is that the `Bind = ""` is done automatically.

If you have an `Order.TotalAmount` property which performs `SUM(Order.OrderItem.Amount)` then it will be calculated on each observe as well.
