### ISSUE TITLE
Question : How to bind (1 attribute) Query result with Json

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3770]
I am trying to bind data with my following Json : 
```
  "$AdminNotificationTypes": { "Bind": "AdminNotificationTypes_" },
  "AdminNotificationTypes": [
    {
      "Name": "SuccessAudit"
    }
  ],
```
and the code-behind-Json looks like :

```
        public IEnumerable AdminNotificationTypes_
        {
            get
            {
                QueryResultRows<string> ReturnResult = null;
                ReturnResult = Db.SQL<string>("SELECT Name FROM AdFenix.Database.AdminNotification an group by Name");
                return ReturnResult;
            }
        }
```

This how it looks when I debug it : 
![image](https://cloud.githubusercontent.com/assets/4388707/17171853/bbbc9064-53f2-11e6-8316-9cf9ab9f5685.png)

And this is how it looks in frontend : 
![image](https://cloud.githubusercontent.com/assets/4388707/17171889/de167986-53f2-11e6-9444-c6ce4a2bc6bd.png)

I know the reason of this issue, but I'm not sure how can i fix it.

**Comment by miyconst** [comment]
Replace this:

```cs
return ReturnResult;
```

With

```cs
return ReturnResult.Select(x => new { Name = x });
```

**Comment by atifwaqar** [comment]
@miyconst Thanks a lot, its working now.  :)
