### ISSUE TITLE
Invalid Json object observation when contains response from multiple apps

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3771]
I have the following model:

### Playground app

- Three pages:  `IndexPage`, `SubPage`, and `DatePage`.
- Each page has a handler.
- The `SubPage` handler is mapped to `/sc/mapping/playground-sub-page`.
- The `IndexPage` has a property `SubPage: { }`, which is set with a `Self.GET`.

### Subground app

- Single `SubPage` and a handler.
- The `SubPage` handler is mapped to `/sc/mapping/playground-sub-page`.

When two apps are running the following happens:

```cs
index.SubPage = Self.GET("/playground/date"); // Only DatePage is shown.
index.SubPage = Self.GET("/playground/sub"); // SubPage from both apps are shown.
index.SubPage = Self.GET("/playground/date"); // The SubPage from Playground app is replaced with DatePage, but the SubPage from Subground app is still there.
```

The code is available in my [Playground](https://github.com/miyconst/Playground/) project.

Steps to test:

- Start both Playground and Subground solutions.
- Open `http://localhost:8080/playground`.
- Click `[Load sub page]` button to load `SubPage`.
- Click `[Load date page]` button to load `DatePage`.

cc @chrhol

**Comment by chrhol** [comment]
There is some mixup here with an older change that I made (#3583), so in this case the old sibling (SubPage) gets overwritten and existing siblings gets connected with the new page (DatePage). So not a problem with the merger (which is correct, only DatePage is merged)  or the patches that are sent, but a problem in another place inside TypedJSON code.

Not really sure how to fix it yet, will have to spend some more time on this one.

**Comment by chrhol** [comment]
It was a quite small change needed to fix this. I have pushed a fix to develop and pnext. 

Could you please verify if it works as expected when you have time @miyconst

**Comment by miyconst** [comment]
The issue is fixed. Thank you @chrhol.
