### ISSUE TITLE
Scheduling.ScheduleTask - what is schedId and documentation

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3774]
I am trying to use `Scheduling.ScheduleTask` to execute some code in multi-thread mode.

The `Scheduling.ScheduleTask` method has a third parameter `byte schedId = 255`.

- If this is `schedulerId`, then why `schedId`?
- How do I get list of available schedulers?
- What happens if I pass a wrong value in there?

How to make sure that the scheduled tasks will be distributed between all available schedulers and not 100% load single CPU core? Whatever I did, in task manager I can see only one core working and my tasks are executed one by one instead of parallel.

**Comment by linkdata** [comment]
> If this is `schedulerId`, then why `shedId`?

No clue. Bad speller?

> How do I get list of available schedulers?

`255` means to use some unspecified scheduler (round-robins in current implementation). Range is from zero to `StarcounterEnvironment.SchedulerCount - 1`.

> What happens if I pass a wrong value in there?

Probably nothing good.

> How to make sure that the scheduled tasks will be distributed between all available schedulers and not 100% load single CPU core? Whatever I did, in task manager I can see only one core working and my tasks are executed one by one instead of parallel.

The main use case for `Scheduling.ScheduleTask` is to queue up some `Action` for execution onto one of the SC database schedulers so you can do database operations. Don't confuse this with .NET `Task`'s - they have nothing in common.

Scheduled tasks are always started in order. Note that I said "started" - it doesn't imply that they will always *execute* in order. That depends on OS thread scheduling. Use concurrent queues, semaphores, events or other thread synchronization mechanisms to ensure execution order if you need it.

**Comment by miyconst** [comment]
Today I tried the things again, and scheduling tasks on `[0, 1, 2, 3, 4]` schedulers actually execute it on different cores.

I still would like to change the API and provide documentation as well as inline code comments.

It would be good to replace `StarcounterEnvironment.SchedulerCount` with list of schedulers and update `Scheduling.ScheduleTask` method to accept a scheduler rather than it's number.

**Comment by alemoi** [comment]
Just to remind here is our documentation on scheduling in Starcounter: http://starcounter.io/guides/transactions/running-background-jobs/

**Comment by mtornwall** [comment]
> It would be good to replace StarcounterEnvironment.SchedulerCount with list of schedulers and update Scheduling.ScheduleTask method to accept a scheduler rather than it's number.

`SchedulerCount` implicitly defines the list of schedulers as noted by @linkdata. I think this would be an unfortunate and unnecessary API change that would break existing applications (disclosure: it will break my code, so I'm biased :-)).

**Comment by alemoi** [comment]
I added the check to verify correct scheduler ID supplied and renamed the parameter.
