### ISSUE TITLE
Session.ForAll executed right after another Session.ForAll ignored

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3775]
In my app I have the following code:

```cs
Starcounter.Logging.LogSource log = new Starcounter.Logging.LogSource(Application.Current.Name);

Session.ForAll((s, id) => {
    log.Debug("Session.ForAll #0");
});

Session.ForAll((s, id) => {
    log.Debug("Session.ForAll #1");
});
```

The second `Session.ForAll` block never executed and the `"Session.ForAll #1"` log entry never appears in the log.

You can test this via my [Playground](https://github.com/miyconst/Playground/).

- Start the app.
- Go to `http://localhost:8080/playground`.
- Click `Add items via Session.ForAll`.
- Check the log entries or observe on screen changes.

**Comment by linkdata** [comment]
I'm pretty sure `Session.ForAll()` has been deprecated. You're now supposed to track your active sessions and iterate over them.

**Comment by miyconst** [comment]
As I remember I asked @alemoi to get this function back, and he did so.

**Comment by linkdata** [comment]
> As I remember I asked @alemoi to get this function back, and he did so.

Oh, ok.

**Comment by alemoi** [comment]
`Session.ForAll()` is valid. I will check the example, probably session died between calls or something.

**Comment by alemoi** [comment]
By some reason both tasks start to run on the same scheduler but different threads. I first thought its because of log.debug, but no.

**Comment by alemoi** [comment]
The scheduler seem to pick a new task right during the call to `sccoredb.sccoredb_set_current_transaction`, which is probably causing yielding:
![image](https://cloud.githubusercontent.com/assets/208134/17381404/058cd6c0-59cc-11e6-8ccb-43be8bec4f24.png)
I need a discussion with @linkdata and @dan31 and @bigwad regarding this.

**Comment by alemoi** [comment]
This is a won't fix in current version as we discovered with @bigwad 
There is a different scheduling in future pnext that won't have such problems.

**Comment by miyconst** [comment]
This is pretty sad, hopefully the `pnext` version will be released soon.

**Comment by alemoi** [comment]
> This is pretty sad, hopefully the pnext version will be released soon.

This is unfortunately also only in future pnext, since current pnext has the same scheduling schema.
