### ISSUE TITLE
Question : Does modifying Json changes data in DB?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3776]
I have the following code : 
```
info.Products.Data = Db.SQL<Products>("SELECT p FROM AdFenix.Database.Products p WHERE Domain = ?", domain).First;
Db.Transact(()=>{
    info.Products.Name = "Test";
});
```

`info` is a Json object. If I dont use `Db.Transact` I get an exception on `info.Products.Name = "Test";`. The code runs fine when I have the `Db.Transact`. 
Should I expect the DB value changed?

**Comment by miyconst** [comment]
@atifwaqar in your case the JSON view-model represents database objects. The values are not copied to the view-model, they are just shown in there.

Updating view-model will update the database object. This is also true for non database objects.

```cs
var item = new Item() {
    Name = "Custom item"
};

var json = new ItemPage() {
    Data = item
};

json.Name = "Custom view-model";
```

In this case both `json.Name` and `item.Name` will be the same and equal to `Custom view-model`.
