### ISSUE TITLE
DbObject gets corrupted while entering DbSession()

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3779]
SC Version : 2.2.1.2850

State 1 (Before entering DbSession. `ca.ObId` & `ca.IsFacebookAdNeeded` displayed fine): 
![first state](https://cloud.githubusercontent.com/assets/4388707/17480060/53615b48-5d76-11e6-9062-6f682fece2f6.png)

State 2 (After entering DbSession. `ca.ObId` is still there but code can not access `cs.IsFacebookAdNeeded` or any other Db attribute):  
![second state](https://cloud.githubusercontent.com/assets/4388707/17480067/5a9b8aa0-5d76-11e6-9599-d58c1f6c6273.png)

**Comment by atifwaqar** [comment]
One thing I forgot to mention is, the code is in a Handler, database object `ca` is created in the same handler. and then I try to use the created object `ca` inside `DbSession`. 
I get exception when i access it in `DbSession`, but when I query in SC Admin Panel, I can see the object.

**Comment by miyconst** [comment]
@atifwaqar could you please provide full stack of the exception thrown?

**Comment by alemoi** [comment]
@atifwaqar please use `Scheduling.ScheduleTask` because `DbSession` is deprecated. Also let's see what `DbException` is thrown there.

**Comment by atifwaqar** [comment]
@linkdata mentioned about `DbSession.RunAsync()` in https://github.com/Starcounter/Starcounter/issues/3733#issuecomment-238237976

I updated the code with `Scheduling.ScheduleTask()` and it works fine now. 
@Ripipip can you verify at your end as well?

**Comment by atifwaqar** [comment]
I'm not getting any DbException now (after the fix).
But if you want the exception, I can revert the code for you to reproduce the exception.

**Comment by linkdata** [comment]
> I'm not getting any DbException now (after the fix).

Seems fixed after replacing `DbSession.RunAsync()` with `Scheduling.ScheduleTask()`. Please reopen if the issue is seen again, or if @alemoi wants to try reproducing it.
