### ISSUE TITLE
Support for Byte range requests in Response.StreamedBody

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3780]
Hi! 

I'm trying to use StreamedBody to serve video content for direct playback in browser, via the html5 tag `video`. But the playback fails. Network inspection  reveals that the mp4 file is downloaded. (Playback works when serving the same file with IIS.)

After some reading I believe that the web server needs to support Byte ranged request to allow playback in the browser.

Is this some thing that the Starcounter web server will/should handle or do we need to have a separate web server / media server to handle video stream.

Any thoughts?

**Comment by miyconst** [comment]
cc @alemoi

**Comment by alemoi** [comment]
> After some reading I believe that the web server needs to support Byte ranged request to allow playback in the browser.

You can probably implement a custom handler that processes such requests that has offset/position in video stream. Have you tried this?

**Comment by alemoi** [comment]
> Is this some thing that the Starcounter web server will/should handle or do we need to have a separate web server / media server to handle video stream.

I don't think we will support video streaming with Starcounter 2.2/2.3 but in later versions I think this would be possible. @dan31 what do you think?

**Comment by ivarbergman** [comment]
Thanks for the feedback! I thinks we for now will use a IIS setup to serve video content. If I have time I might look into a custom handle.

(But eventually it would be nice to have Starcounter handle these request. The setup up would be simpler when it comes to authorization and access control if we could manage the stream within Starcounter.)

Thanks

**Comment by dan31** [comment]
> But eventually it would be nice to have Starcounter handle these request

We plan to support all the lacking features of SC communication facilities by re-wiring Starcounter communidation APIs into 3-rd party solutions. This will be done gradually. Currently we try to avoid big additions and enhancements into existing self-made web server.
