### ISSUE TITLE
Question : How to check object Count in `QueryResultRows` 

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3783]
I have following C# code : 
```
QueryResultRows<AdFenix.Database.Images.ImageTemplate> imageTemplates = Db.SQL<AdFenix.Database.Images.ImageTemplate>("SELECT it FROM AdFenix.Database.Images.ImageTemplate it WHERE Name=? AND PublicationOwner.Domain=?", "GenericBannerAd", po.Domain);
```

Currently if I need to check count I either use `foreach` loop or make another query as following : 
```
Int64 imageTemplateCount = Db.SQL<Int64>("SELECT count(it) FROM AdFenix.Database.Images.ImageTemplate it WHERE Name=? AND PublicationOwner.Domain=?", "GenericBannerAd", po.Domain).First;
```

But is there any non-expensive way to get count? like 'imageTemplates.Count`?

**Comment by miyconst** [comment]
@atifwaqar you can use the following method to get number of object inside an `IEnumerable`.

```cs
namespace System.Linq {
    public static class Enumerable {
        public static int Count<TSource>(this IEnumerable<TSource> source);
    }
}
```

**Note:** `IEnumerable` is not an `IList` and it may return different result per each call. Read more here: [IList vs IEnumerable for Collections on Entities](http://stackoverflow.com/questions/376708/ilist-vs-ienumerable-for-collections-on-entities).
