### ISSUE TITLE
Change behavior of statefull partials

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3786]
Right now we have the following behavior:

**Launcher.MasterPage.json**

```json
{
    "UserPage": { }
}
```

**SignIn.MasterPage.json**

```json
{
    "SignInForm": {
        "Username": "",
        "Password": ""
    }
}
```

The SignIn has handler to return `SignInForm` and it's mapped to `/sc/mapping/user`.

Launcher fills `UserPage` with a `Self.GET`. In the result we get the following JSON tree:

```json
{
	"UserPage": {
		"Launcher": { },
		"SignIn": {
			"Username": "",
			"Password": ""
		}
	}
}
```

The `Launcher.UserPage.SignIn` object is a statefull partial from the `SignIn` app. That is why when `SignIn` app makes some changes in the object they are reflected in the `Launcher` JSON tree as well.

The strange thing start to happen when `SignIn` app replaces entire `SignInForm` object with a new one. Although Launcher JSON tree does not have any reference to `SignIn.MasterPage` the following code will replace `Launcher.UserPage.SignIn` as well, and `Username` will be set to `New name`.

```cs
var master = Session.Current.Data as MasterPage;
master.SignInForm = new SignInForm() { 
    Username = "New name"
};
```

Another problem is when Launcher sets value of `Launcher.UserPage` property. The following code will replace `Launcher.UserPage.Launcher` object, but the `Luancher.UserPage.SignIn` object will stay untouched.

```cs
master.UserPage = new LauncherUserPage();
```

This is unexpected and inconsistent behavior. 

After discussion with @chrhol and @warpech it was decided to implement the following behavior. Assuming we have the following partials:

- Stateless - `a` and `b`.
- Statefull - `master` and `slave`.

```cs
var a = new { Name = "A" };
var b = new { Name = "B" };

var master = new {
	A = a,
	B = b
};

var slave = new {
	A = a,
	B = b
};
```

- Replacing `master.A.Name` should reflect in `slave.A.Name` as they reference the same `a` object.
- Replacing entire `master.A` should no affect `slave.A` at all.
- The `a` partial should stay alive as long as `master` or `slave` reference it.
- The `a` partial should state **statefull** as long as application created it references it.

**Comment by chrhol** [comment]
Thank you for investigating this @miyconst! I will change the behaviour to how it's explained in this issue.

**Comment by chrhol** [comment]
I have pushed some changes now (basically removed my other "fix" for this in #3583 :smile:). Tests and running in Playground seems to work as expected now.

@miyconst: Could you please also confirm that the behaviour is as we want it to now?

**Comment by miyconst** [comment]
Seem to be working as described. @warpech please take a look and see if it breaks anything for SWO.

cc @ubbeK, @aloscha, @joozek78, @Mnosek

**Comment by warpech** [comment]
@aloscha, @Mnosek could you please update to PnextNightly 2.3.2998 and see if partials work as before?

**Comment by aloscha** [comment]
For me works as before :)

**Comment by Mnosek** [comment]
It works for me either. I didn't notice any issues.

**Comment by chrhol** [comment]
I will consider this issue resolved then and close it! Thanks for the feedback!
