### ISSUE TITLE
Access violation writing location 0x000000000000001C

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3789]
I am trying to attach debugger to `sccode.exe` process to debug a starting application. And getting infinite amount of the following errors:

```
Exception thrown at 0x00000212B72CCF34 (sccoredb.dll) in sccode.exe: 0xC0000005: Access violation writing location 0x000000000000001C.
The thread 0x20fc has exited with code 0 (0x0).
```

Is it something I am doing wrong?

cc @alemoi

**Comment by alemoi** [comment]
Strange, I never experienced this myself. Seems its some database related operation, since the library is sccoredb.dll. Do you see anything in the log? Do you have this only when attached?

**Comment by miyconst** [comment]
This happens immediately after attached to debugger. Visual Studio keeps popping up a dialog box with option to select a `*.cpp` file, don't remember the exact name.

**Comment by miyconst** [comment]
Does not happen if I start app in debug mode.

**Comment by alemoi** [comment]
Can put the file name here with code line that it complains about? Thanks. I can provide you with the actual file, to see where it throws an exception there.

**Comment by miyconst** [comment]
![image](https://cloud.githubusercontent.com/assets/6435556/17661177/de189d8e-62dd-11e6-8ed3-37643d1df0cc.png)

**Comment by miyconst** [comment]
```
Locating source for 'c:\teamcity\teamcity9\buildagent\work\sc-develop-nightly-437\level0\src\sccoredb\sccoredb\sccoredb.cpp'. Checksum: MD5 {62 2e ae 25 3c 74 d5 48 ff d0 6c 1c 52 a1 e5 f6}
The file 'c:\teamcity\teamcity9\buildagent\work\sc-develop-nightly-437\level0\src\sccoredb\sccoredb\sccoredb.cpp' does not exist.
```

**Comment by miyconst** [comment]
![image](https://cloud.githubusercontent.com/assets/6435556/17661327/c7aacefe-62de-11e6-8702-be50f786823d.png)

**Comment by alemoi** [comment]
So its some transaction creation code. Strange why its throwing access violation, maybe its actually some misleading exception. @eriohl @bigwad do you know anything about it?

**Comment by eriohl** [comment]
My guess is that this is not an unhandled exception but a first-chance exception intercept? This piece of code is excepted to sometimes throw an access violation exception so this is not a problem.

**Comment by miyconst** [comment]
>... so this is not a problem.

Should I just ignore it or? It's very annoying as it throws the exception every 2-4 seconds. I can disable it, but then I won't see other exceptions as well.

**Comment by miyconst** [comment]
As it turns out I can disable only this one specific exception. Thanks for help @eriohl. Closing the issue.
