### ISSUE TITLE
Is it possible to define an index on type?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3796]
@k-rus we support `IS` operator in the SQL queries, like this:

```sql
SELECT p
FROM Somebody p
WHERE p IS Person
```

Is it possible to define an index for this comparison so it will be executed much faster?

**Comment by k-rus** [comment]
To discuss an efficient implementation I want to understand the use cases and what should be the correct data model. Obviously, selecting directly from Person with its own index will be the most efficient approach, but you have some requirements, which you don't describe in the issue. It is possible to utilise the global index, which can be enough if you don't have filtering index as in your example.

**Comment by k-rus** [comment]
> SELECT p
> FROM Somebody p
> WHERE p IS Person
> Is it possible to define an index for this comparison so it will be executed much faster?

My first impression is that the query execution should use an index on `Person` if it is defined, however I am not sure if there is an optimisation rule for this. Or what do you mean?

**Comment by miyconst** [comment]
What index should be defined on the `Person` class to get it work?

If the `IS` comparison applied on a property like:

```sql
SELECT * FROM Company c WHERE c.Owner IS Person
```

Can I define an index on the `Company.Owner` property? Will this index be used with the `IS` operator?

**Comment by eriksunsol** [comment]
More elaborate example:

```C#
// Entity-relation framework w. support for integer and string relations. Base classes.

class Entity { }

class Relation {
  Entity source;
  Entity destination;
}

class IntRelation : Relation {
  int value;
}

class StringRelation : Relation {
  string value;
}


// Some entities

class Producer : Entity { }
class Consumer : Entity { }
class Distributor : Entity { }


// Relation access example: Do something with volumes from certain
// producer going through each distributor, only processing pairs
// that are actually related.
  ...
  Entity e1 = new Producer();
  ...
  IEnumerable<IntRelation> volumes = Db.SQL<IntRelation>(
    "SELECT ir FROM IntRelation ir WHERE Source = ? AND Destination IS ?",
    e1,
    typeof(Producer));
  ...

```

**Comment by k-rus** [comment]
> SELECT * FROM Company c WHERE c.Owner IS Person
> Can I define an index on the Company.Owner property? Will this index be used with the IS operator?

Thank you for more specific example.
How can you imaging defining index on one table and include property of referenced table? I don't really get this. Note that reference using dot notation is a sugaring for a join.

**Comment by eriksunsol** [comment]
I take it that `Owner IS ?` is sugar for (conceptually, behind the scenes) `Owner.GetType() = ?`. If so then use of `IS` also implies a `JOIN`?

**Comment by k-rus** [comment]
> I take it that Owner IS ? is sugar for (conceptually, behind the scenes) Owner.GetType() = ?

Actually, in the case of operator `IS` applied to a reference I am not sure and may be wrong. So `IS` is just complex filter operator on the reference.

**Comment by miyconst** [comment]
@k-rus I don't know how it is implemented on the low level side, what I know is that references access is much faster than `JOIN`. I also don't know whether it's possible or not to create such index.

In our project we hit a bottleneck executing an SQL query with `WHERE x IS X`. We can eliminate the bottleneck by adding an extra sting property to save the type name and add an index on the field, but it would be nice to get the same speed without the extra field. That is why I asked whether it is possible to add such index.

From your answers I can see that it's not possible, am I right?

**Comment by k-rus** [comment]
> @k-rus I don't know how it is implemented on the low level side, what I know is that references access is much faster than JOIN.

I am sure the query plan uses reference access in this case. Do you have query plan where it shows opposite?



> I also don't know whether it's possible or not to create such index.

We have a kind of standard CREATE INDEX statement and I don't really understand how to incorporate type of reference value in index statement syntax.



> In our project we hit a bottleneck executing an SQL query with WHERE x IS X. We can eliminate the bottleneck by adding an extra sting property to save the type name and add an index on the field, but it would be nice to get the same speed without the extra field. That is why I asked whether it is possible to add such index.

I don't really understand your use case. You have presented two completely different use cases, which require different functionality.

**Comment by miyconst** [comment]
>I am sure the query plan uses reference access in this case. Do you have query plan where it shows opposite?

Unfortunately I don't have it right now on hands, but here you can see some benchmark results - [Performance benchmarks](https://starcounter.gitbooks.io/rebelslounge/content/query_processor/performance_benchmarks.html).

>I don't really understand your use case. You have presented two completely different use cases, which require different functionality.

Well, if we have anything for any of the cases, I would appreciate if you describe it here :).

The main use case is described by @eriksunsol which is identical to mine example with `Company.Owner` property.

**Comment by k-rus** [comment]
> Well, if we have anything for any of the cases, I would appreciate if you describe it here :).
> 
> The main use case is described by @eriksunsol which is identical to mine example with Company.Owner property.

We supported such case through `SynonymousTo` and I don't know what is the status. @per-samuelsson was voting to remove the support for it by replacing with properties. Using properties requires to use casting, so Starcounter cannot treat it efficiently currently. `SynonymousTo` or derived property with casting allows to provide another name to a database-stored property and more narrow subtype, while maintaining efficiency in accessing and querying such property.

Saying this,
@miyconst you are right that we don't have any good solution for your case right now, but it is important that we understand the need correctly. My conclusion is that we should support functionality similar to `SynonymousTo` and not a syntax extension of create index statement.

**Comment by miyconst** [comment]
After discussion with @k-rus we came to conclusion that the best way in our case would be to add a custom string property to save related object's type.

In the long term we should add support for indexes over path expression. Something like:

```sql
CREATE INDEX index_name
ON table_name (related_table.column_name)
```

Closing this issue.
