### ISSUE TITLE
Add possibility to ignore unknown properties when populating TypedJSON.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3802]
The current behaviour when populating a TypedJSON object with data and a property from the source JSON is found that does not exist in the schema for the TypedJSON, is to throw an exception.

This should be changed so that it's possible to just ignore the properties that are unknown, and possibly as a feature enhancement, have some mechanism to allow the user to handle these cases.

This first step is to add functionality to allow unknown properties to be ignored.

cc @erikvk

**Comment by per-samuelsson** [comment]
@chrhol: Is this a concern in the `PopulateFromJson` API? I just want to understand where the problem lies.

**Comment by chrhol** [comment]
> @chrhol: Is this a concern in the PopulateFromJson API? I just want to understand where the problem lies.

Yep, that's the spot.

**Comment by chrhol** [comment]
The particular case for this is receiving data from some provider which follows a standard (https://openrtb.github.io/OpenRTB), but the actual json contains properties that are not defined in the standard.

For example a user can be defined like this (in OpenRTB):

```javascript
"user": {
    "id": "abc",
    "gender": "F",
    "keywords": ""
}
```

But the actual data that is received look like this:

```javascript
"user": {
    "id": "abc",
    "gender": "F",
    "keywords": "",
    "age": 29
}
```

**Comment by chrhol** [comment]
I have pushed the changes for this now to develop. I have some trouble running my personal build on pnext, so I am a bit behind to push it to there, but will do that as soon as possible.

There are currently two ways to specify that missing members should be ignored. Either change it globally, which means that missing members will be ignored for all TypedJSON instances when populating data or a settings-object can be specified when calling the `PopulateFromJson` method (but this requires that you call it yourself of course)

Changing it globally:
```csharp
using Starcounter.Advanced.XSON;

class Program {
    static void Main() {
        TypedJsonSerializer.DefaultSettings.MissingMemberHandling = MissingMemberHandling.Ignore;
    }
}
```

Specifying a settings-object per instance:
```csharp
using Starcounter.Advanced.XSON;

class Program {
    static void Main() {
        Handle.GET("/ignore", (Request req) => {
            var user = new UserJson();
            var settings = new JsonSerializerSettings();
            settings.MissingMemberHandling = MissingMemberHandling.Ignore;

            user.PopulateFromJson(req.Body, settings);
            return 200;
        });
    }
}
```

I hope this will work for you @erikvk, lets discuss and test this tomorrow when we have a nightly build with the changes included.

**Comment by chrhol** [comment]
Looks like this change works as it should. I added a new issue to document these features, and will consider this issue resolved.
