### ISSUE TITLE
installer hangs if destination directory is not empty 

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3803]
Sometimes uninstall process doesn't actually delete files from program files (I don't know why and when, so not submitting bug). If that happens, installer always hangs (telling you nothing in the interface and in the logs)

**Comment by alemoi** [comment]
So its uninstaller that is hanging during uninstall process? Or installer during installation?

**Comment by joozek78** [comment]
It's during installation and it happens after installer failed to remove files. It'll probably hang too if I just select a non-empty directory (or maybe directory with specific content, IDK)

**Comment by alemoi** [comment]
This was actually fixed recently! I found a bug in checking for empty directory.
