### ISSUE TITLE
Replace the JSON-by-example parser in TypedJSON

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3811]
As a step in moving towards the next version of Starcounter and start to clean some things up, it's time to remove the old parser used for JSON-by-example, which is a 3rd party library written in F#. 

An advantageous side-effect of this is that we also remove the need for F#, which will make our development-environments a bit cleaner as well.

The replacement is not yet decided, but NewtonSoft.JSON feels like a likely candidate.

**Comment by chrhol** [comment]
One thing that does not work out-of-the-box with NewtonSoft (and probably with other implementations as well): There is no way to distinguish between decimal and double values when parsing JSON-by-example. 

There is a setting that allows you to use either double or decimal when parsing floating point values, but not that can use both.


Possible solutions:
- Modify the part of the code that handles the parsing of numbers to handle our way of determine if a float value is a double or decimal. This also means that we have to build the library from sourcecode ourselves instead of grabbing a nuget package.
- Read all values as strings and handle the conversion to correct type ourselves.
- If we use a more high-level deserializer, maybe we can add our own converter that does the above. This one I haven't tested so I don't know how much effort it will be, or if it's possible at all.

**Comment by miyconst** [comment]
>There is no way to distinguish between decimal and double values when parsing JSON-by-example.

I didn't even know we have such an option right now :D. For me it does not make much sense to have double values in JSON view-model.

P.S. We do not distinguish `int` and `long`, all the values are `long`.

**Comment by chrhol** [comment]
> I didn't even know we have such an option right now :D. For me it does not make much sense to have double values in JSON view-model.

Yeah, it's not commonly used I think :) There are a few specific places where you need to use double to get correct values, like the carthographer app which uses coordinates for a map. 

But maybe we can just assume that a floating point value should be decimal, and add some other way to explicitly say that this property should be treated as a double (on the server)

**Comment by miyconst** [comment]
For me using double for map coordinates looks to be wrong, I would rather use a string. Also syncing such values between client and server might get tricky. Floating point values may end up be different between client and server just because of a `0.00001`.

**Comment by chrhol** [comment]
About backwards-compability and legacy support:
We have a bunch of weird stuff in the current parser for adding metadata inside the json (which we are now trying to get away from). 

Doing a quick search in the code that I have available (both our own and customer code), I found that most of this was never used or known outside our internal tests. Which is really good, then I can simply remove (or not support) most of it. 

The things I found that are used, and that I will add support for are the following:

**Specifying namespace for a root-object**. 
The same thing can be achieved by having a code-behind file with a namespace. If both are specified, an error will be raised today. So this should be considered deprecated, and kept simply for backwards-compability
```javascript
{
  "$" : { "Namespace": "ns.for.the generated.partial" }
}
```

**Specifying datatype**. 
Same as above, can be specified in the code-behind by adding `IBound<DataType>` to class declaration.
Should be considered deprecated, and kept simply for backwards-compability
```javascript
{
  "$" : { "DataType": "fullname.of.datatype" },
  "SomeObj": { },
  "$SomeObj": { "DataType": "fullname.of.other.datatype" }
}
```

**Reusing an existing TypedJSON class**
This is currently the only way to reuse a TypedJSON inside another. 
```javascript
{
  "SomeObj": { },
  "$SomeObj": { "Reuse": "fullname.of.typedjson" }
}
```

**Specifying a path for binding**
The current proposed solution is to do this in code-behind, and set the property directly on the template. Should be considered deprecated.
```javascript
{
  "Name": { },
  "$Name": { "Bind": "FullName" }
}
```

**Comment by chrhol** [comment]
A note about double: I found a few places where double is used today, but these ocurrences are all from our own code, so as long as we have some way to support it I think it's fine that the default handling is to treat these numbers in json-by-example as decimal.

**Comment by miyconst** [comment]
@chrhol currently we have automatic binding in place, like this:

```json
{
    "Value": 0
}
```

```cs
public class ValuePage : Json {
    public decimal Value {
        get {
            return 0;
        }
    }
}
```

Can we use the same technique to define `double` properties? By default all the number are treated as `long` or `decimal`. If double needed then we can define the property manually.

```cs
public class ValuePage : Json {
    public double Value {
        get {
            return this.Data.Value;
        }
        set {
            this.Data.Value = value;
        }
    }
}
```

**Comment by miyconst** [comment]
For the backwards compatibility I would vote to abandon all usage of `$` in JSON except the editable properties mark.

**Comment by chrhol** [comment]
> Can we use the same technique to define double properties?

Hmm, yeah maybe this is a way to use it. I will try it out and see if it's possible. Would allow us to not have any strange pattern or any more special characters in the jsonfile, which is good.

> For the backwards compatibility I would vote to abandon all usage of $ in JSON except the editable properties mark.

That would be awesome, however I think that its simply not feasible. There is too much usage of this in existing code and would require quite a lot of effort to find and rewrite all places. So I think we have to live with supporting it. 

I will check if I can add some notification somehow, so that there are warnings generated when compiling (same as when [Obsolete] attribute is used).

**Comment by chrhol** [comment]
The coding for this task is more or less done. I have a couple of things left to do, adding a warning when using the old deprecated way of specifying metadata inside the jsonfile and creating errorcodes with good errors.

 I'm currently testing it, and probably need to write some more tests as well but so far it seems to be working fine.

I found a way for specifying double and to get away from having to specify Reuse-metadata inside the jsonfile. Instead you can assign the property `InstanceType` on a template to the (json-) type that should be reused, and the code-behind parser will pick it up. 

There are a few restrictions however. Mostly because I wanted to keep the code for the parser as simple as possible.

1) `InstanceType` for the template needs to be assigned in the static constructor in the code-behind
2) The static field `DefaultTemplate` (that contains the schema for each jsonclass) needs to be used.
3) The type assigned needs to be declared with the `typeof` operator.
4) If the property is an object or array it needs to be untyped (i.e. no other properties for that object/array can be declared)
 
Currently the only allowed assignments are: decimal <- -> double and custom types on objects and arrays.

**Master.json**
```javascript
{
  "ElapsedTime": 1.1, // Will be default decimal
  "Page": { }
}  
```

**Master.json.cs**
```csharp
partial class Master : Json {
    static Master() {
        DefaultTemplate.ElapsedTime.InstanceType = typeof(double);
        DefaultTemplate.Page.InstanceType = typeof(SomeOtherJson);
    }
} 
```

If you try to assing `InstanceType` in some other way (by using a local variable or getting the type in some other way for example) an exception will be thrown, and a compiler-error generated describing the problem.

**Comment by chrhol** [comment]
I have just pushed this change to pnext. Will update a few places in the documentation before closing this issue.

**Comment by chrhol** [comment]
I've added sections in http://starcounter.io/guides/json/json-by-example/ and http://starcounter.io/guides/json/json-data-binding/ to describe how to declare double and use reuse in code-behind.
