### ISSUE TITLE
Question : How to open a new browser tab from Json with Code-behind

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3814]
I want to open a new browser tab by clicking on a button. (Button click triggers Code-behind Json). Currently I am using the following code : 
```
Process.Start(NewTabUrl);
```
But the issue is, this opens a new tab on server end, We want the new tab on client end.

**Comment by miyconst** [comment]
@atifwaqar you have to use client side tech to open a new tab on client side, obviously.

```js
window.open("/my/new/url");
```

This has nothing to with JSON with or without code behind.

**Comment by atifwaqar** [comment]
Ofcourse its not. My bad. 
Actually we have to calculate/makeup the url in code behind, which can take 30 seconds or more sometimes. Thats why we were trying to open the new tab directly from Code-Behind. But now im setting the url in a Json attribute, and then I use your syntax to open the new tab, just need to set a delay in Polymer Script.

This is not Starcounter related question, But I will update my finding here, in case anyone else need the info.

**Comment by miyconst** [comment]
>Actually we have to calculate/makeup the url in code behind, which can take 30 seconds or more sometimes.

@atifwaqar could you please explain this a bit more?

>... just need to set a delay in Polymer Script.

You should not static timeout values, you never know how long certain action will take to finish on a different server. You need an event instead.

**Comment by atifwaqar** [comment]
@miyconst I am on vacations, So I assigned this task to another developer, looks like the issue is resolved. So im closing this issue for now. but When i come back I will update the complete solution aswell.
