### ISSUE TITLE
Improve error reporting for SCERR2149

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3815]
Currently the only information I get is:

> The application can not start because it contains at least one database class with private data. See separate errors with ID "ScErrNonPublicFieldNotExposed". 1 illegal fields exist. (ScErrCantBindAppWithPrivateData (SCERR2149))
(Double-click here for additional help)

Specifically, I don't get any information about where is the prohibited field. It should be pointed out in error message. It is also possible that it would be mentioned in separate error, but I didn't get anything more, so that could be a bug here

**Comment by per-samuelsson** [comment]
Just generally, we could certainly improve in how to deal with and present errors. If I'm not mistaken, we have a few of these in the backlog already.

Just out of curiosity, regarding 

> See separate errors with ID "ScErrNonPublicFieldNotExposed". 1 illegal fields exist. 

You didn't find any such entries in the [error log](http://starcounter.io/guides/tools/error-log/)?

**Comment by joozek78** [comment]
The information was there, thanks. I just had no idea to look there, since I treated this more like a build error
