### ISSUE TITLE
Use new starcounter-include in /sys/, and move it to Starcounter/starcounter-include

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Starcounter#3819]
If we are ok with the new `<starcounter-include>` that uses just Shadow DOM Composition, maybe it's the time to finally ship it with Starcounter installation.

As designed the new `starcounter-include` (currently at https://github.com/StarcounterPrefabs/launcher-include):

1. Will does nothing if does not receive composition (performance of pure `starcounter-include` remains untouched)
2. Is no longer Juicy-specific thing..
3. Is no longer opinionated - it's just vanilla Document Fragment that we want to put into Shadow DOM 
4. Could enhance experience with `Starcounter.HTMLComposition` delivered by Launcher,
5. Could enhance experience when used without Launcher, but app developer provided _default composition_ within partial (`<template is="starcounter-composition">`) - We give complate freedom to compose standalone layout, that would be consistent with Launcher's layout,
5. Could enhance experience when used without Launcher, but app developer provided composition manually (implemented his/her own layout manager)

Therefore I believe we should go for it, so:

1. We will no longer need an ugly hack in Launcher that overwrites [one `stracounter-include`](https://github.com/Starcounter/starcounter-include) with [another](https://github.com/StarcounterPrefabs/launcher-include),
2. We will no longer need to maintain additional repo,
3. We will no longer need to explain that mess to other devs, and clients

Maybe we should include it within 2.2.1, as we are shipping `Starcounter.HTMLComposition` there.

The only risk of such change is that standalone apps that were using old `juicy-tile-grid`-driven layouts will loose those layouts. But AFAIK  nobody used it anyways.

@dan31, @warpech, @miyconst WDYT?

**Comment by warpech** [comment]
We need to make sure it works cross browser first, because I can't get it to work in browsers other than Chrome.

**Comment by ubbeK** [comment]
:star:

**Comment by tomalec** [comment]
@warpech Do we have any issues reported related to lack of cross-browser support? The problem you described to me on slack seems to be rather Products-SignIn problem https://github.com/StarcounterSamples/Products/issues/30 https://github.com/StarcounterSamples/Products/issues/29

**Comment by warpech** [comment]
I confirm, the cross browser problem was another thing.

> The only risk of such change is that standalone apps that were using old juicy-tile-grid-driven layouts will loose those layouts. But AFAIK nobody used it anyways.

If this is the only risk, then let's go for it!
