### ISSUE TITLE
Assertion failed Error

### ISSUE THREAD

**Issue by Adeelkh** [Starcounter/Starcounter#3823]
Our Database is crashing due to following error. Quick Response in this regard will be a great help

Assertion failed (released_chunks_num == num_ipc_chunks) at OurSources\worker_db_interface.cpp:21 (Data 0).
   00007FF861B411E9 sccoredbg!do_handle_assertion_failed : assert-win.cpp (76)
   00007FF861B41039 sccoredbg!handle_assertion_failed : sccoredbg.cpp (29)
   00007FF72465B166 scnetworkgateway!starcounter::network::WorkerDbInterface::ScanChannels : worker_db_interface.cpp (149)
   00007FF72465793E scnetworkgateway!starcounter::network::GatewayWorker::ScanChannels : worker.cpp (1986)
   00007FF724658BD5 scnetworkgateway!starcounter::network::GatewayWorker::WorkerRoutine : worker.cpp (1892)
   00007FF72463DB30 scnetworkgateway!starcounter::network::GatewayWorkerRoutine : gateway.cpp (3224)
   00007FF866D416AD KERNEL32!
   00007FF869324629 ntdll!

**Comment by atifwaqar** [comment]
SC Version 2.2.1.2709
And this is a critical issue, our Live Server is crashing again and again.

![image](https://cloud.githubusercontent.com/assets/4388707/18200981/ad1021b6-7107-11e6-8d38-e18f6f0bf2ff.png)

**Comment by alemoi** [comment]
Hi @atifwaqar I am looking at it now! Will get back to you asap!

**Comment by alemoi** [comment]
The problem seems to be in IPC code. I wonder if I can give you a different version of scnetworkgateway executable with more checks, so you can run it instead?

**Comment by alemoi** [comment]
I have increased the time needed for chunks to be returned to shared chunk pool, and the problem seems disappeared so far. Via: 2ef871ae45377dfb973ac4e21902f2142c5724a0
