### ISSUE TITLE
Call Database.Intit from Launcher on app start

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3825]
See the Test project `/palma/init` handler.

**Comment by Joltrix** [comment]
Implemented in: 985a4c9

**Comment by Joltrix** [comment]
Implemented in commit: [985a4c9 ](https://github.com/HRidge/PalmaServer/commit/985a4c9936977a44abf66e6e8758b4503c5aae78)

**Comment by miyconst** [comment]
See my comment in the commit.

**Comment by Joltrix** [comment]
Fixed: Implemented in commit: [1a60a4e](https://github.com/HRidge/PalmaServer/commit/1a60a4ea62dc6659b3ed5c4de21f2c962c136571)
