### ISSUE TITLE
ScErrFieldSignatureDeviation (SCERR4128)

### ISSUE THREAD

**Issue by aloscha** [Starcounter/Starcounter#3826]
I've create database model:

> ```
>   public class DateChanged : Something
>   {
>        public DateTime NewDate;
>   }
> ```

Then I used that model in my app. I realized that this field could be `null`, so I change my datamodel to:

> ```
>   public class DateChanged : Something
>   {
>        public DateTime? NewDate;
>   }
> ```

I start debug and received `
"ScErrFieldSignatureDeviation (SCERR4128): A database type declared a persistent field that did not match the signature of the attribute in the core schema. The type for property/field 'NewDate' in class 'Sweoffshore.Checklist.Event.DateChanged' has been changed from 'UInt64' to 'UInt64'.
436.6096 Starcounter.Host.Loader:Processing completed."`

I delete database but that not help at all. I think deleting the file which contains DB locally could help, but I don't check it.

This could be really simple workaround by changing property `NewDate` to something else and change it in whole project. (for me that works)

**Comment by per-samuelsson** [comment]
> This could be really simple workaround by changing property NewDate to something else and change it in whole project. (for me that works).

@aloscha, could you expand a bit on that last section (commented above)? I don't fully understand it.

Meanwhile, I'll try to set up a test to see what options you have doing the thing you are trying to do (essentially, changing the data type, or rather allowed "range", or a database field). I'll get back to you on that.

Finally, what version is this? Can you run `star -v | clip` and copy the content here?

**Comment by per-samuelsson** [comment]
Also @aloscha, you might find issues #3499 and #3559 relevant to this discussion.

cc @chrhol @k-rus (both has been involved in past discussions about database refactorings)

**Comment by k-rus** [comment]
I don't fully understand the issue. It sounds that deleting database has not deleted the database is the main issue. Otherwise according to the post the error was meaningful and understood correctly. The suggested strategies (remove database or add another field) feel to me reasonable.

**Comment by per-samuelsson** [comment]
> The suggested strategies (remove database or add another field) feel to me reasonable.

And to preserve data when changing data type? Is that not possible in neither version (2.2x | 2.3.x)? For this case, could unload/reload be used for that?

**Comment by k-rus** [comment]
> And to preserve data when changing data type? Is that not possible in neither version (2.2x | 2.3.x)? For this case, could unload/reload be used for that?

I think Unload/Reload should move the data into the new database schema. The other mentioned approach is to create new column. Then the data can be preserved by manually copying them (i.e., by app code) from to new column.

**Comment by dan31** [comment]
Old way to migrate is deprecated in favor of StarDump:
2.2 -> 2.3: https://docs.starcounter.io/guides/working-with-starcounter/migrating-from-2.2-to-2.3+/
2.3 -> 2.(3+N): https://docs.starcounter.io/guides/working-with-starcounter/unload-reload/
