### ISSUE TITLE
Add support for hosted unit tests

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3831]
This has been an ongoing discussion for quite some time. We have now made a principal decision to give it a go.
### Main idea

Allow developers to **write unit tests** using a common framework. Probably [xUnit](https://xunit.github.io/) to start with. And support **running those tests** (transparently) inside a database host. In a sense, the host become a custom test runner.
### Why not support common runners?

Standard unit tests runners such as console- and VS-runners can't be used since they are designed to load unit tests into their own respective process. Starcounter applications are hosted and therefore can't support that model.

In future version 3.x ("Starcounter.Core"), we plan to support self-hosted applications as a complement to platform-hosted ones (i.e. those hosted by Starcounter). By doing that, we can support these runners in that environment.

Mocking could also enable this. We don't plan for mocking in the first version though. See below.
### Points to consider
- In an early prototype, we identified tests to be ran using a naming pattern, forcing tests to be written in a separate library. While this is probably the desired approach for most cases, we will try to support also having tests defined in the application / library itself.
- We are planning to add various safety guards to minimize the risk of tests being executed on live / production data.
- We want to support running just specified tests.
- Tests must be able to run in a CLI context, mainly to support build tools / common CI strategies. 
- Ideally, I would also like us to have an app that can present all tests loaded inside a certain host and explicitly run them over and over. Kind of like [NUnit GUI runner](http://www.nunit.org/index.php?p=nunit-gui&r=2.5). Would make for very good test + debugging scenarios (i.e. attach debugger to the host, then trigger the test you want to run/debug). Not sure we can fit this into the first version though.
### Mocking

Not part of this initiative. We plan to go deeper into those discussions once we have shipped this.
### Background

https://github.com/Starcounter/Starcounter/issues/1297
https://github.com/Starcounter/Starcounter/issues/3112
https://github.com/Starcounter/CompanyTrack/issues/151

**Comment by bigwad** [comment]
Do we really the entire control over the host? To my knowledge, we are free to perform our initialization at any point and the only real problem is to make sure an actual test is running on starcounter thread. I don't see immediate solution how it could be implemented in NUnit, but it's an open source. Just a small new attribute like ThreadInitializer may handle it :)

Just a dream.

**Comment by bigwad** [comment]
Probably, not even a new attribute, but an overload to existing RequiresThreadAttribute.
Still just a dream :smile:

**Comment by per-samuelsson** [comment]
> Do we really need the entire control over the host?

Not sure I understand what you mean?

**Comment by per-samuelsson** [comment]
Discussion issue, for a small part of this: #3833.

**Comment by bigwad** [comment]
>Not sure I understand what you mean?

Probably, it's the same approach you mentioned as self-hosted app. I just tried to say there is a possibility that:
1. enabling self-hosted app is not that hard
2. by enabling self-hosted app we may achieve simpler integration with NUinit without bothering with custom runners etc

**Comment by per-samuelsson** [comment]
> 1. enabling self-hosted app is not that hard
2. by enabling self-hosted app we may achieve simpler integration with NUinit without bothering with custom runners etc

Thanks for clarifying, @bigwad. Then I do understand what you mean. But I disagree. 

Supporting self-hosted apps in 2.x I just don't see as an option (knowing that there are major things that need to be solved for this, and several of those, we haven't figured out yet). If someone tells me otherwise (with confidence), I'm certainly willing to listen :smile:

**Comment by jwillmer** [comment]
As long as I don't need to rewrite all tests after you support self-hosted apps and only need to switch the "target" I would participate in testing the nightlys on our current project.

One remark: Did you thought about the problem to start from a prepared database and revert it back to that state after each test?

**Comment by per-samuelsson** [comment]
>As long as I don't need to rewrite all tests after you support self-hosted apps and only need to switch the "target" I would participate in testing the nightlys on our current project.

That's our absolute aim. And one of the benefits of using a standard framework to **define tests**. Once defined, we "just" have to make sure we can bring tests along from one (older) version to another (new).

> One remark: Did you thought about the problem to start from a prepared database and revert it back to that state after each test?

Yes, we did. Or more precisely: we touched on it. Thanks for pointing it out. We need to do more thinking about that.

A very simple approach (for us at least) is to advice users to run tests in dedicated (temporary) databases. With context/fixture support in the framework (like that in [xUnit fixtures](https://xunit.github.io/docs/shared-context.html)), you could easily initialize the database before tests start, and remove it again as part of teardown (if needed).

Furthermore, since creating new databases in Starcounter is pretty lightweight and simple to do, a simple CI-approach could be:

```
staradmin new db foo
star -d=foo --test app.exe
staradmin -d=foo delete --force db
```

But again, let us do some more thinking on it first, until we decide something more concrete. Meanwhile, we really appreciate all feedback!

**Comment by per-samuelsson** [comment]
Regarding this clause from the OP:

> We are planning to add various safety guards to minimize the risk of tests being executed on live / production data.

I propose one constraint to start with: that databases must be **explicitly configured** to run tests. That would mean `star --test app.exe` would return an error unless the database was configured to support running tests: `staradmin -d=testdb new db --allowRunningTests` (or similar).

Pretty simple to guard it from within the host.

Another alternative is not to have it on the database, but instead the **host**. So that before you can run tests, you have to start the host with an enabling parameter:

```
staradmin start db --allowRunningTests`.
star --test app.exe
```

Feedback appreciated.

**Comment by per-samuelsson** [comment]
Update: as hinted earlier, we are making the first hosted tests driven by `xUnit`, meaning that's the API to use to write tests in the first version.

I'm making a thin abstraction in between the host and the underlying test engine though, to make it straightforward to support other test frameworks, most notably `NUnit`.

Anyone has thoughts about this? Should I try to support both right from the start?

**Comment by per-samuelsson** [comment]
My recent struggles has been to find the best way to approach *how to run* tests, and how they *relate to application state**.

Right now, after a few considerations and testing, I have settled with the simplest possible solution: we run tests as part of application bootstrapping and based on some precondition(s) (probably "enabled" host/db + switch). And we always do that *after* executing the entrypoint and the effect it has on application state is *none*.

There are really quite a mix of possible combinations here, and I've tried considering them one by one, listing pros and cons. They seem to have a few each, and based on that, doing the simplest thing to start with seem to be the most reasonable choice, and that's what I'm currently working on.

Actually, the option I kind of like best is to have tests being driven by an API rather than tooling. That gives the absolute most flexibility for those writing and executing tests, but has some disadvantages - the main ones being that it's somewhat non-standard (compared to other frameworks) and that the story "How to add tests to your application" become less straightforward (and longer).

**Comment by per-samuelsson** [comment]
Realized a usability limitation regarding this from the OP:

> In an early prototype, we identified tests to be ran using a naming pattern, forcing tests to be written in a separate library. While this is probably the desired approach for most cases, we will try to support also having tests defined in the application / library itself.

The idea I had was that any **app** (i.e. executable) could include tests, and that the host would detect (and run) those. Plus that if next to the app, there was a `[appname].tests.dll` library, it would get the same treatment. That would allow for a simple and yet flexible alternative for app developers.

Problem with it is that it's kind of backward when you must materialize it as project references in a solution. Assuming most code you want to **test** is contained in the *app*, the test library must reference the app. But to have the test library end up next to the app when *built*, the app must depend on the test library. This is of course bad, and also technically impossible since it would create a circular dependency.

I need to spend some more time trying to figure out an alternative to actually detect and trigger tests that live outside the application.

**Comment by per-samuelsson** [comment]
WRT the last comment: I'm starting to lean towards a model where we make a clearer distinction between tests and apps, and have a dedicated tooling for tests. Then maybe support a "shortcut" to allow tests to be run as part of app bootstrapping. But the default being that you give your tests to the host and they are run separately and on demand.

**Comment by per-samuelsson** [comment]
> But the default being that you give your tests to the host and they are run separately and on demand.

Just for the record, I wan't to bring up that there is a thing we possibly need to eventually resolve with this: the fact that code loaded into the host can not be unloaded (w/o restarting host) will mean that passing subsequent builds of a certain test suite into the same host will result in undefined behavior.

In the first version, I plan to just load it transparently and be done with it. Let's see from how it's used how big a problem the above will be.

**Comment by per-samuelsson** [comment]
> But the default being that you give your tests to the host and they are run separately and on demand.

Turned out this was not as straightforward as I first imagined. Quite a setback. The problem is that as soon as tests contains code that target database classes that was *weaved*, things don't work that well (obv). And running tests through the weaver on demand is something that require quite some redesign of the weaver.

**Comment by per-samuelsson** [comment]
With all things above taking into consideration, the best I can produce right now, without having to do some hefty design of stuff I really don't want to touch in 2.x, is this:

1. From your application, add a reference to xUnit (normally from NuGet).
2. Write your tests.
3. Run your application.
4. Run tests in your application with `staradmin test [appname]`.

Because of above-mentioned limitations, tests will have to load as part of the application. The con of this is that it's less flexible than being able to run any unit test assembly at any point. The pro is that it is compatible with application state (if you restart your application, your tests are reloaded too).

Host tests in a separate assembly is possible using the same naming pattern as I suggested earlier - `[appname].tests.dll`. It's an extra step to set up though, since you need to make sure you distribute that assembly next to your exe.

Nothing is merged yet. Still some details to work out, plus that we must have another round of discussions on this initiative in large.

**Comment by per-samuelsson** [comment]
We abandoned this and instead went with a solution based on self-hosted apps.
