### ISSUE TITLE
HTTP header with disk location for static files

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3836]
## Problem 

Starcounter's static file server is serving static files from multiple directories on the local file system.

When you find a problem in the static file, it is hard to guess what is the file path on disk.

This is especially a problem, when there are multiple paths with the same file. Which one wins?

## Actual behavior

Starcounter serves the file from the last app that was started. But if you don't know that order, then you have to guess the path.

## Expected solution

Starcounter should add a custom HTTP header (`X-File-Path`) that contains the original file path.

It should be possible to disable this option using a configuration option on the database.

cc @alemoi, @tomalec

**Comment by tomalec** [comment]
Very big :+1: from me, I get hit by this sooo many times.

**Comment by alemoi** [comment]
Was a bit messing with commits, so you see a duplicate. But otherwise added and tested this feature. For existing databases add the new entry in database config `XFilePathHeader`:

![image](https://cloud.githubusercontent.com/assets/208134/18534040/f0931a58-7ae7-11e6-90be-34665145324a.png)

Appreciating your input.

**Comment by miyconst** [comment]
I also have been hit by this issue, but we should understad that exposing physical file path is a potential security hole.

**Comment by miyconst** [comment]
@alemoi it looks like after your rework Starcounter stopped detecting changes in static files and I have to restart an app to see the changes.

**Comment by alemoi** [comment]
Sorry, about that! Going to check right now!

**Comment by warpech** [comment]
Oops, this needs a fix before stable.

**Comment by alemoi** [comment]
> Oops, this needs a fix before stable.

Just fixed. Producing a nightly now. Will be ready in an hour approximately.

**Comment by alemoi** [comment]
@miyconst can you please test the latest nightly http://downloads.starcounter.com/download/Starcounter/DevelopNightlyBuilds/2.2.1.3178

Just want to be sure it works on your computer. Thanks!

**Comment by andwah** [comment]
After quick test with latest level1 "develop" branch.. Still not working for me.. i will now do a rebuild of level1 and test again.....

**Comment by alemoi** [comment]
No need to rebuild, just build latest develop. Thanks for testing @andwah

**Comment by andwah** [comment]
@alemoi pulled latest level1 (develop). still not working for me sorry..

**Comment by alemoi** [comment]
@andwah works fine for me. Lets test on your system. @miyconst what about you? :)

**Comment by alemoi** [comment]
@andwah thx for debugging session, some system differences! The fix is pushed now to develop and pnext.

**Comment by andwah** [comment]
@alemoi pushed a new fix and that solved the problem, now it works.  

It was an issue with comparing filenames that had both upper and lower case characters.

**Comment by warpech** [comment]
Could you please add documentation of this feature to http://starcounter.io/guides/database/database-configuration/?

**Comment by alemoi** [comment]
> Could you please add documentation of this feature to http://starcounter.io/guides/database/database-configuration/?

Was going to ask if this feature should be public. Anyways, added the documentation for it. You can close the issue if you think its done here.

**Comment by warpech** [comment]
It must be explained, since it is **true** by default for developer's comfort. It should be disabled for production.

Thanks!

**Comment by alemoi** [comment]
> It must be explained, since it is true by default for developer's comfort. It should be disabled for production.

Done! :)
