### ISSUE TITLE
HTTP handler does not respond if mapped in UriMapping.Map but called from the outside world

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3840]
# Problem

If in my app defines `UriMapping.Map` for a URL that is requested from the outside world (not only from the `Self.GET`), the response times out (goes into an infinite loop?).

This will cause Starcounter build tests to fail after Launcher `develop` branch gets merged to Launcher `master`. (The tests that checks that: [test.js](https://github.com/StarcounterPrefabs/Launcher/blob/6ede4d038717b6f8a27af4fa0f79048d8b847fc8/test/test.js#L85))

# Expected

The server should respond the same as without `UriMapping.Map`, without the sibling responses.

# Steps to reproduce

1. Start SignIn (*without* Launcher)
2. Go to `localhost:8080/signin/signinuser`
3. Verify that it never loads
4. Now comment the line: `UriMapping.Map("/signin/signinuser", "/sc/mapping/userform");`. Rebuild and see that `localhost:8080/signin/signinuser` loads.

@alemoi could you please take a look?

cc @tomalec, @miyconst

**Comment by alemoi** [comment]
Thanks for reporting! I found the problem, but want to ask additional question: what if another app do map to `UriMapping.Map("/anotherapp/signinuser", "/sc/mapping/userform");` what response (for external request of course) you would expect by calling:
1. `localhost:8080/signin/signinuser`
2. `localhost:8080/anotherapp/signinuser`
3. `localhost:8080/sc/mapping/userform`
Thanks!

**Comment by alemoi** [comment]
And the response is just a partial in a correct case, right?

![image](https://cloud.githubusercontent.com/assets/208134/18528472/7d697ac2-7ac9-11e6-9d5e-06b22f009d44.png)

**Comment by warpech** [comment]
Yeah, right now I would expect a partial, that is wrapped by Launcher if Launcher is running.

**Comment by warpech** [comment]
Yeah, right now I would expect a partial, that is wrapped by Launcher if Launcher is running.

Regarding what I expect:

1. localhost:8080/signin/signinuser - response from SignIn, without siblings on the root level
2. localhost:8080/anotherapp/signinuser - response from AnotherApp, without siblings on the root level
3. localhost:8080/sc/mapping/userform - 404, because this is a mapping URI, not an entry point URL

Does it make sense?

**Comment by alemoi** [comment]
@warpech can you please test the build http://downloads.starcounter.com/download/Starcounter/DevelopDailyBuilds/2.2.1.3180

I tested with/without Launcher and it was fine. Except the case 3 since it returns the mapped URI, as a redirect, which is correct.

**Comment by warpech** [comment]
I have just tested Starcounter 2.2.1.3180 + Launcher `develop` + SignIn `master`.

The `npm test` is successfully passing, so I guess it is fixed! Thanks!

**Comment by alemoi** [comment]
Thanks for reporting! I just merged to develop/pnext. Should be available in the next nightly.
