### ISSUE TITLE
Incomprehensible error message when trying to upgrade pnext

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Starcounter#3843]
When I'm trying to upgrade pnext from Starcounter v2.3.3675 to v2.3.3824 I've got following error message:
![upgrade_error](https://cloud.githubusercontent.com/assets/4943949/18588171/a7fa0722-7c25-11e6-8b68-ff9de12e5c57.png)

According to the links in the message it should not be possible to do the upgrade automatically, but I think that this message is a bit confusing:
- There should not be stack trace there
- `The image file API's are not supported in 2.2` - the version is invalid in this part as I have 2.3.x and trying to upgrade to 2.3.x
- The link: `https://github.com/Starcounter/CompanyTrack/issues/120#issuecomment-157342000` is available only for Starcounter github members. I think that in installer should be no private links at all
- Actually is there any error? If I click "yes" the whole process works fine and I've got Starcounter upgraded. If I click "No" installation closes. Maybe there should not be any error at all, just a confirmation "Would you like to upgrade from v.X.X to v.X.X.

I just giving a look from a Starcounter's user level, I've found the whole upgrade process bit confusing because of it.

**Comment by dan31** [comment]
On Monday @andwah is on it. Thanks @warpech for additional attention.

**Comment by andwah** [comment]
Stacktrace and Database Compability check removed,
