### ISSUE TITLE
Cookie Expires date is serialized in wrong format

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3847]
The date set in [`Cookie.Expires`](https://github.com/Starcounter/Starcounter/blob/57c6d056c5a43e4ffabbea3f261e3f30219220b1/src/Starcounter.Internal/Http/Cookie.cs) is serialized to string in a wrong format:

Is: `soauthtoken=OtS8ogGxO384xYwAsCpZ0Q2; expires=2016-09-21T14:22:28.617Z; path=/`

Should be RFC 1123: `soauthtoken=OtS8ogGxO384xYwAsCpZ0Q2; expires=Thu, 21 Sep 2016 14:22:28 GMT; path=/`

Explanation: http://stackoverflow.com/questions/11136372/which-date-formats-can-i-use-when-specifying-the-expiry-date-when-setting-a-cook

Related issue: https://github.com/StarcounterPrefabs/SignIn/issues/40

@alemoi could you please take a look?

**Comment by warpech** [comment]
Similar problem was here: https://github.com/Starcounter/Starcounter/issues/3427#issuecomment-195961404

**Comment by alemoi** [comment]
Thanks for reporting! Should be fixed now. @miyconst so you know also, since its in `Cookie.cs`.

**Comment by warpech** [comment]
Tested, looking good!
