### ISSUE TITLE
Starcounter Not running!

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#3854]
```
Starcounter: 2.2.1834 or 2.3.3940
OS: Win10 Pro
User: Administrator

C:\Starcounter\DB\Personal>scservice
Starting Starcounter PERSONAL engine...
Press CTRL-C to exit.

Reading server configuration from: C:\Starcounter\DB\Personal\PERSONAL.server.config
Reading gateway configuration from: C:\Starcounter\DB\Personal\scnetworkgateway.xml
Error: ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
Please review server log in: C:\Starcounter\DB\Personal\Logs

Log:
20160924T162732 Error sc://senerm/personal/service Starcounter - ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
20160924T162732 Error sc://senerm/personal/service Starcounter - Process exitcode: -1073740791
```

**Comment by andwah** [comment]
Some anti-virus software may interrupt and block Starcounter from working properly and you will get a similar error as you describe.

See https://github.com/Starcounter/Starcounter/issues/925

**Comment by SenerDemiral** [comment]
Only I have Windows Defender and real-time protection is off.

**Comment by dan31** [comment]
Hi @SenerDemiral! I believe that the reason for the current problem is the different installation path mixed with your user settings. @alemoi can you please follow up on the issue to see what might have gone wrong?

**Comment by SenerDemiral** [comment]
I already tried to install default path. But result is the same.

**Comment by dan31** [comment]
@SenerDemiral thanks for checking! Looks like definitely something specific to your Windows environment (most likely reason). @alemoi will get back to you asap.

**Comment by SenerDemiral** [comment]
I think found the problem.
I'm using Win10 with Administrator account/login.
If I signed-in the regular account Personel Server started as usual.
Sorry to take your time.
Maybe you mention this behaviour in getting-started documentation for newbies like me.

**Comment by alemoi** [comment]
@SenerDemiral so when you was signed in again as Administrator - the Starcounter did not start, right? Can you please post here the contents of the Starcounter server log that corresponds to startup failure? (server log is usually located in `Documents\Starcounter\Personal\Logs`) Thank you!

**Comment by SenerDemiral** [comment]
@alemoi Log is already in the first comment. anyway.
Log:
20160924T162732 Error sc://senerm/personal/service Starcounter - ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
20160924T162732 Error sc://senerm/personal/service Starcounter - Process exitcode: -1073740791

**Comment by SenerDemiral** [comment]
Yes, with adminisrator signin, Personel Server is not running.
