### ISSUE TITLE
Partials without explicit slot attributes, get unscoped from auto-assignment

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Starcounter#3859]
as @warpech noticed in HellowWorld app.

When you create partial without specifying slot attributes for some elements, the names that are created automatically are prefixed with `""` ;)

This is because Starcounter (w/o Launcher) does not add `juicy-composition-scope` not `juicy-tile-group` elements between scopes.

We decided to change `<juicy-composition-scope>` to `<meta itemprop="juicy-scope" name="AppName"/>` to hopefully improve performance and code clarity by using native elements instead of custom ones.

**Comment by warpech** [comment]
I think the attribute should be `content`, not `name`:

> If `name` is set, it is document-level metadata, applying to the whole page. 

[source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta)

**Comment by tomalec** [comment]
`content` or `scope`?

**Comment by warpech** [comment]
`<meta itemprop="juicy-scope" content="AppName">` seems to be the most spec-compliant to me

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemprop

**Comment by tomalec** [comment]
Cool, thanks :)
