### ISSUE TITLE
Heads application do not work after upgrade to 2.2.1.3234

### ISSUE THREAD

**Issue by niklasbjorkman** [Starcounter/Starcounter#3861]
Application worked before upgrade, after upgrade nothing is displayed in the "IndexPage" section (implemented according to sample on SC site).

JSON is update correctly. Cleared temp, delete DB. 

Even more critical is that it is not possible to downgrade to a working version. After downgrade the weaver no longer works.

**Comment by per-samuelsson** [comment]
> Application worked before upgrade, after upgrade nothing is displayed in the "IndexPage" section (implemented according to sample on SC site).

Hard to say why. I guess you have tried disabling the browser cache? (I just seem to remember that previously, weird browser caching stuff has caused "blank" pages like that).

cc @warpech @miyconst @chrhol 

> Even more critical is that it is not possible to downgrade to a working version. After downgrade the weaver no longer works.

You uninstall "2.2.1.3234", reinstall the previous version (successfully), and then the weaver fails when you rebuild your application? If so, what kind of error do you get?

**Comment by dan31** [comment]
We checked with @niklasbjorkman and it appears that everything works, patches go through, except that the response is not rendered at all. Most likely we missed something when moving from Polymer versions 1.4 -> 1.6.1 (he upgrades from 2.2 to 2.2.1 Stable) and what we had to reflect in release notes to let users migrate the code. But what this might be?

**Comment by tomalec** [comment]
Do you have `starcounter-include.html` in you app code? (custom one, different that one shipped with Starcounter)

Could you post a piece of code around `<starcounter-include>`? and a screenshoot of output from (Browser Dev Tools') elements tab around  it?

**Comment by andwah** [comment]
maybe some duplicated mix of polymer versions? (one version in the app solution and another one in starcounter?)   just guessing....

**Comment by niklasbjorkman** [comment]
We do not have any reference to starcounter-include.html. Only reference to that is from a file we no longer use.

**Comment by miyconst** [comment]
I am trying to run this project and seeing the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The user code entrypoint method raised an exception. System.NotSupportedException: 
			An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework.
			This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous.
			If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch.
			See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

			at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-505\Level1\src\Starcounter\Query\QueryPreparation.cs:line 67
			at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-505\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
			at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-505\Level1\src\Starcounter\Mock\Db.cs:line 123
			at Starcounter.Db.SQL(String query, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-505\Level1\src\Starcounter\Mock\Db.cs:line 81
			at HeadsWMS.Persistent.Session.SessionHelper.AssureIndex(String indexTextLine) in F:\Debug\WMS\HeadsWMS\Persistent\Session\SessionHelper.cs:line 94
			at HeadsWMS.Persistent.Session.SessionHelper.AssureIndexes() in F:\Debug\WMS\HeadsWMS\Persistent\Session\SessionHelper.cs:line 73
			at HeadsWMS.Persistent.DbHelpers.HeadsDbHelper.LoadStartupObjects() in F:\Debug\WMS\HeadsWMS\Persistent\DbHelpers\HeadsDbHelper.cs:line 49
			at HeadsWMS.WMSProgram.Main() in F:\Debug\WMS\HeadsWMS\WMSProgram.cs:line 99 (ScErrFailingEntrypoint (SCERR4259))

(Double-click here for additional help)			0	
```

Anyone seen this thing before?

**Comment by miyconst** [comment]
Here is the fix for the issue above:

**Before** unpacking the downloaded `zip` or `rar` archive right click on it and unblock it.

![image](https://cloud.githubusercontent.com/assets/6435556/19013042/64f03030-87c6-11e6-8f2c-d2d673ab1e21.png)

Otherwise windows will mark the files as unsafe and the compiled assemblies as well. This will result in the error above on app start.

**Comment by miyconst** [comment]
And here is the fix for the main issue:

>Heads application do not work after upgrade to 2.2.1.3234

The application works, and as expected. The partial handling magic has been removed from Starcounter side. That is why the following partial usage no longer loads the partial:

```html
<template is="imported-template" content$="{{model.IndexPage.Html}}" model="{{model.IndexPage}}"></template>
```

This `model.IndexPage.Html` property was previously calculated and set by the server as sum of all HTML responses from all the partials. This magic is no longer there. Explanation:

**Before**

```js
partial: {
    Html: "/sc/htmlmerger?App1=App1Page.html&App2=App2Page.html",
    App1: { Html: "App1Page.html" },
    App2: { Html: "App2Page.html" }
}
```

**Now**

```js
partial: {
    App1: { Html: "App1Page.html" },
    App2: { Html: "App2Page.html" }
}
```

The `<imported-template>` element was never intended to be used to load Starcounter partials. There is a designated component called `<starcounter-include>` for this purpose. The component was adjusted to the new server behavior, that is why no migration guide is required.

Current solution - replace usage of `<imported-template>` with `<starcounter-include>`.

For example, this:

```html
<template is="imported-template" content$="{{model.IndexPage.Html}}" model="{{model.IndexPage}}"></template>
```

Should be replaced with:

```html
<starcounter-include partial="{{model.IndexPage}}"></starcounter-include>
```
