### ISSUE TITLE
Custom element with input with type bound to 'text' not working

### ISSUE THREAD

**Issue by thebrauer** [Starcounter/Starcounter#3867]
I have a custom element that has an input field in it. That input has a binding on type so you can control it from where it is implemented. If I try to send 'text' in type, nothing is bound but if I send anything else it works.

`<dom-module id="heads-input">
...
<input type="{{type}}" value="{{value}}">
...
Polymer({
            is: 'heads-input',
            properties: {
                type: {
                    type: String,
                    value: 'text'
                }
            },
});`

This doesn't work:
`<heads-input type="text" value="{{model.UserName$::input}}"></heads-input>`

However this does work:
`<heads-input type="password" value="{{model.UserName$::input}}"></heads-input>`
or:
`<heads-input type="foo" value="{{model.UserName$::input}}"></heads-input>`

AFAIK, this worked before upgrading to 2.2.1.3234. Is this something that you have noticed?

**Comment by tomalec** [comment]
I suspect it might be related to the fact that you bind to native element via property `type="{{` according to Polymer docs https://www.polymer-project.org/1.0/docs/devguide/data-binding you should do it like `type$="{{`

**Comment by thebrauer** [comment]
Yep, that did the trick! Strange that it just stopped working all of a sudden. And that password and number still worked. Thanks!

**Comment by tomalec** [comment]
> Strange that it just stopped working all of a sudden

Maybe you were using the SC version with Polymer <1.0

>  And that password and number still worked

attribute values provided as string works as usual, the only thing that require custom `$=` setter are binding from Polymer to native elements.
