### ISSUE TITLE
Starcounter apps don't work on iOS 10

### ISSUE THREAD

**Issue by Mnosek** [Starcounter/Starcounter#3871]
Starcounter apps don't work on iOS 10 at all. The window is blank (nothing renders) and there is an error in console: `TypeError: undefined is not an object (evaluating 'descriptor.value')`

As every iPhone user already got an update to the newest iOS 10 I think that it is a major issue.
### Affected browsers:

Chrome and Safari on iOS 10

I've investigated it a bit and it seems that it is a webcomponents issue. See the following links:
- https://github.com/webcomponents/webcomponentsjs/issues/617
- https://github.com/webcomponents/webcomponentsjs/issues/628
- https://github.com/webcomponents/webcomponentsjs/pull/618
- https://github.com/cucumber-tony/cucumber-frontend/issues/326

Should we try to deal with it on our own or wait for official webcomponents fix? Anyway, we should keep our finger on the pulse to do the update when it's available.

**Comment by dan31** [comment]
@Mnosek please CC those you think should participate in this issue and respond.

**Comment by dan31** [comment]
CC @warpech @tomalec @miyconst

**Comment by tomalec** [comment]
webcomponents.js update to V1 is coming soon (I bet it will happen at Polymer Summit)

**Comment by warpech** [comment]
Looking at the description, this is the same as https://github.com/PuppetJs/PuppetJs/issues/107

Solution is to call define this function: `window.showModalDialog = function(){};`

Are we doing something specific that triggers it?

**Comment by tomalec** [comment]
Fixed by updating the webcomponentsjs polyfill https://github.com/Starcounter/Starcounter/issues/3925

**Comment by tomalec** [comment]
Available since Starcounter 2.2.2.3627
