### ISSUE TITLE
Database kernel may hang deleting an object

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3875]
In certain cases, a database may hang deleting an object if there is a quite long binary or string field inside the record.
Other possible evidence of this problem could be the failure to find such a record using index on that field.

Found in 2.2. Possible reproduction in pnext is under investigation.

**Comment by bigwad** [comment]
Fixed for 2.2

**Comment by bigwad** [comment]
Note about how to apply the fix. 
The root cause of the problem is the wrong data in the record header. As 2.2 stores records in the image, just upgrading SC wouldn't help out. Unload/reload to the rescue.

**Comment by dan31** [comment]
@bigwad which means that those migrating to 2.2.2 would have to unload/reload the database whatsoever, as the image file would become incompatible? @bigwad pls add the reference to the fixed problem to https://github.com/Starcounter/Starcounter/blob/develop/CHANGELOG.md.

**Comment by bigwad** [comment]
No, it's not incompatible in any way.
2.2.2 will just work in the same way as 2.2.1 does. Hence, if kernel hangs deleting a record in 2.2.1, it will continue to hang deleting the same record in 2.2.2.
But, as we don't know whether a particular image is the subject of this problem or not, it's safer to always do unload/reload during upgrade to 2.2.2.

**Comment by bigwad** [comment]
Not a problem for 2.3
