### ISSUE TITLE
Is there any GUI tool for Startcounter to view Class hierarchy, fields,.. like traditional SQL?

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#3878]

**Comment by per-samuelsson** [comment]
@SenerDemiral 

Today, AFAIK, no there is not. Sorry.

We've had this discussion several times though, and we should make one at some point. There are some previous discussions on the tracker, for example in #3063.

**Comment by per-samuelsson** [comment]
Also, if you need something low-level to diagnose some condition, there is a thing you can do that I do from time to time. It's a command-line thing:

1. Browse to the folder of your Starcounter Application exe (e.g. `myapp\bin\debug\myapp.exe`).
2. Run `scweaver myapp.exe`. This will produce a folder named `.starcounter` under the current folder.
3. CD into `.starcounter`.
4. Run `scweaver schema myapp.exe`.

Leaving no guarantees on that though, since it can/probably will change in future versions.

**Comment by SenerDemiral** [comment]
It would be great!
Especially, coming from traditional SQL side.
I feel myself blind!

**Comment by SenerDemiral** [comment]
Trying to get meaningful view on Administrator SQL using
Starcounter.Metadata.Table
Starcounter.Metadata.Column
but...

I will try your suggestion.

**Comment by SenerDemiral** [comment]
How can I use StarcounterDB from Windows Forms Application? (Classic Desktop App)

**Comment by per-samuelsson** [comment]
> Trying to get meaningful view on Administrator SQL using
Starcounter.Metadata.Table
Starcounter.Metadata.Column
but...

Yeah, that's another alternative, but the way those are modeled is not always easy to understand, not even from an insider such as myself.

@k-rus Do we have any documentation on those? I know I've asked that before, but I keep forget. Maybe it would be good to just write a short help page on the most common ones.

**Comment by mtornwall** [comment]
> How can I use StarcounterDB from Windows Forms Application? (Classic Desktop App)

Unlike conventional database management systems, Starcounter doesn't provide a network protocol for issuing queries. This is because all application logic is running in the database itself, analogous to an application implemented entirely in stored procedures.

The easiest way to interact with a Starcounter application from the native world is through an HTTP-based protocol, such as a REST API.

**Comment by per-samuelsson** [comment]
> How can I use StarcounterDB from Windows Forms Application? (Classic Desktop App)

Moved that question (and the @mtornwall answer) into its own topic: #3881.

@SenerDemiral 

Do you feel your original question was fully answered? Can we close this issue?

**Comment by andwah** [comment]
> Trying to get meaningful view on Administrator SQL using
> Starcounter.Metadata.Table
> Starcounter.Metadata.Column
> but...

There is an app called DatabaseEditor in the appstore that can be used to see all tables and also edit values.

**Comment by SenerDemiral** [comment]
Thanks, I'll check it out now.

**Comment by k-rus** [comment]
> Trying to get meaningful view on Administrator SQL using
> Starcounter.Metadata.Table
> Starcounter.Metadata.Column
> but...
> Yeah, that's another alternative, but the way those are modeled is not always easy to understand, not even from an insider such as myself.
> 
> @k-rus Do we have any documentation on those? I know I've asked that before, but I keep forget. Maybe it would be good to just write a short help page on the most common ones.

Currently the best description can be found [here](http://stackoverflow.com/a/39490683/840340)

**Comment by dan31** [comment]
@SenerDemiral considering our current undertake for 2.3 RC to provide a new Unload/Reload, this tool will allow to export whole database to SQLite database. This will give people a way to use 3-rd party tools for editing and navigating their tables. We agree that, even though your tables are your classes, it becomes convenient to look at the whole data set "from the bird's eye view" prospective using good navigation tools.

The other option, which is also improving, is DatabaseEditor, which has been mentioned there already.

**Comment by SenerDemiral** [comment]
@dan31 How can I export database to SQLite? 
Is it enough to unload or is there any other export switch on staradmin command?

**Comment by dan31** [comment]
> @dan31 How can I export database to SQLite?
> Is it enough to unload or is there any other export switch on staradmin command?

Unload tool will use SQLite as a storage format for data. This is a separate tool that is not available yet.
