### ISSUE TITLE
GetType() not working in SQL

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3880]
I have 2 tables :
1. Parent
2. Child : Parent

When i query Parent table, I get all the object from child table, which is not what I want. I need only the Parent objects. I saw a note in [this](http://starcounter.io/guides/database/inheritance/) page, which says : 

> 
As a side note, you can use the GetType() function to get only instances of a exact class

```
SELECT C FROM Customer C WHERE Name LIKE 'Goldman%' 
  AND GetType() == typeof(Customer)

```

But this does not work in SC Admin Panel nor in Code. 
This the query I am running in Sc Admin Panel : 
```
SELECT po FROM AdFenix.Database.PublicationOwner po Where GetType() == typeof(AdFenix.Database.PublicationOwner)
```

and this is the code that I have in my solution:
```
Db.SQL<AdFenix.Database.PublicationOwner>("SELECT po FROM AdFenix.Database.PublicationOwner po Where GetType() == typeof(AdFenix.Database.PublicationOwner)");
```

**Comment by miyconst** [comment]
@atifwaqar there is an example of how to do that on starcounter.io - [Comparison predicates](http://starcounter.io/guides/sql/comparison-predicates/).

```sql
SELECT *
FROM MyNameSpace.Parent p
WHERE p IS MyNameSpace.Parent
```

**Comment by atifwaqar** [comment]
@miyconst For me its not working as expected, or may  be im not able to understand to concept of `WHERE p IS MyNameSpace.Parent`. 
Can you please take a look at this image and let me know if its explaining my point?

![issue](https://cloud.githubusercontent.com/assets/4388707/19321807/cbaf1f40-90b6-11e6-9bc7-f39a355b4ff0.png)


My expected result for : 
First query is `66`
Second query is `204` &`205`

**Comment by k-rus** [comment]
Operator `IS` verifies that object can be casted to the type, so the child object will be accepted by the predicate for its parent time. To my knowledge there is no syntax in our SQL to select only objects of a given type and exclude children. So currently a solution for you will be to filter objects in C# code or to redesign the class hierarchy. The second requires careful migration of data from one class hierarchy into another.

**Comment by miyconst** [comment]
@atifwaqar in your case you can add a custom property:

```cs
[Database]
public class Parent {
    public string TypeName {
        get { return this.GetType().FullName; }
    }
}
```

It will be available in SQL like:

```sql
SELECT *
FROM MyNameSpace.Parent p
WHERE p.TypeName = 'MyNameSpace.Parent'
```

**Comment by atifwaqar** [comment]
Thanks for the help guys. 
I am not using this solution though. I changed my logic entirely. 
But thanks anyway :)
