### ISSUE TITLE
How can I use Starcounter from Windows Forms Application? (Classic Desktop App)

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3881]
The question was originally posted in this https://github.com/Starcounter/Starcounter/issues/3878#issuecomment-253221351 by @SenerDemiral:

> How can I use StarcounterDB from Windows Forms Application? (Classic Desktop App)

@mtornwall provided the first answer ([here](https://github.com/Starcounter/Starcounter/issues/3878#issuecomment-253242617)):

> Unlike conventional database management systems, Starcounter doesn't provide a network protocol for issuing queries. This is because all application logic is running in the database itself -- you could think of it as the application being implemented entirely in stored procedures.

> The easiest way to interact with a Starcounter application from the native world is through an HTTP-based protocol, such as a REST API.

**Comment by SenerDemiral** [comment]
What a  sad news!
There is super fast DataBase in my hand, but I can't use in Desktop App.

**Comment by per-samuelsson** [comment]
> There is super fast DataBase in my hand, but I can't use in Desktop App.

We are actually working on a complementary hosting model, where Starcounter will be possible to run in a way that more resemble a transitional client-server model. In such case, the desktop app could "connect" to Starcounter and utilize the same services as apps do today.

It's planned for an upcoming release sometime this year, or in the beginning of next, but I won't dare make any final promises on it yet.

Follow #3869 for progress.

**Comment by SenerDemiral** [comment]
Good news.
It is possible to write more solid DB tools then.

**Comment by mtornwall** [comment]
@SenerDemiral Perhaps I misunderstood your question. Do you want to use Starcounter as an *embedded* database, distributed with a desktop application?

**Comment by SenerDemiral** [comment]
No I want to use Starcounter as SQL Server in LAN. Not embedded!

**Comment by mtornwall** [comment]
@SenerDemiral 

In that case you can definitely use Starcounter, but you have to expose your database objects through a custom API (e.g., REST). You still get the benefits of a VMDBMS if you implement most of your application logic on the Starcounter side.

**Comment by SenerDemiral** [comment]
You are right, it is the only way (e.g., REST) by now.

**Comment by mtornwall** [comment]
@SenerDemiral Do you feel that your question has been adequately answered? If so, do you mind if I close the issue?

**Comment by SenerDemiral** [comment]
Please close.
