### ISSUE TITLE
How can drop class/table property/column in production database?

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#3882]

**Comment by per-samuelsson** [comment]
In the current version of Starcounter, the class model is defines the schema, so dropping a "table" / "column" would be done by removing the corresponding item from the domain code.

**Comment by SenerDemiral** [comment]
If accidentally rename some field of table and run.
What happens to oldField data?

**Comment by SenerDemiral** [comment]
oldField's data stay in DB! 
Means you can't drop field with data, only hide.

**Comment by per-samuelsson** [comment]
> oldField's data stay in DB! 
Means you can't drop field with data, only hide.

I'm quite sure that's by design. And the way to physically remove the data is by issuing an [unload](http://starcounter.io/guides/tools/staradmin/#unload-command) (and a corresponding [reload](http://starcounter.io/guides/tools/staradmin/#reload-command)).

@k-rus, can you confirm this please?

**Comment by SenerDemiral** [comment]
Changing of field string to int in production DB is a long and exhausting journey.

**Comment by k-rus** [comment]
> oldField's data stay in DB! 
> Means you can't drop field with data, only hide.
> I'm quite sure that's by design. And the way to physically remove the data is by issuing an unload (and a corresponding reload).
> 
> @k-rus, can you confirm this please?

In 2.2 data from old field is removed. So if a property is renamed by mistake, the data will be gone. In 2.3 the data from old filed are kept in the database.



> Changing of field string to int in production DB is a long and exhausting journey.

I confirm that we currently we don't have support for schema refactoring.

**Comment by SenerDemiral** [comment]
I'm already using 2.3..
Is behaviour stay as 2.3 in the feature?

**Comment by k-rus** [comment]
> Is behaviour stay as 2.3 in the feature?

Can you clarify your question? I don't follow to which feature you relate here.

**Comment by SenerDemiral** [comment]
Ok. 
You already answered question.
 In future 2.3 the data from old filed are kept in DB
