### ISSUE TITLE
Installer fails when upgrading from 2.2.1.3234 to 2.2.2.3422

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3885]
![image001](https://cloud.githubusercontent.com/assets/1658979/19343408/6760ab82-9136-11e6-84ea-6c90a28bc413.png)

**Comment by chrhol** [comment]
cc @alemoi, @per-samuelsson

**Comment by alemoi** [comment]
Hmm, my initial guess would be that a DLL wasn't added to white-list by the author?

**Comment by alemoi** [comment]
However this sccoredbh.dll DLL seems to be in the white list:

https://github.com/Starcounter/Starcounter/blob/develop/src/BuildSystem/WhiteList.txt

**Comment by chrhol** [comment]
It was reported by @IdieHeads, I will try it locally and see what happens.

**Comment by chrhol** [comment]
I get this as well when trying to install 2.2.2.3422. The previous versions works fine, and latest develop (compiled by me) seems to work as well. I will try a new installer from a daily build and see.

**Comment by chrhol** [comment]
Still occurs on installer from daily build. So something has happened after version 2.2.2.3391

**Comment by alemoi** [comment]
So there is some file dependency. I have a guess why its so. Let me build a new version of develop.

**Comment by alemoi** [comment]
@chrhol thanks for testing and reporting, the fix is pushed! Forgot to add a dependency extraction. I have started a "short" develop nightly now.

**Comment by dan31** [comment]
@alemoi I wonder whether it is possible to add such test: upgrade the latest installed Stable to the latest available Nightly. Feasible?

**Comment by alemoi** [comment]
Feasible when I add a silent version working. Now its only manual.
