### ISSUE TITLE
Question : Is there a way to have a Commit Hook `BeforeUpdate` like we have `BeforeDelete`?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3886]
I am working on TransactionHistory. And I want to keep both states of DB Object : 
1. Before Updating the object (Old State)
2. After Updating the object (New State)

For now I have only the new State. How can I have the old state?

**Comment by per-samuelsson** [comment]
> Question : Is there a way to have a Commit Hook `BeforeUpdate` like we have `BeforeDelete`?

I'm afraid there is not. And it's quite hard to achieve too, for several reasons, so it's unlikely we can implement it on that level.

**Comment by atifwaqar** [comment]
@per-samuelsson Thanks for the response.
If its hard then I think I have a simple solution for it. 
Just mentioning here so that if anyone else need this solution : 

1. When I create the object, I'll transact it in my `TransactionHistory` table 
2. When I update the object, I'll transact the changed object in my `TransactionHistory` table 
3. When I update the object again, I'll transact the changed object in my `TransactionHistory` table

This way I have all the 3 states of my object.
