### ISSUE TITLE
Refactor the TypedJSON serializer.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3887]
The current implementation of the serializer has some flaws, which leads to some strange (and bad!) errors, for example #3600. 

Should be refactored and problably use Newtonsoft internally instead of our custom-made writer, so a prerequisite for this issue is #3811

Will be changed only in 2.3+

**Comment by chrhol** [comment]
I have been working on this for a while, and as usual I found some strange stuff not directly related to the serializer that also needs to be fixed for everything to work.

Current status is that the serializer is rewritten, the code in jsonpatch that reads and writes json have been rewritten and currently I'm looking into the methods that checks and gather changes. 

All code that requires `unsafe` have been removed and the flag to allow unsafe code is unchecked. The only thing left is a couple of obsoleted methods that takes `IntPtr`.

And I guess this should be merged to upcoming 2.4 since it contains rather large changes.

**Comment by per-samuelsson** [comment]
> And I guess this should be merged to upcoming 2.4 since it contains rather large changes.

If they won't affect the user in terms of that he/she need to change application code it should be fine to target 2.3, if you think that would be better.

**Comment by chrhol** [comment]
Added a separate issue for the dirtycheck problems. 

> If they won't affect the user in terms of that he/she need to change application code it should be fine to target 2.3, if you think that would be better.

I don't think it will require any changes from usercode, I will test it with some of our and our customers apps when it's in a working state  and see. It would be good to get this in as soon as possible I guess.

**Comment by chrhol** [comment]
I've been testing this and made a few fixes for bugs that I found. So far I can see no breaking changes, and the old API is still there but obsoleted. It's probably a good idea then to push this to 2.3 (and not wait for 2.4)

I think everything is in shape to be merged. I will do a few more runs with some apps before merging, but the plan is to do it today.

**Comment by chrhol** [comment]
Code merged and pushed.
