### ISSUE TITLE
Upgrade to Polymer 1.7

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3888]
Polymer 1.7 is out since few days. 

@tomalec have you evaluated it? What is the status of upgrading to it in Starcounter?

Related: https://github.com/Starcounter/CompanyTrack/issues/233

**Comment by tomalec** [comment]
Currently, I'm evaluating Polymer 2.0 https://github.com/Starcounter/CompanyTrack/issues/233

**Comment by warpech** [comment]
Thanks for upgrading. Any details about this? Is this painlessly backwards compatible?

**Comment by tomalec** [comment]
From what I tested it seems pretty painless.
But gives us possibility to use v1's `<slot>` which is nice step forward migrating our Polymer elements to 2.0 and v1
