### ISSUE TITLE
Strange issue appears when using 'DatabaseEditor'

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3893]
SC Version 2.2.2.3422
DatabaseEditor : Installed directly from App Warehouse.

When I query in SC Admin Panel, everything works fine, and i can see the results like this : 
![image](https://cloud.githubusercontent.com/assets/4388707/19479267/2e4481b6-9546-11e6-9aaa-5d692f282982.png)

When I try to view the same table in DatabaseEditor app I get this : 
![image](https://cloud.githubusercontent.com/assets/4388707/19479360/972a9440-9546-11e6-9e5d-3dfe8ab1e563.png)

**Comment by andwah** [comment]
thanks for reporting.. The database editor is a "side" project of mine.  
The problem you found is known by me.. some property names in the classes is not working good together with the bound json object. (the json also have the same property name).

 Im trying to find a solution/workaround.

**Comment by andwah** [comment]
Here is the DatabaseEditor repo: https://github.com/Smorgasbord-Development/DatabaseEditor

**Comment by atifwaqar** [comment]
BTW I install this app from your SC App Warehouse. 
Do I get the latest build from there?

**Comment by atifwaqar** [comment]
And I am facing 2 type of errors. 1 is mentioned already.
2nd one is as following (I guess this is the one you already know): 
```
System.Exception: ScErrCreateDataBindingForJson (SCERR14006): Cannot create binding between typed json and dataobject. Incompatible types for binding. Json property '<noname>.Parent' (System.String), data property 'Starcounter.Json.Parent' (Starcounter.Json).
Version: 2.2.2.3422.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14006.
 
```
And this is the page that I see : 
![image](https://cloud.githubusercontent.com/assets/4388707/19481284/a8e33ad2-954d-11e6-8e89-6586059866d5.png)

**Comment by andwah** [comment]
> BTW I install this app from your SC App Warehouse. 
> Do I get the latest build from there?

Yes.

i think i would be good in the future to report DatabaseEditor issues here: https://github.com/Smorgasbord-Development/DatabaseEditor/issues 

Thanks in advance

**Comment by per-samuelsson** [comment]
> i think i would be good in the future to report DatabaseEditor issues here: https://github.com/Smorgasbord-Development/DatabaseEditor/issues

I took the freedom to open an issue, with a back-reference to this one for background:

https://github.com/Smorgasbord-Development/DatabaseEditor/issues/2

I hope that was what you wanted @andwah. Otherwise, feel free to reopen this one.
