### ISSUE TITLE
Is it a Starcounter Thread?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3895]
Is there any way of checking if the current thread is an attached thread?

**Comment by chrhol** [comment]
You can call `StarcounterEnvironment.IsOnScheduler()` to check or get the schedulernumber by `StarcounterEnvironment.CurrentSchedulerId` which will return `StarcounterEnvironment.InvalidSchedulerId` (255) if the current thread is not a starcounter thread.

**Comment by careri** [comment]
Great, thanks
