### ISSUE TITLE
pnext: an item created inside Db.Transact is not returned by SELECT x WHERE x

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3899]
I have a very weird situation.

``` cs
var sessionId = Starcounter.Session.Current.SessionId;

Db.Transact(() => {
    var context = new Context() { SessionId = sessionId };

    QueryResultRows<Context> list = Db.SQL<Context>("SELECT c FROM Palma.Context c WHERE SessionId = ?", sessionId);

    Context context = list.First; 
    // context is NULL here!

    if (context == null)
    {
        list = Db.SQL<Context>("SELECT c FROM Palma.Context c");
        context = list.ToList().FirstOrDefault(x => x.SessionId == sessionId);
        // context is NOT NULL here!
    }
});
```

The current `sessionId` value is `BBD4D29B246E413600000010`, but it happens with any other value as well.

I tried to setup a small solution to reproduce it, but was not able to. This happens on `pnext` only, never seen on `develop`, also it does not happen after page reload, only on cold database start.

Here is a screenshot from Visual Studio, but I doubt it will help debug the issue anyhow.

![image](https://cloud.githubusercontent.com/assets/6435556/19567722/1f7d275a-96ef-11e6-8f79-981be874db68.png)

@k-rus what else can I check or provide to locate the error?

**Comment by k-rus** [comment]
Is `sessionId` always so large? What is difference between cold and warm execution in terms of database data and `sessionId` data? What is the type of `SessionId`?

We have some bugs related to some values, see #3226 
 This will explain why the query with where clause has different result then the query without where clause.

How can we reproduce the bug in our local environment that we can debug it?

**Comment by miyconst** [comment]
>Is `sessionId` always so large?

Yes.

>What is difference between cold and warm execution ...

- There is one finished transaction which inserts an item into `Palma.Context`.
- The `SessionId` value is changed to a new one.

>How can we reproduce the bug in our local environment that we can debug it?

You can come to me, and I show it.

**Comment by k-rus** [comment]
> What is difference between cold and warm execution ...
> There is one finished transaction which inserts an item into Palma.Context.
> The SessionId value is changed to a new one.

Thank you for clarifying. It feels like a problem related to shadow indexes, which is responsibility of the kernel team, i.e., @bigwad and @eriohl . Is there an index on `SessionId`? Will the query work correctly if you remove the index?



> How can we reproduce the bug in our local environment that we can debug it?
> You can come to me, and I show it.

I don't know how it can help without source code of Level1 and build in Debug configuration if it is a bug in Starcounter. Do you have this environment (i.e., source code of Level1 and installation from local Debug build) on your machine?

**Comment by bigwad** [comment]
I suspected kernel issue and tried to reproduce it yesterday, but failed. @miyconst, will be great if you could make some compact project to reproduce.

**Comment by miyconst** [comment]
>It feels like a problem related to shadow indexes ...

Yes, there is an index on `SessionId`, and I also suspect it to be the cause. I will check whether it works without the index.

>I suspected kernel issue and tried to reproduce it yesterday, but failed. @miyconst, will be great if you could make some compact project to reproduce.

As I have already wrote, unfortunately I can't reproduce the issue in a small solution with a small database. It happens only in this particular database, and only on `pnext`.

**Comment by bigwad** [comment]
Ok, please share to me all I need to reproduce it. 
Perfect scenario for me is if you share:
- binary code
- database image (as small as possible)
- REST-endpoint, that I may invoke to get 100% reproduction.

**Comment by miyconst** [comment]
>It feels like a problem related to shadow indexes ...

The issue has gone as soon as I dropped the index.

**Comment by miyconst** [comment]
@bigwad is now able to reproduce the issue with binaries and steps from me.

**Comment by bigwad** [comment]
Hopefully, fixed. Should be available in the upcoming nightly.

**Comment by miyconst** [comment]
I confirm the fix.

**Comment by miyconst** [comment]
@bigwad I have met the same issue one again. This time the index and `WHERE` is applied on a reference column. Will approach you tomorrow to debug.

**Comment by eriksunsol** [comment]
Some additional information about this particular index (N1PropertyAtom1NameChangeSetTimestampIdx), just in case it helps.

There are three participating fields:
 - a reference to another [Database] object
 - a string
 - a long, sorted descending

We have many indexes like this one, also with more participating fields.

**Comment by miyconst** [comment]
@eriksunsol thank you for the additional info. I have already supplied @bigwad was binaries and instructions to reproduce, so let's see whether it is possible to fix quickly.

**Comment by bigwad** [comment]
@miyconst , @eriksunsol 
Would it change anything if you make long field to be sorted ascending? Then I guess it the same as https://github.com/Starcounter/Starcounter/issues/3936

**Comment by miyconst** [comment]
No, it does not make any difference.

Here are the lines of code:

```cs
List<N1Property> sql = Db.SQL<N1Property>("SELECT np FROM Palma.N1Property np WHERE Atom1 = ? AND Name = ? ORDER BY ChangeSetTimestamp DESC",
                    admin, nameof(admin.InExistence)).ToList();
```

```cs
List<N1Property> linq = Db.SQL<N1Property>("SELECT np FROM Palma.N1Property np WHERE Name = ? ORDER BY ChangeSetTimestamp DESC",
                    nameof(admin.InExistence)).Where(x => x.Atom1.Equals(admin)).ToList();
```

The first one returns zero records, the second one returns one record. Changing `DESC` to `ASC` does not make any difference.

**Comment by bigwad** [comment]
@miyconst, I meant sorted in the index, not in the query.

**Comment by miyconst** [comment]
Yes. Replacing `DESC` to `ASC` in the index definition makes it work as expected.

**Comment by bigwad** [comment]
Great. I'll keep this issue open until I fix #3936 and then I'll check it again.

**Comment by bigwad** [comment]
Regarding the question of possible performance pitfalls.
Sad to say, but I suspect index is not used to full extent in your query. Even before you changed the sorting order. For me, it's a bug in QueryProcessor, but it's easy to get around it.

Let me explain: if you have an index over fields {F<sub>1</sub>,..., F<sub>n</sub>}, you may expect index to be used if you have comparison of all except the last field in WHERE clause and then sort by the last field. Like:
SELECT * FROM table WHERE F<sub>1</sub>=C<sub>1</sub> AND ... AND F<sub>n-1</sub>=C<sub>n-1</sub> ORDER BY F<sub>n</sub>

And the sort order you specified in index definition doesn't matter here. It should work either way.
But according to query plan (that you may see in administrator), in this case index is used only for processing WHERE clause, but not for results ordering. Probably, it's something to let @k-rus know about.

To overcome it, just add all the fields in ORDER BY clause:
SELECT * FROM table WHERE F<sub>1</sub>=C<sub>1</sub> AND ... AND F<sub>n-1</sub>=C<sub>n-1</sub> ORDER BY F<sub>1</sub>,...,F<sub>n</sub>

And about reversing sorting order in the query. You may do so and still employ the index only if toggle order for all fields. Say query should still use the index:
SELECT * FROM table WHERE F<sub>1</sub>=C<sub>1</sub> AND ... AND F<sub>n-1</sub>=C<sub>n-1</sub> ORDER BY F<sub>1</sub> DESC,...,F<sub>n</sub> DESC

And the last note - I recommend to pay attention to the query plan builder to make sure your indices are  used as you expected. Probably, you'll find some flows in query optimizer if they aren't.

**Comment by k-rus** [comment]
> Regarding the question of possible performance pitfalls.
> Sad to say, but I suspect index is not used to full extent in your query. Even before you changed the sorting order. For me, it's a bug in QueryProcessor, but it's easy to get around it.
> 
> Let me explain: if you have an index over fields {F1,..., Fn}, you may expect index to be used if you have comparison of all except the last field in WHERE clause and then sort by the last field. Like:
> SELECT * FROM table WHERE F1=C1 AND ... AND Fn-1=Cn-1 ORDER BY Fn
> 
> And the sort order you specified in index definition doesn't matter here. It should work either way.
> But according to query plan (that you may see in administrator), in this case index is used only for processing WHERE clause, but not for results ordering. Probably, it's something to let @k-rus know about.
> 
> To overcome it, just add all the fields in ORDER BY clause:
> SELECT * FROM table WHERE F1=C1 AND ... AND Fn-1=Cn-1 ORDER BY F1,...,Fn
> 
> And about reversing sorting order in the query. You may do so and still employ the index only if toggle order for all fields. Say query should still use the index:
> SELECT * FROM table WHERE F1=C1 AND ... AND Fn-1=Cn-1 ORDER BY F1 DESC,...,Fn DESC
> 
> And the last note - I recommend to pay attention to the query plan builder to make sure your indices are used as you expected. Probably, you'll find some flows in query optimizer if they aren't.

@bigwad Thank you for investigating and describing the issue with the query optimiser. It is clearly a bug in the old query optimiser. I haven't created new issue, but added to this list https://github.com/Starcounter/RebelsLounge/issues/49

**Comment by miyconst** [comment]
@eriksunsol as it turns out the `DESC` index does not help much in our case, at least for now. Can we use `ASC` till this issue is resolved?

**Comment by miyconst** [comment]
@bigwad do we have any estimation of when this issue can be fixed?

**Comment by bigwad** [comment]
Not yet. Probably next week. But workaround works for you, doesn't it?

**Comment by miyconst** [comment]
Next week is fine. Thank you. Yes, workaround works in this particular place, but the issue is difficult to and time consuming to debug, so I would not like to hit it in some other place.

**Comment by eriksunsol** [comment]
@bigwad Thanks for pointing out that the indexes are not fully utilized in our code. We (or at least I) have clearly not payed enough attention to the query plan builder when setting up our indexes.

@k-rus Is there an estimate on when the issue with the optimizer will be fixed? (I can't access https://github.com/Starcounter/RebelsLounge/issues/49 to monitor the progress.)

**Comment by k-rus** [comment]
> @k-rus Is there an estimate on when the issue with the optimizer will be fixed? (I can't access https://github.com/Starcounter/RebelsLounge/issues/49 to monitor the progress.)

So far it is not planned to be done in 2.x.

**Comment by k-rus** [comment]
> @k-rus Is there an estimate on when the issue with the optimizer will be fixed? (I can't access Starcounter/RebelsLounge#49 to monitor the progress.)
> So far it is not planned to be done in 2.x.

We are working on new query processor using different stack. It will be available in 3.x. It might be available in 2.x at some point too.

**Comment by bigwad** [comment]
@miyconst,
please check out the latest nightly

**Comment by miyconst** [comment]
Tried `Starcounter-PnextNightlyBuilds-2.3.0.5099 (Nov 29, 2016 2:01:54 AM)`, the issue is not fixed.

**Comment by bigwad** [comment]
Do you run the same test you gave me? Because it runs fine for me.

**Comment by miyconst** [comment]
@bigwad sorry, it was the same test with some "extra" lines from me, which broke it. Re tested again, and it works.

Thank you for fixing the issue.
