### ISSUE TITLE
App build fails on pnext - newtonsoft is missing

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3900]
[failing build](https://teamcity.starcounter.org/viewLog.html?buildId=12018&tab=buildResultsDiv&buildTypeId=Starcounter_Apps_KitchenSink_KitchenSinkPnext)
Probably because of [this task](https://github.com/Starcounter/Starcounter/issues/3811) not having added newtonsoft to public assemblies.

cc @chrhol

**Comment by chrhol** [comment]
Already reported in https://github.com/Starcounter/AdminTrack/issues/133

I thought it was just on one buildserver. Missed the whole Apps project in teamcity. Working on a fix now, will close this one and keep track in the other.
