### ISSUE TITLE
The unload commad stacks after the first time

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3903]
I have a big database (600mb in SQL) and trying to unload it for the second time in a row. It hangs forever. Showing the following message for more than five minutes.  The dots are changing from `.`, `..`, `...` means the app is doing something, but nothing happens.

```
Unloading default (restarting default (and 2 other executable(s)) ...)
```

Unloading database works for the first time, when `Starcounter_Internal_Unload_Utility` is not started.

Steps to reproduce:

- Create an empty database.
- Start all the apps required to access database classes.
 - The apps should not create any objects in the database on start.
- Reload an SQL script into the database.
 - Make sure that `Starcounter_Internal_Reload_Utility` is still running.
- Unload database with `staradmin unload`.
- Do the `staradmin unload` once again.
- It hangs with `Unloading default (restarting default (and 2 other executable(s)) ...)`.

After this I am also not able to stop `Starcounter_Internal_Unload_Utility` or `Starcounter_Internal_Reload_Utility`. No errors, no log entries, it just stuck.

![image](https://cloud.githubusercontent.com/assets/6435556/19636259/8b8b8302-99c8-11e6-9b0e-ebad411a517e.png)

cc @andwah, @per-samuelsson, @alemoi, @k-rus

**Comment by miyconst** [comment]
Some investigation shows, that the issue happens to newly reloaded database only. Steps to reproduce updated.

**Comment by miyconst** [comment]
This issue is also applicable for `pnext`.

**Comment by per-samuelsson** [comment]
@miyconst 

Sorry to see you experience this. I think it's a problem since quite long, and just that it has passed under the radar when we prioritize what things to do. It's probably on me.

Could be a duplicate, or at least related, to #2506. Can you take a look and see if the workaround described there is applicable?

**Comment by miyconst** [comment]
Yes, I think my issue is a duplicate of [After staradmin unload apps cannot be restarted](https://github.com/Starcounter/Starcounter/issues/2506). I close this one.
