### ISSUE TITLE
Exclusive access to the session with id {0} could not be obtained

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3904]
SC Version 2.2.1.3234

My dashboards are not opening, and in error log i see lots of these errors : 

![image](https://cloud.githubusercontent.com/assets/4388707/19643304/f12281c2-99e9-11e6-98e2-b559910c0f5d.png)

**Comment by miyconst** [comment]
@atifwaqar in Starcounter session is not a thread safe object. Currently all the session tasks are executed one by one, not in parallel.

If one of the tasks is not able to execute within three minutes then it throws the exception.

Please use `Starcounter.Scheduling.ScheduleTask` instead of `Session.Scheduling.ScheduleTask` to execute long running tasks, in this case your session will not be blocked for so long time.

**Comment by atifwaqar** [comment]
And when I tried to stop SC apps :
1. Signin
2. UserAdmin
3. Launcher 

Just stopping them took 7+ min. Here is what i see in RAM : 
![image](https://cloud.githubusercontent.com/assets/4388707/19643396/6214a2f2-99ea-11e6-8f95-38b4086d709c.png)
![image](https://cloud.githubusercontent.com/assets/4388707/19643428/8c942804-99ea-11e6-8e9c-2408bf3cb35c.png)
![image](https://cloud.githubusercontent.com/assets/4388707/19643447/ac21951c-99ea-11e6-8b01-f39f597371a8.png)
![image](https://cloud.githubusercontent.com/assets/4388707/19643479/dc6dee28-99ea-11e6-83f1-3e893f507cd6.png)
![image](https://cloud.githubusercontent.com/assets/4388707/19643496/ee466db4-99ea-11e6-91df-35b210dd6619.png)
![image](https://cloud.githubusercontent.com/assets/4388707/19643505/fe2b490c-99ea-11e6-8c37-ed40681001bd.png)
![image](https://cloud.githubusercontent.com/assets/4388707/19643517/0d0f6a02-99eb-11e6-91da-cec55425663a.png)
![image](https://cloud.githubusercontent.com/assets/4388707/19643540/20c3ab30-99eb-11e6-906c-e7dada2bf8e0.png)
![image](https://cloud.githubusercontent.com/assets/4388707/19643572/4d75ceec-99eb-11e6-9b03-f469f8538552.png)
![image](https://cloud.githubusercontent.com/assets/4388707/19643592/5c1e8498-99eb-11e6-9ba9-4dce2b374c1d.png)

**Comment by miyconst** [comment]
Judging from the graphs, I can assume that the `AdFenix` app has some serious memory leakage.

Starcounter tries to stop the apps without terminating running processes. If you have endless tasks running in background, it may cause very long stopping time. Please read more here - [Running background jobs](http://starcounter.io/guides/transactions/running-background-jobs/).

Also you can terminate all the Starcounter threads with the following command, it won't take long:

```
staradmin kill all
```

**Comment by atifwaqar** [comment]
> Please use Starcounter.Scheduling.ScheduleTask instead of Session.Scheduling.ScheduleTask to execute long running tasks, in this case your session will not be blocked for so long time.

I dont have a single call to `Session.Scheduling.ScheduleTask` in my code. any idea why i still get the log message?

**Comment by miyconst** [comment]
There might be are multiple reasons:

- `Program.Main` runs forever or very long time.
- Application handlers run forever or very long time (when requested).
- A commit hook runs forever or very long time.
- Page handlers (button click) run forever or very long time (when triggered).

**Comment by atifwaqar** [comment]
I see.
Ok then, i'll investigate my code to fix this behavior. I'll update this thread if I find something.
Thanks for the info @miyconst  :)

**Comment by dan31** [comment]
Arcived.
