### ISSUE TITLE
Question : How to solve Symbols loading issue

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3905]
Hi guys, this may not be Starcounter specific issue, but you guys may have seen it. Any suggestion will be really appreciated. 
On one of our server VisualStudio is not loading sccode.exe under modules, and im not able to debug my code. This image may explain a bit : 
![debugger issue](https://cloud.githubusercontent.com/assets/4388707/19664662/c7b4b668-9a41-11e6-9c55-c85754da3ba3.png)

And this is how it looks like at my local machine : 
![image](https://cloud.githubusercontent.com/assets/4388707/19664720/0d4d83c6-9a42-11e6-82fb-9800c7f0859e.png)

**Comment by per-samuelsson** [comment]
@atifwaqar 

It might be the result of how Starcounter execute - in "production mode" vs "developer mode". If Starcounter is running in Windows level 0, you won't be able to debug `sccode` without administrative privileges.

Can you take a look if that could be so?

**Comment by bigwad** [comment]
Another guess. Looks like you're attaching a native-mode debugger to the running process. Make sure you pick managed architecture instead:
![image](https://cloud.githubusercontent.com/assets/2953584/19676425/9c6069a0-9a94-11e6-899b-1b701cf966da.png)

**Comment by atifwaqar** [comment]
@bigwad You are a life & time savor. He've been trying this for last 2 days :D
and you fixed the issue in a second, Thanks a lotttt :)
