### ISSUE TITLE
Assertion failure in scllvm.dll

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3906]
I tested on latest 2 builds : 
2.2.2.3484 (Oct 24, 2016 3:01:43 AM)
2.2.2.3476 (Oct 21, 2016 3:01:50 AM)

When I start me Database, i get a weird windows error, and DB does not start after it. Please verify if this is only on my local machine or everyone else have the same issue?

![image](https://cloud.githubusercontent.com/assets/4388707/19680153/e5e1811c-9aa4-11e6-8bee-e9d68b4627dd.png)

I installed 2.2.2.3422 (Oct 13, 2016 5:01:30 AM) and things work fine for me now.

**Comment by miyconst** [comment]
@atifwaqar thank you for reporting this.

Can you please check if there are any log entries regarding the exception?

cc @alemoi, @bigwad

**Comment by atifwaqar** [comment]
This is what i see. But im not sure if they are related.


![image](https://cloud.githubusercontent.com/assets/4388707/19680808/608a4ad2-9aa7-11e6-8739-942c8b03ae74.png)

**Comment by per-samuelsson** [comment]
An assertion failure would normally not generate anything in the log I think. This is very likely some recently introduced internal bug. Let's see what @alemoi has to say about it.

**Comment by per-samuelsson** [comment]
@atifwaqar, hope you don't mind I changed the title. ✋

**Comment by atifwaqar** [comment]
@per-samuelsson I have no issues at all. Its your GH :P

**Comment by alemoi** [comment]
Yes, its an internal issue we encounter for the first time. @atifwaqar so the server starts fine? So its not even when starting the app, but starting a database by the means of Administrator?

**Comment by alemoi** [comment]
Additional question: does it happen on a specific database or even if you create a new one and then try to start it?

**Comment by atifwaqar** [comment]
> so the server starts fine? So its not even when starting the app, but starting a database by the means of Administrator?

Yes server starts fine. And when I start the Default Databsae (not app), I get the error. 

> Additional question: does it happen on a specific database or even if you create a new one and then try to start it?

And I never had any database other than Default. so i cant comment on this

**Comment by alemoi** [comment]
> And I never had any database other than Default. so i cant comment on this

Can you please create a new database in admin and try to start the database?

**Comment by alemoi** [comment]
After diagnosing using a remote session I have a clue now. I initially decided to skip versioning for scllvm folders but now I will introduce it back. Seems old clang produced the modules that were incompatible with the newest version. Going to create a patch.

**Comment by alemoi** [comment]
@atifwaqar I just pushed a new version of scllvm that uses versioning subfolders. Please test the new develop nightly (if it succeeds). I hope it was not a problem with SHA256 hash collisions though! Thanks for testing!

**Comment by atifwaqar** [comment]
testing

**Comment by chrhol** [comment]
> Please test the new develop nightly (if it succeeds).

The latest nightly build failed, so I dont think the last version available on the download page contains the fix.

**Comment by atifwaqar** [comment]
@chrhol how can i get that build ?

**Comment by chrhol** [comment]
I will start a new build with some long running tests disabled, but it will take some time.

**Comment by chrhol** [comment]
Actually I might have been wrong. The latest build failed, but version 3506 should contain the fix from @alemoi. He started a separate build. @atifwaqar: then you should be able to use that one

**Comment by atifwaqar** [comment]
I tried, I dont get the error message now, but the DB never starts.

**Comment by chrhol** [comment]
Do you get anything in the log?

**Comment by alemoi** [comment]
Predicting that nightly will fail on build agent 3, I started another one on agent 2, that succeeded.

**Comment by alemoi** [comment]
Added as a requirement not to run on `scbuildwin03` until I find what's the deal with TPCA:
```
[03:05:17]Cloning into 'C:\TeamCity\BuildAgent\work\sc-develop-nightly-542\tpc-a'...
[03:05:17]bash: /dev/tty: No such device or address
[03:05:17]error: failed to execute prompt script (exit code 1)
[03:05:17]fatal: could not read Username for 'https://github.com': Invalid argument
[03:05:17]System.Exception: Can't clone repository: https://github.com/starcounter/tpc-a.git
```

**Comment by alemoi** [comment]
Ok, I found it. The issue was actually fixed in the different branch. Had so many branches that I forgot to merge from one of it. @atifwaqar thanks for you environment access. Apparently it was reproducible only on your machine :smile: Here is a new build: http://downloads.starcounter.com/download/Starcounter/DevelopDailyBuilds/2.2.2.3511

**Comment by atifwaqar** [comment]
Thanks @alemoi. Server and Db starts fine now. 
But i suspect that Server starting is slow, not sure though, let me confirm this thing now.

**Comment by alemoi** [comment]
> But i suspect that Server starting is slow, not sure though, let me confirm this thing now.

Do that after a few starts. It should start fast after this.

**Comment by atifwaqar** [comment]
Perfect @alemoi 
Thanks alot for the fix :)
