### ISSUE TITLE
Question : Why is my code trying to find dll in SC installation folder?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3908]
I am using a 3rd party Dll, and its using NewtonSoft latest version. 
I have Newtonsoft Json package installed in my project, but when i run the code, it tries to find the dll in SC installation folder : 
![image](https://cloud.githubusercontent.com/assets/4388707/19687524/f95a2b74-9ac5-11e6-9e8b-233397ac017b.png)

Any idea where am i going wrong?

**Comment by SenerDemiral** [comment]
Unrelated but there is another alternative,
http://www.codeproject.com/Articles/159450/fastJSON

**Comment by per-samuelsson** [comment]
Probably related to #3811, and should be eventually resolved by #1620.

@chrhol, would you agree that could be a cause for this?

**Comment by atifwaqar** [comment]
@SenerDemiral I agree with you, but I dont understand why is my code trying to access 
`C:\Program Files\Starcounter\sccode.exe.Config`
instead of 
`C:\adfenix-backend\src\bin\Debug\AdFenix.exe.config`
Thats why I posted the issue here.

**Comment by chrhol** [comment]
> @chrhol, would you agree that could be a cause for this?

I dont think so in this case. @atifwaqar, you're running on Starcounter 2.2 right? #3811 is only pushed to 2.3

**Comment by atifwaqar** [comment]
@chrhol yes we are still on 2.2

**Comment by atifwaqar** [comment]
I managed to fix my issue by updating `C:\Program Files\Starcounter\sccode.exe.config` file. Now my file looks like following : 
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <gcServer enabled="true"/>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

But this is a hack solution :P
I still havent figured out why is my app.config not being loaded in SC project. It loads in non SC projects :/

**Comment by per-samuelsson** [comment]
> I still havent figured out why is my app.config not being loaded in SC project. It loads in non SC projects.

Yeah, that is by design. We had discussions a few years ago about if we could support app.config for separate apps, but it turned out we really couldn't.

The reason for this is that we are loading multiple applications into a shared host while .NET app.config is designed to be 1 app / process.

**Comment by per-samuelsson** [comment]
> We had discussions a few years ago about if we could support app.config for separate apps, but it turned out we really couldn't.

See #1015 and #1184 for the background detail.

**Comment by atifwaqar** [comment]
@per-samuelsson Thank you for the detailed response. 
And my solution is working now. But do you think this update in `sccode.exe.config` will harm any functionality in SC code?

**Comment by per-samuelsson** [comment]
> But do you think this update in `sccode.exe.config` will harm any functionality in SC code?

Not sure, but I don't think so, no. But I agree with you it must be considered a hack, and we really don't want you guys having to do such things long term of course, so we need to come up with some solution. I spent some time thinking about it yesterday, but I still have no great answer on what we can do.

Also, that update of the code host config will need to be maintained over versions of course. Meaning that when you install a new version of Starcounter, you'll have to do it once again.

Sorry for the inconvenience really. 😞

**Comment by atifwaqar** [comment]
> Also, that update of the code host config will need to be maintained over versions of course. Meaning that when you install a new version of Starcounter, you'll have to do it once again.

I have an idea about this.
Also is it possible for you guys to update NewtonSoft Json? Or may be you are already updated, What version of NewtonSoft Json SC is using?

**Comment by chrhol** [comment]
> Also is it possible for you guys to update NewtonSoft Json? Or may be you are already updated, What version of NewtonSoft Json SC is using?

We are not using Newtonsoft.Json in the version of Starcounter you are using. If you have some dll lying around it must come from some other place.

In later builds of 2.3 (pnext) we're using version 9.0.1, latest available nuget package.

**Comment by atifwaqar** [comment]
> We are not using Newtonsoft.Json in the version of Starcounter you are using.

Sorry for the confusion, I assumed this because I get issues only related to NewtonSoft Json. Where as I am using alot of 3rd party dlls like `google analytics`, `cloudinary`, `ExcelLibrary` etc

Anyway, my current solution works so lets close this issue for now. 

Note : I had to copy the dll in `C:/Program Files/Starcounter/` after updating the `sccode.exe.config` file.
