### ISSUE TITLE
SC Admin issue

### ISSUE THREAD

**Issue by RickardR** [Starcounter/Starcounter#3918]
Has happened a couple of times now, mostly annoying/visual issue:

When i've started the application with debug, and it critically crashes, I'm unable
to delete the database from the web GUI, because it's still running. It's hanging in some broken state.

The admin page seems to think the db is stopped (Only have a "Start" option),but the DB is running
and the adminpage refuses to allow a delete of the DB, and I cannot stop it since there's only an Start option (that does nothing in that state).

I have to manually stop it with staradmin stop db <name> in order to be able to delete the database.
Mostly annoying since it's easily remedied through staradmin in cmd, but thought I'd report it anyway.

**Comment by andwah** [comment]
Same as https://github.com/Starcounter/Starcounter/issues/3896

**Comment by per-samuelsson** [comment]
> Same as #3896

Based on that, I'll close this as a dup. Reopen it if thats wrong.
