### ISSUE TITLE
Corrupt database after removal of property.

### ISSUE THREAD

**Issue by RickardR** [Starcounter/Starcounter#3919]
I've been playing around (and found some issues, Vadim has fixed one of them) with Unloading/Reloading large databases.

So, on the latest nightly (3568). I had loaded the large database successfully (~68 million records).
I have a dummy property called, well, _DUMMYPROPERTY.
Was going to do a git push, so I commented (removed) the _DUMMYPROPERTY from the code, and
restarted the app (stop debug, remove property, restart debug) so I could take a new dump without the property. Now it seems it cannot start at all with that database anymore.

First time , after property removal, i got (full message from log in files):
Starcounter.DbException: ScErrUpdateFailed (SCERR10009): Failed to update the database user code library. Update failed due to an error for the table HeadsWMS.Persistent.WMSOrders.CustomerOrders.CustomerOrder
Version: 2.2.2.3568.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10009.

After that one, everytime I try to start the db (app) i get:
Starcounter.TransactionAbortedException: ScErrInvalidObjectAccessAbort (SCERR8006): The transaction was aborted because of an invalid object access.
Version: 2.2.2.3568.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8006

Even if i re-add (un-comment) the property, the database won't come back up, it seems to be corrupt.
Stacktraces attached. For full code, contact me (or Vadim, he has a copy).

[First stacktrace.txt](https://github.com/Starcounter/Starcounter/files/564333/First.stacktrace.txt)
[second_third_and_fourth_stacktrace.txt](https://github.com/Starcounter/Starcounter/files/564334/second_third_and_fourth_stacktrace.txt)

I've recreated the error by restarting the app with  DB from 2 diffrent dumps containing the "DUMMYPROPERTY" (with data, one larger, 64 million records, one smaller about 4 million), stop it, remove the _DUMMYPROPERTY again, restart. The large one takes a while though ~23 min to load it, so timeconsuming, but i've recreated the error with both db's, even the small one. 

And, since you cannot Reload a dump with a removed property
(if the dump contains a property that has been removed´the reload crashes. I haven't created an issue on that one yet, I've informed Vadim though. Shortyly, old backups containing removed properties are unusable at the moment unless you first start it with the "correct" application version).

The end result on this build is: I cannot remove a property *at all* from a persistent class, since that
will make the current DB usuable/corrupt (?), and backups (unloads) containing the property cannot be read without crashing with "Unknown column".

For dumps for a reload, contact me, they're too large  for Github (67 + 662mb compressed)

**Comment by per-samuelsson** [comment]
@RickardR 

Thanks for the detailed description of this issue! Sorry for the inconvenience.

Let's see what to take from this, it's surely something we must address ASAP.

Anyone recognize this or have a guess?

cc @k-rus @chrhol @bigwad

**Comment by k-rus** [comment]
> First time , after property removal, i got (full message from log in files):
> Starcounter.DbException: ScErrUpdateFailed (SCERR10009): Failed to update the database user code library. Update failed due to an error for the table HeadsWMS.Persistent.WMSOrders.CustomerOrders.CustomerOrder
> Version: 2.2.2.3568.
> Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10009.

I copy the important part from the stack trace from the file here:

>---> Starcounter.TransactionAbortedException: ScErrInvalidObjectAccessAbort (SCERR8006): The transaction was aborted because of an invalid object access.
Version: 2.2.2.3568.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8006.
   at Starcounter.Internal.TransactionManager.Commit(Int32 tran_locked_on_thread, Int32 detach_and_free) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-551\Level1\src\Starcounter\TransactionManager.cs:line 712
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-551\Level1\src\Starcounter\Db.cs:line 354
   at Starcounter.Binding.TableUpgrade.MoveRecordsToNewTable() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-551\Level1\src\Starcounter\Binding\TableUpgrade.cs:line 450
   at Starcounter.Binding.TableUpgrade.Eval() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-551\Level1\src\Starcounter\Binding\TableUpgrade.cs:line 95
ErrorCode=8006
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8006

This error is the same as reported when subsequent database start ups. The error happens during committing a transaction, which inserted moved data into a table with new schema, I believe.

cc @bigwad @eriohl

**Comment by bigwad** [comment]
I'm working on the similar problem reported by Mopedo. Hopefully, I'll nail it down shortly and then check if it helps in this case.

**Comment by per-samuelsson** [comment]
> I'm working on the similar problem reported by Mopedo. Hopefully, I'll nail it down shortly and then check if it helps in this case.

I'm assigning you to it until you decide otherwise.

**Comment by RickardR** [comment]
FYI, just got it again, pretty quickly, on the latest nightly (3597). First i did a reload of my small DB (with the property). Stopped, commented property, loaded -> Worked, Yay!
Stopped. Un-commented property (and added a little code somehere elsewhere) : Crash with first exception. This time though, if i just restarted the app, it started fine, oddly enough!

**Comment by dan31** [comment]
In 2.3 schema migration bug is fixed.
