### ISSUE TITLE
weaver.ignore limitations

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3924]
Currently we exclude assemblies from being weaved by adding them into a text file called `weaver.ignore`.

This is very inconvenient because:

- It is an unknown file type.
- Developers have to read documentation to get to know about such file.
- It **does not work** with shared assemblies. If I have an assembly which has a `weaver.ignore` file, then I copy it's content to my local version in order to keep it working.

I am not sure whether it is possible, but I would like to rid of the `weaver.ignore` and provide the same info in different way. For example in the `AssemblyInfo.cs` file.

cc @per-samuelsson

**Comment by per-samuelsson** [comment]
@miyconst 

I do agree with most of what you write. It's far from optimal right now. My concerns though:

1. We don't have any clear, suggested alternative. And it will take time to research one if no one comes up with one suggestion that work kind of as proposed.
2. We are stearing against a totally rewritten weaver (in 3.x / Starcounter.Core) and it's very likely we will change how "ignoring" should work there, if it even applies.

**Comment by miyconst** [comment]
>We are stearing against a totally rewritten weaver (in 3.x / Starcounter.Core) and it's very likely we will change how "ignoring" should work there, if it even applies.

I would love to rid of this "feature" in Starcounter `3.x`.

Closing this issue in favor of - [Unable to use weaver.ignore in Simplified](https://github.com/Starcounter/Starcounter/issues/3926).
