### ISSUE TITLE
Scdb 1.5

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3927]
Hi!

I sometimes run into errors at startup, e.g. the port is occupied or another database is running with the same name.

scdbs.exe then shows a messagebox with error info, this is fine. Except for the fact that I'm spawning the process from a service. So the scdbs.exe is spawned as LOCAL_SERVICE meaning there is no UI. So the process just hangs with 1MB of memory usage.

Is there any nice way of detecting these errors? Or redirecting them to something that isn't a messagebox?
![image](https://cloud.githubusercontent.com/assets/4263597/20059354/2bf112e8-a4f6-11e6-9d30-35a225009156.png)

**Comment by careri** [comment]
I found this env var:
````c
#define _HEADLESS_ENV_VAR L"STARCOUNTER_HEADLESS"
````
In:
Mark4\sccoresrv\execproc.cpp

Is there a commandline way of setting this env? Or do I need to set it when spawning the process?

**Comment by careri** [comment]
The env-var works, I got a logfile called scerr.log:
> 11/07/16 14:36:20 The server failed to start: SC_E_APP_ALREADY_STARTED (0x20001): A Starcounter process with the specified name is already started.

**So the question is, can I set this with a command line switch? Or should I set it in the process env when spawning?**

**Comment by careri** [comment]
Another not is that the process seemed to exit with errorlevel=0, that is a bit of right?

**Comment by per-samuelsson** [comment]
> So the question is, can I set this with a command line switch? Or should I set it in the process env when spawning?

As you probably know, the version you are asking about is really old (> 10 years probably) so it's not sure anyone knows without doing some investigation. I know @chrhol at least had a look at something in that version quite recently, maybe he knows (or have a copy of sources and can have a look)?

> Another note is that the process seemed to exit with errorlevel=0, that is a bit of right?

Yeah, feel incorrect.

**Comment by careri** [comment]
Nah, it's not that old. I think this version was built by you 2014. But the code we're talking about might very well be that old.

Any way, I got it working by providing the env in the ProcessStartInfo so I'm fine with that. 
Don't spend any more time on this.
