### ISSUE TITLE
Removing a database field cause reload to fail

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3929]
As part of me reviewing and documenting database refactoring scenarios, I came across a flaw that was also recently detected by one of our customers.

The versions I've tested this in: `2.2.2.3622` and  `pnext / 2.3.0.4643`

It's simply reproduced and I can constantly trigger it.

1. Create a new empty database.
2. Build and run an application such as the one in **app.cs (before)** below.
3. Issue an unload: `staradmin unload db --file=app.sql`
4. Stop, delete and recreate the database.
5. Alter the content of the application to **app.cs (after)**.
6. Build and run the application.
7. Issue a reload: `staradmin reload db --file=app.sql`

**app.cs (before)**
```cs
using Starcounter;

namespace RemoveField
{
    [Database]
    public class Foo {
      public string Bar;
    }

    class Program
    {
        static void Main()
        {
            Db.Transact(() => { new Foo() { Bar = "Value" }; });
        }
    }
}
```

**app.cs (after)**
```cs
using Starcounter;

namespace RemoveField
{
    [Database]
    public class Foo {}

    class Program
    {
        static void Main()
        {
        }
    }
}
```

**Error**:
> [09:17:55, Critical, Starcounter (default)]
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. ScErrSqlUnknownColumn (SCERR7038): The column is unknown. The name of the column or property specified in the query is unknown and cannot be matched to a database column.  The error near or at position 28, near or at token: Bar
In query: INSERT INTO "Starcounter"."Raw"."RemoveField"."Foo"(__id,"Bar")VALUES(object 1,'Value')
Version: 2.2.2.3622.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7038.
Version: 2.2.2.3622.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 600
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 263
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 587
HResult=-2146232828
---> Starcounter.SqlException: ScErrSqlUnknownColumn (SCERR7038): The column is unknown. The name of the column or property specified in the query is unknown and cannot be matched to a database column.  The error near or at position 28, near or at token: Bar
In query: INSERT INTO "Starcounter"."Raw"."RemoveField"."Foo"(__id,"Bar")VALUES(object 1,'Value')
Version: 2.2.2.3622.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7038.
   at Starcounter.SqlProcessor.SqlProcessor.ExecuteQuerySqlProcessor(String query) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 45
   at Starcounter.Reload.<>c__DisplayClass4_1.<Load>b__0() in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Starcounter\Mock\Reload.cs:line 163
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Starcounter\Db.cs:line 354
   at Starcounter.Reload.Load(String filename) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-558\Level1\src\Starcounter\Mock\Reload.cs:line 165
   at ReloadDatabase.Program.Main(String[] args) in c:\Program Files\Starcounter\cli-apps\ReloadDatabase.cs:line 24
ScErrorCode=7038
ErrorMessage= The error near or at position 28, near or at token: Bar
In query: INSERT INTO "Starcounter"."Raw"."RemoveField"."Foo"(__id,"Bar")VALUES(object 1,'Value')
Token=Bar
BeginPosition=28
EndPosition=30
Query=INSERT INTO "Starcounter"."Raw"."RemoveField"."Foo"(__id,"Bar")VALUES(object 1,'Value')
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR7038

Keywords: ScErrSqlUnknownColumn, SCERR7038

cc @k-rus @chrhol @bigwad @RickardR

**Comment by per-samuelsson** [comment]
FWIW, this applies when changing from a field to a property as well. 

**app.cs (before)**
```cs
using Starcounter;

namespace RemoveField
{
    [Database]
    public class Foo {
      // Use a property instead of a field
      public string Bar { get; set; }
    }

    class Program
    {
        static void Main()
        {
            Db.Transact(() => { new Foo() { Bar = "Value" }; });
        }
    }
}
```

Not at all surprising, but since I needed to test it, I figured I might as well log that.

**Comment by bigwad** [comment]
>Not at all surprising

Good for you, but still surprising for me. As I remember you mentioned that weaver supports properties and I thought that for metalayer there should be no difference between properties and fields.

**Comment by miyconst** [comment]
+1

**Comment by per-samuelsson** [comment]
> As I remember you mentioned that weaver supports properties and I thought that for metalayer there should be no difference between properties and fields.

We **do** support auto-implemented properties as a mean to define database state. In every case defining a *field* works, changing that to a *auto-implemented property* will work similarly good. But the same goes the other way around: where there is a *problem/bug defining a field*, there will be a similar problem if you change that to an auto-implemented property.

It was that fact I considered unsuprising. Why: because underneath, they are treated kind of as the same thing. 

Does that make better sense?

**Comment by bigwad** [comment]
Oh, I see.
I thought that in your second experiment you changed a field to a property instead of removing the field. But what you did is changing a field to a property first and then removing the property.

**Comment by per-samuelsson** [comment]
> But what you did is changing a field to a property first and then removing the property.

Exactly. I just ran the exact same sequence from start to finish, but instead of defining a field, I used a property. I'm trying to cover every possible refactoring case in my review and get it documented, hence I made that test too.

**Comment by per-samuelsson** [comment]
Just verified this in `pnext / 2.3.0.4643` and the problem persist there. I'm updating OP to reflect that.

**Comment by k-rus** [comment]
If I understood the issue correctly, you unload data with one table schema and try to load into a database with another table schema. It is not supported, since the schemas are different. I don't see why it is a bug. Correct me if I am wrong in the understanding the issue.

**Comment by RickardR** [comment]
Just my 2 cents:

You should be able to trigger a rebuild from a dump, as in SC 0.x and 1.x, since currently this is the only "classic" way backup that exists in 2.x at least (other than having external backup schemes like shadowcopy etc). So while I understand the thought behind the new limited unload/reload (e.g to use it between starcounter upgrades due to datamodel changes), one would expect that you could use an unloaded DB to create new images (trigger an rebuild). As it is now it is only usable for migrating data between SC version changes, and nothing else. 

I've also encountered some errors (might be fixed, havent been able to test it completely yet. See isse #3919) that have caused the "in place" rebuild to fail completely when restarting the app after simple code changes, for example just removing a property (thus resulting in a complete dataloss) , so the possibility to rebuild the images from a dump (again, like in 1.x for example) is highly desirable, at least for simple scenarios such as removed/added properties and classes (typechanges i can understand).

Haven't seen what backup possibilites there is in 2.3 yet though for data migration.

**Comment by dan31** [comment]
Old way to migrate is deprecated in favor of StarDump:
2.2 -> 2.3: https://docs.starcounter.io/guides/working-with-starcounter/migrating-from-2.2-to-2.3+/
2.3 -> 2.(3+N): https://docs.starcounter.io/guides/working-with-starcounter/unload-reload/
