### ISSUE TITLE
Add X-Referer header value to Starcounter.Internal.StarcounterEnvironment

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3931]
When sending a request outside from PuppetJs we need to add `X-Referer` header to execute the server side handler in scope of a session.

This value can be calculated as following:

```cs
this.Referer = "/_" + Starcounter.Internal.StarcounterEnvironment.DatabaseNameLower + "/" + Session.Current?.SessionId;
```

Can this value be added as `Starcounter.Session.Current.Referer` or `Starcounter.Internal.StarcounterEnvironment.Referer`? So I don't have to calculate it in every app?

cc @alemoi

**Comment by alemoi** [comment]
@miyconst feel free to add it to the most suitable place. Or if you want me to add, just decide on the place, as best for the user.

**Comment by miyconst** [comment]
@alemoi I do not have environment for it, so please do add it to `Starcounter.Session.Current`. Don't forget some meaningful comments.

**Comment by alemoi** [comment]
Added. Please check and close if satisfying.

**Comment by miyconst** [comment]
Thank you @alemoi, it does what it should.

**Comment by warpech** [comment]
I think that this should not be called `Referer` is not correct. "Referer" is just one of many context when it can be used.

The value is the **session URI**, which sometimes happens to be sent using HTTP `X-Referer`. Some other times it is sent as `Location` cookie. Some other time it is used as WebSocket upgrade URL.

We will rename these headers in future: https://github.com/Starcounter/Starcounter/issues/2713

**Comment by miyconst** [comment]
@warpech let's pick a better name. How about `SessionUrl` or `SessionLocation`?

**Comment by alemoi** [comment]
Up to you guys about the name :)

**Comment by warpech** [comment]
Without the `http://` part, it is a **URI**, not a **URL** (https://danielmiessler.com/study/url-uri/#gs.syRciFI)

`Session.Current.Uri` would work for me.

We have `Session.Current.SessionId`, so `Session.Current.SessionUri` would be OK, too.

**Comment by miyconst** [comment]
Sure. @alemoi please rename it to `SessionUri`.

**Comment by alemoi** [comment]
Done. Please close if satysfying.

**Comment by miyconst** [comment]
Thank you @alemoi. Closing.
