### ISSUE TITLE
Back Ground worker for long running threads

### ISSUE THREAD

**Issue by Adeelkh** [Starcounter/Starcounter#3934]
I need a back ground worker which will be always running a job (performing both read from and write to the database). I was going through guides and found this guideline regarding background job https://starcounter.io/guides/transactions/running-background-jobs/

Is there any harm in using scheduling in Starcounter for a long or never ending task or should I use C# standard BackGround worker? will it effect anything?

**Comment by miyconst** [comment]
@Adeelkh thank you for the question.

There is no extra harm apart of the extra resources needed for the background job. Make sure to use `Scheduling.ScheduleTask` and not `Session.ScheduleTask` to do not lock a session.

>... or should I use C# standard BackGround worker?

In this case you would have to schedule a Starcounter task for ever database operation, since such threads are not attached to the database. It might require even more resources.

cc @linkdata, @chrhol, @alemoi

**Comment by linkdata** [comment]
This information may be out of date, @alemoi will correct me if it is:

Running a delegate using `Scheduling.ScheduleTask()` will lock one of the kernel contexts for the duration of the call. Long-running operations (more than a few milliseconds) should be be run on standard .NET Tasks or threads, and use queues or other mechanisms to move work to and from the database.

For more information, see https://github.com/Starcounter/Starcounter/wiki/SCERR1026

**Comment by alemoi** [comment]
All long running threads should be standard .NET threads. In these threads whenever Starcounter has to be accessed (e.g. database operation), a task should be scheduled using `Scheduling.ScheduleTask()`
It depends if you want to run the database operation and wait for the result or just schedule a database operation (that will be performed as soon as scheduler grabs the task): thus the synchronous parameter in the `Scheduling.ScheduleTask()`

**Comment by miyconst** [comment]
@Adeelkh was your question answered? Can we close the issue?

**Comment by alemoi** [comment]
@Adeelkh what do you think of the recommendations here: https://starcounter.io/guides/transactions/running-background-jobs/#long-running-tasksthreads-and-starcounter

**Comment by Adeelkh** [comment]
Thanks for the info @alemoi :) and miyconst :) . Yes you can close the issue
