### ISSUE TITLE
Hardcoded path to clang++ in scllvm.cpp

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3938]
https://github.com/Starcounter/Starcounter/blob/4f9751785667363411e354114af0455f3520e1b5/src/scllvm/scllvm.cpp#L498

Results in this if clang is properly installed and on the path (but not in whatever the current working directory happens to be):

```
sh: 1: ./clang++: not found
scdata: /home/alemoi/Documents/scllvm/scllvm.cpp:551: uint32_t CodegenEngine::ProduceModuleAndReturnPointers(const char*, const char*, const char*, const char*, const char*, bool, const char*, char*, float*, uint64_t*, void**): Assertion `(0 == err_code) && "clang++ returned an error while compiling generated code."' failed.
```

**Comment by alemoi** [comment]
That was made on purpose for now, because clang++ is part of Starcounter distribution both Lin &  Win, and on Linux everything we run so far is inside bin directory.

**Comment by linkdata** [comment]
clang++ should not be part of the SC distribution on Linux - it's a prerequisite, not a subcomponent. But that would be a separate issue. We still need to get that path removed though, as the workaround is quite horrible (creating softlinks to clang++ in every directory you start an SC app).

**Comment by linkdata** [comment]
If we need to ship clang++ as part of our Linux distribution, use an absolute path to the clang++ binary and make sure that any shared libraries loaded by that clang comes from the right place by setting LD_LIBRARY_PATH for it's process.

**Comment by linkdata** [comment]
Will be fixed as part of issue/4042 and issue/4012

**Comment by linkdata** [comment]
Fixed.
