### ISSUE TITLE
Get rid of excessive Db.Transact and Db.Scope overloads

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3945]
There are bunch of overloads that are excessive as user may easily accomplish the same with lambdas:

```
void Transact<T>(Action<T> action, T arg, ...
TResult Transact<T, TResult>(Func<T, TResult> func, T arg, ...
void Scope<T>(Action<T> action, T arg, ...
void Scope<T1, T2>(Action<T1, T2> action, T1 arg1, T2 arg2, ...
void Scope<T1, T2, T3>(Action<T1, T2, T3> action, T1 arg1, T2 arg2, T3 arg3, ...
TResult Scope<T, TResult>(Func<T, TResult> func, T arg, ...
TResult Scope<T1, T2, TResult>(Func<T1, T2, TResult> func, T1 arg1, T2 arg2, ...
```

I've refactored them to avoid code duplication. Also, I suggest to mark them as obsolete and rid of them in 2.4.  Opinions?

cc @chrhol

**Comment by miyconst** [comment]
Although I am sure I have seen some of our customers using those overloads, I vote for removing it as well.

Keep only:

```cs
void Transact(Action action) { action(); }
T Transact(Action<T> action) { return action(); }
void Scope(Action action) { action(); }
T Scope(Action<T> action) { return action(); }
```

**Comment by bigwad** [comment]
@miyconst, you probably meant Func instead of Action in two places:

```
T Transact(Func<T> action) { return action(); }
T Scope(Func<T> action) { return action(); }
```

**Comment by miyconst** [comment]
Yes, thanks for noticing. I have updated the snippet.

**Comment by chrhol** [comment]
I guess it's a decision on how we want our public API to look. 

The reasons for the number of overloads was to avoid having an extra object created (that the compiler adds) for each call, used to transfer the parameters to the lambda. But this was from a time when we had a different policy on things. It's probably better to keep it down I guess, as long as we keep some of them.

**Comment by bigwad** [comment]
My micro benchmark shows that capturing parameters inside lambda is even faster (by a very small margin) than passing it directly. Have no idea why.
Regardless, I don't suggest to remove them immediately - just mark them obsolete.
As code duplication has been removed, it's not a problem of supporting them - it just looks silly.

**Comment by dan31** [comment]
As I recall in 3.0 @linkdata, @k-rus and @alexanderstc has just made an implementation for QP calls based on variadic templates. They have also done benchmarks. Guys, what can you add to this issue based on your recent work? Likewise, how are ```Transact``` and ```Scope``` APIs done in 3.0 now? Recall again: we make 2.x be 3.0. Meaning that: what we do over 2.x lifetime should turn out to be identically functioning in 3.0. I would also add that, to achieve the best performance and the best level of complexity, we have to be pragmatic and rely firstly on tests, evidences and common sense there rather than ideal picture, and question everything.

**Comment by linkdata** [comment]
Generic non-SC specific implementation for passing variadic arguments to native from C# is at https://github.com/linkdata/CSharp-variadic-args

Also includes benchmarks and basic correctness tests.

**Comment by linkdata** [comment]
> Likewise, how are Transact and Scope APIs done in 3.0 now?

Scope() is not yet implemented, so it has no long-running transactions.

As to using a Task to wait for a transaction to complete, I found issues with that and deadlocking: https://github.com/Starcounter/Starcounter.Core/issues/107#issuecomment-247577815

`Db.Transact...` API looks like:
```
        //
        // Execute the given callback in the context of a database
        // transaction.
        //
        void Transact(Action action, Action onCommit = null);
        void Transact(Func<Task> function, Action onCommit = null);

        //
        // Execute the given callback in the context of a database
        // transaction.
        // Returns true if the transaction was committed, false if
        // a conflict occured and it was rolled back.
        //
        bool TryTransact(Action action, Action onCommit = null);
        bool TryTransact(Func<Task> function, Action onCommit = null);

        //
        // Asynchronously execute the given callback in the context of
        // a database transaction.
        // If a conflict occurs, the Task will be in a faulted state.
        //
        Task TransactAsync(Action action, Action onCommit = null);
        Task TransactAsync(Func<Task> function, Action onCommit = null);
```

**Comment by bigwad** [comment]
I think we agreed on making this clean up. Right? Then I'll do it and close the issue.

**Comment by bigwad** [comment]
Done.
Probably some update to the documentation is required. Who is aware of it?

**Comment by bigwad** [comment]
@chrhol, I've just realized, that in 2.2 we didn't have all those Db.Transact overloads, so no reason to keep them. Can be wiped out. Right?

PS.
Obsoleting is still appropriate for Db.Scope

**Comment by chrhol** [comment]
> @chrhol, I've just realized, that in 2.2 we didn't have all those Db.Transact overloads, so no reason to keep them. Can be wiped out. Right?

I think we had them in 2.2 as well unfortunately. But they are obsoleted in 2.3 so maybe we can start removing obsoleted overloads in 2.4 to make it more in line with 3.x version? 

How long do you usually keep obsoleted items?

**Comment by bigwad** [comment]
> I think we had them in 2.2 as well unfortunately. 

In 2.2 we had similar ones with the `forceSnaphot` parameter. You already removed them.

**Comment by chrhol** [comment]
I removed the optional parameter (that no one ever used) not the overloads themselves. In hindsight I should have made them obsolete, but this was quite some time ago.

**Comment by bigwad** [comment]
>I removed the optional parameter (that no one ever used) not the overloads themselves. 

Doing so you effectively removed some overloads and created unrelated instead :smile:
And I marked those new overloads as obsolete. It just doesn't make sense to create a new method and immediately mark it as obsolete. That's why I want to remove them.

As to putting back old overloads with forceSnapshot and marking them obsolete - it concerns binary compatibility and we may discuss it in other thread: https://github.com/Starcounter/CompanyTrack/issues/296#issuecomment-279684042

**Comment by chrhol** [comment]
> Doing so you effectively removed some overloads and created unrelated instead 😄

But it still only required a recompile in 2.3 to work, no changes in the code. 

> it concerns binary compatibility and we may discuss it in other thread: Starcounter/CompanyTrack#296 (comment)

Yes, and the conclusion is that we are not binary compatible and that we probably aren't mature enough in the product to enforce binary compatibility between major releases. But between 2.2 and 2.3 we're still API compatible. Even with me removing the parameter, since no customers at that time (or ever) used this optional parameter.

**Comment by bigwad** [comment]
> But it still only required a recompile in 2.3 to work, no changes in the code.

Except getting warnings, that quite possible will lead to errors in case of enabled "warning as errors". but I admit, this is more friendly.

>Yes, and the conclusion is that we are not binary compatible and that we probably aren't mature enough in the product to enforce binary compatibility between major releases. 

Let's wait for @dan31 response in that thread.

**Comment by per-samuelsson** [comment]
This will simplify for #4074 too I guess. Which is good.

And guys, don't feel shy to jump on that and get it done while you are already at it! 😉 🚶 ✋
