### ISSUE TITLE
Develop build fails because of Products app

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3955]
Here is the link to the failing build example:
https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=13752#_focus=4895

@warpech @joozek78 do you know if its related to the latest changes in repository?

**Comment by warpech** [comment]
Might be... Taking this on me

**Comment by warpech** [comment]
@alemoi PR available for review: #35

**Comment by alemoi** [comment]
@warpech should I review the JS? :) I can do if you want. I guess you wanted for me to get into procedure, right?

**Comment by warpech** [comment]
I am showing off that we have a procedure of never making changes in app without peer review :)

**Comment by alemoi** [comment]
> I am showing off that we have a procedure of never making changes in app without peer review :)

Yes yes, that what I thought :) Ok, will merge the pull request! :D
