### ISSUE TITLE
Document transaction and storage management on .io

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#3958]
Below I sum up 2.5 years of questions from many customers, events attendees, tech analysts etc regarding the core Starcounter data management and storage (Will cross-link some relevant issues later). One might think that such questions should not come from a typical customer, but the truth is indeed quite opposite. Data is amongst the most important assets of the companies, and they want to know how their data is treated in a very fine detail.

Below is a wrap-up of what I have on top of my head. @bigwad, treat this list as an initial input to your eventual "How transactions and storage engine works" article. Note that parts of those questions originate from me (I am thinking about what and how we would do in the future, in upcoming releases 2.4+).

Inherently this article, once available, would deprecate https://starcounter.io/guides/tools/run-starcounter-in-production/.

1. What is the "size of transaction" (i.e. maximum number of objects, modifications - or what is the proper name of the items in transaction). What is it set for by default? How to adjust the size of the transaction (if it is not adjustable - exapain why? what would be the price of making it adjustable?).

2. How logging works? What is log and logopt? When and how logs are converted into logopt? How one can change the parameters of it being done (duration?).

3. Deletion of objects in Starcounter: is there "garbage collection" on deleted objects? When purge is invoked, if there is currently purge in Starcounter? Is there any other special limitations and potentially severe conditions (e.g. when one transaction holds objects form being deleted for very long time, eventually killing the instance) that the user must beware of?

4. Syncronous and asyncronous transactions in ```Db.Transact``` API. How does them all relate to ```Db.Scope``` as of now? Explain in a fine detail, how group commit works and what is it done fore (you know, ferry or airplane analogy, something like that). Do we flush buffers to OS (```fflush```) or do we force sync with storage buffers? (```fsync```). Why one is chosen over another? How can I tune group commit (e.g. size of the group).

5. Expain how log is synced to a stable storage (explain timeout and log buffer size). Explain how those affect the guarantees you have if you choose fire-and-forget ASYNC commits (what is the max amount of transactions that you report committed but loose).

6. What are the requirements to physical storage setup when one wants to benefit from syncronous commits? I.e., battery backed disk buffer, switch off OS write-cache buffer etc. What is the recommendation for RAID setup for a stable storage for logs?

7. Why is it save to do backup "on hot" database folder? (related to p.2). Why the assumption holds true that no corruption, distortion and consistency loss would take place (explaining redo ops on startup - non-commited transaction is not re-done).

8. Does Starcounter strictly binds to RAM or does it actually automatically spans to swapfile? (This is what people notice at least, by we explain it nowhere). What happens when it starts to span to swapfile? How bad it is, what is the expected performance drop in certain microbenchmark-like cases? Would anything stop to work when the spanning into swapfile starts to happen?

9. What happens to my current database on the next run when I increase/decrease physical amount of RAM on a machine? Increase/decrease/remove pagefile in the OS?

10. What happens when the power goes off? What are my guarantees, what shall I loose? What is the expected times for startup "on cold" from disk?

**Comment by SenerDemiral** [comment]
Thanks, awesome detection!
Every old SQL developer will/should ask these questions before switch to Starcounter.

**Comment by bigwad** [comment]
@dan31, you may find draft of the FAQ at https://github.com/Starcounter/TechComm/wiki/draft-of-the-answers-to-https:--github.com-Starcounter-Starcounter-issues-3958

Let's discuss it there until it ready to be published.

**Comment by dan31** [comment]
Moved to https://github.com/Starcounter/TechComm/issues/294 to prepare the material for 2.3 release train.
