### ISSUE TITLE
User Admin app not running on SC Version 2.3

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3959]
I have tried every version, but User Admin app is not running. 
My SC version is 2.3.04845.

**Comment by miyconst** [comment]
@atifwaqar I am sorry that you have to experience this. This is a known issue, there is no compatible version of UserAdmin app with Starcounter 2.3, only 2.2.

The compatible version is available under [pnext-adaptation](https://github.com/StarcounterPrefabs/UserAdmin/tree/pnext-adaptation)  branch of UserAdmin, and the app package will be released soon.

Hope this solves your problem.

**Comment by atifwaqar** [comment]
@miyconst Thanks it worked. 
Any idea when you will have this build in `App Warehouse` ?

**Comment by miyconst** [comment]
@Mnosek please publish the package as soon as possible and close this issue.

**Comment by Mnosek** [comment]
Now it's available in App Warehouse, but not in Beta Warehouse yet.

**Comment by dan31** [comment]
I assume it is published already @mmnosek. Reopen if otherwise.
