### ISSUE TITLE
Non database type Starcounter.Metadata.MetadataEntity of property Type in class Starcounter.Internal.Metadata.SetSpecifier

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3965]
SC Version 2.3.0.4845

Whenever I run my app, I get this warning. Is it something to worry about?

![image](https://cloud.githubusercontent.com/assets/4388707/20527549/30f77942-b0c9-11e6-855a-2dedcb64cfd1.png)

**Comment by miyconst** [comment]
cc @k-rus

**Comment by per-samuelsson** [comment]
Duplicate of #3937.
