### ISSUE TITLE
How to check whether a Database class property is a nullable or not?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3973]
There are two tables with meta data for the table columns.

- `Starcounter.Metadata.Property`
- `Starcounter.Metadata.Column`

Here is the information for the `Simplified.Ring2.Person` table.

**Starcounter.Metadata.Property**

```sql
SELECT *
FROM Starcounter.Metadata.Property
WHERE "Table".FullName = 'Simplified.Ring2.Person'
```

![image](https://cloud.githubusercontent.com/assets/6435556/20560066/c5334894-b177-11e6-8b1f-62e563389b56.png)

**Starcounter.Metadata.Column**

```sql
SELECT *
FROM Starcounter.Metadata.Column
WHERE "Table".FullName = 'Simplified.Ring2.Person'
```

![image](https://cloud.githubusercontent.com/assets/6435556/20560049/b30d4d4a-b177-11e6-9632-d6e376822bf6.png)

So, the `Starcounter.Metadata.Column` has a `Nullable` column indicating whether it is nullable or not, but it does not have all the records from the `Starcounter.Metadata.Property` table.

How do I check whether `FirstName` is nullable or not?

P.S. I know that `FirstName` is a string, and it can be null, this is just an example on the shared database model, which is also applicable for the `int` and `int?` properties which have exactly the same `DataType` in the meta tables.

cc @k-rus

**Comment by miyconst** [comment]
Here is the definition of the [Person](https://github.com/StarcounterPrefabs/Simplified/blob/master/Ring2/Person.cs) class.

```cs
namespace Simplified.Ring2 {
    public class Person : Simplified.Ring1.Somebody {
        private string _FirstName;
        public string FirstName {
            get {
                return _FirstName;
            }
            set {
                _FirstName = value;
                UpdateName();
            }
        }

        private string _LastName;
        public string LastName {
            get {
                return _LastName;
            }
            set {
                _LastName = value;
                UpdateName();
            }
        }
        
        public decimal Weight;
        public DateTime Birthdate;
        public Gender Gender;

        private void UpdateName() {
            string[] parts = new string[] { this._FirstName, this._LastName };

            this.Name = string.Join(" ", parts.Where(x => !string.IsNullOrEmpty(x)).ToArray());
        }
    }
}
```

**Comment by k-rus** [comment]
We discussed offline. The metadata tables to use are `Starcounter.Metadata.Rawview` and `Starcounter.Internal.Metadata.RawColumn`. Complete schema of metadata described in `metaschema.json`, which available in Level0 and in Level1.

**Comment by miyconst** [comment]
Thanks @k-rus, closing the issue.

**Comment by miyconst** [comment]
cc @ubbeK, you should also know this.

**Comment by per-samuelsson** [comment]
> Complete schema of metadata described in `metaschema.json`, which available in Level0 and in Level1.

Just to make it clear, that's an implementation detail. Lets try use it only for reference, but never depend on it programatically. I think @k-rus meant for it as a reference only.
