### ISSUE TITLE
No Proper Error message on Crash

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3974]
SC Version : 2.3.0.4846

I had some logical errors in my code (`An unhandled exception of type 'System.StackOverflowException' occurred`). 
The issue here is that SC didn't gave me any error message in logs, and just crashed with only 1 message : 
`The host has been disconnected.`

Here is a snapshot of my log : 
![image](https://cloud.githubusercontent.com/assets/4388707/20563372/9ca07490-b188-11e6-90e7-5f137fc49a72.png)

I know that the proper way to code in SC is to have a try catch body and then we log the error message in catch body, but this is something that our new developers forget every time. and we have lots of handlers that are without Try Catch body.

**Comment by bigwad** [comment]
@atifwaqar, I believe in such case system should generate a dump, if it is configured to do so. Please check https://github.com/Starcounter/Starcounter/issues/3637#issuecomment-220346794 for details.

**Comment by dan31** [comment]
@atifwaqar activating crash dumps investigation is explained here: https://starcounter.io/guides/tools/guidestoolsinvestigating-apps-crashes/.

**Comment by atifwaqar** [comment]
I'll investigate this today.
