### ISSUE TITLE
pnext: can't run useradmin, staradmin seems to be broken

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3975]
1. remove any existing sc installation and data directories
1. install [pnext build 4846](https://192.168.200.91/viewLog.html?buildId=13889&tab=buildResultsDiv&buildTypeId=Starcounter_PnextNightlyWindows)
1. download useradmin@60979f9a516a4d0626062f95a395cd71f1b066cd
1. 
```
C:\Users\joozek\dev\useradmin>run

UserAdmin -> default                                                                                                    
UserAdmin -> default (starting server)                                                                                  



Type "star -h" to see help
```
note that there is no message about success / failure. Nothing happened in database (nothing created / started)

1.
```
C:\Users\joozek\dev\useradmin>staradmin new database default

Creating database default                                                                                               
Creating database default (creating database)                                                                           



Type "star -h" to see help
```
Again, exact same situtation. Nothing happened and no information about success / failure

**Comment by andwah** [comment]
Anything in the log?

**Comment by miyconst** [comment]
Are you sure that you don't have any old binaries in the folders which were build for the Starcounter 2.2?

**Comment by joozek78** [comment]
Sorry for the silence. Some time later I tried it again and couldn't reproduce. Strange thing is that earlier cleaning the db and binaries didn't help. I'll reopen if I stumble on it again
