### ISSUE TITLE
Allow custom bound accessors in XSON

### ISSUE THREAD

**Issue by eriksunsol** [Starcounter/Starcounter#3977]
XSON currently supports custom __unbound__ accessors, which I think are used by JsonByExample code generation.

We're looking into creating the JSON schemas dynamically with explicit data accessor delegates. For this to work we need to override the default generated `BoundGetter` and `BoundSetter` delegates which is currently not possible.

**Comment by chrhol** [comment]
Good point. It should be possible to override these as well, and not rely on the default behaviour. I will try to do this as soon as possible.

**Comment by eriksunsol** [comment]
I have made the changes already as a proposal. Just figuring out how to do a pull request...

**Comment by chrhol** [comment]
I've got a bit delayed, but now it's been merged into develop and pnext branches (I changed the PR to a separate branch to be able to add a litte stuff before pushing it),

The next nightlies should contain the fix for this issue. Thanks for the help and the PR @eriksunsol, much appreciated :smile:

**Comment by eriksunsol** [comment]
Cool. Thx @chrhol. Will try it out tomorrow.

**Comment by eriksunsol** [comment]
@chrhol Sorry for the delay. It works like a charm! Thanks.
