### ISSUE TITLE
XSON, refactor public fields in Property<T> abstract class

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Starcounter#3979]
Refactor the Getter and Setter fields into properties with public getter and private setter since there is a set method for them.

```cs
public Func<Json, T> Getter;
public Action<Json, T> Setter;
....
public void SetCustomAccessors(Func<Json, T> getter, Action<Json, T> setter, bool overwriteExisting = true);
```

cc @chrhol

**Comment by chrhol** [comment]
Thank you for adding an issue for this. 

I will add a note, so I dont forget, that this needs to done for TObject, TObjArr and TArray<T> as well since they have different signatures of the delegates.

**Comment by chrhol** [comment]
Another note: this will require code that uses Starcounter.XSON (i.e. TypedJSON with generated code) to be recompiled, although without any changes in usercode or generated code. So I guess the best time to push this change will be in the upcoming 2.4 version.

**Comment by chrhol** [comment]
Done.
