### ISSUE TITLE
Introduce generic way to specify that a type / assembly should use "UseOnlyFullNamespaceSqlName"

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3980]
Background here: https://github.com/Starcounter/RebelsLounge/issues/50#issuecomment-260880804

We need to explain what this thing do, and provide a way for app devs to set it. And make sure it's used by Simplified and SocietyObjects.

**Comment by per-samuelsson** [comment]
> We need to explain what this thing do [...]

Taking a guess: with this class

```cs
namespace Foo {
  [Database] public class Bar {}
}
```

and if this thing is **set**, a query such as 

```sql
SELECT b FROM Bar b
``` 

will **fail**. While it won't when it *isn't* set. 

Anyone can confirm? @alemoi?

**Comment by per-samuelsson** [comment]
I considered a few alternatives, but I settled for one that is the simplest possible, and quite static, which would cater for minimal maintenance. I'm adding it as a property to already existing `StarcounterAssemblyAttribute`, which is currently used only to make sure the compiler add a reference to `Starcounter` for any application being compiled using sources.

**Comment by alemoi** [comment]
Yes the query on short names on SO and Simplified should fail, and on only full names succeed. However the above query should succeed if you have other Bar definition outaide SO and Simplified :)

**Comment by per-samuelsson** [comment]
This is now done, as part of #3869. I'll merge it into main trunk once that one is merged.

**Comment by per-samuelsson** [comment]
Done and pushed. Merged in https://github.com/Starcounter/Starcounter/commit/d5aa1ff89fbffba7842275e2e3132c4b19b01ea6.
