### ISSUE TITLE
How to get number of rows returned from Db.SQL?

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#3983]
```
QueryResultRows<Turnuva> turnuva = Db.SQL<Turnuva>("select t from Turnuva t");
```

**Comment by mtornwall** [comment]
Try this:

    var numRows = Db.SQL<long>("SELECT COUNT(t) FROM Turnuva t").First;

**Comment by SenerDemiral** [comment]
Yes, that is option. 
But if turnuva is something like object array (or cursor?), why we can't get length of it?

**Comment by k-rus** [comment]
We don't store statistics on tables including their sizes for performance reason. To know the size of a query result even if a query accesses entire table requires to iterate over entire result.

**Comment by mtornwall** [comment]
@SenerDemiral However, if you don't mind materializing the whole result as an array, you could do this:

using System.Linq;

// ...

var arr = Db.SQL<Turnuva>("SELECT t FROM Turnuva t").ToArray();
// Now you can get at the length using arr.Length

**Comment by SenerDemiral** [comment]
Means:
QueryResultRows<Turnuva> turnuva is a pointer/cursor to rows. 
And query not accesses table until iteration.
Thanks.

**Comment by k-rus** [comment]
> QueryResultRows turnuva is a pointer/cursor to rows.
> And query not accesses table until iteration.

It's correct now. On the other side we provide `IEnumerable` semantics for results of simple queries, i.e., manipulations with data in the database do not affect simple queries with open iterators/cursors. However, current implementation does not allow to know the size of the result, but we will consider in future if we can support this without performance lost, but I am doubt.

Thank you for the comment.
