### ISSUE TITLE
Don't use SessionIdString and ToAsciiString in sample & prefab apps

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3986]
Some of our sample apps and prefab apps use obsolete property `SessionIdString ` or method `ToAsciiString` of the Session class. They should be replaced with `SessionId`.

@Mackiovello could you take this? You need to search all our apps (I recommend using https://starcounter.gitbooks.io/rebelslounge/content/github_search.html) and replace the lines of code that use this.

**Comment by Mackiovello** [comment]
Changed from `SessionIDString` and `ToAsciiString` in Chatter and Calendar and pushed on the develop branch. Should I go and change on the master branches too? 

Simplified has a property `SessionIDString` in `SystemUserSession` which I didn't touch. Was that the correct call?

**Comment by Mackiovello** [comment]
I'll go ahead and close this since I consider it done.
