### ISSUE TITLE
Document staradmin new db CLI parameters

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3996]
@Mackiovello please update this page [staradmin CLI](https://starcounter.io/guides/tools/staradmin/) with information from here - [Add support to `staradmin.exe` for the `-oid` and `-lastoid` flags](https://github.com/Starcounter/Starcounter/issues/3360#issuecomment-184234893).

**Note:** it is only applicable to Starcounter 2.3 (pnext).

**Comment by dan31** [comment]
@miyconst @Mackiovello I know the following comment is out of context and is not formulated anywhere yet as a regular practice, but some people already follow this practice by my example, hence I would encourage you do the same:

![image](https://cloud.githubusercontent.com/assets/7162535/21030076/f3b6a7fc-bd9c-11e6-9b2f-6fc1692bc869.png)

Thanks! 👍

**Comment by Mackiovello** [comment]
This [page](https://starcounter.io/guides/tools/staradmin/) is now updated with the following text:
```### New Command From 2.3
The new command works the same way in Starcounter 2.3 as 2.2 except for two changes:
1. Databases are created using the syntax `staradmin new db foo` instead of `staradmin -d=foo new db`.

2. All the available configuration options in the underlying REST JSON representation can be set from the command line. These are:
* Uri
* DataDirectory
* TempDirectory
* DefaultUserHttpPort
* FirstObjectID
* LastObjectID

These options are specified on the creation of the database using this syntax:
`staradmin new db DataDirectory=C:\Users\Per\Foo DefaultUserHttpPort=1234 Uri=http://example.com/api/databases/foo/configuration"

**Comment by warpech** [comment]
> @miyconst @Mackiovello I know the following comment is out of context and is not formulated anywhere yet as a regular practice, but some people already follow this practice by my example, hence I would encourage you do the same:

Actually many of us follow another practice: create documentation requests in [TechComm](https://github.com/Starcounter/TechComm/issues) issue board.

**Comment by miyconst** [comment]
@dan31, @warpech, thank you for the tips. I will follow both.
