### ISSUE TITLE
SQL comparison predicate "not equal" ('<>') not working in web admin

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3997]
Version: latest bits of 2.3+.

Having this class:

```cs
[Database] public class Foo {
  public string Bar;
}
```

and then populating using this

```cs
Db.Transact(() => {
    new Foo() { Bar = "Hej" };
    new Foo();
});
```

give these results when querying from Web Administrator:

```sql
SELECT f FROM Foo f WHERE f.Bar IS NULL // 1 hit, correct
SELECT f FROM Foo f WHERE f.Bar = 'Hej' // 1 hit, correct
SELECT f FROM Foo f WHERE f.Bar <> 'Hej' // 0 hits, incorrect I guess?
```

**Comment by miyconst** [comment]
I think this is not a bug, but rather SQL language standard. Any comparison with a NULL value except `IS NULL` and `IS NOT NULL` returns `false`.

At least it is so in MS-SQL server.

**Comment by miyconst** [comment]
Here is the same question - [T-SQL: select rows not equal to a value, including nulls](http://stackoverflow.com/questions/10421017/t-sql-select-rows-not-equal-to-a-value-including-nulls).

**Comment by miyconst** [comment]
The other thing is that Entity Framework automatically converts `query.Where(x => x.Bar != "Hej")` into `WHERE x.Bar <> 'Hej' OR x.Bar IS NULL`.

**Comment by per-samuelsson** [comment]
OK, thanks for providing that insight @miyconst. Let's close this one then, and be done with it. We can reference it if we ever get the same thing reported again.
