### ISSUE TITLE
Assertion failed in scllvm.dll

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#4000]
```
Starcounter-Develop-2.3.0.5330 (Dec 8, 2016 2:42:52 AM)
```

![image](https://cloud.githubusercontent.com/assets/6435556/21046283/3ea21c9e-be04-11e6-8d34-362c5f7a1e1e.png)

Entire server crashes. Log entries:

```
Process exitcode: 3
```

```
ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
```

What can I provide for debugging?

cc @alemoi, @bigwad

**Comment by alemoi** [comment]
I got the generated code from @miyconst and everything was fine with it, no compilation errors. Error code 3 indicates ERROR_PATH_NOT_FOUND. Very strange! I will rework the code so it returns an error code to the calling process.

**Comment by miyconst** [comment]
>I got the generated code from ...

This might be not the culprit code, since I have reinstalled Starcounter multiple times since that time. I will try to reproduce the issue and give update here.

**Comment by alemoi** [comment]
> This might be not the culprit code, since I have reinstalled Starcounter multiple times since that time. I will try to reproduce the issue and give update here.

Big thanks!

**Comment by miyconst** [comment]
No. I can't reproduce the issue with the fresh installation of `Starcounter-RC-2.3.0.5364`. Closing for now.
