### ISSUE TITLE
Starpack: add force app install (upgrade) option.

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Starcounter#4002]
**Overview**
In our current project, we try to setup continuous deployment to our test environment. We want to use starpack as I think it should be our standard way to create app packages and install them. Unfortunately, we've faced a problem almost at the end of the process.

Steps are as follows:
1. Code is merged to develop branch
2. TeamCity is building couple of apps
3. Apps are packed from build artifacts by `starpack` on TeamCity to `app.zip` files
4. `app.zip` files are sent to remote server through sftp
5. There is a service listening for zip files changes, this service is supposed to install a new version of each app by running batch script.

Here is our problem. Starpack is unable to install a new version because the same app at the same version is already installed. It's understandable in a production-like environment, but in development/testing this limitation is very annoying. We can't uninstall app (there is no this kind of option in starpack).

**Proposed solution:**
Add "force install" option to starpack. It should not check things like app version or if current app is already installed, just remove old one and install new one.
Similar to GIT --force option, or linux -f in some commands. WDYT? Is it possible? It would eventually make our life much easier :) Something like `starpack install --force app.zip`

cc @andwah

**Comment by andwah** [comment]
I agree, a "force install" should be very handy

- "force install" : replace or install the app.
- "upgrade" : uninstall all other versions and install the app.

I will take a look to see what i can do about the "force install".

**Comment by mmnosek** [comment]
cc @aloscha

**Comment by per-samuelsson** [comment]
> Similar to GIT --force option, or linux -f in some commands. WDYT? Is it possible? It would eventually make our life much easier :) Something like `starpack install --force app.zip`

And compatible with our very own `staradmin delete --force db` 😎

**Comment by mmnosek** [comment]
> And compatible with our very own staradmin delete --force db

Absolutely, I should have mentioned it in the very beginning 😄

**Comment by andwah** [comment]
Now it's pushed.   

Install options has been added.

`-f` (force install) : Will overwrite any existing version (same namespace,channel and version)
`-u`  (upgrade): Will uninstall latest existing version and install new package.

**Comment by mmnosek** [comment]
Wow! Extremely fast, thanks! Closing for now!

**Comment by per-samuelsson** [comment]
Hate to sound like a boring old dog, but just one word of caution implementing this force option: it kind of violate the principles of versioning. 

If you have a version x.x.x, that version should (in the perfect world) always refer to the same artifact. Once you have published it, there is really no return. If you need to fix something, you should bump the lowest possible number (if there are no API-changes).

Again, in the perfect world.

What is bad about having one version for several artifacts (where older ones are being replaced) is that it can be very confusing when someone report a bug for example. What version of version x.x.x are they reporting it for?

Not saying we absolutely can't have this. You guys know the domain better. Just wanted to share a thought.

**Comment by aloscha** [comment]
I have one more question about ability start/stop installed apps.
My workflow:
1. Application A is currently running in version 1.0.0.1
2. PowerShell script get zip file of app A in new version 1.0.0.2 (this zip is prepare with Starpack)
3. PowerShell script run `starpack -u A`, and I guess Application A in 1.0.0.1 will be stopped, uninstalled and new version of A 1.0.0.2 will be installed
4. I need to start it via CMD (Powershell) but using `star A` is doesn't work because of path problem.

I think we should also add start stop functionality into installed applications from Starpack.

**Comment by andwah** [comment]
I dont want to make starpack a tool for starting/stopping apps.

but..  will option 1 or option 2 work for you: 

Installed package will be started:

**Option 1**. IF database is running
**Option 2**. IF previous/replaced app was running.

**Comment by aloscha** [comment]
Option 2 sound great.

**Comment by andwah** [comment]
options 2 => pushed

**Comment by aloscha** [comment]
@andwah thanks I will test it tomorrow,

**Comment by per-samuelsson** [comment]
> I dont want to make starpack a tool for starting/stopping apps.

I think that was a very good intention. We should be careful duplicating logic like that, because it will increase maintenance for us and also make Starcounter harder to understand as a product. Separation of concerns is the key.

But still as I understand from 

> options 2 => pushed

you did in fact make `starpack` start the newly installed application? Can't we try to come up with some better workflow for that?

For me, **installing / upgrading** apps is not to be concerned with **starting** them.

**Comment by andwah** [comment]
> you did in fact make starpack start the newly installed application?

Well only if it was an "upgrade" and the previous version was running.  So after an installation the end result is the same as before just now with the new version running. 

> Can't we try to come up with some better workflow for that?

Sure, this was only the most user friendly approach i could think of at the moment.

**Comment by per-samuelsson** [comment]
> Well only if it was an "upgrade" and the previous version was running. So after an installation the end result is the same as before just now with the new version running.

My main concern is really that we try to have our tooling both consistent and somewhat *compact*. With several tools, working in similar ways (but yet not exactly equal), we will confuse users.

> Sure, this was only the most user friendly approach i could think of at the moment.

For me, the most natural thing for `starpack install` to do if the app being installed was already present and *running* was to raise an error, asking the user to stop it first. I dont think it make sense to install something that is already running (except when different versions can run side-by-side, but that's not the case here I think).

Me personally, I don't consider "fewest letters to type" is always the most user-friendly. Consistency is of more importance IMHO. But I might very well be a minority here.

I think one of our problems here is that tooling is not consistent in terms of artifacts different tools know about, or can handle. As an example, you can't start an *installed* app (i.e. one from a warehouse) using the same tools as you can for one you have somewhere on your HD, right? E.g. it's not possible today to do `star <app-by-name>`? If we address those underlying limitations first, it will be easier to make more "outer" tooling correct.

```
staradmin stop app A
starpack -u A
star A
```

**Comment by andwah** [comment]
> As an example, you can't start an installed app (i.e. one from a warehouse) using the same tools as you can for one you have somewhere on your HD, right?

An installed app exist on your HD so you can use `star` to control it. 
(It exist in the repository / Personal / Databases / <databasename> / Apps)

The "install" part of the starpack was/is still just an experimental thing, maybe that function should be placed somewhere else. There is a demand of a tool to install packages without getting them from the warehouse.

**Comment by per-samuelsson** [comment]
> An installed app exist on your HD so you can use star to control it.

Yes, I understand that, but it require you to know about some specific path. It would be more convenient for users being able to reference them just by their installed name I suppose.

> The "install" part of the starpack was/is still just an experimental thing, maybe that function should be placed somewhere else.

Okay, I see. Is there somewhere we have some kind of specification for starpack as a whole? What it should do mainly. I know we are limited on resources, and we probably can't work anything out right now I guess, but it would be good to get a more complete picture of all functionality we have a demand to provide. To better see the whole picture.

>  There is a demand of a tool to install packages without getting them from the warehouse.

I'm not sure I understand that? You mean to build and install a package from just any executable? I probably need to understand better the whole functionality of app-packaging, and maintenance of those packages.

**Comment by andwah** [comment]
> There is a demand of a tool to install packages without getting them from the warehouse.

Some customers want to be able to install an apps "offline"  (not connected to internet /warehouse ), they may have the "new" app on a usb-stick etc.

**Comment by per-samuelsson** [comment]
> Some customers want to be able to install an apps "offline" (not connected to internet /warehouse ), they may have the "new" app on a usb-stick etc.

Aha, ok, I understand. Thanks for sharing.

Maybe we should try assemble some list of all management operations we have today, and add a tail of known requirements? Just something very basic and raw, like:

```
star <app.exe|app.cs> : start an app given its path
staradmin stop app <name> : stop an app given its name
staradmin list log : list the content of the server log
...
```

Once we have such list, I guess it will be easier to understand where cross-concerns exist.

**Comment by aloscha** [comment]
@per-samuelsson if I have installed application from starpack, there are impossible to start/stop it using
`star <app.exe|app.cs> : start an app given its path` because we don't have the proper path.

I need to looking for installed path than go there and make start/stop. I prefare that it makes automatically or even batter that `star` will be looking by name apps and stop it.

**Comment by per-samuelsson** [comment]
@aloscha 

> I need to looking for installed path than go there and make start/stop. I prefare that it makes automatically or **even batter that star will be looking by name apps and stop it**.

That's exactly my point: see this https://github.com/Starcounter/Starcounter/issues/4002#issuecomment-266682618.

Basically: we must improve our underlying tools (like `star`) rather than implement similar functionality in more high-level tools.

**Comment by aloscha** [comment]
> Basically: we must improve our underlying tools (like star) rather than implement similar functionality in more high-level tools.

Agreed :)
