### ISSUE TITLE
Possible buffer overrun in star_crud_ReadString

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#4010]
It may write null-terminator outside of the kernel buffer.
cc @alexanderstc , @k-rus

I think it's worth to change API to return {ptr, length} pair so it solves both this issue and helps with performance https://github.com/Starcounter/StarDump/issues/4#issuecomment-267549592

**Comment by linkdata** [comment]
I think it's far better to move memory allocation to the caller, as it avoids all intermediate allocations and copying.

**Comment by alexanderstc** [comment]
@bigwad with the current api you might just make sure the kernel buffer can always hold the terminating zero.

**Comment by alexanderstc** [comment]
On my side with the current api I can only fix this by making a copy of the whole string, that I rather not.

**Comment by bigwad** [comment]
No doubt this solution is cleaner and unlike the current solution may handle strings of arbitrary size.
But from the performance point of view, it's not that obvious.
First, kernel decode strings into its own buffer. Unless we change it there will be at least three data copies: 
1. kernel making decoding
2. metalayer filling StringBuffer
3. host converting StringBuffer to string

Now we have only two:
1. kernel making decoding
2. host marshaling kernel's buffer to string.

We can change kernel implementation to decode into external buffer, but there is one more problem. Kernel doesn't store the length of the original string. So if the buffer is not sufficient we will need to decode twice, that much worse than copying the data. Probably we can store original size, we may even optimize it and store original size only for relatively large strings to save the space. As it's unlikely that we may run out of the buffer decoding short strings. This will complicate kernel's code I think.

And I didn't mention that StringBuilder has to be cached because creating of StringBuilder is expensive. And kernel buffer is likely to be in processors cache, so some client may take advantage of this.

In essence, I don't think it's worth to change it that way.

**Comment by bigwad** [comment]
> @bigwad with the current api you might just make sure the kernel buffer can always hold the terminating zero.

Yes, but we don't have to. It's much better for performance to know the length.


>On my side with the current api I can only fix this by making a copy of the whole string, that I rather not.

Why returning  {ptr, length} pair is not an option?

**Comment by linkdata** [comment]
> First, kernel decodes strings into its own buffer.

That should indeed probably be changed for performance reasons. Always try writing to the final target in order to avoid intermediate allocations and copying.

> Kernel doesn't store the length of the original string

That's another thing that should be fixed, as having to decode the string to know the expanded size is expensive, and in addition to enabling easy allocation control, some operations can do fail-fast using only the length of a string.

**Comment by alexanderstc** [comment]
I'd like to mention a few points:
- any change to _existing_ crud public api must be approved by @k-rus 
- QP team will probably reject any design which would require creation of intermediate buffers in QP/crud/metalayer.

If any1 somehow need my help to specifically design/implement anything, please go through @k-rus, he'll schedule.

**Comment by k-rus** [comment]
We definitely should fix this issue. However, the suggested fix with a pair of length and pointer seems to be a hack. Does it natively supported in code hosts?

CRUD API is really a thin layer, which should not do much or any conversion between kernel and code hosts. Providing the result of kernel's read string as it is does not seem good option, since every code host will need to have the same logic.



> @bigwad with the current api you might just make sure the kernel buffer can always hold the terminating zero.
> Yes, but we don't have to. It's much better for performance to know the length.

In this case, CRUD API should just return the original output from kernel, but it does not seem to be a good solution for code hosts implementation. Let me know if I am wrong and it works well for code host.

Do you mean that it is expensive to guarantee that the kernel buffer is large enough to hold the terminating zero? How does it work to hold the original string? May be kernel can write the terminating zero?

**Comment by k-rus** [comment]
> I think it's far better to move memory allocation to the caller, as it avoids all intermediate allocations and copying.

If the kernel will support this, then CRUD API should be changed accordantly.



> @bigwad with the current api you might just make sure the kernel buffer can always hold the terminating zero.

Actually, why is the logic to prepare proper string value not in the kernel? Are there clients interested in the byte array with the length header?

**Comment by bigwad** [comment]
>Do you mean that it is expensive to guarantee that the kernel buffer is large enough to hold the terminating zero? How does it work to hold the original string? May be kernel can write the terminating zero?

The expensive part is on the code host side looking for zero terminator to get string length to allocate proper buffer for the string.

> Actually, why is the logic to prepare proper string value not in the kernel? Are there clients interested in the byte array with the length header?

If host copies the string, which current hosts always does, then as mentioned it's better to know a string length. Thus no need in zero-terminator.

**Comment by k-rus** [comment]
> The expensive part is on the code host side looking for zero terminator to get string length to allocate proper buffer for the string.

Should we just return what the kernel returns, i.e., the pointer, where the header contains the length?

**Comment by k-rus** [comment]
@bigwad Can you answer the question: why cannot the kernel guarantee place for terminating zero?

**Comment by k-rus** [comment]
Returning byte array and length work well for C# code host at it has corresponding constructor:

```c#
public unsafe String(
	sbyte* value,
	int startIndex,
	int length
)
```

So I agree CRUD API should return length and byte array. cc @alexanderstc 
Currently CRUD API is used in Starcounter.Core and SQL test framework. So they will need to be updated by the owners after the change. cc @linkdata and @henriksjostrom

**Comment by k-rus** [comment]
I guess API to read string into client buffer can be implemented using current kernel API to read binary and TT API. @bigwad WDYT?

**Comment by linkdata** [comment]
The API exposed by Bluestar to the codehosts must allow for the codehost to determine the required buffer size for a string, excluding terminating null (ideally for more than one encoding, but UTF-16 is enough to start with) and then have an API which takes a pointer to a buffer into which the string must be placed.

I've given a reasonable signature for such an API in the [other thread](https://github.com/Starcounter/StarDump/issues/4#issuecomment-267556817):

```c
uint32_t star_crud_ReadString(
  uint64_t dbHandle,
  uint64_t crudHandle,
  uint64_t dbId,
  uint64_t dbRef,
  wchar_t* buf,
  int32_t available,
  int32_t* needed)
```

```cs
uint sccrud.star_crud_ReadString(
  ulong dbHandle,
  ulong crudHandle,
  ulong dbId,
  ulong dbRef,
  [MarshalAs(UnmanagedType.LPWStr)] StringBuilder sb,
  int available,
  out int needed)
```

**Comment by k-rus** [comment]
I suggest to fix the bug in following steps:

1. Fix CRUD Read String API to return 8-byte array and length and relevant func tests by @alexanderstc 
2. Fix SQL test framework by @henriksjostrom 
3. Fix Starcounter.Core and its tests accordingly by @linkdata 
4. Merge into develop branch
5. Fix the dump tool by @miyconst 

Let me know if it is not a good way. Assigning @alexanderstc for the first step.

We don't go now for implementing solution where clients allocate buffer as it requires considerable amount of work. It should be in a separate issue.

**Comment by bigwad** [comment]
>Fix CRUD Read String API to return 8-byte array and length and relevant func tests by @alexanderstc

@k-rus, I suggested to just unparse kernel array into {pointer, length} pair. It shouldn't add any measurable overhead and will simplify host implementation a little bit.

**Comment by k-rus** [comment]
> Fix CRUD Read String API to return 8-byte array and length and relevant func tests by @alexanderstc
> @k-rus, I suggested to just unparse kernel array into {pointer, length} pair. It shouldn't add any measurable overhead and will simplify host implementation a little bit.

For me it is just different words to say the same, since kernel returns 8-byte array with a header.

**Comment by bigwad** [comment]
> For me it is just different words to say the same, since kernel returns 8-byte array with a header.

When you return a byte array - host should know endianness, do pointer arithmetic or other nasty stuff.
Probably better to offload it and return two clean and obvious values. But you might want to profile it.

**Comment by linkdata** [comment]
> I suggest to fix the bug in following steps:

If the point of that is to simply return the length, and the point of that is to improve performance, I think that it's better to put the work towards implementing the proper API instead. Otherwise we're just wasting time writing code that'll soon be replaced anyway.

If there's no time to do a proper implementation right now, I'm OK with delaying it.

**Comment by k-rus** [comment]
> If the point of that is to simply return the length, and the point of that is to improve performance, I think that it's better to put the work towards implementing the proper API instead. Otherwise we're just wasting time writing code that'll soon be replaced anyway.
> 
> If there's no time to do a proper implementation right now, I'm OK with delaying it.

It is a bug and needs to be fixed. It is not much work. The main work is to fix clients and seems to be not so much.



> When you return a byte array - host should know endianness, do pointer arithmetic or other nasty stuff.
> Probably better to offload it and return two clean and obvious values. But you might want to profile it.

Kernel returns byte array with header, what CRUD API will do is to move pointer from pointing to header to pointing to the value and will return length separately. Will it be sufficient to the client? This is almost what happens now, the only difference is static cast to string and setting terminating zero.

**Comment by bigwad** [comment]
>Kernel returns byte array with header, what CRUD API will do is to move pointer from pointing to header to pointing to the value and will return length separately. Will it be sufficient to the client? This is almost what happens now, the only difference is static cast to string and setting terminating zero.

Right. That's all I'm asking for. Should be 10 minutes changes (both metalayer and the client) and will solve all our current issues.

**Comment by k-rus** [comment]
> Right. That's all I'm asking for. Should be 10 minutes changes (both metalayer and the client) and will solve all our current issues.

Our development environment does not allow to produce result in 10 minutes. It requires to allocate at least 1 hour due to running builds and other infrastructure and environment.

It is already planned to be done at appropriate moment without significant delays. @alexanderstc will switch when it is good moment for him. I am only worried with fixing in sc.core, which I would prefer that sc.core team does.

**Comment by linkdata** [comment]
> I am only worried with fixing in sc.core, which I would prefer that sc.core team does.

It should be a trivial change. Just update this issue when you've pushed the changes.

**Comment by alexanderstc** [comment]
> @bigwad Right. That's all I'm asking for. Should be 10 minutes changes (both metalayer and the client) and will solve all our current issues.

Nice of you to make time estimates.
And no, it won't solve the title issue (as we have two issues mixed up here).

**Comment by alexanderstc** [comment]
Well, I take it back: it'll solve the title issue as it stated - buffer overrun when accessed through the crud api - but the rest of metalayer and qp should be adjusted also not to zero-terminate kernel string buffers.

**Comment by k-rus** [comment]
> Well, I take it back: it'll solve the title issue as it is stated - buffer overrun when accessed through the crud api - but the rest of metalayer and qp should be adjusted also not to zero-terminate kernel string buffers.

Thank you for describing. It is so.

@bigwad Can you answer the question from above why it is not possible to make sure that terminating zero fits the buffer?

And another question from above: can you confirm that it is possible to use `star_context_get_binary` to read string value in encoded format?

**Comment by linkdata** [comment]
> Can you answer the question from above why it is not possible to make sure that terminating zero fits the buffer?

Not all languages use null-terminated strings. If you're writing null characters, some codehosts will have to allocate space for something that's not being used. In some cases, it may require a temporary buffer when the target datatype must be constructed with an exact size at the time it's being initialized.

In this case you're managing the memory (for now), and C# Unmanaged.LPWStr type expects it. In the final API, null terminators must not be written.

**Comment by k-rus** [comment]
> Can you answer the question from above why it is not possible to make sure that terminating zero fits the buffer?
> Not all languages use null-terminated strings. If you're writing null characters, some codehosts will have to allocate space for something that's not being used. In some cases, it may require a temporary buffer when the target datatype must be constructed with an exact size at the time it's being initialized.
> 
> In this case you're managing the memory (for now), and C# Unmanaged.LPWStr type expects it. In the final API, null terminators must not be written.

Obviously it is not long term solution. It is to fix bug now, especially if it is low hanging fruit. Solving in a way that @bigwad suggests is not so simple.

**Comment by k-rus** [comment]
> Not all languages use null-terminated strings. If you're writing null characters, some codehosts will have to allocate space for something that's not being used. In some cases, it may require a temporary buffer when the target datatype must be constructed with an exact size at the time it's being initialized.
> 
> In this case you're managing the memory (for now), and C# Unmanaged.LPWStr type expects it. In the final API, null terminators must not be written.

If null terminator is not expected, then length is expected I guess. Or?

**Comment by linkdata** [comment]
> If null terminator is not expected, then length is expected I guess. Or?

Yes, that's the `neededChars` output parameter.

This is a very old and common pattern. We are already prepared for it in TT4:

```c
int Utf16FromTurboText(uint16_t* dst, int dst_max, const char* src, size_t src_len)
```

It accepts a buffer to write to, with a given max size, and returns the size needed. If the target buffer has room for a terminating null character, it will write that. Otherwise not.

**Comment by linkdata** [comment]
I don't know the layers between codehost and TT4, but what needs to be done is forwarding the codehost buffer information to TT4 and return the needed size to codehost.

**Comment by k-rus** [comment]
> Yes, that's the neededChars output parameter.
> 
> This is a very old and common pattern. We are already prepared for it in TT4:
> 
> int Utf16FromTurboText(uint16_t* dst, int dst_max, const char* src, size_t src_len)
> It accepts a buffer to write to, with a given max size, and returns the size needed. If the target buffer has room for a terminating null character, it will write that. Otherwise not.

Thank you for clarifying!

I don't see in the list of TT API if it is possible to get the size of decoded string. Is it possible?



> I don't know the layers between codehost and TT4, but what needs to be done is forwarding the codehost buffer information to TT4 and return the needed size to codehost.

I understand this. So if it is possible to read encoded value from database, then it will be possible to call TT4 with client buffer.

By the way, since I looked into TT4 header file, I wonder why it uses type `int` as result of some functions, not `int32_t`? 

And is there actually any documentation of TT4 API? What is expected inputs and outputs?

**Comment by bigwad** [comment]
>@bigwad Can you answer the question from above why it is not possible to make sure that terminating zero fits the buffer?

I didn't say it's not possible. I thought it's not feasible. But if a lot of code in metalayer depends on it... then ok.
Actually, kernel's buffer is large enough to hold a string of maximum size plus zero terminator. It was just somewhat brave from metalayer to expect it without explicit warranty. From now on you may assume buffer is large enough. So no fix is required unless you want to improve marshaling performance returning string length in a separate parameter.

> And another question from above: can you confirm that it is possible to use star_context_get_binary to read string value in encoded format?

It's possible but impractical as you can't decode it. Kernel doesn't export decode function.

**Comment by linkdata** [comment]
> By the way, since I looked into TT4 header file, I wonder why it uses type int as result of some functions, not int32_t?

No particular reason. It's simply common to use `int` as a buffer size in many C++ libraries.

> And is there actually any documentation of TT4 API? What is expected inputs and outputs?

Sorry, no docs except the header files and the tests (`tests/tt_test.cpp`). It's pretty standard API design though, so not very hard to read.

**Comment by linkdata** [comment]
> Kernel doesn't export decode function.

But can probably do so by wrapping the relevant TT4 call.

**Comment by bigwad** [comment]
>>Kernel doesn't export decode function.

>But can probably do so by wrapping the relevant TT4 call.

Totally. Just had no reason.

**Comment by k-rus** [comment]
> @bigwad Can you answer the question from above why it is not possible to make sure that terminating zero fits the buffer?
> I didn't say it's not possible. I thought it's not feasible. But if a lot of code in metalayer depends on it... then ok.
> Actually, kernel's buffer is large enough to hold a string of maximum size plus zero terminator. It was just somewhat brave from metalayer to expect it without explicit warranty. From now on you may assume buffer is large enough. So no fix is required unless you want to improve marshaling performance returning string length in a separate parameter.

To claim that it was brave, it is really necessary to know the history. I cannot really say now, but it is very probable that it was explicitly specified that kernel's buffer is large enough. @bigwad we treated your issue as it is actually a problem.

**Comment by k-rus** [comment]
OK. So it is actually no issue, but only request to implement a CRUD API with length.

**Comment by bigwad** [comment]
> @bigwad we treated your issue as it is actually a problem.

Sorry about that, but it actually could be a major problem if I started some kernel refactoring without knowing such expectations from the metalayer. And it's better to not have such dependencies

**Comment by bigwad** [comment]
> OK. So it is actually no issue, but only request to implement a CRUD API with length.

If, as time passes, you manage to get rid of this expectation - I'll be happy to know it.
Until that time I think we may close this issue as length suggestion is covered in https://github.com/Starcounter/StarDump/issues/4

**Comment by k-rus** [comment]
> Sorry about that, but it actually could be a major problem if I started some kernel refactoring without knowing such expectations from the metalayer. And it's better to not have such dependencies

I guess it is not the only place and I agree that we need to improve to not have such dependencies.

So short term solution is length in result, and possible long term solution is client buffer.

**Comment by k-rus** [comment]
> I guess it is not the only place and I agree that we need to improve to not have such dependencies.
> 
> So short term solution is length in result, and possible long term solution is client buffer.

I added both in our todo list. @alexanderstc might fix API with length shortly if he found a good solution. It will be reported in Starcounter/StarDump#4

Archiving this one.
