### ISSUE TITLE
Broken markup response from htmlmerger

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#4013]
Hi!

Occasionally we have problems with the http response from the htmlmerger. Parts of the response html i broken.

Here is a screenshot of a broken htmlmerge response:

![screen shot 2016-12-20 at 12 10 20](https://cloud.githubusercontent.com/assets/112064/21348398/55e9fc4e-c6ad-11e6-802c-218ffb609b0e.png)

It is easy to identify what partial html file that causes the invalid html. And if I re-save that specific file the response will be ok again.

I talked to @chrhol about this and problem is probably caused by invalid cache of the file, and when I re-save the file the cache is flushed.

/Ivar

**Comment by miyconst** [comment]
@ivarbergman could you please check that all of the files in the response are in the same encoding? Otherwise it is @alemoi to answer.

**Comment by ivarbergman** [comment]
Yes all are UTF8 without BOM.

**Comment by ivarbergman** [comment]
Interestingly we have two different databases (with the same set of apps) that use the same html files. And when I accessed the same htmlmerge url for the other database/port I get no error. 

So, I doesn't seem to be related to the file content.

**Comment by ivarbergman** [comment]
fyi: we use sc version 2.2.2.3710

**Comment by miyconst** [comment]
@alemoi please follow up.

**Comment by alemoi** [comment]
@ivarbergman is it possible to reproduce this somehow? How often does it occur?

**Comment by ivarbergman** [comment]
I haven't been able to reproduce. We have observed this error approx 1 time every second month. It seems very random. I have attached a zip of the htmlmerger response (both the broken response and the correct response), if that can be of any help. 

[issue_4013.zip](https://github.com/Starcounter/Starcounter/files/665989/issue_4013.zip)

**Comment by dan31** [comment]
This is a bug. @alemoi follows up in the next 2 days, checks the file caching.

**Comment by alemoi** [comment]
@ivarbergman I dug into the code and have a question: do you see this behavior after a while for a certain file or its from the very first access to this file?

**Comment by dan31** [comment]
Ping @alemoi @ivarbergman

**Comment by chrhol** [comment]
This also happened for heads a couple of times in 2.3 (unsure about the exact version). Still no consistent way to reproduce it though. 

cc @IdieHeads

**Comment by alemoi** [comment]
For me the main question is:  do you see this behavior after a while for a certain file or its from the very first access to this file?

**Comment by IdieHeads** [comment]
This behavior occurs after a while. I has only happened for a certain file so far.

**Comment by ivarbergman** [comment]
Hi! The cache error has now happened on a server that has been running for more than 2 week. So I would also say that the problem did not happened on first file access, but rather some time later.

We have seen this error on different servers and different files.

**Comment by dan31** [comment]
Several customers face the issue with 2.3 RC. It needs to be investigated and fixed.

**Comment by alemoi** [comment]
I have investigated the issue and one possible reason is gzipping of partials. Starting from version 2.3.0.5753 one can set environment variable `SC_SHOULD_GZIP`  to `False`
(you would need to restart your computer after setting it)

You can see if the problem occurs again.

**Comment by chrhol** [comment]
@alemoi, does this have anything to do with #5?

**Comment by alemoi** [comment]
> @alemoi, does this have anything to do with #5?

@chrhol now, after this seems to be confirmed as a gzipping issue, I think these are very related.
I would like to discuss if its ok to drop gzipping completely, and serve all static files as is. Would need some input from customers about this.
In future we will anyway replace current static Web server.

**Comment by alemoi** [comment]
Gzipping is now completely disabled in static file caching. We will reopen the issue if some problems occur with it.
