### ISSUE TITLE
Multicore scaling of transactions

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#4020]
Consider a problem of using a multicore machine to crunch data with starcounter.

We need to wrap calculations in transaction scope if we want consistency, but as for now, starcounter transaction is limited to be executed on a one thread at a time. We may start many transactions and execute them on different threads, but then we lack consistency. Here I introduce a method of launching several transactions that share the same snapshot thus eliminating consistency problem. 

First, new class ```Starcounter.TransactionToken``` is introduced. It holds information that is required to launch a transaction that will share the same snapshot as the transaction from which we got the token.
Then token is to be passed to ```Db.TransactXXX``` to launch a new transaction. It can be used to launch as many transaction as you need and it doesn't matter if original transaction token was taken from is alive or not. Token of current transaction can be retrieved with Db.CurrentTransactionToken property. Finally, token has to be disposed and you have to dispose it as soon as you don't need it.

Here is the code sample:

```c#
TransactionToken tt = null;

try
{
                
  //transaction 1
  Db.Transact(
    //saving token
    () =>{tt = Db.CurrentTransactionToken;}
  );
       
  //here can go transaction that change data

  //transaction 2. use saved token to share the same snapshot
  Db.Transact(
    () =>{}, 
    0, new Db.Advanced.TransactOptions { source_token = tt });
  }
}
finally
{
if (tt != null)
  tt.Dispose();
}
```

Limitation. If you changed some data in transaction 1 - that data are not included in the token. You can take it like this - no matter when you retrieve a token during transaction lifetime - token always represents data state as it was at the start of transaction.

Other than being based on the same snapshot, cloned transactions are just as ordinary as others. You may modify data inside them. And they are subject to the same conflict resolution as other transactions.

Now code is available in branch duplicate_transaction for level0 and level1. I'm not sure where to merge it: to develop or to v2.3. As I understand v2.3 is frozen, but I think it could be useful to improve unload performance of stardump (https://github.com/Starcounter/StarDump/issues/4). 
Another problem is that stardump is based on starcounter.core, while I haven't integrated this API to starcouter.core yet. But I'm planning to do it soon.

So, questions. 
1. Where to merge to?
2. How do you feel about API?

@dan31, @miyconst

**Comment by linkdata** [comment]
Is this threadsafe? 

That is, how are you guaranteeing that the cloned transaction doesn't access the same underlying database scheduling context as the original transaction at the same time?

cc @eriohl

**Comment by bigwad** [comment]
> Is this threadsafe?

Yes, otherwise it would be meaningless. As I said cloned transaction is just an ordinary transaction except it borrows snapshot (not a context) from some other transaction. So it doesn't share the context with the original transaction. It has its own.

**Comment by eriohl** [comment]
> Is this threadsafe?

> That is, how are you guaranteeing that the cloned transaction doesn't access the same underlying database scheduling context as the original transaction at the same time?

> cc @eriohl

I'm not involved in this one but from what I understand it is simply a matter of assuring that multiple transactions has a snapshot of the same generation. I don't see why thread-safety then would be a problem then?

Basically then it should work like now with the only difference that the "transaction token" prevents this generation from being garbage collected and that you can specify a generation when creating a transaction.

Right? Or do the transactions share the underlying handle table or something like that?

**Comment by bigwad** [comment]
>Basically then it should work like now with the only difference that the "transaction token" prevents this generation from being garbage collected and that you can specify a generation when creating a transaction.
Right? 

exactly

>Or do the transactions share the underlying handle table or something like that?

no, they don't

**Comment by linkdata** [comment]
Cool, that should help reader speeds quite a lot.

**Comment by miyconst** [comment]
I would change the API a little bit.

Here is what I would like to do:

```cs
TransactionToken tt = Db.CreateTransactionToken();
List<Task> tasks = new List<Task>();

tasks.Add(Task.Run(() => {
    Db.Transact(() => { /* Some logic in here */ }, tt);
}));

tasks.Add(Task.Run(() => {
    Db.Transact(() => { /* Some logic in here */ }, tt);
}));

Task.WaitAll(tasks.ToArray());
tt?.Dispose();
```

**Comment by miyconst** [comment]
>Another problem is that stardump is based on starcounter.core, while I haven't integrated this API to starcouter.core yet. But I'm planning to do it soon.

Yes. This is where it is mainly needed. I can implement the `Starcounter.Core` interface if I have a description for the low level C/C++ methods. Not sure what will be faster for you, implement it in `Starcounter.Core` or provide description.

>Where to merge to?

I would like to see it in 2.3, otherwise there will be two different StarDump tools, for 2.3 and 2.4. Still, it is up to @dan31 to decide.

**Comment by linkdata** [comment]
> I would change the API a little bit.

I don't want to pollute the `Db.Transact()` (and all it's variants) API with a default parameter that will be `null` for almost all cases. I'd rather have you use `Transaction.Run()` and control it directly. Probably adding a `Transact()` or `Run()` method to `TransactionToken` would help:

```cs
using (TransactionToken tt = Db.CreateTransactionToken())
{
  List<Task> tasks = new List<Task>();

  tasks.Add(Task.Run(() => {
      tt.Transact(() => { /* Some logic in here */ });
  }));

  tasks.Add(Task.Run(() => {
      tt.Transact(() => { /* Some logic in here */ });
  }));

  Task.WaitAll(tasks.ToArray());
}
```

**Comment by miyconst** [comment]
@linkdata I like your suggestion. This will not only clear the `Db.Transact` from the default parameters, but also would make code more easy to read and understand when it is safe to make changes inside a transaction, and when it is not.

**Comment by linkdata** [comment]
Also, rather than doing
```cs
 tasks.Add(Task.Run(() => {
      tt.Transact(() => { /* Some logic in here */ });
  }));
```

what you want is

```cs
 tasks.Add(tt.TransactAsync(() => { /* Some logic in here */ }));
```

**Comment by miyconst** [comment]
>... what you want is ...

In my case there might be some code before and after `tt.Transact`, but in general you are right.

**Comment by linkdata** [comment]
No need to place `CreateTransactionToken` inside `Db`. Just use a constructor.
Side note: The name `TransactionToken` doesn't really say anything. Maybe `SnapshotTransactionFactory`?

**Comment by bigwad** [comment]
Merged as is to level1. For Starcounter.Core it's up to @linkdata
