### ISSUE TITLE
2.3: Session.Data is null inside Task.Run + Session.ScheduleTask 

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#4026]
I have the following code:

```cs
string sessionId = Session.Current.SessionId;
bool inSession = true;

System.Threading.Tasks.Task.Run(() =>
{
    while (inSession)
    {
        Starcounter.Session.ScheduleTask(sessionId, (s, id) =>
        {
            if (s == null || !page.Equals(s.Data))
            {
                inSession = false;
                return;
            }

            // Some logic in here.

            s.CalculatePatchAndPushOnWebSocket();
        }, true);
    }
});
```

The purpose of the code is to run a task in a loop as long as a page is opened. The problem is that `s.Data` is always NULL. 

I tried to execute `Starcounter.Session.ScheduleTask` outside of `System.Threading.Tasks.Task.Run` and the value was in there.

A working example is available here - [Playground](https://github.com/miyconst/Playground/blob/master/Playground/Program.cs#L116).

```
Starcounter-RC-2.3.0.5455 (Jan 2, 2017 9:19:57 PM)
```

cc @alemoi

**Comment by miyconst** [comment]
Same thing happens if I use `System.Threading.Thread` instead of `System.Threading.Tasks.Task`.

**Comment by alemoi** [comment]
Its a known issue related to .NET threads because they are not on scheduler. I suppose `s.Data` is NULL is because `Session.Current` is NULL inside a .NET routine. Just an experiment, what if you would set `Session.Current` to session saved in a variable inside a .NET task. There is some issue about this already reported.

**Comment by miyconst** [comment]
I have checked, and `Session.Current` is not NULL, while `Session.Current.Data` is null.

**Comment by chrhol** [comment]
`Session.Current.Data` is specific to each app, and the information about which app that is currently handling an request or a task is depending on `StarcounterEnvironment.AppName` being set correctly.

So if `StarcounterEnvironment.AppName` is NULL  then `Session.Current.Data` will be null. Can you check if that is the case? I dont think there is any way when having an .Net thread to know which app it's originated from.

A workaround when having these patterns is to manually specify executing app using `StarcounterEnvironment.RunWithinApplication("theAppName", () => { ... });`

**Comment by miyconst** [comment]
Yes, `StarcounterEnvironment.AppName` is null as well.

@chrhol thank you for the info, I will try to use this workaround.
