### ISSUE TITLE
I am not using Simplified.Ring* tables. How can I drop these?

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4031]

**Comment by warpech** [comment]
Hi @SenerDemiral, thanks for a good question. 

You might try setting `LoadEditionLibraries` to false in the database config. This should work for a new/empty database. More info: https://starcounter.io/guides/database/database-configuration/

But I don't think it will "drop" the already created tables. Let's wait for someone else to respond regarding that.

**Comment by per-samuelsson** [comment]
cc @alemoi, we don't have a way for that really, do we?

@SenerDemiral 

FYI, we are actively doing work redesigning "special" / "built-in" types like those in 2.4, where they will be more of opt-in than opt-out (as they have been in the past). Hope you can bare with us on that.

**Comment by SenerDemiral** [comment]
OK, thank you.
How will I follow what is going on v2.4?

**Comment by per-samuelsson** [comment]
> How will I follow what is going on v2.4?

By following the **Develop** channel over at http://downloads.starcounter.com/download. Note though that it's bleeding edge and hence we can not leave any real guarantees on how it works from day to day.

**Comment by SenerDemiral** [comment]
I mean, What is new in v2.4, what is changing?
How can I learn something like that?
For example;
In 2.2 when DB class properties changed/deleted underlying data is also deleted, but in v2.3 not.

**Comment by miyconst** [comment]
>How can I learn something like that?

We are working on a new version of starcounter.io, which is based on GitHub and will allow you to browse the documentation for different versions of Starcounter.

**Comment by SenerDemiral** [comment]
I will be waiting.

**Comment by per-samuelsson** [comment]
@SenerDemiral 

> I will be waiting.

As @miyconst point out, we are in the middle of a rather big documentation improvement. We are aware of the problem that users find it hard to see what change between versions, and what changes are breaking. We are in constant discussions about how to improve.

One approach we have been implementing the last few years is to maintain a *change log*. Then, when we make a new release, we go through that and write a blog post about it. The idea is to have more "low level" summaries in the change log, and to gather higher-level release notes / docs / blogs that summarize the important parts. [Here](https://starcounter.io/starcounter-2-2-1-release/) is an example of such a post.

For the really curious users it's also possible to browse the change log "live" as it evolves (when things actually get committed to the code base). As an example, the [develop change log](https://github.com/Starcounter/Starcounter/blob/develop/CHANGELOG.md) will always reveal stuff that are about to happen in the upcoming version. Checkout Added | Fixed | Improved | Changed sections under **Unreleased**.
