### ISSUE TITLE
Performance differences using Object and Object.ObjectNo

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4033]
Using Object
First Run: `TurnuvaChain-1 ms:62, tick:159069 Cnt:1178`
Second Run: `TurnuvaChain-1 ms:32, tick:82646 Cnt:1178`
```
var sw = Stopwatch.StartNew();
int i = 0;

var trn = (TTDB.Turnuva)DbHelper.FromID(DbHelper.Base64DecodeObjectID(ID));
var trnTkms = Db.SQL<TTDB.TurnuvaTakim>("SELECT a FROM TurnuvaTakim a WHERE a.Turnuva = ?", trn);
foreach(var trnTkm in trnTkms) {
	var TkmMsbs = Db.SQL<TTDB.Musabaka>("SELECT a FROM Musabaka a WHERE a.Turnuva = ? and (a.HomeTakim = ? OR a.GuestTakim = ?)", trn, trnTkm.Takim, trnTkm.Takim);
	foreach(var tkmMsb in TkmMsbs) {
		var MsbMacs = Db.SQL<TTDB.Mac>("SELECT a FROM Mac a WHERE a.Musabaka = ?", tkmMsb);
		foreach(var msbMac in MsbMacs) {
			var MacSncs = Db.SQL<TTDB.MacSonuc>("SELECT a FROM MacSonuc a WHERE a.Mac = ?", msbMac);
			foreach(var macSnc in MacSncs) {
				i++;
			}
		}
	}
}
Console.WriteLine(string.Format("TurnuvaChain-1 ms:{0}, tick:{1} Cnt:{2}", sw.ElapsedMilliseconds, sw.ElapsedTicks, i));
```
Using Object.ObjectNo
First Run: `TurnuvaChain-2 ms:300, tick:761890 Cnt:1178`
Second Run: `TurnuvaChain-2 ms:287, tick:727758 Cnt:1178`
```
sw = Stopwatch.StartNew();
i = 0;
trn = (TTDB.Turnuva)DbHelper.FromID(DbHelper.Base64DecodeObjectID(ID));
trnTkms = Db.SQL<TTDB.TurnuvaTakim>("SELECT a FROM TurnuvaTakim a WHERE a.Turnuva.ObjectNo = ?", trn.GetObjectNo());
foreach(var trnTkm in trnTkms) {
	var TkmMsbs = Db.SQL<TTDB.Musabaka>("SELECT a FROM Musabaka a WHERE a.Turnuva.ObjectNo = ? and (a.HomeTakim.ObjectNo = ? OR a.GuestTakim.ObjectNo = ?)", trn.GetObjectNo(), trnTkm.Takim.GetObjectNo(), trnTkm.Takim.GetObjectNo());
	foreach(var tkmMsb in TkmMsbs) {
		var MsbMacs = Db.SQL<TTDB.Mac>("SELECT a FROM Mac a WHERE a.Musabaka.ObjectNo = ?", tkmMsb.GetObjectNo());
		foreach(var msbMac in MsbMacs) {
			var MacSncs = Db.SQL<TTDB.MacSonuc>("SELECT a FROM MacSonuc a WHERE a.Mac.ObjectNo = ?", msbMac.GetObjectNo());
			foreach(var macSnc in MacSncs) {
				i++;
			}
		}
	}
}
Console.WriteLine(string.Format("TurnuvaChain-2 ms:{0}, tick:{1} Cnt:{2}", sw.ElapsedMilliseconds, sw.ElapsedTicks, i));
```
Result:
Total records : 1178

Run | Object | ObjectNo
------------ |------------ | -------------
First | 62 | 300
Second | 32 | 287

**Comment by SenerDemiral** [comment]
If all relation fields indexed, there is no difference between Object and Object.ObjectNo.
**I didn't know Object references should/could be indexed!**

Run | Object | ObjectNo
------------ |------------ | -------------
First | 35 | 39
Second | 3 | 4

**Comment by miyconst** [comment]
I have created a very simple benchmark on my own, which is available here - [reference-vs-objectno](https://github.com/miyconst/Playground/blob/master/Playground/Program.cs#L217).

Steps to run:

- Clone the [Playground](https://github.com/miyconst/Playground) repository.
- Start the Playground app.
- Execute `http://localhost:8080/playground/insert`.
- Execute `http://localhost:8080/playground/objectno/100`

The `100` value can be changed with any numeric value, it indicates the number of `for` iterations.

**Here are my results**

Name | Result
-------|--------
Reference comparison | `00:00:01.4261098`
ObjectNo comparison | `00:00:12.8882374`
ObjectNo comparison with `GetObjectNo()` | `00:00:12.9868586`

This means that reference comparison in SQL is about 10 times faster.

---------------

@SenerDemiral very big thank you for sharing the info and digging into Starcounter, but could I ask you to:

- Do not use foreign language names in the code shared. For me it is very difficult to follow up the code logic with `Musabaka`, `TurnuvaTakim`, `Turnuva` and other names like this. I am sorry, I don't know your language (yet).
- Write the description in more clear way. For example `First Run`, `Second Run`, or `TurnuvaChain-2` requires to read the code to understand what you are comparing.
- Add code highlight to the code snippets, it will be much easier to read. You can add it by defining the language in the code snippet. Like this: ` ```cs ` - for C#, ` ```js ` - for JavaScript, ` ```html ` - for HTML, and so on.
- Write a minimal Starcounter app and share it via GitHub instead of sharing code snippets of your close-source app. The database classes of your app is not available, and the logic is very often contains lots of redundant parts, which are not related to the issue.

**Comment by SenerDemiral** [comment]
Thank you.
I will try to apply your suggestions.

Do I need to index object references?
I think yes, because 100 iteration took 1sec! (10ms/iteration)
My OldSQL Firebird DB makes 100,000 iteration in 600ms

If Starcounter is in-memory DataBase, means object references are memory address,
Why we need to index on object reference to speed up execution?

**Comment by miyconst** [comment]
>My OldSQL Firebird DB makes 100,000 iteration in 600ms

I bet you didn't look at the Playground solution. If you would, you would see that it not only makes an iteration over a reference, but also:

- Concatenates a string to produce an SQL query.
- Creates a list of objects by calling `.ToList()`.

Also there is no statement of how many objects my database has, so it is not possible to compare with old Firebird database with another unknown number of objects.

The values I provide can be compared between each other only, because everything else except the comparison algorithm is the same.

>If Starcounter is in-memory DataBase, means object references are memory address,
Why we need to index on object reference to speed up execution?

Memory address is a value, and you are performing a comparison for this value. As any other database column, it is faster to perform comparison on top of an indexed column.

Whether you need an index or not, can be decided in scope of your application, means how often you perform this comparison.

**Comment by SenerDemiral** [comment]
Your bet is partially correct.
I didn't see `.ToList()`
I prepare another `dynamic` SQL, two table joined with Primary Key in DB procedure. 
Reads ~743K recods in 3s 650ms. (100 iteration)
(Single table without join takes 2sec)
Result Lists size is 81K in one iteration.
```
  HspNo1 = '''120.''';

  while (i < 100) do
  begin
    ES = 'select list( HspNo || Trh)'||
         '  from AVD'||
         ' where HspNo starting '||HspNo1||
         '    and (select Drm from AVB where AVBid = AVD.AVBid) <> ''A''';

    execute statement es
       into :Lists;

    i = i+1;
  end
```

**Comment by miyconst** [comment]
>I prepare another `dynamic` SQL, two table joined with Primary Key in DB procedure.

Sorry, I have lost the point. Do you have exactly the same database in Starcounter, doing the same thing and it is slower or something else?

**Comment by SenerDemiral** [comment]
Never mind!
I try to compare `old Firebird` with `new Starcounter`.

**Comment by miyconst** [comment]
>I try to compare `old Firebird` with `new Starcounter`.

Yeah, please do so. It would be really nice to see the numbers. I can help you setup the identical testing environment if needed.

**Comment by SenerDemiral** [comment]
Yes, please give the test data and structure to simulate in Firebird.

**Comment by miyconst** [comment]
Please perform a clean test with just a couple of tables and the same data. The database I tried with is very old and dirty with not related data, so it would be difficult to get the same conditions.

**Comment by SenerDemiral** [comment]
I can access Firebird and Starcount DBs in console application.
I think Conversion is not difficult, if you can give StarDump unload data.

**Comment by miyconst** [comment]
Okay. I will prepare some tests and share with you, not at the moment though.

**Comment by miyconst** [comment]
@SenerDemiral here you go - [StarcounterReferenceBenchamrk](https://github.com/miyconst/StarcounterReferenceBenchamrk/).

Please look at the code and implement the same thing in the old Firebird database. Let me know if you need any help.

The database dump is available in the root of the repository.

**Comment by SenerDemiral** [comment]
OK,
I will check it out ASAP.

**Comment by SenerDemiral** [comment]
Preliminary results [https://github.com/miyconst/StarcounterReferenceBenchamrk/issues/1](url)

**Comment by miyconst** [comment]
Thanks. Let's leave this issue, since it is too long and already closed. Keep discussion in the referenced issue.
