### ISSUE TITLE
OnData() callback is in some cases called after bound properties are called.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#4035]
When having a bound array in TypedJSON, the `OnData` callback is sometimes called too late, after bound properties are called. This might lead to functionality depending on the callback to produce inconstistent results.

This seems to happen when a json is stateful (i.e. is connected to a session and has additional state for keeping track of changes) and the array or item in the array is not accessed before being serialized, leading to the sent json being incorrect.

The behaviour is reproduced in a unittest (will link the actual test to this issue once it's ready)

Should probably be fixed in `v2.3` (aka `RC`) as well as `develop`.

cc @careri

**Comment by careri** [comment]
Nice that you managed to reproduced. Tell me when it's fixed.
I got round the problem by making sure my cached value is initiated in each called to the properties.

**Comment by chrhol** [comment]
I have a fix ready, just wanted to run some more tests (or let the buildserver run some more tests :)) before pushing it.

Unless something fails, I will push it later today.

**Comment by chrhol** [comment]
Pushed to 2.3 and 2.4 (RC and develop) now. 

A version with this fix included should be available tomorrow. I will keep the issue open until you have had a chance to try it out.

**Comment by careri** [comment]
It's on my TODO-list. I'll get back to you once tested

**Comment by careri** [comment]
It seems to be working, you can close this.

**Comment by chrhol** [comment]
> It seems to be working, you can close this.

Thanks for testing it out! Closing.
