### ISSUE TITLE
sccode.exe memory usage

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#4036]
Hi! We are running 10+ applications for each sc database on our servers. And each sccode.exe process uses approx 700 MB of RAM (Working set RAM). We are trying to identify if we can reduce this memory footprint.

The exe/dll/pdb's for each app is about 10-15 MB.

Question: What is actually kept in memory by the sccode.exe process. Are static files/auto generated files cached by this process?

**Comment by miyconst** [comment]
@alemoi please correct me if I am wrong, but as far as I know, everything what is inside the resource folder is cached into ram.

**Comment by alemoi** [comment]
> @alemoi please correct me if I am wrong, but as far as I know, everything what is inside the resource folder is cached into ram.

Upon first usage though. So if static resources are not used - memory should not be eaten. There are a lot of other reasons why memory can be eaten. I remember @dan31 wanted us to investigate this problem, related to Administrator also.

**Comment by per-samuelsson** [comment]
> Question: What is actually kept in memory by the sccode.exe process. Are static files/auto generated files cached by this process?

We also have data in there. We still map shared memory into the host process, although it's not as hungry as it used to be. It's kind of the idea with the VMDBMS.

@eriohl, maybe you can expand on that further, and/or correct me if I'm wrong?

**Comment by eriohl** [comment]
> > Question: What is actually kept in memory by the sccode.exe process. Are static files/auto generated files cached by this process?

> We also have data in there. We still map shared memory into the host process, although it's not as hungry as it used to be. It's kind of the idea with the VMDBMS.

> @eriohl, maybe you can expand on that further, and/or correct me if I'm wrong?

Yes: Storage memory is mapped into the host process. If this is the total working set it will include storage memory as well. If it is the private working set then not. If you check the shared working set this is usually mostly storage memory.

**Comment by per-samuelsson** [comment]
@ivarbergman, you consider your question answered?

**Comment by per-samuelsson** [comment]
> @ivarbergman, you consider your question answered?

Didn't get any answer on that. Closing this. @ivarbergman, just let us know if you want to reopen it and extend the discussion.
