### ISSUE TITLE
Load clang++ from the calling DLL's path

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#4042]
Currently, we require that our special build of clang++ is in the PATH, and is also the first such executable in the PATH. This is not needed. Simply load it using the calling DLL's location directly. Getting the calling DLL path (as opposed to the calling executable file) is done so:

```c
// Doing it this way to avoid "include <windows.h>"
typedef struct _IMAGE_DOS_HEADER
{
     uint16_t e_magic; // WORD
     uint16_t e_cblp;
     uint16_t e_cp;
     uint16_t e_crlc;
     uint16_t e_cparhdr;
     uint16_t e_minalloc;
     uint16_t e_maxalloc;
     uint16_t e_ss;
     uint16_t e_sp;
     uint16_t e_csum;
     uint16_t e_ip;
     uint16_t e_cs;
     uint16_t e_lfarlc;
     uint16_t e_ovno;
     uint16_t e_res[4];
     uint16_t e_oemid;
     uint16_t e_oeminfo;
     uint16_t e_res2[10];
     int32_t e_lfanew; // LONG
} IMAGE_DOS_HEADER, *PIMAGE_DOS_HEADER;
extern "C" IMAGE_DOS_HEADER __ImageBase;
```

...

```c
  wchar_t our_dll_path[MAX_PATH] = {0};
  GetModuleFileNameW((HINSTANCE)&__ImageBase, our_dll_path, _countof(our_dll_path));
```

**Comment by bigwad** [comment]
Wouldn't it be better to use documented [GetModuleHandleEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683200(v=vs.85).aspx) with GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS parameter?

**Comment by linkdata** [comment]
For Linux,  [`dladdr`](http://man7.org/linux/man-pages/man3/dladdr.3.html) seems like a good place to start looking.

**Comment by linkdata** [comment]
> Wouldn't it be better to use documented GetModuleHandleEx with GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS parameter?

Documented is always to be preferred over undocumented. Please provide patches to the branch `issue/920`.

**Comment by linkdata** [comment]
@alemoi 

The Linux implementation is done and tested locally on the level1 `issue/920`, but you'll probably want to tweak the CMakeLists.txt back so it matches your path preferences. 

Yeah, the branch is named 920 because I misread this issue number. Should have been 4042. 😒 

I'm not going to try and upload a new version of `libscllvm.so` to the FTP simply because I don't trust that my LLVM build ended up the same as yours -- please build and test it before updating.

The Windows version should be done tonight or tomorrow.

**Comment by linkdata** [comment]
The Windows implementation is now also in place.

**Comment by linkdata** [comment]
This is now merged into develop.
