### ISSUE TITLE
Installer size, increased 20MB from Starcounter-RC-2.3.0.5465-Setup

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#4043]
Hi!

Not really a bug, but should the installer go from 95MB to 115MB from before Christmas to now?

Looks to me like you added something by mistake?

**Comment by andwah** [comment]
Can it be `Stardump` that was added?

**Comment by per-samuelsson** [comment]
> Can it be `Stardump` that was added?

This, yes. IIRC, we distribute .NET core along with it.

**Comment by dan31** [comment]
Question, @alemoi @warpech: for the installer, what packing method do we use, do we use the (really) strongest compression level? Maybe we have a low-hanging fruit here.

**Comment by warpech** [comment]
I cannot answer this, I think only @alemoi can.

**Comment by dan31** [comment]
@warpech I meant @andwah, poor keyboard.

**Comment by careri** [comment]
| This, yes. IIRC, we distribute .NET core along with it.

Do you distribute the .Net Framework needed by the database as well? If not it seems inconsistent to distrubute .Net Core.

But then I undestand the increase in size

**Comment by andwah** [comment]
> do we use the (really) strongest compression level?

Cant answer this, @alemoi may have better knowledge about it.

**Comment by alemoi** [comment]
![image](https://cloud.githubusercontent.com/assets/208134/21910427/3e199a08-d91c-11e6-8940-0f589088149a.png)

Highest available compression from .NET ZipFile.

**Comment by dan31** [comment]
@careri we distribute .net core of a particular version to make the tool completely self-sustained. This distributed .net core does not install itself, it just resides together with the application. By not doing this we would need somehow to restore the .net core by the means of installer after the installation is complete, and this we didn't want to do. @linkdata can comment more on a philosophy of .net core.

**Comment by dan31** [comment]
@alemoi thanks, I tried to re-compress the distro with 7z, not much gains are possible.

**Comment by per-samuelsson** [comment]
> @careri we distribute .net core of a particular version to make the tool completely self-sustained. This distributed .net core does not install itself, it just resides together with the application.

https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/

**Comment by linkdata** [comment]
> But then I undestand the increase in size

Ok, closing it.
