### ISSUE TITLE
The quantifier distinct is not supported!

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4046]
But in Administrator SQL is supported.

**Comment by mtornwall** [comment]
> But in Administrator SQL is supported.

Could you post the query that works in the administrator but not when using `Db.SQL`? As far as I can tell, `DISTINCT` is not supported in the administrator (either).

**Comment by per-samuelsson** [comment]
IIRC, we don't support `DISTICT` at all, and never had. [Here's](https://docs.starcounter.io/guides/SQL/sql.html) the reference. As far as I can tell, we only reserve the word.

Maybe @k-rus can provide a more certain answer?

**Comment by SenerDemiral** [comment]
Yes you are right. 
Distinct is not supported.
I must have dreamed!
Sorry.
