### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bazemaze** [Starcounter/Starcounter#4049]
I've tried to install several different versions of the software but always get the same error message, see screen shot below. Also there's some problems in Visual Studio, see screen shot.
I'm using Windows 10 64x and Visual Studio Enterprise 2015 version 14.0.25424.00 Update 3. Any help is appreciated.

//Basel

![vsproblem](https://cloud.githubusercontent.com/assets/7026982/22064160/9c72351e-dd82-11e6-8ee7-743bed8e0695.png)
![starcounterproblem](https://cloud.githubusercontent.com/assets/7026982/22064254/0a13a490-dd83-11e6-89bf-af0b414fb3c5.png)

**Comment by per-samuelsson** [comment]
@bazemaze 

Thanks for reporting this. I don't remember seeing this before.

Could it be something with privileges?

**Comment by bazemaze** [comment]
I tried to run as Administrator, but the error remains...

**Comment by per-samuelsson** [comment]
> I tried to run as Administrator, but the error remains...

Can you try something for us?

Create a standard C# Console Application. Then implement an entrypoint similar to this:

```cs
void Main() {
  Environment.SetEnvironmentVariable("Foo", "Bar", EnvironmentVariableTarget.Machine);
}
```

Can you run it successfully?

**Comment by per-samuelsson** [comment]
Just FYI:

> Similarly, if target is EnvironmentVariableTarget.Machine, the environment variable is stored in the HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Session Manager\Environment key of the local computer's registry.

From https://msdn.microsoft.com/en-us/library/96xafkes(v=vs.110).aspx

**Comment by bazemaze** [comment]
Output from the console application:

 at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
   at ConsoleApplication1.Program.Main(String[] args) in C:\Projects\testStarCount\ConsoleApplication1\ConsoleApplication1\Program.cs:line 14
Press any key to continue . . .

**Comment by per-samuelsson** [comment]
> Output from the console application:

Thanks, then it's clear what fails, but I can't really tell why. Starcounter rely on that we can set a machine wide environment variable ([here](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.Installer/Starcounter.InstallerEngine/Components/InstallationBase.cs#L248) is the source code), and if that is not possible, we can't successfully install.

Exactly why it doesn't work on your machine, I don't know unfortunately. 😢 Let's see if anyone else can provide any insight in this matter.

**Comment by bazemaze** [comment]
Ok Per thanks for your support!

**Comment by bazemaze** [comment]
Okey I succesfully installed Starcounter on another machine now, but I still have the same problem in VS saying the KitchenSink project is incompatible with current version of VS. 

I use Windows 7 64x and VS community 2015 v14.0.25431.01 Update 3.

**Comment by per-samuelsson** [comment]
> ...

That's odd. Can you share the version of Starcounter you have installed? Try `star -v | clip` in a prompt and paste it here.

Meanwhile, I'll test that same thing on my machine. I have the same version of VS:

```
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
```

**Comment by per-samuelsson** [comment]
> Meanwhile, I'll test that same thing on my machine.

Now did that, pulled all latest bits from **master** over at `https://github.com/StarcounterSamples/KitchenSink`, opened the solution in Visual Studio and successfully built it.

I'm on Win 10 though. Also, I'm using a build of Starcounter that is built locally, quite close to our "Develop" channel (http://downloads.starcounter.com/download/Starcounter/Develop/latest). Don't know if that can have an impact.

**Comment by bazemaze** [comment]
It works now! Installed latest version of Starcounter. But I think the "problem" was something else; in VS there was this incompatible problem right, but now and also in the screen shot I shared before there was another "problem": In the solution it said "The project requires user input. Reload project for more information" So, I did just that and voila, the solution loaded.

**Comment by per-samuelsson** [comment]
> It works now!

Great. 🛩 Then I'm closing this issue. If you have other problems or questions, don't hesitate creating new issues and we'll try to help.
