### ISSUE TITLE
Question : Is there any plan to make `QueryResultRows` more accessible?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4050]
We know there are ways in C# to add functions like 
```
QueryResultRowsObject.Count
QueryResultRowsObject.Next
QueryResultRowsObject.Previous
QueryResultRowsObject.Last
```
But whenever we create a new project, we have to redo them in new Code Repository. or at least merge that code to new Repo. 
So my question is, Do you have any plan to implement these in SC so we dont have to code them again in new projects?

**Comment by miyconst** [comment]
@atifwaqar could you please explain why you need those?

>QueryResultRowsObject.Count

This is already available as [Enumerable.Count](https://msdn.microsoft.com/en-us/library/bb338038(v=vs.100).aspx).

>QueryResultRowsObject.Last

Same thing - [Enumerable.Last](https://msdn.microsoft.com/en-us/library/bb358775(v=vs.110).aspx).
