### ISSUE TITLE
Invalid result when query have "Name = ?" in query

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4054]
SC Version : 2.2.2.3511
I think I have reported this issue before, may be its fixed in latest versions of SC.

This query with `like` works, it returns `1`
```
select count(Name) from adfenix.database.campaign where publicationowner.name like 'remax'
```

This query with `=` doesn't works, it returns `0`
```
select count(Name) from adfenix.database.campaign where publicationowner.name = 'remax'
```

**Comment by miyconst** [comment]
cc @k-rus

**Comment by k-rus** [comment]
The issue is #3447. No work on fixing it was done. I close this one as duplicate.
