### ISSUE TITLE
Make HtmlFromJsonProvider use default path if none is provided

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter#4064]
When using `HtmlFromJsonProvider`, it throws an `ArgumentOutOfRangeException` when there is no HTML document at the path specified in the JSON file. Would it be possible to have a default path where it looks for an HTML document when there is not one already provided?

The path would be `/<AppName>/<PageName>.html` 

Right now, we specify the path this exact way in every partial of all our sample apps. This change would remove that redundancy.

**Comment by warpech** [comment]
I am not sure if providing if am for or against. It would be, after all, some additional magic and we try to move away from magic.

We need to get the actual `/<AppName>/<PageName>.html` as the `Html` value on the client side.

Anyway, does anyone feel that `ArgumentOutOfRangeException` sounds weird in this case?

Related: https://github.com/Starcounter/Starcounter/issues/3252

**Comment by warpech** [comment]
Alternatively: have a Visual Studio file template that inserts the HTML file and the path to it in JSON?

**Comment by Mackiovello** [comment]
> I am not sure if I am for or against. It would be, after all, some additional magic and we try to move away from magic.

That's a fair point. Wouldn't it then be possible to provide an overload to `HtmlFromJsonProvider` to allow this extra magic without interrupting magicless usage? 

> Anyway, does anyone feel that ArgumentOutOfRangeException sounds weird in this case?

Yes, it does

> Alternatively: have a Visual Studio file template that inserts the HTML file and the path to it in JSON?

I don't think that's a bad solution at all. Is there any issue with integrating that into the existing template?

**Comment by warpech** [comment]
> Wouldn't it then be possible to provide an overload to `HtmlFromJsonProvider` to allow this extra magic without interrupting magicless usage? 

It is possible but then I guess the next step is that we start to use it in all samples, and it becomes as ubiquous as `new Session(SessionOptions.PatchVersioning)` that we just got rid off.

> Is there any issue with integrating that into the existing template?

We only have such templates right now:

1) JSON
2) JSON with CS
3) HTML

I guess we could add another one:

4) JSON with CS and HTML

@chrhol WDYT?

**Comment by Mackiovello** [comment]
I retract my statement on this. If anyone feels like this is needed, please reopen the issue
