### ISSUE TITLE
Starcounter.Hosting missing from installation

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#4071]
```
Starting Starcounter PERSONAL engine...
Press CTRL-C to exit.

Reading server configuration from: C:\Users\Johan\Documents\Starcounter\Personal\PERSONAL.server.config
Reading gateway configuration from: C:\Users\Johan\Documents\Starcounter\Personal\scnetworkgateway.xml

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Starcounter.Hosting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf' or one of its dependencies. The system cannot find the file specified.
   at scadminserver.scadminserver.Main(String[] args)
Error: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation.
```

I think @per-samuelsson forgot to add `Starcounter.Hosting.dll` to the whitelist.

**Comment by per-samuelsson** [comment]
> @linkdata linkdata closed this in 2265c21 a minute ago

Thanks @linkdata. I'm just in the process of verifying what things I've fucked up in user experience / installation scenarios in 2.4. This was clearly one of them 😄

**Comment by linkdata** [comment]
Found it testing the installer as part of https://github.com/Starcounter/StarDump/issues/27
In general, having the build server produce a custom installer and testing it is a good idea when messing with DLL's.

**Comment by per-samuelsson** [comment]
> In general, having the build server produce a custom installer and testing it is a good idea when messing with DLL's.

Totally agree. My bad. I was just focused running personal nightlies to make sure things worked (since I knew I had rewritten quite a lot). I should of course have tested real installation scenarios before pushing too.

**Comment by miyconst** [comment]
This does not apply to the latest 2.3 version (`Starcounter-RC-2.3.0.5627 (Jan 30, 2017 12:09:53 PM)`) which works well.

**Comment by linkdata** [comment]
Thanks for testing, @miyconst

**Comment by per-samuelsson** [comment]
> This does not apply to the latest 2.3 version

It should not affect that version, no. This whole new redesign in projects and hosting is in 2.4/Develop only. Which should be considered quite unstable ATM.
