### ISSUE TITLE
After Signing in User have to refresh the page.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4081]
After singing in the page does not update, and user have to refresh the page to see the logged in content.

**Comment by per-samuelsson** [comment]
@atifwaqar 

I guess this belong to either [SignIn](https://github.com/StarcounterPrefabs/SignIn/issues) or [UserAdmin](https://github.com/StarcounterPrefabs/UserAdmin/issues) apps, right? Can you reopen issue there?

**Comment by atifwaqar** [comment]
@per-samuelsson Yes you are right. My bad. I'll close this issue from here now.
