### ISSUE TITLE
Millions of records iteration.

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4082]
Do I have to read all the records and assign to variable to iterate?
as:
```
QueryResultRows<Game> Game = Db.SQL<Game>("SELECT g FROM Game g");
foreach(var g in Game) {
  ...
}
```
or
Are there any alternative way like sequential read one by one?
as:
```
Game.First();
do {
  ...
while(Game.Next)
```

**Comment by mtornwall** [comment]
Since `QueryResultRows<T>` implements `IEnumerable<T>`, you can get an `IEnumerator<T>` using the `GetEnumerator()` method.

I doubt this would confer any particular benefits, though, as the compiled `foreach` statement is doing exactly that in the background.

**Comment by k-rus** [comment]
`foreach` in C# is a syntactical sugaring over `IEnumerable`. The result of calling `Db.SQL` is `IEnumerable`, therefore you can use `MoveNext` and `Current`. Check C# documentation as it is nothing special for Starcounter.

**Comment by SenerDemiral** [comment]
Sorry,
You are right, I mixed up Array and IEnumerable!

**Comment by mtornwall** [comment]
No problem! Do you have any further questions on this topic? Otherwise I will close the issue.

**Comment by SenerDemiral** [comment]
No question, thank you.
