### ISSUE TITLE
Upgrade to Polymer 1.8 and WebComponents.js 0.7.24

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#4088]
I propose to do this in Starcounter 2.3 (RC) and 2.4 (develop)

@alshakero could you please test HelloWorld and KitchenSink with Polymer 1.8 and WebComponents.js 0.7.24?

Instructions how to do it are at the bottom of https://github.com/Starcounter/RebelsLounge/blob/master/platform/client-side_libraries.md#local-testing

**Comment by alshakero** [comment]
On it.

**Comment by warpech** [comment]
cc @tomalec

**Comment by alshakero** [comment]
Tested HelloWorld and KitchenSink and they work perfectly with:
```
"polymer": "Polymer/polymer#1.8.0",
"webcomponentsjs": "0.7.24"
```

**Comment by warpech** [comment]
Thanks. I will upgrade the Polymer version in Starcounter 2.3 and 2.4

**Comment by andwah** [comment]
@warpech Will that solve https://github.com/Juicy/juicy-jsoneditor/issues/12

**Comment by warpech** [comment]
No, because https://github.com/Starcounter/starcounter-debug-aid/issues/38 is not fixed.

**Comment by warpech** [comment]
TeamCity tests passed ok, merging to 2.3 and develop.

Thank you @alshakero for your tests.

**Comment by warpech** [comment]
Closing as done
