### ISSUE TITLE
Cors Issue

### ISSUE THREAD

**Issue by iliassays** [Starcounter/Starcounter#4095]
How can we enable CORS for calling handler. I want it for both global and handler level.

**Comment by miyconst** [comment]
You should use `Handle.AddOutgoingHeader` to add response headers in order to setup CORS.

**Comment by dan31** [comment]
@iliassays and guys, I want to kindly ask you for the future try your best to close the issues with questions that you have previously opened in timely manner. We do not and will not have a dedicated person who grooms and grinds issues on the main tracker, and it is quite difficult sometimes to not get lost among issues that are opened for questions and are not closed. Thanks in advance! And feel free to re-open a question if you feel it is not answered.
