### ISSUE TITLE
Question : Is there any builtin way to time stamp each object on Create and Update?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4099]
One option in my mind is through CommitHooks, but that will be too expensive operation. considering if we have to keep time stamps of each and every object.

**Comment by per-samuelsson** [comment]
No, there is not I'm afraid. Time-stamping every update of every object seem like a questionable thing to do in general, considering performance.

One pattern that could be used to time-stamp all objects when inserted would be to have a common baseclass:

```csharp
[Database]
public abstract class BaseOfAllOtherClasses {
  public DateTime Inserted;

  public BaseOfAllOtherClasses() {
    Inserted = DateTime.Now;
  }
}

public class Foo : BaseOfAllOtherClasses {}
public class Bar : BaseOfAllOtherClasses {}
public class Etc : BaseOfAllOtherClasses {}
```

**Comment by atifwaqar** [comment]
TimeStamp on Object creation is fairly easy. Issue is when we update the Object.

**Comment by mtornwall** [comment]
@Mackiovello I think the pattern described by @per-samuelsson is cookbook material!

**Comment by Mackiovello** [comment]
> OT: @Mackiovello I think the pattern described by @per-samuelsson is cookbook material!

It is now here: https://docs.starcounter.io/cookbook/timestamp-on-object-creation/

**Comment by atifwaqar** [comment]
Thanks guys

**Comment by per-samuelsson** [comment]
> Thanks guys

Sure. If we ever get into a discussion about supporting scenario for update (not based on hooks), I'll ping you on that.

Feel free to reopen if you think issue is not answered.
