### ISSUE TITLE
Question : Is there a way to merge 2 Databases?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4101]
We have more than 1 servers, I was wondering if I can merge them all to see what will be the merged size, and how the server will behave if I run that merged DB.
There is no requirement for this, was just thinking to have a stress test with huge DB :P

**Comment by miyconst** [comment]
You can merge two database using [StarDump](https://github.com/Starcounter/StarDump) tool. Just reload dumps of two databases into a single one, but you have to make sure that the object ids are unique.

**Comment by atifwaqar** [comment]
> but you have to make sure that the object ids are unique.

@miyconst what do you mean by this? Both Dbs should not have the same ObjectId?

**Comment by miyconst** [comment]
>Both Dbs should not have the same ObjectId?

Yes. You can modify the SQL dumps manually if needed.

**Comment by atifwaqar** [comment]
Ok thats impossible to not have same ObjectId in 2 DBs of size 40GB each. 
So is there an easy way or automated way to Change ObjectIds in 1 DB? by just giving the last ObjectId of DB 1 so Db 2 can start setting ObjectIds from that Offset?

**Comment by miyconst** [comment]
Currently there is no such option, but we already have it in plans.

**Comment by atifwaqar** [comment]
@miyconst Awesome. Thanks :)

**Comment by dan31** [comment]
Nice answer from @miyconst. @atifwaqar feel free to close issues if you consider them answered ;)
