### ISSUE TITLE
Index Creation failed on having an attribute name like `_PublicationOwner`

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4102]
SC version 2.2.2.3511

Index creation failed when I have `_PublicationOwner` in the index: 
```
Failed to process query: CREATE INDEX PlayGroundCampaignStatusIndex ON AdFenix.Database.Campaign (Running, start,_PublicationOwner): Incorrect syntax. 
```

and it works fine when I remove `_PublicationOwner`. So to me it looks like I can not have an Index if I have an attribute that starts with a `_`, Am I right?

**Comment by k-rus** [comment]
I checked the source code and indeed only letters are allowed at the beginning of an identifier in `create index` statement.

**Comment by atifwaqar** [comment]
Oh noo. This is bad. :P 
And is this going to be same in 2.3 ?

**Comment by k-rus** [comment]
I will try to fix it for 2.3.

**Comment by k-rus** [comment]
Fixed and merged. Will come tonight into installer I hope.

**Comment by atifwaqar** [comment]
This is awesome news. thanks
