### ISSUE TITLE
Question : Does indexes work for queries with `like` ?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4103]
I have following Index : 
```
Starcounter.Db.SQL("CREATE INDEX PlayGroundCampaignNameIndex ON AdFenix.Database.Campaign (name,start)");
```

Should it work on following Query? 
```
Db.SQL<Int64>("select count(c) from adfenix.database.campaign c where not name like ? and start >= ?", po.Domain + "%agent%", DateTime.Today).First;
```

**Comment by miyconst** [comment]
cc @k-rus

**Comment by SenerDemiral** [comment]
It can work only  `like "abcde%"`  not `like "%abcde%"`

**Comment by atifwaqar** [comment]
@SenerDemiral In my case, the query is `like "abc%hij%"`. I think it should work the same as `like "abcde%"`.  What do you think?

**Comment by SenerDemiral** [comment]
@atifwaqar 
`like abc%hij%` means in OldSQL is:
Find  `starting with "abc"` using index and then make sequential search for `hij` part.
I mean, OldSQL use index if `like` not start with `%` .

`like "abc%hij%"` is not equals to `"abcde%"`.
But it can find `"abc12345hij52353890"` or `"abchij"`
I don't know if Starcounter follows this way.
Please look WebAdministrator page If you can read/understand Starcounter QueryPlan syntax.

**Comment by k-rus** [comment]
@SenerDemiral Thank you for answering the question!

**Comment by SenerDemiral** [comment]
Not at all!
