### ISSUE TITLE
Question : Difference between Db.SlowSQL and Db.SQL

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4105]
Is there any difference in performance for these 2 syntaxes : 
```
Db.SQL("DELETE FROM Adfenix.Database.ListingImage WHERE ClassifiedAd.ObjectId = ?", ca.ObId);
```
and 
```
Db.SlowSQL("DELETE FROM Adfenix.Database.ListingImage WHERE ClassifiedAd.ObjectId = ?", ca.ObId);
```

**Comment by k-rus** [comment]
Thank you for your question.

No, there is no difference in performance between `Db.SQL` and `Db.SlowSQL`. The only difference is that the second one allows literals in SQL queries, while the first one requires usage of parameters.

@Mackiovello Can you check if the documentation needs to reflect this information?

**Comment by atifwaqar** [comment]
@k-rus Thanks. 
And I tried to find this info in the documentation, couldn't find it.

**Comment by Mackiovello** [comment]
> No, there is no difference in performance between Db.SQL and Db.SlowSQL. The only difference is that the second one allows literals in SQL queries, while the first one requires usage of parameters.

Is that the case for all Starcounter versions from 2.1.177?

**Comment by k-rus** [comment]
> Is that the case for all Starcounter versions from 2.1.177?

Yes

**Comment by Mackiovello** [comment]
Closing the issue as the question is answered

**Comment by atifwaqar** [comment]
One more thing is there any difference in operation time? 
I'm asking cuz when `SlowSQL` give an impression that it might be slower in performance as compared to `Db.SQL`

**Comment by k-rus** [comment]
> I'm asking cuz the name SlowSQL give an impression that it might be slower in performance as compared to Db.SQL

Name `SlowSQL` is so, since it allows to run slow stuff, which is not available through `Db.SQL`.

**Comment by Mackiovello** [comment]
> Name SlowSQL is so, since it allows to run slow stuff, which is not available through Db.SQL.

What kind of "stuff"? Is there anything in addition to literals?

**Comment by k-rus** [comment]
> Name SlowSQL is so, since it allows to run slow stuff, which is not available through Db.SQL.
> What kind of "stuff"? Is there anything in addition to literals?

Not any more. Historically it was much more available only through `SlowSQL`. Actually there was a request to rename the function.

**Comment by atifwaqar** [comment]
Ok the following code gives exception : 
```
                Db.Transact(() =>
                {
                    Db.SQL("DELETE FROM AdFenix.Database.ClassifiedAd");
                });
```

Exception is : 
```
{"Failed to process query: DELETE FROM AdFenix.Database.ClassifiedAd: Incorrect syntax. "}
```

**Comment by Mackiovello** [comment]
> Not any more. Historically it was much more available only through SlowSQL. Actually there was a request to rename the function.

From the [comment](https://github.com/Starcounter/Docs/issues/20#issuecomment-283004380) by @mmnosek too, what's the actual deal with `DELETE` in SQL?

**Comment by k-rus** [comment]
`DELETE` fails if transaction becomes too large. It was easy to experience the failure in 2.2. I believe this is initial reason for not recommending.

Another problem it is not efficient. It is just sugaring around `foreach` loop.

**Comment by Mackiovello** [comment]
> DELETE fails if transaction becomes too large. It was easy to experience the failure in 2.2. I believe this is initial reason for not recommending.

Is there a better way to delete elements? 

I guess the performance would be the same as doing the following:
```cs
var collection = Db.SQL("SELECT r FROM MyTable r");
foreach (var item in collection)
{
    item.Delete();
}
```

**Comment by k-rus** [comment]
> I guess the performance would be the same as doing the following:
> 
> var collection = Db.SQL("SELECT r FROM MyTable r");
> foreach (var item in collection)
> {
>     item.Delete();
> }

Yes, it is what `DELETE` does. But in the above case, you can control the size of transaction. For example, do commit every 1000 delete.



> Is there a better way to delete elements? The only way I've seen other than using Delete() is using SlowSQL.

I believe the main problem was in 2.2. If I don't mistake the size of transaction in 2.3 and above corresponds to few gigabytes. So it should be no problem to use `DELETE FROM`. May be it is good to test.
