### ISSUE TITLE
Question : How to created Indexes for attributes that are inside another table?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4106]
My question may not make sense so here is an example. 
My tables looks like: 
```
[Database]
public class ParentTable
{
 public ChildTable ChildTable;
 public string Name;
 public DateTime Age;
}


[Database]
public class ChildTable
{
 public string Name;
 public DateTime Age;
}
```

and my query looks like : 
```
SELECT ct FROM ParentTable Where Name = ? and ChildTable.Name = ? and Age = ? and ChildTable.Age = ?
```

Now Question is, what will be the index for this query?

**Comment by k-rus** [comment]
I guess your question if we support path indexes. No, we don't support path indexes, i.e., index takes in account traversing to referenced tables. We discussed it, but it is not easy to maintain efficiently.

Indexes pay off for selective conditions. If conditions are selective on `ParentTable`, then defining indexes on it is straightforward. If you have high selectivity on `ChildTable`, then you can defined index on it. This means that it will be join between `ChildTable` and `ParentTable` on the reference column, thus you need to define index on the the reference column, `ChildTable`, in `ParentTable`, which will work well if this column is selective for the query. For exampe:

```SQL
CREATE INDEX ChildTableAge ON ChildTable (Age);
CREATE INDEX ParentTableChild ON ParentTable (ChildTable);
```

You might also think if you want to design your schema to be more suited for access patterns, but this might not hold in future.

**Comment by atifwaqar** [comment]
@k-rus you are right, My question is about path indexes. And thanks, this answers my question.
