### ISSUE TITLE
When retrieving the whole viewmodel, bound properties are accessed twice.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#4111]
When the handler to get the complete viewmodel from a client is called, each bound property is accessed twice, instead of once.

This is happening due to the fact that the dirtycheck is not executed, and serialization and checkpointing (resetting flags) are called manually, leading to that bound values are not marked as cached the first time.

This should be improved to reduce the number of accesses to bound values to one during the request.

NOTE: This only happens when the whole viewmodel is retrieved explicitly, not when patches are handled and generated later on.

**Comment by miyconst** [comment]
>NOTE: This only happens when the whole viewmodel is retrieved explicitly, not when patches are handled and generated later on.

Means it happens once when connection established?

**Comment by chrhol** [comment]
> Means it happens once when connection established?

Yes, exactly.

**Comment by chrhol** [comment]
Pushed to `v2.3` and `develop` branches now. Will be included in the next nightly build.
