### ISSUE TITLE
Registering Handlers is slow when we have traffic coming to server

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4113]
SC Version : 2.3.0.5767 (behavior is same in all versions)
CC @alemoi 

Here are 2 cases:
1. We have no traffic coming to the server. (meaning no handler is being called.)
![2017-03-02](https://cloud.githubusercontent.com/assets/4388707/23513335/eda498de-ff63-11e6-92a9-040953918ceb.png)
Here you can see, all handlers got registered in 1.01 second

2. Traffic is coming to server (Meaning, some handlers are being called, even though they are not registered yet, cuz the app is not launched yet, and handler is not registered)
![2017-03-02 1](https://cloud.githubusercontent.com/assets/4388707/23513349/f792eff8-ff63-11e6-98cf-bfa3b1d5d03e.png)
Here you can see, all handlers got registered in 634 seconds. and in this case, CPU load was like nothing, but the load on Network card is pretty high (1.5 Mbps receiving traffic)

**Comment by atifwaqar** [comment]
It seems like as soon as a handler is registered it does not wait for other handlers to get registered, and it starts accepting requests, making other handler registration slow.

There should be a way to Block Network Gateway (Stop accepting requests). When apps and their handlers are being registered. and As soon as an app and its handlers are registered, Network Gateway should start accepting requests to handlers.

**Comment by atifwaqar** [comment]
@alemoi for me It was always a problem on production servers. I never faced this issue on local machine where I never have any network load.

**Comment by bigwad** [comment]
I think it should work transparently. The reason is that apps could be started (and in future stopped) dynamically. 
Looks like some prioritization issue (probably in task queue) - serving requests gets priority over startup code. I think the good starting point is to profile and see what startup code is waiting for.

**Comment by atifwaqar** [comment]
@bigwad Do let me know if you need any details on this issue.

**Comment by alemoi** [comment]
Today I pushed the fix for 2.3 and develop. @atifwaqar would be awesome to hear your test result when you can :)

**Comment by atifwaqar** [comment]
Fix tested.
Ammazing fix. this solved a lot of things for us. You rock @alemoi :)

**Comment by dan31** [comment]
Guys, is this one related: https://github.com/Starcounter/Starcounter/issues/4027?

**Comment by atifwaqar** [comment]
Yes, it is. and I'm sorry for the duplication.

**Comment by alemoi** [comment]
@atifwaqar how is the new handlers registration speed? Any faults?

**Comment by atifwaqar** [comment]
Its very fast now. it takes less than a second now.

**Comment by alemoi** [comment]
> Its very fast now. it takes less than a second now.

Thanks! Is it also very consistent? Meaning 100%? :)

**Comment by atifwaqar** [comment]
>  Is it also very consistent? Meaning 100%? :)

That I am not sure. I have tested all servers once, and they all ran fine in first attempt. 
But I will reopen this issue if I see anything wrong :)
