### ISSUE TITLE
Enable Starcounter for VS 2017

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#4120]
The release of the subj is tomorrow!

**Comment by per-samuelsson** [comment]
Well, lets just make a plan for when I should spend time doing so, and I will. Like everything else, it's a matter of how we prioritize.

I would say we push this to 2.4, but I have a feeling that the usual not-acceptable-alarm will ring. 😄 And then 2.3 is the target I presume.

**Comment by dan31** [comment]
@per-samuelsson Actually, if we are lucky enough, doing extensions for 2017 is no difference than for 2015. Might well be very simple configuration for it to have it built and having templates included into installation too — please take a look.

For future versions of Visual Studio, we should really strive hard to implement the extension ahead of time, with emergence of first RCs. The main reason is pretty much because today no one uses previous versions — but the one directly available on download sites, which is — latest.

**Comment by per-samuelsson** [comment]
> @per-samuelsson Actually, if we are lucky enough, doing extensions for 2017 is no difference than for 2015. Might well be very simple configuration for it to have it built and having templates included into installation too — please take a look.

Yeah, it's usually somewhat compatible, but still involves work. And considering the constantly increasing workload, "just" a day or two of new work will have to be somewhat planned.

Even if everything works straight out of the box, I know from experience that this work is always 1-2 days, since it spans several components (including the installer), and all testing of that installers (in all affected versions) work as they should is manual, since there are no automatic tests to rely on.

**Comment by andwah** [comment]
> spans several components (including the installer)

I can help out with the installer gui part.

**Comment by jwillmer** [comment]
I have VS2017 on my system now. Waiting for Starcounter support :nail_care:

**Comment by per-samuelsson** [comment]
> Waiting for Starcounter support

I hear you. 😄 I'll give it a go within upcoming days. If things work out well, and @andwah will find time to surface it in the installer, we can probably have it in a release within a week.

**Comment by dan31** [comment]
This time we add it only to installer.

**Comment by per-samuelsson** [comment]
Also intend to fix #3791 as part of this.

**Comment by per-samuelsson** [comment]
@dan31 (and others),

I'm also aiming at dropping every bit of code we have to support VS versions **older** than 2015, even in 2.3 RC. After that, the only support we have left is 2015 and 2017. 

Please confirm in time before I eventually merge this one into main trunk.

**Comment by per-samuelsson** [comment]
Not as easy as one had hoped for - extension deployment model seem to have changed in 2017 and after building the extension and trying to install it manually in VS 2017, I get warned it's not compatible.

https://channel9.msdn.com/coding4fun/blog/Its-Time-to-Update-Your-VS-2017-Extension-Manifest

**Comment by per-samuelsson** [comment]
Yep, seem we are in need of doing some more stuff for sure, and I need to go deeper into all the details discussed in these pages (including comments):

http://www.visualstudioextensibility.com/2017/01/10/its-time-to-change-the-vsix-manifest-of-your-extension-to-v3-for-visual-studio-2017-compatibility/

https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/faq-2017.md#can-i-build-a-vsix-v3-with-visual-studio-2015

Guess I'm happy there's at least some documentation out there, but this is no longer a day or work I presume.

**Comment by per-samuelsson** [comment]
The whole footprint story of Visual Studio has also changed, and the installer can no longer rely on the registry to find the installed VS 2017. 

For all VS versions prior to 2017, it was possible to find the installation path via a registry detour. That's what our installer has relied on from the start. In 2017, that's no longer possible:

http://stackoverflow.com/questions/41106407/programmatically-finding-the-vs2017-installation-directory

(Yes, found out the hard way, scratching my head why we didn't find it).

**Comment by per-samuelsson** [comment]
> For all VS versions prior to 2017, it was possible to find the installation path via a registry detour. That's what our installer has relied on from the start. In 2017, that's no longer possible.

Seem to be other ways though, I guess I need to spend some time testing which one best fit our propitiatory installer: 

https://github.com/Microsoft/vsixbootstrapper
https://github.com/Microsoft/vswhere

**Comment by per-samuelsson** [comment]
Having some trouble understanding if 2017 support the [1.0 schema VSIX manifest format](https://msdn.microsoft.com/en-us/library/dd393700(v=vs.100).aspx) that we still use. 

The schema format was completely rewritten in VS 2012, now versioned [2.0](https://msdn.microsoft.com/en-us/library/hh696828(v=vs.140).aspx), but all versions up until now has supported both formats.

Think I'll better update the VS 2017 package to use the new format. This will probably get us in better shape for when we want to build Starcounter using VS 2017.

**Comment by per-samuelsson** [comment]
OK, so first step completed: I've now ran the first Starcounter application in VS 2017 after rewriting the package manifest as specified above, and installed the extension manually with the built .vsix file.

Considering the next step - extending the installer - seem to include quite some work, I propose we make that a separate issue. Then I can push what I have now, and anyone interested could start using 2017 by tomorrow doing

1: Install new 2.3 version
2. Go to %StarcounterBin% and double-click new `Starcounter.VS15.vsix`.

Only problem is I currently can't access our VPN so I can't push it for testing. If I can resolve that and push before tonight, I'll go with that plan.

**Comment by jwillmer** [comment]
Nice documentation about the problems you are facing. If you fancy a blog post about I can offer you a platform for it 🥇

**Comment by per-samuelsson** [comment]
>  If you fancy a blog post I can offer you a platform for it 🥇

Haha, appreciate it. But everything that force me to be structured and think things through make me want to dig a hole, throw myself into it and refuse to come back up again until I'm promised I don't have to anymore. 💨 👾

**Comment by per-samuelsson** [comment]
> OK, so first step completed: I've now ran the first Starcounter application in VS 2017 after rewriting the package manifest as specified above, and installed the extension manually with the built .vsix file.

Now I've ran it through a nightly build, grabbed the generated installer, and set it up that way too. Seem everything works, at least on my machine.

> Considering the next step - extending the installer - seem to include quite some work, I propose we make that a separate issue. Then I can push what I have now, and anyone interested could start using 2017 by tomorrow doing
>
> 1: Install new 2.3 version
> 2. Go to %StarcounterBin% and double-click new Starcounter.VS15.vsix.

I'm going for this. What I like about that is that while we continue work on getting everything setup for the installer, we can verify the extension in VS 2017 on different machines and maybe even among partners that are willing to review how it works.

**Comment by per-samuelsson** [comment]
First step now done, pushed and merged in https://github.com/Starcounter/Starcounter/commit/5e563807fa114fd34ce44a351a2b48026798b8b2.

With any 2.3 RC > 2.3.0.5867 it is now possible installing the extension manually:

>1: Install new 2.3 version
>2. Go to %StarcounterBin% and double-click new `Starcounter.VS15.vsix`.

Please report any weird behavior you might find if you decide to give it a try.

Next is to get it supported by the installer: #4135.
