### ISSUE TITLE
Make comparer for dataobjects overridable in TypedJSON

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#4122]
The comparer is used when bound objects are checked, for all json instances. This includes single value json  and items in arrays that are bound.

This allows apps to override default behaviour and add their own implementation where a more informed decision can be taken.

Small sample that will set a different dataobject on the current instance in the array making the item to be reused rather than create a new item. Of course, the assumption for this to work is that the instance only contains bound values. Any values stored directly on the json will be resetted.

```csharp
TObjArr someArr = ...;
TValue itemTemplate = someArr.ElementType;
itemTemplate.SetDataObjectComparer(
    (Json instance, object newDataObj) => {
        if (instance.Data != newDataObj) {
            // return false; // this would lead to a new jsoninstance being created for the array
            instance.Data = newDataObj;
       }
       return true; // no new jsoninstance is created.
    }
);


```

**Comment by chrhol** [comment]
Pushed to `v2.3` and `develop` branches. Will be included in the next nightly build.

**Comment by chrhol** [comment]
Needs to be documented somewhere...keeping it open until done.

**Comment by chrhol** [comment]
@miyconst found one more improvement that should be done. Even if the comparer returns true (meaning it considers the dataobjects to be equal) the reference on the viewmodel instance should be updated to the   new dataobject. 

This will allow the viewmodel instance being reused, without the need for any special hack, and this brings no additional cost for XSON.

I will add the (small) change so it's included in the next nightly build.

**Comment by chrhol** [comment]
Pushed to `v2.3` and `develop`

**Comment by miyconst** [comment]
>Pushed to `v2.3` and `develop`

Thanks! Now it seems to be working as it should.

**Comment by miyconst** [comment]
>Needs to be documented somewhere...keeping it open until done.

Do we have any documentation for the StrictJson declaration?
