### ISSUE TITLE
Drop table giving an error

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4123]
SC Version : 2.3.0.5828

My table is empty, we can see here
![image](https://cloud.githubusercontent.com/assets/4388707/23654120/8f490be2-032f-11e7-976f-00a9ff3f4b7b.png)

When I try to execute `drop table AdFenix.Database.AdfenixJs.BookShowingConfig`,  I get the following error : 
```
System.Exception: ScErrDropTypeNotEmpty (SCERR15006): Type cannot be dropped, since it is not empty. CLR class is loaded for the table being deleted: AdFenix.Database.AdfenixJs.BookShowingConfig
 Version: 2.3.0.5828.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR15006
```

![image](https://cloud.githubusercontent.com/assets/4388707/23654437/eb95dc9e-0330-11e7-9399-a048cecc4d8f.png)

**Comment by dan31** [comment]
CC @k-rus

**Comment by SenerDemiral** [comment]
Close Application then try again. (CLR class is loaded for the table being deleted)
Before running App delete table definition, if not it will created again!

**Comment by SenerDemiral** [comment]
If there is inheritance, Deleted parent deletes all children. (v2.4..)
For example: 
If Simplified.Ring1.Something table were deleted, all Simplified.* tables also deleted.
Because, all Simplified tables are inherited from Simplified.Ring1.Something.

**Comment by atifwaqar** [comment]
> Close Application then try again. (CLR class is loaded for the table being deleted)

Tried that. Didn't work.

**Comment by atifwaqar** [comment]
Let me give a little background on this issue. 
1. I have to change inheritance of `BookShowingConfig` from 'Concept.cs' to something else
2. So I clean (Delete data from) the table before running the code with changed inheritance.
3. After cleaning, I try to drop table. if I don't do this, my app(with changed inheritance) crashes when I run it. and on dropping table i am getting this error.

Now, important thing. 'Concept.cs' is inherited in each and every table in AdFenix code. so we cant clean concpet table

**Comment by SenerDemiral** [comment]
I tried on both version 2.3.0.5726 and 2.4.0.1213, it is working.

**Comment by atifwaqar** [comment]
Do you have access to AdFenix code repo?

**Comment by SenerDemiral** [comment]
No, I try to simulate on my tables.
Did you look Metada tables?
SELECT * FROM Starcounter.Metadata.Table m order by m.FullName

**Comment by SenerDemiral** [comment]
I'm sure you saw below document.
Docs -> Guides -> Working with Starcounter -> Database Refactoring
[https://docs.starcounter.io/guides/working-with-starcounter/database-refactoring/](url)](url)

**Comment by atifwaqar** [comment]
Aha, finally I can drop table. but a sequence is needed to do that.

1. Run all apps
2. stop app which has your target table
3. execute drop table query
4. stop DB (this is important, If I don't do this, and directly run my app, it crashes)
5. Run all apps

**Comment by dan31** [comment]
@atifwaqar was behaviour different to you in pre-2.3?

**Comment by atifwaqar** [comment]
Never noticed or tried it before.

**Comment by dan31** [comment]
@Mackiovello can you jump in and verify that what @atifwaqar point in his comment https://github.com/Starcounter/Starcounter/issues/4123#issuecomment-284758478 is deducible from https://github.com/Starcounter/Starcounter/issues/url? (my guess: it is not).

**Comment by Mackiovello** [comment]
> @Mackiovello can you jump in and verify that what @atifwaqar point in his comment https://github.com/Starcounter/Starcounter/issues/4123#issuecomment-284758478 is deducible from https://github.com/Starcounter/Starcounter/issues/url? (my guess: it is not).

The second link is broken. Could you paste it again?
