### ISSUE TITLE
View-Model is missing some data.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4132]
SC Version 2.3.0.5828

Case 1 Steps (Expected Behavior):
1. I go to `https://224.adfenix.com/adfenix/signin`
2. I login
3. In left panel, I click on `Admin Notifications` tab
4. I click on `Filter Type` dropdown list and I can see a list like following:
![image](https://cloud.githubusercontent.com/assets/4388707/23745687/6707403c-04b9-11e7-80fb-cb3225c18fdd.png)
5. I check Starcounter Debug Aid and I can see the object from my drop down list: 
![image](https://cloud.githubusercontent.com/assets/4388707/23745723/8cc80c52-04b9-11e7-817d-16c52921d6ce.png)

Case 2 Steps (Issue):
1. I directly go to 'https://224.adfenix.com/adfenix/domainconfig?AdminNotification'
2. I click on `Filter Type` dropdown list and I don't see anything in the list like following:
![image](https://cloud.githubusercontent.com/assets/4388707/23745784/d8a8e588-04b9-11e7-993d-6385245076ef.png)
3. I check Starcounter Debug Aid and I have no objects for my drop down list: 
![image](https://cloud.githubusercontent.com/assets/4388707/23745828/ffa19aa4-04b9-11e7-8c3c-6225fd6dc3d2.png)

Here is code snippet that populates `AdminNotificationTypes` : 
```
        public IEnumerable AdminNotifications_
        {
            get
            {
                if (this.AdminNotificationTypes.Count == 0)
                {
                    AdFenix.Database.AdminNotification adminNotification = null;
                    AdminNotificationTypesElementJson adminNotificationTypesElementJson = null;
                    foreach (AdFenix.Database.NotificationMessages AdminNotificationType in Enum.GetValues(typeof(AdFenix.Database.NotificationMessages)))
                    {
                        adminNotificationTypesElementJson = new AdminNotificationTypesElementJson();
                        adminNotificationTypesElementJson.Name = AdminNotificationType.ToString();
                        adminNotification = Db.SQL<AdFenix.Database.AdminNotification>("SELECT an FROM AdFenix.Database.AdminNotification an WHERE Name = ? and archive = ? fetch ?", adminNotificationTypesElementJson.Name, DisplayArchive, 1).First;
                        if (adminNotification != null)
                        {
                            this.AdminNotificationTypes.Add(adminNotificationTypesElementJson);
                        }
                    }
                }
                QueryResultRows<Database.AdminNotification> adminNotificationList = GetAdminNotifictionsPage(this, this.AdminNotificationsPageNo - 1);
                this.TotalNotificationCountPerPage = adminNotificationList.Count();
                this.AdminNotificationsPageNo = Math.Max(this.AdminNotificationsPageNo, 1);
                return adminNotificationList;
            }
        }
```

The reason for this strange population is that I don't want to query and populate `AdminNotificationTypes` everytime a JSON Patch is updated.

When I debug this page, I can see that `this.AdminNotificationTypes.Count` is never 0.

Also I important info, I am using `CurrentPage` logic, maybe it's messing with this population, but I'm not sure about this.

**Comment by chrhol** [comment]
Interesting.

There can be some peculiar behaviour when adding or removing items manually in a bound array (for example #3788) and I've never gotten around to implement a check for it. But since it looks like it's working when you don't load the whole page directy it might not be related to this issue.

I will take a look at it and see if I can understand what's happening.

**Comment by atifwaqar** [comment]
I shared the credentials on Hangout General Chat. You can log in and reproduce the issue live ;)

**Comment by chrhol** [comment]
I didn't read the snippet carefully enough it seems. I thought you added items to the bound array in it, but it's actually a different array you're adding items to.

So the problem here is when the whole page is serialized, instead of just collecting the changes, the array `AdminNotificationTypes` have already been processed and written when the `AdminNotifications_` is called. The reason it works the when you click on the menu is more by a sideeffect then anything else.

Ideally I guess it would make the most sense to put the initialization of `AdminNotificationTypes` in the constructor, since you only want to add items once. But since we currently does not allow using your own constructors that wont work 😊 

The quickest fix, in this case, is to move the declaration of `AdminNotificationTypes` in the jsonfile so that it's declared after `AdminNotifications`

So instead of this:
```javascript
"AdminNotificationTypes": [
  {
    "Name": ""
  }
],
"$AdminNotifications": { "Bind": "AdminNotifications_" },
"AdminNotifications": [
  {
    ...
  }
],
```
 it will look like this:

```javascript
"$AdminNotifications": { "Bind": "AdminNotifications_" },
"AdminNotifications": [
  {
   ...
  }
],
"AdminNotificationTypes": [
  {
    "Name": ""
  }
],
```

Let me know if this solves your problems in this issue!

**Comment by atifwaqar** [comment]
Just moving the declaration will work? I though order of declaration doesn't matter in typed JSON.

**Comment by chrhol** [comment]
> I though order of declaration doesn't matter in typed JSON.

It matters in this case, when you update one property inside the binding of another. Then the property being updated might already have been processed. It doesn't matter for anything else. 

Another workaround, that I know some people used, is to use the `OnData` callback to initialize these kind of values, and if no dataobject is used, then it can be triggered with setting it to null:

So the codebehind would look like this:
```cs
public partial class AdminNotificationJson : Json {
    protected override OnData() { 
        AdFenix.Database.AdminNotification adminNotification = null;
        AdminNotificationTypesElementJson adminNotificationTypesElementJson = null;

        this.AdminNotificationTypes.Clear();
        foreach (AdFenix.Database.NotificationMessages AdminNotificationType in Enum.GetValues(typeof(AdFenix.Database.NotificationMessages)))
        {
            adminNotificationTypesElementJson = new AdminNotificationTypesElementJson();
            adminNotificationTypesElementJson.Name = AdminNotificationType.ToString();
            adminNotification = Db.SQL<AdFenix.Database.AdminNotification>("SELECT an FROM AdFenix.Database.AdminNotification an WHERE Name = ? and archive = ? fetch ?", adminNotificationTypesElementJson.Name, DisplayArchive, 1).First;
            if (adminNotification != null)
            {
                this.AdminNotificationTypes.Add(adminNotificationTypesElementJson);
            }
        }
    } 
}
```

And when you instantiate this viewmodel (assuming that you don't already set the dataobject):
```cs
var adminNotificationJson = new AdminNotificationJson() { Data = null };
```

If you do it like this, then order wont matter, and items to the array will only get added when you set a dataobject (which is once, when you create a new instance).

**Comment by chrhol** [comment]
Did any of these workarounds work for you @atifwaqar?

**Comment by atifwaqar** [comment]
Ah, my bad, i totally forgot about this issue. 
It is fixed btw, just moving the `AdminNotificationTypes` fixed my issue. Thanks for the help @chrhol :)
