### ISSUE TITLE
The Starcounter-RC-2.3.0.5867 build has disappeared from the download page

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#4134]
@chrhol did you remove it? @andwah, @alemoi what else could be the reason?

```
Starcounter-RC-2.3.0.5867 (Mar 9, 2017 2:01:19 AM)
```

**Comment by miyconst** [comment]
The build is there once again. Why it happened to disappear? Any clues?

**Comment by andwah** [comment]
the reason can be this.
When the upload is done from TeamCity to download server it will be unpacked and then displayed in the page, then it starts to pre-build version, if that fails the version will be removed, but in the background it retrys to build it a couple of times. if that is successfull then the version is re-added to the download page list.

**Comment by chrhol** [comment]
I will close this issue as answered.
