### ISSUE TITLE
Support installing of VS 2017 extension via principal installer

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#4135]
Take off where #4120 finished. As part of that, it's possible to install the extension using a new `.vsix` file.

This next and final step is to get it all part of the installer.

**Comment by andwah** [comment]
@per-samuelsson Excellent progress. I will add the GUI Part. then i need @alemoi Help with the Installer engine.

**Comment by per-samuelsson** [comment]
> then i need @alemoi Help with the Installer engine.

That is what I'm doing right now. I'm hoping we can leave @alemoi out of it. 

If you can do the GUI once I'm done with integration in the installer engine, and maybe also take this: https://github.com/Starcounter/Starcounter/issues/3791#issuecomment-285352385, that would be great! 👍

**Comment by per-samuelsson** [comment]
From #4120:

>  I guess I need to spend some time testing which one best fit our propitiatory installer:
>
> https://github.com/Microsoft/vsixbootstrapper
> https://github.com/Microsoft/vswhere

I've now spent some time testing both out, and it turns out the former is basically the later wrapped up in a convenient tool. It seem to fit our need pretty well, and my plan now is to

1. Bring it in as part of the distribution
2. Integrate it in the installer engine

The only concern I have now really is how they've changed the behavior of the underlying `vsixinstaller.exe`. We previously invoked that with a `/q` switch to get the job done, and the same is supported in 2017, but their strategy has changed - if there is something running that the tool think is a problem (like some VS-related process), it ask the user to quit that and then **wait** for that to be done. In a quiet mode, it means waiting forever - and yes, I've tried, and it works that way.

The workaround, I guess, is that we put some new timeout in the installer, treating anything that takes more than x seconds as an error, and we quit with a message saying so (killing the vsixinstaller process first). And then, for any problems involving installing the extension, we kindly ask the user to disable installing of that component, and switch to a manual install of it. And pointing them to a guide on how to.

**Comment by per-samuelsson** [comment]
Realized our installer also need a way to say *if* 2017 is at all installed (as a prerequisite), and that is neither possible to do the way we've done in the past.

I re-reviewed tools from above, and my best option now is to include also `vswhere` for that. The way it would go is that our installer would invoke that, parse the output (via redirected output stream(s)) and judge from there. Or if `vswhere` would be extended to return an indicating exit code: https://github.com/Microsoft/vswhere/issues/35

**Comment by per-samuelsson** [comment]
In some discussion, a new proposal has been raised (issued initially by @linkdata):

1. We start offering Starcounter Visual Studio extension on the Visual Studio marketplace (so any developer having a Starcounter installation can manage it themselves).
2. We redesign the package so that we have a single VSIX for all supported versions (2015, 2017 and beyond).
3. In the installer, we present user with two options when installing: **developer**- or **production** mode. We add a descriptive text to each option, describing the effect it will have.
4. If developer mode was chosen, at the end of the installer there will be a new (pre-checked) box that will launch the Visual Studio VSIX installer engine, passing it our package, and then users can manage the installation of the extension from there, to the best of their own needs.

The main benefits of this is that we will get a more stable installation experience, since we don't have to handle all edge cases and even look for versions of Visual Studio being installed, and what not. And that users will be in much better control of what is going on, including knowing things like why Starcounter is run as a service (or why not), etc.

**Comment by miyconst** [comment]
I just have checked the extension with VS2017, works like a charm, good job @per-samuelsson.

**Comment by per-samuelsson** [comment]
Suggestion: now that we are already heading against the marketplace and there is new suggested templates in the pipeline, what about we move out project- and item-template projects and the VSIX project (building the package) to a separate repo, e.g. "Starcounter.VisualStudio"?

Then on the build server, we just bring that in and build it, so we still package the package in the distribution.

That is another step in the direction we want to go anyway (less monolithic code base).

I took a look, and all those projects depend on nothing to build. To run, they will need `Starcounter.VisualStudio.dll`, and that one has a lot of dependencies to our tooling and runtime, so we keep that in for now.

**Comment by k-rus** [comment]
Changes to repo structure should take in account our need as developers of Starcounter. It should not make our development and testing more difficult than now. So if the proposed change will not add any additional steps to current workflow or requirements for network connectivity, then I am completely for. If this step means that it will be more dependencies on build server, additional repo to check out, additional manual build step, etc, then I am against as our development is already not so great, and making it worse is not really acceptable.

**Comment by per-samuelsson** [comment]
@k-rus 

> If this step means that it will be more dependencies on build server, additional repo to check out, additional manual build step, etc, then I am against as our development is already not so great, and making it worse is not really acceptable.

IMO, not everything is that black or white.

There are probably some benefits to have everything monolithic, but cons too, and vice versa. 

For me, its about learning to think and work a bit differently. I'm sure when you do your daily work, you rarely will need to do any kind of maintenance regarding the Visual Studio integration. On the extreme - running kernel tests should obviously have no dependency whatsoever on development assist tools.

As for the build server, it will need to pull in code from another repository, yes. But I'll set that up and you won't ever need to do anything with that. Also: that is the direction we have decided to go, inevitably.

The only thing that will change for us is that when you do a local build and install using that `Starcounter-Setup.exe`, the Visual Studio extension will not be part of that. Instead, you need to install it as an extension in Visual Studio yourself, or pull the repository and build it yourself. I can provide simple instructions on that workflow, and with like 99% certainty, you will need to do that only once, only repeating it (by means of hitting Update button) once a new Visual Studio version is released (a major, that is). I hope that is acceptable for you.

Worst case, I guess I could wrap the extension package up in a NuGet dito (even though it feels a bit weird) and have Level1.sln depend on that. That way, even a local build / install would offer you to install the extension. But I propose we do that as a step 2, if we really find the need to.

**Comment by per-samuelsson** [comment]
> Suggestion: now that we are already heading against the marketplace and there is new suggested templates in the pipeline, what about we move out project- and item-template projects and the VSIX project (building the package) to a separate repo, e.g. "Starcounter.VisualStudio"?

Done: https://github.com/Starcounter/Starcounter.VisualStudio

**Comment by per-samuelsson** [comment]
> Worst case, I guess I could wrap the extension package up in a NuGet dito (even though it feels a bit weird) and have Level1.sln depend on that. That way, even a local build / install would offer you to install the extension. But I propose we do that as a step 2, if we really find the need to.

Decided to do so straight away, meaning the experience for anyone building Starcounter ("Level1") will be principally the same - at the end of the build, `Starcounter.VS.vsix` will be part of the output.

The reason was I still need build system to somehow bring it in, and the best approach is to make that transparent, instead of making some build-system dependent thing. The approach I'm taking now is that I'm packaging the extension up in a NuGet package, and making sure that any project referencing that will get the .vsix in its configured output directory. In Level1, I'll set up some project to just reference that package, and we are done.

**Comment by per-samuelsson** [comment]
Done. Merged an pushed to 2.3 in https://github.com/Starcounter/Starcounter/commit/21849168344fbde37bae1f1253fa547c1ec7cc20.
