### ISSUE TITLE
Question : How to get current directory of a running app?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4139]
How I normally get current directory in C# apps:
`Environment.CurrentDirectory`

In Starcounter app I get:
`C:\Program Files\Starcounter`

And it makes sense why, but Expected values should be something like:
`C:\adfenix-backend\src\bin\Debug`

So is there any SC syntax that can give me the expected value?

**Comment by miyconst** [comment]
See these:

```cs
Starcounter.Application.Current.WorkingDirectory
Starcounter.Application.Current.ResourceDirectories
```

**Comment by per-samuelsson** [comment]
@Mackiovello. something for our docs? Working with applications? There are quite a few APIs in the Application class we could describe.

**Comment by Mackiovello** [comment]
> @Mackiovello. something for our docs? Working with applications? There are quite a few APIs in the Application class we could describe.

This should absolutely be documented. Ultimately I would like to create some kind of auto-generated documented for things where one or two lines would sufficiently describe it. See https://github.com/Starcounter/Docs/issues/32

If that's not possible I'll go ahead and document this separately
