### ISSUE TITLE
Review new installer experience

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#4141]
With #4135 pushed, the installer experience has changed quite a bit:

* There is no more option to add/remove components - only install or uninstall.
* There is no way to choose if to install the "server component" or not - it's always installed.
* At the first page, you need to make an active choice to install other "Developer" or "Production". For the former, you have the option to install the extension.

Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/2902045/23889114/afe08eaa-088b-11e7-9922-3c4ef617ee35.png)

One major *functional* change is installing/uninstalling the Visual Studio extension:

* If you choose to do so, we will launch the *standard Visual Studio extension installer* at the *end of the installation*. This one will simply take over where we finish - in a new window.
* When you uninstall, we never touch the extension - you have to uninstall it manually if you want to.

Here's the final uninstall screen:

![image](https://cloud.githubusercontent.com/assets/2902045/23888992/0d4a53ba-088b-11e7-9013-c05c2accfbc1.png)

I propose initially two improvements:

1. At the first *install* page, under **Install extension** option, we should make it clear that this will happen in a *separate application* - a new window will appear.
2. At the *uninstall* page, when I confirm the uninstall, we should explicitly tell:
    * That we are not removing your databases / any data
    * That we are not uninstalling any extension

All other feedback are highly welcome!

cc @andwah @miyconst @warpech @jwillmer @dan31 @linkdata

**Comment by per-samuelsson** [comment]
Also, @andwah, notice I have a tiny scroll to the right? 😕

**Comment by linkdata** [comment]
Should we not have `Production` pre-selected and topmost of the radio buttons?

**Comment by k-rus** [comment]
I am wonder what happens if the extension was not manually removed (will be a common case) and  installation of new Starcounter version is running. Will it replace the extension with new version?

**Comment by per-samuelsson** [comment]
> Should we not have `Production` pre-selected and topmost of the radio buttons?

@andwah? @dan31? Me personally, I'm not sure what is preferable tbh.

> I am wonder what happens if the extension was not manually removed (will be a common case) and installation of new Starcounter version is running. Will it replace the extension with new version?

No, but since last night, I'm currently implementing a check so that if you have a version of the extension that is not compatible with the installed version of Starcounter, you'll get an error when trying to build your project, advising you to adjust the version of the extension you are using. See https://github.com/Starcounter/Starcounter.VisualStudio/issues/1.

So as long as you just keep updating, say 2.3-based versions, you can safely have the extension just installed. With the benefit that you now can do an update of Starcounter without closing Visual Studio.

But when you make the switch between incompatible versions - e.g 2.3 -> 2.4, or vice versa - you will get instructed to update the version of the extension. Either by going to the marketplace, or double-clicking `%StarcounterBin%\Starcounter.VS.vsix`.

**Comment by andwah** [comment]
> notice I have a tiny scroll to the right?

Interesting, it did not pop up on my screen. but i will fix that by removing some padding/margins.

**Comment by jwillmer** [comment]
> Should we not have Production pre-selected and topmost of the radio buttons?

I think the development option is that 99% of the users like to do so I think the default is o.k.
Everyone knows that you need to know what you are doing if you like to setup a system for production so it can be expected that they read the installation and not just click it trough.

**Comment by warpech** [comment]
Installing through an upgrade from 2.3.0.5828 to 2.3.0.5943, the upgrade installer has removed the extension but not installed the new one.

When opening a project in VS I get this now:

![2017-03-14 11_47_21-greenshot](https://cloud.githubusercontent.com/assets/566463/23897049/01975ee8-08ac-11e7-9662-f30743c14b26.png)

**Comment by per-samuelsson** [comment]
> Installing through an upgrade from 2.3.0.5828 to 2.3.0.5943, the upgrade installer has removed the extension but not installed the new one.

@andwah, and idea why?

> Reinstalling Starcounter (uninstall, then install) helps.

You could have just brought it down from the market place instead: https://marketplace.visualstudio.com/items?itemName=Starcounter.StarcounterforVisualStudio

Just sayin. 😉

**Comment by andwah** [comment]
> Installing through an upgrade from 2.3.0.5828 to 2.3.0.5943, the upgrade installer has removed the extension but not installed the new one.

The old installation still uninstalls the extension and in the new installation we never install the extention on an upgrade (only in a first time installation). 

So we need to figure out a nice solution for this..

**Comment by per-samuelsson** [comment]
> The old installation still uninstalls the extension and in the new installation we never install the extention on an upgrade (only in a first time installation).

Ah, ok. That explains it.

> So we need to figure out a nice solution for this..

Any ideas on how? Can you take that?

**Comment by andwah** [comment]
> Any ideas on how? Can you take that?

Yes,  Maybe one solution can be that we check the version date of installed version. if it's the "old" installer then we will launch the extention installation on an upgrade otherwise not.

**Comment by per-samuelsson** [comment]
I've now finished all documentation work regarding everything that is new with the Visual Studio extension, including troubleshooting guides for cases where users might face problems:

* In all branches of Gitbook, there is now a guide on how to create projects without the extension (highlighting what project templates does for you). Here's the one for [2.3](https://docs.starcounter.io/v/RC/guides/working-with-starcounter/working-in-visual-studio/) (compatible with all earlier versions); here's the one for [2.4/develop](https://docs.starcounter.io/v/Develop/guides/working-with-starcounter/working-in-visual-studio/).
* On the landing page referenced in Visual Studio, when users get an error building their project, I've included a [**Version Compatibility chart** as well as a **Troubleshooting** guide](https://github.com/Starcounter/Starcounter.VisualStudio/wiki/Version-compatibility).

If anyone see something unclear, please report.

**Comment by per-samuelsson** [comment]
Seem #4163 is the only known outstanding thing left, and it has an issue of its own. Review considered done.

**Comment by per-samuelsson** [comment]
Regarding the offensive message when extension was already installed, reported by @warpech, I've filed an issue about it now, over at MS: https://connect.microsoft.com/VisualStudio/feedback/details/3130163

**Comment by warpech** [comment]
Specifically what @per-samuelsson is referring to:

After uninstalling Starcounter and installing it again with "Install Extension" checked, I get the following alert:

![2017-03-22 14_40_11-vsix installer](https://cloud.githubusercontent.com/assets/566463/24200477/78fb8b50-0f0d-11e7-948c-7cd9b24334ac.png)

**Comment by warpech** [comment]
I tried to add the comment in connect.microsoft.com, but for some reason it does not sign me in properly.
