### ISSUE TITLE
Improve Ontology mapping in docs

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#4148]
I am reading about ontology mapping in the docs and I get the concept (or I knew it) but I am missing an example. The code pieces are not enough. 

For instance I know that in our projects we are using something like this:

    UriMapping.OntologyMap("/App/partials/appicon/content/@w", typeof(EditAnnouncement).FullName);
    Handle.GET("/App/partials/appicon/content/{?}", (string objectId) => new Page(), new HandlerOptions() { SelfOnly = true }); 

but I don't see any paragraph in the docs that explains how I can map an app and make sure that always the same object (image) will be displayed - and how this works.

Side note: In the sharing screen section is a link broken. How about a process that checks for broken links?

**Comment by Mackiovello** [comment]
Thanks for the notice. I've moved the issue to the Docs repo
