### ISSUE TITLE
maximum number of uri alias

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#4152]
The network gateway has a maximum number 32 of uri alias and crashes the server if you try to add one more. Since our application suite adds 6 uri alias, this means we only can run 5 dbs on the same server. Not good...

**Comment by miyconst** [comment]
cc @alemoi

**Comment by alemoi** [comment]
Increased the maximum number of URI aliases to 128. If that would be a problem, the code should be rewritten, because its inefficient.
