### ISSUE TITLE
Web Administrator SQL is showing null value as zero. (Nullable<Int32>) v2.4.0.1263

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4155]

**Comment by miyconst** [comment]
This is a duplicate of - [Allow C# null(able) values in JSON and allow mapping C# null values to JSON omitted field](https://github.com/Starcounter/Starcounter/issues/3694).

Currently Typed JSON does not support nullable numeric data types, that is why NULLs are shown as zeroes.

**Comment by SenerDemiral** [comment]
But Nullable<DateTime> field can be shown NULL

**Comment by miyconst** [comment]
>But Nullable field can be shown NULL

Yes, it is just not implemented.

**Comment by SenerDemiral** [comment]
Nullable DateTime field already shown NULL

**Comment by miyconst** [comment]
As I already said, yes, it is possible to show `NULL` for nullable numeric values when the value is NULL, it's just not implemented yet. And this issue is a duplicate of an already existing one.

**Comment by SenerDemiral** [comment]
Thank you for your patient.
