### ISSUE TITLE
Question : Why literals are not supported in the query?

### ISSUE THREAD

**Issue by mandatorySuicide** [Starcounter/Starcounter#4160]
try
            {
                var test =
                   Db.SQL<dynamic>(
                       "select x from SCHaiHai.Chanachur x where Age >= 21");
                foreach (Chanachur queryResultRow in test)
                {
                    var name = queryResultRow.Muri.Name;
                }

            }
            catch (Exception ex) // come's here
            {                
                var msg = ex.Message;
                /*
                **Gives this exception!!!
                ScErrUnsupportLiteral (SCERR7029): Literals are not supported in the query. Method Starcounter.Db.SQL does not support queries with literals. Found literal is 21. Use variable and parameter instead.**
                Version: 2.2.1.3234.
                Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7029.
                */
            }

------------- GIVES ME EXCEPTION -------------------------------------
           `try
            {
                var test =
                   Db.SQL<Chanachur>(
                       "select x from SCHaiHai.Chanachur x where Age >= ?",21);
                foreach (Chanachur queryResultRow in test)
                {
                    var name = queryResultRow.Muri.Name;
                }

            }
            catch (Exception ex) // doesn't come here , passes nicely
            {
                var msg = ex.Message;
                /*
                Porque MR. ANDERSON Porque
                */
            }
---------------------------------- PASSES NICELY -------------------------------------

Mr questions are : 

- Why literals are not supported in the query? 
- What is your philosophy behind this? 
- I see something like NewSQL in SC 2.3. Will it support literals and give us to execute plain string query? 
- Is there any documentation about NewSQL? 
- What's the difference between SQL, SlowSQL and NewSql ?

**Comment by Mackiovello** [comment]
> Why literals are not supported in the query?

It's for performance reason. It's partly explained here: https://github.com/Starcounter/Starcounter/issues/160#issuecomment-16352787 

Keep in mind that literals are supported with `Db.SlowSQL` if there's some cases where [variables](https://docs.starcounter.io/guides/database/variables/) absolutely cannot be used, which I don't know if there are any.

> What is your philosophy behind this?

See above, it's much slower than variables.

> What's the difference between SQL, SlowSQL and NewSql ?

I don't know much about NewSql. The difference between SQL and SlowSQL is that SlowSQL supports two things that are not performance optimized: `DELETE FROM` queries, explained [here](https://docs.starcounter.io/guides/database/data-manipulation/) and literals.

**Comment by miyconst** [comment]
@Mackiovello thank you for answering the question.
