### ISSUE TITLE
Delete and create db from cmd

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#4165]
Hi!

I've managed to delete and create a dabase using staradmin. 
I'm trying to figure out a way to define the port to use for the database.
The code suggests that it should be possible, the comment at row: 20
````cs
// e.g staradmin new db foo defaulthttpuserport=80
````
https://github.com/Starcounter/Starcounter/blob/develop/src/Server/staradmin/Commands/NewDatabaseCommand.cs

But I can't figure out the correct way of passing the argument

**Comment by per-samuelsson** [comment]
> But I can't figure out the correct way of passing the argument

Some raw content that should get you going:

https://github.com/Starcounter/Starcounter/issues/3360#issuecomment-184234893

@Mackiovello, I think we need to get this thing documented, don't you?

**Comment by Mackiovello** [comment]
> @Mackiovello, I think we need to get this thing documented, don't you?

This is documented here at the bottom of the page: https://docs.starcounter.io/guides/working-with-starcounter/staradmin-cli/

**Comment by careri** [comment]
Thanks, that worked
