### ISSUE TITLE
Http/Node problem used with reverse proxy

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4166]
1: Server Database Http Port 8080 and proxy used:
Client Http.GET returns 404, But Postman returns 200.

2: Server Database Http Port 80 and proxy not used:
Client and Postman Http.GET returns 200 OK.

1:
Server Database Http Port: 8080
Server Reverse Proxies:
```
<ReverseProxies>
	<ReverseProxy>
		<DestinationIP>127.0.0.1</DestinationIP>
		<DestinationPort>8080</DestinationPort>
		<StarcounterProxyPort>80</StarcounterProxyPort>
		<MatchingHost>masatenisi.online</MatchingHost>
	</ReverseProxy>
</ReverseProxies>
```

Client:
```
Response res = Http.GET(80, "http://masatenisi.online/ttClient2");
returns: 404 Not Found (URI not found: GET /ttClient2 )
```
Postman at client:
```
GET http://masatenisi.online/ttClient2

Code:
GET /ttClient2 HTTP/1.1
Host: masatenisi.online
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache
Postman-Token: 52b8b539-4b54-1fb0-8b0e-5fbc9d8539c2

returns: 200 OK
```

**Comment by miyconst** [comment]
What is `Http.GET` in your question?

**Comment by SenerDemiral** [comment]
On Server:
```
Handle.GET("/ttClient2", () =>
{
	return "ttClient2";
});

**Comment by SenerDemiral** [comment]
Same result using Node.GET
```
Node node = new Node("masatenisi.online", 80, 600);
Response res = node.GET("/ttClient2");

**Comment by miyconst** [comment]
>1: Server Database Http Port 8080 and proxy used:
Client Http.GET returns 404, But Postman returns 200.

What is "Client" and what is "Http.GET" in this case? Sorry, I don't understand how you perform the HTTP request.

**Comment by SenerDemiral** [comment]
You are right, I am from desktop terminology about client/server.
Client is Starcounter app which collects data from OldSQL Database and 
sends to another Starcounter app to store which is Server.
There is no web client.

**Comment by miyconst** [comment]
Please show the code of you perform the HTTP GET request.

**Comment by SenerDemiral** [comment]
First trial:
Server DataBase Http Port 8282
Server Reverse Proxy used. port: 80 -> 8282 (GateWay Config updated)

Run Client from VS -> OpenClient from WebAdmin -> Visit  http://127.0.0.1:8080/Client/test
Result:
Client: URI not found: GET /server/test 
Postman: Test OK

Second trial:
Server DataBase Http Port changed to 80 from 8282
Server Reverse Proxy not used. (GateWay Config updated)

Run Client from VS -> OpenClient from WebAdmin -> Visit  http://127.0.0.1:8080/Client/test
Result:
Client: Test OK
Postman: Test OK

Client:
```
Location: 127.0.0.1
DataBase HttpPort: 8080

Program.cs
using System;
using Starcounter;
namespace Client
{
	class Program
	{
		private static Node serverNode = new Node("masatenisi.online", 80, 10);
		static void Main()
		{
			Handle.GET("/Client/test", () => {
				Response res = serverNode.GET("/server/test");
				return res.Body;
			});
		}
	}
}
```
Server:
```
Location: masatenisi.online

Program.cs
using System;
using Starcounter;
namespace Server
{
	class Program
	{
		static void Main()
		{
			Handle.GET("/Server/test", () => {
				return "Test OK";
			});
		}
	}
}
```
scnetworkgateway.xml:
```
<ReverseProxies>
	<ReverseProxy>
		<DestinationIP>127.0.0.1</DestinationIP>
		<DestinationPort>8282</DestinationPort>
		<StarcounterProxyPort>80</StarcounterProxyPort>
		<MatchingHost>masatenisi.online</MatchingHost>
	</ReverseProxy>
</ReverseProxies>
```
Postman:
```
Send:
GET http://masatenisi.online/Server/test
Code:
GET /Server/test HTTP/1.1
Host: masatenisi.online
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache
Postman-Token: 89864202-4c5d-ab9b-7901-b0edb69a162f

Result:
Status: 200 OK
Body: Test OK
```

**Comment by miyconst** [comment]
>private static Node serverNode = new Node("masatenisi.online", 80, 10);

Where does this come from? Is `Node` your own HTTP Client or? What happens inside `serverNode.GET("/server/test");`?

**Comment by SenerDemiral** [comment]
Node is remote REST server located at http://masatenisi.online listens GET request via Handle.GET("/Server/test", ..)
Server responds simply "Test OK" string.
Situation for Http.GET  and Node.GET are same.
Response res = Http.GET("http://masatenisi.online/server/test");

**Comment by SenerDemiral** [comment]
Problem occurs if Reverse proxy used.
Client SC app can't access Server's Handle.GET
But Postman used at Client side access Server's Handle.GET always (ReverseProxy or not)

**Comment by miyconst** [comment]
Okay. Please try using [System.Net.WebClient](https://msdn.microsoft.com/en-us/library/system.net.webclient(v=vs.110).aspx) and report back if the issue persists.

**Comment by SenerDemiral** [comment]
```
WebClient client = new WebClient();
Stream data = client.OpenRead("http://masatenisi.online/server/test");
StreamReader reader = new StreamReader(data);
string s = reader.ReadToEnd();
```
s: Test OK
WebClient works!

Response res = Http.GET("http://masatenisi.online/server/test"); 
returns Body as:
```
System.IO.IOException: Remote host closed the connection.
   at Starcounter.NodeTask.PerformSyncRequest() in C:\TeamCity\BuildAgent\work\sc-3893\Level1\src\Starcounter.Internal\Rest\NodeTask.cs:line 514
```

**Comment by miyconst** [comment]
@SenerDemiral it's good that `WebClient` works for you. Please use available .Net features when that is possible.

The `Http.GET` and `Starcounter.Node` are subjects to deprecate. cc @alemoi.

I am closing this question as answered.

**Comment by alemoi** [comment]
> The Http.GET and Starcounter.Node are subjects to deprecate. cc @alemoi.

That's correct. Especially Node, will mark it obsolete soon.
