### ISSUE TITLE
Exception in a get constructor of a Table Attribute

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4174]
SC Version 2.3.0.5943

![image](https://cloud.githubusercontent.com/assets/4388707/24189535/a77cd81c-0ee5-11e7-8f35-0f688b6f9f84.png)

This issue is caused be bad coding, like if I dont have a try catch in a get constructor, I will get exceptions.

**Comment by miyconst** [comment]
In this case the best thing Starcounter can do - report the exception to the code which invoked the query.
