### ISSUE TITLE
Date as SQL parameter throws an error

### ISSUE THREAD

**Issue by TakhirMamirov** [Starcounter/Starcounter#4181]
I'm trying to run an SQL passing current date as a parameter:

```cs
Db.SQL<long>("SELECT COUNT(sh) FROM StatusHistory sh WHERE sh.Created >= DATE ? AND sh.Room = ?", DateTime.Now.ToString("yyyy-MM-dd"), this).First
```

But in runtime I get the following exception:

```
ScErrSQLIncorrectSyntax (SCERR7021): Incorrect SQL syntax. Unexpected token. The error near or at position 64, near or at token: ?
In query: SELECT COUNT(sh) FROM StatusHistory sh WHERE sh.Created >= DATE ? AND sh.Room = ?
Version: 2.2.1.3234.
```

Would you mind please help me fixing it?

**Comment by warpech** [comment]
cc @k-rus

**Comment by miyconst** [comment]
The SQL query should be like this:

```cs
Db.SQL("SELECT COUNT(sh) FROM StatusHistory sh WHERE sh.Created >= ? AND sh.Room = ?", DateTime.Today, this).First;
```

**Comment by TakhirMamirov** [comment]
That worked, thank you. At the same time if I have DB class DateTime properties named "From" and "To", I can't use them in SQL since it throws and exception:

```
---> Starcounter.SqlException: ScErrSQLIncorrectSyntax (SCERR7021): Incorrect SQL syntax. Unexpected token. The error near or at position 48, near or at token: [
In query: SELECT COUNT(sh) FROM StatusHistory sh WHERE sh.[From] < ? AND sh.[To] > ? AND sh.Room = ?
```
Does Starcounter's SQL allows From/To columns naming?

**Comment by miyconst** [comment]
In Starcounter you have to escape reserved keywords with `"` (double quote).

```sql
SELECT COUNT(sh) FROM StatusHistory sh WHERE sh."From" < ? AND sh."To" > ? AND sh.Room = ?
```

**Comment by Mackiovello** [comment]
The reserved keywords are found here: https://docs.starcounter.io/guides/SQL/reserved-words/

**Comment by miyconst** [comment]
Closing the issue as answered.

**Comment by warpech** [comment]
@Mackiovello every developer at some point has a problem with unescaped keywords (when the property names are like "Order", "From", "To"). Maybe it is worth mentioning on https://docs.starcounter.io/guides/database/querying-using-sql/ page
