### ISSUE TITLE
Image App in 2.3 throws an exception

### ISSUE THREAD

**Issue by TakhirMamirov** [Starcounter/Starcounter#4186]
While in 2.2 it worked perfectly, 2.3 forces this row:

`UriMapping.OntologyMap<RoomManagementDataModel.Room>("/images/partials/concept-room/{?}");`

 to throw an exception:

`Failed to process query: select t from starcounter.metadata.table t where fullname = ?: Unknown class starcounter.metadata.table. Unknown property or alias fullname. `

Any ideas?

**Comment by alemoi** [comment]
I suppose this is a duplicate, the same issue is here: https://github.com/Starcounter/Starcounter/issues/4183#issuecomment-288744337
