### ISSUE TITLE
Upgrade from 2.2 to 2.3 requires one more step

### ISSUE THREAD

**Issue by TakhirMamirov** [Starcounter/Starcounter#4187]
I believe, this guide: https://docs.starcounter.io/guides/working-with-starcounter/migrating-from-2.2-to-2.3+/ is missing the clean up or deletion of Documents/Starcounter folder, otherwise an attempt to start Starcounter's webserver will fail.

**Comment by miyconst** [comment]
cc @Mackiovello

**Comment by Mackiovello** [comment]
Thank you for noticing! Fixed in https://github.com/Starcounter/Docs/commit/577cefffcf7765eed4c7c2c58c89a2556c84a7ac
