### ISSUE TITLE
SQL: NULLS LAST aren't supported?

### ISSUE THREAD

**Issue by TakhirMamirov** [Starcounter/Starcounter#4194]
When I sort ASC in SQL by a particular field, I would like records with NULL value in that field to appear last, but not first. While this works:

`SELECT sh FROM StatusHistory sh WHERE sh.Room = ? ORDER BY sh.\"To\"`

the following, which, probably, should do what is needed, doesn't:

`SELECT sh FROM StatusHistory sh WHERE sh.Room = ? ORDER BY sh.\"To\" NULLS LAST`

with an exception:

```
Starcounter.SqlException: ScErrSQLIncorrectSyntax (SCERR7021): Incorrect SQL syntax. Unexpected token. The error near or at position 67, near or at token: NULLS LAST
In query: SELECT sh FROM StatusHistory sh WHERE sh.Room = ? ORDER BY sh."To" NULLS LAST
Version: 2.3.0.6107.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7021.
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-4040\Level1\src\Starcounter\Query\QueryPreparation.cs:line 70
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-4040\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-4040\Level1\src\Starcounter\Mock\Db.cs:line 132
   at RoomManagementDataModel.Room.get_StatusHistory() in C:\Development\Resource-Scheduler\RoomManagementApp\RoomManagementDataModel\Room.cs:line 31
   at lambda_method(Closure , Json )
ScErrorCode=7021
ErrorMessage=Unexpected token. The error near or at position 67, near or at token: NULLS LAST
In query: SELECT sh FROM StatusHistory sh WHERE sh.Room = ? ORDER BY sh."To" NULLS LAST
Token=NULLS LAST
BeginPosition=67
EndPosition=76
Query=SELECT sh FROM StatusHistory sh WHERE sh.Room = ? ORDER BY sh."To" NULLS LAST
HResult=-2146233088
```

When I tried to slightly modify the SQL using IS NULL:

`Starcounter.SqlException: Failed to process query: SELECT sh FROM StatusHistory sh WHERE sh.Room = ? ORDER BY sh."To" IS NULL: Incorrect syntax.`

**Comment by miyconst** [comment]
The `NULL LAST` operator is not supported by Starcounter.

You can use LINQ instead:

```cs
var items = Db.SQL<StatusHistory>("SELECT sh FROM StatusHistory sh WHERE sh.Room = ?", room).OrderBy(x => x.To);
```

Replace the `.OrderBy(x => x.To)` part with any logic required.

**Comment by bigwad** [comment]
The solution with OrderBy will prevent you from using indices. I'd suggest to split a query into two queries and use 'Enumerable.Concat' (I've not checked a syntax, but I think you get the idea):

```cs
var items = Db.SQL<StatusHistory>("SELECT sh FROM StatusHistory sh WHERE sh.Room = ? AND sh.To IS NOT NULL ORDER By sh.To", room).Concat( Db.SQL<StatusHistory>("SELECT sh FROM StatusHistory sh WHERE sh.Room = ? AND sh.To IS NULL", room));
```

**Comment by miyconst** [comment]
@bigwad thank you for the clarification.

Yes. The `Where` and `OrderBy` actions executed by LINQ do not use table indexes.

Still, if the query heavily relies on an index, I would suggest to execute a single query and just slightly modify the code to properly treat the `NULL` values on top.
