### ISSUE TITLE
Static resources are either compressed or not compressed, should be both

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#5]
### Problem

`GetFileResource(Response cached, string relativeUri, Request req)` caches only either compressed or not compressed version of the static file `Response` (which depends on the first request, gzipping). Instead `Response` should store both compressed and uncompressed file inside one cached response.
### Getting an uncompressed representation causes an exception

Currently `ResolveAndPrepareFile(string relativeUri, Request request)` `GetBytes` call returns NULL for uncompressed file resources (when gzip is not accepted on the client). Which causes eventually a system exception, since `OnHttpMessageRoot(Request request)` always assumes non-nullable `result.Uncompressed`

**Comment by chrhol** [comment]
I will close this issue now, since we removed gzipping altogether.
