### ISSUE TITLE
Create a Wiki that describes how to use our Json serializer/deserializer

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#501]
Since Niklas, Jinkung, etc. they still use NewtonSoft Json.

We should probably remove Newtonsoft.Json.dll from our distribution.

**Comment by miyconst** [comment]
>We should probably remove `Newtonsoft.Json.dll` from our distribution.

Why so? As I understand it is now required for proper work of our JSON by example. Should we implement it as a NuGet dependency for our Starcounter template project?

**Comment by dan31** [comment]
@miyconst I believe @chrhol will close this issue as no longer relevant, as F# JSON parser has been recently kindly evicted by @chrhol.

**Comment by miyconst** [comment]
Ah, this is a very old issue, yes, looks like no longer relevant.

**Comment by chrhol** [comment]
Yeah an old issue, I will close this one.
