### ISSUE TITLE
Extra redundant Starcounter project templates in VS2017

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#62]
Why there are two `Starcounter Application` and `Starcounter Class Library` templates? What is the difference?

![image](https://cloud.githubusercontent.com/assets/6435556/24349580/c3bd4c5c-12df-11e7-8535-11b343cbfe2d.png)

**Comment by andwah** [comment]
I guess you may have two starcounter extentions installed (the old and the new)..

**Comment by miyconst** [comment]
Do we have the old extension for VS2017?

**Comment by andwah** [comment]
> Do we have the old extension for VS2017?

Dont think so.   

Will you check if you have multiple starcounter extentsions installed in VS2017?

**Comment by miyconst** [comment]
Yes. Seems like I have two.

![image](https://cloud.githubusercontent.com/assets/6435556/24351490/2f3ce05e-12e6-11e7-927e-78eb65ada5ca.png)

Have no idea how that happens, closing the issue.
