### ISSUE TITLE
Could Db.Transaction delegate have return value?

### ISSUE THREAD

**Issue by niklasbjorkman** [Starcounter/Starcounter#653]
Is there a reason why Db.Transaction is always a void?

It seems to generate a lot of boiler-plate code just to return something.
Ideally something like 
   
    return Db.Transaction<IEnumerable<Account>>(() => { return Db.SQL<Account>(“select a from accounta”); });

would be awesome. The IEnumerable<Account> would be inferred, and all it will take is a Transaction<T>(Func<T> func) overload.

**Comment by per-samuelsson** [comment]
@chrhol, isn't this an old duplicate of what you recently implemented? Close it if so.

**Comment by chrhol** [comment]
Nice catch! It's implemented and I will close it.
