### ISSUE TITLE
Communication between sccode.exe and scdata.exe using pipe

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#687]
Replace shared memory communication between sccode.exe and scdata.exe with pipe.

**Comment by per-samuelsson** [comment]
Made my work implementing installation ID in the admin server library a separate issue (#2663), since I'm not sure if this was the only remaining part of this issue. Will check if I can close both once its done.

**Comment by per-samuelsson** [comment]
Issue #2663 now implemented, merged and pushed to **next**, and closed as done.

Since I'm not sure if this issue is also done with that, I'll just leave it up to someone else to eventually close this. @eriohl maybe?

**Comment by eriohl** [comment]
Yes, we can probably consider this one merged now. Closing...
