### ISSUE TITLE
How C# classes map to SQL - documentation needs improvement

### ISSUE THREAD

**Issue by andthy** [Starcounter/Starcounter#700]
The documentation needs to be improved here:
https://github.com/Starcounter/Starcounter/wiki/How-C%23-classes-map-to-SQL

The sentence:
"The table Customer will contain all PrivateCustomers and all CorporateCustomers. So if there are a private customer called 'Goldman, Carl' and a corporate customer called 'Goldman Sachs' the "
is not finished. . .

**Comment by dan31** [comment]
It is now finished and it is there: http://starcounter.io/guides/database/inheritance/.
