### ISSUE TITLE
Starting database in Administrator causes SQL query tab to crash when quering data

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#711]
I have the only database Default that has data.

If I start this database directly inside Administrator and then query my class Person inside SQL query tab: `Select * from Person`
I get: `Failed to process query: Select * from Person: Unknown class Person.`

If, in comparison, I start my EXE using `star.exe` for the same database `Default` - I get all needed objects in Administrator SQL query tab.

**Comment by andwah** [comment]
The answer to this issue is what @k-rus explained.

> It is not possible to query a database if database classes are not loaded into the host process. It is necessary to start sccode with the application executable.
