### ISSUE TITLE
Introduce architecture of running Starcounter application

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#796]
When I read [Step 3 of Getting started](https://github.com/Starcounter/Starcounter/wiki/Creating-a-Hello-World-application) I meet that Starcounter personal server is mentioned. I tried to search for its definition on our wiki, but I haven't  found anything.
We should describe what is the Starcounter personal server and may be about processes too.

**Comment by Mackiovello** [comment]
Just to make sure that I'm not misunderstanding things here:

The Starcounter personal server is simply the server that is started on your local machine when a Starcounter application is started. This server is then where the application is run.

Is that correct? @k-rus

**Comment by k-rus** [comment]
> The Starcounter personal server is simply the server that is started on your local machine when a Starcounter application is started. This server is then where the application is run.
> 
> Is that correct? @k-rus

This question is not to me. I think I saw a post recently where it was described.

**Comment by per-samuelsson** [comment]
> Is that correct? @k-rus

Nah, that is not correct. I think I have written something about the architecture. Let's see if @k-rus  find it. Otherwise I can post a summary here later.

**Comment by k-rus** [comment]
> Let's see if @k-rus find it.

Don't wait, I am not searching for it. I am bad in searching on GitHub.

**Comment by per-samuelsson** [comment]
@Mackiovello 

I'll try to find time explaining a few concepts in a raw format so that you can use them to document. Meanwhile, there is some info in #2992.

**Comment by per-samuelsson** [comment]
@Mackiovello 

More ramblings: https://github.com/Starcounter/Starcounter/issues/3852

**Comment by Mackiovello** [comment]
I've included it in the [glossary](https://starcounter.io/glossary/) with the following text:

>Server is the Starcounter server (previously personal server). It is the name for the processes started by scservice.exe including the gateway and scadminserver.exe which exposes all administrative functionality as a REST API that governs all database and codehost specific process management.

**Comment by Mackiovello** [comment]
Close if it's considered satisfactory.

**Comment by Mackiovello** [comment]
Updated to:

> Server is the Starcounter server (previously personal server). It is the name of the processes started by scservice.exe, which includes the gateway and scadminserver.exe. The scadminserver.exe process exposes all administrative functionality as a REST API that governs all database and codehost specific process management.

Closes as it's considered done.

**Comment by per-samuelsson** [comment]
> Server is the Starcounter server (previously personal server). It is the name of the processes started by scservice.exe, which includes the gateway and scadminserver.exe. The scadminserver.exe process exposes all administrative functionality as a REST API that governs all database and codehost specific process management.

Well done. I like how you formulated that. *Maybe* we should also write somewhere how we differentiate _production_- and _developer_ mode, and how that effect how the server is started (session 0 or session 1). But that might be another topic.

**Comment by Mackiovello** [comment]
@per-samuelsson 
Thank you!
I don't know how important that is. If you feel like it should be included, please create an issue with some reference and assign it to me. Then I'll put it somewhere in the guide where it fits.
