### ISSUE TITLE
Create regression tests based on Client Node and PMail

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#814]
Open a session using Client side Node and force fixed session id. Run a series of deterministic http request and check all JSON (and JSON-Patch) results using exact string match.

Use PMail on the server side.

**Comment by chrhol** [comment]
Regression tests are good. However this one is really old, and the suggestion is to base the test on apps (PMail) that isn't used anymore and features that we are not using.
