### ISSUE TITLE
Tutorial clarifications and changes due to Step 8 (handler with query)

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#836]
[The step 8](https://github.com/Starcounter/Starcounter/wiki/Querying-using-SQL) contains the following code:

``` c#
   static void Main() {
      Handle.GET("/hello/{?}", (string firstName) => {
         Quote q = Db.SQL("SELECT Q FROM Quote Q WHERE Person.FirstName=?", firstName ).First;
         return "<!DOCTYPE html><link rel=\"stylesheet\" href=\"quote.css\"><title>Hello</title>" + 
                "<div id=\"Person\">" + q.Person.FullName + "<div id=\"Says\">" + q.Text + "</div>";
      });
```

The code is potentially unsafe, which brings several questions for clarifications and improvements and might require to split this issue in several.

If request contains string for which the query returns an empty result, then `NullReferenceException` will happen. Thus:
1. It is necessary to explain what happens if an exception is thrown in the application code of a handler. (it is logged and corr
2. A step, where a handler inserting data is registered, should be before this step.
3. May be check if result of the query contains the object and if not return an error in recommended way.

**Comment by dan31** [comment]
@Mackiovello for you to improve (not high prio). CC @miyconst.

**Comment by Mackiovello** [comment]
A disclaimer is added regarding security and code is simplified for comprehension and to allow to be run without needing to add additional code. It can be found [here](http://starcounter.io/guides/database/querying-using-sql/).

**Comment by dan31** [comment]
@Mackiovello cool, you killed two birds at once 👍 
```
