### ISSUE TITLE
Starcounter DLL quarantined by Avast antivirus

### ISSUE THREAD

**Issue by andthy** [Starcounter/Starcounter#925]
When I built a release or debug version with the latest source from the develop branch, right after Clang linked a DLL the antivirus software I used, Avast, silently removed the DLL.

Then, when trying to start a database I got an error that a DLL could not be loaded (missing.)

To solve the problem I uninstalled Avast.

More details here: http://www.starcounter.com/forum/showthread.php?2726-Solved-System.IO.FileNotFoundException-DLL-not-found

**Comment by andwah** [comment]
*bump*,  I you have Bitdefender installed you can not run starcounter apps (they are blocked).

**Comment by atifsheikh** [comment]
With AVG Starcounter still gives the following error, even if I add scnetworkgateway.exe to exception:
ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network
 gateway executable (scnetworkgateway.exe) unexpectedly terminated.
Version: 2.0.3023.3.

**Comment by SenerDemiral** [comment]
Only I have Windows Defender and real-time protection is off.

**Comment by atifwaqar** [comment]
I managed to run SC with my AVG antivirus active :

![image](https://cloud.githubusercontent.com/assets/4388707/18873115/22107a14-84be-11e6-8af6-e0aab77206eb.png)

I added a lot of things in AVG Exception list. let me know if you guys need that list.

**Comment by dan31** [comment]
@atifwaqar that is right! We have moved to obj files cached on disk instead of dlls. Once @alemoi implemented this solution, I believe it solves all antivirus issues ubiquitously.
