### ISSUE TITLE
Add a Download page on www.starcounter.com

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#948]
Add a new download page on www.starcounter.com/downloads
Where users may view and download versions from all channels.

The download page will present a list of historical and latest versions grouped by channel.

**Comment by Starcounter-Jack** [comment]
There is now a download page, but we still need to explain versions and platforms better.

**Comment by warpech** [comment]
There is a download page on http://starcounter.io/

There is a link to that on http://starcounter.com/

I think this issue can be closed.
