### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by rezasalehi** [Starcounter/Starcounter#983]
I think it would be good to provide facilities for setting Data constrains such as:
NOT NULL constraints
Unique (or unique key) constraints
Primary key constraints
Foreign key (or referential integrity) constraints
(Table) Check constraints
Informational constraints

**Comment by Mackiovello** [comment]
I've documented constraints [here](https://starcounter.io/guides/database/referential-integrity/) so I'll close this issue.
